### ISSUE TITLE
Scheduled backup won't work anymore after upgrade from 2.4 to 3.1

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#1000]
After the upgrade the scheduled backup won't work.The garbage collection is working fine, but no scheduled backups.
Manual backup is working fine.
This happens on all upgraded servers.
Any idea

**Comment by cvining** [comment]
This may be related to issue #901,

**Comment by omega8cc** [comment]
Yes, it is a duplicate of #901
