### ISSUE TITLE
Remove unused PHP versions

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#1002]
Is there a way to safely remove unused php versions? I only use 5.6 and 7.0 now, but the upgrade takes a very long time because of the building of older PHP versions. 
Multi install option in .barracuda.cnf has only 5.6 en 7.0.
.octopus.cnf also has no references to older PHP versions than either 5.6 or 7.0

**Comment by omega8cc** [comment]
We have a related feature request: https://github.com/omega8cc/boa/issues/801

For a quick workaround, if you have already removed not used versions from .barracuda.cnf, do something like this:

mv -f /opt/php53/bin/php /opt/php53/bin/.old.php
mv -f /opt/php54/bin/php /opt/php54/bin/.old.php
mv -f /opt/php55/bin/php /opt/php55/bin/.old.php

This will stop barracuda from rebuilding these not used versions on upgrade.
