### ISSUE TITLE
MariaDb 10.x unexpectantly stopped - ? wheezy to jessie upgrade problem?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1004]
Our dedicated server (which IS bare metal - because that's what you recommended ("dedicated box") until recently - has mariadb (10.0 series with boa 3.1.0 stable) stopped - and we don't know why. We are working to resolve the problem and will update. We can see that (this dedicated server went from _WHEEZY_TO_JESSY=YES when we upgraded to BOA 3.1.0 - this server still has mariadb -wheezy apt sources.list - is this correct or is this an error? Shouldn't it be jessie? We have changed this to Jessie and are attempting to update to jessie, in the hopes that is will allow us to restart mariadb. Mariadb was working OK until this morning - and we haven't done any updates on this server for 3 weeks! We still don't know why mariadb has stopped, but we cannot upgrade boa, because mariadb is stopped and won't start; We are testing and will inform.

Ed

**Comment by EdNett** [comment]
when we aptitude update we see:  10.0.26+maria-1~wheezy  

If we have successfully updated to Jessie via _WHEEZY_TO_JESSIE=YES, then why are we still updating mariadb in the wheezy channel?

Thanks for your help,
Ed

**Comment by EdNett** [comment]
After changing the sources list for mariadb to jessie, when I try to run a boa up-stable I receive the following error:

server1:~# tail -f /var/backups/reports/up/barracuda/160625/barracuda-up-160625-2212.log
 * Parallels guest
 * VirtualBox guest
 * VMware ESXi guest
 * Xen guest
BOA is not designed to run directly on a bare metal.
We recommend to install Linux VServer if you plan to
use BOA on a dedicated machine -- server or laptop.
Note: There are plans to support Linux VServer installation
via BOA tools: https://github.com/omega8cc/boa/issues/980
Bye

Don't you think this is a little draconian - changing the "rules" in mid-stream?

**Comment by EdNett** [comment]
We have had this problem - that mysql (mariadb 10.x) cannot find the socket ... for the last 2 upgrades.

Are you sure there is not a problem with the /var/run/mysqld  - which is empty, and which appears to be a symlink to /run/mysqld

I think mysql (or the boa update script) must be looking in the wrong place for this file. We can't get mariadb (mysql) started , and we can't figure out why it stopped working today - beofre we tried to run the boa upgrade from 3.1.0 to 3.1.1 stable.

**Comment by omega8cc** [comment]
No, we never _recommended_ bare metal and we have already explained this. We can't offer any further help for those using bare metal, I'm afraid. It is just too many unexpected problems to handle. If you add some non-standard modifications on top if it, it makes it completely impossible to offer any useful help.
