### ISSUE TITLE
Querry re remote Import

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1005]
I am not able to use remote import successfully. Can you please verify:

1) Although there is a mention of a target-source in the REMOTE.txt instructions, it is, in fact, never used in the procedures. 

2) Also, I am trying to import from a server whose db is stopped and cannot be started. Is this possible?  The errors I receive are that the remote import hostmaster server (added to the target) does not validate. The error message states: "The specified server is not an Aegir master server." I have added the remote import server as server1.example.com.

3) by source-host, I take it that you mean "server1.example.com"  and NOT "master.server1.example.com" or "o1.server1.example.com" ? The instructions are a little unclear since they refer to an instance (? o1.server1.example.com" ?) yet also refer to a FQDN. Could you please clarify this?

Thank you,

Ed

All this is being done on two boa 3.1.1 stable servers (however the source server has its db down - and that doesn't seem like it should be a problem to transfer sites)?

**Comment by omega8cc** [comment]
It should just work, if used properly, although we have not tested this in BOA-3.x, I think. We recommend `docs/MIGRATE.txt` instead. No, it will not work if something (especially db server) doesn't work on the source system.
