### ISSUE TITLE
Restart Config Server Firewall $ csf -r gives warnings

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1006]
```$ csf -r
lfd will restart csf within the next 5 seconds
*WARNING* Binary location for [SYSTEMCTL] [/usr/bin/systemctl] in /etc/csf/csf.conf is either incorrect, is not installed or is not executable
*WARNING* Missing or incorrect binary locations will break csf and lfd functionality
*WARNING* RESTRICT_SYSLOG is disabled. See SECURITY WARNING in /etc/csf/csf.conf.
$```

More here http://pastebin.com/1xYjd3b7

barracuda_log.txt / .barracuda.cnf = http://pastebin.com/2ZXv7EPZ

**Comment by omega8cc** [comment]
Can you please link the output of `boa info` command? I can't reproduce this, though.

**Comment by Juc1** [comment]
$ boa info = http://pastebin.com/q2mHtNRc (host = Digital Ocean)

Thanks...

**Comment by omega8cc** [comment]
Well, it doesn't look like you have followed the docs on screen and you have not run barracuda upgrade after rebooting it, as you should. Please reboot and run barracuda upgrade.

**Comment by Juc1** [comment]
@Omega8cc  - problem fixed, sorry and thanks...

**Comment by Helwieahmad** [comment]
what the solution for this issue? i found this issue on my server

**Comment by yaazkal** [comment]
@Helwieahmad as @omega8cc said previously:

>Well, it doesn't look like you have followed the docs on screen and you have not run barracuda upgrade after rebooting it, as you should. Please reboot and run barracuda upgrade.
