### ISSUE TITLE
Drush broken post 3.1.1

### ISSUE THREAD

**Issue by nitinsareen** [omega8cc/boa#1007]
Hi, using o1.ftp drush command ends up in below error - 

drush cc all --debug
Using the Drush script found at /opt/tools/drush/8/drush/drush.launcher using pcntl_exec
Cache HIT cid: 8.2-dev-commandfiles-0-1e9381f3bcd8614f8680f2135ad1cce6 [0.11 sec, 2.61 MB]                                                                                                [debug]
Bootstrap to phase 0. [1.61 sec, 7.17 MB]                                                                                                                                             [bootstrap]
Trying to bootstrap as far as we can. [1.64 sec, 7.17 MB]                                                                                                                                 [debug]
Drush bootstrap phase : bootstrap_drupal_root() [1.72 sec, 7.52 MB]                                                                                                                   [bootstrap]
Initialized Drupal 7.38 root directory at /data/disk/o1/static/platform/starter.v1 [1.77 sec, 7.53 MB]                                                                                [bootstrap]
Find command files for phase 1 (max=7) [1.78 sec, 5.15 MB]                                                                                                                                [debug]
Cache MISS cid: 8.2-dev-commandfiles-1-1700bc511faa45c174da2120dce6b583 [1.78 sec, 5.16 MB]                                                                                               [debug]
Cache SET cid: 8.2-dev-commandfiles-1-1700bc511faa45c174da2120dce6b583 [1.79 sec, 5.16 MB]                                                                                                [debug]
Cache MISS cid: 8.2-dev-annotationfiles-1-ef392cb31422c129705a500741b14179 [1.79 sec, 5.16 MB]                                                                                            [debug]Drush command terminated abnormally due to an unrecoverable error.                                                                                                                    [error]
Error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/data/disk/o1/static/platform/starter.v1/sites/all/drush): failed to open
dir: Permission denied' in /opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:54
Stack trace:
#0 /opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(54): RecursiveDirectoryIterator->__construct('/data/disk/o1/s...', 4096)
#1 /opt/tools/drush/8/drush/vendor/symfony/finder/Finder.php(808): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('/data/disk/o1/s...', 4096, false)
#2 /opt/tools/drush/8/drush/vendor/symfony/finder/Finder.php(681): Symfony\Component\Finder\Finder->searchInDirectory('/data/disk/o1/s...')
#3 /opt/tools/drush/8/drush/vendor/consolidation/annotated-command/src/CommandFileDiscovery.php(240): Symfony\Component\Finder\Finder->getIterator()
#4 /opt/tools/drush/8/drush/vendor/consolidation/annotated-command/src/CommandFileDiscovery. in
/opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php, line 54 [1.81 sec, 5.44 MB]

The upgrade of octopus too ended up in error - https://gist.github.com/nitinsareen/538c22774b0ae174f73386e2b058d34e

boa more info - 
https://gist.github.com/nitinsareen/5c18c74741ee64260ddc7693856a65c0

barracuda upgrade -
https://gist.github.com/nitinsareen/f3354787cd6b2bf38cba7f8d2cf538dd

Thanks for your help.

**Comment by omega8cc** [comment]
The Octopus upgrade didn't fail, and the errors are safe to ignore -- we need a separate issue for this, I think.

To fix your problem please set `_PERMISSIONS_FIX=YES`, the run `bash /var/xdrago/daily.sh`, then run `octopus up-stable 1 force`

This should fix the problem caused by recent Drush 8 version.

**Comment by nitinsareen** [comment]
Thanks for identifying the cause, I did all the 3 steps. The 3rd though finished in less than a second! 
Not sure it worked the way it was intended. 

Do I need to revert back the permissions parameter in .barracuda.cnf back to NO?

I ran drush command again and ended up with the same error - 

o1.ftp:[starterv1.o1.samedaypros.com]$ drush cc all
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                    [error]
Error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/data/disk/o1/static/platform/starter.v1/sites/all/drush): failed to open
dir: Permission denied' in /opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:54
Stack trace:
#0 /opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(54): RecursiveDirectoryIterator->__construct('/data/disk/o1/s...', 4096)
#1 /opt/tools/drush/8/drush/vendor/symfony/finder/Finder.php(808): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('/data/disk/o1/s...', 4096, false)
#2 /opt/tools/drush/8/drush/vendor/symfony/finder/Finder.php(681): Symfony\Component\Finder\Finder->searchInDirectory('/data/disk/o1/s...')
#3 /opt/tools/drush/8/drush/vendor/consolidation/annotated-command/src/CommandFileDiscovery.php(240): Symfony\Component\Finder\Finder->getIterator()
#4 /opt/tools/drush/8/drush/vendor/consolidation/annotated-command/src/CommandFileDiscovery. in
/opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php, line 54

**Comment by omega8cc** [comment]
You should keep `_PERMISSIONS_FIX=YES`.

There was a typo in the 3rd command, it should be `octopus up-stable o1 force`, obviously.

Then wait until all platforms will be re-verified, and only then try to use drush/drush8 on command line again.

In the meantime use `drush7`.

**Comment by nitinsareen** [comment]
Thanks for hint, I repeated the 3rd step and ended up with the same error. Reverting to drush7 as suggested via changing the softlink inside /usr/bin as - 

root@boaaegir:/usr/bin# ll drush*
lrwxrwxrwx 1 root root 30 Jun 29 11:49 drush -> /opt/tools/drush/7/drush/drush*
lrwxrwxrwx 1 root root 30 Jun 28 03:48 drush7 -> /opt/tools/drush/7/drush/drush*
lrwxrwxrwx 1 root root 30 Jun 28 03:48 drush8 -> /opt/tools/drush/8/drush/drush*

When i log back in to o1.ftp account i encounter the same error of drush 8. Please suggest what am I missing as this is all what I used to do earlier for reverting drush?

**Comment by omega8cc** [comment]
Please don't modify any symlinks! It should just work if you have really completed all steps.

**Comment by nitinsareen** [comment]
Have reverted the symlinks to orignial. Using drush7 command is working correctly. But drush command ends up in error as it uses drush8.

**Comment by omega8cc** [comment]
Then you probably you did something unexpected before and we have no way to assist you further. It should just work if you follow the outlined steps.
