### ISSUE TITLE
Info/querry Re: Disk Space being used up

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1008]
We have noticed that disk space is being used up very quickly on a BOA server 3.1.1 (current). We notice that once we get to 90% disk full, Octopus stops running tasks, and Barracuda won't do anything (like upgrades). There are inexpensive VPS's out there that allow us to run an inexpensive BOA test server, so we can find faults outside of a production environment. These inexpensive vps's (think OVH) have only 10GB of disk space, which only seems to allow a few platforms and one static custom platform, before the disk is 90% full.

SO, we'd like to:

1) Ask where the data is being used up - and if anyone is using a new cron instruction to clean up anything;

2) Inform others that 10 or so MariaDb full backups are being made - each one in the hundreds of MB at least - so we're talking GB of data - that can be deleted if needed on a limited disk space;

3) Can it be added to the requirements that a minimum of 20 GB of hard disk space as well as 2 GB or RAM is needed. 10 GB is simply not enough, and causes us endless problems.

Lastly, is there any other discussion on this disk space issue that you can refer us to, or that we should be aware of?

Thank you very much,

Ed

**Comment by omega8cc** [comment]
You are expected to monitor your disk usage on your own, and BOA doesn't have any specific requirements (besides the sane less than 90% requirement), plus, it is designed to use as little, as possible. Next, even the cheapest VPS options on the market come with no less than 24GB (Linode 2G RAM), or even 40GB (DigitalOcean 2G RAM), so having a system with just 10GB if very unusual, and should be avoided.

**Comment by omega8cc** [comment]
At any rate, your workflow/usage/data specific requirements are not related in any way with BOA itself, so there is no point in trying to define BOA requirement in regard to disk space.
