### ISSUE TITLE
New security update for o1

### ISSUE THREAD

**Issue by azvox** [omega8cc/boa#1010]
This is probably somewhere in the docs. But could someone tell me how apply security update to o1 satellite site. I was able to update the hostmaster by using Upgrade Drupal core.
	•	drush @hostmaster pm-updatecode drupal. But how do i do it o1.xxxx.xxx.com

Thanks

**Comment by omega8cc** [comment]
No, no, this is against all basic principles. Never do this again.

The only proper upgrade workflow for your BOA system is explained at https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt

The recommended upgrade workflow for hosted sites is explained at: https://omega8.cc/your-drupal-site-upgrade-safe-workflow-298
