### ISSUE TITLE
Cron not running on sites with SSL required and Cloudflare

### ISSUE THREAD

**Issue by me336408** [omega8cc/boa#1011]
coming from #998 
open new issue for boa cron not running on sites

-------------------------------------------------------------
i setup the cron for 15 minutes but doesn't run on sites

[boa info more](https://gist.githubusercontent.com/me336408/3520ecd82f704fb6401525e9a39b5de6/raw/6d506ee000ed9865149cdc56bd6f24da112e61c8/boa%2520info%2520more)
hosting provider = vultr.com

i was previously on 3.0.1 and everything was just working fine
i upgraded 3.0.1 to 3.1.1 and cron and aegir tasks stooped working so out of desperation i manually migrated to a new server with a fresh install of 3.1.1

on the new server (3.1.1) the cron is not running on the sites. but the aegir tasks are running fine
- cron is set for 15 minutes

**Comment by omega8cc** [comment]
Please set the sites cron to run every 5 minutes, then monitor nginx access log and let us know the responses with:

`$ tail -f /var/log/nginx/access.log | grep cron.php`

**Comment by omega8cc** [comment]
Not sure if this is related to your problem, but worth checking anyway, perhaps: https://github.com/omega8cc/boa/issues/998#issuecomment-229703247

**Comment by me336408** [comment]
Seems to be the SSL Settings required vs enabled

When SSL Settings is on required the cron is not running
When SSL Settings is on enabled cron runs

**Comment by omega8cc** [comment]
SSL settings/mode shouldn't mater. Can you show us the entries you see when you monitor the access.log?

**Comment by me336408** [comment]
your right, i have Cloudflare and that seem to add to the issue

------------------------------------------------------------
SSL required + Cloudflare OFF

"104.*.*.113" domain.com [01/Jul/2016:11:12:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 301 178 140 433 "-" "iCabProXy" 0.000 "-"
"104.*.*.113" domain.com [01/Jul/2016:11:12:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 200 5 140 482 "-" "iCabProXy" 0.152 "-"
"104.*.*.113" domain.com [01/Jul/2016:11:18:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 301 178 140 433 "-" "iCabProXy" 0.000 "-"
"104.*.*.113" domain.com [01/Jul/2016:11:18:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 200 5 140 482 "-" "iCabProXy" 0.417 "-"

-------------------------------------------------------------------------

**Comment by omega8cc** [comment]
This log snippet is too aggressively anonymized to be helpful, but I guess this is similar to the problem we have explained in the docs at: https://omega8.cc/running-scheduled-sites-cron-in-aegir-118

Basically, site cron will not work if the request goes via some alien network because of the redirect.

To avoid this problem you could switch cron method from wget to drush and then create control file: `/data/disk/o1/log/hosting_cron_use_backend.txt`

**Comment by me336408** [comment]
on the documentation you have:

> The site cron will not work if your site’s DNS is pointed to CloudFlare and not to your instance default IP address or dedicated SSL enabled IP and you have enabled alias redirect in Aegir which points to an alias and not to the site main name defined in Aegir

i dont have an alias redirect but i do have "SSL required" which is essentially a redirect of HTTP to HTTPS
than could explain why i see no issues with "SSL enabled"

**Comment by me336408** [comment]
SSL enabled + Cloudflare ON = cron runs

"104.x.x.113" domain.com [01/Jul/2016:13:36:05 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-TnKIQ HTTP/1.1" 200 5 140 482 "-" "iCabProXy" 2.810 "-"
"104.x.x.113" domain.com [01/Jul/2016:13:41:04 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-TnKIQ HTTP/1.1" 200 5 140 482 "-" "iCabProXy" 1.199 "-"
"104.x.x.113" domain.com [01/Jul/2016:13:47:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-TnKIQ HTTP/1.1" 200 5 140 482 "-" "iCabProXy" 0.158 "-"
"104.x.x.113" domain.com [01/Jul/2016:13:52:04 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-TnKIQ HTTP/1.1" 200 5 140 482 "-" "iCabProXy" 0.392 "-"

**Comment by me336408** [comment]
SSL required + Cloudflare ON = cron fails

"104.x.x.113" domain.com [01/Jul/2016:14:10:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 301 178 140 433 "-" "iCabProXy" 0.000 "-"
"104.x.x.113, 108.162.212.157" domain.com [01/Jul/2016:14:10:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 403 134 362 331 "-" "iCabProXy" 0.000 "1.32"
"104.x.x.113" domain.com [01/Jul/2016:14:15:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 301 178 140 433 "-" "iCabProXy" 0.000 "-"
"104.x.x.113, 108.162.212.157" domain.com [01/Jul/2016:14:15:03 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 403 134 362 331 "-" "iCabProXy" 0.000 "1.32"
"104.x.x.113" domain.com [01/Jul/2016:14:21:04 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 301 178 140 433 "-" "iCabProXy" 0.000 "-"
"104.x.x.113, 108.162.212.157" domain.com [01/Jul/2016:14:21:04 +0000] "GET /cron.php?cron_key=s0EPpLGGWawp1bJKywzBIz6ax9iacUUB7TWYF-XxXXX HTTP/1.1" 403 134 362 331 "-" "iCabProXy" 0.000 "1.32"

**Comment by me336408** [comment]
what i gather is that "SSL required" redirects http:// request to https://
while a call to cron.php via http is causig a 301
thats why we see a 301 on the first request on then followed by another request. but since the second request is no longer internal it goes out and makes a request to the IP on DNS, in the cloudflare case it will go to cloudflare causing a 403 response

a solution i found was to add the IP pointing to domain.com to /etc/hosts file

**Comment by me336408** [comment]
i think the call to cron.php should be made in HTTPS to prevent a 301 response in the first place, if SSL is set to "SSL required"

**Comment by omega8cc** [comment]
The correct question is: how it works when you don't use Cloudflare?

**Comment by omega8cc** [comment]
Your reported before:

>> SSL required + Cloudflare OFF = cron runs

And this is how it is expected to work.

With Cloudflare in place there is no way to make it work, because the cron procedure will just follow redirects (any, SSL or alias).

To avoid this problem we would need to hack Aegir Provision to create exception for `/cron.php`, but I'm not sure if this would be the correct method to make it work.

**Comment by omega8cc** [comment]
That said, we need to figure it out, somehow.

**Comment by me336408** [comment]
> The correct question is: how it works when you don't use Cloudflare?

when cloudflare is off, is the same as it not being there. all request do directly to the origin server, with no proxy in between

when cloudflare is on, all request do to cloudflare's reverse proxy server which then makes a request to the origin server

about the curl call to cron.php im not sure how that works, but from your documentation i get that is an internal request:
> Our customized, curl based method with protected access to /cron.php will work even if the main site domain name doesn’t point to your instance IP address yet or when you are using third-party proxy like CloudFlare. Just another kind of BOA magic!

**Comment by omega8cc** [comment]
Right, so while we can't make it work with Cloudflare and forced redirect to an alias which is not a site main name, we can make it work using `https://` local request, because even if the site doesn't have its own valid SSL cert, it can still use the system HTTPS wildcard proxy.

**Comment by omega8cc** [comment]
Fixed in https://github.com/omega8cc/hosting/commit/41f84f8f3bde38fcf885409e175cdd51ee4119ef
