### ISSUE TITLE
Solr port

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1013]
our solr4 is not working, and I think its because of a hardcoded port 8983 in the /opt/solr4/solr.xml file (before there was no port number in that file)

The file is here: https://gist.github.com/EdNett/7c7ee6a52580d94cf9002702a992d39b

Boa info more is here:  https://gist.github.com/EdNett/14bd9e4cf7c925d73156e7a860ab9f5c

Replacing the port number in the solr.xml file with 8099, or removing it altogether does NOT help. I am restarting jetty9 after each change.

Could you please advise if the port number 8983 is supposed to be in that file, or if it should be removed or changed to 8099, please.  I have followed the new instructions regarding copying the default_boa_site_control.ini file and uncommenting the necessary. I am using apachesolr 7.x-1.8

I am running bash /var/xdrago/manage_ltd_users.sh 
    and  bash /var/xdrago/daily.sh  

also after enabling solr via the site ini file.
This is what my Solr Server URL looks like:
http://localhost:8099/solr/d41d8cd98f00b204e9800998ecf8427e.example1.com.fast1

and the browser error message when I try to visit it is:

HTTP ERROR 503

Problem accessing /solr/d41d8cd98f00b204e9800998ecf8427e.example1.com.fast1. Reason:

    Server is shutting down or failed to initialize

**Comment by omega8cc** [comment]
Your `boa info` doesn't look complete. What is the result of command `virt-what` ?

**Comment by omega8cc** [comment]
The port in this file is correct, but it is not used by your Solr cores. Please just follow the standard how-to: https://github.com/omega8cc/boa/blob/master/docs/SOLR.txt

**Comment by EdNett** [comment]
My apologies - the sites that can't connect to the solr are sites being restored from a server that went down when we lost mysql. SO, we are importing the db dump and ftping the /files/ folder over the newly created site. This must be causing the problem. The db dump has the old solr4 paths of /solr/core0 ... 

I will try disabling all solr modules for each of these sites, waiting a day, and then starting the process anew with the new control file way of using solr.
