### ISSUE TITLE
Not able to execute bash BOA.sh.txt

### ISSUE THREAD

**Issue by DominicBoettger** [omega8cc/boa#1016]
A few hours ago i did a installation on a system and everything worked quite well. Now i had to reinstall the same system and after 

bash BOA.sh.txt

nothing happens .

**Comment by omega8cc** [comment]
What happened then? It always helps to add a comment when you close the issue.

**Comment by DominicBoettger** [comment]
Sorry. Didn't want to talk about it :-). I had an error in my apt config.

**Comment by omega8cc** [comment]
Ah.. OK.
