### ISSUE TITLE
rvm installation incomplete

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1017]
On a new installation, RVM does not install properly for Octopus users.

OS: Debian Jessie
BOA: 3.1.1

Steps to duplicate:
1. Log in as o1.ftp user
2. `touch ~/static/control/compass.info`
3. wait for `/var/xdrago/manage_ltd_users.sh` to run
4. notice a CSF email alert: 
```2016-07-06 16:51:06,481 (o1.ftp): *** forbidden shell escape: echo ZSH_VERSION```
5. test RVM installation with `rvm --version`
6. error `grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`

**Comment by omega8cc** [comment]
Looks like a regression.

**Comment by omega8cc** [comment]
Just tested this on BOA head (which is basically 3.1.1) and I can't reproduce the problem -- at least on Wheezy. Maybe you need to wait a little longer until the install is really complete?

```
o1.ftp:~$ rvm --version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
o1.ftp:~$
```

**Comment by omega8cc** [comment]
It works also on Jessie and BOA-3.1.1 stable:

```
o8.ftp:~$ rvm --version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
o8.ftp:~$
```

**Comment by pricejn2** [comment]
Thanks for confirming the issue was on my side. I ran `barracuda up-stable` after adding CSS to the XTRAS_LIST and now it installs fine.

**Comment by pricejn2** [comment]
Just noting for the next guy/gal that this was a complete id10t move on my part -- the dependency on the CSS XTRA is already clearly documented in  @[docs/RVM.txt](https://github.com/omega8cc/boa/blob/master/docs/RVM.txt). I don't regularly do/test new BOA installs and totally missed this at the time.
