### ISSUE TITLE
Compatibility with Multi-byte UTF-8 support in Drupal 7

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#1020]
Drupal 7.50 introduces multi-byte UTF-8 support for MySQL and other database drivers, allowing for emojis, Asian symbols, mathematical symbols, etc.

To use this feature you need to use Drupal 7.50 based platform, and then convert charset for the database in question, preferably with [UTF8MB4 Convert](https://www.drupal.org/project/utf8mb4_convert) Drush extension, and then add in the `local.settings.php` file these two lines:

```
$database['default']['default']['charset'] = 'utf8mb4';
$database['default']['default']['collation'] = 'utf8mb4_general_ci';
```

We can't add these lines in Aegir templates, obviously.

This means that that apart from [this commit](https://github.com/omega8cc/boa/commit/7715cf3ca689bc466ac5797f392183b739d94fd1) we need also the [UTF8MB4 Convert](https://www.drupal.org/project/utf8mb4_convert) Drush extension added to our toolbox.
 
See related issues:

https://www.drupal.org/node/2488180
https://www.drupal.org/node/2754539

**Comment by omega8cc** [comment]
We should also deny attempts to convert tables to MyISAM via `sqlmagic` tool, if the database is already converted to use UTF8MB4.

**Comment by omega8cc** [comment]
We need to wait until it is properly supported in Aegir: https://www.drupal.org/node/2764111

**Comment by caldenjacobs** [comment]
It appears that a fix has been committed: https://www.drupal.org/node/2764111#comment-11464781

**Comment by omega8cc** [comment]
Yes, we have merged it in our fork https://github.com/omega8cc/provision/commits/3.x.x-dev

Still, on the BOA side we should deny attempts to convert tables to MyISAM via `sqlmagic` tool, if the database is already converted to use UTF8MB4.

**Comment by omega8cc** [comment]
We still need to add [UTF8MB4 Convert](https://www.drupal.org/project/utf8mb4_convert) Drush extension, perhaps.

**Comment by omega8cc** [comment]
Let's make it a separate issue.
