### ISSUE TITLE
Redirect issues with LE when non-SSL page is requested on different domains

### ISSUE THREAD

**Issue by gandhiano** [omega8cc/boa#1022]
On an OA setup with multiple domains - and domain per space activated, after enabling encryption and effectively activating Lets' Encrypt, there are redirect problems ocurring.

E.g. can be seen by going on http://sementes.gaia.org.pt. It directs to the SSL page, but keeps redirecting without end. If I reload with ctrl+F5, then I can see the login page (actually it should have present the respective space page, which is public, and not redirect to SSL).

I haven't had time to explore the issue further, and appreciate any help, especially in understanding if this is a BOA-dependent behavior or a result of badly setup OA.

**Comment by omega8cc** [comment]
There is nothing in the Aegir HTTPS handling which is new, and it is used by many people, for years. We have only recently started to leverage this for LE certs, but I don't see anything on the Aegir or BOA side which could cause such problems, so I must assume that it is some misconfiguration in your site which you need to debug and fix.

Feel free to re-open if you will find anything really BOA related here.
