### ISSUE TITLE
Using hook_node_load() and redis caching in module development.

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1023]
Ok, so this is a developer type question regarding module development when running drupal behind redis on boa.

First, I'm using the vimeo.com video service to host videos. Their api provides for pulling download links for videos via rest.

My initial approach was to use hook_node_load() to test for a specific node and compare php time() [now] against a field which contains the time in which the download links expire. There's no reason in making the call on each load if the links to the videos on vimeo are still valid.

Vimeo download links expire so they can't be shared. Probably using some hash like an hmac.

After pulling the links via rest, I just push them into fields for display on the node.

Here's the problem. If redis is providing the page from cache, and that node has never pulled in updated links - or - the links have expired between the time they were last used and when the node is viewed (but before being cached) then they're stale links and won't work.

I know I can cycle the nodes with expired links using hook_cron(), but the problem is that nodes are obviously viewed randomly by visitors and I simply need to check if the links are expired (when the node is viewed?), get the new links, then flush the redis cache.

Questions:
Can I flush redis for just one path?
How do I do this within a drupal module?
Is there a better way to solve the problem explained above?

Hoping someone can save me some time.

**Comment by petrowsky** [comment]
Well, I found this https://github.com/omega8cc/boa/blob/master/aegir/conf/global.inc#L882

But it would be nice to get any clarification from boa devs regarding running this type of module scenario on omega servers. Which I'm hoping to do some day when I can rip out my custom code which requires me running my own servers. :)

**Comment by omega8cc** [comment]
Redis is just a cache backend, and if you need to expire something from its cache, you need to use Drupal API.

On some problematic URIs you may want to disable page cache (Redis) and Nginx cache (if the default TTL causes problems, or if you force Speed Booster TTL), as explained in this article: https://omega8.cc/speed-booster-redis-boost-and-advagg-108

```
      /**
       * Custom Speed Booster TTL override, for example to force no-cache
       * on some selected URLs which need to be excluded to always provide
       * dynamic results.
       */
       if (preg_match("/^\/(?:foo|bar)/", $_SERVER['REQUEST_URI'])) {
         header('X-Accel-Expires: 1'); // This disables Speed Booster
         $conf['cache'] = 0; // This disables page caching on the fly
       }
```

The only other method would be to run the links check and selective page cache purge action via some backend script, because when the page is server from Nginx cache (and/or Redis page cache), there is no chance to check & update anything on the fly.

**Comment by petrowsky** [comment]
Thanks for the reply. I'm going to be digging into the redis module but my follow up question would be related to flushing the redis cache from php. Can this be done or is it an all or nothing by using the proper header()?

Also, my page which shows the expiring vimeo links is accessed only by logged in users. If I do disable redis for those uri's then would the next suggestion be to use boost for anon versions of those same uri's?

**Comment by omega8cc** [comment]
You seem to confuse Nginx cache with Redis cache. You don't need to dig in that module. You can't use headers to manage it. Forget it's Redis. It just Drupal cache, so use standard Drupal API to interact with it. If the problem affects logged in users, then simply disable page cache only -- either globally or for affected paths. You can also disable it for logged in users only. Just add clever enough code in you local.settings.php using our example as a start.

**Comment by petrowsky** [comment]
Ok, thanks for the feedback! I think I've figured it out for now. For anyone who happens to stumble on this comment thread this is what I ended up putting in my local.settings.php. I'll let omega comment on whether I really need the redis header.

```
<?php # local settings.php
//unset($conf['preprocess_css']);
//unset($conf['preprocess_js']);

if (preg_match("/^\/videos\/.*$/", $_SERVER['REQUEST_URI'])) {
    header('X-Allow-Redis: NO');
    header('X-Accel-Expires: 1'); // This disables Speed Booster
    $conf['cache'] = 0; // This disables page caching on the fly
}
```

I needed a dynamic page on anything that was /videos/extra_url_stuff_here

Thanks for  the guidance Omega!

**Comment by omega8cc** [comment]
HTTP headers are **not** used to manage Redis. The headers your see in `global.inc` are only for debugging mode. Also, you don't want to disable Redis completely. But if you do, there are INI directives to manage this. You manage Redis behaviour via INI directives, not via HTTP headers.

`X-Accel-Expires` HTTP header **is** used to force custom TTL for Speed Booster cache, though.

When you use `$conf['cache'] = 0;` you are disabling only the page cache bin in Drupal. It doesn't matter that it happens to use Redis as a cache backend. You just use Drupal API here, selectively.

I hope this helps.

**Comment by petrowsky** [comment]
Yes, it does help! It clarifies that I can't really control Redis caching on a per url basis when implemented via php code - unless I use an ini. It also helps with understanding that the headers themselves are only for knowing what is going on and not control - unless it's nginx.

It's been a while since I've had to dig deep into the underside of drupal and doing this custom module for periodically expiring vimeo links via rest has been a good challenge.

I think I've got it working now as I had to make functions to clear drupal's db cache whenever I updated fields directly instead of using node_save().

As a pointer for anyone using hook_node_load(). You can't call a node_save() within hook_node_load() because hook_node_load() will be called recursively. If you're wanting to update certain fields, when a node is loaded (prior to being viewed), then using field_attach_update() is how you do it. You just have to make sure and update the cache after saving the fields.

Or at least this is how I think it goes.
