### ISSUE TITLE
What's the best way to set up remote Drush Aliases

### ISSUE THREAD

**Issue by kepford** [omega8cc/boa#1024]
I find it very convenient to run Drush commands without ssh'ing into the o1 or o1.ftp user accounts.  I'd like to be able to run drush commands locally. The barrier to this is that no matter what I do in my ssh config the o1.ftp account requires a password. What am I missing? I don't see anything in the docs about doing this either. Thanks.

**Comment by omega8cc** [comment]
Just two steps:

1. Add SSH keys to your o1.ftp account properly
2. Follow https://omega8.cc/how-to-use-drush-aliases-321

If SSH keys don't work, check/fix permissions, as explained at the bottom of https://omega8.cc/ftp-and-sftp-password-not-accepted-120

**Comment by kepford** [comment]
Thank you! It was the permissions issue.
