### ISSUE TITLE
Wheezy to Jessie Upgrade script unfinished

### ISSUE THREAD

**Issue by ethnovode** [omega8cc/boa#1026]
Hello I upgraded from Debian Wheezy to Jessie just after an upgrade from 2.4.9 to 3.1.1. Since then the tasks in Aegir are not running and Drush is broken. I noticed I still had a /var/xdrago_wait directory which I believe should have been renamed to xdrago with the upgrade script.

Drush error :
`exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/data/disk/o2/static/erplaindev-743-2/sites/all/drush): failed to open dir: Permission denied' in /opt/tools/drush/8/drush/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:54`

When the upgrade occurred I didn't saw it finish whereas I let it run for more than five hours.

boa info more : https://gist.github.com/ethnovode/67ffbfd9631e414918d5c0ade48c0b06 (AWS)

**Comment by omega8cc** [comment]
You have not completed the upgrade to Jessie, if that is what you have in your `boa info` now. Please try again and pay attention to what you see in your terminal.

Remember that once it is complete, you must reboot and run another upgrade.

If it appears to be stuck for some reason, don' wait hours! Check what the verbose log tells you in the other terminal window and if it waits for some y/n answers, enter that answer in the **first** terminal window and hit Enter to allow it to continue. It shouldn't happen, but who knows what AWS does here.

**Comment by omega8cc** [comment]
For reference: https://github.com/omega8cc/boa/blob/BOA-3.1.0/CHANGELOG.txt#L303

**Comment by ethnovode** [comment]
Thanks, I'll try the upgrade again tomorrow with another terminal window open. I wasn't sure I could run the upgrade again.

Thanks again, I really appreciate your help.

**Comment by ethnovode** [comment]
After another attempt everything seems running fine now. There were some errors, but I kept going through all the steps. Had to answer some reconfig about postfix and a few others, always kept old config.

Tasks are now working and drush too after the verifications of the platforms.

Thanks!

**Comment by omega8cc** [comment]
Thanks for the update.
