### ISSUE TITLE
_XTRAS_LIST forgot SR4

### ISSUE THREAD

**Issue by DominicBoettger** [omega8cc/boa#1027]
Hello,

i forgot to add SR4 to XTRAS_LIST when installing barracuda.
How can i install it after barracuda and octopus have been installed?

Thanks
Dominic

**Comment by bserem** [comment]
See https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt

Short answer: add it there and run barracuda up-stable

**Comment by DominicBoettger** [comment]
Thank you. That helped me a lot.
