### ISSUE TITLE
Not getting limited FTP creds

### ISSUE THREAD

**Issue by leevh** [omega8cc/boa#1034]
Hello, I followed instructions here: https://omega8.cc/shell-and-ftps-extra-accounts-per-aegir-client-226
and created a client (with no email) in aegir and assigned to a site by editing site node.  Unfortunately for me there is no ~/users folder created (I assume its supposed to be at /data/disk/o1/users).  I don't see anything unusual in the logs, is there any way to diagnose, or am I misunderstanding how to set up FTP for a single site?   thanks

https://gist.github.com/leevh/6b9e52debc1f3e177490cacdb43d2377

**Comment by bserem** [comment]
Try /home/o1.ftp/users

**Comment by omega8cc** [comment]
Correct. We could improve the how-to to avoid confusion:

>> stored in the ~/users/ directory in your main account

replaced with:

>> stored in the ~/users/ directory in your main SFTP account
