### ISSUE TITLE
Drupal Core - Highly Critical - Injection - SA-CORE-2016-003

### ISSUE THREAD

**Issue by zanami** [omega8cc/boa#1037]
Just a heads up, haven't checked if BOA is affected

View online: https://www.drupal.org/SA-CORE-2016-003

   * Advisory ID: DRUPAL-SA-2016-002
   * Project: Drupal core [1]
   * Version: 8.x
   * Date: 2016-July-18
   * Security risk: 20/25 ( Highly Critical)
     AC:Basic/A:None/CI:All/II:All/E:Proof/TD:Default [2]
   * Vulnerability: Injection

-------- DESCRIPTION

Drupal 8 uses the third-party PHP library Guzzle for making server-side HTTP
requests. An attacker can provide a proxy server that Guzzle will use. The
details of this are explained at https://httpoxy.org/

**Comment by omega8cc** [comment]
This has been mitigated in Our Provision fork: https://github.com/omega8cc/provision/commit/6c5346270e31845d7b595f9a49c01c92f474fa73

**Comment by zanami** [comment]
Could you elaborate on how do I fix it on a working server?

**Comment by omega8cc** [comment]
Just upgrade to latest Drupal 8, if you are using it, I think? Otherwise you would need to upgrade both barracuda and octopus to head version, which is not recommended.
