### ISSUE TITLE
Default MariaDB 10.0.26 settings suggestion/querry

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1038]
Hello,

We are using BOA stable 3.1.1 and have noticed that /etc/mysql/my.cnf comes with defaults that seem to be wasting memory for drupal 7 and drupal 8 sites.

Namely:

aria_pagecache_buffer_size defaults to 128 MB (and we're using 1 byte of it with 10 mixed D7/8 sites on this vps)

We added the below line to the my.cnf file to give it a size of 128K:
aria_pagecache_buffer_size = 131072

additionally key_buffer and key_buffer size are defaulting to 256MB and almost none is being used.

This is on a vps with 2GB ram.

Just a heads-up. Thansk for the great work.

Ed

**Comment by omega8cc** [comment]
Please follow [guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt).

**Comment by EdNett** [comment]
boa info more is here (not really necessary for this support heads-up, is it?):
https://gist.github.com/EdNett/2e864a383ce4727bb72d5787b6f7b40c

Since only the mysql database and its tables use myisam, defaults to key_buffer, key_buffer_size and 
aria_pagecache_buffer_size should be kept super low. I recommend 2 MB for key_buffer and key_buffer_size, and 128 KB (or lower if the block unit size is lowered - 128 KB is the min res unit for this aria storage engine table setting). Or can we safely disable aria database engine altogether?

Ed

**Comment by omega8cc** [comment]
The `boa info` is always relevant and always required.

BOA is not designed to precisely tune everything in MariaDB, quite contrary, it is designed to use as much memory, as safely possible. It's not designed to use as little as possible. You can change this behavior, though, as [explained in the docs](https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L101)

```
###
### By default BOA configures your system to use as much RAM as safely available
### but if you want to make the configuration more precize, add this extra
### variable to use MySQLTuner on the fly to detect optimal memory allocation.
### This check is no longer enabled by default, because it is very expensive
### method on systems with not enough resources and many sites hosted.
###
_USE_MYSQLTUNER=NO #------------ Use MySQLTuner to configure SQL limits when YES
```

As for the Aria engine, have you actually verified the memory usage before and after? I don't think its limit is used if the engine is not used.

**Comment by omega8cc** [comment]
Additionally, since you are using `SKYNET_MODE=OFF`, please run this command to update the meta-installers before trying `boa info`:

```
$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
```

Also, the `VPS` line shouldn't be empty.
