### ISSUE TITLE
SSL Fields not auto-filled, fields disabled

### ISSUE THREAD

**Issue by serhatozkara** [omega8cc/boa#1039]
When I try to enable ssl through edit page of a site, I get this error:
"The encryption key field is required to enable us to generate a new SSL certificate for your site."  I'm using BOA and successfully used let's encrypt on a couple of sites. I can't enable https for the site. Is there any workaround?
<img width="1280" alt="screen shot 2016-07-28 at 11 43 44 am" src="https://cloud.githubusercontent.com/assets/3116157/17207550/cb93551a-54bd-11e6-9ee3-52ca61705903.png">

**Comment by omega8cc** [comment]
This should never happen. Maybe you have had an empty/incorrect record for this site already present in the database? Was the site renamed after enabling SSL before? If nothing else helps, please try to revert this change in the Eldir theme: https://github.com/omega8cc/eldir/commit/293fc395757e93c0c6366fc929846c1d2687e974

**Comment by serhatozkara** [comment]
Site may be renamed before disabling SSL i dont recall unfortunately :/
By reverting the changes in eldir and removing certificates as per https://www.drupal.org/node/1612608 , i was able to generate new self signed certificates. But LE gives me error on validation: [hosting_le] The site's vhost must already exist, or the LE agent will not be able to proceed.
the site is on a remote server defined in BOA.

**Comment by omega8cc** [comment]
We don't really support Aegir remote server feature in BOA, even if it is possible, so it is never tested.

Please make sure you are using latest `hosting_le` version, and make sure to copy the correct file in place, as discussed in https://github.com/omega8cc/hosting_le/issues/3

**Comment by omega8cc** [comment]
By the way, the task log message should provide the information about missing file you need to copy to the LE script directory, to be able to support remote sites.

**Comment by serhatozkara** [comment]
After upgrading hosting_le to dev version and adding mentioned script, i was able to get LE working.

**Comment by omega8cc** [comment]
Thanks for the update. We have pushed tags to make the dev progress tracking easier.
