### ISSUE TITLE
Is it possible to add custom NGINX config to a specific site?

### ISSUE THREAD

**Issue by netdream** [omega8cc/boa#1040]
Hello, I need some advice...
Is it possible to add custom config to a specific nginx vhost config? What is the best practice?

We need to add some code (specifically a new "location" block) in the server block, but I suppose that it will be rewritten by platform migrations ... or not?

My idea is to write the additional config directives after the "Extra configuration from modules" area, adding an include file BEFORE the inclusion of "nginx_vhost_common.conf", to eventually override anything written in it.

Is it ok? Thanks in advance!

```
server {
  include       fastcgi_params;
[...]
# Extra configuration from modules:
  ###
  ### Allow access to letsencrypt.org ACME challenges directory.
  ###
  location ^~ /.well-known/acme-challenge {
[...]

## HERE
include        /data/disk/nd/config/includes/nginx_www-mysite-specific.conf

  include       /data/disk/nd/config/includes/nginx_vhost_common.conf;
} 
```

**Comment by memtkmcc** [comment]
While we are using the Aegir built-in feature to extend Nginx configuration, so we can add the LE support **before** it loads the main config include (see [this submodule](https://github.com/omega8cc/hosting_le/tree/7.x-3.x/hosting_le_vhost) for details), there are rules you must be aware of, to avoid problems:

1. Nginx will not accept duplicate locations ([named location](https://github.com/omega8cc/boa/issues/948#issuecomment-224553810) is an exception)
2. Which means you can't override existing locations
3. But you can add new or more specific regex locations via [BOA includes](https://github.com/omega8cc/boa/blob/master/docs/HINTS.txt)
4. You can make them domain specific using `if{...}` pseudo locations
5. But not all directives are allowed within `if{...}` pseudo locations

I hope this helps!

**Comment by cvining** [comment]
Just wanted to say thanks for this answer! It led me to the HINTS.txt notes, and within minutes I had a working solution to a legacy URL redirect problem, where I wanted some "old" website URLs to still work after porting a the site to Drupal/BOA.

Perfect. Thanks.

-- Con

**Comment by omega8cc** [comment]
@cvining Nice to hear that, thank you!
