### ISSUE TITLE
Non-interactive Octopus upgrade doesn't set _AUTOPILOT=YES on the fly

### ISSUE THREAD

**Issue by cobiashi** [omega8cc/boa#1041]
Upgrade in silent mode is left hanging, using command 

> octopus up-stable all both log

.

Log shows that after Aegir Satellite Instance upgrade, the script asks for user input.

> Do you want to install some ready to use platforms? [Y/n]

How do you get around this?

**Comment by omega8cc** [comment]
Please follow [guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt).

**Comment by thebennos** [comment]
confirm. stops at the same point. 


BOA [18:09:55] ==> UPGRADE A: Syncing hostmaster frontend db_passwd...
BOA [18:09:55] ==> UPGRADE A: Aegir Satellite Instance upgrade completed

Do you want to install some ready to use platforms? [Y/n]

**Comment by omega8cc** [comment]
You probably have `_AUTOPILOT=NO` in your `.o1.octopus.cnf` file, for some reason. We should force `_AUTOPILOT=YES` in Octopus on the fly for silent/log mode, like we do in Barracuda.

**Comment by thebennos** [comment]
yepp, _AUTOPILOT=NO in .o1.octopus.cnf. confirming. 

I try an upgrade with autopilot=YES.

**Comment by thebennos** [comment]
works like a charm with _autopilot = YES

**Comment by omega8cc** [comment]
Should be fixed now. Thanks for the report!
