### ISSUE TITLE
barracuda up-stable system successful, but some packages not updated

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#1046]
Every so often I get a package that is not updated with barracuda up-stable system. The next day's email still has packages to be updated, along with the message `E: There are problems and -y was used without --force-yes`.

I know this problem has happened before, and have read the old bug at https://www.drupal.org/node/2094867, as well as the referenced articles from mariadb.com, but is there some generic process I can use to fix this issue once it crops up? I don't want to mess things up by updating through apt-get or something like that. Also am I doing something wrong that causes these packages to get stuck?

I'm on a DigitalOcean Debian/jessie VPS. Output of boa info more is here: https://gist.github.com/dnotes/64500bc578c87ad52b8d66f6c4026844

**Comment by omega8cc** [comment]
Can you provide examples of not updated packages? Are you absolutely sure this happens despite running `barracuda up-stable system` upgrade?

**Comment by dnotes** [comment]
Packages are:

libcurl3 7.38.0-4+deb8u4
openssh-sftp-server 1:6.7p1-5+deb8u3
E: There are problems and -y was used without --force-yes

-and yes, I've tried the update several times. It reports success, but the
next day there are the same packages not updated. I'm only running boa on
this server, no other software, and I do all my updates via the barracuda
up-stable system command.

**Comment by omega8cc** [comment]
Thanks for the information. These are known issues we have fixed in BOA head:

[Force /root/.use.curl.from.packages.cnf](https://github.com/omega8cc/boa/commit/724b40f00df065b1dad3e865243521ce739e8597)
[Fix for openssh-sftp-server status on Jessie](https://github.com/omega8cc/boa/commit/bc08c780fdd0e8e5616deb9b2cd38cd5ebdcef49)

BTW: It is safe to upgrade the system to BOA head currently -- we are running current head (barracuda only, not octopus) in production all servers we host and support remotely.

**Comment by dnotes** [comment]
Thanks so much for the info, and for all the work you put into the project. I suppose in future I'll just report such issues sooner and more specifically. 

I do have a couple of questions: once I've upgraded using barracuda up-head, is it possible after the next release to revert to using barracuda up-stable? And will I need to change anything so that the automated weekly updates don't revert to the stable version?

**Comment by omega8cc** [comment]
Yes, after upgrading to head you can later continue with stable, once released.

To make unattended upgrades also running head, add in your `/root/.barracuda.cnf` this line:

`_AUTO_VER=head`

You can later change it to:

`_AUTO_VER=stable`
