### ISSUE TITLE
up-stable 3.1.2 fails/ stalls at upgrade of building ImageMagick from sources

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1051]
An up-stable on Jessie has stalled/fails - it is trying to build imagemagick 7.0-1.9 from sources for over 3 hours now.

boa info more is here:
https://gist.github.com/EdNett/b5ad459ecad48dd516b79bc7e6b2797a

This is a process list output three 1/2 hours after starting the imagemagick from sources build (what do you recommend doing to not break our boa?):

 Barracuda System managed by Skynet Agent v.BOA-3.1.1 welcomes you aboard

server1:~# ps
  PID TTY          TIME CMD
 9194 pts/3    00:00:00 bash
 9202 pts/3    00:00:00 ps
server1:~# ps -a
  PID TTY          TIME CMD
  352 pts/1    00:00:01 bash
  547 pts/2    00:00:00 tail
 8495 pts/1    00:00:00 apt-get
 9203 pts/3    00:00:00 ps
18315 pts/1    00:00:00 mysqld_safe
18591 pts/1    00:00:37 mysqld
18592 pts/1    00:00:00 logger
28096 pts/0    00:00:00 screen
31284 pts/1    00:00:00 barracuda

**Comment by EdNett** [comment]
On this vps, I had to 

wget https://ftp-master.debian.org/keys/archive-key-8-security.asc

and

wget https://ftp-master.debian.org/keys/archive-key-8.asc

and then 

apt-key add archive-key-8-security.asc

and

apt-key archive-key-8.asc

then apt-get update

and

aptitude update

and I am trying to run barracude up-stable system again

**Comment by omega8cc** [comment]
Is this about ImageMagick or FFmpeg (fixed elsewhere) ?

Do you have `_MAGICK_FROM_SOURCES=YES` non-standard option? We don't recommend to use it, it was only a temporary workaround for security issues.

**Comment by EdNett** [comment]
Hello,

This is probably about the keyring issue I think - and I did have _MAGICK_FROM_SOURCES=YES for the first upgrade attempt. Then I modified that to _MAGICK_FROM_SOURCES=NO (and also fixed the keyring problem) for the second upgrade attempt, which then worked. This can probably be closed.
