### ISSUE TITLE
dont overwrite file not respected

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#1053]
I added some custom certificates and followed https://github.com/omega8cc/boa/blob/master/docs/SSL.txt for the implementation.
But after upgrading Boa the dont-overwrite ctrl files do not prevent that the certificates are renewed.

I was able to fix it for now by removing the vhosts for all sites with custom certificates and than verify the sites again. 

(error: nginx: [emerg] PEM_read_bio_X509_AUX("/data/disk/o1/config/server_master/ssl.d/sub.domain.nl/openssl.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: configuration file /etc/nginx/nginx.conf test failed)

**Comment by omega8cc** [comment]
Can you check if the path/filename you have created matches the path/filename you can find in the verify task log? It is visible in the line starting with:

> [hosting_le] The optional immutable flag is

**Comment by omega8cc** [comment]
If you have a correct and readable pid file in place, you will see these lines in the task log, too:

> [hosting_le] Immutable protection mode detected for this domain
> ...
> [hosting_le] To re-activate LE auto-renewals please delete this file:

**Comment by omega8cc** [comment]
No further feedback, so closing. Feel free to reopen if needed.
