### ISSUE TITLE
Querry on deletion of AEgir hostmaster platforms

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1054]
Hello,

I notice disk space being used up, and then I see in /var/aegir/host_master

platforms with numbers running from 000, 010 - up to 026.

When I login to the octopus instance  I see that AEgir Hostmaster 022 is the only AEgir platform (I manually deleted the others.)

So, I have deleted from /var/aegir/host_master  all the platforms from 010 to 021.  My questions:

1) Is deleting the platform in the Octopus web interface supposed to delete the code and the platform on the server?  (It is not doing so.)

2) Platform 000 has a file in it called placeholder_do_not_remove.txt - should it be left?

3) Can I safely delete platforms 023 through 026? 

BOA info more is here:
https://gist.github.com/EdNett/71d16952d8b58eeefc17accdf64c6ebd

Thank you,

Ed

**Comment by omega8cc** [comment]
You can easily delete all those old platforms, both in the master and satellite hostmaster, using batch delete task in Aegir. You should *never* delete anything manually on the filesystem there.

That said, these platforms don't use any huge disk space, so you have some other problems there if you are trying to save space by deleting tiny and empty platforms.

**Comment by EdNett** [comment]
Hello,

I think you have misunderstood me. 

1) I did do a batch delete task in AEgir (on the octopus site), and it appeared to work, but it did not actually remove any of the files in those platforms.

2) Those platforms DO use a lot of space - about 60 MB each. They are NOT tiny and they are not empty - they are full. 25 of them is 1.25 GB or more - a substantial amount of disk space. 

So, I have changed this to a bug report, since the batch AEgir delete task is not working as intended. Please re-open.

Thank you.

**Comment by omega8cc** [comment]
We can't reproduce this, and deleting old hostmaster platforms always works for us, both on our machines and on various systems we support remotely. You need to figure out what exactly happens on your system if delete task doesn't work, but you have not explained what you mean, like, did the task failed? what errors were reported, etc, etc.
