### ISSUE TITLE
Nginx: Do not hardcode X-Frame-Options header

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#1056]
In commit ebf3d5577bec7ed5080530e27a3b109314b7c6d2 the HTTP header in nginx config was added by default

`add_header X-Frame-Options SAMEORIGIN;`

I know this is a security measure, but it can be very restrictive specially using **CiviCRM** when many Online Webforms are design to be included in IFRAMES in external websites.

I don't find a way to override this header at php level, because I think it's added after the php page is parsed.

Any tips?

Thanks

**Comment by omega8cc** [comment]
It should be enabled by default, but we should make it easy to override / turn off via INI variable on the site and platform level.

**Comment by omega8cc** [comment]
Related commit in Provision: https://github.com/omega8cc/provision/commit/559888c41063efc75ce8798b51be96b7cb183b9c

**Comment by omega8cc** [comment]
@ixiam For immediate fix on the hosted instance(s), please open a ticket at: https://omega8.cc/contact

**Comment by dsnopek** [comment]
What is the "immediate fix"? (for those who run BOA on their own server...)

**Comment by omega8cc** [comment]
@dsnopek The best immediate fix is to upgrade barracuda and octopus to BOA head. We run it in production, so it should be safe for everyone.

**Comment by omega8cc** [comment]
But the fix is also included in BOA-3.1.3

**Comment by dsnopek** [comment]
Hm, I thought we were already on 3.1.3, but I guess not! I'll run through the upgrade steps.. Thanks!
