### ISSUE TITLE
Aegir Setup failed with PHP 7

### ISSUE THREAD

**Issue by sTb1337** [omega8cc/boa#1058]
hi there,

the aegir setup installer failed: https://gist.github.com/sTb1337/7cc7335e8010e29bbd8eafa3f8613026

here is the .barracuda.conf with php 7 configured: https://gist.github.com/sTb1337/b2b6698d1038b9757c1053cf7594cfb5

boa info: https://gist.github.com/sTb1337/d9c2d7011e88a52339cb80d656d19377

**Comment by omega8cc** [comment]
PHP 7.0 is not supported as the only version to install currently. Octopus still expects 5.6 installed by default, hence the lines:

>* This Octopus will use PHP-CLI 5.6 for all sites
>* This Octopus will use PHP-FPM 5.6 for all sites

You should be able to switch to 7.0 once it is installed, though.

The problem here is that you would need to specify 7.0 also in the .octopus cnf file before it is installed.

That said, we should allow to use just 7.0, and perhaps inherit PHP version between barracuda and octopus, so it doesn't try to use not installed version.

**Comment by sTb1337** [comment]
Thanks a lot for your fast response. How can i continue the installation now?

**Comment by omega8cc** [comment]
@sTb1337 

1. Set 7.0 for FPM and CLI in the (failed) Octopus /root/.o1.octopus.cnf file
2. Install Octopus with `boa in-octopus {email} o1 {mini|max|none} stable`

See also: https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L132

**Comment by sTb1337** [comment]
Thanks a lot, but its not working as intend.

See ouput: https://gist.github.com/sTb1337/6d8b67d3dad2b6a189c7bf4d39f4386f
cat /root/.p1.octopus.cnf  > https://gist.github.com/sTb1337/877c019d7183fe0853f63d491c13c9d5

**Comment by omega8cc** [comment]
Looks like the initial install went too far, so it now thinks it is an upgrade.

Rename /root/.p1.octopus.cnf to /root/.p2.octopus.cnf and use p2 in the boa in-octopus command.

**Comment by sTb1337** [comment]
Thanks, it seemed to work, but the url is not https://p2.sq006wqa01.somedomain.com/node/add/platform its https://p1.sq006wqa01.somedomain.com/node/add/platform despite i used p2 in conf and bash command.

**Comment by omega8cc** [comment]
You have not updated the URL and username in the renamed cnf file, probably.

**Comment by EdNett** [comment]
INstalling only php 7.0 in both barracuda and octopus IS workign for us for at least a month or more now. This is with 3.2.0. It seems to be working fine. Waiting for 7.1! Cheers!
