### ISSUE TITLE
No ftp instruction email for o1

### ISSUE THREAD

**Issue by civiclix** [omega8cc/boa#1063]
Reinstalled BOA after having not used it in a year; finally got it installed (sketchy wireless connection didn't help!), but - as I recall from previous installs - aren't I supposed to get an email w/ my o1 FTP credentials? Is there any way to recreate this?

Thanks so much!

**Comment by omega8cc** [comment]
You mean `o1.ftp`, I think?

Check your spam folder, perhaps?

If this doesn't help, check the `/data/disk/o1/log/setupmail.txt` file.
