### ISSUE TITLE
Requests failing OCSP_basic_verify()

### ISSUE THREAD

**Issue by kevinob11** [omega8cc/boa#1064]
Here is my `boa info` output. We are self-hosted in a datacenter on our own hardware.
https://gist.github.com/kevinob11/6b659e3c927c1e4b9f7d00eab3c4be7b

We recently upgraded to boa 3.1.2 and since have been having issues with our nodejs server making requests to our drupal app. The nodejs server is a pretty standard implementation of a simple notification web socket using the nodejs module. When our page makes the initial request to the nodejs to upgrade to a websocket connection we see the following errors in the log.
https://gist.github.com/kevinob11/591049bc0f3b303dabeff120d1134b8a

When that failure occurs in our nodejs app we see the following errors in `/var/log/nginx/error.log`.
https://gist.github.com/kevinob11/0348116c60871f874a8eb8b47fa434e6

Thanks!

**Comment by omega8cc** [comment]
Is the remote server trying to connect to the site with incorrectly set up SSL, perhaps?

These errors suggest that somehow Nginx is trying to verify the cert at ocsp.godaddy.com but gets some self-signed certificate in the chain?

Please make sure you are using URL with valid SSL cert.

**Comment by kevinob11** [comment]
I don't think that is the issue, it is trying to reach `https://portal.praece.com/nodejs/message` which looks good in ssl labs. My logs show access to it working as expected on the 9th before the update, I've attached those in the gist below. I'm happy to dig a bit deeper of course if I'm missing something.
https://gist.github.com/kevinob11/07d57eb1332a92d6ecf83849897134dc

**Comment by omega8cc** [comment]
These Nginx errors are unrelated then, because Comodo has nothing to do with GoDaddy certs, I think?

Or maybe you have verified when requests fail, the errors you have attached appear in the Nginx log?

Also, have you whitelisted your remote server in CSF on your BOA server? Maybe it just got blocked?

**Comment by omega8cc** [comment]
I have compared timestamps in the logs you have attached and they don't seem related at all.

**Comment by omega8cc** [comment]
You need to determine what really happens on both servers at the same time, to determine what causes the `[Error: socket hang up]` error.

Hence, you have two separate issues, apparently, not necessarily related.

**Comment by kevinob11** [comment]
Solved, the nodejs server I was working on was very old, updating node solved the issues. For anyone else who finds this ticket it is working great in node >= 0.10.

Sorry for the mostly false alarm!

**Comment by omega8cc** [comment]
No problem, glad to hear it works now.
