### ISSUE TITLE
Older BOA box upgrade fails

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#1065]
Trying to upgrade using the following before I do up-stable: barracuda up-2.4

I think it may be related to the no such file of directory error shown below?
```
BOA [18:37:15] ==> INFO: Restarting Redis, PHP-FPM and Nginx...
BOA [18:37:20] ==> INFO: Restarting MariaDB server...
grep: /data/disk/*/config/includes/*: No such file or directory
BOA [18:37:28] ==> INFO: Upgrading csf/lfd firewall...
BOA [18:37:30] ==> TEST: csf/lfd firewall should work fine on this system
```

Sites are currently not accessible on the server

**Comment by omega8cc** [comment]
Please follow guidelines.

**Comment by BrianGilbert** [comment]
apologies, added here

boa info output: https://gist.github.com/BrianGilbert/e71bfd4df7e979b7926f5041f9bd705e

**Comment by omega8cc** [comment]
OK, but what you mean by "upgrade fails", exactly?

The little log snippet with "No such file or directory" is not really helpful in determining the source of the problem.

Could you add our SSH keys, so we could check this directly? It will be faster, I think.

**Comment by omega8cc** [comment]
I mean:

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab https://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
cd
```

**Comment by BrianGilbert** [comment]
I'll PM you on gitter the server details

**Comment by omega8cc** [comment]
OK

**Comment by BrianGilbert** [comment]
this was caused because the server was installed as 32bit but I had been told by host to change to 64bit kernel
