### ISSUE TITLE
Admirer not installed on BOA 3.1.3 upgrade

### ISSUE THREAD

**Issue by cvining** [omega8cc/boa#1067]
Hi guys,

Thought I ticked the right option, but looks like Admirer was not installed.

here is my latest 'boa info' output: https://gist.github.com/cvining/4fb5bff4c6f9df4866e8310f4957d4ac

Thanks for all the fish!

-- Cronin

**Comment by memtkmcc** [comment]
Why do you think it was not installed? How do you check this?

**Comment by cvining** [comment]
OK, I'm just typo crazy. 'adminer' of course works just fine.

'admirer'? Obviously doesn't exist.

Sincere apologies to all. I'm slowly losing it.

-- Phrum my Fone

   Cronin B. Vining,
   ITS Webmaster: http://www.its.org & ITSnews@its.org
   http://cvining.com/
   cvining2009@cvining.com
