### ISSUE TITLE
pdnsd config changed last night automatically, broke many things

### ISSUE THREAD

**Issue by obrienmd** [omega8cc/boa#1069]
BOA 3.1.2 
Ubuntu 14.04.x LTS

Last night, at some point /etc/pdnsd.conf changed the server{ip} directive to our server's domain name (i.e. foo.com}, causing DNS lookups to fail miserably. I just manually changed this to 8.8.8.8, and all DNS-relying services starting working as expected. 

Any ideas what could have caused this? I know BOA has a ton of "self healing" magic behind the scenes, and I want to make sure this doesn't happen again.

Corrupted conf file was:
server {
        label = "google-servers";
        ip=**_{was changed to the domain part of server's FQDN}_**;
        timeout=100;      // By default 50.
        interval=5m;      // Test every 5 minutes.
        uptest=ping;
        ping_timeout=300; // By default 30 seconds.
        purge_cache=off;
        exclude=.local.;
}

**Comment by omega8cc** [comment]
Please follow [guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt)

Also, what is the output of commands:

`cat /etc/resolv.conf`
`ls /root/.use.default.nameservers.cnf`
`ls /root/.use.local.nameservers.cnf`

**Comment by obrienmd** [comment]
Sorry: https://gist.github.com/obrienmd/977d0ee32774167e5253106f2344d2fb

cat /etc/resolv.conf
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search ourdomain.com
```

ls /root/.use.default.nameservers.cnf
`ls: cannot access /root/.use.default.nameservers.cnf: No such file or directory`

ls /root/.use.local.nameservers.cnf
`ls: cannot access /root/.use.local.nameservers.cnf: No such file or directory`

cat /root/.local.dns.IP.list
```
        label = "google-servers";
        ip=ourdomain.com;
```

**Comment by omega8cc** [comment]
Thanks. The line with `search ourdomain.com` should never be present in this file, and is probably forced there by Ubuntu specific and/or host specific forced DNS settings. That said, we should add better filtering to make sure that pdnsd will ignore it.

**Comment by obrienmd** [comment]
Gotcha, so if I manually remove search ourdomain.com from the /etc/resolv.conf file, and change /root/.local.dns.IP.list to a real DNS server, say 8.8.8.?

**Comment by omega8cc** [comment]
It should do this for you, on the fly. But don't modify `/etc/resolv.conf`, only update  `/root/.local.dns.IP.list` so there will be a line `ip=8.8.8.8;`

**Comment by omega8cc** [comment]
Please wait 15 minutes and then try to force default config with:

`$ touch /root/.use.default.nameservers.cnf`

It should re-create working configuration when you run:

`$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`

Make sure it worked as expected!

**Comment by obrienmd** [comment]
Looks like it works, thanks!
