### ISSUE TITLE
Adding custom symbolic link to Grav site folder inside client folder

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#1070]
I wanted to know how client management works in BOA and if I can add custom symbolic links to not Aegir controlled sites. For instance, its a Grav site, which I want to be symlinked to clients folder.
 
I added custom symbolic link to clients folder in /data/disk/o1/clients/[username]. Then after some time (probably some Aegir tasks executed or daily cleanup is done), this symbolic link is deleted. Is there any way to keep custom symbolic links? Or maby you have some suggestions as a workaround for this problem? Maby some custom cron job which readds custom symbolic link? Would be nice to know where this stuff happens in code, so I can better idea. Cheers.

**Comment by omega8cc** [comment]
It is managed by /var/xdrago/manage_ltd_users.sh script, but it is not possible to introduce custom exceptions or symlinks, since these extra sub-accounts are by definition ephemeral and are expected to be destroyed and recreated automatically, if needed.
