### ISSUE TITLE
Support for Open Social

### ISSUE THREAD

**Issue by gandhiano** [omega8cc/boa#1071]
[Open Social](https://www.drupal.org/project/social) is a very recent and promising Drupal 8 distribution, which has recently reached it's first public beta.

> Open Social is a distribution for building social communities and intranets. The distribution is positioned as the successor of Drupal Commons, taking full advantage of the new possibilities of Drupal 8.
> Open Social is made by the same core team that created the award winning, Drupal based social community: 'Greenpeace Greenwire'. Open Social is a complete redesign and rewrite inspired by the lessons learned from this and other community projects. 

Would be great to have it among the supported distributions of BOA.

**Comment by memtkmcc** [comment]
Thanks for the suggestion, but we need to fix Drupal core first, somehow.

For more details please check: https://learn.omega8.cc/platforms

>> Note: BOA will not include built-in Drupal 8 platforms until Drupal 8 will support symlinks in the codebase, like all previous core versions.

Also: https://twitter.com/omega8cc/status/763431687929880576

**Comment by memtkmcc** [comment]
To quote these links directly:

On Symlinks in Drupal8:

https://www.drupal.org/node/1792310 
https://www.drupal.org/node/1672986 
https://www.drupal.org/node/1008402 
https://www.drupal.org/node/2453973

**Comment by omega8cc** [comment]
It's a part of 4.0.1 release: https://github.com/omega8cc/boa/blob/master/README.txt#L158
