### ISSUE TITLE
Sites down after upgrades 

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1072]
Hello 
Here is my boa info. 
https://gist.github.com/yazzou/5fb6ccf8aa031fea259278b2828de087
I have upgraded barracuda and octopus to have the latests versions of drupal core. I have upgraded one of my hosted sites but i am constently redirected to www.mysite.com/install.php
What can i do to bring it online again ?

**Comment by omega8cc** [comment]
You are running not supported system, so anything can happen.

The redirect to /install.php happens when you have conflicting vhosts, and the one with no longer existing site directory takes precedence.

You need to find the vhost with duplicate domain entry and fix it manually, then reload Nginx.

**Comment by yazzou** [comment]
The command "find /data -name  www.mysite.com" returns 
/data/disk/octopusname/distro/008/drupal-7.50.1-prod/sites/www.mysite.com
/data/disk/octopusname/distro/002/drupal-7.36.1-prod/cache/perm/www.mysite.com
/data/disk/octopusname/distro/002/drupal-7.36.1-prod/cache/normal/www.mysite.com
/data/disk/octopusname/distro/004/drupal-7.39.2-prod/cache/perm/www.mysite.com
/data/disk/octopusname/distro/004/drupal-7.39.2-prod/cache/normal/www.mysite.com
/data/disk/octopusname/config/server_master/nginx/vhost.d/www.mysite.com


It seems that my vhost file is pointing to the right path. Here is what is written in it : 
https://gist.github.com/yazzou/d8c5662c8fe401cc87b14bd621692253

**Comment by omega8cc** [comment]
Please check #980

**Comment by omega8cc** [comment]
As for checking vhosts for duplicate names, the correct command to use is:

`$ grep site.com /data/disk/o1/config/server_master/nginx/vhost.d/*`
