### ISSUE TITLE
If install or update for the new version drupal-8.2.0-rc2, website break!

### ISSUE THREAD

**Issue by dgvmd** [omega8cc/boa#1073]
Hi,
If install or update for the new version drupal-8.2.0-rc2, website break!
Here is the error message :
The website encountered an unexpected error. Please try again later.

Work well with drupal-8.2.0-rc1 version.
Thank you.

**Comment by omega8cc** [comment]
Please follow guidelines.

**Comment by memtkmcc** [comment]
@dgvmd Have you tried to clear caches with Aegir task on the affected site after the install/upgrade? This sounds like Redis related issue..

**Comment by dgvmd** [comment]
@memtkmcc New install, no Redis, tried to clear caches with Aegir task. Version 8.2.0-rc2 doesn't work.

**Comment by omega8cc** [comment]
It seems to work just fine with 8.2.0

![screenshot 2016-10-05 20 30 34](https://cloud.githubusercontent.com/assets/128547/19126343/d1316008-8b3a-11e6-999f-e93d2544832e.jpg)
