### ISSUE TITLE
Migration between installation profiles

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#1076]
Is this recipe still working from migration between different installation profile names in latest BOA/AEgir?
https://learn.omega8.cc/migrate-sites-between-installation-profiles-111

I've tried it, following the instructions, but I'm not able to migrate from one platform to another with a different installation profile in BOA 3.1.3

**Comment by ixiam** [comment]
Well I'm trying to migrate from a custom profile to a Vanilla Drupal **Standard** 
Added in standard.info **old_short_name =  "my_custom_profile"** , berfied platform, but in database I see standard package has **old_short_name =  "default"** entry

Maybe some hardcoding around.. will try with another profile name

**Comment by omega8cc** [comment]
This code in Aegir "reserves" the standard/default pair to make D6->D7 upgrades easier:

```php
// Drupal 7 renamed the default install profile to 'standard'
// Aegir now allows projects to specify an "old short name" to provide an upgrade path when projects get renamed.
if ($profile->name == 'standard') {
  $profile->info['old_short_name'] = 'default';
}
```

**Comment by omega8cc** [comment]
We have removed it, along with all other hardcoded pairs from our customized Provision backend: https://github.com/omega8cc/provision/commit/a93a8c5ce72864be22544df1ecad60fe4d563682

**Comment by omega8cc** [comment]
This means that if you patch Provision on your instance, it should work for your custom profile -> standard migration.
