### ISSUE TITLE
BOA SSL support not PCI compliant?

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1078]
Ok, so I've had this ongoing issue for two months and I'm at the end of my rope when it comes to troubleshooting.

I've been using BOA for who knows how long. I have an online store at Yahoo and for the longest time I've used a feature which POSTs XML body content to a BOA vhost. I parse the XML for forwarding to Authorize.net. The XML includes credit card data.

Anyway, two months ago something happened. I can't coordinate it to an update to 3.1.3 exactly, but it was about that time when I stopped receiving the XML. So, it was either a change with Yahoo sending or a change with my box/setup.

The box ranks an A at ssllabs.com and with HSTS would get an A+ (thanks BOA!)

I've turned on/off all kinds of features. TLSv1 with stapling, X-Frame-Options, nosniff, stronger ssl_dhparam. I've even dropped down into the trenches and used tcpdump to watch the packets on 443.

For the life of me I can't sovle this issue. So, either my Yahoo store is trying to get rid of me as a customer or this is something in the build of nginx that I have no idea about in terms of what headers they expect vs what is being sent. They won't give me exact specs and it's a guessing game to see if I can get it working again. I looked at both pre 3.1.3 conf files and current. I don't see any major changes.

I'm sorry for using the issue queue as a support ticket, but maybe the issue is of enough interest to give it some thought or someone smarter than me might be able to help. I know there's something missing or Yahoo really is trying to shut down the feature. Does Omega or anyone know anyone who might be able to help?

**Comment by omega8cc** [comment]
How exactly do your run HTTPS on BOA? With Let's Encrypt, or with the old method (local HTTPS proxy on the same or dedicated IP address)?

**Comment by petrowsky** [comment]
It's the older method of using the proxy I presume. The connection from Yahoo verifies the session based on the IP so I couldn't use SNI. It's nginx_wild_ssl.conf which proxies up to upstream nginx_http.

I did try temporarily turning off the proxy_set_headers to see if Yahoo's sender didn't like them. Is that what you were thinking?

**Comment by omega8cc** [comment]
The problem with this old local proxy method is that it may cause problems hard to identify and track down, at least this is what we have seen a few times already, where replacing this proxy with direct HTTPS vhost fixed all weird problems auto-magically.

I guess that it could be related to some things specific to proxy mode with Nginx, but we could never pinpoint what exactly caused problems, because usually it was the remote server which seemed to not like some header, or quite opposite, required some extra header we normally don't use. And it was always site specific, to make it more complicated.

Theoretically your problem could be caused by changes on the Yahoo store side, changes in recent Nginx versions in regard to proxy behaviour, or even latest OpenSSL version we always use for custom built Nginx, for security reasons.

So there could be a single problem or a combinations of those three, at least. Or maybe even cURL version update (provided via Debian packages).

It is obviously hard to debug, because BOA doesn't support installing Nginx or OpenSSl version of your choice, so you could easily go back to version you think worked previously.

So, yeah, no wonder the problem here is rather hard to debug.

**Comment by omega8cc** [comment]
Hmm.. we could probably allow custom Nginx/OpenSSL versions, if defined in the .barracuda.cnf

**Comment by omega8cc** [comment]
It works out of the box -- just specify the versions you want to use in your `/root/.barracuda.cnf`

Example:

`_NGINX_VRN=1.11.0`
`_OPENSSL_NGX_VRN=1.0.2h`

**Comment by petrowsky** [comment]
Thank you SO, SO much for the response! You've given me the info to continue troubleshooting. So, I retrograded nginx and openssl back to what they were at 2.4.9 (which is what was running prior to the upgrade). That didn't work when initiating a send from Yahoo. I still got a 500 response from their end and I can see the packets hit the box. So they must have changed something at about the same time I upgraded my BOA. I had retrograded to this...

```
root@s2:~# nginx -V
nginx version: nginx/1.9.15
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.2f  28 Jan 2016
```
Yeah, I wouldn't want to be running 1.0.2f anyway!

I've now updated to

```
nginx version: nginx/1.11.3
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.2h  3 May 2016
```

Still getting a 500. :(

So now it's probably the proxy that it doesn't like. Or so I'm guessing. So the next step would be switching to the LE method? Is there a best method suggested for switching to a direct HTTPS vhost? I'm only running a few sites on the box but I do have two different IPs each with different certs & keys.

**Comment by petrowsky** [comment]
Is this an issue?

```
root@s2:~# nginx -V
nginx version: nginx/1.11.3
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.2h  3 May 2016
TLS SNI support enabled
configure arguments: --prefix=/usr --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --user=www-data --group=www-data --with-http_realip_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_ssl_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_scgi_module --without-http_uwsgi_module --with-ipv6 --with-http_geoip_module --with-openssl=/var/opt/openssl-1.0.2h --with-debug --with-http_v2_module --add-module=/var/opt/nginx-upload-progress-module/ --add-module=/var/opt/ngx-cache-purge/

root@s2:~# openssl version
OpenSSL 1.0.1t  3 May 2016
```

Nginx is statically linked and reports 1.0.2h yet openssl reports at 1.0.1t. Is that because of your build process in the arguments pointing to /var/opt/openssl-1.0.2?

**Comment by omega8cc** [comment]
No, using custom OpenSSL version  doesn't matter here, I think.

I would suggest to try LE to replace the old proxy method and its possible weird issues before digging further.

The how-to: https://github.com/omega8cc/boa/blob/master/docs/SSL.txt#L163

**Comment by omega8cc** [comment]
If this will not help, then it would suggest that the problem could be on the PHP level, perhaps?

**Comment by petrowsky** [comment]
Ok, I THINK I finally have resolution and can close this out. Given that my issue has nothing to do specifically with BOA, I'm hoping this information will help someone else out.

In my case I had two options within my Yahoo store which POSTs XML to my BOA box. Nginx is obviously configured correctly because we get an A ranking from SSLLabs when checking it.

This is probably an issue on the sending end of things. The two options when sending from Yahoo were to include credit card data or not. When POSTing XML WITHOUT credit card data, things would work fine. Meaning the script was receiving the data. When the POSTing of XML happened WITH credit card data enabled it would fail.

The resolution? I had to use a tcpdump pcap file and inspect the packets under both circumstances. It turns out the two different options were handled by two different machines. When then sent from the machine which DID NOT include credit card data, everything went through fine. When they sent from a different box which included credit card data things were rejected because that particular machine did not have the root CA in their trust store for my CA provider! At least that's the current assumption. I'm waiting for confirmation on this.

Talk about a troubleshooting nightmare. If I didn't know how to use tcpdump and wasn't so stupid as to go two months without checking a pcap file within Wireshark, then I likely would never have found the issue because you can't tell what's going on at the packet level as easily on the server.

Ugghhhhh! This is just one of those issues where one little variable is out of whack and it puts your knowledge to the test. Making assumptions, like they must be sending from the same machine are the types of things which cause headaches like this. If I had just opened the pcap file in Wireshark two months ago I would have immediately found the issue!

```
TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Certificate Unknown)
```

**Comment by omega8cc** [comment]
Wow... Thanks for sharing this!
