### ISSUE TITLE
Have followed all directions.... I can not get 5.3 to be used on a d6 site. Please see details...

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#1080]
Hi, I am trying to find a way to use php 5.3 on a specific site on my server (not all sites). I thought this was a possibility, but Im having a hard time finding  the documents to help make this happen. I appreciate it and your great work.

**Comment by AntiNSA** [comment]
so am I coorect https://learn.omega8.cc/how-to-quickly-switch-php-to-newer-version-330

within /home/o1.ftp/static/control

I can create 

site1.com 5.3
site2.com 5.6
site3.com 5.6 

save as multi-fpm.info

and then site1.com will be using 5.3?

**Comment by AntiNSA** [comment]
Ok even after adding the control multiplatform I am seeing PHP	5.6.25 in the status report in drupal 6. 

is there something I have to edit in the baracudda.cnf file to make sure 5.3 is installed and available for the control file to use?

**Comment by AntiNSA** [comment]
ok I am adding this into the barracudda.cnf file
_PHP_MULTI_INSTALL="5.6" #------ PHP versions to install: 7.0 5.6 5.5 5.4 5.3


it doesnt give an example of multiple instances, so I am trying this

_PHP_MULTI_INSTALL="5.6 5.3"

I hope that is the correct syntax. I hope then 5.3 will be installed and the multiplatform control fiile will be utilized.

**Comment by angel0d** [comment]
@AntiNSA this is the correct syntax and AFAIK you need to fill in .barracuda.cnf upgrade so that newly added php version becom avaiable

**Comment by AntiNSA** [comment]
I have tried multiple things...  I have 
1) edited the .barracuda.cnf 

_PHP_CLI_VERSION=5.6
_PHP_EXTRA_CONF=""
_PHP_FPM_DENY=""
_PHP_FPM_VERSION=5.6
_PHP_FPM_WORKERS=AUTO
_PHP_IONCUBE=NO
_PHP_GEOS=NO
_PHP_MONGODB=NO
_PHP_MULTI_INSTALL="5.6 5.3"
_PHP_SINGLE_INSTALL=

Than I ran baracudda upgrade - stable......

and I have tried to :

a) /home/o1.ftp/static/control/multi-fpm.info
and created myseite.com 5.3

and Ive even tried 
b)created a /home/o1.ftp/static/control/fpm.info
5.3  as a single line...


However status report still shows 	5.6.25 in drupal 6.


So now I will try the option to set the CLI for 5.3

I will runt a forced ocoput upgrade just incase.

Does anyone know what I am missing and what is needed to allow a dingle site to use php 5.3?

**Comment by AntiNSA** [comment]
I will try to force php install on upgrade

**Comment by angel0d** [comment]
@AntiNSA what i 've tried several times and always worked is to use/change the PHP version per octopus instance

i have never used the per site option though

if you have more than 1 D6 site that needs php 5.3 you could go for an extra octopus on php 5.3

in this case be careful as you probably do not need to change the CLI version of PHP but the FPM version as this is the one that really affects you site

CLI is used from drush and also from aegir drush commands. you should not mess with it unless you have very specific (and tested) CLI scripts that need php 5.3

**Comment by AntiNSA** [comment]
@angel0d I really only have one d6 site I need to use 5.3 with. Thanks for letting me know about the CLI. 

I am running out of options to try. 

If I understand you , I have never ran two octopus instances. 

I currently have one instance of octopus which is running two Drupal 7 sites, and one drupal 6 site.

I really have no need for 5.3 except on the D6 site.

If I change the octopus.cnf file, that means all my sites would have to use 5.3 ?

I forced the rebuild, am waiting on the upgrade to complete now.

**Comment by AntiNSA** [comment]
I noticed 

_PHP_CLI_VERSION=5.6
_PHP_EXTRA_CONF=""
_PHP_FPM_DENY=""
_PHP_FPM_VERSION=5.6
_PHP_FPM_WORKERS=AUTO
_PHP_IONCUBE=NO
_PHP_GEOS=NO
_PHP_MONGODB=NO
_PHP_MULTI_INSTALL="5.6 5.3 5.4"
_PHP_SINGLE_INSTALL=

_PHP_SINGLE_INSTALL=
was** missing brackets, so I 
changed that to _PHP_SINGLE_INSTALL=" " 

am am trying baracudda upgrade again. I have a feeling 5.3 is not being installed. So I am trying to install 5.4 in addition and will see if thaat can be set in the control file.

My next step will be to try to force reinstall from sources.

**Comment by AntiNSA** [comment]
BOA [11:48:55] ==> INFO: Installing extra Drush versions...
BOA [11:48:59] ==> INFO: Running system packages update...
BOA [11:49:51] ==> INFO: Upgrading required libraries and tools...
BOA [11:50:30] ==> INFO: Running MariaDB upgrade and then PHP forced rebuild...
BOA [11:51:36] ==> INFO: Installing MariaDB...
BOA [11:51:43] ==> INFO: Forced MariaDB 10.0.27 in Debian/jessie
BOA [11:53:03] ==> INFO: Restarting MariaDB server...
BOA [11:53:08] ==> INFO: MariaDB server restart completed
BOA [11:53:08] ==> INFO: Running aptitude full-upgrade...
BOA [11:53:45] ==> INFO: Upgrading Nginx...
BOA [11:56:51] ==> INFO: Installing wkhtmltopdf and wkhtmltoimage x86_64...
BOA [11:56:52] ==> INFO: Installing VnStat monitor...
BOA [11:57:14] ==> INFO: PHP to 5.6.25 rebuild forced
BOA [11:57:14] ==> INFO: Building PHP 5.6.25 from sources, please wait...
BOA [11:57:19] ==> INFO: Building PHP 5.6.25 part 1/3
BOA [11:57:20] ==> INFO: Building PHP 5.6.25 part 2/3
BOA [11:58:12] ==> INFO: Building PHP 5.6.25 part 3/3










BOA [12:10:39] ==> INFO: Installing PhpRedis for PHP 5.6.25...
BOA [12:10:58] ==> INFO: Installing UploadProgress for PHP 5.6.25...
BOA [12:11:06] ==> INFO: Installing JSMin for PHP 5.6.25...
BOA [12:11:15] ==> INFO: Installing Twig C for PHP 5.6.25...
BOA [12:11:23] ==> INFO: Installing Imagick for PHP 5.6.25...
BOA [12:11:38] ==> INFO: Installing MailParse for PHP 5.6.25...
BOA [12:11:47] ==> INFO: Installing YAML for PHP 5.6.25...
BOA [12:12:01] ==> INFO: Upgrading Limited Shell to version 0.9.18.8...
BOA [12:12:13] ==> INFO: Installing Redis update for Debian/jessie...
BOA [12:13:11] ==> INFO: Updating MariaDB and PHP configuration
BOA [12:13:12] ==> INFO: OS and services upgrade completed
 
BOA [12:13:12] ==> INFO: Restarting MariaDB server...
BOA [12:13:25] ==> INFO: Upgrading MariaDB tables if necessary...
 
Do you want to upgrade Aegir Master Instance? [Y/n] BOA [12:14:26] ==> INFO: Running Aegir Master Instance upgrade
BOA [12:14:58] ==> INFO: Downloading drush micro-8-23-07-2016...
BOA [12:15:01] ==> INFO: Installing Aegir Provision backend...
BOA [12:15:01] ==> INFO: Downloading Drush and Provision extensions...
BOA [12:15:02] ==> INFO: Running hostmaster-migrate, please wait...
BOA [12:15:54] ==> INFO: Aegir Master Instance upgrade completed
BOA [12:15:55] ==> INFO: Building Pure-FTPd server from sources, please wait...


on forced reinstall from sources I cn not see 5,3 being installed even though I added i in 
_PHP_MULTI_INSTALL="5.6 5.3 5.4"

**Comment by angel0d** [comment]
@AntiNSA 

i think _PHP_SINGLE_INSTALL= needs simply to be empty without any brackets

note also: from the documentation I think the multi-fpm.cnf is taken in consideration during an octopus update

> I have a feeling 5.3 is not being installed

during the barracuda upgrade it clearly states which versions it install but you can also have a look at /opt/ directory where you should find one folder for each php version install with names like php53 php54 etc

**Comment by angel0d** [comment]
ups. hadn't see your last comment while writing my previous one

as said, simply check the /opt/ folder

**Comment by omega8cc** [comment]
PHP 5.3 and 5.4 are not supported on Debian Jessie, so no matter what you will try, BOA will not install these versions. Also, 5.3 and 5.4 will be removed in BOA 3.3.x, and the only method to still use these versions is to run Debian Wheezy and BOA up to 3.2.x

See also: https://github.com/omega8cc/boa/issues/801

**Comment by AntiNSA** [comment]
ah : ( thank you
