### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#1081]
Hi,

is it possible to use the built in letsencrypt.sh to create and update certificates for non Drupal sites hosted under `/var/www` (nginx config file at `/var/aegir/config/server_master/nginx/vhost.d/example.com`)?

**Comment by omega8cc** [comment]
It is not supported by BOA currently. Only Drupal sites get proper vhosts and certs structure managed via Aegir extension. This will change a bit once we introduce HTTPS support for Grav CMS sites. But it will still not cover any other sites you create manually. Of course you could try to use letsencrypt.sh outside of BOA context, but you should then use your own copy, in some other location, with custom build vhosts, paths, etc.

**Comment by luxio** [comment]
Thanks.

**Comment by attiks** [comment]
FYI you can use ` ~/tools/le/letsencrypt.sh -c --domain www.example.com --domain example.com ` to create the certificates, they can be found inside `/data/disk/o1/tools/le/certs/www.example.com` and can be used as follows, best in a config file stored inside `/var/aegir/config/server_master/nginx/vhost.d`

```
  ssl_certificate_key        /data/disk/o1/tools/le/certs/www.example.com/privkey.pem;
  ssl_certificate            /data/disk/o1/tools/le/certs/www.example.com/cert.pem;
  # Extra configuration from modules:

  ssl_trusted_certificate    /data/disk/o1/tools/le/certs/www.example.com/chain.pem;
```

**Comment by luxio** [comment]
@attiks thanks.
