### ISSUE TITLE
Error: require_once(): Failed opening required 'ctools_export_ui.inc'

### ISSUE THREAD

**Issue by serhatozkara** [omega8cc/boa#1088]
I'm constantly getting this from tasks while importing sites to Aegir from non-aegir hosted installations. Every tasks fails with this error: 
Drush command terminated abnormally due to an unrecoverable error.
Error: require_once(): Failed opening required '/data/disk/.../static/.../profiles/hostmaster/modules/contrib/ctools/plugins/export_ui/ctools_export_ui.inc' (include_path='.:/opt/php56/lib/php') in /data/disk/.../static/.../sites/all/modules/ctools/includes/plugins.inc, line 477
There are no issues with command line drush commands like "cc all" , "rr"

**Comment by omega8cc** [comment]
Please always follow [guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt).

**Comment by serhatozkara** [comment]
I do. https://learn.omega8.cc/import-your-sites-to-aegir-in-8-easy-steps-109

**Comment by serhatozkara** [comment]
Well, turns out, hosting-queue daemon script was running under default "aegir" user which was wrong.

**Comment by omega8cc** [comment]
I don't mean docs, but issue queue guidelines which you don't follow.

Also, "hosting-queue daemon script"? It is not used in BOA at all.

**Comment by serhatozkara** [comment]
My bad, sorry about not following guidelines. But, I never knew "Hosting queue daemon" not used in BOA. It is not mentioned anywhere. It is recommended to be used in 2.x+ AFAIK somewhere in the install Docs.

**Comment by omega8cc** [comment]
> It is not mentioned anywhere

Because it is not used.

> It is recommended to be used in 2.x+ AFAIK

Not with BOA, which supports multiple Aegir Octopus instances on the same system.

**Comment by serhatozkara** [comment]
I thought it should be used in octopus instances but not on master...
