### ISSUE TITLE
Replace the complex public IP detection with an external API

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1089]
I was doing an installation on Scaleway, where the servers have a private and a public IP address, and BOA is unable to pick up the public IP (it's not visible directly in eth0 config).

So I used `boa in-stable public web01.example.nl info@email.com o1 none nodns`. This failed the DNS test - perhaps expected, because I had not yet configured _MY_OWNIP correctly because .barracuda.cnf did not yet exist. First question: **what is the correct way to use the nodns option (i.e. how to provide the correct _MY_OWNIP on first run)?**

So after the first `boa in-stable` attempt I corrected the _MY_OWNIP configuration in the now available .barracuda.cnf, and ran `boa in-stable public web01.example.nl info@email.com o1 none nodns` again. But this still failed the DNS test, even though all settings were now correct:

> BOA [15:21:47] ==> EXIT on error due to invalid DNS setup
> 
> ```
> * Your custom _MY_OWNIP is set to "12.34.56.78"
> * Your custom _MY_HOSTN is set to "web01.example.nl"
> * Your custom _MY_FRONT is set to "master.web01.example.nl"
> 
> * Your _MY_HOSTN and/or _MY_FRONT doesn't match your _MY_OWNIP,
>   or your hostname is not set properly yet.
> ```

My configuration:

> web01:~# uname -n
> web01.example.nl
> web01:~# curl icanhazip.com
> 12.34.56.78
> web01:~# host web01.example.nl
> web01.example.nl has address 12.34.56.78
> web01:~# host master.web01.example.nl
> master.web01.example.nl has address 12.34.56.78

So the displayed _MY_OWNIP in the error message actually does match both _MY_FRONT and _MY_HOSTN; and DNS settings have propagated. It looks like the DNS test is actually still run, but the test does not use the values configured in .barracuda.cnf, although it does display them later on.
It also looks like the `nodns` argument should have written `_DNS_SETUP_TEST=NO` in .barracuda.cnf, but it was absent. After manually adding _DNS_SETUP_TEST=NO to .barracuda.cnf the installation succeeds. Second question: **is it a bug that _DNS_SETUP_TEST was not written to /root/.barracuda.cnf with the nodns option?**

**Comment by omega8cc** [comment]
Hmm.. The `nodns` option was intended mainly for debugging and may not work on all systems, because of the environment differences BOA is not aware of. It is also possible that it got broken at some point, because we didn't need/test it for a very long time.

That said, the `nodns` is not a replacement for vendor specific support, like for Amazon EC2.

**Comment by ar-jan** [comment]
Beside fixing the nodns option, would it make sense to get the public IP address from an external API instead of from the internal network configuration? Something like `curl -s https://api.ipify.org`, `curl http://ip4.icanhazip.com`, etc.?

**Comment by omega8cc** [comment]
Good idea. This could simplify a lot of the crazy code we have in place.
