### ISSUE TITLE
How to work with 301 Redirects

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1090]
I have migrated a client site onto a BOA platform and have noticed that their .htaccess redirect links from old site pages to new site pages no longer work. A quick google confirms that htaccess does not work with Nginx and I noticed that the redirect module does not work either.

My question is - what is the best place within BOA that I should be adding these 301 redirects so that they migrate correctly with the platform?

Thanks in advance for any advice

**Comment by omega8cc** [comment]
You can use the redirect module for all URLs which don't end with .php, .html, . jpg or similar extension.

Custom redirects on the Nginx level are supported via extra includes, as [explained in the docs](https://github.com/omega8cc/boa/blob/master/docs/HINTS.txt) (with a few examples).

**Comment by iaminawe** [comment]
Thank you - unfortunately the old site urls end in .php so thats why redirect was not working. I will read the docs and try and work out what I need to do for these existing urls. Thanks for your help.

**Comment by omega8cc** [comment]
It will be easy! See: https://github.com/omega8cc/boa/blob/master/docs/HINTS.txt#L72

**Comment by iaminawe** [comment]
Perfect! Thank you
