### ISSUE TITLE
How to set the php version when creating a new octopus instance?

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#1092]
When creating a new octopus instance with `boa in-octopus` the php version is set to 5.6. 

PHP 5.6 can't be installed on my server (`sed: can't read Makefile: No such file or directory`, s #999)

Is it possible to create a new octopus  #instance with php-5.5? 

[boa info](https://gist.github.com/luxio/aa8520f5afc621cb24ba8c046e726b77)

**Comment by omega8cc** [comment]
Have you tried to start the installation and halt it early enough, so it will create octopus config file, which you can modify to switch PHP version to use and then run the install command again?

Not sure if this is going to work, but currently it is not possible to specify PHP version on boa install command.

**Comment by luxio** [comment]
> Have you tried to start the installation and halt it early enough, so it will create octopus config file, which you can modify to switch PHP version to use and then run the install command again?

I have tried it, but it did now work.

As I finally managed to install php 5.6 after installing some packages installing the new octopus instance with 5.6 works for me.
