### ISSUE TITLE
Custom Cron jobs

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1093]
I have a situation where I need to be running a custom cron job every 5 minutes on a BOA server to save a webcam snap onto the server.

I added my custom cronjob code using crontab -e as root user. For about 3 weeks it was working great then its stopped working. I ran a Barracuda Update and also an Octopus One and I still had no luck with getting my custom cron job restarted.

I tried the technique mentioned here https://github.com/omega8cc/boa/blob/a63d7610e5e1a977fb8808d52afa2be9585db52b/CHANGELOG.txt#L5871 with the custom.txt file and could not get that to run either.

In reviewing my system logs I found server CRON[7693]: Authentication token is no longer valid; new one required - which further reading suggests is because my root password has expired.

I also noticed on running the upgrades that my customizations using crontab -e as root were overwritten

Please can you let me know what the best practice here is - I would prefer to be running cron as my octopus user and would like to retain my changes on update as well as avoiding the expiring password problem. What should I be doing here? I have looked through so much documentation and have yet to find anything on setting custom cron jobs other than that link above and that was from quite an older version so I am not sure if its still relevant.

Thanks in advance for any help

**Comment by omega8cc** [comment]
Add your custom cron entry to `/etc/crontab`

**Comment by iaminawe** [comment]
Thank you for the clarification thats great to know the "right" place to put them.

I have noticed though that after running the most recent barracuda/octopus updates again - both the hostmaster queue and my custom cron commands are not running automatically.

I have tried the following troubleshooting steps to get the system cron and Aegir queue running again and I cannot seem to get things running automatically again after reading other issue postings on this topic

- updating both barracuda and octopus
- rm -r /data/disk/o1/.tmp/cache/download
- touch static/control/clear-drush-cache.info
- deleted any pid from static/control/
- rebooted server

If I run php /var/aegir/drush/drush.php @hostmaster hosting-cron —debug it runs with no errors

When I run this /var/aegir/drush/drush.php '@hostmaster' hosting-dispatch --debug it runs the task queue correctly without errors.

I have just run all updates again and all run without error but right out the gate my Octopus instance task queue is stuck.

Any ideas on how I can troubleshoot this further? 

Thank you for the great support you always give.

**Comment by omega8cc** [comment]
If `touch ~/static/control/clear-drush-cache.info` doesn't help (it should, just wait a few minutes), then run this:

`rm -rf /data/disk/o1/.tmp/*`

I believe that we have improved this in BOA head already.

**Comment by iaminawe** [comment]
I have done both of those suggestions now but my task queue is still not running.

I have the following messages recurring in my syslog - what is the best BOA way to generate a new Authentication token?

Nov 13 10:26:01 server CRON[25986]: (aegir) CMD (/usr/bin/env php /var/aegir/drush/drush.php '@hostmaster' hosting-dispatch >/dev/null 2>&1)
Nov 13 10:26:01 server CRON[25982]: Authentication token is no longer valid; new one required

**Comment by omega8cc** [comment]
This error has nothing to do with your Octopus instance cron, since it is for the master instance you should not use for anything. That said, this error makes no sense to me..

You must have something unusual (modified) on your system?

Please attach the result of `boa info` command.

**Comment by omega8cc** [comment]
Also, have modified root account somehow? Like by forcing password expiration?

Have you tried to update root password to see if this helps?

**Comment by iaminawe** [comment]
I have not modified the root account at all - absolute stock default from BOA install.

I had not tried to update root passwd for fear of incurring BOA's paranoid idiosyncratic wrath :)

I just did this using 'passwd root' and it seems to have fixed it completely - my hostmaster queue is running correctly as is my site cron. Thanks for your help - this issue can be closed.

**Comment by omega8cc** [comment]
Interesting. We never use passwords for root, but we have also never seen the root password to just expire, unless explicitly configured to expire.

**Comment by iaminawe** [comment]
The server I am using is a Digital Ocean droplet that I chose to provision using my existing ssh key so I believe no root password is generated by default and access is only via ssh. 

Things seemed to work fine for a month or two before cron stopped working and I received the token issue. I believe this is a digital ocean issue and not a BOA one as I see someone else also having this issue https://www.digitalocean.com/community/questions/root-password-expired-upon-droplet-creation
