### ISSUE TITLE
duplicated hostname in vhost files after migrating to old.example.com with LE turned on

### ISSUE THREAD

**Issue by danielbeeke** [omega8cc/boa#1095]
Self hosted boa.
Boa info
https://gist.github.com/danielbeeke/eccafe461796fd8204dd6599f5f57fa2

We used to do a deployment of a site in the following way:

Create new platform, from git clone
Clone production to the new platform with a 'staging' domain name
Migrate production to the same platform but with 'old.example.com'
Migrate staging to production name on the new platform

When we do this with LE ssl turned on, but turend off when migrating a site. It creates a vhost in
/data/disk/o1/config/server_master/nginx/vhost.d with the new site name but somewhere in the lines is the old site name in a server_name statement.

**Comment by omega8cc** [comment]
This may happen especially when you have enabled redirection on the renamed site before, and the redirection target is an alias and not a main site name. Always disable redirection if you plan to swap names between sites like this.

Also, check the docs for workarounds mentioned here: https://learn.omega8.cc/how-to-debug-failed-migrate-task-328

**Comment by dnotes** [comment]
I got tripped up by this as well, and I think it deserves a mention in the documentation. I think this may be more serious than you realize, because my redirection was pointed to the main site name, and the only alias was the automatically created www domain.

**Comment by omega8cc** [comment]
I have commented on this also at https://github.com/omega8cc/boa/pull/1109#issuecomment-272962754
