### ISSUE TITLE
Auto-renew for let's encrypt doesn't work

### ISSUE THREAD

**Issue by kazdegroot** [omega8cc/boa#1098]
BOA Info to be found here: https://gist.github.com/kazdegroot/61deb440ce708adc1bd371cbc0c4c07a. 
Hosting on Linode.

Found yesterday that one of the sites on my BOA instance had a lapsed SSL certificate; when attempting to run a verify to fix that, found out the octopus site did as well. 
While I can find the code in /var/xdrago/daily.sh (and linked from #942), it doesn't seem to trigger.
/var/xdrago/log/le is empty too.

Running verify from within aegir fixed the issues, but I'm not sure why the auto renew didn't work.

**Comment by omega8cc** [comment]
Please check the corresponding `/var/xdrago/log/daily/daily-yymmdd-hhmm.log` file when it was expected to renew and make sure it doesn't report errors for this site.

We couldn't reproduce the problem.

**Comment by kazdegroot** [comment]
Checked the logs, and all my sites are reporting as 'THIS SITE IS PROBABLY BROKEN', though all of them seem to work. 

`drush status` also works, but behaves oddly when executed from the root account. Failing silently on database initialisation, instead of failing directly with a 'drush shouldn't be run as root'

**Comment by omega8cc** [comment]
You should never run drush as root. Always switch to `o1` or `o1.ftp`

Something must be wrong or broken there if all sites are reported that way. Are you running Drupal 8 only or some ancient Drupal 6 only? or maybe some too old PHP version?

Try this:

`su -s /bin/bash - o1`
`drush @sitename status`

Then:

`su - o1.ftp`
`drush @sitename status`

**Comment by omega8cc** [comment]
By th way, we allow to run `drush @sitename status` from root, but depending on the core version, you may need to run `drush7 @sitename status` instead. Because Drush 8 doesn't like root.

**Comment by kazdegroot** [comment]
Seems the weekly verify started working correctly again since a recent update. 
Thanks for the response!

**Comment by omega8cc** [comment]
Thanks for the update!
