### ISSUE TITLE
SSL-Cert for Hostmaster Site is expired

### ISSUE THREAD

**Issue by mabo1972** [omega8cc/boa#1100]
I have activated le for the hostmaster site  (BOA 3.1.3) like described in the docs. Up till now this worked well.
But now i get an cert expired message in the browser.
A verify of the hostmaster site in aegir could not resolve the problem.

What can i do to renew the cert?

**Comment by omega8cc** [comment]
Please check the verify task log and expand all long lines which start with `[hosting_le]` for details on what happens there.

**Comment by mabo1972** [comment]
![grafik](https://cloud.githubusercontent.com/assets/8982685/20825110/351357bc-b862-11e6-8d84-63de63af70f8.png)

**Comment by mabo1972** [comment]
anybody an idea which could cause this problem?

**Comment by omega8cc** [comment]
No idea, sorry, we couldn't reproduce the problem. When exactly it worked and when stopped working?

**Comment by mabo1972** [comment]
after the upgrade to BOA 3.1.4 LE works again. I take a closer look to this when its happened again.

**Comment by omega8cc** [comment]
Thanks for the update.
