### ISSUE TITLE
Option to disable 90 days password expiration

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#1101]
As explained in docs : _"...BOA forces all users to update their passwords every 90 days.."_

We have several websites where external processes upload files by SFTP to them using AEgir clients credentials (for import cron tasks, logs, synchronization of info, etc..)
The problem with this password lifetime is that once it's expired the SFTP won't connect anymore and we need to remember to send to the external providers/customers the new password we need to regenerate every 3 months. 
We are not very happy to do this every 90 days for tens of websites, they are not very happy to change their sftp/processes' credentials every 90 days neither :disappointed: 

Would be nice to have an option to disable this expiration or at least to expand it to 1 year lifetime.

Thoughts?

**Comment by omega8cc** [comment]
You can "disable" this by adding proper SSH keys. It is a very bad idea to use passwords for SSH/SFTP, and using never expiring passwords is even worse idea.
