### ISSUE TITLE
SSL / HTTP2 Performance gains and the correct configuration

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1102]
Just wanted to clarify the new SSL configuration and how to maximise its benefits.

1. I understood it from the announcement that http2 is a performance gain, but couldn't understand clearly how it is supposed to be set up in order to get the benefits.

Is it configured to allow the admin to drop a real SSL cert in place or are admins simply enforcing SSL with the auto generated invalid certs?  That seemed odd to me as all the enforce SSL sites would then complain the cert was invalid.  It seemed there is a piece of the puzzle not explained clearly but perhaps I might have overlooked or read something incorrectly?

**Comment by omega8cc** [comment]
It is automated, you don't configure anything. All you need to do is just to follow the docs at: https://github.com/omega8cc/boa/blob/master/docs/SSL.txt

You enable HTTPS per site, and you don't need to force HTTPS, but it is recommended once you have tested that it works with HTTPS enabled on the site.
