### ISSUE TITLE
Upgrading platforms fails for me

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1104]
Hello 
Here is the info concerning my system : 
https://gist.github.com/yazzou/53a221896ac99f712b9beff73edbc7be#file-boa-info

I have tried to update my drupal (currently 7.50.1) core by following the upgrade procedure : 
barracuda up-stable system   
octopus up-stable all force

The output says that the upgrade is complete but i do not see any new platform (https://gist.github.com/yazzou/fbac96304ac4b2ddbd0749f9b8b7fcfe)

**Comment by omega8cc** [comment]
It is expected because 3.1.3 was a Barracuda Edition and not a Full Edition.

We plan to release full 3.1.4 this week.
