### ISSUE TITLE
Clean install, 502 on http://o1.server2.aegirhosting.nl/

### ISSUE THREAD

**Issue by danielbeeke** [omega8cc/boa#1105]
Clean install on digital ocean this morning.

cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
boa in-stable public server2.aegirhosting.nl developers@studiofonkel.nl o1 none NEWRELICKEYREPLACED
reboot
barracuda up-stable
reboot

http://o1.server2.aegirhosting.nl/ gives a 502
https://adminer.master.server2.aegirhosting.nl/ gives a 404

Something seems to go wrong, could it be that I have missed some documentation?
I have tried installing it via docs/INSTALL.txt

**Comment by danielbeeke** [comment]
boa info
http://pastebin.com/raw/rdyFmU1x

**Comment by danielbeeke** [comment]
After turning on _DEBUG_MODE=TRUE in /root/.barracuda adminer seems to work.
I saw a couple of can not stat notices while upgrading.

**Comment by danielbeeke** [comment]
I changed the dns this morning, could it be that the server itself could not see it's dns correct?

**Comment by danielbeeke** [comment]
I destroyed the droplet and started again:

cp: cannot stat �/opt/php56/lib/php.ini�: No such file or directory

chattr: No such file or directory while trying to stat /home/o1.ftp/platforms
chattr: No such file or directory while trying to stat /home/o1.ftp/platforms/*
chattr: No such file or directory while trying to stat /home/o1.ftp/.drush
chattr: No such file or directory while trying to stat /home/o1.ftp/.drush/usr
chattr: No such file or directory while trying to stat /home/o1.ftp/.drush/*.ini

BOA [13:31:32] ==> BYE!
cp: cannot create regular file '/opt/php56/etc/pool.d/o1.conf': No such file or directory
chattr: No such file or directory while trying to stat /home/o1.ftp/.drush/*.ini

**Comment by danielbeeke** [comment]
php 7.0 is also not installed in the second try

**Comment by danielbeeke** [comment]
2016/12/21 15:11:33 [crit] 10135#0: *2243 connect() to unix:/var/run/o1.fpm.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: o1.server2.aegirhosting.nl, request: "GET /?nocache=1&noredis=1 HTTP/1.0", upstream: "fastcgi://unix:/var/run/o1.fpm.socket:", host: "o1.server2.aegirhosting.nl"

The socket does not seem to be there.

**Comment by danielbeeke** [comment]
I changed /data/disk/o1/config/includes/nginx_vhost_common.conf

if ($user_socket = '') {
  set $user_socket "o1";
}

to

if ($user_socket = '') {
  set $user_socket "www70";
}

Now something seems to work. What can this be?

**Comment by danielbeeke** [comment]
https://gist.github.com/danielbeeke/dadcb5638374a4569d67ff0bc9d60b56 output of service --status-all

**Comment by danielbeeke** [comment]
In the gist you see 
[ + ] php56-fpm
[ + ] php70-fpm

while /opt gives:
etc/  local/  php53/  php54/  php55/  php56/  php70/  tmp/  tools/

**Comment by omega8cc** [comment]
Indeed, something is clearly broken on clean install. I guess we have tested this only on VServer machines, so it worked w/o issues. Thanks for the report.

**Comment by dev286** [comment]
The same thing happening on Linode (KVM) / Debian 8 / USA

**Comment by omega8cc** [comment]
This has been fixed in head and stable. Thanks for the report!
