### ISSUE TITLE
Migration procedure should use Let's Encrypt certificates in HTTPS proxy vhosts, if available

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1106]
Does the [migrate](https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt) procedure also take care of migrating https certificates (Let's Encrypt or other)? Thanks!

**Comment by omega8cc** [comment]
Yes: https://github.com/omega8cc/boa/commit/16849f5a9f38d72652dbb0dd6b68e614bacd7394

**Comment by omega8cc** [comment]
However, the proxy vhost created for zero-downtime migration will not use LE certs, so this is something we need to improve, I think.

**Comment by omega8cc** [comment]
Fixed!

**Comment by ar-jan** [comment]
Great, thanks!
