### ISSUE TITLE
Ultimate Cron forced disabled. Why?

### ISSUE THREAD

**Issue by thebennos** [omega8cc/boa#1108]
Hey 

Found in
https://github.com/omega8cc/boa/blob/master/docs/MODULES.txt

that the ultimate cron module get forced disabled.
Why? (Searched the issues and found nothing) 

Need a module to manage the cron jobs better.
Is there a compatible alternative or can I use ultimate cron with some known sidekicks?

**Comment by omega8cc** [comment]
It is known to be able to cause serious performance issues, basically, to self-DoS the server. No idea if the problem has been fixed, so for now it is by default banned. [You can whitelist it, though](https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L31). Like:

`_MODULES_SKIP="foo bar etc"`
