### ISSUE TITLE
When and when not to upgrade also the Master Instance

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1110]
When installing BOA for the first time, as far as I understood it requires also the upgrade
barracuda up-stable
This asks me if I also want to upgrade the master instance. When is that necessary and when not? 
Why does it create a new master instance instead with a number?

**Comment by omega8cc** [comment]
You should upgrade master instance when you upgrade to new BOA version. For other upgrades use system-only barracuda upgrade, which skips Aegir master upgrades automatically. if in doubt, follow the docs.
