### ISSUE TITLE
Another BOA installer is running probably because  /var/run/boa_run.pid exist

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1111]
For some reason my putty session ended itself in the middle of the BOA upgrade after I did barracuda up-stable. It was actually asking me if I wanted to install "Collectd" graphics, which I did not answer and then the putty connection broke.
Now I logged in again but dont see the same session showing up. Instead i get
"Another BOA installer is running probably because  /var/run/boa_run.pid exist"

How do i complete the first installation, and does it harm if I remove the pid file and just do the barracuda up-stable again?

**Comment by Corvalan** [comment]
I now started a new session and typed in $ screen -r
This brought the previous session/screen back, but actually showed that the upgrade was completed. Apparently the upgrade script did not have the patience to wait for my answer and just continued upgrading. However, now I have no idea what it actually did and did not install/upgrade.

**Comment by Corvalan** [comment]
...and the pid file is still preventing further installations or upgrades.

**Comment by omega8cc** [comment]
Delete these pid files and try again.
