### ISSUE TITLE
Error while trying to find the common path for enabled extensions of [error] project advagg.

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#1114]
Error while trying to find the common path for enabled extensions of [error]
project advagg.

o1.ftp:~$ drush @haveread.com dl flag --select
Error while trying to find the common path for enabled extensions of [error]
project advagg. Extensions are: advagg, advagg_bundler,
advagg_css_cdn, advagg_css_compress, advagg_ext_compress,
advagg_font, advagg_js_cdn, advagg_js_compress, advagg_mod,
advagg_sri, advagg_validator.

Im running the latest stable ver.... using open atrium I get this error in drush...

**Comment by omega8cc** [comment]
No idea what this means (how the flag module is related to advagg) I guess you should post in OA queue on drupal.org?
