### ISSUE TITLE
Make boost cache clear configurable

### ISSUE THREAD

**Issue by angel0d** [omega8cc/boa#1115]
hi

@omega8cc would you consider/accept patches to make the removing of boost caches configurable ?

instead of daily by default, it could be weekly or never

if yes should it be a global setting (.barracuda.cnf) or a per site control variable/file ?

in our case we had work hard to support permanent caches on specific paths where the expiration can be fine tuned with custom expire hooks and a custom crawler so that anonymous users (or bots, crawlers) never get to hit php/sql but rather get a relatively recent content

**Comment by omega8cc** [comment]
Yes, patches are always welcome! Thanks!

**Comment by angel0d** [comment]
@omega8cc 

I can confirm that updated daily.sh has arrived and after configuring the control variable it works as expected
