### ISSUE TITLE
How to add thousands of aliases to a site in boa

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1117]
Until now I have not understood how to create a drupal site in boa/aegir that catches all domains (a default site).  I hope someone can shed some light on that.

As a workaround I now decided to create aliases instead, but the problem is that I need about 2000 aliases for one single site (landing pages for domain names).

Not sure if anyone has eperience with this use case. Is there a way to bulk-add these aliases? A drush script maybe?

**Comment by angel0d** [comment]
@Corvalan see the options in `drush help provision-save` like ` --aliases site: comma-separated URIs `

as I mentioned in the other issue there some performance implications from very long server_names

see also : http://nginx.org/en/docs/http/server_names.html#optimization

**Comment by omega8cc** [comment]
You can add a wildcard alias, like:

`*.example.com`

instead of adding:

`foo.example.com`
`bar.example.com`
`etc.example.com`

But you can't add wildcards like:

`*.com`
`*.org`
`*.net`

because Aegir doesn't allow this, for obvious reasons -- this type of wildcard could easily take over all other sites hosted on the same server.

See the code responsible for this filtering: https://github.com/omega8cc/hosting/blob/feature/3.0.x-hosting/hosting.inc#L73

**Comment by omega8cc** [comment]
So, to make it possible, you would have to:

1. Make sure no other sites are hosted on the same server, other than the "wildcard" site
2. Modify the code in `_hosting_valid_fqdn_wildcard()` to allow `*.com` type wildcards
3. Add wildcard aliases in the Aegir interface for all expected domains extensions

**Comment by omega8cc** [comment]
But make sure the wildcard doesn't take over your hostmaster site! Just make sure the wildcard main site name starts with something like `zzzyyyxxx`, so its vhost is loaded *after* the hostmaster vhost.

**Comment by angel0d** [comment]
@omega8cc 

according to nginx documentation in http://nginx.org/en/docs/http/server_names.html#optimization

> The exact names hash table is searched first. If a name is not found, the hash table with wildcard names starting with an asterisk is searched. If the name is not found there, the hash table with wildcard names ending with an asterisk is searched.

i tested this successfully in #1112 

hostmaster site worked fine when using its TLD on a hosted site server_name directive

**Comment by angel0d** [comment]
also I think that a wildcard site alias would work when redirection is enabled which is not the use case of the OP

**Comment by omega8cc** [comment]
@angel0d Ah, you are right. Thanks.

**Comment by Corvalan** [comment]
I have nearly accomplished my goal of (theoretically) unlimited domain aliases on one drupal site in boa. Thanks for the guidlies, guys.

As advised by you I did not delete the default server blocks.
I did not use the server_name www.*; option because I indeed couldn't figure out how to redirect non www domains in the www version.

Here is the setup that worked:

I imported my drupal site 'example.com' in data/disk/o1/static/examplecom/

I symlinked sites/default to sites/example.com. (otherwise no show (404) for other domains than example.com)

I manually created another new vhost file:
data/disk/o1/config/server_master/nginx/vhost.d/all.tlds
which is a clone of the vhost example.com, except from the following:

server_name *.com *.net *.org *.stream *.group *.com *.sale *.bio *.insure (and about 200 other tlds)

include   /data/disk/o1/config/includes/nginx_vhost_common_alltlds.conf;

I Created a new configuration file 
data/disk/o1/config/includes/nginx_vhost_common_alltlds.conf 
whish is a clone of nginx_vhost_common, except from:

location /   {
rewrite ^/?$ /landingpage/$http_host break;
}

..which results in each domain name showing its own landing page, ie. 
http://foo.com will serve http://foo.com/landingpage/foo.com while the URL in the browser stays the same http://foo.com. 

The reason for creating a new server block with new configuration file, is:
- the all.tlds block has a different location / and different configuration (rewrite)
- nginx will first select example.com before the alltlds server. This is better for performance, because 9 out of 10 visits will be on example.com
- it may be done more efficiently but this is what finally worked.

HOWEVER... After waking up the next morning, my boa had happily deleted the two files all.tlds and nginx_vhost_common_alltlds.conf.  I didnt expect that complete files would be deleted.

Angel0d suggested in #1112 injecting a configuration snippet using  provision_nginx_vhost_config() as explained in the aegir documentation page http://docs.aegirproject.org/en/3.x/extend/altering-behaviours/#injecting-into-site-vhosts

..but I'm drupal site builder, not an experienced programmer, so I have difficulty with creating such a module that injects or prevents deletion of the all.tlds vhost and its configuration file.

Feedback is very welcome

**Comment by omega8cc** [comment]
@Corvalan Use `--CDN` suffix for custom vhosts to avoid having them deleted. They were not really deleted, only moved to `/data/disk/o1/undo/` directory. Example safe filename: `all.tlds--CDN`

BOA will not delete any files from `/data/disk/o9/config/includes/` but please use more unique filename, for example `nginx_vhost_alltlds.conf`

I hope this helps!

**Comment by Corvalan** [comment]
Yes, that works. Thanks! 
Case closed :-)

**Comment by omega8cc** [comment]
OK, nice!
