### ISSUE TITLE
Increasing memory limit.

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1119]
Hi,

I have looked through a range of articles on this topic and cannot seem to find one that deals specifically with increasing the memory limit in a recent version of BOA.

I tried adding these to local.settings.php in the sites folder
ini_set('max_execution_time',1000);
ini_set('memory_limit','512M');

The execution time worked but the memory limit did not.

I then tried updating the php.ini at /opt/php56/etc/php56.ini and then service php56-fpm reload

When I view the php.info from the sites status report - it does not look like the memory limit changed at all

Can you please provide some guidance with how I would do this please

Thanks
Gregg

**Comment by omega8cc** [comment]
There is already feature request, with many useful comments: https://github.com/omega8cc/boa/issues/559

**Comment by omega8cc** [comment]
A quick "fix" (but it will not survive upgrades) is to edit `/opt/etc/fpm/fpm-pool-common.conf` file -- see the line `php_admin_value[memory_limit]`

**Comment by omega8cc** [comment]
By the way, it is already explained in the docs: https://github.com/omega8cc/boa/blob/master/docs/FAQ.txt#L48

**Comment by iaminawe** [comment]
Thanks for the quick reply and apologies for for the duplicate ticket. May I suggest that you remove "after BOA-2.2.0 upgrade" from the question title in the FAQ as it suggests that it may only have relevance to the older version. Great support as always. Thank you.

**Comment by omega8cc** [comment]
Thanks!
