### ISSUE TITLE
Dynamic DNS and BOA

### ISSUE THREAD

**Issue by superfedya** [omega8cc/boa#1120]
Hi,

Is there somethings special about BOA install on server with no fix IP? I use Dynamic DNS.
Any special config?

Thanks

**Comment by omega8cc** [comment]
We never tried this with non-static IP address, but it should work, I think, since we are using wildcard listen directive in web server and localhost connections for DB access. Let us know if you will experience any issues -- especially on upgrade.

**Comment by superfedya** [comment]
Thanks

I disabled DNS check during install process. And after the script was unable to create "o1.server.mysite.com" because server.mysite.com pointed to my LAN IP, and DNS for this domain pointed to my WAN IP. So, BOA is installed, I can access server.mysite.com and see "under construction".

But I cannot access o1.server.mysite.com and control BOA.

My help?

Thanks

**Comment by omega8cc** [comment]
Then it is not going to work, sorry!

**Comment by superfedya** [comment]
Thanks really sad :( Many people use dynamic DNS.

**Comment by omega8cc** [comment]
I don't know anyone using server with no fixed IP address. You mean using dynamic DNS for BOA hosted locally on your computer, perhaps?

**Comment by superfedya** [comment]
Yes, local on my server, but for production.

**Comment by angel0d** [comment]
@superfedya  did you try to make all domains point to your LAN IP (which you can make sure that it does not change), see if then the install succeeds and then switch the DNS back to your WAN IP ?

also when the installed stopped it should have already created /root/.o1.octopus.cnf

there is another instance of `_DNS_SETUP_TEST=YES` in that file. did you try changing it there too and re-run the install ?
