### ISSUE TITLE
Install ClamAV on BOA server - good idea or bad?

### ISSUE THREAD

**Issue by andrilablateral** [omega8cc/boa#1121]
Hello team BOA

Would would like to install this Drupal module - https://www.drupal.org/project/clamav - in order to scan uploaded files for any viruses. It works in conjunction with ClamAV so I thought I'd first check to see if;

1. installing ClamAV on BOA is a good / or bad idea?
2. if not a good idea - does BOA already check uploaded files for viruses?

Thank you!

Andri

**Comment by omega8cc** [comment]
Hi,

It is already included by default (in HEAD, at the moment): https://github.com/omega8cc/boa/issues/1019

**Comment by andrilablateral** [comment]
Hi,

I was hoping to get it under a stable release today, but noticed that the 3.2.0 milestone has now been pushed back to mid-February.

Can I go ahead and manually install ClamAV? If so, any special method to it so that the 3.2.0 release will go smoothly?

**Comment by omega8cc** [comment]
You can install it manually, since will not do anything special to it.

**Comment by omega8cc** [comment]
Yeah, we expected 3.2.0 already, but there are some issues discovered in Aegir we want to fix first, and we couldn't do another 3.1.x after too much stuff was already pushed to HEAD in anticipation of 3.2.0
