### ISSUE TITLE
ALRT! MariaDB server not running properly!

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1122]
I noticed over the weekend something had changed in the daily upgrade script to break mysqld.
I realised mysqld wasn't running so gave it a: service mysql restart
It failed to start.

I checked all the logs and found in the /var/log/syslog when trying to start mysqld.
[ERROR] /usr/sbin/mysqld: unknown variable 'innodb_buffer_pool_dump_at_shutdown=1'

So I assumed this had been deprecated and removed the config from /etc/mysql/my.cnf and commented out the offending line.

Tried to start up mysqld again and got the same error but a different variable this time:
[ERROR] /usr/sbin/mysqld: unknown variable 'innodb_buffer_pool_load_at_startup=1'

removed that and tried again but got this variable:
[ERROR] /usr/sbin/mysqld: unknown variable 'innodb_buffer_pool_dump_pct=100'

I removed that and voila, the daemon is back up and running now.
Bit of a pain that an upgrade broke our system and that this hasn't been communicated out if it is a new or old problem.

Just wanted to leave something for any others that may come across this on their own self hosted BOA.

**Comment by omega8cc** [comment]
This may happen when:

1. You trust BOA HEAD to never break on automated upgrades (bad idea)
2. You are running old MariaDB version 5.5, while HEAD switched to 10.1

By the way, BOA doesn't run daily upgrades, it runs weekly upgrades, if you have told it to run them (it is not ON by default).

**Comment by karudonaldson** [comment]
The last time we spoke, BOA HEAD was advised to be used instead of stable.  
I've also seen this mentioned several times elsewhere online.

Agreed, I don't normally do daily upgrades especially from HEAD but in this situation where you never can keep up with releases, I chose to take that risk so I'll own that.  

If weekly automated upgrades are ok, how are self-hosted instance admins supposed to know when significant releases are out without running an automated upgrade?  

I subscribe to this repo, try to stay connected on gitter and assumed emails would circulate when significant upgrades are posted.  If only I knew when to run HEAD or stable at the right time I'd follow that, it's quite simple.  Also, if I need an upgrade, where is the best place to consistently follow to know that?  Twitter?  Email?  github?  gitter?  It's not super clear at times.

Finally, am I safe to switch to MariaDB 10.1 now?  Can you point me in the direction of docs to read about the changes particular focus with regards to hosting Drupal on BOA?

**Comment by omega8cc** [comment]
HEAD was never "advised" to be run on production systems.

If you ask us, we may confirm if it works at the current moment like "stable". But it is valid only for the moment you ask.

You can run HEAD at your own risk only.

**Comment by omega8cc** [comment]
As for mew releases, it is very simple: we always announce new BOA release on Twitter and Gitter. Plus, you can subscribe to GitHub RSS, if you want.

If you prefer to live on the edge, you are welcome, but then you must follow everything we do with HEAD and take action when needed, like, when we announce that from now on MariaDB 10.1 is new default version supported.

You should be aware of it, if you pay any attention to release notes.

And [we have announced it already in BOA-3.1.4](https://github.com/omega8cc/boa/blob/BOA-3.1.4/CHANGELOG.txt#L21)

**Comment by omega8cc** [comment]
Also BOA will notify you automatically via e-mail (daily) when new release is available if you still run previous stable. Not sure how this can be done any better, but suggestions are always welcome.
