### ISSUE TITLE
PHP 7.3, 7.2 and 7.1 Support

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#1126]
Just wanted to know if there is anything currently blocking PHP 7.1 support on _PHP_MULTI_INSTALL setting? It seems that PHP 7.0 is similar to 7.1 version. Let me know why we only can use PHP 7.0. Cheers.

**Comment by omega8cc** [comment]
PHP 7.1 is not the same as 7.0, and the difference is not just .1 digit added -- so, not sure if Drupal 7 is compatible with PHP 7.1 already? The same question about Drush 8.x, I guess. But we could try to add it and then see if it works, perhaps.

**Comment by Pls** [comment]
Yep, it seems that 7.1 is still in progress for Drupal core and there are bunch of issues - https://www.drupal.org/project/issues/search?issue_tags=PHP%207.1

**Comment by omega8cc** [comment]
Yeah.

**Comment by angel0d** [comment]
i checked the issues tagged with php 7.1 and re-checked again now

most of them are fixed and the ones that are still open seem to be causing more confusion than actually telling whether drupal 7 or 8 work with php 7.1

@omega8cc would a detailed report of the still open core issues be of any help ?

**Comment by omega8cc** [comment]
@angel0d -- We plan to just go ahead and add PHP 7.1 as supported version. It was already announced [in 7.55 core release](https://www.drupal.org/project/drupal/releases/7.55) that PHP 7.1 passed all automated tests with no major problems reported.

**Comment by yaazkal** [comment]
Drupal core (7.50+ and 8) seems to be fully compatible with PHP 7.1. Now contrib modules can be another thing.

I think it has more sense to add 7.1 now than ever, because 7.0 active support is ending on December (in a few days) and even it ends security support before the end of 5.6 security support; so seems to has more sense to migrate drupal sites from PHP 5.6 to 7.1 and skipt the 7.0 version, anyway 7.1 will have active support until Dec. 2018 and security support until Dec. 2019, so looks like a long term solution.

http://php.net/supported-versions.php

Anyway, seems to be not an urgent feature but a really nice to have one.

**Comment by andytruong** [comment]
We should support PHP 7.2 instead

**Comment by omega8cc** [comment]
I think we need both 7.1 and 7.2 ?

**Comment by EdNett** [comment]
HI,

I agree that we need both 7.1 and 7.2 - drupal 8 PHP requirements do not even support 7.0 - it requires 7.1 or 7.2:


PHP version | Supported | Recommended?
-- | -- | --
5.5 | 5.5.9+ | No
5.6 | Yes | No
7.0 | Yes | No
7.1 | Yes | Yes
7.2 | Yes as of Drupal 8.5.0* | Yes

Thank you for doing this.

**Comment by dsnopek** [comment]
Is there an ETA on this?

PHP 7.0 will stop getting security support on December 3rd of this year (about 3 months from now):

http://php.net/supported-versions.php

Even 7.1 is switching from "active support" to "security support" in December. But PHP 7.1 would still be sufficient to be able to say it's secure.

**Comment by omega8cc** [comment]
This week.

**Comment by yaazkal** [comment]
> This week.

Awesome news !

**Comment by cwaone** [comment]
> This week.

@omega8cc  any updates on this?

**Comment by aanjaneyam** [comment]
Any updates on the availability of PHP 7.1 and 7.2 in BOA?

**Comment by dsnopek** [comment]
@omega8cc Sorry to add to the impatient pinging, but this month is the month that PHP 5.6 and 7.0 are going to become unsupported!

What's the current timeline on PHP 7.1 or 7.2 support in BOA? (Assuming this hasn't be added already, and I missed it?)

**Comment by yaazkal** [comment]
@dsnopek Hi, they are already on HEAD.

Generally speaking head is ok even for production on the last year, but I can see lot of activity last week so not sure how stable it is to use it today, you can test it first on a non production server.

Maybe they are planning to release 4.0.0 soon.

**Comment by dsnopek** [comment]
Oh, awesome! Thanks :-)

**Comment by omega8cc** [comment]
Yes, we will release 4.0.0 this week, and it will come with PHP 7.2 and 7.1, already available in HEAD. There were many backward compatibility issues to fix, so we could still support PHP 5.6 on Debian Stretch, which was a requirement to even work on supporting smooth migration from Jessie. Then there are still some systemd related problems to fix on Stretch before everything works as it should in the easy installation mode. At some point we planned to even abandon Debian and go with systemd-free Devuan or similar, but with time Debian folks changed their stance on forcing systemd, so there is still hope. We will proceed with weekly or bi-weekly releases to keep backward compatibility and reference points for those still running on very old versions or systems.

**Comment by omega8cc** [comment]
We have added support for PHP 7.3, 7.2 and 7.1, but release was delayed first because there was upcoming Aegir release to include, then Aegir regressions and another release, and then the Holidays season when no one should upgrade servers anyway. We are ready for the release this week, finally! Happy New Year!

**Comment by yaazkal** [comment]
@omega8cc thanks so much !!

Happy new year !!

**Comment by luxio** [comment]
@omega8cc any updates for the release date of  4.0.0 ?
