### ISSUE TITLE
Upgrade on Squeeze

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#1132]
Unfortunatly I started the legacy 2.4 upgrade (in silence mode) on a squeeze server without the _SQUEEZE_TO_WHEEZE setting and the upgrade stacked here...

BOA [03:43:52] ==> Skynet Agent v.BOA-2.4.9 welcomes you aboard!
 
BOA [03:43:55] ==> INFO: UPGRADE

BOA [03:44:02] ==> Aegir on server.techangel.me Debian/squeeze x86_64 PHP 5.6
 
BOA [03:44:05] ==> INFO: Installing extra Drush versions...
BOA [03:44:08] ==> INFO: Running system packages update...
BOA [03:44:27] ==> INFO: Upgrading required libraries and tools...
BOA [03:44:45] ==> INFO: Installed OpenSSH version 7.1p1, upgrade required
BOA [03:44:45] ==> INFO: Building OpenSSH 7.1p2 from sources, please wait...
BOA [03:45:40] ==> INFO: Installed cURL version 7.44.0, upgrade required
BOA [03:45:44] ==> INFO: Building cURL 7.45.0 from sources, please wait...
BOA [03:46:46] ==> INFO: Uninstalling previous version of New Relic Apps Monitor...
BOA [03:47:01] ==> INFO: Installing latest version of New Relic Apps Monitor...
BOA [03:47:24] ==> INFO: Running aptitude full-upgrade...

Any suggestions, please?

**Comment by omega8cc** [comment]
When the process seems to stall, in fact it is because it ask you to enter
"YES", so it could proceed further. It will happen *twice* during the
upgrade on Squeeze, and you can see this in the verbose log in
/var/backups/ -- just type YES and hit Enter in the same window where you
have started the upgrade.

**Comment by omega8cc** [comment]
We may need to apply a hotfix for 2.4 to avoid this problem, but at some point you may no longer be able to upgrade from Squeeze, because most of Squeeze packages are no longer available online, which causes these problems.

**Comment by velpan** [comment]
Thank you for your help. I started the upgrade inside a 'screen' session, and then I somehow I lost the connection with the server. Is it possible to continue after a 'screen -r' and press YES ?
And something important: What if 'aptitude' fails to upgrade squeeze? The 2.4 script stops there or continues? Thank you again.

**Comment by omega8cc** [comment]
It should be enough to run `screen -R` after you log in again, and type YES, then hit Enter. Note that this this will happen twice, so run tail -f /var/backups/latest-log-filename` too watch when to type YES etc. Don't worry about anything else. We still run one 2.4 instance for testing, so we know how it works.

**Comment by velpan** [comment]
Thank you for your time.
