### ISSUE TITLE
Can't access Octopus Aegir hosting after upgrade

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#1133]
I upgraded my octopus twice (first time I forgot to change PHP version to 5.6, old value was 5.3)
so after the first time I change values in octopus .cnf file and run upgrade again. Upgrade was succeful both times.

I run "octopus up-2.4 o1 both" command cause I am in BOA 2.4.9  

Now I can't access the octopus hosting system, Nginx redirects to /install.php and ends with 404 not found.
What is happened?

Thank you in advance for your help.

**Comment by angel0d** [comment]
@velpan have you tried to restart nginx manually ? (not reload but restart)

i had similar problems with an older BOA install

**Comment by velpan** [comment]
Yeah, this is it! Thank you @angel0d
