### ISSUE TITLE
Errors on installation of BOA

### ISSUE THREAD

**Issue by chvypwrd** [omega8cc/boa#1134]
I am volunteering my time to help a non-profit fundraising organization to get a Drupal site up for them. Bought VPS hosting with 1GB Ram, Installed Debian 8, 64bit, clean install, no updates.

I am following all BOA installation instructions but getting errors on installation and 502 Bad Gateway when trying to reach the master.xxx.xxxx.com site. The main web address seems to be working and displaying an under construction page. but I am unable to access master.o1.xxx.com as well as o1.xxx.com sites. 

After spending the last week+ of trying, googling, wiping, re-installing over and over - I can't help but believe it has to be a configuration or permissions issue. I ran the `cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`  then `boa in-stable public srv1.mywebsite.org myname@gmail.com o1 max`. Are there other settings I am supposed to change before or after running the installation? 

I have DNS entries  for master.o1.xxxx.com and o1.xxx.com as well as the wildcard "*.xxx.com". 

Any help is greatly appreciated!

**Comment by omega8cc** [comment]
Have you run barracuda system upgrade after rebooting the server once initial installation is complete?

**Comment by omega8cc** [comment]
Also, there is never URL like master.o1.xxxx.com created. Please read the welcome email you should receive once the installation of octopus is complete, and use only Octopus instance, and never the master instance.

**Comment by omega8cc** [comment]
Your URL for Octopus should be `o1.srv1.mywebsite.org`

**Comment by omega8cc** [comment]
Note that we recommend to use at least 2 GB of RAM, and 1GB is the old minimum, usually for testing, but never for production servers.

**Comment by chvypwrd** [comment]
Thank you for the reply. Yes, after completion of the installation script, I reboot then run `barracuda up-stable` and reboot again. Still gets the 502 error. 

I am not sure why I get emails about the master.o1.xxx.com if not supposed to. This is the first welcome email that is sent, then it is followed with another one for o1.xxx.com. 

I feel like this is not caused by a memory issue, but I may be wrong. Do you feel like this could be the problem? I don't mind upgrading if needed, but I don't want to ask them for more money to upgrade hosting and still have the same problem. 

Here are the only errors found in the /var/aegir/install.log

> <em class="placeholder">nginx</em> on <em                            [1;33;40m[1m[warning][0m
> class="placeholder">o1.mywebsite.org</em> could not be
> restarted. Changes might not be available until this has been done.
> (error: <em class="placeholder">Reloading nginx configuration (via
> systemctl): nginx.serviceJob for nginx.service failed. See
> &#039;systemctl status nginx.service&#039; and &#039;journalctl
> -xn&#039; for details.
>  failed!</em>)
> 
> 
> The following module is missing from the file system: <em            [1;33;40m[1m[warning][0m
> class="placeholder">hostmaster</em>. For information about how to fix
> this, see <a href="https://www.drupal.org/node/2487215">the
> documentation page</a>. bootstrap.inc:1138

Then it has this one again towards the bottom:

> <em class="placeholder">nginx</em> on <em                            [1;33;40m[1m[warning][0m
> class="placeholder">o1.mywebsite.org</em> could not be
> restarted. Changes might not be available until this has been done.
> (error: <em class="placeholder">Reloading nginx configuration (via
> systemctl): nginx.serviceJob for nginx.service failed. See
> &#039;systemctl status nginx.service&#039; and &#039;journalctl
> -xn&#039; for details.
>  failed!</em>)

**Comment by chvypwrd** [comment]
I finally chased the correct rabbit hole. I found some information about changing the hosts file, updated it, rebooted and it is now working! There were no instructions found anywhere that mentioned a need to edit the hosts file. Is this not normally required for BOA installations? I kind of expected the script to make all of the settings and changes needed, otherwise instructions on what need to be changed manually. Very happy to have it working now and looking forward to using it!

Leaving this here for anyone else having 502 Bad Gateway errors after installing Barracuda 

This different installation guide lead me to the etc/hosts file modification
[http://azvox.net/content/how-install-aegir-octopus-high-performance-hostmaster-drupal](http://azvox.net/content/how-install-aegir-octopus-high-performance-hostmaster-drupal)

added the following line to /etc/hosts:
xx.xxx.xxx.ip o1.mywebsite.org o1

**Comment by omega8cc** [comment]
You seem to still confuse the master and satellite instances BOA installs for you, which in turn translates to DNS misconfiguration. At least, that is my guess, not sure.

Forget `/var/aegir` and use `/data/disk/o1` only.

It is explained at the top of the project README.

The Octopus instance doesn't have the "master" keyword in its URL.

The welcome email I'm talking about is also available in `/data/disk/o1/log/setupmail.txt`

Also, BOA doesn't require any modifications to `/etc/hosts`, it is automated in 100% and in fact `/etc/hosts` is not used to hardcode any names in server mode.

If such unexpected modifications help you, you are probably on some weirdly configured host.

What is you server host (company) name?

**Comment by chvypwrd** [comment]
DNS Misconfiguration is a possibility. As is weirdly configured host.  I have tried so many times with fresh installs, googling, reading, trying different things to make it work. 

The DNS is set-up with wildcard as per the instructions in INSTALL.txt. Also, came across this [set of instructions](https://www.drupal.org/node/1741624) so added 
 
>  master.server.mydomain.org
> o1.server.mydomain.org
to the DNS settings (my previous example in the first post was from the top of my head while at work, not logged into the server, this is how it is set-up, in addition to the wild card entry) Do I need these?

The host is LeaseWeb. Previously known as Ubiquity Hosting. I have been with Ubiquity for a number of years, still have my personal sites hosted on a shared environment so I stuck with them for this project. 

If the hosts file is not supposed to be edited, it is really strange that after adding the line it started working after getting nothing but 502 errors for the longest time. Everything seems to be working now and was able to get platforms and sites set-up and working as expected. It is not too late to wipe it clean one more time and start fresh again if there is something else I need to do to get it right.

**Comment by omega8cc** [comment]
This is not normal, either. If the system really needs hardcoded names in its /etc/hosts, then there are some crazy things behind the scenes done with networking, routing, forced DNS, or something else. We use such method in the localhost mode, so it could work also when you are offline. But it shouldn't be needed when your server is online!

Anyway, I would strongly recommend getting Linode or DigitalOcean VPS instead and forget about debugging this, or even getting in some real trouble later, with production sites hosted.

**Comment by omega8cc** [comment]
For example, it is possible that Drupal will not be able to connect to itself (which many contrib modules do), and things will break horribly. Similar problem affects vCloud Air: https://github.com/omega8cc/boa/blob/master/docs/CAVEATS.txt#L10
