### ISSUE TITLE
rysylog error in boa 3.2.0 stable

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1135]
Our BOA stable 3.2.0 dedicated server went down last night at 03:10 (approx) am.  We had to do a hard reboot to get it up and running again. There was no ssh access, and all sites were down, of course. The only errors we can find are a series of rsyslog errors that kept adding swap (could this have caused the server to crash):  Other than this, there's just a lot of firewall activity. Does rsyslog need to be updated?

We are running the 3.2.0 up-stable again to try to resolve this issue, and will post results.

examples of log messages is here: (dedicated with raid at ovh)
https://gist.github.com/EdNett/f7a13d06ac33bd9c03ae576337c40051

boa info more is here:
https://gist.github.com/EdNett/33d989aa6e86db5df46a432bcd6382e4

The server went down shortly thereafter. Does rsyslog need to be updated?

**Comment by omega8cc** [comment]
It is probably your hardware failure, which you need to investigate with your provider. The rsyslog only reports that the system can't clean up its swap (memory dump on disk, usually empty anyway), which firewall maintenance script does hourly.
