### ISSUE TITLE
dpkg: error processing package mariadb-server-10.1 (--configure):

### ISSUE THREAD

**Issue by dgvmd** [omega8cc/boa#1137]
Hi,
after apt-get dist-upgrade
mariadb server is broken after failed package update
see also:
https://superuser.com/questions/1103321/mariadb-server-broken-after-failed-package-update
https://mariadb.com/kb/en/mariadb/upgrade-10116maria-1jessie-broke-system/
https://mariadb.com/kb/en/mariadb/apt-upgrade-fails-but-the-database-is-running/

Thank you

**Comment by omega8cc** [comment]
Please never run manual packages upgrades and follow [the docs](https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt).

**Comment by dgvmd** [comment]
ha. ha. ha

**Comment by omega8cc** [comment]
Also, follow [the guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt).

**Comment by dgvmd** [comment]
No solution for this problem?

**Comment by omega8cc** [comment]
The solution is above in my comments, in front of you.

**Comment by dgvmd** [comment]
pooh!

**Comment by dgvmd** [comment]
Hi,
just after a downgrade of mariadb-server-10.1.21 it works again!
good day!

**Comment by omega8cc** [comment]
Interesting, but mariadb 10.1.22 works just fine. At least as long as you don't mess with manual upgrades..
