### ISSUE TITLE
Backlog of items in hosting_task table

### ISSUE THREAD

**Issue by etduroch** [omega8cc/boa#1140]
We upgraded our BOA instance to 3.2.0 about a month ago and I recently discovered our backup-delete task was changed to run every minute (instead of every hour).  This has caused a significant backup in our task processing due to the amount of sites we have - we are currently at 400,000+ pending records in the task queue.  Since all these backup-deletes are not necessary, I'd like to clear them out of the table or flag them as complete.  What is the best way to do so?

**Comment by omega8cc** [comment]
You could run this cleanup:

`su -s /bin/bash - o1 -c "drush8 @hm sqlq \"DELETE FROM hosting_task WHERE task_type='delete' AND task_status='-1'\""`
`su -s /bin/bash - o1 -c "drush8 @hm sqlq \"DELETE FROM hosting_task WHERE task_type='delete' AND task_status='0' AND executed='0'\""`

or even:

`su -s /bin/bash - o1 -c "drush8 @hm sqlq \"DELETE FROM hosting_task WHERE task_type='delete'\""`

**Comment by etduroch** [comment]
Awesome - thanks!  Do we need to be concerned with orphaned records (i.e. node records)?

**Comment by omega8cc** [comment]
Ah, right.. It will still leave a ton of orphaned nodes, indeed, because tasks are still a full nodes, since currently our built-in cleanup works only for nodes revisions. It may need a more complex sqlq to delete associated nodes and revisions first, and then to delete the not needed tasks from the queue.

**Comment by omega8cc** [comment]
Or maybe uninstalling the module temporarily could cleanup its nodes and tasks, not sure. We do recommend to not use the built-in Aegir backups.

**Comment by sgardapee** [comment]
What is the recommendation for doing the backups?  Can you point us to some documentation?  Or are you suggesting we build our own backup process?

**Comment by omega8cc** [comment]
@sgardapee We recommend that you use the [backboa](https://github.com/omega8cc/boa/blob/master/docs/BACKUPS.txt) utility. It will automatically take care about all your files and databases remote, encrypted, and versioned S3 backups.

Or, if you don't want remote backups, BOA already creates local backups for all your databases, and keeps the latest 7-8 days in `/data/disk/arch/sql` (this doesn't include any other files, though).
