### ISSUE TITLE
Backboa: Certificate error

### ISSUE THREAD

**Issue by tourtools** [omega8cc/boa#1141]
hello, 

[boa info](https://gist.github.com/tourtools/88110cdf413510325531ff26cf2e269a)

on a VPS BOA 3.2.0, with backboa running flawless from quite a year, all up to date: 
on midnight of April 2nd it stopped to run backups, 

if I type the backboa status it says:

[backboa status](https://gist.github.com/tourtools/a596d4e94291e13c8f0086ed8890a358)

which last lines are here:

`CertificateError: hostname 'daily.boa.server01.tourtools.it.s3-eu-west-1.amazonaws.com' doesn't match either of 's3-eu-west-1.amazonaws.com', '*.s3-eu-west-1.amazonaws.com', 's3.eu-west-1.amazonaws.com', '*.s3.eu-west-1.amazonaws.com', 's3.dualstack.eu-west-1.amazonaws.com', '*.s3.dualstack.eu-west-1.amazonaws.com', '*.s3.amazonaws.com'`

**Comment by tourtools** [comment]
seems related to Python 2.7.9 strict certificate checking, but I wonder why only 3 days ago it fails

**Comment by angel0d** [comment]
i have the same issue

backups stopped on April 2nd

as in the python traceback and with a quick google search this seems to be coming from **boto** which itself is called by **duplicity**

it tried a few suggestions like creating a config file for boto

```
[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat

```
from : https://github.com/boto/boto/issues/2836

or to instruct boto to not validate certificates

```
[Boto]
https_validate_certificates = False

```

but it does not work or the config file is ignored

**Comment by angel0d** [comment]
it seems that this started happening after 221be4a

i run `backboa install` but `backboa status` still fails

**Comment by omega8cc** [comment]
Ouch, we totally forgot about the patch for boto we have added before: https://github.com/omega8cc/boa/commit/00dbb9efa81a1540cdb670af9597fbadffbc383b

Reverting until it is tested with latest boto: https://github.com/omega8cc/boa/commit/f8925cd4405a44faca0fb65393e28fc8052040bd

**Comment by omega8cc** [comment]
Please run `backboa install` to revert to previous working version.

**Comment by tourtools** [comment]
thank you, reverting it got back to work.

**Comment by omega8cc** [comment]
Fixed! Thanks for the feedback and patches!
