### ISSUE TITLE
Migration doesn't work if drupal has not the same core (drupal 6 to drupal 7, ...)

### ISSUE THREAD

**Issue by dgvmd** [omega8cc/boa#1143]
But migration works from drupal to drupal with the same core.

Examples:
drupal 6 to drupal 7 does not work
drupal 7 to drupal 7 works

Thanks for your help.

**Comment by angel0d** [comment]
@dgvmd every migration fails for a reason

what are the error you get in the specific migration ?

see also : https://www.drupal.org/node/2020073

if there isn't much to tell from the task report inside aegir you might want to run the "drush -v provision-migrate ..." line with the same parameters found in the task report

you might want to try a more specific issue queue like the provision's one

**Comment by omega8cc** [comment]
Aegir is not a magic trick to make the Drupal beast able to hop easily from D6 to D7 rocket. It would be awesome, but it is just not how these things work in real life. Aegir and Drush can do and react only to what Drupal allows/provides.

So, yeah, it is indeed a problem with Drupal and not with Aegir/BOA

But there is a hope it will change in the future: http://buytaert.net/making-drupal-upgrades-easy-forever
