### ISSUE TITLE
local.settings.php cleanups question

### ISSUE THREAD

**Issue by danielbeeke** [omega8cc/boa#1144]
Hello,

I have had a strange couple of times that I would add something to a local.settings.php file with the root user. And after a while the contents would be gone. Today I had it with an old Drupal 7 site.

A couple of weeks ago I placed error_reporting(E_ALL ^ E_DEPRECATED); in the local.settings.php so my deprecated warnings of ctools would be gone.

Today the line was gone, and the notice was on the frontpage. Is this familiar functionality or am I seeing ghosts?

**Comment by omega8cc** [comment]
Hmmm.. really weird, because this file is designed to be `local`, so never touched by the system, once created and/or edited manually. I don't think BOA does anything here. Just checked the code and we definitely don't modify it. Only permissions get fixed, nightly.

Are you sure you are making the file writable before editing it, even as root?

**Comment by omega8cc** [comment]
Wait, or maybe you mean the `local.settings.php` in the hostmaster site? That file is replaced on every Aegir upgrade, and Aegir Provision does this, to fix problems with Drupal core upgrades, in `function drush_provision_hostmaster_migrate()`.

**Comment by omega8cc** [comment]
The code is buggy, because it keeps adding the same lines on every upgrade:

```
  if ($major_version_upgrade) {
    drush_log('Detected major version upgrade. Disabling error-reporting.', 'warning');
    $local_settings_file = d('@hostmaster')->site_path . '/local.settings.php';
    if (!file_exists($local_settings_file)) {
      file_put_contents($local_settings_file, "<?php # local settings.php \n");
    }
    $local_settings_backup = $local_settings_file . '.bak';
    provision_file()->copy($local_settings_file, $local_settings_backup)
      ->succeed('Backed up local.settings.php.')
      ->fail('Failed to backup of local.settings.php.');
    provision_file()->chmod($local_settings_file, 02640);
    $lines_to_append = "
    // These lines were added to overcome a false-positive error thrown in Drupal 7.50+
    error_reporting(0);
    ini_set('display_errors', FALSE);
    ini_set('display_startup_errors', FALSE);";
    file_put_contents($local_settings_file, $lines_to_append, FILE_APPEND);
  }
```

**Comment by danielbeeke** [comment]
Thank you for the response,
I mean the local.settings.php inside a static platform.
I have also seen this with $config_directories.
Can it maybe that when verifying of migrating the file gets lost?

Maybe it is fine for now, When I encouter it another time I will investigate, debug and provide debugging info.

**Comment by omega8cc** [comment]
Provision will generate empty `local.settings.php` file only if the file doesn't exist. It will not touch this file, if it exists, and BOA has no code to do anything to this file, except to fix its permissions, so it is pretty mysterious..

**Comment by yaazkal** [comment]
Hi, as I'm working on a D8 site using config_split module I have in my respository a sites/example.com/local.settings.php file with a line that disable the some configuration (config_dev) as mentioned in the [docs](https://www.drupal.org/docs/8/modules/configuration-split/creating-a-simple-split-configuration-dev-modules-only-in-dev). So this configuration will be only applied on my BOA server.

So I git clone my respository, then `composer install --no-dev` then adds a platform and then create the site `example.com` on that platform, but the sites/example.com/local.settings.php file gets overrited.

**Comment by omega8cc** [comment]
Hmmm.. it doesn't sound good.

**Comment by omega8cc** [comment]
We couldn't reproduce this using standard workflow with managing sites. Does anyone still experience it?
