### ISSUE TITLE
Writing Drupal Test

### ISSUE THREAD

**Issue by chrisarcherhydrant** [omega8cc/boa#1153]
Hi,

Not sure this is the correct place to post this, but is there any examples or documentation on writing Behat or Drupal Tests for sites, for when you either install a new site or migrate a site within Aegir?  I'm not sure if this is even possible.  

A little context: I'd like to write some tests for when a site is installed or migrated and for Aegir to show if these have been successful.  This would really help when installing sites and adding new features to Drupal install profiles.  

At the moment I'm just using Drupal 7 so this relates to this, but I'd also be looking to write tests for Drupal 8 when I get round to porting the custom Drupal 7 profile to Drupal 8.

Thanks,
Chris

**Comment by memtkmcc** [comment]
I believe it is not related to BOA project scope directly? It is rather Aegir upstream question, I think.
