### ISSUE TITLE
Issues installing a D8 Site

### ISSUE THREAD

**Issue by chrisarcherhydrant** [omega8cc/boa#1154]
Hi,

I've tried to install a Standard D8 site using version 8.3.2 of Drupal.  But when I try and install a site on the platform I get the following error.

`Error: Class 'Drupal\Core\Site\Settings' not found in /var/aegir/platforms/drupal_test_eight/core/lib/Drupal/Core/DrupalKernel.php, line 1022`

Thanks,
Chris

**Comment by memtkmcc** [comment]
Hi Chris,

We don't support hosting Drupal sites on the master Aegir instance in /var/aegir. Please use the Octopus Aegir instance in /data/disk/o1 instead. It is explained at the top of the project readme.

**Comment by memtkmcc** [comment]
Also, please make sure to read about D8 support: https://learn.omega8.cc/platforms

**Comment by chrisarcherhydrant** [comment]
Okay thanks.
