### ISSUE TITLE
SSH key changes mid-install

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#1156]
Mid-install, after PHP is installed, and Master (master.server.[domain.com]), the session drops ... I think because the remote key changes.
No Octopus satellite instance is successfully installed. BUT I did manage to successfully install o2.server.[domain.com] manually after reconnecting.

Why does the remote key change? It that normal?

Debian 8, vultr.com .

**Comment by MetaBureau** [comment]
Retrospectively installed Octopos user o1.ftp as follows:

server:~# boa in-octopus srm@reop.com.au o1 none stable

BOA [06:30:46] ==> Skynet Agent v.BOA-3.2.0 welcomes you aboard!

BOA [06:30:50] ==> Octopus Satellite Instance Upgrade in progress...

BOA [06:30:50] ==> This Octopus URL address is o1.server.reop.com.au
BOA [06:30:50] ==> This Octopus PHP version is 7.0
BOA [06:30:50] ==> This Octopus System is Debian/jessie x86_64

BOA [06:30:58] ==> UPGRADE A: Shared platforms code v.002 will be used
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'o1'@'server.reop.com.au'
BOA [06:31:42] ==> UPGRADE B: Downloading drush micro-8-07-02-2017...
BOA [06:31:48] ==> UPGRADE B: Installing Aegir Provision backend...
BOA [06:31:48] ==> UPGRADE B: Downloading Drush and Provision extensions...
BOA [06:31:55] ==> UPGRADE B: Hostmaster STATUS: Upgrade in progress...
BOA [06:32:16] ==> UPGRADE B: Hostmaster STATUS: Upgrade completed
BOA [06:32:16] ==> UPGRADE B: Aegir upgrade test result: OK

BOA [06:32:21] ==> UPGRADE B: Letsencrypt SSL initial mode: DEMO
BOA [06:32:21] ==> UPGRADE B: LE -- No real SSL certs will be generated
BOA [06:32:21] ==> UPGRADE B: LE -- To enable live SSL mode, please delete file:
BOA [06:32:21] ==> UPGRADE B: LE -- /data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid
BOA [06:32:21] ==> UPGRADE B: LE -- Then run octopus forced upgrade

BOA [06:32:21] ==> UPGRADE B: LE -- !!! WARNING
BOA [06:32:21] ==> UPGRADE B: LE -- Don't enable SSL option for the Hostmaster site in Aegir
BOA [06:32:21] ==> UPGRADE B: LE -- SSL for Aegir control panel is handled outside of it
BOA [06:32:21] ==> UPGRADE B: LE -- !!! WARNING

BOA [06:32:21] ==> UPGRADE B: Enhancing Aegir UI, please wait...
BOA [06:32:48] ==> UPGRADE A: Aegir Satellite Instance upgrade completed

Do you want to install some ready to use platforms? [Y/n] n
BOA [06:32:56] ==> UPGRADE A: No new Platforms added this time
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the sites backups
ln: failed to create symbolic link ‘/home/o1.ftp/backups’: No such file or directory
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the system registry_rebuild
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the system clean_missing_modules
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the system drupalgeddon
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the system drush_ecl
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the system safe_cache_form_clear
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the system mydropwizard
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:32:56] ==> UPGRADE A: Adding symlink to the clients directory
chown: invalid user: ‘o1.ftp:users’
chown: invalid user: ‘o1.ftp:users’
BOA [06:33:25] ==> Final post-upgrade cleaning, one moment...
BOA [06:33:29] ==> BYE!

**Comment by EdNett** [comment]
I have the same problem and it causes me hours and hours of work. Why is this happening or necessary?

**Comment by omega8cc** [comment]
The SSH keys change, because BOA installs SSH from sources, and we can't simply re-use SSH keys from the standard SSH packages, due to versions and paths conflicts. It doesn't affect current sessions, though, so the installation always should complete without issues. It seems to be related to your host behaviour?

**Comment by EdNett** [comment]
This probably was because of the host behavior in our case - the vps company has a separate file which can contain ssh keys temporarily load the ssh key info the authorized file which is then wiped clean after it is read!

**Comment by omega8cc** [comment]
OK, so it's probably better to simply not enforce building ssh from sources by default. It will not interrupt the installation nor cause any confusion, and you can still enable it optionally later.
