### ISSUE TITLE
Add support for --include-filelist and --exclude-filelist for duplicity.

### ISSUE THREAD

**Issue by angel0d** [omega8cc/boa#1159]
Would you consider adding support for a more fine grained control of what files/folder are included/excluded from duplicity ?

Created a quick pull request to demonstrate a way this could be achieved.

In my usecase I would like to exclude all boost cache folders. With the logic in the PR I would do so by adding a file /root/.backboa.exclude with contents like:

`/data/disk/*/static/*/cache`

Other use cases could be home folders that are huge and do not need to be backed up

**Comment by omega8cc** [comment]
Patch committed, thanks! There is a typo in the docs, but we can fix this later, I guess. Thanks again!
