### ISSUE TITLE
Server package updates using Webmin

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1160]
Is it safe to update server packages using Webmin on the BOA server?
Webmin lists the following packages that can be updated:

bind9-host
dnsutils
git
git-core
git-man
imagemagick
imagemagick-6.q16
imagemagick-common
ldap-utils
libbind9-90
libdns-export100
libdns100
libgtk2.0-0
libgtk2.0-bin
libgtk2.0-common
libirs-export91
libisc-export95
libisc95
libisccc90
libisccfg-export90
libisccfg90
libjbig2dec0
libldap-2.4-2
libldap2-dev
liblwres90
libmagickcore-6-arch-config
libmagickcore-6-headers
libmagickcore-6.q16-2
libmagickcore-6.q16-2-extra
libmagickcore-6.q16-dev
libmagickwand-6-headers
libmagickwand-6.q16-2
libmagickwand-6.q16-dev
libmagickwand-dev
libmariadbclient-dev
libmariadbclient18
libmariadbd-dev
libmysqlclient18
libnss3
libperl5.20
libpq5
librtmp1
libtasn1-6
libtirpc1
login
mariadb-client-10.1
mariadb-client-core-10.1
mariadb-common
mariadb-server-10.1
mariadb-server-core-10.1
mysql-common
openjdk-7-jre-headless
passwd
perl
perl-base
perl-modules
rpcbind
sudo
w3m

**Comment by ar-jan** [comment]
No, you should only use the documented boa upgrade mechanism (docs/UPGRADE.txt). I recall having seen explicit warnings not to use anything else.

**Comment by omega8cc** [comment]
Correct, you should never use Webmin to manage upgrades.
