### ISSUE TITLE
New Relic not sending data (maybe due to changing Licence Key)

### ISSUE THREAD

**Issue by EmilPhosworks** [omega8cc/boa#1161]
New Relic has been installed before on this server but I do not know if it has been working. Now I changed the Licence Key in these files:

```
/root/.barracuda.cnf
/data/disk/o2/static/control/newrelic.info
/etc/newrelic/nrsysmond.cfg
/etc/newrelic/newrelic.cfg
/opt/php56/etc/pool.d/o2.conf
/opt/php56/etc/php56.ini
```

Did this:
`touch /root/.enable.newrelic.sysmond.cnf`
(did not exist before today)

and restarted the server. No gain.

Tried this:
`usermod -aG users newrelic`
and restarted the server. No gain.

Troubleshooting:
These are the logged messages after reboot of the server:
```
server:~# tail /var/log/newrelic/php_agent.log 
rotate
2017-06-13 15:43:09.392 +0200 (920 920) error: failed to read reply preamble: fd=6 errno=ETIMEDOUT
2017-06-13 15:43:09.396 +0200 (920 920) error: APPINFO failure: len=4832 errno=ETIMEDOUT
2017-06-13 16:11:25.707 +0200 (3647 3647) error: failed to read reply preamble: fd=6 errno=ETIMEDOUT
2017-06-13 16:11:25.710 +0200 (3647 3647) error: APPINFO failure: len=4832 errno=ETIMEDOUT
2017-06-13 16:27:31.038 +0200 (3766 3766) error: failed to read reply preamble: fd=6 errno=ETIMEDOUT
2017-06-13 16:27:31.039 +0200 (3766 3766) error: APPINFO failure: len=4832 errno=ETIMEDOUT
server:~# tail /var/log/newrelic/newrelic-daemon.log 
rotate
2017/06/13 15:43:09.416731 (4568) Error: listener: closing connection: unable to read header: read unix /tmp/.newrelic.sock->@: read: connection reset by peer
2017/06/13 16:11:25.777788 (4450) Error: listener: closing connection: unable to write reply of length 44: write unix /tmp/.newrelic.sock->@: write: broken pipe
2017/06/13 16:27:31.045318 (4282) Error: listener: closing connection: unable to write reply of length 44: write unix /tmp/.newrelic.sock->@: write: broken pipe
```

New Relic version:
```
server:~# nrsysmond -h
New Relic system monitor daemon version 2.3.0.132 ("cloudy") ("8cff29599e1e9619b31da739b2ac86c7213f6b71")
(C) Copyright 2009-2016 New Relic Inc. All rights reserved.
curl version libcurl/7.42.1 OpenSSL/1.0.1t zlib/1.2.8
pcre version 8.36 2014-09-26
zlib version 1.2.8
```

Logged in to New Relic I have this:
`Still waiting for data from application`
`this message will automatically disappear upon successful connection`

Googling for the error messages I found this:
[https://discuss.newrelic.com/t/error-listener-closing-connection-unable-to-write-reply-of-length-5892-write-unix-broken-pipe/40999](https://discuss.newrelic.com/t/error-listener-closing-connection-unable-to-write-reply-of-length-5892-write-unix-broken-pipe/40999)
but in which file should the settings according to the next link to be entered?
[https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-slowsql](https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-slowsql) if that is the error in the first place?
Add these 
`newrelic.transaction_tracer.slow_sql=false`
`newrelic.transaction_tracer.enabled=false`
in the following file? But I cannot edit it as root nor as o2.ftp:
`/data/disk/o2/.drush/php.ini`

Some more troubleshooting:
```
server:~# tail /var/log/newrelic/nrsysmond.log
rotate
server:~# sudo /etc/init.d/newrelic-sysmond status 
New Relic Server Monitor: newrelic-sysmond is not running
server:~# service newrelic-daemon status
New Relic Daemon: newrelic-daemon is running
```

[https://discuss.newrelic.com/t/ubuntu-starting-new-relic-server-monitor-newrelic-sysmond-failed/40296](https://discuss.newrelic.com/t/ubuntu-starting-new-relic-server-monitor-newrelic-sysmond-failed/40296)
Nothing written, no error:
```
server:~# su newrelic -s /bin/sh -c "env -i /usr/sbin/nrsysmond -f -c /etc/newrelic/nrsysmond.cfg -p /var/run/newrelic/nrsysmond.pid"
server:~# 
```

Added [IP ranges](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/networks) of New Relic to these files:
```
/etc/csf/csf.ignore 
/etc/csf/csf.allow
50.31.164.0/24
162.247.240.0/22
```

Barracuda version:
`3.3.0-dev`

To update Barracuda 3.3.0-dev (is it head?) - should I run this?
`barracuda up-head log`
or what should I do to get New Relic to connect and send data?

Should I also first remove this file so that New Relic would be updated?
`etc/apt/sources.list.d/newrelic.list`

**Comment by omega8cc** [comment]
You should never modify any of those config files manually. It is very simple to use, if you follow the docs: https://learn.omega8.cc/how-to-use-new-relic-apps-monitoring-335

If you ever need to change the key, delete the `newrelic.info` control file, wait 5 minutes, and then add it again, with new key.

**Comment by EmilPhosworks** [comment]
Thanks for the quick reply, that maybe got the newrelic-sysmond running. It runs even after a reboot. I'm not sure this did it, because I did not check before if newrelic-sysmond was running.

Still, no data is recieved on the New Relic website.

1. I moved away the newrelic.info, waited 5 minutes and moved it back at 09:44, waited at least 5 min rebooted.
2. Moved it away, waited 5 min, created a new file at 10:25 (in case the date is imortant), waited 5 min, checked newrelic logs - nothing, rebooted at 10:35.

When the file was removed, the two newrelic services were still running.

Logs look like this - no reaction to step 2 above. Probably no reaction to step 1 either. At 08:36 nothing was done, so maybe some cron job is doing something.

```
server:~# tail -f /var/log/newrelic/php_agent.log 
rotate
2017-06-14 08:36:30.120 +0200 (301 301) error: failed to read reply preamble: fd=6 errno=ETIMEDOUT
2017-06-14 08:36:30.121 +0200 (301 301) error: APPINFO failure: len=4832 errno=ETIMEDOUT
2017-06-14 09:54:34.620 +0200 (2061 2061) error: failed to read reply preamble: fd=6 errno=ETIMEDOUT
2017-06-14 09:54:34.620 +0200 (2061 2061) error: APPINFO failure: len=4832 errno=ETIMEDOUT
^C
server:~# tail -f /var/log/newrelic/nrsysmond.log
rotate
^C
server:~# tail -f /var/log/newrelic/newrelic-daemon.log 
rotate
2017/06/14 08:36:30.144208 (4282) Error: listener: closing connection: unable to write reply of length 6496: write unix /tmp/.newrelic.sock->@: write: broken pipe
2017/06/14 09:54:34.625018 (4282) Error: listener: closing connection: unable to write reply of length 6496: write unix /tmp/.newrelic.sock->@: write: broken pipe
^C
server:~# service newrelic-sysmond status 
New Relic Server Monitor: newrelic-sysmond is running
server:~# service newrelic-daemon status 
New Relic Daemon: newrelic-daemon is running
server:~# 
```
Reboot times:
```
server:~# grep relic /var/log/lfd.log
Jun 14 09:57:57 server su[2958]: Successful su for newrelic by root
Jun 14 09:57:57 server su[2958]: + /dev/console root:newrelic
Jun 14 09:57:57 server su[2958]: pam_unix(su:session): session opened for user newrelic by (uid=0)
Jun 14 09:57:58 server su[2958]: pam_unix(su:session): session closed for user newrelic
Jun 14 10:34:45 server su[2981]: Successful su for newrelic by root
Jun 14 10:34:45 server su[2981]: + /dev/console root:newrelic
Jun 14 10:34:45 server su[2981]: pam_unix(su:session): session opened for user newrelic by (uid=0)
Jun 14 10:34:45 server su[2981]: pam_unix(su:session): session closed for user newrelic

```

How should I continue? Create a ticket so you can fix it?

**Comment by angel0d** [comment]
@EmilPhosworks there are some other users facing similar errors [on new relic forums](https://discuss.newrelic.com/t/error-listener-closing-connection-unable-to-write-reply-of-length/34185)

it seems to have to do when the daemon tries to send huge packets and is timing out

this [one here](https://discuss.newrelic.com/t/error-listener-closing-connection-unable-to-write-reply-of-length-5892-write-unix-broken-pipe/40999) has a suggestion to overcome this

**Comment by EmilPhosworks** [comment]
Yes, that is the link I wrote about in my first post. I also asked to which file these setting should be applied.

**Comment by angel0d** [comment]
sorry, I missed it in the long comment

not sure if `/data/disk/o2/.drush/php.ini` is the one that should be changed. but you can write to it by unlocking it first with chattr -i and editing it very quickly or doing something like:

`chattr -i /data/disk/o2/.drush/php.ini; echo "newrelic.transaction_tracer.slow_sql=false" >> /data/disk/o2/.drush/php.ini; echo "newrelic.transaction_tracer.enabled=false" >> /data/disk/o2/.drush/php.ini`

have you tried using ini_set in your local.settings.php ? this could work on a per site basis

if it does work you could also try adding them to `/opt/php56/lib/php.ini` (given that you have php 5.6)

**Comment by angel0d** [comment]
if ini_set does not work the main .ini will be eventually replaced on a next BOA update

not sure if the following could be a permanent solution on a per project basis

https://docs.newrelic.com/docs/agents/php-agent/configuration/php-directory-ini-settings

**Comment by omega8cc** [comment]
It would be better to find out why you need to disable this feature via custom settings. Could be an issue with your codebase to track and fix.

You should be able to add these lines either in the `local.settings.php` file for site level fix, or globally in either `/data/conf/override.global.inc` or `/data/conf/settings.global.inc`

```php
<?php
if (extension_loaded('newrelic')) {
  ini_set('newrelic.transaction_tracer.slow_sql', 'false');
  ini_set('newrelic.transaction_tracer.enabled', 'false');
}
```

**Comment by EmilPhosworks** [comment]
@angel0d thanks for the `chattr -i` tip and the other suggestions. I followed them.

@omega8cc 
To track errors in the codebase - that is the reason to set up New Relic. Especially useful because someone else created the code and now I have to fix it.

I put your code into /data/conf/override.global.inc (just because that file already existed). Rebooted. Waited 5 minutes.

Before that, I had already put the two settings in lots of other files and they are listed in `/admin/reports/status/php` so they should be in effect, at least for the site.

Still no data shown when logged in to the New Relic website.

**Comment by EmilPhosworks** [comment]
More troubleshooting
---------------------------

So, the two newrelic settings are present in `/admin/reports/status/php` so they should be in effect. Also the right license key is reported there and the New Relic Version is the newest [7.2.0.191](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes).

Changed the log levels to debug. New Relic is at least collecting data:

```
server:~# tail -f /var/log/newrelic/newrelic-daemon.log
2017/06/14 13:16:25.558697 (4468) Debug: command='analytic_event_data' url='https://collector-233.newrelic.com/agent_listener/invoke_raw_method?license_key=a4..b4&marshal_format=json&method=analytic_event_data&protocol_version=14&run_id=1247204censored' payload={...bla bla lots of Drupal stuff...}

2017/06/14 13:16:25.826683 (4468) Debug: command='analytic_event_data' url='https://collector-233.newrelic.com/agent_listener/invoke_raw_method?license_key=a4..b4&marshal_format=json&method=analytic_event_data&protocol_version=14&run_id=12472060censored', response={null}
2017/06/14 13:16:25.833781 (4468) Debug: command='metric_data' url='https://collector-233.newrelic.com/agent_listener/invoke_raw_method?license_key=a4..b4&marshal_format=json&method=metric_data&protocol_version=14&run_id=12472060censored', response={[]}
```

The right license is visible in here also:
```
server:~# tail -f /var/log/newrelic/nrsysmond.log
2017-06-14 14:12:10.112 (3266) debug: nria_add_responsetime_metric for System/Disk/All/Writes = 0.001508 (3.520000 / 2334.000), 26763264.000
2017-06-14 14:12:10.112 (3266) debug: nria_add_percent_metric for System/Disk/All/Reads/Utilization/percent = 0.36%
2017-06-14 14:12:10.112 (3266) debug: nria_add_percent_metric for System/Disk/All/Writes/Utilization/percent = 2.98%
2017-06-14 14:12:10.112 (3266) debug: nria_add_percent_metric for System/Disk/All/Utilization/percent = 3.34%
2017-06-14 14:12:10.112 (3266) debug: nria_add_simple_metric for System/Disk/All/Type = 0.000
2017-06-14 14:12:10.112 (3266) debug: nria_add_rate_metric for System/Disk/All/bytes/sec = 29483008.000 / 20.000 (1474150.400/sec)
2017-06-14 14:12:10.113 (3266) debug: nria_add_percent_metric for System/CPU/User/percent = 39.83%
2017-06-14 14:12:10.113 (3266) debug: nria_add_percent_metric for System/CPU/System/percent = 12.57%
2017-06-14 14:12:10.113 (3266) debug: nria_add_percent_metric for System/CPU/IO Wait/percent = 0.70%
2017-06-14 14:12:10.129 (3266) debug: Docker GET from 'http://localhost/info' failed
2017-06-14 14:12:27.993 (3266) debug: harvester running
2017-06-14 14:12:27.994 (3266) debug: harvesting appname='Infrastructure' daemon_id=0x6ecb0ff700000000 for license='a4...b4'
2017-06-14 14:12:28.635 (3266) debug: RPM cmd='metric_data' for 'Infrastructure' returned code=200
2017-06-14 14:12:28.635 (3266) debug: RPM cmd='metric_data' return=OK reply_type=10
2017-06-14 14:12:28.636 (3266) debug: harvester done
```

But `/admin/reports/status/php` reports instead `newrelic.daemon.collector_host	collector.newrelic.com`
so that maybe has to be changed to `collector-233.newrelic.com` somewhere? Or the other way around? On the other hand, both are allowed and ignored by IP range in `/etc/csf/csf.allow` and in `/etc/csf/csf.ignore`


Latest users log:
```
/var/backups/ltd/log/users-170614-1436.log
_USER is == o2 == at manage_user
Custom FPM, HHVM or CLI settings for o2 exist, running switch_php checks
New Relic integration is already active for o2
Managing Users for /data/disk/o2 Instance
...
```

Connection to newrelic collectors ok (as root):
```
server:~/newrelic-test# curl -v http://collector.newrelic.com/status/mongrel
* About to connect() to collector.newrelic.com port 80 (#0)
*   Trying 50.31.164.149...
* connected
* Connected to collector.newrelic.com (50.31.164.149) port 80 (#0)
> GET /status/mongrel HTTP/1.1
> User-Agent: curl/7.26.0
> Host: collector.newrelic.com
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 22
< 
mongrel ==> up (true)
* Connection #0 to host collector.newrelic.com left intact
* Closing connection #0
server:~/newrelic-test# 
server:~/newrelic-test# 
server:~/newrelic-test# curl -v http://collector-233.newrelic.com/status/mongrel
* About to connect() to collector-233.newrelic.com port 80 (#0)
*   Trying 50.31.164.148...
* connected
* Connected to collector-233.newrelic.com (50.31.164.148) port 80 (#0)
> GET /status/mongrel HTTP/1.1
> User-Agent: curl/7.26.0
> Host: collector-233.newrelic.com
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 22
< 
mongrel ==> up (true)
* Connection #0 to host collector-233.newrelic.com left intact
* Closing connection #0
server:~/newrelic-test# 

```

Maybe this is more of a New Relic issue than BOA?

**Comment by EmilPhosworks** [comment]
Fixed!

Thank you!

**Comment by omega8cc** [comment]
I don't think it is a BOA issue, because we don't see it anywhere on our systems.

It is possible that you have managed to break something by changing many files, instead of following the docs and using BOA automated procedures.

By the way, what is the point in rebooting the system after editing simple `.php` file?

Please proceed with these steps:

1. rename/remove `newrelic.info` ctrl file
2. switch `fpm.info` ctrl file to 5.3 and run `bash /var/xdrago/manage_ltd_users.sh`
3. add proper key to `newrelic.info` ctrl file and run `bash /var/xdrago/manage_ltd_users.sh`
4. switch `fpm.info` ctrl file to 7.0 and run `bash /var/xdrago/manage_ltd_users.sh`

Now check if the correct key is present in `/opt/php70/etc/pool.d/o1.conf` (assuming octopus system user is default `o1`)

**Comment by omega8cc** [comment]
Fixed?

**Comment by EmilPhosworks** [comment]
I was looking at the wrong page at New Relic:
https://rpm.newrelic.com/accounts/123456/applications/setup#

instead of at
https://rpm.newrelic.com/accounts/123456/applications
(which redirected to setup in the beginning I think, when data was not sent to New Relic)

Even when I reloaded the setup page with CTRL+F5 there was still, and is now too, the yellow message saying:

> Still waiting for data from application
> this message will automatically disappear upon successful connection

Maybe a New Relic-newbie mistake - sorry for taking your time. Hope this helps someone else...

Thank you for all your help!

**Comment by omega8cc** [comment]
Ah, OK..
