### ISSUE TITLE
Queue settings gets reset

### ISSUE THREAD

**Issue by serhatozkara** [omega8cc/boa#1162]
Outstanding hosting tasks queue gets reset after failed tasks to 1 tasks per 5 seconds. Because task count is 1, outstanding tasks get never processed.

**Comment by omega8cc** [comment]
Please provide more details and context. Not sure what exactly happens and why?

**Comment by omega8cc** [comment]
Also, BOA forces the queue to always run one task at the time, to avoid race conditions. It works perfectly, but if you have pseudo-running task, you need to unlock the queue by deleting this task node. It is explained in the docs here: https://learn.omega8.cc/aegir-task-fails-or-spins-forever-126

**Comment by serhatozkara** [comment]
Since there are 42000 task nodes on my server, I really couldn't find which tasks are stuck. After outstanding tasks queue gets reset to 1 per 5 seconds, all backup-delete tasks gets unprocessed and task queue gets bloated with unprocessed backup-delete tasks.

**Comment by omega8cc** [comment]
Ouch... maybe stop using the built-in backups to avoid this giant tasks nodes overhead?

**Comment by serhatozkara** [comment]
Yes, I plan on doing that and use backboa for backups, but I think it needs aws instance to work and really couldn't find a guide. Open to suggestions :)

**Comment by omega8cc** [comment]
You don't need AWS instance, just Amazon AWS account and then you activate S3 service there, and get billed for what is used (extremely cheap).

**Comment by serhatozkara** [comment]
Cool, does it support remote site backups?
