### ISSUE TITLE
How to host sites on the boa server but outside Aegir

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1165]
I would like to host a number of sites on my BOA server, but I don't need ever to replicate them and I don't want to use the aegir system for them, they should not be includes as platforms.

What is best practice for doing this? Is this approach discouraged, should I install them on a separate server?

Should the DNS server also be a separate server?

**Comment by omega8cc** [comment]
It's absolutely possible, but not supported officially -- [see the project FAQ](https://github.com/omega8cc/boa/blob/master/docs/FAQ.txt).
