### ISSUE TITLE
MariaDB doesn't restart after recent up-stable (from 3.2.0 to 3.2.0)

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1166]
This error happened when I ran an up-stable which included about 70 aptitude upgrades, including from mariadb 10.1.23 to 10.1.24.  I should also report that the 1024 MB of RAM are ALL used when I run the barracuda up-stable.

mariadb-server-10.1 fails to fully install and cannot then be fully installed/configured:
https://gist.github.com/EdNett/37e197c0b840c43e467196409f81509a

Error starts with could not open mysql.plugin table, then can't open and lock privilidges tables errors - posted on gist:  https://gist.github.com/EdNett/e1985f6731da26b576c26c4d918b3902

boa info is here:
https://gist.github.com/EdNett/5fa1a9c6ed444f7eea01b0857c97bd30

I also see this error - aptitude not finding php-apcu 👍 
https://gist.github.com/anonymous/658d812d587b205f66f8b7de6a7abbe6

(very strange as it doesn't include last 4 up-stables - this is an vmware openvz vps - I know, it's not officially supported -  (vps classic from ovh with 1 core and 1 GB of ram - solr is not installed - we use this as a test vps only)

Could this be related to the following issue:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864298

Ed

**Comment by EdNett** [comment]
There seems to be something wrong with boa 3.2.0 (or some part of it like php 5.6, etc.) and mariadb 10.1.21, too - on a production vps (with 2 GB RAM and of a type that is listed as supported), a recent updb to a site that had been upgraded to core 7.56 from 7.54 (an IDN site) caused a PDO SQL State error, and I have not been able to get mariadb to restart at all - very strange error messages like InnoDB is unknown type, etc.

**Comment by EdNett** [comment]
an upgrade to the recently released mariadb-10.1.25 does not solve the problem. I think the problem must be with an incompatibility between BOA's method of starting mysql and the newer mariadb versions.:

Errors were encountered while processing:
 mariadb-server-10.1
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up mariadb-server-10.1 (10.1.25+maria-1~jessie) ...
[ ok ] Stopping MariaDB database server: mysqld.
[....] Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . [FAIL . failed!
invoke-rc.d: initscript mysql, action "start" failed.
dpkg: error processing package mariadb-server-10.1 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 mariadb-server-10.1

**Comment by angel0d** [comment]
@EdNett it does not seem to be a maria DB bug

we have upgraded production to 10.1.24 and everything worked fine

it seems more that both problems are related to an unclean shutdown (maybe because of low resources ?) and mysql not being able to recover from crash and start 

in the 1st case have you tried to specially start sql with --skip-grant-tables repair the tables that are reported in the logs ?

in the 2nd case that you had to use innodb_force_recovery it seems that you might need to dump all databases (or at least the problematic ones), delete them, start mariadb without innodb_force_recovery and restore the databases

https://mariadb.com/kb/en/mariadb/xtradbinnodb-recovery-modes/

needless to say to snapshot the VMs before you try anything

**Comment by EdNett** [comment]
I'm going to close this issue - can't recover the db at all - and the problem probably was due to a crash on the boa up-stable (from 3.20. TO 3.2.0, BUT with about 100 aptitude updates - far too many for my comfort zone) because of lack of memory at some point. Can't reproduce this - practically impossible to reproduce the exact state of vps before failed upgrade.

**Comment by EdNett** [comment]
I guess I should reopen this since I just reinstalled the server (vps) and boa in stall failed, then running a barracuda up-stable also failed - mariadb won't start.

**Comment by EdNett** [comment]
We still have this problem - are are unable to install BOA on a fresh vps with 1 GB ram. Is it possible that the default memory settings for mariadb are too high - so high that during the install or upgrade process, there isn't enough ram available to comply with the my.conf default memory requirements? This would prevent newer versions of mariadb from being started or restarted, I believe.  For an existing vps with 1 GB of RAM, the default mariadb memory setting should be no more than 256 MB, don't you agree?

**Comment by EdNett** [comment]
On another production VPS, with 2 GB of ram, we found our sites down this morning - mysql was stopped. This is BOA 3.2.0 stable with mariadb latest 10.1.24. Happily mariadb started with a simple service mysql start command, but then I notices that with a ps -a command both mysqld and mysqld_safe were listed. Killing the PID of mysqld_safe also stops mysql and sites are down again. So,

1) What to do?
2) Why did mysql go down in the first place?  Can you help us troubleshoot this and (other than logs which don't tell me much information as to the cause of this problem) where to look?

Thanks.

**Comment by EdNett** [comment]
As I thought, on a 2GB vps, boa is using too much memory - specificallly innodb_buffer_pool (and probably jetty9) a php invoked oom -killer and it killed mysql first. So this is happening 2 or 3 times a week now. I have manually lowered my.cnf and phpxx.ini memory footprints.

Gist here:
https://gist.github.com/EdNett/981a3acc26374cb449d22722dd84034a

Now mysql only starts with mysqld_safe. What to do?

Can we lower default memory settings, (for phpxx.ini files - memory_limit, etc.), as well as my.cnf settings including innodb_buffer_file specifically)?

 and can jetty9 memory be configurable by us?

**Comment by EdNett** [comment]
Update: I can confirm that I am able to install BOA and do barracuda up-stables without problems on vps's from a different service provider with 4 GB of RAM and better disk IO. We were using OVH which has great prices, but whose disks seem to benchmark superslow compared to linode, digital ocean, etc.

**Comment by EdNett** [comment]
I'll close this, and leave it as a heads up that to successfully restore a mariadb 10.1 + db with innodb, enough RAM needs to be free to regenerate the entire innodb_pool - at least.
