### ISSUE TITLE
re-alive MariaDB Server after installing mysql-server accidentelly

### ISSUE THREAD

**Issue by InfraSteven** [omega8cc/boa#1174]
Unfortunately i installed mysql-db-server in a running boa system. Uninstalling and recovering /var/lib/mysql and the configuration files doesn´t take any effect. How can i get back the state before my accident?

thanks for help

**Comment by omega8cc** [comment]
You can add `_SQL_FORCE_REINSTALL=YES` to your `.barracuda.cnf` and run barracuda upgrade.

It's documented at https://github.com/omega8cc/boa/blob/master/lib/settings/barracuda.sh.cnf#L253
