### ISSUE TITLE
Feature request - Stretch - some Server Providers only install stretch now - there is no option to install Jessie

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1176]
Hi,

A feature request to use Debian 9 "Stretch" as default instead of Jessie. At least some server rental companies no longer offer Jessie as an install option, only Stretch!

I know it may be a while, but, nevertheless ...

Ed

**Comment by omega8cc** [comment]
It's planned for 3.3.0

**Comment by fotiDim** [comment]
My provider supports only Debian Stretch. Is BOA incompatible for now? Is there an ETA on Strech compatibility?

**Comment by omega8cc** [comment]
Debian Stretch will be supported starting with BOA-3.3.0, which is expected later this month.

**Comment by AntiNSA** [comment]
Whats the deal on this ? Is this still happening?

**Comment by attiks** [comment]
Wondering the same since Debian 8 is about to enter security support only

**Comment by EdNett** [comment]
Hi, Can I close this now, since 4.0.0 is stretch?  Or, please close this if it should be closed. Thanks for stretch!
