### ISSUE TITLE
Deny bots on non-prod domains, not only on aliases

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1178]
Ever since the is_dev detection got changed to site aliases only, I haven't found an out-of-box boa solution to denying bots on tmp or dev domains. What would you suggest? It would great to utilize something like is_dev or is_tmp detection for automatic handling.

**Comment by omega8cc** [comment]
It is a clear omission, indeed.

**Comment by omega8cc** [comment]
Should be fixed now.

**Comment by pricejn2** [comment]
Looks great. Thanks!
