### ISSUE TITLE
? minor issues with 3.2.0 stable barracuda up and octopus up

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1180]
There are two minor errors during a barracuda up-stable and octopus up-stable  from 3.2.0 to 3.2.0: Are these something that need to be looked at (there don't seem to be any issues arising from them)?

barracuda up-stable:

Do you want to upgrade Aegir Master Instance? [Y/n] y
BOA [10:27:47] ==> INFO: Running Aegir Master Instance upgrade
BOA [10:27:51] ==> INFO: Syncing provision backend db_passwd...
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'aegir_root'@'server1.example.com'

then during the octopus up-stable:

DEBUG AegirSetupA
BOA [10:48:28] ==> UPGRADE A: Aegir automated install script part A
BOA [10:48:28] ==> UPGRADE A: Checking OCTOPUS version...
BOA [10:48:28] ==> UPGRADE A: OCTOPUS version test: OK
BOA [10:48:28] ==> UPGRADE A: Shared platforms code v.001 will be used
BOA [10:48:28] ==> UPGRADE A: Creating directories with correct permissions
BOA [10:48:32] ==> UPGRADE A: Syncing provision backend db_passwd...
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'o1'@'server1.example.com'

Regards,

ed

**Comment by omega8cc** [comment]
This is purely cosmetic problem, which needs to be silenced, I think.
