### ISSUE TITLE
How can I clone a platform?

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1183]
Is there a fast way to clone a platform like openlucius in order to create a customized version of it?
For some reason the method here did not work for me https://learn.omega8.cc/how-to-add-custom-platform-properly-140 
After uploading the distribution to static and modifying the permissions and creating the platform, it does not show errors but creates vanilla drupal sites

Is there a script that simply clones a platform?

**Comment by omega8cc** [comment]
There is no clone task nor script for a platform. If you don't see the platform installation profile, make sure to delete all other default profiles in that platform first, and try to replicate built-in platforms structure.
