### ISSUE TITLE
database import with drush gives error: Drush cannot find your database connection details

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1184]
I tried to import a databse dump 'dump.sql' into a site 'foo.com' that I imported in a custom platform. 
I used the command:

`drush @foo.com sqlc < ~/static/dump.sql`

However, that gives an error:

`exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.'`

**Comment by omega8cc** [comment]
This means that your platform's codebase or the site's files structure is somehow broken or incomplete. Or it's a Drupal core version not supported by Drush version you have. Or that you have broken permissions, so Drush can't access all files it needs to read.

**Comment by Corvalan** [comment]
Confirmed..working now. Thanks
