### ISSUE TITLE
Unable to install RVM under octopus account

### ISSUE THREAD

**Issue by kunago** [omega8cc/boa#1185]
I am currently unable to install the RVM under octopus account using the documented method, by creatting the ~/static/control/compass.info.

I have previously updated barracuda to have RVM in the system by using "CSS" as en extra, and RVM is accessible as root. Octopus accounts do not have it installed.

Running "manage_ltd_users.sh" manually, I get this output:

-----

gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
mktemp: failed to create file via template ‘/usr/local/rvm/rvm-exec-test.XXXXXX’: Permission denied
Archives path '/usr/local/rvm/archives' not writable, aborting.
Already installed ruby-2.3.1.
To reinstall use:

    rvm reinstall ruby-2.3.1

Using /usr/local/rvm/gems/ruby-2.3.1
Done for /data/disk/<user>

-----

I have not done any modifications manually. The system is Debian 8, installation is rather recent, it was a clean install.

**Comment by omega8cc** [comment]
Interesting, but something doesn't look correct here:

> Done for /data/disk/

It doesn't list the octopus system username in this path, which is not expected, no matter if RVM setup works or not.

What is the octopus system username and the problematic SSH account username?

**Comment by kunago** [comment]
I digged around a bit and found out that while barracuda update works fine, I receive an error while trying to update my octopus instances. At the time of a regular update I receive in between the lines this error:

"ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'kunago'@'server.kunago.com'"

Looking at the database, I can this user properly set with this host, meaning user "kunago@server.kunago.com" exists, yet it cannot be deleted. Might this be a hint?

No modifications have been done to the system, no custom changes.

**Comment by omega8cc** [comment]
This error is irrelevant in this context and a cosmetic issue only (should be silenced soon).

**Comment by kunago** [comment]
I am including some files for analysis.
[ls-home-output.txt](https://github.com/omega8cc/boa/files/1251554/ls-home-output.txt)
[kunago.octopus.cnf.txt](https://github.com/omega8cc/boa/files/1251555/kunago.octopus.cnf.txt)
[cat-passwd-output.txt](https://github.com/omega8cc/boa/files/1251567/cat-passwd-output.txt)

There is only one client, and that is the user "kunago". It seems that all users exist.
