### ISSUE TITLE
How to set correct permissions on /data/disk/o1/config/server_master/nginx/passwords.d/* (to allow HTTP Basic Auth to work)

### ISSUE THREAD

**Issue by dsnopek** [omega8cc/boa#1187]
See this issue in the hosting_tasks_extra queue:

https://www.drupal.org/node/2903654

In short, nginx is unable to read the file at:

/data/disk/o1/config/server_master/nginx/passwords.d/test.o1.sub.aegir.local

If I do `chmod -R a+rx /data/disk/o1`, then it'll work for a moment, but after a few seconds the permissions will be reset and nginx will no longer be able to open that file.

I'm assuming that it's some process in BOA that's resetting those file permission, but I can't find it, let alone figure out how to override it.

This is (I think) the last thing preventing HTTP Basic Auth from working! (You need to use the latest Git of the hosting_tasks_extra module to get passed some other issues)

I'd really appreciate the help! Thanks!

**Comment by omega8cc** [comment]
Thanks for the report. We don't include/enable this feature in BOA, because it didn't work as expected before, but we shall look at this again.

**Comment by dsnopek** [comment]
Any advice on how I can make the permissions for that directory stick? Even if this doesn't get fixed upstream, I'd really like to figure out how to support it on our server.

Even just pointing to which script from BOA is reverting permission changes to that directory would be super useful!

Thanks!

**Comment by dsnopek** [comment]
Since I don't know how to modify how BOA is setting these permissions, I tried making the permissions stay with ACLs:

```
cd /data/disk/o1 # or whatever the Octopus is called
setfacl -m user:www-data:rx config/
setfacl -m user:www-data:rx config/server_master/
setfacl -m mask:rx config/server_master/
setfacl -m user:www-data:rx config/server_master/nginx/
setfacl -m mask:rx config/server_master/nginx/
setfacl -m user:www-data:rx config/server_master/nginx/passwords.d/
setfacl -m mask:rx config/server_master/nginx/passwords.d/
setfacl -m user:www-data:r config/server_master/nginx/passwords.d/*
setfacl -m mask:r config/server_master/nginx/passwords.d/*
setfacl -m default:user:www-data:r config/server_master/nginx/passwords.d/
setfacl -m default:mask:r config/server_master/nginx/passwords.d/
```

This works for me, but is overly complicated since ACLs aren't really needed, I just don't know where the permissions are being changed to fix it there... Posting in case someone else is trying to make this work!

**Comment by dsnopek** [comment]
Blergh. The ACL approach worked in my VM, but is failing on the live server. :-/ It's resetting the ACL mask with the file permissions. I wish I knew what script was resetting the permissions!

**Comment by dsnopek** [comment]
Ok, I'm like 90% sure that it's manage_ltd_users.sh that's resetting the permissions and here's a PR to try and open up access to the password files for HTTP basic auth: https://github.com/omega8cc/boa/pull/1189

**Comment by omega8cc** [comment]
Indeed, looks like it should do the trick. Committed. Thank you!
