### ISSUE TITLE
What actions are not supported by BOA using Webmin

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1192]
Since Webmin is a BOA installation option, I would like to know what actions in Webmin are safe, not recommended or will break the installation. Some questions:

1) What was the motivation of including Webmin in the BOA installation options? What useful and safe funtionality was in mind when including it?

2) I did not find such documentation, has someone wrote something about this already?

3) For example for creating virtual hosts on the server through Webmin, but outside the reach of the aegir system. Because I haven't been successful in creating working virtual hosts manually using the (unsupported) method mentioned in the faq.txt using folder  /var/aegir/config/server_master/nginx/vhost.d/
Yes, I know BOA is not supposed to serve custom sites outside of Aegir, I think my need is common in the sense that the BOA optimized hosting environment is unique and no such environment seems to be available out of the box without Aegir.

4) At the moment I use Webmin mainly for its nice web based file manager. I could drop Webmin but did not find a similar/better other web based file manager that could be safely installed on a BOA system. Maybe you have recommendations. The reason for using such web based file managers is because FTP clients are unable to remotely decompress zip files on the server. And yes, I want to reduce command line work to the minimum.

**Comment by cvining** [comment]
I'm interested in the response here as well.

I've been using Webmin, well, forever. Way longer than I've used BOA. I install it on most everything.

On my BOA system I use Webmin for virtual hosts a fair bit and it seems to work well enough for me. Once you get one working template, making more is easy peasy. I don't do anything very complex, though I do have a low volume WordPress site working that way.

**Comment by omega8cc** [comment]
While Webmin is a huge tool, with many modules available to install, we have included it only for one simple reason: to provide a web based interface to manage [Bind9 DNS server, if installed](https://github.com/omega8cc/boa/blob/master/docs/NOTES.txt#L22). 

There were never any other plans or intentions behind adding it as an optional add-on.
