### ISSUE TITLE
Does boa/aegir take care of duplicate modules in sites/all/modules ?

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1195]
When I add my custom sites to built-in core Drupal platforms, I move the custom sites contrib modules into the folder sites/all/modules/contrib-foocom folder. As far as I understand this is the recommended place to put all contrib modules.

Up to now that went well for a number of sites.
Today after a BOA upgrade one site broke with the error

`Error: Cannot redeclare ctools_cache_plugin_type() (previously declared in /data/disk/o1/distro/002/drupal-7.54.2-stage/sites/all/modules/contrib-gracias/ctools/includes/cache.plugin-type.inc:8) in /data/disk/o1/distro/002/drupal-7.54.2-stage/sites/all/modules/contrib-webdesigngroup/ctools/includes/cache.plugin-type.inc, line 11`

Then I checked all the contrib-foo.com folders to check if more than one ctools module was present. There was, I removed one and after renaming (migrating) the site I got this:

`Drush command terminated abnormally due to an unrecoverable error. Error: Class 'EntityCacheNodeController' not found in /data/all/000/core/drupal-7.54.2/includes/common.inc, line 8242`

Then after migrating the site, all was well again.

My question is: 

1. I thought that BOA takes care of any duplicate modules in the sites/all/modules folder and subfolders?
2. If not, how can we keep contrib modules together per site, so future exports of the site will be complete?
3. Is it only for the purpose of migrating sites, that the sites contrib modules need to be moved out of their foo.com/modules folder into sites/all/modules/contrib-foocom folder? If that is the case, that would mean a LOT of work to maintain sites in BOA.

**Comment by omega8cc** [comment]
1. No, BOA doesn't manage your codebases (you manage them) and it doesn't care if you put multiple copies of the same module in the same platform codebase, which causes problems you have experienced. Uploading site specific modules in the sites/all/modules is against the purpose of this directly, which very loudly says *SITES/ALL*. It is a mistake and you should never do this, anywhere. It is nothing Aegir or BOA specific, it is how Drupal works.

2. Use separate platforms for sites which need custom codebase, and only occasionally use sites/sitename/modules for custom or ad-hoc modules which don't rely on paths to includes, and don't introduce db schema changes on upgrades.

3. We never recommended such practice to use site specific subdirectories in sites/all/modules. Again, it says *ALL*. It's explained in detail in our docs, where we quote also Aegir maintainers -- see recipe number four at https://learn.omega8.cc/the-best-recipes-for-disaster-139

You may also want to read:

https://learn.omega8.cc/managing-your-code-in-the-aegir-style-110
https://learn.omega8.cc/your-drupal-site-upgrade-safe-workflow-298
