### ISSUE TITLE
Automated, rotated daily backups for all databases in /data/disk/arch/sql not happening

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1197]
The folder /data/disk/arch/sql shows eight folders of the past eight days, but they are all empty.
Apparently the folders are created but databases are not backed up automatically.

**Comment by omega8cc** [comment]
Try to run the db backup script in /var/xdrago manually to see what errors it will report.

**Comment by omega8cc** [comment]
Typically, this happens when your disk usage is too high already.
