### ISSUE TITLE
Site breaks using Database Update task

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1198]
I' wondering if the Database Update task actually is safe to use with the current issues around 'required' UTF8MB4 conversion. Drupal.org decided with the latest 7.x version to make updating a non-UTF8MB4 database impossible without first converting it, so I gues there must be a valid reason for that.

Anyway, for a custom site in static I needed to update a module and applied the Database Update task in Aegir, as recommended in another issue here. The result is a completely broken site, which keeps being broken when a database restore is performed. I now have to restore the complete site from my amazon backup. If I missed a best practices doc about updating modules, please let me know.

**Comment by yaazkal** [comment]
The regular way is not to update the module. You create a new platform that includes the new version of the module and then you migrate the site from your platform to the new one. Aegir will automatically do a backup an in the process of migration it will run any database update, if it found any error, it roll back the action and you never have a site that has gone.

To have that automatic feature please use makefiles when creating platforms.

Also please refer to the documentation for how-tos and more information: [Your Drupal Site Upgrade -- Safe Workflow](https://learn.omega8.cc/your-drupal-site-upgrade-safe-workflow-298)

**Comment by yaazkal** [comment]
Please algo check [The best recipes for disaster](https://learn.omega8.cc/the-best-recipes-for-disaster-139)

**Comment by Corvalan** [comment]
Thank you yaazkal for your helpful suggestions. Much appreciated!
