### ISSUE TITLE
Feature request: Clone a platform

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1202]
A number of issues here have referred to the possibility of cloning a platform. 
One of the reasons this is useful for developers, is that updating a module requires the creation of a new version of the platform, which is such a regular task that developing a site on Aegir becomes tedious. As mentioned in https://github.com/omega8cc/boa/issues/1198#issuecomment-326697092

> The regular way is not to update the module. You create a new platform that includes the new version of the module and then you migrate the site from your platform to the new one

**Comment by omega8cc** [comment]
This is what makefiles are for. You can't bootstrap a codebase, only a site running it, so you can't use Drush to "clone" codebase alone, while Aegir is basically a Drush extension plus web frontend for this Drush extension. Aegir is not a tool to manage your codebases, it's a tool to manage your Drupal sites. Managing codebases is something where Drush makefiles or Composer play their roles.
