### ISSUE TITLE
Suggestions for automatic hourly backup and daily backup export

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1204]
It is very convenient developing sites directly in the Aegir system. However, I am now manually backing up development sites every hour, and exporting the latest backup every day.
What would be the recommended way to create an automatic hourly (or scheduled) backup of a site?
Is it possible to trigger drush actions to do this, using a cron tab?

**Comment by omega8cc** [comment]
You could use Aegir built-in backups for scheduled backups per site, managed by Aegir. It's a standard feature, although we don't enable it by default in Aegir.
