### ISSUE TITLE
Undo automatic CoreForceDisabled for dblog in a development environment site

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1205]
Another great feature of Drupal, for developers, is the dblog module which includes more drupal specific details about error logs than the general server log files.

However, this module gets force-disabled automatically in BOA.  Apparently because of server performance reasons. However, I think that it would be nice to either have some on/of switches for features that are force-disable by default or alternatively a way to allow dblog, such as when it is a 'dev' subdomain (dev.foo.com)

This would be in line with the current dev.foo.com alias feature that allows disabling of caching.

Because BOA is (as far as I understood) a semi-development environment (combi of development, staging and production sites), I think it is rather important to provide one or more 'switches' in the Aegir site configuration page that instantly create a workable environment (dblog, devel, uncaching, etc).

Although this probably is a feature request, I am looking forward to your much appreciated feedback and possible workarounds for the time being.

**Comment by angel0d** [comment]
@Corvalan you can use the _SKIP_MODULES setting in .barracuda.cnf which though has global effect

https://github.com/omega8cc/boa/blob/master/docs/MODULES.txt#L30

in my experience disabling such modules across all sites is a good thing because some day you might enable dblog or devel on a live site and BOA will disable it for you in case you forget it

**Comment by Corvalan** [comment]
@angel0d  I agree with you with regard to the purpose of the default global [FD] setting.
I see that FD happens weekly on saturday according to the modules.txt, so that leaves me room to enable those modules for development sites. Weekly enabling them manually for the development sites is doable. Thanks!
