### ISSUE TITLE
Upgrade drush to 8.1.12 version

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1206]
Current version of drush in BOA is 8.1.10, will be great to have 8.1.12 in order to support an update from D8.3 to D8.4 in the near future as seems drush 8.1.12 is the minimum compatible version to make the update to a D8.4 site.

https://www.drupal.org/project/drupal/releases/8.4.0-rc1
https://www.drupal.org/node/2874827

**Comment by omega8cc** [comment]
It will be included in BOA-3.2.1

**Comment by omega8cc** [comment]
```
o1@quad:~$ drush --version
 Drush Version   :  8.1.15-dev
```
