### ISSUE TITLE
Cannot perform the task Delete Site

### ISSUE THREAD

**Issue by vebester** [omega8cc/boa#1210]
Cannot perform the task Delete Site on D8 platform that was not installed but was verified after manual installation.
The log contains error
Could not write database backup file mysqldump (command: mysqldump --defaults-file=/dev/fd/3  --single-transaction --quick --no-autocommit --skip-add-locks --hex-blob ) (error: Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
)
Why make the backup of a deleted site at all?
Another D7 site was successfully deleted.

**Comment by omega8cc** [comment]
If the site or its database no longer exists (or never existed, if installation failed), you need to clean up things manually -- delete the site's leftovers on disk and its node in Aegir. See also: https://learn.omega8.cc/aegir-task-fails-or-spins-forever-126
