### ISSUE TITLE
update vim to 7.4 or newer

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#1212]
The Vim that BOA ships with doesn't support the awesome `:set number relativenumber` hybrid that https://jeffkreeftmeijer.com/vim-number/#hybrid-line-numbers shows.  A newer version would be appreciated.

**Comment by omega8cc** [comment]
BOA doesn't install vim from sources. It's installed from a Debian package, so the vim version depends on the OS version you are using.
