### ISSUE TITLE
How to upgade BOA to get the built in platform Drupal 7.56.1

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1214]
Today I performed
$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt 
$ barracuda up-stable 
$ octopus up-stable all both 

But I still don't see Drupal 7.56.1 as platform available. 
What should I do to get that platform?

**Comment by omega8cc** [comment]
Are you sure the Octopus upgrade was complete without errors? Please make sure you have correct value(s) in the `_PLATFORMS_LIST` variable (typically: `ALL`) and that you didn't limit it via `~/static/control/platforms.info` file.
