### ISSUE TITLE
Notifications about new BOA editions are sent to notify@omega8.cc

### ISSUE THREAD

**Issue by reswild** [omega8cc/boa#1219]
I've noticed that I never receive any notifications about new available BOA editions for any of my servers like I used to. Looking into this, I find that they are all sent to notify@omega8.cc instead of to my email address. This is set in line 3431 in daily.sh: https://github.com/omega8cc/boa/blob/master/aegir/tools/system/daily.sh#L3431

I tried to manually edit the email address, which worked for one night, but this was overwritten again next morning.

I have my email address listed correctly in .barracuda.cnf, and as far as I can tell, I receive all other email notifications from the servers as normal. Is there something I'm missing here?

**Comment by omega8cc** [comment]
It's a bug caused by clearly very old configuration in these maintenance scripts. We should stop replacing the template placeholders, and use proper includes, since it's not replaced during frequent self-updates, which results with the placeholder left in place, instead of the correct address.

**Comment by omega8cc** [comment]
This will be fixed automatically in ~15 minutes on all systems with `_SKYNET_MODE` empty or `ON`.

Thanks for the report!
