### ISSUE TITLE
PDNSD Unable to start

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1226]
After doing a simple up-stable from 3.2.0 stable to 3.2.1 stable, pdnsd wouldn't restart; The error message was bad IP address on line 28 of /etc/pdnsd.conf which is

ip=cloud.online.net;

commenting this out allowed pdnsd to start. This is in the google-servers server section, right after ip=10.6.30.8

Is this just a temp error, or a real one, and is commenting out that line the correct temp fix?

This is on a php 7 only system, jessie, stable, mariadb 10.1.

Best,

Ed

**Comment by omega8cc** [comment]
Hmm.. I have seen something like this before, but we couldn't reproduce the problem for a long time already. Something to re-visit again..

**Comment by EdNett** [comment]
Hello,  We ran an up-stable for 3.2.1 again and no longer have this problem. We have the google data ip=8.8.8.8 and ip=8.8.4.4   This is what we have always seen before, I believe.  I'll leave you to close this, but it appears to be fixed to us.

**Comment by EdNett** [comment]
Closing this as too old
