### ISSUE TITLE
Error BOA install - undefined function ctools_include()

### ISSUE THREAD

**Issue by sluc23** [omega8cc/boa#1229]
I'm getting an error on a fresh BOA 3.2.1 installation
Installing in Bare Metal box (I know it's unsupported but I don't think that might be the issue), tried both **in-stable** and **in-head** and getting the same results. Attaching install logs from last executing with HEAD

There is an error on the AEgir master install and the AEgir Octopus install, in both cases got drush error like this:

```
Platforms permissions of /var/aegir/platforms have been changed to 755.                                      [success]
Platforms path /var/aegir/platforms is writable.                                                             [success]
Installing site with the "profile" method.                                                                   [ok]
The following module is missing from the file system: <em class="placeholder">hostmaster</em>. For           [warning]
information about how to fix this, see <a href="https://www.drupal.org/node/2487215">the documentation
page</a>. bootstrap.inc:1143
Fatal error: Call to undefined function ctools_include() in /var/aegir/hostmaster-HEAD/profiles/hostmaster/modules/contrib/views/views.module on line 1505
Drush command terminated abnormally due to an unrecoverable error.                                           [error]
Error: Call to undefined function ctools_include() in
/var/aegir/hostmaster-HEAD/profiles/hostmaster/modules/contrib/views/views.module, line 1505
The external command could not be executed due to an application error.                                      [error]
Generated config in write(): Drupal sites.php file (/var/aegir/hostmaster-HEAD/sites/sites.php)              [success]
Changed permissions of /var/aegir/hostmaster-HEAD/sites/sites.php to 644                                     [success]
Could not find the alias @hostmaster                                 [error]
The command could not be executed successfully (returned: Could not find the alias @hostmaster               [error]
                 [error]
, code: 1)
```

[boa info](https://gist.github.com/sluc23/02a73d8767eaec73484a5def5fe5a72b)
[/var/aegir/install.log ](https://gist.github.com/sluc23/b3c9dfb5abf091c65491e4e6283192e6)

**Comment by sluc23** [comment]
I've installed in a linode box and didn't get that error, so might be something very specific from that box.
I'll keep on searching the cause..

**Comment by sluc23** [comment]
And in a virtualbox in the same network.. same error :weary: 
Is there a way to install BOA in a "debug" mode?

There is something that is breaking the AEgir installation somehow..

**Comment by sluc23** [comment]
After a deep debugging we found out that there is an issue when BOA script downloads and tries to unzip this file:
http://nl.files.aegir.cc/dev/BOA-3.2.1/static/ctools-7.x-1.12.tar.gz

Looks like it's corrupted or similar. @omega8cc  could you please confirm that ?
tx!

```
$ curl -L --max-redirs 10 -k -s --retry 10 --retry-delay 5 -A iCab  http://nl.files.aegir.cc/dev/BOA-3.2.1/static/ctools-7.x-1.12.tar.gz -o ctools-7.x-1.12.tar.gz
$ tar -zxvf ctools-7.x-1.12.tar.gz 
ctools/
ctools/tests/
ctools/tests/math_expression_stack.test
ctools/tests/ctools.plugins.test
ctools/tests/ctools_plugin_test.module
ctools/tests/ctools_plugin_test.info
ctools/tests/css_cache.test
ctools/tests/plugins/
ctools/tests/plugins/cached/
ctools/tests/plugins/cached/ctoolsCachedPluginArray.class.php
ctools/tests/plugins/cached/ctoolsCachedPluginArray2.class.php
ctools/tests/plugins/cached/plugin_array.inc
ctools/tests/plugins/cached/plugin_array_dne.inc
ctools/tests/plugins/cached/plugin_array2.inc
ctools/tests/plugins/not_cached/
ctools/tests/plugins/not_cached/ctoolsNotCachedPluginArray2.class.php

gzip: stdin: unexpected end of file
ctools/tests/plugins/not_cached/ctoolsNotCachedPluginArray.class.php
ctools/tests/plugins/not_cached/plugin_array.inc
ctools/tests/plugins/not_cached/plugin_array_dne.inc
ctools/tests/plugins/not_cached/plugin_array2.inc
ctools/tests/css.test
ctools/tests/ctools.drush.sh
ctools/tests/math_expression.test
ctools/tests/object_cache.test
ctools/tests/ctools_export_test/
ctools/tests/ctools_export_test/ctools_export_test.install
ctools/tests/ctools_export_test/ctools_export_test.info
ctools/tests/ctools_export_test/ctools_export_test.module
ctools/tests/ctools_export_test/ctools_export_test.default_ctools_export_tests.inc
ctools/tests/ctools_export_test/ctools_export.test
ctools/tests/context.test
ctools/term_depth/
ctools/term_depth/plugins/
ctools/term_depth/plugins/access/
ctools/term_depth/plugins/access/term_depth.inc
ctools/term_depth/term_depth.module
ctools/term_depth/term_depth.info
ctools/ctools.module
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by omega8cc** [comment]
The file is fine, and has the same exact size on all our mirrors, plus, it worked on all instances we host in EU with zero issues. A simple test to confirm the file integrity:

iMac:~ albert$ curl -I http://nl.files.aegir.cc/dev/BOA-3.2.1/static/ctools-7.x-1.12.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 20 Nov 2017 18:05:48 GMT
Content-Type: application/octet-stream
Content-Length: 433707
Last-Modified: Tue, 22 Nov 2016 03:59:22 GMT
Connection: keep-alive
ETag: "5833c29a-69e2b"
Expires: Wed, 20 Dec 2017 18:05:48 GMT
Cache-Control: max-age=2592000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

iMac:~ albert$ curl -I http://us.files.aegir.cc/dev/BOA-3.2.1/static/ctools-7.x-1.12.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 20 Nov 2017 18:05:57 GMT
Content-Type: application/octet-stream
Content-Length: 433707
Last-Modified: Tue, 22 Nov 2016 03:59:22 GMT
Connection: keep-alive
ETag: "5833c29a-69e2b"
Expires: Wed, 20 Dec 2017 18:05:57 GMT
Cache-Control: max-age=2592000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

iMac:~ albert$ curl -I http://uk.files.aegir.cc/dev/BOA-3.2.1/static/ctools-7.x-1.12.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 20 Nov 2017 18:06:10 GMT
Content-Type: application/octet-stream
Content-Length: 433707
Last-Modified: Tue, 22 Nov 2016 03:59:22 GMT
Connection: keep-alive
ETag: "5833c29a-69e2b"
Expires: Wed, 20 Dec 2017 18:06:10 GMT
Cache-Control: max-age=2592000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

iMac:~ albert$ curl -I http://jp.files.aegir.cc/dev/BOA-3.2.1/static/ctools-7.x-1.12.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 20 Nov 2017 18:06:17 GMT
Content-Type: application/octet-stream
Content-Length: 433707
Last-Modified: Tue, 22 Nov 2016 03:59:22 GMT
Connection: keep-alive
ETag: "5833c29a-69e2b"
Expires: Wed, 20 Dec 2017 18:06:17 GMT
Cache-Control: max-age=2592000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

iMac:~ albert$

**Comment by sluc23** [comment]
@omega8cc thanks for the confirmation.

Yes there is something very weird when we download this file from our network with curl..
Manually using wget and unzip works fine..

Well at least I could narrow the problem to get until here. Closing the issue because is something internal
