### ISSUE TITLE
octopus hostmaster querry stable 3.2.1 

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1230]
Hello,
(This is a BOA stable 3.2.1 php 7 only  mariadb 10.1 production server ) This is after a second up-stable 3.2.1 barracuda and a forced octopus up-stable.

We notice that in our octopus hostmaster GUI site we have listed as Platforms the following:
1) Is the fact that no drupal release is listed for most hostmaster pltforms a problem?
2) Is the fact that the hostmaster instance is NOT in the latest hostmaster platform a problem? If so, should it be migrated manually to the latest hostmster 10 platform?
3) Lastly, could this be the reason why our LE certificates are not being renewed? Could this be the reason why a symbolic link is mising perhaps, or why the directory structure might be different in current hostmaster instances than in earlier ones?  Thus could this be the cause of this issue: https://github.com/omega8cc/boa/issues/1179

Thank you.
 
  | Platform | Release | Server | Verified | Sites

  | Aegir Hostmaster 002 | drupal 7.56 | server1.example.com | 1 hour 23 min ago | 0
  | Aegir Hostmaster 003 |   | server1.example.com | 3 weeks 14 hours ago | 0
  | Aegir Hostmaster 004 |   | server1.example.com | 3 weeks 14 hours ago | 0
  | Aegir Hostmaster 005 | drupal 7.56 | server1.example.com | 1 hour 23 min ago | 0
  | Aegir Hostmaster 006 |   | server1.example.com | 10 months 3 weeks ago | 1
  | Aegir Hostmaster 007 |   | server1.example.com | 10 months 3 weeks ago | 0
  | Aegir Hostmaster 008 |   | server1.example.com | 8 months 2 weeks ago | 0
  | Aegir Hostmaster 009 |   | server1.example.com | 8 months 2 weeks ago | 0
  | Aegir Hostmaster 010 |   | server1.example.com | 8 months 2 weeks ago | 0
  | Drupal-7j-Custom-Ubercart | drupal 7.56 | server1.example.com | 1 hour 24 min ago | 5
  | hostmaster | drupal 7.56 | server1.example.com | 1 hour 24 min ago | 0

boa info more is here:
https://gist.github.com/EdNett/8bfb75a58859e3b0a735d3402599f25a

Im going to manually verify all the hostmaster platforms, and the hostmaster site, as it appears that only the second oldest hostmaster platform which does not contain the hostmaster site is being verified automatically - this may be a symptom of an error somewhere in the octopus upgrade script?

Manually verifying the platforms without a release entry, gave them all the drupal 7.56 release entry.

**Comment by omega8cc** [comment]
These empty platforms should be deleted automatically, but there is a regression in Aegir which prevents this from happening. Needs a proper fix, since it adds annoying noise in the platforms list.

That said, if your existing hostmaster site is listed in the incorrect hostmaster platform, something is perhaps broken in the drush aliases and/or hostmaster database, like incorrect nid registered etc.

Unfortunately, we can't provide an easy fix to help you. It needs manual intervention in the drush aliases and hostmaster database.
