### ISSUE TITLE
Query re backup method of emergency LE cert renewal (manual renewal with params)

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1231]
Hello,

Isn't there a way to run a command line LE/dehydrated cert renewal specifying in the renew command certain parameters, for example to use only IPv4, (since our error message indicates that the IPv6 address is being used, and the error is an unresponsiveness timeout) and specifying BOA's unusual /.well-known/.acme-challenge/ path?  This could be a very helpful backup or emergency method of renewing a certificate in case of trouble with octopus renewing it (as we are currently having this trouble again).

If this is a possibility, could you please let us know what the command line renewal command would be, with IPv4 only paramaters, and let us know if we need to specify server full paths, or only example.com/paths ? This would really be a big help, and would also serve as a second backup method of renewing certificates in a fix.  We think there is a problem with the current BOA 3.2.1 stable nginx vhost directives and their location alias directives, but cannot solve the problem ourselves.

This relates to the re-occurrance (I think it's the same problem as before, or very similar to what happened before) here:
https://github.com/omega8cc/boa/issues/1179

Thank you very much.

**Comment by omega8cc** [comment]
We need to use `--ipv4` flag, as discussed in #1179 -- you can't really do this reliably on command line to avoid issues, because it requires the Aegir backend code to be run too.
