### ISSUE TITLE
ssl_stapling issue for boa 3.2.1

### ISSUE THREAD

**Issue by david8653** [omega8cc/boa#1232]
Good Day, 

Hi, i am sorry to disturb. I have been install boa for several time for new vps company and all went well. i have been use boa system for a long time, But when i try to edit from no ssl to ssl for the exampledomain.com but the ssl is not working, try to service nginx status  and found out  nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/...openssl.crt". I have view the location of the file and the file is there does this mean the chown or permission problem. Do i need to manually change the file?

Best Regard
David

**Comment by omega8cc** [comment]
The ssl_stapling message is normally harmless, and you should check the Verify task log to make sure what exactly fails. Remember to expand truncated lines in the task log to read complete output.

**Comment by david8653** [comment]
Just foud out is the le module, 

""[hosting_le] ACME Output: # # !! WARNING !! No main config file found, using default config! # + Generating account key... + Registering account key with letsencrypt...   + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-reg (Status 400)  Details: {   "type": "urn:acme:error:malformed",   "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",   "status": 400 }  rm: cannot remove ‘/data/disk/o1/tools/le/domains.txt’: No such file or directory   Error registering account key. See message above for more information. |  
-- | --  ""

and 

[hosting_le] Hmm.. For some reason cert_dir doesn't exist: /data/disk/o1/tools/le/certs/example.com

Best regard
david

**Comment by omega8cc** [comment]
Whats is the result of this test there?

`grep LE-SA /data/disk/o1/tools/le/letsencrypt.sh`

**Comment by david8653** [comment]
Hmmm.. my mistake.. i change it at /var/xdrago/conf. 
Dint notice there is letsencrypt.sh at le folder.
Thanks alot. Thank you for your time. 
I would like to help out if there is any. i am very new to programming.
