### ISSUE TITLE
is mysql service auto-started?

### ISSUE THREAD

**Issue by sluc23** [omega8cc/boa#1233]
I need to perform some **mysql** maintenance tasks and I discovered that after some minutes I stop the service, then it is automatically started.
Is there any cron job that automatically starts **mysql** service? 
In that case how do we proceed when we need to set it down manually?

Tx!

```
server:/var/lib/mysql# service mysql stop
[ ok ] Stopping MariaDB database server: mysqld.

server:/var/lib/mysql# mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

** After 1 minute **

server:/var/lib/mysql# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 38
Server version: 10.1.29-MariaDB-1~jessie mariadb.org binary distribution

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```

**Comment by angel0d** [comment]
@sluc23 i think you could/should simply stop cron when you perform maintenance tasks like BOA does during updates

**Comment by sluc23** [comment]
@angel0d stopping cron service did the trick ;)
I'm wandering if it's a good practice to have a cron job starting automatically mysql service when it's down.. :thinking:

**Comment by omega8cc** [comment]
@sluc23 -- It's by design, as listed in the project readme:

https://github.com/omega8cc/boa/blob/master/README.txt#L138
https://github.com/omega8cc/boa/blob/master/README.txt#L137
