### ISSUE TITLE
Querry on how to get 3.2.2-dev - up-head gives 3.3.0-dev

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1235]
Hello,

We recently did a barracuda up-head, (from 3.2.1-stable) trying to get 3.2.2-dev, but instead got 3.3.0-dev. Is this normal? 

And, is there a way to specify 3.2.2-dev head?

Thanks,

Ed

**Comment by omega8cc** [comment]
This is expected, because once we decided to release more editions in the 3.2.x series after the HEAD was tagged as 3.3.0-dev, we couldn't switch the dev tag back to 3.2.x-dev to avoid confusion -- just ignore this.
