### ISSUE TITLE
Upgrade to 3.2.1 killed D8 site, but not D7 sites

### ISSUE THREAD

**Issue by startinggravity** [omega8cc/boa#1238]
A gist showing the output of `boa info` is [found here](https://gist.github.com/startinggravity/622f55e52d6fa49d36b060e0265c569f)

Today I updated Barracuda and Octopus to version 3.2.1 on an installation that hosts three small D7 sites and one D8 site. Everything seemed to go normally and all sites on the system appeared to be unaffected. Initially, all sites displayed correctly. Later, however, I discovered the D8 was no longer running.

I didn't make any changes to the D8 site beforehand and only ran the script to update BOA, as prescribed in the docs.

I am getting this error any time I attempt verify, flush caches, or what-have-you from the Aegir site management page:
```

exception 'Symfony\Component\DependencyInjection\Exception\LogicException' with message 'Service 'cache_tags.invalidator.checksum' for consumer 'cache_tags.invalidator' does not implement Drupal\Core\Cache\CacheTagsInvalidatorInterface.' in /data/disk/o1/static/hike_8-2-5_2017-02-10/core/lib/Drupal/Core/DependencyInjection/Compiler/TaggedHandlersPass.php:125
Stack trace:
#0 /data/disk/o1/static/hike_8-2-5_2017-02-10/vendor/symfony/dependency-injection/Compiler/Compiler.php(104): Drupal\Core\DependencyInjection\Compiler\TaggedHandlersPass->process(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#1 /data/disk/o1/static/hike_8-2-5_2017-02-10/vendor/symfony/dependency-injection/ContainerBuilder.php(590): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#2 /data/disk/o1/static/hike_8-2-5_2017-02-10/core/lib/Drupal/Core/DrupalKernel.php(1263): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /data/disk/o1/static/hike_8-2-5_2017-02-10/core/lib/Drupal/Core/DrupalKernel.php(866): Drupal\Core\DrupalKernel->compileContainer()
#4 /data/disk/o1/static/hike_8-2-5_2017-02-10/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#5 /data/disk/o1/static/hike_8-2-5_2017-02-10/core/lib/Drupal/Core/DrupalKernel.php(701): Drupal\Core\DrupalKernel->boot()
#6 /data/disk/o1/static/hike_8-2-5_2017-02-10/core/includes/utility.inc(42): Drupal\Core\DrupalKernel->prepareLegacyRequest(Object(Symfony\Component\HttpFoundation\Request))
#7 /data/disk/o1/tools/drush/commands/core/cache.drush.inc(302): drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#8 [internal function]: drush_cache_rebuild()
#9 /data/disk/o1/tools/drush/includes/command.inc(422): call_user_func_array('drush_cache_reb...', Array)
#10 /data/disk/o1/tools/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#11 [internal function]: drush_command()
#12 /data/disk/o1/tools/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#13 /data/disk/o1/tools/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#14 /data/disk/o1/tools/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 /data/disk/o1/tools/drush/drush.php(12): drush_main()
#16 {main}
```

[I found a reference to Redis here](https://github.com/md-systems/redis/issues/19), indicating that if the Redis module is missing this error will occur. Seeing that, I confirmed that a symlink still exists in my modules directory to the `o_contrib_eight` directory. I traced this through additional symlinks back to the Redis module at `/data/all/000/modules/redis_eight/`. This leads me to believe the module remains correctly in place, as it was before the update.

I am now at a loss as to what is preventing the D8 site from loading.

**Comment by startinggravity** [comment]
My D8 site is now running again, but the way I fixed is not ideal. I would like to know what I should have done differently.

As I suspected, the problem was the result of my site expecting Redis to be enabled, but was not able to find Redis. In digging around for how Redis was installed and enabled by the system, I found the file `/data/disk/o1/config/includes/global.inc`. I made a single change, as noted below, altering `$use_redis = TRUE;` to `$use_redis = FALSE;`.

```
/**
 * Core version detection
 */
if (file_exists('web.config')) {
  if (file_exists('core')) {
    if (file_exists('vendor/symfony') || file_exists('core/vendor/symfony')) {
      $drupal_eight = TRUE;
      $use_redis = FALSE; // Originally set to TRUE.
      if ($is_dev && !$is_backend) {
        header('X-Backend: A');
      }
    }
```

This change feels as dirty as hacking core and affects performance, so I wish to put things back to normal. Unfortunately, I don't understand the system well enough to know why it failed after updating BOA to version 3.2.1 and how to correctly direct Redis to my site.

**Comment by omega8cc** [comment]
This sounds very unusual.. but if you need to disable Redis, you don't need to hack the `global.inc` file.

You can use [site or platform level INI variable](https://github.com/omega8cc/boa/blob/master/aegir/conf/default.boa_site_control.ini#L125).

**Comment by startinggravity** [comment]
I put the `global.inc` back to TRUE and verified the site again. There were no repercussions. 

I don't want to disable Redis, but if I need to again, now I know what to do. Thank you.

**Comment by omega8cc** [comment]
Redis support in Drupal 8 has been much improved since 2018, so closing.
