### ISSUE TITLE
Known incompatibility issues from contrib module Redirect in Drupal 8 and BOA

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1239]
As a follow up from #1061 and #1215 I'll like to open this issue for two reasons. 1) Summarize what are the known issues and their fix and 2) Let the community know what is still not working.

### Summary
In Drupal 8, the [Redirect module](https://www.drupal.org/project/redirect) seems to have any kind of incompatibility when installed on a site hosted on a BOA environment. As redirect loops seems to be a configuration issue I guess this should be fixed in BOA. I've tested the same site and configuration on local machine using php-fpm 5.6 and nginx (similar to the production BOA server) and I can't find the described issues. This only happens when _Drupal 8 + Redirect_ is hosted on BOA.

### Partial fixes

- A common issue was infinite loops like `q=/?q=/?q=/`. This has been solved on commit https://github.com/omega8cc/provision/commit/a36d8ca7a27450d5e4134f5baf6ce75e32b280e5 which is included on BOA 3.2.1
- Another issue is the manual execution of cron or other administration task wich also creates an infinite loop. To solve this, just make sure in your Redirect module that the option `Allow redirections on admin path` is checked.

### Still not working.
They don't work if the option _Enforce clean and canonical URLs_ is enabled
- **You can't use the search capability provided by D8 core**.
You'll get a loop redirection like `/search/node?keys=magic&keys=magic&keys=magic` etc; where _magic_ is the searched word.
- **You can't reference an entity using autocomplete in a field.**
The list of entities to be referenced never shows up. You just see the icon spinning forever.
If you check the console on your browser, you can see loop redirection like `/entity_reference_autocomplete/node/default:node/_rAnDoM?q=magic&q=magic`.
Where _magic_ is the word you type to reference a node called _Magic node_ and _rAnDoM_ is a random hash.
- **You can't navigate a View using pagination.**
If you have a view with a pager, clicking on the _next page_ or any number page it will not work. There is also a loop: `/?page=1&page=1&page=1&page=1&page=1` etc.

**Comment by omega8cc** [comment]
Thank you for documenting this problem, however I'm not sure if this is related to Nginx configuration at this point, since we have fixed this in Provision, and there is nothing BOA specific on the web server configuration level anymore (I think). Maybe it is Redis caching related?

**Comment by omega8cc** [comment]
Have you tried to disable this feature with:

`redis_path_enable = FALSE`

in the site's INI file?

**Comment by yaazkal** [comment]
Thanks for the update. Seems that has no effect.
In the next outputs I replaced my real domain for _example.com_

```
o1.ftp:[modules]$ pwd
/data/disk/o1/static/drupal_8.4.x/sites/example.com/modules
o1.ftp:[modules]$ cat boa_site_control.ini | grep 'redis_path_enable'
redis_path_enable = FALSE
```

I forgot to said in the original post that the site is under cloudflare. Anyway I have tested the site with and without cloudflare enabled and with cloudflare page rules on and off (which can generate some issues) but that only confirms to be the server.

Extra info:

```
yaazkal@PC ~ $ curl -I https://www.example.com/?page=1
HTTP/1.1 301 Moved Permanently
Date: Tue, 02 Jan 2018 20:42:01 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d290c3923c36a083ca09212fd1618805b1514925721; expires=Wed, 02-Jan-19 20:42:01 GMT; path=/; domain=.example.com; HttpOnly
X-Cookie-Domain: .example.com
Location: http://example.com/?page=1&page=1
X-Drupal-Route-Normalizer: 1
X-UA-Compatible: IE=edge
Content-language: es
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Cache-Control: must-revalidate, no-cache, private
expires: -1
pragma: no-cache
X-Device: normal
X-Speed-Cache: MISS
X-Speed-Cache-Key: /?page=1
X-NoCache: Cache
X-This-Proto: https
X-Server-Name: example.com
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Server: cloudflare
CF-RAY: 3d708ade5ee72e75-MIA
```

**Comment by yaazkal** [comment]
Today I'm working on this and see if I can troubleshoot it better.

Interesting thing is that if the site is a subdomain it works.

I mean, on _example.com_ the issue is present, but on _subdomain.example.com_ not. Also tried the domain without the _www_ alias in the url but issue is present.

**Comment by omega8cc** [comment]
Hmm.. this makes it extra weird..

**Comment by yaazkal** [comment]
@omega8cc I'm still troubleshooting it. I've tried many configuration options (like redirect all alias to domain name on/off). I feel I'm close, I'm now testing things with SSL (with SSL disabled, enabled and required).

I would said now that in some way this can be related to https://github.com/omega8cc/boa/issues/790#issuecomment-258349255

Look what I got when I query directly the server (I've changed the real domain name for _example.com_  and the real IP for _SERVER_IP_:

```
yaazkal@Athena-PC ~ $ curl -vso /dev/null --user-agent "Mozilla 5.0" -H "Host: example.com" https://SERVER_IP/search/node?keys=magic
*   Trying SERVER_IP...
* Connected to SERVER_IP (SERVER_IP) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 0
```

**Comment by yaazkal** [comment]
Anyway no look even with SSL off on the site trough the aegir control panel and off on cloudflare. I still have the redirect. Querying directly the server:

```
yaazkal@Athena-PC ~ $ curl -vso /dev/null --user-agent "Mozilla 5.0" -H "Host: example.com" http://SERVER_IP/search/node?keys=magic
*   Trying SERVER_IP...
* Connected to SERVER_IP (SERVER_IP) port 80 (#0)
> GET /search/node?keys=magic HTTP/1.1
> Host: example.com
> User-Agent: Mozilla 5.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: close
< X-Cookie-Domain: .example.com
< Date: Thu, 18 Jan 2018 23:57:07 GMT
< Location: http://example.com/search/node?keys=magic&keys=magic
< X-Drupal-Route-Normalizer: 1
< X-UA-Compatible: IE=edge
< Content-language: es
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Cache-Control: must-revalidate, no-cache, private
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< X-Device: normal
< X-GeoIP-Country-Code: CO
< X-GeoIP-Country-Name: Colombia
< X-Speed-Cache: MISS
< X-Speed-Cache-Key: /search/node?keys=magic
< X-NoCache: Cache
< X-Server-Name: example.com
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
<
{ [6 bytes data]
* Closing connection 0
```

**Comment by yaazkal** [comment]
@omega8cc 
>Hmm.. this makes it extra weird..

You are right. Sorry, my mistake, I checked that the module where present on both sites but not that they have the same configuration. The issue is also present on the subdomain site.

**Comment by tourtools** [comment]
same problem also with redirect 8.x-1.2 released on 4 May 2018 on a 8.5.1 Drupal core,
each ajax call made for path autocompletion results in a 500, ex:

`XHR failed loading: GET "http://my.domain.com/linkit/autocomplete/default?q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof&q=prof ..... (hundreds of repeating lines)`

**Comment by ahillio** [comment]
@danielgroen if you're using BOA then it should be safe for you to un-check at option.  Omega8.cc's hosted BOA instances have clean URLs enforced by default in the web server configuration, and so I presume it's the same in the self-hosted BOA (unless you changed that server config?).

**Comment by fotiDim** [comment]
I am using BOA on my own server and I am running into the exact issue. Locally everything works fine. It is indeed a BOA issue.

**Comment by fotiDim** [comment]
Is there any chance a fix is included in the upcoming BOA version? This is big blocker for our use case. I assume it is something in `nginx_vhost_common.conf` that creates this redirect but my knowledge with NGINX does not help me further.

**Comment by omega8cc** [comment]
This is really tricky situation after the module removed more granular settings. Previously you could disable just their problematic clean URLs enforcing, but later they bundled this with Canonical URLs redirecting, and you obviously don't want to disable this feature, because it's one of the main reasons why you have installed the module!

Here is  the snippet from the module install file:

```
/**
 * Removes unnecessary settings from storage.
 */
function redirect_update_8106() {
  $config = \Drupal::configFactory()->getEditable('redirect.settings');
  $config->set('route_normalizer_enabled', $config->get('normalize_aliases'));
  $config->clear('term_path_handler');
  $config->clear('normalize_aliases');
  $config->clear('deslash');
  $config->clear('frontpage_redirect');
  $config->clear('nonclean_to_clean');
  $config->save();
}
```

Too bad they removed the `nonclean_to_clean` and now have simply `route_normalizer_enabled`.

We should find the actual culprit, since attempts to enforce module settings are not very useful.

**Comment by omega8cc** [comment]
OK, let's see if disabling this helps:

```
###
### Force clean URLs for Drupal 8.
###
#rewrite ^/index.php/(.*)$ $scheme://$host/$1 permanent;

```

**Comment by fotiDim** [comment]
@omega8cc does not help. I tried checking what I wrote above `you cannot see media entities of type "remote video".` It is loading and loading forever." and the problem persists.

**Comment by omega8cc** [comment]
@fotiDim Thanks for the feedback, we need to investigate more.

**Comment by omega8cc** [comment]
We have finally found the culprit and it has been fixed with these commits:

https://github.com/omega8cc/provision/commit/e1b9f36babf454c9c89169aa36d99e28e36d7def
https://github.com/omega8cc/provision/commit/a495cb59f5bce700354a8e4f59a5e5492d0b2f24

**Comment by omega8cc** [comment]
![varbase-demo-search-php7 3](https://user-images.githubusercontent.com/128547/50720579-e6dbda80-10af-11e9-93b3-1e2e47a7b8dd.jpg)

![redirect-settings](https://user-images.githubusercontent.com/128547/50720580-efccac00-10af-11e9-9ff0-7de4f6d9566d.jpg)

**Comment by fotiDim** [comment]
Neat! When can we expect the 4.0.0 release?
