### ISSUE TITLE
Feature request: Refactor the boa script to accept named parameters

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1244]
## Problem
At this moment, `boa` script seems to use a stric mode when talking about parameters, those parameters should be given in certain order so if you miss one of them or if you put them in a different order maybe you will end up running an incorrect BOA installation generating in some cases a wrong behavior.

## Proposed solution
Refactor the `boa` script to accept named parameters, like `boa -version='in-sable' -mode='public' -fqdn='server.example.com'`. Wins:

- If no parameter is present the script can just fallback to a default value instead of guessing a bad parameter (like assigning `o1` as the `mail` if the user forgot to put the mail)
- Allows the user to give the parameters in any order when installing.
- Ignore some parameters if they are not really needed (like in a migration, more later).
- Keep a more easy to mantain boa script.

#### Using environment variables
The `boa` script can be run stablishing environment variables and then _at the end of the script **unset** them to prevent unexpected behavior if the user wants to run it again_. It can be run like this:

`# version='in-stable' mode='public' fqdn='server.example.com' boa`

or

`# boa -k version='in-stable' mode='public' fqdn='server.example.com'`

Then in the script the "parameters" (in reallity they are not) are just needed to be used after the corresponding validation.

#### Using getopts
As far as I know a caveat of this is that parameters must be only one letter.
Like:

`# boa -v 'in-stable -m 'public' -fqdn 'server.example.com'`

More info: http://wiki.bash-hackers.org/howto/getopts_tutorial

#### Write the script as a program
Like using Python (http://docopt.org), Ruby or Go so the parameters can be handled.

## Use case (when the current behavior is not desired).
If you want to migrate BOA instance to a new server, you will use the `xboa` script as in [docs/MIGRATE.txt](https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt)

Let's say that for any reason (OS upgrade, Datacenter migration, VPS specs upgrade, etc) a user wants to migrate to a new server. The user wants the new server to run php-7.0, so when installing the new server:

`# boa in-stable public server.example.com php-7.0`

User expects PHP 7.0 to be installed but the default php version (PHP 5.6 in this case) is installed as if no php version was given.

So the user is forced to enter something like:

`# boa in-stable public server.example.com o1 none php-7.0`

just to keep the parameters in order and to allow the script to catch the php version.

Now, the problem is that in order to make the migration, the octopus instance should not exist.

Of course this has a basic workaround, like putting `o2` or a different user name to install an useless octopus instance, but is not the best time effective task.

Also the script as it is can be modified to just let the user run the command as the first one, but I made all this long issue thinking in the wins for the future and to prevent some "weird" behaviour.

**Comment by omega8cc** [comment]
Thank you for the proposition, but we have avoided parameters intentionally, and this is not going to change.

The idea is to make the commands readable for normal humans, not only for experienced sysadmins.

The other idea behind the current implementation is that people should read the docs, pay attention, and don't try to be too creative around the how-to's provided, because we can't work around all possible "creativity".

We do welcome improvements to the project docs about installation and upgrades procedures, and this the area where any such effort should be directed, in our opinion.
