### ISSUE TITLE
New Install Failure

### ISSUE THREAD

**Issue by hometowncauses** [omega8cc/boa#1246]
Trying to install on BudgetVM, clean Debian 8.0 x86_64 OS. Have used BudgetVM in the past and had no problems installing...however, this installation hangs/fails silently.

From a clean OS install, I first set up SSH:

login as: root
root@198.71.80.181's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@198701:~# mkdir .ssh
root@198701:~# chmod 700 .ssh
root@198701:~# cd .ssh
root@198701:~/.ssh# vi authorized_keys
root@198701:~/.ssh# chmod 600 authorized_keys
root@198701:~/.ssh# cd .
root@198701:~/.ssh# cd ..
root@198701:~# ls -ald .ssh .ssh/authorized_keys
drwx------ 2 root root 4096 Feb  2 10:13 .ssh
-rw------- 1 root root  398 Feb  2 10:13 .ssh/authorized_keys
root@198701:~#

Exit, then re-login and run the install script:

Using username "root".
Authenticating with public key "rsa-key-20180202" from agent

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Feb  2 10:11:53 2018 from cpe-172-100-236-199.nycap.res.rr.com
root@198701:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
dpkg: warning: package not in database at line 1: curl
dpkg: warning: found unknown packages; this might mean the available database
is outdated, and needs to be updated through a frontend method
touch: cannot touch '/var/xdrago/log/fixPSop.ctrl.322stableQ1.pid': No such file or directory

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
Bye

sysctl: permission denied on key 'net.ipv4.tcp_challenge_ack_limit'

The system is ready for BOA installation!

We will start screen session for you in 15 seconds
to avoid problems with dropped SSH connections
during BOA stack installation, which may take up to
30-60 minutes, depending on your server speed.

If your connection will drop, simply log in again
and re-attach your session with 'screen -R' command.

Please wait a moment until this message disappears.

Enjoy!
root@198701:~#

Nothing at all happens. Have tried this several times...Waited hours, then exited out of screen mode and terminal. Nothing installed. 

Thanks in advance for your help! As I said, I've installed/used this in the past and loved it... ;-)

**Comment by yaazkal** [comment]
Please refer to the documentation: https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt

You'll find that you need to run another script after the BOA meta installer, like `boa in-stable public server.mydomain.org my@email o1` depending on your needs.

**Comment by hometowncauses** [comment]
Tried that...

bash: in-stable: command not found
 ;-(

Been a while since I installed this last, but I seem to remember a lot happening after it went into screen mode....and notified me somehow to run the in-stable command. There is absolutely nothing there...

root@198701:~# dir
BOA.sh.txt
root@198701:~#

Thanks for your reply. Any other ideas?

**Comment by yaazkal** [comment]
@hometowncauses please take your time and read the documentation with calm.

Look that the command after running the BOA meta installer _can_ be something _like_:

`boa in-stable public server.mydomain.org my@email o1`

Where:

**boa** is script that you run to install it.
**in-stable** is the type of installation
**pubic** is the scope of the installation
**server.mydomain.org** is the name of the server (FQDN)
**my@email** is _your_ email
**o1** is the name of the octopus installation.

To run and maintain a BOA server you'll have to know some basic sysadmin skills in order to don't get a nightmare later, so if you feel is too complicated I'll suggest to you to try the managed services from https://omega8.cc or read and try the documentation after you understand what you are going to do.

Regards.

**Comment by hometowncauses** [comment]
sorry...typo forgot the boa part...

Now this:

root@198701:~# boa in-stable public boa.hometowncauses.org admin@hometowncauses.org o1 max
ERROR: BOA requires minimal, supported OS, with no services installed
ERROR: The only acceptable exceptions are: sshd and mail servers
Bye
root@198701:~#

It's a clean install, so not sure why I'm getting this, unless my hosting company adds something. Probably something to do with the initial dpkg errors in my first post on this issue.

Thanks for your help. As I said, I have installed this before with this hosting company and never had an issue... ;-(

**Comment by hometowncauses** [comment]
Back to square one...and still can't get it installed. While I appreciate yaazkal's help..., as I said, I have installed this several times before using this provider and never encountered this problem.

I have submitted an issue with my provider, and they say it is a plain vanilla install; he did, however, think that the touch error might be a problem, and so created those directories/files thinking that might be it..While I was incredulous I did try, and did not work.

So, I again installed a plain vanilla Debian 8 OS and started from scratch, thus....

login as: root
root@198.71.80.181's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@198701:~# mkdir .ssh
root@198701:~# chmod 700 .ssh
root@198701:~# cd .ssh
root@198701:~/.ssh# vi authorized_keys
root@198701:~/.ssh# cd .
root@198701:~/.ssh# cd ..
root@198701:~# cd .ssh
root@198701:~/.ssh# dir
authorized_keys
root@198701:~/.ssh# chmod 600 authorized_keys
root@198701:~/.ssh# cd .
root@198701:~/.ssh# cd ..
root@198701:~# ls -ald .ssh .ssh/authorized_keys
drwx------ 2 root root 4096 Feb 20 11:20 .ssh
-rw------- 1 root root  398 Feb 20 11:20 .ssh/authorized_keys
root@198701:~# dir
root@198701:~#


Using username "root".
Authenticating with public key "rsa-key-20180220" from agent

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Feb 20 11:17:13 2018 from cpe-172-100-236-199.nycap.res.rr.com
root@198701:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
dpkg: warning: package not in database at line 1: curl
dpkg: warning: found unknown packages; this might mean the available database
is outdated, and needs to be updated through a frontend method
touch: cannot touch '/var/xdrago/log/fixPSop.ctrl.322stableQ1.pid': No such file or directory

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
Bye

sysctl: permission denied on key 'net.ipv4.tcp_challenge_ack_limit'

The system is ready for BOA installation!

We will start screen session for you in 15 seconds
to avoid problems with dropped SSH connections
during BOA stack installation, which may take up to
30-60 minutes, depending on your server speed.

If your connection will drop, simply log in again
and re-attach your session with 'screen -R' command.

Please wait a moment until this message disappears.

Enjoy!
root@198701:~# boa in-stable public boa.hometowncauses.org admin@hometowncauses.org o1
ERROR: BOA requires minimal, supported OS, with no services installed
ERROR: The only acceptable exceptions are: sshd and mail servers
Bye
root@198701:~#


Please wait a moment until this message disappears.

Enjoy!
root@198701:~#

Note the errors:

**_ERROR: BOA requires minimal, supported OS, with no services installed
ERROR: The only acceptable exceptions are: sshd and mail servers_**

I have again questioned my provider as to what - if anything - beyond a vanilla install might be happening on their end.

Is there any way to turn on any debugging info???

Thank you for your thoughts....

**Comment by hometowncauses** [comment]
I'm fairly certain the dpkg errors have something to do with this, but have no idea how to correct:

dpkg: warning: package not in database at line 1: curl
dpkg: warning: found unknown packages; this might mean the available database
is outdated, and needs to be updated through a frontend method

How do I know what the unknown packages are, and what do I do about updating the database??? I'm assuming this is a database of the packages in the Debian 8 image used, but...????

I admit my sysadmin skills need a brushup, but a little direction would be helpful.

Thanks again!

**Comment by hometowncauses** [comment]
No thoughts at all?

**Comment by angel0d** [comment]
@hometowncauses i see on budgetVM they are using openVZ which is not supported/tested virtualization technology by BOA

it might have worked in the past but it sounds to me that you need to find another provider if you need better compatibility and support from maintainers/community 

if you choose to use a specific provider/software you might be the only one doing so and no one can help

there are tons of providers with the supported technologies

* Linux KVM guest
* Linux VServer guest
* Microsoft Hyper-V
* Parallels guest
* VirtualBox guest
* VMware ESXi guest
* Xen guest

**Comment by hometowncauses** [comment]
Thank you so much...I can see where that might be the problem. It did work in the past, so perhaps they've changed their virtualization platform. Will check with them to see if I have any other option.

**Comment by hometowncauses** [comment]
Need plain vanilla install of debian 8 system ONLY - no web services
installed.

My problem had been that my provider installed web services in one
configuration, but not in another. I switched to their cloud server and
installed flawlessly.
