### ISSUE TITLE
Feature request: Support imagick on PHP 7.0

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1252]
At the moment, it is explicit to not install [imagick](http://pecl.php.net/package/imagick) on PHP 7.0 on a BOA environment [/lib/functions/php.sh.inc#L587](https://github.com/omega8cc/boa/blob/678b096f1a7fbc4dff7ff06cd78178cc50a168dd/lib/functions/php.sh.inc#L587)

Starting at version 3.4.0 (released on 2016-03-04), imagick has added PHP 7.0 support for [ImageMagick](https://www.imagemagick.org) API (version 6 or 7 of the API).

Please enable the installing of imagick in PHP 7.0

**Comment by yaazkal** [comment]
Had no time to work on it (was my intention). Thanks so much @pricejn2 for the PR.

**Comment by pricejn2** [comment]
I had just done a similar pr for jsmin so it was fresh in my mind and easy to do.

**Comment by omega8cc** [comment]
Both PR accepted, thank you 👍
