### ISSUE TITLE
_SSH_FROM_SOURCES in .barracuda.cnf is not respected on fresh install

### ISSUE THREAD

**Issue by bery** [omega8cc/boa#1260]
Hi,

when I try to install BOA on a clean system, the config setting _SSH_FROM_SOURCES is always set to YES. I have my reasons why I do not want to recompile SSH from source as I am trying to install BOA on Google cloud instance and Google has its own SSH client and when SSH is recompiled from source, I am no longer able to ssh to the instance.

Would you be able to have a look and make sure that the installation honors the configuration found in .barracuda.cnf?

**Comment by omega8cc** [comment]
We have switched at some point to enforced build from sources after some serious issues experienced by users with distro specific versions installed from packages (not just related to security).

We shall look into possibility to allow this to be configurable again.

**Comment by bery** [comment]
Thank you.

The reasons why you did that were obvious to me, yet I would appreciate to have the possibility to live on the edge.
