### ISSUE TITLE
Custom config redis not respected on updates (for VMs on linux-vserver)

### ISSUE THREAD

**Issue by angel0d** [omega8cc/boa#1265]
With a simple search I see that _VMFAMILY checks and sets are in 25 different files and used as one more way to identify when a VM is a managed one or not

I understand this is not something that can easily change but for those who (am I the only one ?) that opted in to use the installer for linux-vserver released a few months ago has a few side-effects

so far I have one main issue to report. that `_CUSTOM_CONFIG_REDIS=YES` is not respected on updates

**Comment by angel0d** [comment]
i see that _CUSTOM_CONFIG_SQL should not have similar problems as it checks again

[line 55 of sql.sh.inc](https://github.com/omega8cc/boa/blob/81545b78b050e4524634ef3523725ecba9c79375/lib/functions/sql.sh.inc#L55)
```
  if [ "${_CUSTOM_CONFIG_SQL}" = "NO" ] \
    || [[ "${_THISHOST}" =~ ".host8." ]] \
    || [[ "${_THISHOST}" =~ ".boa.io" ]] \
    || [ "${_VMFAMILY}" = "VS" ]; then
    if [ "${_CUSTOM_CONFIG_SQL}" = "YES" ]; then
      _DO_NOTHING=YES
else
--

could the same be used on line 231 in [redis.sh.inc](https://github.com/omega8cc/boa/blob/c13ad67cc314edb4a39382ccac1a841a7d76cd89/lib/functions/redis.sh.inc#L231) ?

if not, @omega8cc would you consider maybe removing line 234 from redis.sh.inc for now ?

**Comment by angel0d** [comment]
in case I am not the only one with this problem here is a suggestion for anyone facing the same problem

> set up a cron job that enforces certain redis non-default settings on the fly

```
# re-configure currently running redis instance.
redis-cli -a $(cat /root/.redis.pass.txt) config set maxmemory                  8000MB
redis-cli -a $(cat /root/.redis.pass.txt) config set lazyfree-lazy-eviction     yes
redis-cli -a $(cat /root/.redis.pass.txt) config set lazyfree-lazy-expire       yes
redis-cli -a $(cat /root/.redis.pass.txt) config set lazyfree-lazy-server-del   yes
```

**Comment by omega8cc** [comment]
Oops.. fixed finally!
