### ISSUE TITLE
nginx-extras - is there a way for nginx to be compiled with the lua or perl modules?

### ISSUE THREAD

**Issue by wunluv** [omega8cc/boa#1266]
Both the lua and perl modules for nginx are compiled when nginx is installed using `apt-get install nginx-extras` but this is not the BOA way to go about. How may we get the functionality of these modules following BOA best practices?

I require one of the modules for complex rewrite rules using regular expressions that convert uppercase to lower case. Everywhere I've looked so far point to using one of these two modules.

**Comment by omega8cc** [comment]
While you can't easily add third-party modules, you can enable modules available in Nginx by default.

Example: add `--with-http_perl_module` to `_NGINX_EXTRA_CONF` in your `/root/.barracuda.cnf` file and add there also `_NGX_FORCE_REINSTALL=YES`. Then simply run barracuda system update.

Note that it may not work out of the box. For more information see also https://nginx.org/en/docs/http/ngx_http_perl_module.html
