### ISSUE TITLE
A simple domain alias redirect to a subdirectory of a site

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1267]
Does the Aegir ui have a simple way to redirect another domain to a subdirectory of the same site, instead of the root? I want to use multiple domains for one site.

**Comment by yaazkal** [comment]
Hi, I don't think Aegir has an UI for that. Anyway you can create your own nginx redirects: https://github.com/omega8cc/boa/blob/master/docs/HINTS.txt

**Comment by Corvalan** [comment]
Thanks. That link shows 5 examples.  As far as I see my use case of redirecting a specific domain to a subdirectory of an existing site of another domain, can be accomplished using the example
`###
### Domain specific 301 redirect for legacy .php URIs with literal location
### to stop searching for (and using) other regex based locations.
###
location = /about_us.php {
  if ($host ~* ^(www\.)?(foo\.com)$) {
    return 301 $scheme://$host/node/19;
  }
  return 403;
}`

am i correct?

**Comment by omega8cc** [comment]
>> I want to use multiple domains for one site

I'm not sure what you mean? Using multiple domains as aliases, redirects and sites in subdirectory are three different features.

Please expand on what are you trying to achieve.
