### ISSUE TITLE
adding a mount to fstab for new volume auto-mount on reboot

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1268]
Hello,

On a stable BOA 3.2.2 using php 7.0 only we ran out of disk space because of octopus backups, so I have added a volume and mounted it as /data/disk/o1/backups 

Since BOA isn't using systemd in a tradational way or systemctl, and since the fstab file is empty, I need to ask how to have the new volume auto-mounted on reboot.

I have created the file /etc/systemd/system/data-disk-o1-backups.mount  :

// start of file

[Unit]
Description=Mount NDB Volume at boot

[Mount]
What=UUID="0e5923a3-c942-4894-84fe-788f7f9159364"
Where=/data/disk/o1/backups
Type=ext4
Options=defaults

[Install]
WantedBy=multi-user.target

//end of file

Is this enough? Have I put the file in the right place? Do I need a .target file?  Can I simply use fstab (which I am familiar with), and put the entry in there?

Do I need to create a symbolic link like the existing /etc/systemd/system/multi-user.target.wants/remote-fs.target and name it data-disk-o1-backups.target ?

and put it in /etc/systemd/system/reboot.target.wants  ?

Thanks for a little help on this. I greatly appreciate it.

Best,

Ed

**Comment by omega8cc** [comment]
systemd is not used in BOA and is uninstalled. Please consult your host for information on how to properly mount extra disk space on your system. We can't provide this type of advice.
