### ISSUE TITLE
SA-CORE-2018-001 - D6 Pressflow hotfix for older versions

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#1270]
I guess was out of drupal world for a while, but there was previous security fix on February 21, which was applied on D6 pressflow - https://github.com/pressflow/6/commit/fc43e72dc72834ee1a1a08479b68daadaf69ef03. If there are users with Pressflow 6.38 as I am now and didn't upgraded, they might be vulnerable to https://www.drupal.org/sa-core-2018-001 attacks. As I don't see BOA patch for that here - https://github.com/omega8cc/boa/tree/236b7630becebf6c630b2135621014c746d67053/aegir/patches/6-core, so maby it would be smart to apply that also for D6 platforms that don't have this security issue fixed yet?

Not sure why SA-CORE-2018-001 (Critical) wasn't patched automagically as today SA-CORE-2018-002 (Highly Critical) was. Maby you are willing to patch only Highly Critical ones, what is the BOA policy here? SA-CORE-2018-001 involves alll the core versions also. So, this might be not only for D6, but for D7, D8 platforms also.

Omega8cc team, cheers for the awesome you are doing for keeping us safe, guys, I'm really impressed on responsiveness and continious work, you really are the experts on security! ;)

**Comment by omega8cc** [comment]
The issue with Pressflow is that it's going to be deprecated in BOA, and will not receive any fixes nor updates. We have actually announced this many months ago, so if you continue to use Pressflow 6, you should stop using builtin platforms and instead use custom platforms in ~/static

We will still keep the repo at https://github.com/omega8cc/pressflow6 updated, but we will no longer include existing D6 platforms in any future updates nor security fixes. SA-CORE-2018-002 was an exception.

**Comment by Pls** [comment]
Sure, makes sense. Probably the answer is migrate sites from D6 to D7/D8 whenever possible, because of D6 being so ancient and vulnerable to all sorts of attacks. And supporting ancient versions doesn't make much sense.

**Comment by omega8cc** [comment]
Yes, people should stop using Drupal 6, or at least upgrade to latest available version: https://github.com/omega8cc/pressflow6/releases

**Comment by omega8cc** [comment]
We have applied hot fixes to D6 too, and there was also a new core version released in our forked repo: https://github.com/omega8cc/pressflow6/releases/tag/6.44.1
