### ISSUE TITLE
Advanced Nginx microcaching to improve cache HITs

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#1271]
I think that BOA should consider adding advanced Nginx Microcaching options, which are recommended on this blog post - https://siipo.la/blog/never-miss-the-cache-with-nginx-microcaching

Are there any drawbacks on using this advanced microcaching method in BOA? Related discussion in Trellis pull request - https://github.com/roots/trellis/pull/962

**Comment by omega8cc** [comment]
Which option do you mean, specifically?

The only directive we don't use is `fastcgi_cache_background_update` but it doesn't make any noticeable difference, as shown on the stats in this article.

![nginx-cache-http-response-time-background-update-1400x788](https://user-images.githubusercontent.com/128547/42422045-a53868ea-82df-11e8-97d4-15c0e2458730.png)

**Comment by Pls** [comment]
Yeah, I mean `fastcgi_cache_background_update`. So, it seems that there is no point in adding this option as the performance gain is so small, right?

**Comment by omega8cc** [comment]
It may seem negligible, but shouldn't hurt either.

**Comment by omega8cc** [comment]
Added: https://github.com/omega8cc/provision/commit/fac7503da1f687d2a46c58679a75d9b02f6410b3

**Comment by Pls** [comment]
Cool, thanks!
