### ISSUE TITLE
Change Welcome email to reference Adminer instead of Chive

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1272]
Some info on how to use Adminer to import databases would be great, too.

**Comment by omega8cc** [comment]
While Adminer is now installed by default, Chive is still available as an option. so both welcome email and docs still reference Chive.

It's not recommended to use Adminer nor Chive for db import/export, just for quick fixes only.

For db import you should use Drush, and for export Aegir. It's explained in the docs:

https://learn.omega8.cc/import-your-sites-to-aegir-in-8-easy-steps-109
https://learn.omega8.cc/how-to-export-your-site-from-aegir-241
