### ISSUE TITLE
Let's encrypt ACME v2

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1273]
Hi,

Are there plans to support the new ACME v2?
The main difference is, there is now support for wildcard certificates.
The dehydrated library supports from version 0.6 the v2 of ACME.

Thanks!

**Comment by omega8cc** [comment]
Yes, it's planned.

**Comment by omega8cc** [comment]
It has been done already, and wildcard semi-automated support added, but only for domains using Cloudflare name servers so far. We still need to document this, though, so I'm keeping this open.

**Comment by omega8cc** [comment]
This should be closed already, and any docs updated separately.
