### ISSUE TITLE
daily.sh: site broken because of 'drush status' for localized D8 sites

### ISSUE THREAD

**Issue by zanami** [omega8cc/boa#1275]
This is the command

daily.sh test runs 'drush status' [here](https://github.com/omega8cc/boa/blob/95f0f5b76b645bde2ccfd03db4d7453d4c4fcf6b/aegir/tools/system/daily.sh#L1101)

```
_STATUS_TEST=$(run_drush8_nosilent_cmd "status \
      | grep 'Drupal bootstrap.*:.*Successful'" 2>&1)
```
This is the command I'm trying to test 
su -s /bin/bash - o1.ftp -c "drush8 @somesite.com status"

**Here's the output for Drupal 7 sites**

```
Drupal version                :  7.58
...
 Database                      :  Connected
 Drupal bootstrap              :  Successful
```

**Drupal 8**

```
 Drupal version                :  8.4.4
 ...
 Database                      :  Connected
 Drupal bootstrap              :  Успешно
```

Успешно means Successful in russian. Almost all of my sites are in russian language, but none of D7 has this problem.

I checked if 'drush status' uses the interface translation string for 'Successful' and it does. I guess my other sites just don't have translation for 'Successful'.

So, drush messages are language dependent (unfortunately) and daily.sh isn not (and should not be).

How do I stop drush from using localized strings (or how to set default language)? Or is there a better solution for non-english sites?

**Comment by omega8cc** [comment]
We didn't take this into account, because there was no such problem in previous Drupal versions, so we don't have a method to make the bash scripts checks language neutral. Let's figure that out..

**Comment by omega8cc** [comment]
This has been fixed in:

d51eaa4f8e394c7e4b6e9664475e2e38a3ff5496
510f52192877858fccbd43a82bbcc2508dc8a0c0
