### ISSUE TITLE
Adminer only available sometimes

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1276]
I'd like to use Adminer, but sometimes all I get is a 403 "Forbidden" error.

/var/aegir/config/server_master/nginx/vhost.d/adminer.master.book04.greatcms.com has access directives set to 
  allow                        166.172.187.78;
  deny                         all;

Which is great if I usually get that ip address assigned to me, but I don't.
I tried adding allow directives which works for a short time, but the file keeps getting reset to where it was.  
Where is there a master file that this can be fixed?

**Comment by mabo1972** [comment]
For the operation of Adminer or Chive an existing SSH connection is required. You first have to connect via SSH then you can work with Adminier or Chive over the IP of the server without any problems.

**Comment by omega8cc** [comment]
It's managed on the fly. Please check the docs which apply to Adminer too: https://learn.omega8.cc/how-to-use-chive-manager-323
