### ISSUE TITLE
varbase sites won't migrate

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#1277]
I have a few test sites on Varbase 8.4.14 that won't migrate to 8.4.18 or 8.4.19.  The sites don't really have much/any configuration, just a node or two created with paragraphs, just testing out if Varbase+BOA/Aegir works.  The platform built with `composer create-project Vardot/varbase-project:^8.4.19 varbase-8.4.19 --no-dev --no-interaction` and creating the platform in Aegir UI with Drupal found at `~/static/varbase-8.4.19/docroot/` allows sites to be created on the platform, just fine, no problem.... but the sites won't migrate to a new platform.

The site migration tasks fail with error `The "file_uri" plugin does not exist`.

Output from the Aegir task which fails https://gist.github.com/ahillio/1cc5091e560eb7ff3685d892b2a6e2b7

Is anybody successfully running sites on the Varbase distribution?

**Comment by Corvalan** [comment]
Check out this thread: https://github.com/omega8cc/boa/issues/1116

**Comment by ahillio** [comment]
The error `The "file_uri" plugin does not exists.` was caused by my mistake, I neglected to `chown -R 0775 newplatform` the [way we're supposed to](https://learn.omega8.cc/how-to-add-custom-platform-properly-140).

**Comment by omega8cc** [comment]
Good to know, thanks for sharing!
