### ISSUE TITLE
Redis causing odd urls

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1278]
When I first saw that urls on my site were doing all kinds of weird things, I thought my site had been hacked. Fortunately, this was not the case, but it turns out that there is some issue with Redis and the menus returned by Drupal.

I'm getting url links with values CAPITALIZED and also menus with extra encoded spaces added to the end of links (see image).

<img width="2136" alt="screen shot 2018-04-15 at 12 27 03 am" src="https://user-images.githubusercontent.com/96553/38773132-57020572-4046-11e8-85cb-8cb139fe19a1.png">

I verified that it was indeed Redis causing the issue by disabling it via the INI. The urls went back to all lower case when redis was inactive.

After some initial research this looks to be an older issue from the [Redis queue](https://www.drupal.org/project/redis/issues/2793635) (see comment number 6). Is this happening because the Redis module being used by BOA is an older version? Also, if it is and it's not going to be updated what fix should I implement?

Maybe my server? I'm running BOA 3.2.2 and Octopus is up-to-date.

**Comment by petrowsky** [comment]
Ok, I just did a diff against the Redis module in /data/all/000/modules on my server and the latest from drupal.org. Obviously there will be differences and Omega is likely going to run whatever is most stable for their hosting.

What is the best option for fixing so I can get some better SEO happening? Again, it could be my server too.

<img width="1226" alt="screen shot 2018-04-15 at 1 06 32 am" src="https://user-images.githubusercontent.com/96553/38773338-e528b21c-4049-11e8-8019-a1a27549e55e.png">

**Comment by petrowsky** [comment]
Just found #815 and #861 but still don't know what the best solution is. Where do I read up on this?

**Comment by omega8cc** [comment]
This shouldn't happen when you have BOA stable, which includes latest 7.x-3.17 Redis integration module, but if it still happens for some reason, you should perhaps disable the feature in the site or [platform INI file](https://github.com/omega8cc/boa/blob/master/aegir/conf/default.boa_platform_control.ini#L65) with:

`redis_path_enable = FALSE`

**Comment by omega8cc** [comment]
This has been fixed a long time ago, so closing.
