### ISSUE TITLE
Open Social 8.x-1.12 distribution installation error

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1279]
exception 'Drupal\Core\Config\StorageException' with message 'Write operation is not allowed.' in /data/disk/o1/static/social/core/lib/Drupal/Core/Config/InstallStorage.php:104

The platform is created without errors.

When creating a site using this platform, this error appears when using the ´social´ profile that is selectable. The error does not appear when using the standard profile of the social platform.

![chrome_2018-04-15_05-30-35](https://user-images.githubusercontent.com/8040352/38774644-2fac93b6-406e-11e8-9de8-3da838d464e1.png)

**Comment by lexsoft00** [comment]
Hi Corvalan,

I don't know if you solved your issue, but for whoever has this problem. Install using composer and remember to give permission to the folder before adding the platform.
example:
`composer create-project goalgorilla/social_template:dev-master DIR --no-interaction`
`chmod -R 775 DIR/`
