### ISSUE TITLE
varbase gives internal server error when logging out

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1280]
Installed varbase 8.x-4.19 (not using composer)
Installes fine, but gives internal server error when logging out using the link in the menu:
http://varbase.example.com/user/logout?current=/admin/people 
( or any other current location used)

The url  of the error shows 
http://varbase.example.com/user/logout?current=/admin/people&current=/admin/people&current=/admin/people&current=/admin/people&current=/admin/people&current=/adm   ...etc

meaning it repeats the query string endlessly

**Comment by omega8cc** [comment]
I guess it's related to the known redirect module support issue #1239. Let's continue there. Thanks!
