### ISSUE TITLE
EXIT on error due to invalid DNS setup

### ISSUE THREAD

**Issue by hometowncauses** [omega8cc/boa#1282]
Trying to install on vanilla Debian8-64 and getting the following error:

BOA [16:55:20] ==> EXIT on error due to invalid DNS setup

    * Your custom _MY_OWNIP is set to "23.88.142.66"
    * Your custom _MY_HOSTN is set to "boa.hometowncauses.org"
    * Your custom _MY_FRONT is set to "master.boa.hometowncauses.org"

    * Your _MY_HOSTN and/or _MY_FRONT doesn't match your _MY_OWNIP,
      or your hostname is not set properly yet.

    * Please make sure that below command returns your FQDN hostname "boa.hometowncauses.org":

    $ uname -n

    Your server needs a working FQDN hostname pointing to its IP address.
    This means that you have to configure DNS for your hostname before
    trying to install BOA. Reverse DNS is not required, though.
    Make sure that DNS A record for boa.hometowncauses.org points to 23.88.142.66 and
    then allow some time for DNS propagation before trying this again.
    Alternatively, disable this check with _DNS_SETUP_TEST=NO

BOA [16:55:20] ==> EXIT on error due to invalid DNS setup

BOA [16:55:23] ==> Skynet Agent v.BOA-3.2.2 welcomes you aboard!

BOA [16:55:26] ==> ERROR: This octopus installer can be used only when the same version
BOA [16:55:26] ==> of boa or barracuda installer was used before. Your system must be
BOA [16:55:26] ==> upgraded with barracuda installer version BOA-3.2.2 first
BOA [16:55:26] ==> Bye

BOA in-stable completed
Bye

root@boa:~# uname -n
boa.hometowncauses.org

As you can see, the uname -n command returns the correct FQDN. I have two "A" records, one for boa.hometowncauses.org and one for '@'. I can ping the IP, hometowncauses.org, and boa.hometowncauses.org.

Tried to set _DNS_SETUP_TEST to NO, but couldn't find it...was looking in BOA.sh.txt.

What might I be doing wrong?

Thank you for your help!

**Comment by hometowncauses** [comment]
Found _DNS_SETUP_TEST in .barracuda.cnf. Seems to be running now; will see how it goes!

**Comment by omega8cc** [comment]
It's a typical issue affecting servers with different public and local IP addresses. It should be fixed in #1089
