### ISSUE TITLE
How to access hls, dash file in rtmp server

### ISSUE THREAD

**Issue by rizwanmeer** [omega8cc/boa#1286]
Here is my nginx configuration.
I am receiving live streaming in hls and dash folder but unable to access it for streaming.

worker_processes 1;

events {
	worker_connections 1024;
}

http {
	include mime.types;
	default_type application/octet-stream;
	sendfile on;
	keepalive_timeout 65;
	server {
		listen 80;
		server_name localhost;
		location / {
			root html;
			index index.php index.html index.htm;
		}
		location /live {
			types {
				application/vnd.apple.mpegurl m3u8;
			}
			alias /hls/live;
			add_header Cache-Control no-cache;
		}
		location /dash {
			alias /dash/live;

			add_header Cache-Control no-cache;
		}
	}
}

rtmp {

	server {
		listen 1935;
		chunk_size 8192;
		
		application live {
			live on;
						allow publish 127.0.0.1;
					allow publish all;
			allow play all;
			record all;
			record_path C:\Users\Administrator\Desktop/nginx/video_recordings;
			record_unique on;
			hls on;
			hls_nested on;
			hls_path C:\Users\Administrator\Desktop/nginx/hls;
			hls_fragment 10s;
			hls_playlist_length 10m;

			dash on;
			dash_path C:\Users\Administrator\Desktop/nginx/dash;
			dash_nested on;
			
			
		}

		# Video on Demand
		application vod {
			play /home/vod;
		}

		# Restream
		application restream {
			live on;
			# push server1:1935
			# push server2:1935
		}

	}

}

******** here is nginx folder details****
![nginx folder preview](https://user-images.githubusercontent.com/39165135/39906979-67b4eb84-54d5-11e8-87cd-7deee8b45662.PNG)

**Comment by yaazkal** [comment]
Hi @rizwanmeer for what I can see this not a BOA related issue or question.

I recommend you to check some nginx resources: https://www.nginx.com/resources/more/

You can ask on IRC http://webchat.freenode.net/?channels=nginx or in forums like https://serverfault.com

Good luck !
