### ISSUE TITLE
request php 7.2 sury repos

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1288]
Hello,  

We have done a lot of testing of php 7.2.5.x (non BOA testing of course, but drupal 7 testing) as taken from the sury repos, as an upgrade from php 7.0 latest - i.e. 7.0.24-7.0.27, and there are no problems (with the single exception of mcrypt, which still needs a php 7.1 download) at all, and there are major significant performance improvements.

Thus, we'd like to suggest offering php 7.2 in BOA - and we think it should work perfectly and offer major performance inprovements (as long as mcrypt isn't needed) - and we don't need to upgrade to 7.1 first. Thus to make myself clear, can you offer php 7.2 now, or soon, and simply skip the 7.1 path, as it isn't needeed?

Thank you?

Ed

P.S. We would be glad to test this on a boa stable latest if you would give us the repository you plan on using when BOA introduces php 7.2.

**Comment by omega8cc** [comment]
It's already planned, although we always build PHP from sources: https://github.com/omega8cc/boa/issues/1126
