### ISSUE TITLE
Hostmaster release Drupal 7.56.1

### ISSUE THREAD

**Issue by maninder007** [omega8cc/boa#1292]
Aegir Hostmaster Drupal release version is 7.56.1. I hope that hostmaster drupal release version should be 7.59.1. And the drupal sites I am installing via add site are also of version 7.56.1.  Is it like that or I am doing some mistake.

hostmaster | drupal 7.56 | ******.******.com | 11 hours 32 min ago | 0

Regards
maninder.

**Comment by omega8cc** [comment]
That is correct. BOA didn't have a stable release for a long time, so "stable" is already outdated and you should use "head" until new stable is released in the near future.
