### ISSUE TITLE
php 7.0.24 to 7.0.27 not happening

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1293]
Hello,    

In a recent BOA 3.2.2 stable to 3.2.2 stable upgrade, logs show that php 7.0.24 is being upgraded to 7.0.27, but in fact this is not occurring, even after a forced octopus upgrade, a server restart, etc.

boa info more is here:
https://gist.github.com/EdNett/35b9f8e7021a3b88807ee9df22e5d096

**Comment by omega8cc** [comment]
Octopus upgrade has nothing to do with PHP version upgrade. You need to upgrade barracuda, not octopus. What is the result of command:

`/opt/php70/bin/php -v`

Have you seen any errors during barracuda upgrade?

**Comment by EdNett** [comment]
Of course I know that this is a barracuda problem.

Whether I command   php -v or /opt/php70/bin/php -v  the result is the same 7.0.24 - even though the barracuda upgrade process takes a long time installing 7.0.27 - no errors are written to the screen or the log.

**Comment by EdNett** [comment]
Furthermore, recent upgrades (the last week or so) no longer let me use php 7.0 for both ci and fpm - (as they did a few months ago), but rather they insist that cli be set to a 5.x series!  What is this about?

**Comment by omega8cc** [comment]
Sorry, but we can't really help you if you are using unsupported system configuration:

`VPS unknown / not a virtual machine`

Please try to force PHP rebuild by adding `_PHP_FORCE_REINSTALL=YES` to `/root/.barracuda.cnf` and run barracuda upgrade again.

We are using head in production on all our systems for months with no issues.

**Comment by EdNett** [comment]
Hello,

Well, your answer is absurd - we have three boa servers, a test server, a dev server and a production server,  a VPS and two dedicated, and all three give the same error.  A dedicated server was never an unsupported system  - for years it was advised,  and then one day you arbitrarily decided to no longer support dedicated servers. I wonder why? This post isn't just to help us, but as a warning for all BOA users- and to help all boa users - . I would be surprised to learn that any boa user using stable has been able ot upgrade to any version of PHP 7 past 7.0.24 - please post here anyone if (using stable)  you have been able to do this and are actually running the new version.   Also, what about the fact that we cannot do a barracuda up stable using php 7.0 for cli in stable?

**Comment by EdNett** [comment]
THIS IS A BUG REPORT - as you know - NOT A QUESTION!
