### ISSUE TITLE
Cannot add octopus user if I don't upgrade

### ISSUE THREAD

**Issue by sluc23** [omega8cc/boa#1294]
According to this [docs](https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L137), I should be able to add an octopus user without having to upgrade BOA to latest version.
I'm executing this command and getting and error:

`boa in-octopus newuser@email.com newuser none 3.2.1`

```
BOA [14:10:07] ==> Skynet Agent v.BOA-3.2.2 welcomes you aboard!
 
BOA [14:10:10] ==> ERROR: This octopus installer can be used only when the same version
BOA [14:10:10] ==> of boa or barracuda installer was used before. Your system must be
BOA [14:10:10] ==> upgraded with barracuda installer version BOA-3.2.2 first
BOA [14:10:10] ==> Bye

BOA in-octopus completed
Bye
```

Is it the docs updated or I'm doing something wrong?

**Comment by sluc23** [comment]
hmm. I guess it's only for 2.4 legacy, not for 3.x previous releases

**Comment by omega8cc** [comment]
You can install any compatible Octopus version using this command, but you can't specify exact version, only one of `{stable|head|2.4}`. The trick is to add a line like this:

`echo "BOA-3.2.2" >> /var/log/barracuda_log.txt`
before installing Octopus stable when you have installed BOA head initially, or:

`echo "BOA-3.3.0-dev" >> /var/log/barracuda_log.txt`
before installing Octopus head when you have installed BOA stable initially.

**Comment by omega8cc** [comment]
Note that current Octopus stable doesn't include security fixes, and will not be fixed automatically on existing and already patched BOA system, so the recommended workflow is to install Octopus stable and immediately upgrade it to Octopus head (installing Octopus head directly may not work, as it's intended for debugging only).
