### ISSUE TITLE
Drupal 8.5.X support in BOA/Aegir

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#1295]
Just wanted clarification if BOA currently supports Drupal 8.5.X.

On BOA-3.2.2 it states:

> Thanks to Drush 8.1.15-dev we support also the newest Drupal 8.4.4 core.

So, is it limited to Drupal 8.4.X? As I understand this is a question of Drush. They state that Drush 8.X is not compatible with Drupal 8.5.X. And that only Drush 9.x is compatible with latest Drupal core 8.5.X.  

In https://github.com/omega8cc/boa/issues/1264 you stated that Drush 9 will be command line only.  https://www.drupal.org/project/provision/issues/2953349 states that Drupal 8.5.x support can't be added to Aegir for right now until proper separation is done.

What would you recommend to get Drupal 8.5.3 to BOA right now to have semi-functional site? Are there any workarounds that I haven't thought off?

As temporary solution, I just verified 8.5.3 platform, added blank site, replaced database and been using it without drush support. Would love if anyone in similar situation has some knowledge to share. Cheers!

**Comment by yaazkal** [comment]
Note that there are issues when drush is present on the project, so propertly removing drush as a dependency of the project will make it work.

I have 8.5.3 running sites on BOA and I can use drush for tasks like clearing cache, importing/exporting configuration and so on. But I'm using BOA as in HEAD, so the drush version is different (but anyway is drush 8.x)

**Comment by omega8cc** [comment]
Both BOA stable 3.2.2 and BOA head fully support latest Drupal 8.5.5

You are reading a changelog from the time when 8.4.4 was the latest version, so it's not a source of the up to date information.

While Aegir is working on a workaround to avoid conflict with Drush 9 if included in the platform's codebase, the simplest method is just to remove Drush 9 from your codebases.
