### ISSUE TITLE
Aegir won't update to D7.x

### ISSUE THREAD

**Issue by rokelvisar** [omega8cc/boa#1296]
Initial installation was with boa 2.x, but now I already have 3.x. Aegir Hostmaster is still Drupal 6.x.
Is there any manual on how to properly do the upgrade of Hostmaster instance?

**Comment by bserem** [comment]
You runned the octopus update right?
`octopus up-stable all both`

**Comment by rokelvisar** [comment]
Tried, no luck.

**Comment by yazzou** [comment]
I have exactly the same issue

**Comment by rokelvisar** [comment]
This happens when I run `octopus-up-stable all force`

`:~# octopus up-stable all force
load is 9 while maxload is 600
Octopus upgrade for User /data/disk/o1
Waiting 9 seconds...

BOA [07:28:10] ==> Skynet Agent v.BOA-3.2.2 welcomes you aboard!

BOA [07:28:14] ==> Octopus Satellite Instance Upgrade in progress...

BOA [07:28:14] ==> This Octopus URL address is o1.zofi.rokreativa.si
BOA [07:28:14] ==> This Octopus PHP version is 5.6
BOA [07:28:14] ==> This Octopus System is Debian/wheezy x86_64

BOA [07:28:22] ==> UPGRADE A: Shared platforms code v.010 will be used
BOA [07:28:58] ==> UPGRADE B: Downloading drush micro-8-07-10-2017...
BOA [07:29:01] ==> UPGRADE B: Installing Aegir Provision backend...
BOA [07:29:01] ==> UPGRADE B: Downloading Drush and Provision extensions...
BOA [07:29:04] ==> UPGRADE B: Hostmaster STATUS: Upgrade in progress...
BOA [07:39:19] ==> UPGRADE B: Hostmaster STATUS: Upgrade completed
BOA [07:39:19] ==> UPGRADE B: Aegir upgrade test result: OK
BOA [07:39:24] ==> UPGRADE B: Updating Letsencrypt cert for Hostmaster...
BOA [07:39:24] ==> UPGRADE B: Enhancing Aegir UI, please wait...
BOA [07:40:59] ==> UPGRADE A: Aegir Satellite Instance upgrade completed

Do you want to install some ready to use platforms? [Y/n] Y
Drupal 7.56.1 [010] - https://drupal.org/drupal-7.43-release-notes [Y/n] y
BOA [07:41:35] ==> DISTRO: Drupal 7.56.1 D.010 installed
BOA [07:41:35] ==> DISTRO: Drupal 7.56.1 P.010 installed
Drupal 8.0.5 [010] - http://drupal.org [Y/n] y
BOA [07:41:39] ==> DISTRO: Drupal 8.0.5 [010] installed
BOA [07:41:39] ==> UPGRADE C: Running Platforms Verify tasks, please wait...
BOA [07:41:46] ==> UPGRADE A: Platforms installed
BOA [07:41:46] ==> Final post-upgrade cleaning, one moment...
BOA [07:42:23] ==> BYE!
Waiting 6 seconds...
Done for /data/disk/o1

OCTOPUS upgrade completed
Bye`


And this is content of .../aegir/distro:

```
:~/aegir/distro$ ls -l
total 32
drwxr-xr-x 8 o1 users 4096 Jul 28  2014 001
drwxr-xr-x 9 o1 users 4096 Jun 12 07:08 010
drwxr-xr-x 8 o1 users 4096 Jun 15  2016 012
drwxr-xr-x 8 o1 users 4096 Jul 10  2016 013
drwxr-xr-x 8 o1 users 4096 Jun 12 07:08 014
drwxr-xr-x 8 o1 users 4096 Jun 12 07:08 015
drwxr-xr-x 8 o1 users 4096 Jun 12 07:07 016
drwxr-xr-x 8 o1 users 4096 Jun 28  2017 017
```

**Comment by omega8cc** [comment]
If it says "Aegir upgrade test result: OK" then it means it has been upgraded already.

While the list of platforms may not get updated if you have tried too big upgrade hop and it caused problems, you should check the hostmaster site info where Drupal tells you its real core version at /admin/reports/status

Even your hostmaster site page source tells you it's running Drupal 7 and not 6:

`<meta name="Generator" content="Drupal 7 (http://drupal.org)" />`
