### ISSUE TITLE
barracuda up-stable not working with php7.0 - bug report

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1299]
barracuda up-stable not working with php7.0 cli and fpm- bug report:

THIS is probably being caused by the upgrade script's failure to actually upgrade or install any other version of php than what is already installed - that is what we have determined for both barracuda up-stable and up-head. We are stuck at 7.0.24 - even a full reinstall from source does not give us a higher version.

BOA [16:52:09] ==> INFO: Downloading drush micro-8-07-10-2017...
BOA [16:52:18] ==> FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported versions
BOA [16:52:18] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
BOA [16:52:18] ==> FATAL ERROR: AegirUpgrade installer failed
BOA [16:52:18] ==> FATAL ERROR: Aborting Barracuda installer NOW!
BOA [16:52:09] ==> INFO: Downloading drush micro-8-07-10-2017...
BOA [16:52:18] ==> FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported versions
BOA [16:52:18] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
BOA [16:52:18] ==> FATAL ERROR: AegirUpgrade installer failed
BOA [16:52:18] ==> FATAL ERROR: Aborting Barracuda installer NOW!

barracuda file:  https://gist.github.com/EdNett/060dd7114653b0b8098a15d39faa78b6

boa info more:  https://gist.github.com/EdNett/40b85557e5a0095ca1f0fbad97ebe53c

**Comment by omega8cc** [comment]
This never happened with stable for us. Perhaps you have tried to use head? At least I can't reproduce the problem. You have incorrect values in the config file, although not sure if this contributes to the problem:

`_PHP_MULTI_INSTALL="5.6,7.0"`

This should be:

`_PHP_MULTI_INSTALL="5.6 7.0"`

**Comment by EdNett** [comment]
I'd like to merge this with bug report # 1300 and 1327 - they all seem to cover the same problem, which I can't figure out.
