### ISSUE TITLE
barracuda up-head also fails

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1300]
INFO: Downloading drush micro-8-07-07-2018...

BOA [20:08:27] ==> FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported versions

This is barracuda up-head on a supported vps - what is going on?  We sepend a lot of our time, and money and resources debugging for you, and you aren't being clear about which versions of php for cli are supported.

It doesn't seem to make a difference whether we upgrade to stable or head latest (3.2.2 or 3.3.0-dev), 👍 
1) php upgrades appear to be made but in fact they are not, and we are stuck at a lower version of php 5.6 and 7.0.

2) On head or stable, barracuda upgrades fail if we don't set php-cli to 5.6  (it used to work with 7.0), and now, head fails even if we do set php-cli to 5.6!

This is very confusing. Can't you  tell us what is going on here, and let us know if only php 5.6 for CLI will work, please,  In fact - no matter what we set _PHP_CLI_VERSION= to the aegir upgrade fails with the above error message.  How about some advice about what versions of php will work , please. And we don't understand why php 7.0 and 5.6 are not actually updating to the versions we see on the screen during the upgrade process - i.e. 5.6.33 and 7.0.30 (head) and 5.6.30 and 7.0.27 stable - we are stuck at 7.0.24

UPDATE:

Our problem isn't with setting php_cli to other than 7.0 - it is with the up-stable AND the up-head failure to install ANY new version of php and failure to upgrade ANY or ALL versions of php.  That makes the script at:
 https://github.com/omega8cc/boa/blob/master/aegir/scripts/AegirUpgrade.sh.txt

fail with the error message we receive.  Can you tell us why we can't install old version of php (5.6 for example) and why none of the versions actually update even though the barracuda up script (both stable and head) show the upgrade taking place?

**Comment by EdNett** [comment]
Although I don't do this type of scripting myself, I feel certain that there are errors in the logic of the part of the script:
https://github.com/omega8cc/boa/blob/master/aegir/scripts/AegirUpgrade.sh.txt
in which it checks to see what versions of php are actually installed, and then (instead of allowing an upgrade, as the script should), the error in logic states that only the exact version of php that currently exists can be reinstalled - thus, no upgrades are allowed - neither in stable nor in head.

**Comment by omega8cc** [comment]
Can't reproduce this. Please let us know how to reproduce the problem. Thank you.

**Comment by EdNett** [comment]
Closing this is the cause of the failure to update PHP is that we were running mariadb 10.2, correct?
