### ISSUE TITLE
Access denied for user 'o1'@'localhost'

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1301]
Hi,

I'm trying to upgrade o1 to latest up-head on my VPS with the command:
octopus up-head o1 force

I'm getting this error:
`SQLSTATE[28000] [1045] Access denied for user 'o1'@'localhost' (using password: YES) [10.16 sec, 11.91 MB] `

Also at the end of the setup, I'm getting:
`BOA [01:12:51] ==> UPGRADE B: FATAL ERROR: Required file does not exist:`
`BOA [01:12:51] ==> UPGRADE B: FATAL ERROR:`
`/data/disk/o1/aegir/distro/002/sites/o1.myaegir.mydomain.org/settings.php`
`BOA [01:12:51] ==> UPGRADE B: FATAL ERROR: Aborting AegirSetupB installer NOW!`
`BOA [01:12:51] ==> UPGRADE A: FATAL ERROR: AegirSetupB installer failed`
`BOA [01:12:51] ==> UPGRADE A: FATAL ERROR: Aborting AegirSetupA installer NOW!`
`BOA [01:12:51] ==> FATAL ERROR: AegirSetupA installer failed`
`BOA [01:12:51] ==> FATAL ERROR: Aborting Octopus installer NOW!`

Any advice on how to move on? 
I've already tried:
`barracuda up-head`
Reinstalled PHP with:
`_PHP_FORCE_REINSTALL=YES`
Rebooted my VPS.

Adding a new octopus o2 and updating it to the latest version works! Not sure why I can't update o1.

I've reinstalled everything from start on Debian8 and it seems that I can't update o1 when using octopus command. Getting the same result, the website is locked in aegir, localhost verifies with errors. 
The command used for a fresh install:
`boa in-head public myaegir.mydomain.org myemail@gmail.com o1 mini PHP-7.0`

After more testing, everything works with PHP 5.6. The problem is when PHP 7.0 is in use.

**Comment by omega8cc** [comment]
Could be a temporarily broken HEAD perhaps? Couldn't reproduce this anymore, but remember to see this at some point too. Thanks for the report, though!
