### ISSUE TITLE
How to do a domain redirect via local.settings.php?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1302]
I tried doing a domain redirect via local.settings.php, based on an old [redirect  example](https://github.com/omega8cc/boa/blob/master/docs/old/SSL.txt). I have a site example.com on BOA, with aliases example2.com and www.example2.com. Then I tried a few variations on this code:

```
$request_host = $_SERVER['HTTP_HOST'];
if ($request_host == 'example2.com' || $request_host == 'www.example2.com') {
  header('HTTP/1.1 303 See Other');
  header('Location: https://www.example.com/page';
  exit();
}
```

But they lead to either a blank page (Server Error 500 in JS console), or only the front page working, but navigating to any path on the site also resulting in a blank page (for both of the domains). What would be the right way to do this?

**Comment by omega8cc** [comment]
Not sure why are you trying to be creative with headers and omitting important lines instead of following the working examples? Also, not sure why in `local.settings.php` instead of in Aegir?

**Comment by omega8cc** [comment]
You have PHP coding errors in your example.

Try this instead:

```
$redirection_target = "www.example.com";

if (isset($_SERVER['HTTP_HOST']) &&
    $_SERVER['HTTP_HOST'] != $redirection_target &&
    !$is_backend) {
  header('X-Accel-Expires: 5');
  header("HTTP/1.1 301 Moved Permanently");
  header("Location: http://" . $redirection_target . $_SERVER['REQUEST_URI']);
  header("Connection: close");
  exit;
}
```

or if you want to redirect only selected two aliases to some hardcoded URI"

```
$redirection_target = "www.example.com";
$alias_first = "example2.com";
$alias_second = "www.example2.com";
$target_uri = "/some/uri";

if (isset($_SERVER['HTTP_HOST']) &&
    $_SERVER['HTTP_HOST'] != $redirection_target &&
    !$is_backend) {
  if ($_SERVER['HTTP_HOST'] == $alias_first ||
      $_SERVER['HTTP_HOST'] == $alias_second) {
    header('X-Accel-Expires: 10');
    header("HTTP/1.1 301 Moved Permanently");
    header("Location: http://" . $redirection_target . $target_uri);
    header("Connection: close");
    exit;
  }
}
```

**Comment by ar-jan** [comment]
Thanks! The reason to use local.settings.php was that afaik there's no way to redirect to a specific path using Aegir.
