### ISSUE TITLE
settings.php not write protected for long periods of time

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1303]
On boa up-head latest we are seeing status report messages for many sites that settings.php is not write protected - every day it appears - not all sites on every day, but eventually the problem corrects itself - sometimes taking 6 -8 hours or more. We don't believe this barracuda + octopus is overloaded at all. What do you make of this?

boa info more is here:
https://gist.github.com/EdNett/7ea49399b35a15ddf3c9754b6e700cc0

**Comment by omega8cc** [comment]
BOA doesn't have any code capable of touching or modifying permissions on `settings.php` for hosted sites. The permissions are maintained exclusively by Aegir and are switched to writable only for Aegir itself and only on migrate/clone/verify tasks. BOA doesn't modify them.
