### ISSUE TITLE
Connection Lost on Octopus up-stable

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#1307]
My internet connection lost while I was on an "Octopus up-stable o1 force" update to enable SSL certificate to the Aegir Hostmaster site.

I think there is a question y/n during this update. What can I do to finish the process without problem?

Thank you for your support.

**Comment by angel0d** [comment]
@velpan did you use `screen` ? i know BOA enforces the use of `screen` during install but i am not sure about updates

if you there is a screen session open you can attach to it with `screen -x`

if there are more than 1 screen sessions open you can see the with `screen -ls` and then connect to it with `screen -x session_name`

**Comment by velpan** [comment]
@angek0d thank you for your answer. Yes I know about screen command but this time I forgot to use it! 

Is there something else to do?

**Comment by velpan** [comment]
Is it good solution to cut a copy of the octopus.sh at the point of the question and run the rest of script?

**Comment by velpan** [comment]
I found the solution, I ran the clean up function "up_finish" found inside octopus.sh

up_finish() {
  rm -f /root/BOA.sh*
  rm -f /var/run/boa_run.pid
  rm -f /var/run/boa_wait.pid
  rm -f /var/run/manage_ltd_users.pid
  rm -f /var/run/manage_rvm_users.pid
  rm -f /var/backups/*.sh.cnf*
  rm -f /var/backups/OCTOPUS.sh*
  if [ -e "/opt/local/bin/php" ] || [ -e "/usr/local/bin/php" ]; then
    rm -f /opt/local/bin/php
    rm -f /usr/local/bin/php
  fi
  rm -rf /opt/tmp/*
  echo
  echo OCTOPUS upgrade completed
  echo Bye
  echo
  exit 0
}
