### ISSUE TITLE
Cannot switch php-cli version to 7.0 and hence cannot create varbase composer project.

### ISSUE THREAD

**Issue by aanjaneyam** [omega8cc/boa#1308]
Hi
When I am trying to run 
`composer create-project Vardot/varbase-project:^8.5.1 hsl_varbase_8.5.1_p001 --no-dev --no-interaction`
I get the output as shown on https://gist.github.com/aanjaneyam/499558014a8e4bb375b4175a61ff7065

Here is the output of boa info https://gist.github.com/aanjaneyam/56eb89c7df90267011c74b0a375fa3b4

I have tried recommended steps:
1. manually update PHP version for CLI and FPM in these files: root/.barracuda.cnf/root/.octopususer.octopus.cnf to 7.0.
2. Provision the install of php 7.0 by using _PHP_MULTI_INSTALL="5.6 7.0"
2. Then run the `boa up-stable` , `boa up-stable system`, `octopus up-stable all both ` , `bash /var/xdrago/manage_ltd_users.sh` and `bash /var/xdrago/daily.sh`
3. Add 7.0 in control file ~/static/control/cli.info

I then also manually amended the contents of /data/disk/octopususer/log/cli.txt and /data/disk/octopususer/log/fpm.txt and run `octopus up-stable all force`. However, this seemed to force the version to 5.6 in ~/static/control/cli.info. I had to manually change it back to 7.0.  Thereafter ,the contents of cli.txt, fpm.txt and cli.infor are now showing as 7.0. 

However, the output of php -v is always shows 5.6:
```
lws01:~# php -v
PHP 5.6.33 (cli) (built: Oct  4 2018 01:26:43) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
PHP FPM version is showing fine as 7.0.27

Any hints? Is it possible to use varbase on boa 3.2.2? If yes how to?

**Comment by lexsoft00** [comment]
Hi @aanjaneyam,

I believe your problem is PHP 7.1:
`doctrine/common v2.9.0 requires PHP ^7.1` 

BOA is going to release the PHP 7.1 and PHP 7.2 in the following days which should solve your problem.

Hope this helps.

**Comment by aanjaneyam** [comment]
Hi @lexsoft00

Thanks for the reply. Yeah I know the PHP version problem in BOA/Aegir. I was just wondering if there was a workaround. I too was waiting for the BOA update to include PHP 7.1 and 7.2.  I was wondering when could we expect the next BOA release supporting PHP 7.1 and 7.2.

**Comment by aanjaneyam** [comment]
@lexsoft00

I have spun up a virtualmin server with php 7.2 installed and started development on it. I will commit composer.json, composer.lock, configuration export. I will pull it into BOA and run composer install when BOA is ready for it.

**Comment by lexsoft00** [comment]
@aanjaneyam 

Have you solved this issue?

**Comment by lexsoft00** [comment]
@aanjaneyam

You can create a file named cpn7 with the contents:
`#!/bin/sh
/opt/php70/bin/php -d memory_limit=-1 /usr/local/bin/composer $1 $2`

Then move the file to usr/bin to be accessible from anywhere:
`mv cpn7 /usr/local/bin`
`chmod +x cpn7`

Then update the file /var/xdrago/conf/lshell.conf and find where composer is located then add the cpn7 after
`'composer', 'cpn7',`

You will now have access to cpn7 from o1.ftp

Hope this helps

**Comment by omega8cc** [comment]
Composer will use PHP 7.2 by default starting with BOA-4.0.0

Note that CLI and FPM control files will not be able to control the version Composer is using, because it's installed system wide, so will use the PHP-CLI defined in `.barracuda.cnf` and not per Octopus instance.
