### ISSUE TITLE
Improve SSL certificates auto-renewal procedure reliability

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1309]
I couldn't find the answer in another issue so have to report it.

We've noticed in the last few months, a change in the system that doesn't automatically renew and update the LE ssl certs.  

To manually work around this, you disable encryption then re-enable it per site and the cert gets renewed ok.  Now we're forced to have to check this periodically or face customers contacting to say their sites are down which is obviously not a good look.

Typically on a non-boa system, we would schedule a cronjob like so:
`43 6 * * * certbot renew --post-hook "systemctl reload nginx"`

How is it handled in BOA?
Is there something we can check and verify to ensure this process is actually working as expected?

**Comment by Anoesj** [comment]
Is there any kind of update on this?

**Comment by omega8cc** [comment]
@Anoesj This has been fixed in head on May 22, and hot fix already applied on all instances with default auto-update not disabled. Looks like we forgot to reference this issue in the commit..

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
