### ISSUE TITLE
Backboa not installed

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#1310]
I have a fresh Debian 8 server, with 3.2.2 installed. But backboa does not work, It says: Command not found.
I already installed the server again, with the same result.
Any idea what goes wrong?

**Comment by florisvanwoudenberg** [comment]
I found a workaround:
1. On a server with a working backboa, I did `cat /opt/local/bin/backboa`
2. I copied this to /opt/local/bin/backboa on the new server
3. chmod a+x /opt/local/bin/backboa
4. backboa install

And it's working.

**Comment by iaminawe** [comment]
I can confirm this is no longer in place on a fresh install. Thanks for the workaround @florisvanwoudenberg

**Comment by omega8cc** [comment]
This was intentionally disabled so we could test if automated switching to newer buckets naming convention worked as expected. It required to use the `/root/.backboa.autoupdate` file to enable, now enabled by default. Unfortunately, even if the migration worked fine for all systems we have tested, sometimes the ACL on the S3 side prevents it from creating new bucket automatically, which blocks further backups. We are still working on extended auto-healing, monitoring and notifications to alert the system admin if the automated migration didn't work as expected. Work in progress. But this issue can be closed.
