### ISSUE TITLE
_PERMISSIONS_FIX var gets overriden to YES daily basis

### ISSUE THREAD

**Issue by sluc23** [omega8cc/boa#1311]
I have a dev box with latest BOA 3.2.2 where I don't want permissions to get fixed.
Basically what I'm trying to achieve is to keep ownership of **o1.ftp:users** for custom modules, themes, extensions etc, so it's easy to develop/manipulate them

So I set variable `_PERMISSIONS_FIX=NO` in **.barracuda.cnf**, but daily basis the ownership of files are changed to **o1:www-data**, and the variable is overwritten in the file as **YES**

am I missing any other var/file to set up? Why this var is forced to **YES** daily basis?

PS: I've tried with creating `~/static/control/unlock.info` as well, as described [here](/static/control/unlock.info), but not luck neither

**Comment by omega8cc** [comment]
Ouch, it was a leftover from temporary procedure associated with applying Drupal core security fixes. Thanks for the report!
