### ISSUE TITLE
Changes in php.ini (added extension) seem to be overwritten

### ISSUE THREAD

**Issue by mwprutten** [omega8cc/boa#1313]
We're running PHP 7.0 on a Debian machine with BOA.

We've installed a PHP extension (oauth) that is loaded when we manually add it to the php70.ini file, where the extension_dir is also specified.

It seems that the ini file is overwritten every once in a while however, which means we have to edit the ini file again and restart PHP for the extension to be loaded.

Is there a way to make this change permanent or is there a more appropriate way to do this?

Any hint or feedback is appreciated.

**Comment by lexsoft00** [comment]
Hi @mwprutten 

Check this links:
https://github.com/omega8cc/boa/issues/691
https://github.com/omega8cc/boa/issues/781

I don't think it's possible to have your own settings in the php70.ini unless you rewrite some of BOA scripts.

**Comment by omega8cc** [comment]
In short, you can enable PHP built-in extensions with `.barracuda.cnf` variable:

`_PHP_EXTRA_CONF="" #------------ Allows to add custom options to PHP build`

But for any third party extensions which require php.ini modifications, you would need to open feature request, or even better, propose a patch.
