### ISSUE TITLE
Alert via email about failed Let's Encrypt cert renewal

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#1315]
BOA will normally try to renew expiring LE certificates ahead of time, but if you don't check your Aegir control panel daily to review all Verify tasks statuses, it may go unnoticed until the certificate actually expires, because it couldn't be renewed for some reason, like invalid alias DNS, custom redirect breaking LE verification etc.

**Comment by EdNett** [comment]
This would be very nice!

**Comment by omega8cc** [comment]
This has been implemented.
