### ISSUE TITLE
Upgrade to HEAD failed

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1320]
Hi,

These are my BOA info files (taken after the failed upgrade):

https://gist.github.com/timlie/7ae53e8218f7a6f21f8c47ca8001e440
https://gist.github.com/timlie/13a407e6c84c5d6027cfd1e22ef6e2ae

To make the change from PHP 5.6 to PHP 7.2 I decided to upgrade my BOA server to HEAD.
I changed _PHP_MULTI_INSTALL="7.2 5.6" (it was first _PHP_MULTI_INSTALL="5.3 5.5 5.6").
I also changed MARIADB to _DB_SERIES=10.2 (from 5.5) in the barracuda.cnf and then started the upgrade with:

barracuda up-head

MARIADB was first upgraded but after that upgrade I got errors from building PHP from sources:

BOA [20:59:02] ==> INFO: Building PHP 7.2.14 from sources, please wait...
BOA [20:59:08] ==> INFO: Building PHP 7.2.14 part 1/3
BOA [20:59:14] ==> INFO: Building PHP 7.2.14 part 2/3
BOA [20:59:54] ==> INFO: Building PHP 7.2.14 part 3/3
BOA [20:59:54] ==> INFO: Building PHP 7.2.14 part 2/3 (again)
sed: can't read /var/opt/php-7.2.14/Makefile: No such file or directory
BOA [21:00:34] ==> INFO: Building PHP 7.2.14 part 3/3 (again)
BOA [21:00:34] ==> WARN: Building PHP 7.2.14 failed!
/opt/php56/bin/php: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory

Also for PHP 5.6 I got these errors:

BOA [21:00:34] ==> INFO: Installed PHP version , upgrade required
BOA [21:00:34] ==> INFO: Building PHP 5.6.40 from sources, please wait...
BOA [21:00:39] ==> INFO: Building PHP 5.6.40 part 1/3
BOA [21:00:40] ==> INFO: Building PHP 5.6.40 part 2/3
BOA [21:01:16] ==> INFO: Building PHP 5.6.40 part 3/3
BOA [21:01:16] ==> INFO: Building PHP 5.6.40 part 2/3 (again)
sed: can't read /var/opt/php-5.6.40/Makefile: No such file or directory
BOA [21:01:52] ==> INFO: Building PHP 5.6.40 part 3/3 (again)

I had to put back a snapshot I took before the upgrade. Sadly I copied the wrong upgrade logs from /var/backups before putting back the snapshot.
I'll try again tomorrow and hope to add the logs then to this issue.

Thanks for feedback.

**Comment by omega8cc** [comment]
That happens when you try to use MariaDB 10.2 because it doesn’t work with PHP 7.1+ at the moment, because MariaDB changed libs paths in 10.2, so we are going to more forcefully block attempts to install MariaDB newer than 10.1 and perhaps force downgrade if anyone is using it. You need to use 10.1 to make it work.

**Comment by timlie** [comment]
Allright, thanks!
That explains this commit:
https://github.com/omega8cc/boa/commit/c4ecc03010623f4625454799edd01872ebcbf738#diff-83ea8a0b5dd75c6fef5ed9dd2eabefdf

**Comment by timlie** [comment]
Closing this ticket as with MariaDB 10.1 and PHP 7.2/5.6 upgrade to HEAD was successful.
Thanks!
