### ISSUE TITLE
Is there a way to bulk delete site backups in Aegir

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1324]
I have a load of backups listed in the 'backups' tab of several stes. is there a wa to bulk delete them without having to manually click delete buttons and wait for all tasks to be performed?

**Comment by omega8cc** [comment]
Enable all 3 submodules of Aegir Backup then hit the Enable backup garbage collection checkbox and configure it to your preferences. It's the only way to automate this cleanup.

**Comment by Corvalan** [comment]
Thanks!
