### ISSUE TITLE
todays up-head (shown on screen as boa 4.0.0-prod) fails to install php 7.2

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1327]
todays up-head (shown on screen as boa 4.0.0-prod) fails to install php 7.2

BOA [13:52:56] ==> INFO: Building PHP 7.2.14 part 3/3
BOA [14:00:03] ==> WARN: Building PHP 7.2.14 failed!

I don't know if this is our server specific (since we have never been able to upgrade php past 7.0.24 in the past). Will try to debug and add more info; This is on Jessie from 3.3.0 head with starting php  of 7.0.24.

Boa info more here:  https://gist.github.com/EdNett/30e34a7914a621f2cc00fc5b4b39fa7d

I have verified that the only packages on hold are git and ssh/openssh packages. Can't figure this out at all. ANy help would be kind.

This seems to be related to bug report # 1300

**Comment by EdNett** [comment]
Hello,

When I look in the /etc/apt/* files, I can't find any line (including in subdirectories, of course) that lists the sury repo. Isn't sury still necessary for jessie? That might be the reason why PHP 7.2 install is failing.

**Comment by EdNett** [comment]
Lastly,

I am looking at the sources used for aptitude upgrading (/etc/apt/sources.list), and I see:

## MAIN REPOSITORIES
deb http://httpredir.debian.org/debian/ jessie main contrib non-free
deb-src http://httpredir.debian.org/debian/ jessie main contrib non-free
## MAJOR BUG FIX UPDATES produced after the final release
deb http://httpredir.debian.org/debian/ jessie-updates main contrib non-free
deb-src http://httpredir.debian.org/debian/ jessie-updates main contrib non-free

## DEBIAN SECURITY UPDATES
deb http://security.debian.org/ jessie/updates main contrib non-free
deb-src http://security.debian.org/ jessie/updates main contrib non-free
## DEBIAN PROPOSED UPDATES
deb http://httpredir.debian.org/debian/ jessie-proposed-updates main contrib non-free

If you visit
http://httpredir.debian.org/

on the web, it appears they are telling us to use
deb http://cdn-fastly.deb.debian.org   or
deb https://cdn-fastly.deb.debian.org  
 which is what the sources.list tries to redirect to, but fails with a page not found error.

Could you confirm that the above sources.list is correct? It appears to give an error to me. Also, Do one of those repos contain php other than 7.0? I though sury had to be used.  Thanks for your help.

Ed

**Comment by omega8cc** [comment]
Please read the changelog. It’s explained in the known issues section that you cannot install PHP 7.1+ if you run non default MariaDB 10.2 because of known bugs in MariaDB breaking path to libraries. You need to downgrade MariaDB to 10.1 to be able to install newer PHP versions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
