### ISSUE TITLE
Error when installing D8 sites on boa 4.0.0. HEAD

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1328]
`Error: syntax error, unexpected ':', expecting ';' or '{' in /data/disk/o1/distro/004/lightning-3.2.4-8.6.7/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php, line 50`

```
The external command could not be executed due to an application error. 
Checking DB credentials yielded error: Unable to find a matching SQL Class. Drush cannot find your database connection details.
```

**Comment by omega8cc** [comment]
What’s your PHP version in `~/static/control/cli.info` ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Corvalan** [comment]
I don't have the file cli.info in ~/static/control/

I did install php 5.6 and 7.1 
in barracuda.cnf (/root)
![image](https://user-images.githubusercontent.com/8040352/52199834-7cad8580-2867-11e9-8b06-4c3147996ec0.png)

The errors only happen when installing D8 sites lightning thunder varbase, while their platforms appeared fine after upgrade.

![image](https://user-images.githubusercontent.com/8040352/52199613-e5e0c900-2866-11e9-8ce4-c9e7dc72f761.png)

**Comment by Corvalan** [comment]
I see a corresponding issue here:
https://github.com/symfony/symfony/issues/24035

**Comment by omega8cc** [comment]
Then please read the docs linked in the changelog and define both fpm and cli versions you want to use. You will have to use 7.1 or newer for any D8 site. It’s already a minimum requirement for many D8 distributions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
There’s also a readme file in the control directory.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Corvalan** [comment]
Thank you, this solved my issue.  
Great appreciation and thanks for this amazing system and all your work!
