### ISSUE TITLE
crawlers see 403 on public path

### ISSUE THREAD

**Issue by lhaithaes** [omega8cc/boa#1329]
Hi we are fairly new to BOA and launched our first server around April last year. We are in the stable edition v.BOA-3.2.2

There is a section  on our website that no crawlers seem to be able to reach… We see similar 403 errors on Google, Bing, Moz, SEMRush, Screaming Frog and httpstatus.io, but loads fine in the browser. Its been like this for months (i previously reached out on Gitter), and i have been looking into various possibilities; mainly caching issues. So to double check i've flushed caches, rebuilt permissions, cloned the site; tested that, moved to an upgraded platform, emptied boost cache, purged speedbooster cache, and cleared all the AdvAgg cache.

Yet in Google search console (using URL inspection) we always see the following…

Last crawl: Jan 21, 2019, 8:48:42 AM
Crawled as: Googlebot smartphone
Crawl allowed?: Yes
Page fetch: Failed: Crawl anomaly

*This is via the new interface - the old one labels the response code as 403. With the explanation 

> Googlebot couldn't crawl your URL because your server either requires authentication to access the page, or it is blocking Googlebot from accessing your site.

So testing internally using this command 
`$ curl -L -A "Googlebot/2.1 (+http://www.google.com/bot.html)" mywebsite.com/category/subcategory-a/product*`
 
It returns.... 403 Forbidden, nginx.... as a header response

The website indexes fine apart from this certain section. its a path created by a view using contextual filters and it also affects all child view paths and associated nodes. e.g **category/subcategory-a and category/subcategory-a/product/**

As mentioned this isn't specific to Google, it seems all crawlers show the same behaviour…… A few things to mention - We used your [https://github.com/omega8cc/7x](Drupal 7 fork) and then added the additional modules our site needed via makefile + imported our files directory. Then we used the backup and migrate module to import the data to the Drupal Database. The files directory is actually huge so we took your advice and symlinked the files to avoid issues on upgrades backups and cloning. The only other oddity about this website in BOA is that the cron on the Aegir panel shows it runs every 6 hours yet in the Drupal status page the last run date does not progress.

We have removed all the views caching, and reduced it down to the boost module (css/js aggregation is also on). When i look into the boost cache folder it is creating the cache pages - but just not serving them. What is puzzling us, is that other paths on the contextual view and other product nodes are unaffected. i posed a question on the Boost module issue queue but have not had any bites yet. [https://www.drupal.org/project/boost/issues/3026292](url)

This is why i felt its was something to do with caching. I see that speed booster is also in BOA. But i cant find much info except [https://groups.drupal.org/node/173219](url) and i have tried purging with `$ rm -f -r /var/lib/nginx/speed/*`

I feel its something related to the bots blocking in BOA via all the nginx config files. But omega employees said on Gitter that would be 503 not 403. Im hoping i don't have to go back to Plesk, but i can seem to diagnose the issue and its been months now. Could anyone suggest any potentials causes in BOA?

**Comment by lhaithaes** [comment]
Thank you for the prompt response i will contact via email.

**Comment by omega8cc** [comment]
Thank you for helpful and detailed reporting!

This commit should fix the problem: https://github.com/omega8cc/provision/commit/0777a7e318708d40985059ecf260c43b75a5b650

You can modify it on your server in /data/disk/o1/config/includes/nginx_vhost_common.conf
But I would recommend to upgrade both barracuda and octopus to head.

**Comment by lhaithaes** [comment]
wow I've been hunting high and low. I can't believe i didn't spot that.... we still have so much to learn. Thank you so much for your help
