### ISSUE TITLE
upgrade to head SSL error

### ISSUE THREAD

**Issue by arttus** [omega8cc/boa#1330]
I ran up-head and now when i try and restart nginx I'm getting the following.

Starting Nginx Server...:nginx: [emerg] PEM_read_bio_DHparams("/etc/ssl/private/4096.dhp") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)

Running this on Linode.

**Comment by omega8cc** [comment]
Perhaps your Linode is much slower than any instance we have tested, but please check if this process is still running:

`openssl dhparam -out /etc/ssl/private/4096.dhp 4096`

It's from this code:

```
  if [ ! -e "/etc/ssl/private/4096.dhp" ] && [ -d "/var/xdrago" ]; then
    echo "Generating 4096.dhp -- it may take a very long time..."
    openssl dhparam -out /etc/ssl/private/4096.dhp 4096 > /dev/null 2>&1 &
  fi
```

if it's not running for some reason, run it manually as root:

`openssl dhparam -out /etc/ssl/private/4096.dhp 4096 > /dev/null 2>&1 &`

**Comment by omega8cc** [comment]
Please note that this file should be automatically generated for you already a long time ago, unless your have disabled auto-updates with `_SKYNET_MODE=OFF`

**Comment by arttus** [comment]
Yeah running on the smallest Linode. 

Rerunning "openssl dhparam -out /etc/ssl/private/4096.dhp 4096" was the fix.

Thanks for the quick reply.

**Comment by omega8cc** [comment]
System requirements have changed to satisfy Composer and Solr, so things may not work on the smallest VPS instances.
