### ISSUE TITLE
Please a bit more documentation on installing Drupal on BOA server site outside Aegir

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1332]
I know this scenario is officially not supported by you, but because of the userfulness I post this  as a feature request:  Some support to install a drupal site outside Aegir. 
Motivation:
- Centralising my work on different projects on the same server
- Economise, less overhead of multiple servers
- Performance: making user of BOA's excellent performance

That said, I followed the rules in the FAQ.txt:

> Q: Can I use BOA to host Drupal sites outside of Aegir?
> A: Yes, but it is an unsupported feature, so you need to figure out how to
>    do it properly and you should be prepared that things may explode without
>    any warning after next BOA upgrade. All custom vhosts must reside in the
>    master vhosts directory: /var/aegir/config/server_master/nginx/vhost.d/
>    to avoid GHOST vhost detection and auto-cleanup which runs daily, but only
>    for all Octopus instances in /data/disk directory tree.

Following that advice I uploaded d8 as var/www/test 
and created a vhost in
/var/aegir/config/server_master/nginx/vhost.d/test.mydomain.com  
Which starts with  

> server {
>     server_name test.mydomain.com;
>     root /var/www/test;

I used the following block
https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/

 The result is 502 Bad Gateway

What would be a working code for vhost and include conf file ?

**Comment by bserem** [comment]
With this I got Piwik running under BOA several years ago (still valid I guess):
https://github.com/omega8cc/boa/wiki/Piwik

But if you want to install Drupal, then why not add it as a static platform?

**Comment by omega8cc** [comment]
We don't plan to support nor encourage running Drupal outside of Octopus/Aegir instances, simply because all BOA specific enhancements and supported configuration works only within Octopus specific Nginx and PHP configuration context. You won't be able to leverage BOA power outside of Octopus context, so it really doesn't make any sense to try to provide docs for not working variant.
