### ISSUE TITLE
boa in-stable ...php-all fails

### ISSUE THREAD

**Issue by Amstercad** [omega8cc/boa#1337]
After much testing effort recently, I finally hit upon a successful way to install a stable server:

`boa in-stable public server.example.com user@example.com o1 max php-7.0`

while this will fail:

`boa in-stable public server.example.com user@example.com o1 max php-all`

I must add, my recent effort is all to do with, eventually, upgrading to and installing the latest HEAD. I actually succeeded once, and have been trying to get back there since.

I must continue with my rinse/repeat QA process, but **as I recall**, I believe the next thing I did, prior to `barracuda up-head` was to edit the .barracuda.cnf so all PHP values were 7.2 along with:

`_PHP_MULTI_INSTALL="5.6 7.2"`

**Comment by Amstercad** [comment]
This works: 
`boa in-stable public server.example.com user@example.com o1`

This does too and might be preferable to stable, until the 4.0 BOA release comes out and is stable:
`boa in-3.2 public server.example.com user@example.com o1`

FWIW I haven't been able to upgrade to HEAD reliably yet, and I know to be patient for a release. That's not easy for me though, 4.0 is going to be great.

**Comment by omega8cc** [comment]
We are sorry for the extended delay in publishing the new stable release. We have been blocked by Drupal core security releases, then core regressions, and more new releases, then new PHP releases, and now awaiting for all supported distros to update their core patches etc.

**Comment by omega8cc** [comment]
This has been fixed a long time ago, so closing.
