### ISSUE TITLE
Trying to use drush in /static without success

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1338]
See https://i.imgur.com/BRW2pHF.png
tried to use drush with user o1..nothing happens. And root is not accepted with drush.
Tried even new sudo user without success

What is the prescribed way to use drush in platforms in /static

**Comment by Corvalan** [comment]
Okay I got it...it should be 
sudo -u o1 drush

**Comment by omega8cc** [comment]
You should use either the `o1.ftp` user with its restricted shell, or switch from root to backend user properly if you know you have some valid reason to do so:

`su -s /bin/bash - o1`
