### ISSUE TITLE
Host key verification failed after new HEAD install

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1340]
Debian 9

Steps to duplicate:

1. boa in-head public server.example.com me@dev.com o1
2. success, all verify tasks in master and o1 complete successfully
3. reboot
4. barracuda up-head
5. Unable to verify any platforms with error (master example below, equivalent error for o1 platforms)

```
Could not rsync from '/var/aegir/platforms' to 'aegir@server.example.com:/'	
-
error
/var/aegir/platforms could not be synced to remote server server.example.com. Changes might not be available until this has been done. (error: Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2])
-
error
Could not rsync from '/var/aegir/hostmaster-HEAD' to 'aegir@server.example.com:/'	
-
error
/var/aegir/hostmaster-HEAD could not be synced to remote server server.example.com. Changes might not be available until this has been done. (error: Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2])
-
error
Could not rsync from '/var/aegir/hostmaster-HEAD/sites/master.server.example.com' to 'aegir@server.example.com:/'	
-
error
/var/aegir/hostmaster-HEAD/sites/master.server.example.com could not be synced to remote server server.example.com. Changes might not be available until this has been done. (error: Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.2])
```

**Comment by pricejn2** [comment]
As a quick workaround, I stopped initial BOA install immediately after OpenSSH was compiled and ssh-keygen complete, rebooted, and then restarted install.

**Comment by pricejn2** [comment]
I was missing a hosts file entry. Not sure if it's expected that BOA installer will set that or not. Added the following to /etc/hosts and issue is resolved.

```
9.8.7.6            server.example.com  server
```

**Comment by omega8cc** [comment]
This should never be needed in `/etc/hosts`, so it seems to suggest issues either with remote DNS for this hostname or the local resolver/pdnsd was not installed properly for some reason. Couldn't reproduce this, though. What VPS service was used?

On another note, we should stop installing OpenSSH from sources, unless it's Linux Vserver guest etc.

**Comment by pricejn2** [comment]
This was with an https://www.ssdnodes.com/ SSD KVM. In case it matters, the server domain pattern was `server-12345.example.com`
