### ISSUE TITLE
Old version of config_perms module

### ISSUE THREAD

**Issue by reswild** [omega8cc/boa#1341]
I did some testing after installing your new boa version, and all my Drupal modules are now up to date, except config_perm (part of o_config and defined in line 1683 of /lib/functions/satellite.sh.inc). This is still on version 2.1, which makes Drupal nag me about a security update if I turn on the update module. Is there a reason why you didn't update this module along with all the others?

**Comment by omega8cc** [comment]
Looks like an oversight. Thanks for the heads up! https://github.com/omega8cc/boa/commit/2d3c0bc98563944fef54fad026623edd55421d1e
