### ISSUE TITLE
Ajax 200 parsererror on every Drupal site 

### ISSUE THREAD

**Issue by molaria** [omega8cc/boa#1344]
On an updated VPS Debian _JESSIE_TO_STRETCH=YES with BOA 4 HEAD I got Ajax Parse Error 200 on every installed site, despite Drupal version when I start writing tags on a new article. Tags doesn't autocomplete but works as expected after created post.

In Chrome console I get response as below. 
Anybody else with same behavior?
Fixes?

To examples:
Betelkyrkan.se Drupal 7.64 (in swedish):

Ett AJAX HTTP-fel inträffade
Resultatkod för HTTP: 200
Felsökningsinformation följer.
Sökväg: https://betelkyrkan.se/index.php?q=taxonomy/autocomplete/field_tags
Statustext: parsererror
Svarstext: <?php
/**
* @file
* The PHP page that serves all page requests on a Drupal installation.
*
* The routines here dispatch control to the appropriate handler, which then
* prints the appropriate page.
*
* All Drupal code is released under the GNU General Public License.
* See COPYRIGHT.txt and LICENSE.txt.
*/
/**
* Root directory of Drupal installation.
*/
define('DRUPAL_ROOT', getcwd());
require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
menu_execute_active_handler();

avla.se in Drupal 8.6.7:

js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:4 GET https://avla.se/?q=r net::ERR_TOO_MANY_REDIRECTS
send @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:4
ajax @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:4
sourceData @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:754
_search @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:2035
(anonymous) @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:310
search @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:2035
(anonymous) @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:310
(anonymous) @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:2035
c @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:310
setTimeout (async)
_delay @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:310
_searchTimeout @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:2035
(anonymous) @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:310
input @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:2035
h @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:310
dispatch @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:3
q.handle @ js_pvIondkx44V1ZLtQcOfFIziAZuQAiiQpHvejjqTpBy4.js:3

**Comment by omega8cc** [comment]
When have you run this upgrade? It has been fixed on February 1 or 4 in the modified Provision, so Octopus upgrade to HEAD is required to apply fixes.

**Comment by omega8cc** [comment]
That said, you should not use `_JESSIE_TO_STRETCH` yet. It's not finished yet, with some possible rough edges.

**Comment by molaria** [comment]
Ok. Couldn't wait...
Updated in januari way aHEAD of release of 4.0.0.

I will run Octopus Head with force and see what happens.

**Comment by molaria** [comment]
Worked prefect!
This is on a test server but live on Internet. 
Thanks!

**Comment by omega8cc** [comment]
Thanks for the feedback!
