### ISSUE TITLE
no symbolic link to o_contrib_eight for BOA provided D8 platforms

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1345]
On a clean BOA 4.0 / HEAD install, the three D8 platforms do not have symbolic links to the o_contrib_eight shared modules directory.

**Comment by pricejn2** [comment]
Apologies, I must have done the install after the manage daily cutoff. o_contrib_eight is present after another 24 hours.

**Comment by omega8cc** [comment]
These symlinks should be created on platform verify task, not via running daily maintenance script, so we need to check this.
