### ISSUE TITLE
multi-fpm.info does not make a website use specified php version

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1347]
I have followed the guide here https://learn.omega8.cc/how-to-quickly-switch-php-to-newer-version-330
I have installed php 7.2 and 5.6 on BOA (and observed it being installed in the CLI)
In multi-fpm.info I have put:
`mydomain.com 5.6`

but the site mydomain.com still runs on php 7.2

Where should I start looking to solve this?

**Comment by pricejn2** [comment]
One thing to verify -- are the php-fpm processes for mydomain.com running under o1.72.web? If so, that at least means that multi fpm mode is active. Otherwise I believe they just run under o1.web.

**Comment by omega8cc** [comment]
You can verify versions used by checking files in this directory:

`/data/disk/o1/config/server_master/nginx/post.d`

You should see there files for the default and site specific includes, like

```
fpm_include_site_www.foo.com.inc
if ( $main_site_name = www.foo.com ) {
  set $user_socket "o2.70";
}
```

```
fpm_include_default.inc
set $user_socket "o2.56";
```

**Comment by macmladen** [comment]
I had the same dilemma but the key is to use **site name**, not a domain name so you need to use the name as it is named in **Aegir** or if you use terminal you can check with `drush` under `o1.ftp` user like:

```
root@server $ su o1.ftp
...
o1.ftp:~$ drush sa
@www.mydomain.com
@www.yourdomain.com
@www.hisdomain.com
@www.hersdomain.com
```

...and that exact name should be used in `multi-fpm.info`in exact format as explained. Give a few minutes to **agent** and you'll see your domain listed in `/data/disk/o1/config/server_master/nginx/post.d`

**Comment by macmladen** [comment]
@omega8cc While this may seem obvious, it is also apparent that many people a struggling with this.

I would suggest something like above added to the article and `README.txt` for clarification.

**QUESTION** Could this option, _Select PHP version_ be added to site node in Aegir or at least some CLI command (`drush` or other) to make this easier and more predictable?

**Comment by omega8cc** [comment]
@macmladen 

It's already explained in the `~/static/control/README.txt`

```
  ###
  ### NOTE: Each line in the multi-fpm.info file must start with main site name,
  ### followed by single space, and then the PHP-FPM version to use.
  ###
```

**Comment by omega8cc** [comment]
@macmladen

Managing PHP versions per site should not be done in Aegir interface because it shouldn't rely on working Aegir control panel and database, while being vital to keep the web server up and revert mistakes easily.

Having all sites using non-default PHP versions listed in a single file is the safest and easiest to manage way and was chosen deliberately. The octopus user is not expected to have root access so he can't fix potential issues like breaking control panel by setting incorrect default version if he can't easily revert the mistake by editing simple config files.

**Comment by fotiDim** [comment]
I have the same issue:
- I have run `barracuda up-head php-all`. PHP 8.1 was installed among others.
- I have run `octopus  up-head all force`
- I have added `/data/disk/o1/static/control/multi-fpm.info` with `mysite.com 8.1` which is exactly how it is named in Aegir.

`/data/disk/o1/config/server_master/nginx/post.d` only has `fpm_include_default.inc`

**Comment by omega8cc** [comment]
@fotiDim Try to change ~/static/control/fpm.info to something else, at least for 5 minutes, to force the FPM re-configuration.

**Comment by fotiDim** [comment]
@omega8cc that did the trick. Thank you!
