### ISSUE TITLE
D8 core install profile considerations

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1348]
*This may be more appropriate for a Wiki item

I ran into some strange issues with core profiles when I started using composer for new D8 platform installs instead of a packaged download from d.o. In essence, the Drupal packaging script adds version to the bottom of the info.yml files for each core profile such as the following in `standard.info.yml` for the standard D8 installation profile.

```
# Information added by Drupal.org packaging script on 2019-01-02
version: '8.6.5'
core: '8.x'
project: 'drupal'
datestamp: 1546467643
```

If you install D8 via composer, version is not set and remains as `version: VERSION`. What this means is that you'll get a no valid profile warning in Aegir if you try to migrate from a packaged installation where version is, say 8.6.1, to a composer installation where version is VERSION. New site installs are fine and I expect a VERSION to VERSION migration will work without issue.

Also tried installing with a specific version of D8 and that didn't help either:

```
composer create-project drupal-composer/drupal-project:8.x-dev drupal-8.6.5-dev --stability dev --no-interaction --no-install
cd drupal-8.6.5-dev
composer require --no-update drupal/core:8.6.5
composer require --no-update --dev webflo/drupal-core-require-dev:8.6.5
composer install
```

If you manually set `version:` to the correct version, you can migrate from packaged to composer. Hopefully this is being addressed upstream, but I couldn't find a specific reference to the problem on d.o.

**Comment by pricejn2** [comment]
Simple sed replacement that can be used after the composer install

```
composer create-project drupal-composer/drupal-project:8.x-dev drupal-8.6.5-dev --stability dev --no-interaction --no-install
cd drupal-8.6.5-dev
composer require --no-update drupal/core:8.6.5
composer require --no-update --dev webflo/drupal-core-require-dev:8.6.5
composer install
sed -i 's/version: VERSION/version: 8.6.5/' web/core/profiles/demo_umami/demo_umami.info.yml
sed -i 's/version: VERSION/version: 8.6.5/' web/core/profiles/minimal/minimal.info.yml
sed -i 's/version: VERSION/version: 8.6.5/' web/core/profiles/standard/standard.info.yml
```

**Comment by omega8cc** [comment]
Interesting, but I believe it should be reported in Provision or Hosting Aegir queue on d.o. since it's clearly an upstream issue.

**Comment by pricejn2** [comment]
I've submitted this information to the Provision queue on d.o. -- https://www.drupal.org/project/provision/issues/3035679

**Comment by omega8cc** [comment]
Thank you!

**Comment by omega8cc** [comment]
This has been fixed in Provision, I think: https://github.com/omega8cc/provision/commit/f13545c41ff8d1b7166659b8ec8509c26721151b
