### ISSUE TITLE
[php] disable_functions - get_cfg_var and getmypid used by symfony

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1350]
On a Grav site, I keep seeing PHP warnings in error log such as the following:

`PHP Warning:  get_cfg_var() has been disabled for security reasons in /var/www/grav-onepage.com/vendor/symfony/var-dumper/Dumper/HtmlDumper.php on line 63`

Looks to be regularly used in Symfony Framework (https://github.com/symfony/symfony/search?q=get_cfg_var&unscoped_q=get_cfg_var). And getmypid has one instance. 

Haven't dug in enough to know why these are getting called in my particular site.

**Comment by omega8cc** [comment]
The `get_cfg_var` is used in its composer.phar in a single place, and for debugging only, as a backup option, so pretty irrelevant:

```
$this->debug = $debug;
$this->charset = $charset ?: ini_get('default_charset') ?: 'UTF-8';
$this->fileLinkFormat = $fileLinkFormat ?: ini_get('xdebug.file_link_format') ?: get_cfg_var('xdebug.file_link_format');
```

Couldn't find `getmypid` anywhere in the Grav code, though. Shouldn't be used for anything and is disabled for good reasons.

**Comment by omega8cc** [comment]
I guess it's some non-core module in your site you need to examine.

**Comment by omega8cc** [comment]
Note that it's related to `xdebug` specific vars which shouldn't be checked like this if it's not even installed.

**Comment by pricejn2** [comment]
Thanks for the feedback.

I'm pretty sure this is pops up if 'Full Backtrace Error' is enabled in system.yaml (or admin/config/system at Error Handler > Display Errors) but I'll do some more testing and report back.

**Comment by pricejn2** [comment]
Confirmed -- the PHP warnings were a result of the 'Full Backtrace Error' handler.

**Comment by omega8cc** [comment]
Thanks!

**Comment by justincletus** [comment]
> On a Grav site, I keep seeing PHP warnings in error log such as the following:
> 
> `PHP Warning: get_cfg_var() has been disabled for security reasons in /var/www/grav-onepage.com/vendor/symfony/var-dumper/Dumper/HtmlDumper.php on line 63`
> 
> Looks to be regularly used in Symfony Framework (https://github.com/symfony/symfony/search?q=get_cfg_var&unscoped_q=get_cfg_var). And getmypid has one instance.
> 
> Haven't dug in enough to know why these are getting called in my particular site.

Hi @pricejn2 . This is because of your application enabled dev and debug mode also enabled.
To turn off this error, change your env value to prod and debug_mode=0. 
This is solve my issue.
thanks.
