### ISSUE TITLE
Incorrect redis.pid reference?

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1351]
https://github.com/omega8cc/boa/blob/31ca0005e9ddd4ae51c406bb6998f9a4a7118f7b/aegir/tools/system/graceful.sh#L97

I believe this is invalid and should be updated to `/var/run/redis/redis.pid`

**Comment by omega8cc** [comment]
It's purely cosmetic because `service redis-server stop` should do that anyway, but let's fix it. Thanks!

**Comment by pricejn2** [comment]
Good deal. Thanks!
