### ISSUE TITLE
[docs] Ruby with RVM verbiage change

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1353]
https://github.com/omega8cc/boa/blob/a5f1c4dd6db311cfbb2327e01545f7bcf16c33e0/lib/functions/xtra.sh.inc#L422

This is a minor nitpick -- can this read "Do you want to {install,upgrade} Ruby with RVM ~for root~?" The "for root" portion suggests it's unrelated to the global RVM feature.

**Comment by omega8cc** [comment]
Yes, could be confusing.

**Comment by omega8cc** [comment]
This has been fixed in some commit without referencing this issue..
