### ISSUE TITLE
[rvm][debian 9] missing gems from manage_ltd_users.sh

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1354]
The gems installed with elevated permissions are not installed successfully on a new BOA 4.0 HEAD server running Debian 9.

https://github.com/omega8cc/boa/blob/master/aegir/tools/system/manage_ltd_users.sh#L387

Error log when trying a manual installation of ffi: https://gist.github.com/pricejn2/7be58abe0b773c0e6ddfdffd385beac0

**Comment by omega8cc** [comment]
Thanks for the report!

**Comment by pricejn2** [comment]
I did not have this problem with a fresh Debian 9 install using BOA-4.0.1.

**Comment by omega8cc** [comment]
Thanks for the confirmation. Still, for some reason London based VPS instances experienced problems not experienced elsewhere, so we didn't catch it before. Now fixed too.
