### ISSUE TITLE
Solr 7 Connection

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1362]
I am struggling to connect to any of the new Solr 7 cores provisioned since updating to BOA 4.0

After updating the boa_site_control.ini file I see the solr.php file appear about 10 mins later with updated credentials that look like this

Your SOLR core access details for domain.test.net site are as follows:
  Solr version .....: 7.6.0
  Solr host ........: 127.0.0.1
  Solr port ........: 9077
  Solr path ........: /solr/oct.o1.domain.test.net

I update the details in the Search API settings page but the server cannot seem to connect.
This is the string its trying to use  http://127.0.0.1:9077/solr/oct.o1.domain.test.net

I am using Drupal 7 and Search Api Solr 7.x-1.14

Also where would the new solr cores be stored? The old ones were at /opt/solr4 but I dont seen any more recent folder there.

Thanks for any assistance you can give and thanks for another great BOA release.

**Comment by omega8cc** [comment]
There is a bug affecting instances running BOA-3.2.2 before apparently.

**Comment by 7o7o** [comment]
I am also having some issues with BOA 4.0 (head version) and Drupal 8. I managed to make it work for a while but today search was broken and I can't get it back to work. And when I try to get to the Apache Solr admin interface it hangs up and I can't access the server from my IP for a couple of minutes.

iaminawe solr cores are created in the folder /var/solr7/data/ 

I did the same steps and also uploaded the config files from the search api solr module to the sites/example.com/files/solr folder, as described in the documentation for the search_api_solr-8.x-2.x module. Solr server can be reached but the cores can't be accessed.

If it's necesary I can open another issue so I don't hijack this one, I just thought it could be related. If more information is needed about the error or the steps taken just let me know. Thanks.

**Comment by pricejn2** [comment]
@iaminawe FWIW, I have been running Solr 7 and and Search Api Solr 7.x-1.14 with Drupal 7 on BOA 4.0 successfully.

**Comment by omega8cc** [comment]
It works on newly installed instances but not always on upgraded systems. I will quote the comment from Gitter: “Unfortunately Solr 4 cores are provisioned only for apachesolr module as a legacy option for D6 and D7 still using it. That said, we have identified the problem with D7 and Solr 7 on instances upgraded from BOA-3.2.2 and it’s not related to the complex setup on D8. Instead it’s trivial omission. Because new BOA was not tagged yet, existing on the server template configuration wasn’t updated either, so it’s trying to use the old Solr 4 compatible configuration files with Solr 7. Should be easy to fix later today.”

**Comment by omega8cc** [comment]
Drupal 8 is a different story though.

**Comment by iaminawe** [comment]
@omega8cc I was wondering about the status of this. I recently ran upgrades and have just checked and I can still not access the Solr 7 Cores at the details provided - thanks.

**Comment by omega8cc** [comment]
We are trying to reproduce the problem. It's not clear why the issue happens rarely and quite randomly for some sites.

**Comment by omega8cc** [comment]
Be believe that we have found the culprit in https://github.com/omega8cc/boa/commit/b30d74d0d5ccf330ed9818c90e0ed4b819dbb7c5 and it's already enabled for anyone on BOA-4.0.1 even if you have already upgraded before this commit, because it's a part of the hot-fixes/updates to system scripts, which happen every 8 minutes.

**Comment by omega8cc** [comment]
On another note, please make sure that especially with Drupal 8 and `search_api_solr` you haven't enabled `solr_custom_config = YES` in the INI file, because it will block any auto-updates to the affected Solr core.

**Comment by iaminawe** [comment]
Unfortunately this is still not working for me - I have confirmed that the search api solr is not using solr_custom_config and unfortunately I am still not able to connect to a new solr 7 server using the details in solr.php. Not sure where to go next with this.

**Comment by omega8cc** [comment]
@iaminawe It's pretty hard to debug without access to problematic system/site and the script logs, but we still suspect that there could be an edge case situations, at least we do receive rare but similar reports about Solr core suddenly not available. Can you try to restart the Solr server as root with `service solr7 restart` and see if that makes any difference?

**Comment by asztalos-zolee** [comment]
same problem here :( Drupal8, boa_site_control.ini settings: solr_integration_module = search_api_solr solr_update_config = NO solr_custom_config = NO
clean boa 4.0.0 upgraded to 4.0.1
logs from slor admin:
```
19/06/2019, 13:55:13
WARN true
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../dist filtered by solr-dataimporthandler-.*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../dist
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../contrib/extraction/lib filtered by .*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../contrib/extraction/lib
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../dist filtered by solr-cell-\d.*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../dist
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../contrib/langid/lib filtered by .*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../contrib/langid/lib
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../dist filtered by solr-langid-\d.*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../dist
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../contrib/velocity/lib filtered by .*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../contrib/velocity/lib
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../dist filtered by solr-velocity-\d.*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../dist
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../contrib/analysis-extras/lib filtered by .*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../contrib/analysis-extras/lib
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../contrib/analysis-extras/lucene-libs filtered by .*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../contrib/analysis-extras/lucene-libs
19/06/2019, 13:55:13
WARN false
x:oct.o1.domain.eu
SolrConfig
Couldn't add files from /var/solr7/data/oct.o1.domain.eu/../../../dist filtered by solr-analysis-extras-\d.*\.jar to classpath: /var/solr7/data/oct.o1.domain.eu/../../../dist
19/06/2019, 13:55:17
ERROR true
x:oct.o1.domain.eu
RequestHandlerBase
org.apache.solr.common.SolrException: Error CREATEing SolrCore 'oct.o1.domain.eu': Unable to create core [oct.o1.domain.eu] Caused by: solr.ICUCollationField
org.apache.solr.common.SolrException: Error CREATEing SolrCore 'oct.o1.domain.eu': Unable to create core [oct.o1.domain.eu] Caused by: solr.ICUCollationField
```

**Comment by iaminawe** [comment]
When I try to run service solr7 restart as root I get the following error.

`solr7: unrecognized service`

**Comment by omega8cc** [comment]
Hmm, have you added `SR7` to `_XTRAS_LIST` in the `/root/.barracuda.cnf` file before running upgrade?

```
### SR4 --- Apache Solr 4 with Jetty 9
### SR7 --- Apache Solr 7

```

**Comment by omega8cc** [comment]
Please note that all recent fixes are still in BOA head, not in 4.0.1, so if you still experience any issues, please consider upgrading Barracuda to HEAD. We run HEAD in production on all servers, except clusters, which have usually custom upgrade schedule due to setup/configuration differences.

**Comment by iaminawe** [comment]
I had not! Not sure how I missed that step :( 
I am busy running upgrades now after adding it and will report back here.

**Comment by omega8cc** [comment]
I think we have listed `SR7` everywhere except in the `docs/SOLR.txt` ouch.. -- just fixed! https://github.com/omega8cc/boa/commit/e0a663a7b75abb02ecba71007c3314d4c4361b8b

**Comment by omega8cc** [comment]
We should add extra checks and reporting to avoid this kind of confusion. We sometimes miss obvious things because we enable them by default on our servers :-/

**Comment by iaminawe** [comment]
It works correctly now - thank you so much for your assistance. From my perspective this issue can be closed now.
