### ISSUE TITLE
Trouble importing DB into website

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1366]
Hi,

I'm having issues importing DB into the website. Like making a backup and then reimporting into in a blank no tables DB.
The error:
`ERROR 1709 (HY000) at line 622: Index column size too large. The maximum column size is 767 bytes.`

To solve this issue I've added this into the MySQL config file.
`innodb_default_row_format=dynamic`
in /etc/mysql/my.cnf

```
.....
innodb_buffer_pool_dump_at_shutdown = 1
innodb_buffer_pool_load_at_startup = 1
innodb_buffer_pool_dump_pct = 100
innodb_stats_on_metadata = OFF
innodb_adaptive_hash_index = 0
innodb_default_row_format = dynamic
```

Can we have this added by default?

**Comment by omega8cc** [comment]
What is your MariaDB version?

**Comment by omega8cc** [comment]
Anyway, with our other default settings we can safely add this variable. Thanks for the suggestion.
