### ISSUE TITLE
Commerce Cart not updating on latest BOA

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1367]
Hi, 

I've installed BOA into a new AWS EC-2 server and I'm having a hard time trying to figure out why anonymous users cannot add orders to cart.

Thanks.

**Comment by lexsoft00** [comment]
It could be a code/composer related issue or a DNS problem. Still investigating. 
I have a feeling it's related to composer and packages.

**Comment by lexsoft00** [comment]
It was related to a Drupal 8 Core problem, I think it had something to do with a vendor library. After updating to the 8.6.14 the problem was gone.

**Comment by omega8cc** [comment]
Thanks for the update.
