### ISSUE TITLE
Solr dir is not defined in in setup_solr()

### ISSUE THREAD

**Issue by zanami** [omega8cc/boa#1370]
Looks like _SOLR_DIR is used before it's defined later in setup_solr()
which leads to really nasty behaviour

https://github.com/omega8cc/boa/blob/master/aegir/tools/system/manage_solr_config.sh#L308

I'd swap **Support for solr_integration_module directive** and  **Support for solr_custom_config directive** blocks

**Comment by omega8cc** [comment]
Good point, thanks!

**Comment by omega8cc** [comment]
Looks like this has been fixed.
