### ISSUE TITLE
curl couldn't resolve getcomposer.org during boa head install

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1372]
curl: (6) Could not resolve host: getcomposer.org
mv: cannot stat 'composer.phar': No such file or directory
So there is no /root/.composer directory at all in this new in-head on stretch install.

**Comment by aanjaneyam** [comment]
In my case the new in-head install is fully broken. Please https://github.com/omega8cc/boa/issues/1369. Which VPS provider are you using? What other errors are you getting? May be we should continue in the other issue (linked above) to keep the discussion in one place and seek attention of the The Barracuda Team.

**Comment by EdNett** [comment]
I am closing this because we have jsut successfully installed head on a new server with none of these issues. Perhaps I shouldn't have purged bind9 for the original provisioned minimal server - since boa installs it anyways.
