### ISSUE TITLE
Info required to install new BOA test server - what services need to be purged before install, please?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1373]
Hello, We are provisioned with a stretch server with the following services:

- I have already removed:
 iptables
bind9
dbus
openntpd
and cron (and of course aptitude insisted on substituting a cron substitute.) 

It seems to me that none of the remaining services can be safely removed. Can you adveise what to remove to get BOA to install. The error message is :

ERROR: BOA requires minimal, supported OS, with no services installed
ERROR: The only acceptable exceptions are: sshd and mail servers
Bye

root@server1:~# service --status-all
 [ - ]  console-setup.sh
 [ - ]  hwclock.sh
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ + ]  networking
 [ + ]  procps
 [ - ]  screen-cleanup
 [ + ]  ssh
 [ + ]  udev
root@server1:~#

Thank you.

**Comment by angel0d** [comment]
Check If `/etc/apache2` exists and try to remove `javascript-common`

**Comment by EdNett** [comment]
Thanks, that seemed to do it!
