### ISSUE TITLE
Install text/prompt fixes

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1375]
Just providing you guys with some grammar fixes if you want them.

> BOA [20:26:36] ==> NOTE: Please reboot and run barracuda upgrade
> BOA [20:26:36] ==> NOTE: when boa will complete initial installation
> BOA [20:26:36] ==> NOTE: to cleanly remove not used systemd packages!

BOA [20:26:36] ==> NOTE: Please reboot and run barracuda upgrade
BOA [20:26:36] ==> NOTE: **after** boa **completes** initial installation
BOA [20:26:36] ==> NOTE: **in order** to remove **unused** systemd packages!

Note, I'm only doing this because I know English isn't your native language. I don't want to be rude. :)

**Comment by omega8cc** [comment]
Thanks, we appreciate corrections! Clearly, we no longer read the status lines written years ago :-)
