### ISSUE TITLE
[xboa] migrate Solr 7 data

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1376]
The xboa migration tool does not currently handle solr 7.

Perhaps something like this is enough (https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/xboa#L780)
```
    if [ -e "/var/solr7/data" ]; then
      rsync -aEAXq ${ieni} -e ssh /var/solr7/data root@${tgt}:/var/solr7/
      echo "INFO: ${cmd} for ${oct} /var/solr7/data complete"
    fi
```

**Comment by omega8cc** [comment]
Good point, we have overlooked this apparently. Thank you.
