### ISSUE TITLE
master instance not running cron, verification errors due to missing /var/aegir/drush/drush.php

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1378]
First of all thank you for the info and much-improved screen notices about the mysql and/or apache2 empty directories that can stop a boa install.

We have just ran the initial install then a few barracuda up-stables after a reboot, and the only problems we have are similar to ones we had before involving the master instance. The initial warnings were for failure of nginx to restart and gave the yellow warning error messages for everything: localhost, server, hostmaster (twice) and master instance (4 times).

Then we ran barracuda up-stable again(modifying the barracuda.cnf file to add php7.3 to the original 7.2 install, and add headers, nxasi strong passwords, sr7, BDD, FMG and IMG), and everything but the original hostmaster verified green (localhost, server, Aegir hostmaster 001 and the master instance), then 10 min later both the
hostmaster and the Aegir hostmaster 001 did not verify - red error:

The command could not be executed successfully (returned: Could not open input file: /var/aegir/drush/drush.php , code: 1)

Then we rebooted and ran barracuda up-stable again, and localhost, master, Aegir hostmaster 002 and server verified green, but then a few min later, Aegir hostmaster 002 and Aegir hostmaster 001 and hostmaster did not verify. red error: - same error.

It appears that the master instance isn't running cron - the same problem we had before. (Issue 1371).

Boa info more is here: https://gist.github.com/EdNett/726f6a5431afcd2e9af425b26ef12709

Hope this helps.
Other than this, everything seems to be working fine. Thank you for the upgrade!
Ed

**Comment by EdNett** [comment]
We just installed boa stable on another test server and the /var/aegir/drush/drush.php file is  not there (there is a /var/aegir/drush/drushrc.php file in that directory) and we got the same red no-verify errors on the master barracuda instance, the hostmaster and a stuck task, with no cron running on the master barracuda site.

**Comment by omega8cc** [comment]
Wow. That is pretty serious bug. Thanks for reporting! Will be fixed in 15 minutes for everyone automatically. Then running `barracuda up-stable` again will be enough to fix Drush on the master instance.
