### ISSUE TITLE
Upgrade wkhtmltopdf to 0.12.5 (Debian stretch)

### ISSUE THREAD

**Issue by GValFr35** [omega8cc/boa#1379]
There is an issue on Debian Stretch with wkhtmltopdf 0.12.4 related to SSL.
[QSslSocket: cannot resolve SSLv3_client_method / SSLv3_server_method](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001)

Images or css files (https links) are broken, and aren't not included in pdf.  
(tested on BOA 4.0.0 - "head")

Could you upgrade to 0.12.5 ?
Thanks you !

**Comment by timlie** [comment]
I can confirm this issue to. Also using BOA 4.0.0 HEAD.

**Comment by omega8cc** [comment]
Will be included in the upcoming BOA-4.0.2
