### ISSUE TITLE
Mariadb 10.2 to 10.1 downgrade to obtain php updates

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1380]
We had a boa server that we had mariadb 10.2 on, and php 7.0 was stuck at 7.0.24 and no higher version of php, including php7.2 and 7.3 would install - by design.

So to downgrade mariadb from 10.2 to 10.1, we did the following which seems to have worked for us. I would love to know if there is a better way. Others might need to downgrade, too, so I'm posting also for them (no guarantee), but also to have feedback on better ways of doing this.

First we ran a barracuda up-stable simply to disable binary logging before the downgrade (I don't know if this was necessary).
So I set _DB_BINARY_LOG=NO in the /root/.barracuda.cnf file and ran barracuda up-stable.

At the same time I downloaded all sites' sql backups from /data/disk/arch/sql/ 
as well as aegir full site backups in /data/disk/o1/backups

Then I did the following:

(change mariadb apt sources from 10.2 to 10.1)
vim /etc/apt/sources.list.d/mariadb.list

(run aptitude update)
aptitude update

(backup the entire mysql database)
mysqldump -u root --add-drop-table --routines --events --all-databases --force > data-for-downgrade.sql

(apply settings for mysql downgrade - this from:  https://jira.mariadb.org/browse/MDEV-13562 )
mysql -u root --execute="SET GLOBAL innodb_fast_shutdown=0"
mysql -u root --execute="SET GLOBAL innodb_purge_rseg_truncate_frequency=1"

(stop the mysql server)
service mysql stop

(Create a backup from your MySQL lib - If something goes wrong and you have to reinstall MariaDB 10.2.)
mv /var/lib/mysql{,.bak}

(Install MariaDB 10.1 and purge 10.2 - do not change the mariadb root password at prompt )
apt-get install --purge mariadb-client-10.2- mariadb-client-core-10.2- mariadb-server-10.2- mariadb-server-core-10.2- mariadb-client-10.1 mariadb-client-core-10.1 mariadb-server-10.1 mariadb-server-core-10.1 libmariadbclient18 libjemalloc1 libmysqlclient18

(Restore backup)
mysql -u root --force < data-for-downgrade.sql

Then modify the /root/.barracuda.cnf file making sure it calls for mariadb 10.1: _DB_SERIES=10.1 
and add _SQL_FORCE_REINSTALL=YES to it. At this point we added back
_DB_BINARY_LOG=YES

Then run the barracuda up-stable in a screen session.

We then ran:
 bash /var/xdrago/manage_ltd_users.sh
and
bash /var/xdrago/daily.sh

The sites on the server go down for some time when restoring the mariadb db, and once again when nginx is stopped doing the mariadb rebuild during the final barracuda up-stable. Can anyone provide a safe, better way with less downtime? And is disabling the binary log really necessary?

Thanks

Ed

**Comment by omega8cc** [comment]
BOA HEAD now supports downgrade from MariaDB 10.2 to 10.1, however it was tested only with hostmaster and no sites installed (and it worked despite very clear error message), so please don't try it on any live system.

`May  9 02:19:22 v3 mariadb-server-10.1.postinst[14391]: InnoDB: A downgrade from MariaDB 10.2.2 or later is not supported.`

**But the good news is that now you can install all PHP versions and use them with MariaDB 10.2 exactly as with 10.1, so there is no need to downgrade the DB server to be able to run latest PHP versions.**

**Comment by omega8cc** [comment]
You can even upgrade to MariaDB 10.3 and run it with PHP 7.3

![Status report | Octopus System powered by Barracuda](https://user-images.githubusercontent.com/128547/57424786-31659300-7219-11e9-8922-8fb0964ffa84.jpg)
