### ISSUE TITLE
Connection refused after system upgrade

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1381]
Interesting, using stable 4.0.1 since last week or so. Ran `barracuda up-stable system` then reboot because kernel was updated (using Debian 9.7). Now connections are refused. Upgrated to head (4.0.2-dev) and still all connections are refused:

```
curl MY_SERVER_IP -v
* Rebuilt URL to: MY_SERVER_IP/
*   Trying MY_SERVER_IP...
* TCP_NODELAY set
* connect to MY_SERVER_IP port 80 failed: Connection refused
* Failed to connect to MY_SERVER_IP port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to MY_SERVER_IP port 80: Connection refused
```

**Comment by yaazkal** [comment]
Looks like nginx is failing:

```
# service nginx restart
[FAIL] Stopping Nginx Server...: failed!
[....] Starting Nginx Server...:nginx: [emerg] PEM_read_bio_DHparams("/etc/ssl/private/4096.dhp") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
. ok
```

**Comment by omega8cc** [comment]
This shouldn't happen and we have never seen this on any system with default updates enabled, unless you have disabled them?

Try to run:

`openssl dhparam -out /etc/ssl/private/4096.dhp 4096 > /dev/null 2>&1 &`

**Comment by omega8cc** [comment]
This file is generated on install, then checked and generated if needed by script running every 8 minutes, so it's quite impossible it wasn't already generated.

**Comment by yaazkal** [comment]
Well, as far as I know, I've not disabled anything.

6th time I try and no luck:

```
chronos:~# openssl dhparam -out /etc/ssl/private/4096.dhp 4096 > /dev/null 2>&1 &
[6] 30279
chronos:~# service nginx restart
[FAIL] Stopping Nginx Server...: failed!
Killed
chronos:~# nginx -t
nginx: [emerg] PEM_read_bio_DHparams("/etc/ssl/private/4096.dhp") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by omega8cc** [comment]
This file takes a long time to generate... check the status with `ps aux`

**Comment by yaazkal** [comment]
ok, I'll kill them all (that sounds scary) and retry wainting just for one :)

Thanks for the support and responses, I'll update as soon as I can.

**Comment by yaazkal** [comment]
@omega8cc It's working now. Thanks a lot !

**Comment by omega8cc** [comment]
Thanks for the update!
