### ISSUE TITLE
Reset password is not working - how to solve?

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1383]
Since about a week suddenly the BOA server does not send out password resets any more. Other server notifications work as normal and send out notifications like daily backups, but I can't get into a site as admin any more.  Password reset via the website itself is not received either.

**Comment by omega8cc** [comment]
Have you checked `/var/log/mail.log` ?

**Comment by omega8cc** [comment]
Closing because of lack of feedback.
