### ISSUE TITLE
Don't verify sites where encryption is no longer enabled

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1384]
Can we add a check of the Octopus database to validate that SSL is enabled? -- https://github.com/omega8cc/boa/blob/master/aegir/tools/system/daily.sh#L2404

Thinking something like this, but have not had the chance to sufficiently test.

```
check_update_le_ssl() {
  _SSL_ENABLED=$(run_drush8_hmr_cmd \
        "sqlq \"SELECT n.title FROM hosting_site s \
        INNER JOIN hosting_ssl_site le ON s.nid = le.nid \
        INNER JOIN node n ON s.nid = n.nid \
        WHERE s.status > 0 AND le.ssl_enabled > 0 \" 2>&1)
  _SSL_TEST=$(echo "${_SSL_ENABLED}" | grep "${Dom}")
  if [[ "$_SSL_TEST" =~ "${Dom}" ]]; then
    if [ ! -e "${User}/static/control/noverify.info" ]; then
      if [ -e "${User}/tools/le/certs/${Dom}/fullchain.pem" ]; then
        echo "Running LE cert check via Verify task for ${Dom}"
        run_drush8_hmr_cmd "hosting-task @${Dom} verify --force"
        echo ${_MOMENT} >> /var/xdrago/log/le/${Dom}
        sleep 3
      fi
    fi
  fi
} 
```

**Comment by omega8cc** [comment]
Thank you for the suggestion. We have implemented changes which will check daily and update if needed all active SSL certificates without running site verify task at all, so it will no longer cause any unexpected problems. It will also check if the encryption is enabled by examining the site's vhost, not the hostmaster database. The change has been already applied to all BOA instances running 4.0.0 or newer and with auto-updates (default) active.
