### ISSUE TITLE
Add support for Ads.txt

### ISSUE THREAD

**Issue by TheRuslan** [omega8cc/boa#1385]
Please add support for ads.txt https://www.drupal.org/project/adstxt

This module virtually generates txt file with path /ads.txt (like /robots.txt), but in BOA env this path is unavailable.

Thanks in advance!

**Comment by omega8cc** [comment]
Thanks for the suggestion. We will look into this.

**Comment by zanami** [comment]
For those who ended up on this page looking for solutions...

The module isn't supported, but there's an undocumented solution already in /config/includes/nginx_vhost_common.conf

**You have to put ads.txt in /files (/sites/whatever.com/files)**

```
###
### Support for static ads.txt file in the sites/domain/files directory.
###
location = /ads.txt {
  access_log    off;
  log_not_found off;
  add_header Access-Control-Allow-Origin *;
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  try_files /sites/$main_site_name/files/$host.ads.txt /sites/$main_site_name/files/ads.txt $uri =404;
}
```

**Comment by omega8cc** [comment]
Fixed in https://github.com/omega8cc/provision/commit/f16f9c59d00b5e8678557b5175e61ef7ab0300c0
