### ISSUE TITLE
Installing 2 Solr versions at the same time?

### ISSUE THREAD

**Issue by VangelisP** [omega8cc/boa#1387]
I was wondering (and before breaking everything in my environment), is it possible to have 2 different versions of Solr installed ?

Example: `_XTRAS_LIST="ADM CSF FTP CGP CSS SR4 SR7"` 

Or one version will override the other ?

Thanks!

**Comment by omega8cc** [comment]
You can have both installed, they use separate Java versions, ports and directories etc. Solr 4 is run via Jetty server while Solr 7 natively. We use them both, so different core versions and integration modules are covered.

**Comment by VangelisP** [comment]
Many thanks! Closing this issue
