### ISSUE TITLE
Script @composer drupal-scaffold handling the post-install-cmd event returned with error code 1

### ISSUE THREAD

**Issue by aanjaneyam** [omega8cc/boa#1388]
I am trying to install a a custom varbase platform in static directory using composer. However when I run the composer create command it runs into drupal-scaffold error like below:
`composer create-project Vardot/varbase-project cheekucreationsdev-p001 --no-dev --no-interaction`

Last few lines of terminal output:
```
- Installing drupal/varbase_blog (6.2.0): Loading from cache
  - Installing drupal/varbase_auth (6.4.0): Loading from cache
  - Installing vardot/varbase (8.6.11): Loading from cache
  - Installing webflo/drupal-finder (1.1.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
Generating optimized autoload files
> Varbase\composer\ScriptHandler::createRequiredFiles
Create a sites/default/files directory with chmod 0777
> Varbase\composer\ScriptHandler::removeGitDirectories
Script @composer drupal-scaffold handling the post-install-cmd event returned with error code 1
```
I asked to varbase people and they said that it may be BOA specific. What could be wrong as it is happening all the time.

I found another thing. Manually running `composer drupal-scaffold` after the `composer create-project Vardot/varbase-project PROJECT_DIR_NAME --no-dev --no-interaction` completes downloads all the files. Then why is it not running with `composer create-project ....` (edited) 
It is BOA specific or somthing in varbase script.

**Comment by omega8cc** [comment]
Not sure, but we haven’t tested it with limited shell only system user, but it always worked flawlessly, although we only ever used the dev variant: 
```
composer create-project vardot/varbase-project:8.6.x-dev varbase-8.6.9-8.7.1 --no-dev --no-interaction
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aanjaneyam** [comment]
Should I run it as root and chown and chmod to o1.ftp. OR do you thing that switch to o1.ftp with bash shell would help. `su -s /bin/bash - o1.ftp`. Also it it possible to run bash commands/scripts as o1,ftp without shell restriction.

**Comment by omega8cc** [comment]
Never try to run Composer nor Drush as root. I think we had the same problem running via full bash user and only their dev repo worked. Try the command above as o1.ftp it should work just fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aanjaneyam** [comment]
@omega8cc I did not get your last comment regarding running as o1.ftp. I am running the command as o1.ftp (su - o1.ftp) witin the default limited shell. Running with bash shell, as described above, was an option I was thinking of testing as the normal o1.ftp was not working. You mean to say that I should use `su -s /bin/bash - o1.ftp` and not `su - o1.ftp`

**Comment by omega8cc** [comment]
The shell used shouldn’t matter. The key is to use ‘vardot/varbase-project:8.6.x-dev’

**Comment by aanjaneyam** [comment]
It is neither working as `su - o1.ftp` nor as `su -s bin/bash - o1.ftp`. what could be wrong. Is running with o1 an option. What would need to be done after running as o1?

**Comment by aanjaneyam** [comment]
OK I see. Using `vardot/varbase-project:8.6.x-dev` works. So is it a problem with Varbase? Some varbase repo are reconfigured? What could be the reportable problem on varbase issue queue?

**Comment by omega8cc** [comment]
It seems to be a problem with their project, nothing BOA specific because it fails even with standard bash shell while their dev branch works just fine. I’m going to close this as not BOA specific.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Perhaps they don’t sync their dev repo with main and never check the main? No idea.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aanjaneyam** [comment]
Finally may I ask if it is possible to run the bundled varbase bash script like `create-new-vartheme-bs4.sh` or `./bin/update-varbase.sh` as user o1.ftp by switching to o1.ftp by using command `su -s bin/bash - o1.ftp`

**Comment by omega8cc** [comment]
Not possible once you verify the platform in Aegir because the Aegir `o1` user takes it over. You should build new codebase from scratch and use Migrate task instead of updating anything in place, by definition. It would be again Aegir best practices and would actually negate all benefits of using Aegir in your workflow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Besides, we have tried the update script and it failed. Building from scratch was faster than debugging.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aanjaneyam** [comment]
@omega8cc Thanks for the reply. I understand that the update-varbase script is a problem but at least we could run create-new-vartheme-bs4.sh (to easily create a subtheme) before creating/adding the code as platform and take it on from there following aegir principles.

**Comment by omega8cc** [comment]
You can of course use bash scripts with any account via bash shell, just not with limited shell.

Please note that building your codebases is beyond BOA scope, since BOA provides only tools (Drush, Composer, Git) and Aegir in general is designed to manage Drupal sites lifecycle, not codebases lifecycle. It's a matter of developer's preferences.
