### ISSUE TITLE
octopus not installing new instances

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1391]
On a new boa stable 4.0.1, we cannot install a new octopus instance  (we use "f3" instead of "o3" for the name of the octopus instance to install) - it lookis like the f3:user is invalid - that is to say that the user isn't added. If I look in /etc/passwd, I find an entry for f3.ftp, but not for f3, nor for f3.web (like there are for the f2 instance).

see the log:
https://gist.github.com/EdNett/6c640b6b6f3fdb25e26fb37958df0302

boa info more is here:
https://gist.github.com/EdNett/d742e15babc4224089f3019353456018

Best,

Ed

**Comment by omega8cc** [comment]
This can't be reproduced on any supported VPS on DigitalOcean or Linode etc.

**Comment by aanjaneyam** [comment]
Look like I have been able to reproduce this.
```

**Comment by aanjaneyam** [comment]
I am using BOA HEAD install.

**Comment by omega8cc** [comment]
@aanjaneyam I don't think it's related. Please open separate issue. Thank you. We couldn't reproduce this with stable nor head, though, both tested on Digital Ocean and Linode.

**Comment by aanjaneyam** [comment]
OK it has now proceeded after about 20 minutes. What could have been wrong? This has happened for the first time. I don't know if we need an issue if the install proceeds and finishes successfully.

**Comment by omega8cc** [comment]
You should inspect the processes running via `ps axf`, check the install logs in `/data/disk/o1/log/install.log` and PHP errors to determine the culprit.

**Comment by EdNett** [comment]
I am closing this issue because we found old remnants of a failed install from early may using the same octopus username. Removing all references to "f3" allowed the install of a new octopus instance to proceed smoothly. We had to use the chattr -i command and -a commands to remove soem ofd user material that was probably blocking the install.  Sorry about this.
