### ISSUE TITLE
Zombie hostmaster platform come back from dead after daily cron

### ISSUE THREAD

**Issue by cvining** [omega8cc/boa#1393]
My octopus o1.mydomain panel shows 12 Aegir Hostmaster platforms. I've deleted the old platforms several times (and the Task is marked 'successful', but they reappear each day, and they also reappear when I run

$ bash /var/xdrago/daily.sh

All indicate Platform Path is:

/data/disk/o1/aegir/distro/xxx
where the only two most recent versions actually reside. I don't delete either the current or immeadiate past Hostmaster platform.

The oldest zombie platform has been lingering around for 3 years. They don't seem to harm anything, so this isn't any sort of emergency.  But I would like to delete them off once and for all!

Any thoughts? Thanks for all the fish! It's been a great system for me!

[Boa info](https://gist.github.com/cvining/3c090bf1b023223307b32be9858ff23f)

**Comment by omega8cc** [comment]
It's a known problem. Aegir doesn't really delete these platforms nodes, only changes their status internally, even if the platform directory gets deleted. I guess there is a conflict with Aegir internal protection procedure to mark Hostmaster as not allowed to delete. Very irritating.

**Comment by cvining** [comment]
Thanks for the feedback. Annoying, yes, but only that. I can live with it.

**Comment by omega8cc** [comment]
This has been fixed in

ef6e6efa1474392f9b6f81fbeb9e340770ccc3bb
