### ISSUE TITLE
stuck with a simple site install with thunder

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1395]
Hello

I am trying to create a site with thunder  i am using the lated version of BOA 
Here is the information about my install 

https://gist.github.com/yazzou/aaa74adae95405133228d65896502526

Here is what i have added in **fpm.info** : 
7.3
7.2
7.1
5.6

Here is what i have added in **cli.info** : 
7.3
7.2
7.1
5.6

I have also added a **multi-fpm.info** file where i have put the subdomain of the new site to be created with thunder : 
test4.mysite.com 7.2

I have the following error at the end 

https://gist.github.com/yazzou/eff6f2b32005d3ffb1fdbc4712948dad

**Comment by omega8cc** [comment]
Please check the docs again, you should put only one version in fpm.info and cli.info
