### ISSUE TITLE
npm not installed but RVM is fine

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#1397]
BOA 4.0.1 clean install on Debian 9. RVM installed correctly and I can install gems from limited shell accounts. But neither lshell nor root can use npm, they all report:
```
/bin/dash: 1: npm: not found
```
In limited shell account `~/.npm-packages/` is empty.

**Comment by omega8cc** [comment]
I think this has been fixed in HEAD: https://github.com/omega8cc/boa/issues/1363

**Comment by LunkRat** [comment]
Yes, I ran `barracuda up-head` (was on stable) and this got `npm` working.
