### ISSUE TITLE
LE certs not working on sites moved from another old boa server where LE was enabled. Symlink problem?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1399]
Hello,

We had a boa server crash a few months ago, and so I moved a few sites to our workign production server, and have been waiting (3 months now) for LE to renew certs, and we still don't have LE certs workign for these domains.  I have tried disabling LE, verifying, restarting nginx, and then re-enabling LE encryption, but we still only have self-signed certs for these sites which had a different dns adn ipv4 before, of course.  What can we do to get these sites up with a proper LE cert?  I read the SSL.txt doc and didn't find info on this particular situation, perhaps it could be added there?

It appears the problem is with creating a symlink: these are sites on a static custom d7 platform:
Could not symlink cert directory to /data/disk/o1/config/ssl.d/example.com	

Gist of verify log is here
 👍 https://gist.github.com/EdNett/0dd9585b29e5d350a1c6e9b49ee8ffa5

**Comment by omega8cc** [comment]
You would need to provide the complete task log with all truncated lines Expand-ed to see any useful hints there. Normally disabling Encryption and enabling it again is enough.

**Comment by omega8cc** [comment]
Please make sure you are not affected by #1433
