### ISSUE TITLE
query re tika local attachment search with solr 7 and search_api_solr 7.x-1.14 on stretch

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1400]
Hello,

We are working with boa latest up-to-date stable and we have a query re tika local attachment search with solr 7 and search_api_solr 7.x-1.14 on stretch.

There are two main tika .jar files in /opt/solr-7.6.0/contrib/extraction/lib/,
(tika-core-1.19.1.jar and tika-java7-1.19.1.jar)
but the module's GUI doesn't see that as a valid path, and refuses to save the path.  I can't find any other tika directory .

I followed your doc/SOLR.txt recommendation and added the 
$conf['apachesolr_attachments_java'] = '/usr/bin/java8 -Xms32m -Xmx64m';
to the sites' local.setting.php file, but that didn't change anything. (and I'm not sure if you mean the Apache Lucerne SOLR project  or the apachesolr drupal module, which we are no longer using with solr 7 (this could be clarified in the /doc/SOLR.txt).

So, what to do about the path and the tika (local) .jar file?

Or should we be using solr itself to extract info from attachments with solr 7 and search_api_solr - (that is an option but it isn't recommend by the module)?

Thanks for the clarification.

Best

Ed

**Comment by omega8cc** [comment]
Here are our original docs for Tika configuration with D7 module: https://learn.omega8.cc/tika-configuration-example-236 — it should provide helpful hints also for D8 configuration, although we didn’t verify it yet:

The path to use: /opt/tika9

and one of available files:

tika-app-1.8.jar
tika-app-1.9.jar
tika-app-1.10.jar
tika-app-1.11.jar
tika-app-1.12.jar
tika-app-1.13.jar
tika-app-1.20.jar

**Comment by EdNett** [comment]
thank you.
