### ISSUE TITLE
Debian upgrade not possible after 4.0.1

### ISSUE THREAD

**Issue by lefterav** [omega8cc/boa#1405]
The CHANGELOG.txt of version 4.0.1 mentions instructions to upgrade Debian Wheezy to Jessie. Unfortunately the instructions do not work for this version. Once running `barracuda up-stable` one gets the following error.

```
It is not any supported Debian or Ubuntu version.
You need Debian Stretch (recommended) or Jessie.
```

There is practically no obvious way to upgrade to Jessie any more

**Comment by lhaithaes** [comment]
i can confirm this

**Comment by omega8cc** [comment]
Wheezy support has been removed because it’s no longer possible to offer reliable Debian packages from archives. That also means that upgrade from Wheezy had to be removed from BOA 4.x — it was announced a long time ago. Now you are stuck and should probably consider using xboa for migration unless using old stable for upgrade to Jessie will work. We haven’t tested this because honestly never expected anyone still running on Wheezy. To upgrade to old stable you should use up-3.2 but as I said, it’s not tested.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lefterav** [comment]
Could you please point to the documentation for upgrading to an old stable? 
The CHANGELOG.txt should at least be changed because it is misleading.

**Comment by omega8cc** [comment]
You are probably reading wrong part of the changelog? It’s continuous document not just single version related. There are no docs on upgrade to old stable because it’s only intended for testing during phases between releases. Just type barracuda without any parameters to read about available options.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lefterav** [comment]
Yes, you are right, this was in the changelog under v. 3.2.2

**Comment by bserem** [comment]
@lefterav did this work for you?

I am trying to update from BOA-3.2.2 to 4.0.1 but get the same error.
I was under the impression that the update to Jessie had happened while I was doing the v3.x updates.

**Comment by omega8cc** [comment]
Major system upgrade doesn't just happen, it's not automated. You need to run it intentionally. If you still run Wheezy, you can't upgrade straight to BOA 4.x, you have to run upgrade to Jessie with up-3.2 first.

**Comment by lefterav** [comment]
@bserem in my case the upgrade failed, resulting to the entire server going down due to a broken PHP and MariaDB. Of course I am not sure if this failing is consistent because I have no resources to test

**Comment by omega8cc** [comment]
We will try to debug this to possibly offer upgrade path, even if it may require patching old stable.

**Comment by bserem** [comment]
I am retrying this today, the first attempt led to the server going down (a full restore from a system backup was required). I will disable mysqltuner this time though, because this is where things got stuck.

**Comment by bserem** [comment]
One would need to change "wheezy" to "oldstable" in etc/apt/sources.list before the update starts.
If not, the update stucks here:
```
WARNING: The following packages cannot be authenticated!
  openssh-server openssh-client git-man git git-core
Err http://security.debian.org/ wheezy/updates/main openssh-server amd64 1:6.0p1-4+deb7u7
  404  Not Found [IP: 151.101.120.204 80]
Err http://security.debian.org/ wheezy/updates/main openssh-client amd64 1:6.0p1-4+deb7u7
  404  Not Found [IP: 151.101.120.204 80]
Err http://security.debian.org/ wheezy/updates/main git-man all 1:1.7.10.4-1+wheezy6
  404  Not Found [IP: 151.101.120.204 80]
Err http://security.debian.org/ wheezy/updates/main git amd64 1:1.7.10.4-1+wheezy6
  404  Not Found [IP: 151.101.120.204 80]
Err http://security.debian.org/ wheezy/updates/main git-core all 1:1.7.10.4-1+wheezy6
  404  Not Found [IP: 151.101.120.204 80]
```

If oldstable is added the update proceeds.

Then these happen:
```
-BOA [15:12:02] ==> INFO: Building PHP 7.0.27 part 3/3
-sed: can't read Makefile: No such file or directory
```
on **every** php version, right after the 3rd part (I am currently installing php 5.5.38, 5.6.33 and 7.0.27).

The whole thing proceeds up to new-relic installation where it seems to have stuck for the moment with no information on the log:
```
Gracefully shutting down php55-fpm... done
Starting php55-fpm.. done
Reading package lists...
Building dependency tree...
Reading state information...
newrelic-php5 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
newrelic-sysmond is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 

```
While there the server is not serving any sites.
Nging is failing to start with this error:
`nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/srm/config/server_master/ssl.d/__DOMAIN__/openssl.crt"`

Trying to figure this out at the moment.

**Comment by bserem** [comment]
Now updating to 4.0.1, no problems thus far.

Recap:
- Change `wheezy` to `oldstable`
- Had to run `barracuda up-3.2` twice, and to remove newrelic

Once 4.0.1 finishes I will leave things for a day, then try the update to Stretch and re-add new relic (maybe).

**Comment by omega8cc** [comment]
Anyone still running Wheezy? or Jessie? It's time to upgrade to Stretch.
