### ISSUE TITLE
Xboa proxy remote_ip

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1407]
@omega8cc - I've seen some anomolies with the proxy forwarding at the end of a xboa migrate and always wanted to know, once I run this:
```
xboa proxy oct 1.2.3.4
service nginx reload 
xboa post-mig 

```
Of course, I expect the source server to redirect traffic to the new server 1.2.3.4 right?

What if I change my mind and want to scrap the new server for whatever reason and need to revert the proxy forwarding back to the source host?

I couldn't find any documentation around this and have come across it several times where instances are proxying sites to an incorrect IP somehow and it can be tricky to trace.  Is there any way to stop the proxy forwarding so the source server keeps getting the traffic?

**Comment by omega8cc** [comment]
We should document this, but it's pretty simple. You just need to log in to Aegir on the original server and re-verify all sites to overwrite all their overwritten vhosts. But perhaps automating this with extra command would be even better, since the script keeps the original vhosts in place, so it could simply replace them without running verify.

**Comment by karudonaldson** [comment]
Thanks for the response.

Something has gone really pear-shaped on this particular migration where the source host has migrated all sites but is now not processing tasks in the queue even through "service cron status" is showing as started.  

The main problem is if I switch off the source host, all of the sites on the new host, don't load?  I'm just baffled with what's going on here?  Is there something that gets injected into the database during a migration that is pointing back at the old host or something like that?

The current status is the source servers task queue is in a stagnant state preventing any Aegir tasks from being run and the new host can't serve sites if the source server is not on.  

Is there a manual workaround to solve this or could you advise exactly what the reverify will do on the source host to stop the proxy forwarding that perhaps I could do manually?
