### ISSUE TITLE
BOA 4.0.1 install get stuck on Hetzner's Debian 9

### ISSUE THREAD

**Issue by tourtools** [omega8cc/boa#1408]
Hello, 
I don't know if it is an Heztner VPS configuration's issue, 

the VPS is equipped with:
- 8 VCPU
- 32 GB RAM
- 240 GB DISK

the procedure is the following, all done via root user:

1. installing from scratch the VPS with Debian 9
2. changing the /etc/resolv.conf adding Google nameservers
3. adding ssh authorized key
4. removing preinstalled mysql with following commands:
 `$ apt-get remove --purge mysql-server mysql-client mysql-common -y`
 `$ apt-get autoremove -y`
 `$ apt-get autoclean`
 `$ rm -rf /etc/mysql`
 `$ find / -iname 'mysql*' -exec rm -rf {} \;`
5. execute the command for first installation:
 `$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`
6. which successfully gets me to the screen where I execute:
 `$ boa in-stable public xxxx.yyyyy.zz dddd@ffffff.zz o1`
7. this brings me invariably to the last script output:
 `BOA [xx:xx:xx] ==> INFO: InnoDB log file will be set to 1024M...`

where the installation hangs and get stuck seamlessly,

I've tried several times, but the result is always the same,

do you have any clue or a way on how to get to the source of the problem?

**Comment by tourtools** [comment]
Is it possible to config the boa install script in debug mode? 
This evening I've tried again to reinstall the VPS and BOA but with the same result. :(

**Comment by tourtools** [comment]
did it in some way,
looking at the  syslog the mysqld didn't restarting:


`
Jul 16 23:59:16 vpserver4 mysqld[1215]: 2019-07-16 23:59:16 140103969396992 [Note] InnoDB: Setting log file ./ib_logfile1 size to 1024 MB
Jul 17 00:00:01 vpserver4 systemd[1]: mariadb.service: Start operation timed out. Terminating.
Jul 17 00:00:02 vpserver4 mysqld[1215]: 2019-07-17  0:00:02 140103969396992 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
Jul 17 00:00:02 vpserver4 mysqld[1215]: 2019-07-17  0:00:02 140103969396992 [Warning] InnoDB: New log files created, LSN=22214986
Jul 17 00:00:02 vpserver4 mysqld[1215]: 2019-07-17  0:00:02 140103969396992 [Note] InnoDB: Highest supported file format is Barracuda.
Jul 17 00:00:02 vpserver4 mysqld[1215]: 2019-07-17  0:00:02 140103969396992 [Note] InnoDB: Read redo log up to LSN=22280704
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] InnoDB: 128 rollback segment(s) are active.
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] InnoDB: Waiting for purge to start
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.43-84.3 started; log sequence number 22215180
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140098876176128 [Note] InnoDB: Dumping buffer pool(s) not yet started
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17 00:00:04 7f6b4fbf7700 InnoDB: Loading buffer pool(s) from .//ib_buffer_pool
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] Plugin 'FEEDBACK' is disabled.
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] Server socket created on IP: '::'.
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103968925440 [Note] /usr/sbin/mysqld: Normal shutdown
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] Reading of all Master_info entries succeded
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] Added new Master_info '' to hash table
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103969396992 [Note] /usr/sbin/mysqld: ready for connections.
Jul 17 00:00:04 vpserver4 mysqld[1215]: Version: '10.1.40-MariaDB-1~stretch'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103968925440 [Note] Event Scheduler: Purging the queue. 0 events
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140098901354240 [Note] InnoDB: FTS optimize thread exiting.
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140103968925440 [Note] InnoDB: Starting shutdown...
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17 00:00:04 7f6b4fbf7700 InnoDB: Buffer pool(s) load completed at 190717  0:00:04
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140098876176128 [Warning] InnoDB: Dumping buffer pool(s) to .//ib_buffer_pool
Jul 17 00:00:04 vpserver4 mysqld[1215]: 2019-07-17  0:00:04 140098876176128 [Warning] InnoDB: Buffer pool(s) dump completed at 190717  0:00:04
Jul 17 00:00:06 vpserver4 mysqld[1215]: 2019-07-17  0:00:06 140103968925440 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
Jul 17 00:00:07 vpserver4 mysqld[1215]: 2019-07-17  0:00:07 140103968925440 [Note] InnoDB: Shutdown completed; log sequence number 22215190
Jul 17 00:00:07 vpserver4 mysqld[1215]: 2019-07-17  0:00:07 140103968925440 [Note] /usr/sbin/mysqld: Shutdown complete
Jul 17 00:00:07 vpserver4 systemd[1]: Failed to start MariaDB 10.1.40 database server.
`

restarting it manually did the trick, pfiuuuu

**Comment by omega8cc** [comment]
Looks like systemd was the problem here, or more precisely, the fact that MySQL was already installed under systemd control. BOA requires minimal OS with no services installed. Otherwise weird things may happen, with systemd being the most problematic culprit.

**Comment by tourtools** [comment]
Yep, that was the problem, don't know why, but the Hetzner's preconfigured minimal installation for Debian 9 come with Mysql installed, however, done that trick all went smooth, and now I'm moving gradually all the D6, D7 and D8 installations from the old VPS to the new one without problems,

thanks for this exceptional multilayer system integration that always leaves me speechless!!
