### ISSUE TITLE
current head 4.0.2-dev fails to install

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1411]
Hello,

The current head 4.0.2-dev fails to install early on at installing required libraries step - it just stalls - boa info more, below shows where it stops: (this error has been reproduced on a second test instance).

It looks like a mistake was made in the update github IPs  commit (in the BOA.sh.txt) 2 days ago.  
https://github.com/omega8cc/boa/commit/ac8c36dcd90c823750883283b8a44f117e1aa5bb
You have the new Ip for raw.githubusercontent.com wrong (151.101.112.133). It should be: 151.101.120.133
 Applying this change, however, in the BOA.sh.txt and the /etc/hosts fils does NOT allow the installation to proceed further. I cannot debug this further; I can only wonder if the changes made to the apt-get keyring 2 days ago are the cause of this error? 

boa info more:
Aegir BOA Cluster on Debian/stretch x86_64
  VPS unknown / not a virtual machine
  DSK 5/100
  CPU 3
  RAM 3952
  DBV not
  SSH 7.4p1
  SSL 1.1.0k
  CRL 7.52.1
  STG
  CSF
  LSH
  RIS
  SQL
  XTR
  MFX
  PFX
  DNS
  PKG

server1:~#

Best regards,

Edd

**Comment by omega8cc** [comment]
It was a temporary update, because we need to remove this hardcoding as it no longer makes sense because these names use multiple IPs which also change (CDN) plus they are different depending on where from you are connecting to GitHub (because it's CDN):

```
$ host raw.githubusercontent.com
raw.githubusercontent.com is an alias for github.map.fastly.net.
github.map.fastly.net has address 151.101.0.133
github.map.fastly.net has address 151.101.64.133
github.map.fastly.net has address 151.101.128.133
github.map.fastly.net has address 151.101.192.133
```

Normally it's not a problem on supported VPS or cluster installation, because they come with DNS resolver which makes these entries irrelevant anyway, so you can notice it only on unsupported system which doesn't have DNS resolver configured yet.

**Comment by EdNett** [comment]
Hello,
Retrying head gives us the exact same result. We do have a resolv.conf file which lists the online.net cloud IPs. This is a scaleway dev vps - could that be a problem? Are scaleway products a known problem for BOA?  I looked at the logs and I can't find anything relevant at all.

**Comment by omega8cc** [comment]
We don’t have any experience with scaleway, and it’s not listed as supported, so hard to tell what the problem is.

**Comment by EdNett** [comment]
Well at least we can upgrade to HEAD after installing STABLE. So, we can still test it!
