### ISSUE TITLE
[print_pdf_wkhtmltopdf] The currently selected PDF generation library (/usr/local/bin/wkhtmltopdf) is no longer accessible.

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1416]
Not sure when this stopped working, but I'm using print-7.x-2.2 on a v.BOA-4.0.2-dev installation (Debian 9) and wkhtmltopdf 0.12.5 appears to not be available to Drupal sites. The executable is properly installed at `/usr/local/bin/wkhtmltopdf` and has normal root group + 755 permissions for a BACKEND_ITEM.

**Comment by omega8cc** [comment]
The `/usr/bin/wkhtmltopdf` path was a symlink to `/usr/local/bin/wkhtmltopdf` but the modules expect the binary directly at `/usr/bin/wkhtmltopdf` and ignore the symlink, so we have fixed this for everyone with this patch: https://github.com/omega8cc/boa/commit/f3f00359ae003551007158ee0593c43bd007a04d. Perhaps we have missed adding something directly in the installation procedure, not sure.

**Comment by pricejn2** [comment]
Hmm, that still didn't do the trick for me. Even with the actual binary in both locations `/usr/bin/wkhtmltopdf` and `/usr/local/bin/wkhtmltopdf`, print_pdf_wkhtmltopdf is still reporting: 

> The currently selected PDF generation library (/usr/local/bin/wkhtmltopdf) is no longer accessible.

If I remove from `/usr/local/bin/`, it seems to work just fine and recognize the binary in `/usr/bin`

**Comment by omega8cc** [comment]
Interesting, because it fixed the problem in all instances reported in our internal ticketing system.

Can you check if permissions and ownership on those binaries look correct?

Perhaps we should review the print module code to find the culprit.

**Comment by omega8cc** [comment]
Ah, it's probably the shell wrapper which likes only the /usr/bin/ path..

**Comment by omega8cc** [comment]
Should be fixed as soon as the system auto-updates the shell wrapper.

**Comment by omega8cc** [comment]
This has been actually fixed in https://github.com/omega8cc/boa/commit/92f85d82ad4ab93567510a62fc4d2f8e259b08c7
