### ISSUE TITLE
SOLR 7 to SOLR 4 downgrade question

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1417]
Hello,

Update: simply running a new barracuda up-stable replacing SR4 with SR7 and then restarting solr7 and jetty9 services AFTER modifying the solr connection URL seems to have solved the problems we have been having. Could you briefly take a look at this problem (reverting to solr 4 after trying solr 7, and having only solr 7 as a service - is this suppossed to work this way with apachesolr module?) ? Thanks.

We have been using solr 4 with apachesolr module and recently upgraded to solr 7 with search_api_solr and have decided to return to the solr 4 with apachesolr for some sites. We have a few questions (boa 4.0.1 stable ):

Do we need to purge solr7 in order to get solr4 working properly again?  (simply adding SR4 to .barracuda.cnf or replacing SR7 with SR4 won't solve this problem - only solr7 is recognized as a service).

Can we have both solr 4 and 7 working on the same server (same barracuda) - seems unlikely to me - will jetty9 handle both, and how? IS this a hack?

running a barracuda up stable with SR4 specified AFTER having already installed SR7 gives us this:

server1:~# service solr7 status

Found 1 Solr nodes:

Solr process 19545 running on port 9077
INFO  - 2019-08-14 04:58:49.093; org.apache.solr.util.configuration.SSLCredentialProviderFactory; Processing SSL Credential Provider chain: env;sysprop
{
  "solr_home":"/var/solr7/data",
  "version":"7.6.0 719cde97f84640faa1e3525690d262946571245f - nknize - 2018-12-07 14:47:52",
  "startTime":"2019-08-14T00:03:18.698Z",
  "uptime":"0 days, 4 hours, 55 minutes, 31 seconds",
  "memory":"9.3 MB (%0.5) of 19.2 MB"}

server1:~# service solr5 status
solr5: unrecognized service
server1:~# service solr4 status
solr4: unrecognized service
server1:~# service jetty status
jetty: unrecognized service
server1:~# service jetty9 status
Checking arguments to Jetty:
START_INI      =  /opt/jetty9/start.ini
START_D        =  /opt/jetty9/start.d
JETTY_HOME     =  /opt/jetty9
JETTY_BASE     =  /opt/jetty9
JETTY_CONF     =  /opt/jetty9/etc/jetty.conf
JETTY_PID      =  /var/run/jetty9.pid
JETTY_START    =  /opt/jetty9/start.jar
JETTY_LOGS     =  /var/log/jetty9
JETTY_STATE    =  /opt/jetty9/jetty9.state
CLASSPATH      =
JAVA           =  /usr/bin/java7
JAVA_OPTIONS   =  -Xms8m -Xmx2048m -Djava.awt.headless=true -Dsolr.solr.home=/opt/solr4 -Djetty.logs=/var/log/jetty9 -Djetty.home=/opt/jetty9 -Djetty.base=/opt/jetty9 -Djava.io.tmpdir=/tmp
JETTY_ARGS     =  jetty.state=/opt/jetty9/jetty9.state jetty-logging.xml jetty-started.xml
RUN_CMD        =  /usr/bin/java7 -Xms8m -Xmx2048m -Djava.awt.headless=true -Dsolr.solr.home=/opt/solr4 -Djetty.logs=/var/log/jetty9 -Djetty.home=/opt/jetty9 -Djetty.base=/opt/jetty9 -Djava.io.tmpdir=/tmp -jar /opt/jetty9/start.jar jetty.state=/opt/jetty9/jetty9.state jetty-logging.xml jetty-started.xml

Jetty running pid=18735

/opt/solr4 just gives the core0-9 directories and the sites using solr search. It doesn't actually contain the solr executables. (/opt/solr7 is a symlink to the actual solr 7.6.0 install, for example). So, what to do to get solr 4.9.1 working properly once we have already installed solr 7?

Thanks for your thoughts and advice on this. Might be a good idea to add downgrade instructions to the SOLR file in /docs/

Ed

**Comment by omega8cc** [comment]
Solr 4 with Jetty and Solr 7 run in parallel and you should add both keywords, so there is no point and no way to "downgrade". Please check the docs for details: https://github.com/omega8cc/boa/blob/master/docs/SOLR.txt

Important: Solr 4 can be currently used only with apachesolr module with either Drupal 7 or Pressflow 6.

If you specify search_api_solr and the site is build on Drupal 8 or Drupal 7, your core will be created in Solr 7, since Solr 4 is legacy only version for older Drupal versions and apachesolr module.
