### ISSUE TITLE
php 5.6 found in /data/disk/arch/static/control/fpm.info and cli.info

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1419]
Hello,

We have found "5.6" in the files at:

/data/disk/arch/static/control/fpm.info and 

/data/disk/arch/static/control/cli.info

even though we are using php 7.2 for cli and 7.3 for fpm on barracuda.

Is this an error, or do you enforce 5.6 for sql backups or tuning or something?

Boa info more here:
https://gist.github.com/EdNett/c05c0a02d78ae6cac348631dd767767c

Best,

Ed

**Comment by omega8cc** [comment]
These are leftovers you should ignore. We shall purge them automatically to avoid confusion, since they do nothing.
