### ISSUE TITLE
Receiving email alerts from lfd although having set LF_EMAIL_ALERT to 0

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#1421]
I'm receiving emails from lfd about networks that have been blocked, although having set `LF_EMAIL_ALERT = "0"` in `csf.conf.`

Any ideas, how to disable them.

/etc/csf.conf:

```
# Send an email alert if an IP address is blocked by one of the [*] triggers
LF_EMAIL_ALERT = "0"
```

[boa info](https://gist.github.com/luxio/b3d6b7f31dfe01252bd12ab0111ed20d)

**Comment by omega8cc** [comment]
Have you restarted `lfd`? Like: `service lfd restart`

**Comment by luxio** [comment]
I have restarted `lfd` via `csf -r`. 

I had this setting in my csf.conf for a couple of years now, but since a couple of weeks I start receiving the emails again.

**Comment by omega8cc** [comment]
You have locked csf/lfd updates, so we would recommend that you update csf/lfd manually to preserve your configuration with `csf -uf`. You should restart `lfd` using `lfd` startup script, because with `csf -r` you are barely reloading firewall rules, you don't restart `lfd` with `csf`, the `lfd` is a parent daemon using `csf` as a tool.

**Comment by luxio** [comment]
Thanks for the information.

**Comment by luxio** [comment]
I have updated csf/lfd manually with `csf -uf` and restated lfd with `service lfd restart`, but I'm still getting emails with subjects like "lfd on xxx: Network class .. has been blocked". Any ideas why?

**Comment by omega8cc** [comment]
There are many different variables to enable/disable notifications, in this case the correct variable is `LF_NETBLOCK_ALERT` -- check also: https://www.adminbirds.com/scripting/script-disable-email-alerts-csflfd/

**Comment by luxio** [comment]
Thanks.
