### ISSUE TITLE
System Email Deliverability

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1423]
Hi team,

Understand this is an area that is widely unsupported though I wonder if for the sake of system emails getting to their destination that this could be incorporated into the BOA install scripts somehow?

Obviously feature request.

1. Configure DKIM, SPF and DMarc configuration for postfix
2. Include DKIM authentication, SPF Policy and DMarc DNS records in the welcome email
3. Create a readme.txt to finalise configuration and test everything is working correctly.  
- Fallback would be all of this would not apply which is currently the default.

A good reference doc to configure this manually is here:
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy

Thoughts?

**Comment by omega8cc** [comment]
This method looks rather useless in the hosting environment with two or more sites hosted which are using names not associated with server hostname, which is typical for all BOA servers. Our recommendation hasn't changed -- every site should use its own SMTP server and not use the local sendmail for anything -- https://learn.omega8.cc/never-send-mailings-from-aegir-server-322
