### ISSUE TITLE
Mysql and Nginx bugs

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1434]
I've updated the server today with `barracuda up-head `and it failed on MariaDB restart

barracuda.cnf
```
_DB_BINARY_LOG=NO
_DB_SERIES=10.1
_DB_SERVER=MariaDB
_USE_MYSQLTUNER=YES
```
The error output:
```
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to MySQL server on 'localhost' (111 "Connection refused")'
Check that mysqld is running on localhost and that the port is 3306.
You can check this by doing 'telnet localhost 3306'
```

Error output when running "mysqladmin variables"
```
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
```

Upgrade the `_DB_SERIES=10.1` to `_DB_SERIES=10.2` fixes this issue.

Nginx issue:
`2019/09/30 17:42:30 [emerg] 16523#0: "ssl_dhparam" directive is not allowed here in /etc/nginx/conf.d/aegir.conf:265`

Fixed by removed the Nginx defaults

Still getting this after `service nginx restart`
```
[ ok ] Stopping Nginx Server...:.
[....] Starting Nginx Server...:nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/data/disk/o1/tools/le/certs/o1.mywebsite.com/fullchain.pem"
. ok

```

I believe it will be good to have a way to revert the latest changes. Even if this was done on a test server it still need to be amended quickly on the production to remove downtime.

**Comment by omega8cc** [comment]
MariaDB 10.2 is the default version in HEAD since June 11: https://github.com/omega8cc/boa/commit/1938cfaca14cbefeb21ad6cccd9e516304ff6d39

You should switch to 10.2 already if you run head, because older versions are no longer tested with head.

As for the nginx problem, can you tell us what configuration snippet you have removed?

Also, please provide a gist link to required boa info output per https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by lexsoft00** [comment]
Good to know.
https://gist.github.com/lexsoft00/5e81f09126a5d014b11b902b03508dd5

I've lost the Nginx info but it seems to be related to the upgrade Nginx to a different version.

**Comment by omega8cc** [comment]
We are running BOA head in production with MariaDB 10.2 and haven't experienced anything like that on any system managed, so it's hard to tell what happened. Any reason why you have installed BOA head with non-default MariaDB 10.1 ?

**Comment by lexsoft00** [comment]
It's an old install which was upgraded to 4.0.x. I might have missed this in the documentation.
I will let you know if I encounter any more issues.

**Comment by lexsoft00** [comment]
I've updated the server again today and it re-adds these lines which breaks all websites:

```
#######################################################
###  nginx default ssl server
#######################################################


server {
  listen       *:443 ssl http2;
  #listen       [::]:443 ssl http2;
  server_name  _;
  location / {
    root                 /var/www/nginx-default;
    index                index.html index.htm;
    ssl_dhparam          /etc/ssl/private/nginx-wild-ssl.dhp;
    ssl_certificate      /etc/ssl/private/nginx-wild-ssl.crt;
    ssl_certificate_key  /etc/ssl/private/nginx-wild-ssl.key;
  }
}
```

**Comment by omega8cc** [comment]
Have you run full barracuda upgrade (including Aegir master) or just barracuda system upgrade?

**Comment by lexsoft00** [comment]
I used `barracuda up-head` including Aegir master

**Comment by omega8cc** [comment]
We have already fixed this in both Provision and BOA in response to #1430 and we have just tested this again with SSL enabled on master and we couldn't reproduce the problem, it gets properly disabled as expected. Can you possibly try again and make sure you have upgraded both barracuda and aegir master to head?

**Comment by lexsoft00** [comment]
Where is this disabled? Do you mean it remove the `###  nginx default ssl server` lines? 

I will try a test again to see what happens.

**Comment by lexsoft00** [comment]
The issue only happens if you need to upgrade Nginx to a newer version. 

I can't replicate it now since I've already upgraded.

**Comment by omega8cc** [comment]
Relevant commits are referenced in https://github.com/omega8cc/boa/issues/1430

**Comment by omega8cc** [comment]
https://github.com/omega8cc/boa/commit/61a59cee7ae08e164887de2d579c0a83a258e50f
https://github.com/omega8cc/boa/commit/66c82d4e39a74be7aa1596034dd64ba4600e1f33

**Comment by omega8cc** [comment]
Hmmm.. we will run upgrade tests from stable, so hopefully we could catch this if it's still an issue.

**Comment by lexsoft00** [comment]
Hi @omega8cc 
I've updated BOA today and Nginx was upgraded but I have not encountered this issue again.

This fixed for now.

**Comment by omega8cc** [comment]
@lexsoft00 Thanks for the confirmation, we couldn't reproduce this anymore either.
