### ISSUE TITLE
In-head installation fails at extra drush version

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1435]
Haven't tried installing the head version in a long time (several years).

I just tried and it reports this:
```
BOA [11:20:46] ==> INFO: Installing extra Drush versions...
BOA [11:20:46] ==> INFO: Drush 9.7.1 re-installation required
BOA [11:20:51] ==> FAIL: Drush 9.7.1 installation failed! Trying again..
BOA [11:21:10] ==> FAIL: Drush 9.7.1 installation failed again! Oops..
```

The things that I did:
- Fresh Debian 9.7
- `cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`
- `boa in-head public FQDN EMAIL o1 none php-7.2`
- Killed it to add some eXTRA in the .barracuda.cnf file (add IMG, SR7, CGP)
- Re-run the above command.

It continues after the fail, with MariaDB, Nginx etc.
Might be nothing, but I guess its better to report it.

Thanks

**Comment by omega8cc** [comment]
You shouldn't kill the install -- there is no point in doing this to add extra options, since you should run barracuda upgrade afterwards anyway. But the problem is elsewhere, it seems that barracuda is trying to install Drush 9 (non-essential, can be ignored) before installing Composer, so we need to add extra check.

**Comment by bserem** [comment]
Thanks for the fast fix.

Could you please clarify the:
> since you should run barracuda upgrade afterwards anyway

It is not documented in the INSTALL docs.
I'll be happy to assist with updates in the documendation if I can.

**Comment by omega8cc** [comment]
It's documented, at the very top: https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L4

**Comment by omega8cc** [comment]
It's also displayed on screen when you run the initial installation.
