### ISSUE TITLE
"The LE Certificate attempted creation failed in /data/disk/o1/tools/le/certs/example.com"

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1437]
Hi all 

On this Digital Ocean server, existing LE certs are ok  but this new LE cert fails with "The LE Certificate attempted creation failed in /data/disk/o1/tools/le/certs/example.com"

DNS records are correct for example.com and www.example.com

boa info followed by verify task record here https://pastebin.com/kLMdbcEf

I tried the task's suggestion of creating an empty ctrl file at /data/disk/o1/static/control/ssl-no-san-example.com.info - the task record shows this file was detected but the result of the next verify site task is the same

Any ideas please ?

**Comment by omega8cc** [comment]
The "urn:acme:error:badNonce" looks like typical intermittent error. Have you tried that again? if this still happens, please upgrade barracuda and octopus to head. We don't use the old stable and we run head instead, and we are busy with new stable release, so there is very slim chance that we could dive into debugging the isolated issues with old stable at this stage.

**Comment by omega8cc** [comment]
We are now forcing LE ACMEv2 API with new dehydrated script also on systems still running BOA-4.0.1, so you should get a working LE support again within 15 minutes, even if you haven't upgraded barracuda and octopus to HEAD yet.

**Comment by Juc1** [comment]
@omega8cc thanks but fyi I am still getting the same original error mentioned above ""urn:acme:error:badNonce"" etc on stable. I will try upgrading to head.

**Comment by omega8cc** [comment]
Hmm.. that sounds weird, please disable encryption and then enable it again, not just verify.

If this doesn't help, please force new account on LE with these steps:

1. Create empty `/data/disk/o1/.ctrl/ssl-demo-mode.pid`
2. Run verify on any site with enabled Encryption
3. Remove `/data/disk/o1/.ctrl/ssl-demo-mode.pid`
4. Run verify on any site with enabled Encryption

**Comment by Juc1** [comment]
FYI my problem was debugged and fixed in this similar issue https://github.com/omega8cc/boa/issues/1433

**Comment by omega8cc** [comment]
OK, thanks for the update.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
