### ISSUE TITLE
Unable to update barracuda for 24 + hours now

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1443]
Hello, We are running current boa stable and are have been trying to do a barracuda up-stable log on screen for 1 and 1/2 days now and the update won't start. Is there something wrong with our server (a misconfiguration or something), OR is there somthing wrong on your end, or on github, etc. ?

ps -s and ps -a show:

 Barracuda System managed by Skynet Agent v.BOA-4.0.1 welcomes you aboard

server1:~# ps -s
  UID   PID          PENDING          BLOCKED          IGNORED           CAUGHT STAT TTY        TIME COMMAND
    0  4614 0000000000000000 0000000000000000 0000000000000006 0000000000000000 Ss+  tty1       0:00 /sbin/getty 38400 tty1
    0  4615 0000000000000000 0000000000000000 0000000000000006 0000000000000000 Ss+  tty2       0:00 /sbin/getty 38400 tty2
    0  4616 0000000000000000 0000000000000000 0000000000000006 0000000000000000 Ss+  tty3       0:00 /sbin/getty 38400 tty3
    0  4617 0000000000000000 0000000000000000 0000000000000006 0000000000000000 Ss+  tty4       0:00 /sbin/getty 38400 tty4
    0  4618 0000000000000000 0000000000000000 0000000000000006 0000000000000000 Ss+  tty5       0:00 /sbin/getty 38400 tty5
    0  4619 0000000000000000 0000000000000000 0000000000000006 0000000000000000 Ss+  tty6       0:00 /sbin/getty 38400 tty6
    0 13376 0000000000000000 0000000000010000 0000000000380004 000000004b817efb SNs  pts/1      0:00 /bin/bash
    0 13582 0000000000000000 0000000000010000 0000000000000004 0000000000010002 SN+  pts/1      0:00 /bin/bash /opt/local/bin/barracuda up-stable log
    0 14955 0000000000000000 0000000000000000 0000000000000004 0000000000010000 SN+  pts/1      0:00 bash /var/backups/BARRACUDA.sh.txt
    0 14964 0000000000000000 0000000000010000 0000000000000000 0000000000010002 SN+  pts/1      0:00 bash /var/backups/BARRACUDA.sh.txt
    0 14965 0000000000000000 0000000000010000 0000000000000004 0000000000010002 SN+  pts/1      0:00 bash /opt/local/bin/ffmirror
    0 14973 0000000000000000 0000000000000000 0000000000001000 0000000188000201 SN+  pts/1      0:00 wget --spider -q -O /dev/null nl.files.aegir.cc
    0 19671 0000000000000000 0000000000010000 0000000000380004 000000004b817efb SNs  pts/0      0:00 -bash
    0 19745 0000000000000000 0000000000000000 0000000000000000 00000001f3d1fef9 RN+  pts/0      0:00 ps -s
server1:~# ps -a
  PID TTY          TIME CMD
13582 pts/1    00:00:00 barracuda
14955 pts/1    00:00:00 bash
14964 pts/1    00:00:00 bash
14965 pts/1    00:00:00 bash
14973 pts/1    00:00:00 wget
22258 pts/0    00:00:00 ps
server1:~#

yet nothing is actually happening and on the terminal command screen, we don't get the usual message confirming that the barracuda up-stable will commence.

**Comment by omega8cc** [comment]
We couldn’t reproduce this on stable but stable is very old, so at the moment we recommend to upgrade to head which is production stable and we use it ourselves.

**Comment by omega8cc** [comment]
Please try to restart pdnsd if it’s running, run service clean-boa-env start, and try again.

**Comment by EdNett** [comment]
Hello,
Thanks for the advice. pdnsd was running and we restarted it . I ran service clean-boa-env start and had the output:

 Barracuda System managed by Skynet Agent v.BOA-4.0.1 welcomes you aboard

server1:~# service clean-boa-env start
Starting clean-boa-env: clean-boa-env 1 nothing to do.
clean-boa-env 2 nothing to do.
clean-boa-env 3 done.
clean-boa-env 4 nothing to do.
server1:~#

but that didn't allow us to do a barracuda up-stable. The  update process never really gets started.  We have tried doing both hard and soft server restarts.  

We have a server providor firewall which is blocking everything except:
(all are tcp)

ssh on 22
http on 80 and 443
smtp on 25, 465 and 587
dns on 53

Are we missing anything here?  

Thanks.   We might try head, but not on this production server right away.

**Comment by omega8cc** [comment]
You might need to ask your provider to disable their firewall at least temporarily.

**Comment by EdNett** [comment]
Thanks, disableing their firewall did the trick and allowed the update process to proceed. Is there one additional incoming rule that I could add to their firewall (wa can set 10 rules on their firewall) that would allow the update to proceed?  Thanks.

**Comment by EdNett** [comment]
Closing this as it was only a firewall (NOT the boa firewall) issue.
