### ISSUE TITLE
barracuda up-head gives nginx ssl error - nginx won't restart

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1444]
Hello,

Upgrading boa from current stable to head 4.0.2-dev produces an nginx fatal error - it won't restart.

Executing: sudo /etc/init.d/nginx reload
  nginx: [emerg] PEM_read_bio_DHparams("/etc/ssl/private/4096.dhp") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
  nginx: configuration file /etc/nginx/nginx.conf test failed

This is with mariadb 10.2 and php 7.3 for both cli and fpm. I will try to reinstall barracuda head and force the nginx reinstall. This did not help. 

boa info more is here:
https://gist.github.com/EdNett/6e34cbaa4978be5e7c93bcbb57bc002a

**Comment by EdNett** [comment]
In addition, the octopus hostmaster instance can't get its lets encrypt certificate renewed - when it tries at octopus-url/.well-known/acme-challenge - it states "connection refused"

**Comment by omega8cc** [comment]
Have you run full barracuda upgrade on just barracuda system upgrade?

**Comment by EdNett** [comment]
I ran a full barracuda upgrade followed by a full octopus upgrade, and then I ran a second full barracuda up-head with nginx reinstall - and nginx doesn't start

**Comment by omega8cc** [comment]
You need to investigate if the expected file exists and has correct format. It’s normally generated during installation or via auto update every few minutes so something must be wrong if Nginx still complains about it. We couldn’t reproduce this on any supported system.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
Hello,

Of course the expected file exists, and it appears to have the correct read permissions .

Running openssl dhparam -out /etc/ssl/private/4096.dhp 4096  solved the problem, but that didn't tell me why the problem existed in the first place. 

Now it has permissions of 640 and is owned by root and in group ssl-cert. Does that sound right?

I'll try running the up head everything again to make sure nginx stays running. Closing this now since I assume it will.

**Comment by omega8cc** [comment]
Thanks for the update, although not sure why it hasn't worked by itself. We couldn't reproduce the problem.
