### ISSUE TITLE
barracuda up-head fails due to imagick from sources failure to complete - wrong directory name it appears

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1448]
This is on boa 4.0.2-dev with php 7.3, mariadb 10.2

BOA [12:58:46] ==> INFO: Installed ImageMagick version 6.9.7-4, upgrade required
BOA [12:58:46] ==> INFO: Building ImageMagick 7.0.4-6 from sources, please wait...
cp: cannot stat '/etc/ImageMagick': No such file or directory

the up-head stalls here forever (well, at least 1.5 hours the 1st time and over 30 min this time)

There is no /etc/ImageMagick - rather there is an /etc/ImageMagick-6

this must be the problem

boa info more is here:

https://gist.github.com/EdNett/d141b379f9e73624368ef177b6dedcfb

**Comment by omega8cc** [comment]
Hmm.. this options was actually intended as temporary workaround until new version is released a long time ago, and you shouldn't use it any longer (I think), so we never tested this again. Can you disable this option and see if that helps? I mean set `_MAGICK_FROM_SOURCES=NO`

**Comment by EdNett** [comment]
Hello,  We can't test this now because we couldn't get nginx restarted on head and had to scrap this head test server, and this magick_from_sources=YES variable must only have happened on head, since our stable servers all have magick_from_sources=NO.  What we can do is run an up-stable with this setting = YES on our test stable vps and report back and issues. I can do this in about 1 day.

**Comment by EdNett** [comment]
This is no longer a problem, as we have just successfully done an up-head - so this problem must have been resolved.
