### ISSUE TITLE
your uk.files.aegir.cc mirror must be down

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1449]
We have a server in the Eu and we can't update barracuda up-head now - scores of failed download from your uk mirror like:

BOA [17:51:47] ==> OOPS: pecl-jsmin-3.0.0.tar.gz failed download from http://uk.files.aegir.cc/dev/src/pecl-jsmin-3.0.0.tar.gz

**Comment by bserem** [comment]
I can get the file in the link through a browser. Maybe it was a network issue?

**Comment by omega8cc** [comment]
There were no availability issues for the London mirror. Perhaps a network issue then? If the problem persists, please send us your server IP via omega8.cc/contact so we could check the firewall logs.

**Comment by EdNett** [comment]
Closing this now - it must have been a temporary issue - we just wanted to inform you, that's all.
