### ISSUE TITLE
Impossible to upgrade / clone / sites 

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1450]
Hello 
I  had a broken octopus install, i have created a new one and transferred a site on it. 
I have three versions of d7 plateform (dev, staging and prod). : https://ibb.co/cvjRY7t

 The site was imported on the prod version. However when i want to clone the site to work on a dev version i don 't see the d7 dev plateform appearing as suggestion. 

https://ibb.co/MCpYWL8

Here is my 'boa info more '
https://gist.github.com/yazzou/6c8d35d21671b211c5582b65fe8a6bdc

**Comment by omega8cc** [comment]
> transferred a site on it

How it was done exactly? You should re-create the site on the new instance from backup as when you import the site for the first time.

**Comment by yazzou** [comment]
Well i did the transfer by following what written here

https://www.drupal.org/node/1366766#comment-5369572

**Comment by omega8cc** [comment]
> Well i did the transfer by following what written here
> 
> https://www.drupal.org/node/1366766#comment-5369572

This pretty old how-to is for advanced users only, we don't recommend this for anyone who never tried it before and can't fix such post-recovery issues in the hostmaster database themselves.

There must be something out of sync like drush aliases and hostmaster database records, which may need to be fixed directly in the database.

**Comment by omega8cc** [comment]
Or perhaps you have used installation profile which is not recognised properly?

**Comment by yazzou** [comment]
I have used the same installation profile as the target octopus instance.

**Comment by yazzou** [comment]
I have just done the following 
I have created a site with a D7 plateform (same as imported site) 
i edited the database of the octopus instance (table hosting site) 
I have noticed that profile value for the imported site was 0 and for the newly created site 62 (probably the id of the D7 platform) 
i have changed the value from 0 to 62 and saw "_**Install profileVanilla**_ Standard " appeared on the aegir backend when edited the imported site infos
now i can see the other plateform when i want to migrate 

I just tried to migrate to the latest version, it succeeded with a warning, because could not delete the folder of the current site 
Deleting /data/disk/octopus/distro/012/drupal-7.66.1-prod/sites/www.mysite.com/files directory failed. 
I have deleted manually this folder and restarted nginx and everything seems to work

**Comment by omega8cc** [comment]
Very weird, so perhaps a results of some accumulated issues in the Aegir database.
