### ISSUE TITLE
php warnings because of default newrelic.so extension

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1452]
Hello,  We are using boa stable latest with php 7.3 only and we keep getting the following cli warnings:

PHP Warning:  PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /opt/php73/lib/php/extensions/no-debug-non-zts-20180731/newrelic.so (/opt/php73/lib/php/extensions/no-debug-non-zts-20180731/newrelic.so: cannot open shared object file: No such file or directory), /opt/php73/lib/php/extensions/no-debug-non-zts-20180731/newrelic.so.so (/opt/php73/lib/php/extensions/no-debug-non-zts-20180731/newrelic.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

we have commented out the lines of some php.ini files so that they look like this:

;extension=newrelic.so
[newrelic]
newrelic.enabled=false
;newrelic.license = "REPLACE_WITH_REAL_KEY"
;newrelic.logfile = "/var/log/newrelic/php_agent.log"
;newrelic.loglevel = "error"
;newrelic.appname = "Other Tasks"
;newrelic.daemon.logfile = "/var/log/newrelic/newrelic-daemon.log"
;newrelic.daemon.loglevel = "error"
;newrelic.daemon.pidfile = "/var/run/newrelic-daemon.pid"
;newrelic.daemon.dont_launch = 3
;newrelic.framework.drupal.modules = 1

however the problem returns constantly. We are having to use chattr -a -i /home/o1/... to write to these two files:

/home/o1.ftp/.drush/php.ini
/home/o1.web/.drush/php.ini

and then we found these two:

/opt/php73/etc/php73.ini

/opt/php73/lib/php.ini

Are we missing a php.ini file?  Since we don't use new relic and don't want the constant php warnings, should we be doing a chattr +a +i to all 4 files after makeing the modifications?

Is using newrelic the new default, or is this a bug report?  Thanks.

**Comment by omega8cc** [comment]
It's never installed by default, unless you have specified non-empty `_NEWRELIC_KEY`

**Comment by omega8cc** [comment]
if you don't want to use it, make sure that `_NEWRELIC_KEY` is empty and then delete `/etc/newrelic/newrelic.cfg` and then run barracuda upgrade.

**Comment by EdNett** [comment]
Hello, Thanks for the response. We have never used newrelic, and we never put _NEWRELIC_KEY in a .barracuda.cnf file - it must have slipped in there when we did an up-head in the past. Closing this now.
