### ISSUE TITLE
Site migration is not working good

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1455]
Hi, using BOA HEAD, [boa info here](https://pastebin.com/GbsckrjL)

Site is unreachable (404 error) after migrating to a new platform because nginx vhost file is not updated and also there is somewhere a bad platform related to the site after migration.

**Sample scenario:**

- A platform called "oldplatform" (Drupal 8.7)
- Site called example.com
- A platform called "newplatform" (Drupal 8.8).

After migrating example.com from "oldplatform" to "newplatform" site is unreachable with a 404 error. re verifying the platform and the site doesn't seems to solve the issue, so you have to manually update the corresponding nginx vhost file at `/data/disk/o1/config/server_master/nginx/vhost.d/example.com` with the new database, username and password as it is not effectively updated (can see that information at the settings.php file). _Side note: I guess that information was meant to not be there, just in the vhost file._

In Aegir dashboard _all seems ok_ (site shows that the plaftorm is newplatform) but if you try to flush caches of the site, you will end up getting something like this [task log](https://pastebin.com/gns1V7KK) when provision tries to load the oldplatform, so the task is failed.

The Aegir database looks ok, I mean, the registry points to the correct new platform.

If you run `drush @example.com status` in shell, all seems fine too. The alias drush file seems also correct (site and platform aliases) and running tasks like flushing caches works fine in shell.

I tried restarting redis, flushing aegir cache and I still get task failure in aegir dashboard.

I still can't find where in the world is still pointing to the old platform.

**Comment by yaazkal** [comment]
Maybe https://github.com/omega8cc/boa/issues/1454 is related

**Comment by omega8cc** [comment]
Drupal 8.8 is not yet fully tested and supported in Aegir. Thanks for the bug report!

**Comment by yaazkal** [comment]
@omega8cc thanks for the answer. It happened to me before migrating from older versions of 8.x too, I can't remember wich one as I don't always create a new platform for upgrades even if it sounds no good in the aegir workflow ;)

**Comment by omega8cc** [comment]
This could be still a matter of Drush 8 issues with latest Drupal 8 versions. It worked for us before, so perhaps Drush still has something to fix to stay compatible, not sure, we will try to reproduce the problem.

**Comment by yaazkal** [comment]
I've access the shell today and now it seems it can't find the @example.com alias :)
Seems the daily tasks deleted the alias file.

**Comment by yaazkal** [comment]
I had to report that the 404 error also happens if also upgrade a D7 site, like to a the new platform with the recent 7.69 release.

Nginx and drush alias files are correct but a manual nginx restart is needed.

**Comment by zanami** [comment]
Same here

Migrated D8.6 to D8.8 — everything is nice and green
_drush @site status_ doesn't show database credentials
site doesn't work (redirects to install.php and returns 404)

service nginx restart and site verify helps

**Comment by dserrato** [comment]
I've had this issue a few times as well and it just happened this morning. I was running a migration of site from platform A (8.9.13) to platform B (8.9.16) and everything is green on the dashboard for a successful migration. Site give 404 error and url pushes to domain.com/core/install.php. Ran verify on the site and it fixed it quickly. Not ideal, but verify has been the solution for the handful of times this has occurred.

**Comment by tourtools** [comment]
Same thing happened to me yesterday both for D6 and D7 migrations:
root pointing to install.php, after manual trigger the website verification all went to its place.

**Comment by omega8cc** [comment]
The post-migration auto-verify is a part of BOA version of Aegir for some time already.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
