### ISSUE TITLE
o_contrib_eight version bumps

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1462]
Please provide the latest versions of advagg, cdn, and robotstxt o_contrib_eight modules. Thanks!

https://github.com/omega8cc/boa/blob/master/lib/functions/satellite.sh.inc#L1642
```
  get_dev_contrib "advagg-8.x-4.0.tar.gz"
  get_dev_contrib "cdn-8.x-3.4.tar.gz"
  get_dev_contrib "robotstxt-8.x-1.3.tar.gz"
```

**Comment by pricejn2** [comment]
Also, if reroute_email could be added, that would be fantastic!

**Comment by omega8cc** [comment]
We are trying to keep this list at absolute minimum, ideally only the modules automatically configured in BOA, because of the way the code management works in Drupal 8 (basically, via Composer), so adding more built-in modules for D8 is probably not recommended moving forward.

**Comment by pricejn2** [comment]
Yeah, that seems sensible. Can we just deprecate o_contrib_eight altogether then and keep global.inc configuration enhancements in place?

**Comment by omega8cc** [comment]
`o_contrib_eight` is up to date in head.
