### ISSUE TITLE
nginx: [warn] conflicting server name "o1.sub.domain.example" on 0.0.0.0:443, ignored

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1466]
Hi,

https://gist.github.com/lexsoft00/1cd2473b11cac5cdefc3a45b08a53282

I've updated the server to head and also updated o1 to head and resulted in an issue on the o1 website. I can't seem to reach it anymore with the error: `ERR_TOO_MANY_REDIRECTS`

From Nginx logs I get:

```
nginx: [warn] conflicting server name "o1.sub.domain.example" on 0.0.0.0:443, ignored
nginx: [warn] conflicting server name "www.o1.sub.domain.example" on 0.0.0.0:443, ignored
```
I've checked the configuration but everything seem to look fine:
https://gist.github.com/lexsoft00/1c386aa540e407962a04b2c8b242123a

I have tried to update the system again but it does not fix this issue.
I have the feeling I've experienced this before and fixed it somehow.

Please help

**Comment by omega8cc** [comment]
You have enabled forced encryption for the hostmaster site. Not sure why? It’s very visibly explained with warnings when you run installation and octopus upgrades that you should never do that. Please search the issue queue for hints on how to revert this mistake. Basically you have to edit the vhost and remove the block for port 443 and the redirect to https. Then reload Nginx and disable encryption in the control panel.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lexsoft00** [comment]
Hi,

Thanks a lot, 
I've copied another configuration that did not have the SSL enabled and it worked.

I leave here the config in case somebody else has this issue.
https://gist.github.com/lexsoft00/897d781791169a6a7126c737311c978b
