### ISSUE TITLE
csf.ignore site24x7  ips ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1468]
Hello,

I just noticed that there are about 350 ip entries with the notation #site24x7 ips after them in the /etc/csf/csf.ignore file - is this current and expected boa latest stable behavior?

Thanks for the OK if this is correct.

Best regards,

Ed

**Comment by bserem** [comment]
I suppose it is about this service: https://www.site24x7.com/

**Comment by omega8cc** [comment]
Yes, it's one of the few popular services BOA is whitelisting by default. Could be made configurable perhaps.

**Comment by EdNett** [comment]
Thank you - I looked at their site, of course, and I wondered if we would have to pay to get all 350 + servers working for us?

**Comment by omega8cc** [comment]
It's commercial service, but very reasonably priced. Highly recommended. Can be used for server and websites monitoring, kind of more advanced Pingdom and system level monitoring in one.
