### ISSUE TITLE
Warnings when installing an Octopus instance caused by userprotect.module

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1472]
When running an octopus installation, after the LetsEncrypt information messages these lines appear on the screen:

```
BOA [11:27:52] ==> INIT B: Enhancing Aegir UI, please wait...
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? userprotect.module:628                                   [warning]
"continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? userprotect.module:648                               [warning]
```

The installation process finishes and the Aegir UI works as far as I can say.

**Comment by EdNett** [comment]
Here is what we had - quite a bit more extensive:

https://gist.github.com/EdNett/c6a98bc51d30eff4005406e4963fa1bf

**Comment by omega8cc** [comment]
This has been fixed in the contrib module version currently included in BOA head: https://www.drupal.org/project/userprotect/releases/7.x-1.3
