### ISSUE TITLE
Issuer certificate not found for certificate...

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1473]
Lately, some certificates got lost and some failed to be generated.

I tried to test configuration and got this:

```root@dx 10:23:19 $ nginx -t
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/brisel.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/dragan.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/jasmina.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/mila.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/milica.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/mladen.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/nikola.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/sladjana.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/social.dx.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/umami.koder.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/varbase.dx.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.dunjanedeljkovic.com/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.dunjanedeljkovic.com/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.dunjanedeljkovic.com/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.hemiprodukt.co.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.hemiprodukt.co.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.hemiprodukt.co.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.itagency.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.itagency.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.itagency.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.neusatz.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.neusatz.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.neusatz.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.pgmajkic.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.pgmajkic.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.pgmajkic.rs/openssl.crt"
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

If you scroll to left you will see that some sites are listed three times.

Now, I did manage to repair them by going to edit/Disable and then edit/Require and everything was OK again, but that was a tedious process.

* Not sure why that happened in the first place: the first sites were created in series (those `*koder.rs`) and others just at some point displayed a problem. I will see if the **Disable/Require** did fix the thing long term.
* whatever the case is, maybe there should be some self-healing process if some site is missing its **certificate**?
* is there some `drush` or `cli` command that could enable more efficient recreation/healing the certificates?

**Comment by macmladen** [comment]
After trying to fix them all, the first 10 went through somehow.

Then, the eleventh task (requiring the SSL) reported as successful, but again there was a problem:

```root@dx 12:03:25 $ nginx -t
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.itagency.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.itagency.rs/openssl.crt"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/disk/o1/config/server_master/ssl.d/www.itagency.rs/openssl.crt"
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

I had to repeat the procedure of Disabling/Requiring and after a few repetitions, everything was fine.

**Comment by omega8cc** [comment]
This could be related to LE bug which they "fixed" by revoking 3,048,289 certificates: https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864

We should perhaps add temporary flag to force one-time renewal for all certs, instead of trying to figure out if they are affected.

**Comment by macmladen** [comment]
My questions:

1. Why there isn't an option to Control/Require HTTPS in the site creation?
2. Essentially, all the sites should be on HTTPS by default, why is it **Disabled** by default?
3. It would be convenient to have an overview of which sites are in **Required** state or BOA should warn about those which are not?

**Comment by macmladen** [comment]
> This could be related to LE bug which they "fixed" by revoking 3,048,289 certificates: https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864
> 
> We should perhaps add temporary flag to force one-time renewal for all certs, instead of trying to figure out if they are affected.

While that may be the case, today when I tried to reissue certificates, I still had to repeat the process and tasks were reported as successful (green).

**Comment by macmladen** [comment]
I suspected that too many of them (like 10) may be the problem and the thing is that the script should check if the generation was successful by testing with **nginx -t** before proceeding.

**Comment by omega8cc** [comment]
They actually decided to not revoke affected but not yet renewed certificates, so the problem must be elsewhere.

**Comment by omega8cc** [comment]
The system provides detailed report (full output) of the LE check on every Verify taks you run. Just make sure to click Expand on any truncated line starting with [hosting_le] in the Verify task log.

**Comment by omega8cc** [comment]
>> Why there isn't an option to Control/Require HTTPS in the site creation?

Because the site must already exist with valid and working DNS pointing to the server IP before you try to generate the certificate, first with Enabled, never Required on first attempt. On installation things are impossible to check reliably to continue with SSL certificate procedure.

**Comment by omega8cc** [comment]
>> Essentially, all the sites should be on HTTPS by default, why is it Disabled by default?

It's because BOA and Aegir are about features, not policy. There is no point in enforcing HTTPS by default, and no reliable way to make sure it actually works without too many failed attempts which will block the access for your system to LE servers because of too many failed tries.

**Comment by omega8cc** [comment]
>> It would be convenient to have an overview of which sites are in Required state or BOA should warn about those which are not?

Not sure I understand what you mean? There is no point in using Required as default or enforced mode anyway, because you should always use Enabled initially and switch to Required only when it actually works and you are sure you want to enforce encryption.

**Comment by omega8cc** [comment]
Back to the initial issue, please check the daily script log to determine why some sites failed to renew before expiration: `/var/xdrago/log/daily/`

**Comment by macmladen** [comment]
> > > Why there isn't an option to Control/Require HTTPS in the site creation?
> 
> Because the site must already exist with valid and working DNS pointing to the server IP before you try to generate the certificate, first with Enabled, never Required on first attempt. On installation things are impossible to check reliably to continue with SSL certificate procedure.

Understood.

**Comment by macmladen** [comment]
> Back to the initial issue, please check the daily script log to determine why some sites failed to renew before expiration: `/var/xdrago/log/daily/`

While there were failed configurations, I haven't seen anything in the log like **error**, **fail** or ** broken** which would lead to the conclusion.

I'll check tomorrow, but I have fixed them all, already. Nevertheless, I'll check.

On the other hand, lastly, I had around 5 sites left to be fixed.

The issue I had is that I opened them all in tabs, selected disable and save, one by one and after those tasks ended I edited them again to rever to **Required**. And because they were in succession, few failed (waiting in task queue and executing one by one).

For those that failed, I repeated but waiting and leaving some time to "cool off" and they went nicely through.

The thing is while some reported warnings, others went regularly but still failed with **nginx -t** test so I had to repeat those.

**Comment by EdNett** [comment]
Hello,

Is this on current head or stable (or both) ?

To get let's encrypt certificates to work consistently in BOA we have had to remove all IPv6 dns entries.

**Comment by macmladen** [comment]
I am on **stable** and, worse of all, I found that I am still on Jessie so I plan to rebuild on ProxMox container on Stretch.

@omega8cc Is Buster (Debian 10) safe?

For the record, I think the problem is on Let's Encrypt side, that they are either limiting the number of certificates they can issue or they are overwhelmed with requests.

**Comment by omega8cc** [comment]
We recommend conservative approach, because Debian tends to change things the way we not always agree with, so we are not eager to support latest/hottest variants early. We still run Stretch and even some Jessie. But you should run BOA head, not the over one year old "stable", at least until we switch to rolling release after the upcoming (last) stable in the old style.
