### ISSUE TITLE
Feature Request: Allow `drush uli` on hostmaster with .ftp user

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1475]
As documented in #771 and #694 it is possible to execute `drush uli` towards the hostmaster site (aegir), but this requires that you have root access to the system.

I believe it would be really handy if `drush @hostmaster uli` was allowed for octopus `.ftp` accounts. This account is safer to give to developers and other team members, even if they screw up they will screw up their octopus instance at worst.

Something equivalent would be enough too: something like `alias hostmaster-login=sudo -i -u o1 drush @hostmaster uli`, given that this particular sudo command would be whitelisted for user `o1.ftp`

**Comment by omega8cc** [comment]
The access separation between system and regular accounts is fundamental and is not going to change. We will not open this kind of critically dangerous security holes. You don’t need system root to use Aegir backend user. It’s enough to switch its shell to bash and add your SSH keys. But you have to remember about consequences. The Aegir system user has root level access to all databases on the db server. If you have more than one Octopus instance on the same system, as BOA is designed for, that user will have access to databases on all other instances. Of course there’s a ton of other reasons why using Aegir system account directly is very bad idea. It’s enough to run Drush command with incorrect arguments to crash the system if you are not careful. So the short answer is no.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bserem** [comment]
I appreciate the answer, however I am not sure whether my suggestion was understood.

I merely suggested that `o1.ftp` is allowed to run `drush @hostmaster uli`. I never suggested to allow anything more than that nor to use the aegir system user (`o1`) for anything other than that. After all, so many years with BOA and I rarely needed this user to do something.

I assumed that on BOA level, the `drush @hostmaster uli` would be something as easy as adding the site-alias to the o1.ftp user. I guess I was wrong!

**Comment by omega8cc** [comment]
That's exactly the problem that  `@hostmaster` is not just a site alias. It's a master key to run any powerful Drush command within the Aegir backend (and server), not just the hostmaster site. We could of course try to filter allowed commands and copy the alias as we do with hosted sites aliases, but it would be against the fundamental security policy to not open such security holes, where failure in the filtering script could lead to privileges escalation.

**Comment by bserem** [comment]
Didn't know that, I believed it was just another alias. It all makes sense now.

Thanks
