### ISSUE TITLE
How to allow httrack to run against BOA to archive/retire websites?

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1476]
There comes a time where sites become static (and possible outdated) and there are some really nice articles about how to *retire* those sites:
- https://www.drupal.org/node/27882
- https://www.lullabot.com/articles/sending-drupal-site-retirement-using-httrack

I find this to be really convenient, especially with old pressflow sites.

In short, this command:
```
httrack https://WEBSITE -O DESTINATION -N "%h%p/%n/index%[page].%t" -WqQ%v --robots=0 --footer ''
```
will get your website into a static format in your harddisk.

However, BOA systems will not allow HTTRACK to get anything from them (probably treated as a bot?).
How can I allow it to run towards a site hosted on BOA?

Thanks

**Comment by omega8cc** [comment]
You need to check the User Agent httrack is reporting and find if it's blacklisted in BOA/Nginx and then possibly override it to avoid being blocked. Not sure if httrack allows it, like wget and curl.

**Comment by bserem** [comment]
Thanks for the reply. I do not know how/where to whitelist the user agent, but with the information you gave it was quite easy to proceed.

HTTrack allows to customize the user agent. So, the following command is currently working:
`httrack https://YOUR_DOMAIN -O LOCAL_FOLDER -F "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" -N "%h%p/%n/index%[page].%t" -WqQ%v --robots=0 --footer ''`

With such a trick we can even keep BOA running but inaccessible from the public and only generate a copy of the site when needed. I'll post back here once I figure everything out and see if things work as expected.

**Comment by bserem** [comment]
Forgot to update, I have two really old sites fully converted to static html with httrack.
Javascript (accordions and galleries) worked just fine too.
