### ISSUE TITLE
CGP not available - also is collectd too active on head?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1477]
Hello,
on head php 7.3 and mariadb 10.2 - boa info more here:

https://gist.github.com/EdNett/d9d25909ced5009f20dd20a835185e33

1) I cannot  reach collectd at https://cgp.master.fqdn - with root over ssh active if necessary

Do I need to add a port number or what? (8888 doesn't work)

2) I am seeing unusual activity - 4 or 5 PID's as root running collectd -C /etc/collectd/collectd.conf
at all times when I look at htop, for example

Is this normal?

**Comment by omega8cc** [comment]
It no longer works, because it's an old version, no longer compatible with now default PHP 7+ so we need to update this interface, I guess.

**Comment by omega8cc** [comment]
We will probably deprecate it, unless some more modern web interface could be found. Even latest available CGP doesn't work properly.

**Comment by reswild** [comment]
Are you sure CGP doesn't work properly with PHP 7? It seems to be working OK on my servers (Debian 9 / PHP 7.4). The only thing I needed to do was edit /opt/php74/etc/pool.d/www74.conf and remove passthru from disable_functions.

**Comment by sluc23** [comment]
I confirm that removing `passthru` from disable_functions in my case in **PHP 7.2** conf file `/opt/php72/etc/pool.d/www72.conf` makes CGP working again (**BOA-4.1.4-dev**)
