### ISSUE TITLE
Feature Request: Allow civicrm.settings.php overrides

### ISSUE THREAD

**Issue by aiden-grau** [omega8cc/boa#1478]
Occasionally I find that it is necessary (or at least most sensible), to make changes to civicrm.settings.php (one example is when domain IDs need to be set for Domain Access). Apparently there is no way to do this, and I believe the file gets regenerated anyway?
If there is an elegant solution I'm unaware of I would love to hear about it, if not it would be great if provision could me made for customising civicrm.settings.php.

**Comment by GValFr35** [comment]
For your custom settings, use the local.settings.php file (create it if necessary).

**Comment by aiden-grau** [comment]
So I can use local.settings.php in the exact same way I'd use civicrm.settings.php?
According to [this article](https://learn.omega8.cc/how-to-edit-settingsphp-file-230) it's a bit risky in my situation but I'll just have to be careful.
Thanks!

**Comment by GValFr35** [comment]
Yes absolutely!

**Comment by aiden-grau** [comment]
Great, thank you.
