### ISSUE TITLE
GHOST drushrc for example.com detected and moved to /data/disk/o1/undo/

### ISSUE THREAD

**Issue by thomasfeichter** [omega8cc/boa#1480]
I noticed that some sites created in the default Varbase profile on BOA-4.0.1 are being removed nightly. 
The log says:
```
GHOST drushrc for example.com detected and moved to /data/disk/o1/undo/
GHOST vhost for example.com detected and moved to /data/disk/o1/undo/
GHOST site dir for example.com detected and moved from /data/disk/o1/distro/001/varbase-8.6.8-8.7.0/docroot/sites/example.com to /data/disk/o1/undo/
```

The sites were working fine before being moved. Interestingly one site in the profile has not been moved, but I haven't figured out yet, why that one has been spared while the others have been moved.

**Comment by omega8cc** [comment]
Here is the logic responsible for detection of broken/ghost sites:

        if [ -e "${_T_SITE_FDIR}/drushrc.php" ] \
          && [ -e "${_T_SITE_FDIR}/files" ] \
          && [ -e "${_T_SITE_FDIR}/private" ] \
          && [ -e "${_T_SITE_FDIR}/modules" ]; then
          _IS_SITE=YES
        else
          echo "GHOST drushrc for ${_T_SITE_NAME} detected and moved to ${User}/undo/"

There must be a drushrc.php file in the site's directory, along with files, private and modules directories present.

Can you check if the affected sites had these files/directories?

**Comment by thomasfeichter** [comment]
They had no modules folder yet as they were just standard varbase installs without any additional modules. Files, private and drushrc.php were there.
I guess if a site is not pulled from an empty GIT repository, BOA would create the modules folder automatically, but I guess that doesn't happen if the git repository doesn't contain a modules folder.

**Comment by thomasfeichter** [comment]
Sorry, accidentally clicked on the close button...

**Comment by omega8cc** [comment]
OK, we have removed this requirement.
