### ISSUE TITLE
upload progress errors with currrent head

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1482]
Hello, 
On BOA head latest with php 7.3.17 and 
when uploading any image with CKEditor and CKEditor insert, we get an
error shown on-screen in text area when using ckeditor insert an image. The error persists for 60 or more seconds, and there is no progress bar; then all of a sudden we have the correct ckeditor insert box - which then works - without the error message:
 
 An AJAX HTTP error occurred. HTTP Result Code: 502 Debugging information follows. Path: /file/progress/817885537 StatusText: error ResponseText: 502 Bad Gateway 502 Bad Gateway nginx
 
This is with filefield_nginx_upload disabled - with that moduel enabled it doesn't work at all. 

We are using uncompressed jquery 1.9 for site and 1.4 for admin.

nginx version, boa info more is here:
https://gist.github.com/EdNett/11c9a8a1b0fbf6198145d272d2d4c0eb

This may have been a change since updating php from 7.3.15 to 7.3.17 - done yesterday - or a new nginx version, it seems. I am trying to debug and will post more later.

Any ideas of where to look, how to fix would help.

Best regards,

Ed

**Comment by EdNett** [comment]
we have had this error many, many times today, and one (but not all we think) of them could be due to this segfault report:

### PHP: CRASH at 14:33:25 [1] discovered on 200425-143404 for example.com
### SYS: Apr 25 14:33:25 server1 kernel: [95258.958287] php-fpm[28257]: segfault at 7f4300000000 ip 00007f44c130c676 sp 00007ffe325d7a08 error 4 in libc-2.24.so[7f44c128c000195000]
### NGX: "ipv4-ok" example.com [25/Apr/2020:14:33:25 0200] "GET /file/progress/817885537 HTTP/2.0" 502 552 44 619 "https://example.com/node/add/classified" "Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36" 0.061 "-"
### PTH: never
### VHT:

**Comment by omega8cc** [comment]
It could be a result of having some PHP file with size exactly divisible by 1024, which may trigger PHP crash, or some other regression. You can try to switch PHP to some other supported and older version to see if that helps.
