### ISSUE TITLE
opigno d8 not installed - gzip format error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1483]
On new head w php 7.3.17 opigno failed to install during an up-head octopus:

Fri Apr 24 12:53:32 CEST 2020 / Debian.stretch x86_64 / Aegir HEAD / Barracuda BOA-4.0.2-dev / Nginx 1.17.8 / PHP-MI 7.3 / PHP-SE 7.3 / FPM 7.3 / CLI 7.3 / MariaDB-10.2.31 localhost

BOA [15:55:28] ==> DISTRO: Social 8.2 8.8 [005] installed
Opigno LMS 2.11 8.8 [005] - http://opigno.org [Y/n] y
BOA [15:55:30] ==> DISTRO: Opigno LMS 2.11 8.8 [005] installation in progress...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

BOA [15:55:30] ==> UPGRADE C: Removing some unused core files...

**Comment by omega8cc** [comment]
This has been fixed, was still in testing. Thanks.
