### ISSUE TITLE
Request help for firewall issue - unable to run xdrago/daily.sh with server providers' f/w enabled?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1484]
Hello,  I lack a real understanding of firewalls and how boa might need certain ports etc. open. I have a server whose provider offers free incoming rules on their f/w which I want to take advantage of to reduce the load on our boa server (we run a few free-speech advocate sites which draw a lot of ddos attacks, hacking attempts, etc.) I know that I have to disable the server providers f/w to run a barracuda up or an octopus up - this is OK (but if there is a simple f/w rule that you could share with me to allow these updates without disabling the server providers' f:w I would liek to know it!), but now I also think that I need the server providers' f/w disabled to run the xdrago/daily.sh script - which is necessary - it seems to have a wget call in the daily.sh script that the f/w is blocking. Is this correct? Is there a simple rule to add to allow it?  Here are the server providers' f/w rules (they allow us to set to 10 incoming rules only). Could I get some advice on this setup, please from anyone who knows this stuff? Thanks, Ed

Name | Source IP | Destination IP | Source port | Destination port | Protocol | TCP flags | Action |   |  

Icmp	0.0.0.0/0	0.0.0.0/0	0-65535	0-65535		icmp	syn|ack|f			accept

Ssh  	0.0.0.0/0	0.0.0.0/0	0-65535	22		   	tcp	sny|ack|f			accept

http	0.0.0.0/0	0.0.0.0/0	0-65535	80,443			tcp	syn|ack|f			accept

tcp established  “	0.0.0.0/0	0-65535	32768-65535		tcp	ack				accept

smtp	0.0.0.0/0	0.0.0.0/0	0-65535	25,465,587		tcp	syn|ack|f			accept

dns	0.0.0.0/0	0.0.0.0/0	0-65535	53		    	*	syn|ack|f			accept

These are incoming rules – everything else is blocked by default – this is on server providers' firewall (unknown type), BEFORE BOA lfd/csf:  The provider states:
"
Here you can define rules to filter incoming IPv4 packets.
The rules are processed from top to bottom.
If packages are not accepted by a rule, they are blocked by default (default policy: 'discard').
"

I can't run a barracuda up or octopus up (perhaps even the xdrago/daily.sh too) with firewall enabled – must disable! Is there a simple rule to add to allow boa updates and xdrago scripts to run without having to disable providers firewall?  Is there anything missing from these firewall records that could help me secure the server more? Is there anything wrong, or superfluous?  Thanks for help on this – I don't know much about firewalls and am trying to learn.  All this has NOTHING to do with the BOA csf/lfd firewall system.

Thanks for any knowledgable advice,

Ed

**Comment by angel0d** [comment]
> we run a few free-speech advocate sites which draw a lot of ddos attacks, hacking attempts, etc

without getting too political I want to admit that the statement above makes me a little skeptical

@EdNett would you mind disclosing (without any details of course) what type of "freedom of speech" you refer too ?

is it about human/civil rights, journalism, wikileaks etc ?

or is it about this type of US-based freedom of a very specific/narrow speech ?

**Comment by EdNett** [comment]
Hello,

We do get an awful lot of hacking, intrusion, ddos attempts - mostly from China, but 15 of it is spread all over europe north and south america, asia the middle east - it's crazy - and as far as I know (hopefully) we haven't actually been hacked - and i'd like to keep it that way.  This is definately not the place for a political discussion but to be brief we believe in freedom of speech - and are against censorship - that's all. (any kind of censorchip, whether government, ideology, group, church, establishment, left or right, communist, fascist, royal,religious,ideological,etc.!).

I'd like to know how to keep the provider's firewall enabled yet still have the  xdrago/daily.sh script run (and confirmation that it can't run with the above incoming f/w enabled and active (or is it just me that can't run it or do a boa update from the command line when that f/w is active)
Thanks for any help.
ed

**Comment by omega8cc** [comment]
You can find the standard answer in the project README in the requirements section:

>>The outgoing TCP connections via ports: 25, 53, 80 and 443 must be open

The problem is that it refers to "stable" releases which don't depend on the Git specific port, whereas head does depend on Git, so you also have to have Git specific port open for outgoing connections: 9418

We would recommend to mirror BOA firewall configuration for open ports on your network firewall, if you wish to use it, at least for those most important ports:

https://github.com/omega8cc/boa/blob/master/aegir/conf/csf.conf#L138

https://github.com/omega8cc/boa/blob/master/aegir/conf/csf.conf#L141

That said, you need to ask your host for further assistance if you need help in managing your firewall outside of BOA.
