### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by impara** [omega8cc/boa#1486]
Upgraded from the latest head to stable & Vice versa still got Connection refused when trying to load aegir in browser: ERR_CONNECTION_REFUSED
Tried on server
curl 10.0.0.10 -v
* Rebuilt URL to: 10.0.0.10/
*   Trying 10.0.0.10...
* TCP_NODELAY set
* connect to 10.0.0.10 port 80 failed: Connection refused
* Failed to connect to 10.0.0.10 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 10.0.0.10 port 80: Connection refused

Also tried
service nginx restart
[ ok ] Stopping Nginx Server...:.
[ ok ] Starting Nginx Server...:.

nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

Ningx master and worker processes is running fine but not listening on any port 80 or 443 !

**Comment by impara** [comment]
Should also mention that I have only installed php7.2 in both barracuda and octopus, does octopus work with only php7 installation?

**Comment by omega8cc** [comment]
>> from the latest head to stable

You should never do that, unless you can see there is new stable released recently. For now just use head.
