### ISSUE TITLE
Error generating document: Failed to generate PDF: Command unexpectedly terminated without error message

### ISSUE THREAD

**Issue by ephexnl** [omega8cc/boa#1488]
Hi,

First of all, we are not sure that this issue has something to do with BOA, but below you will find our findings.

A while ago we experienced an issue with the Entity Print module in Drupal 8. It was not working with the wkhtmltopdf binary and after some testing, we found out that it was not working at all. Even with a clean installation of Drupal.

**Problem/issue**
When installing the entity print module with the phpwkhtmltopdf library, it is not working out of the box. Instead, there will be an error when printing a node which says that the command is terminated unexpectedly without an error.

When you are using the entity print module and want to use the wkhtmltopdf print eninge, you are required the install the composer package “mikehaertl/phpwkhtmltopdf ~2.1”. The package has a dependency on “mikehaertl/php-shellcommand”, but it seems that the newest version (1.6.1 at the time of writing) of this package is not compatible with our BOA setups (we have tested it on two different servers).

**Drupal log message**
Error generating document: Failed to generate PDF: Command unexpectedly terminated without error message

**PHP error log message**
Uncaught PHP Exception Drupal\entity_print\PrintEngineException: "Failed to generate PDF: Command unexpectedly terminated without error message" at /data/disk/o1/static/[PLATFORM]/web/modules/contrib/entity_print/src/Plugin/EntityPrint/PrintEngine/PhpWkhtmlToPdf.php line 211

**Observations**
It was not clear to us what happened exactly, because we did not get a clear error message or useful debug info. It seemed like that the process was not allowed to execute the wkhtmltopdf binary.

**Quick fix**
After requiring version 1.2.2 instead of 1.6.1 of “mikehaertl/php-shellcommand”, (from another, working, project) it seemed like to work as normal again.

**Comment by ephexnl** [comment]
A gist to the info of the two servers: https://gist.github.com/ephexnl/5959c4aff10413449f77d9c18fe3fcfd

**Comment by omega8cc** [comment]
We recommend that you upgrade to BOA head (both barracuda and octopus) since 4.0.1 is over one year old and doesn't receive any bug fixes, while head is the new "stable" and safe to use in production. We use head in production for years actually. The confusion with stable should be fixed after upcoming release. BOA head includes also fixes for wkhtmltopdf support.
