### ISSUE TITLE
Advagg contrib update

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1490]
Hi,

This is my boa info gist file:

https://gist.github.com/timlie/d340e6e224ea6621715ecda42e60ad20

As described in this commit:

https://github.com/omega8cc/boa/commit/881f615f23d733d36df90d2344074449f015f01b

Advagg for D8 is updated to version 4.0

Only for me in the o_contrib_eight folder, it is still version 3.5

In the .info.yml file:

version: '8.x-3.5'
core: '8.x'
project: 'advagg'

Thanks!

**Comment by omega8cc** [comment]
Have you run `octopus up-head` upgrade to add at least one new platform? It's required to trigger `o_contrib_eight` update -- but only for newly added platforms, it will never update any module in the existing o_contrib_eight tree used by previously created platforms.

**Comment by timlie** [comment]
Aah ok, thanks. I didn't know that.
I use my own custom platforms in static.
Is this "boa" advagg module different from the "Drupal" one? There is now also version 8.x-4.1, can I just replace this one in the o_contrib_eight directory?

**Comment by omega8cc** [comment]
No, you shouldn’t replace anything. You never update code in place. But you can easily override it in newer platform before migrating your site there for properly run upgrade by adding your version to sites/all/modules 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
The modules are not modified in BOA, just included for convenience.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timlie** [comment]
Allright, so if I understand correctly for a Drupal 8 platform, o_contrib_eight takes precedence on docroot/modules (or web/modules), where composer places by default its modules, but not on docroot/sites/all/modules?
In my example advagg 8.x-4.0 is in docroot/modules but is not used, instead the module from o_contrib_eight is enabled.
Thanks a lot!

**Comment by omega8cc** [comment]
Not exactly. The `o_contrib_eight` symlinked in the core `modules` makes it part of that level of code, so `sites/all/modules` can override it. You can't override `o_contrib_eight` with your copy in `docroot/modules` because it's the same level of code. You have to put it in `sites/all/modules` instead.

**Comment by omega8cc** [comment]
BOA head comes with latest AdvAgg now, by the way.
