### ISSUE TITLE
Plans for D9

### ISSUE THREAD

**Issue by Eligioo** [omega8cc/boa#1492]
Hi everybody,

What are the plans for BOA regarding D9? What is currently the support, is there a roadmap, or are there milestones already? I've been looking around to find some information but couldn't find anything.

Stefan

**Comment by timlie** [comment]
As per:

https://www.drupal.org/docs/understanding-drupal/how-drupal-9-is-made-and-what-is-included/environment-requirements-of

The only thing we need is drush10, I guess.

**Comment by omega8cc** [comment]
It’s a matter of Drush and Aegir compatibility, not BOA. Drupal 9 is supported only by Drush 10, but Drush 10 doesn’t support any earlier core version, so it’s useless in the Aegir context. Aegir depends on Drush 8 to support Drupal 8,7,6 so we are working on adding unofficial Drupal 9 support in Drush 8 and Aegir. No ETA yet, though, but there is progress.

**Comment by omega8cc** [comment]
That was fast! The first ever Drupal 9 site successfully installed and managed on BOA modified Aegir hosting system. Also, powered by latest PHP 7.4.6 and MariaDB 10.3.23 plus LetsEncrypt, obviously. New stable BOA is coming!

<img width="1262" alt="screenshot_04" src="https://user-images.githubusercontent.com/128547/83917820-cff35900-a777-11ea-9315-35e67633f2aa.png">

**Comment by molaria** [comment]
Gret News! Impressed!
Greatings from Sweden, Mats-Olof Liljegren

**Comment by timlie** [comment]
Woaw! This is great news!! Tremendous work by you guys!
