### ISSUE TITLE
ALERT: Failed Barracuda/Octopus upgrade

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1493]
This morning I received errors from the weekly automatic upgrades. These upgrades have been running OK for a long time, and I did not make any changes in the last weeks, so I'm a little surprised. Here's my [boa info](https://gist.github.com/ar-jan/f8872a0b11354d11a0dad9d4be01a618) output. And these the emails I received:

BOA [00:06:19] ==> Skynet Agent v.BOA-4.0.1 welcomes you aboard!
BOA [00:06:22] ==> INFO: UPGRADE
BOA [00:06:33] ==> VIRT: This system is supported: Linux KVM guest
BOA [00:06:33] ==> Aegir on myserver.example.comDebian/jessie x86_64 PHP 7.0
BOA [00:07:01] ==> INFO: Installing extra Drush versions...
BOA [00:07:10] ==> INFO: Running system packages update...
BOA [00:10:05] ==> INFO: Upgrading required libraries and tools...
BOA [00:12:21] ==> INFO: Running aptitude full-upgrade...
BOA [00:18:05] ==> INFO: Running Aegir Master Instance upgrade
BOA [00:18:20] ==> FATAL ERROR:: DNS looks broken for server myserver.example.com
BOA [00:18:20] ==> FATAL ERROR:: Aborting Barracuda installer NOW!

BOA [05:05:14] ==> Skynet Agent v.BOA-4.0.1 welcomes you aboard!
BOA [05:05:18] ==> Octopus Satellite Instance Upgrade in progress...
BOA [05:05:19] ==> This Octopus URL address is o1.myserver.example.com
BOA [05:05:19] ==> This Octopus PHP version is 7.2
BOA [05:05:19] ==> This Octopus System is Debian/jessie x86_64
chattr: No such file or directory while trying to stat /home/o1.ftp/platforms/*
BOA [05:05:27] ==> UPGRADE A: Shared platforms code v.002 will be used
BOA [05:05:30] ==> UPGRADE A: FATAL ERROR: DNS looks broken for myserver.example.com
BOA [05:05:30] ==> UPGRADE A: FATAL ERROR: Aborting AegirSetupA installer NOW!
BOA [05:05:30] ==> FATAL ERROR: AegirSetupA installer failed
BOA [05:05:30] ==> FATAL ERROR: Aborting Octopus installer NOW!

There is indeed no platform in /home/o1.ftp/platforms/*, but the hostmaster site for the latter is in /data/disk/o1/aegir/distro/003 and this site is fully functional (platforms for my hosted websites are in static). There is no DNS problem with either myserver.example.com or o1.myserver.example.com (it looks like that's a misleading error and the problem somehow has to do with the hostmaster platform not being in the expected place?).

Any clues what's happening?

**Comment by omega8cc** [comment]
This doesn't look like the weekly system upgrade, it looks like full Barracuda+Octopus upgrade to *stable*, which is wrong for two reasons: you should never run unattended Octopus upgrades without prior testing, second, you shouldn't use stable anymore, only head.

**Comment by ar-jan** [comment]
Oh, I'd been staying on stable because I think it was mentioned somewhere that stable itself would become the rolling release (and head is still described as not meant for production).

I just tried the full upgrade to head manually (`cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`,  `barracuda up-head`) but there the last step failed with the same problem:

Do you want to upgrade Aegir Master Instance? [Y/n] y
BOA [23:44:34] ==> INFO: Running Aegir Master Instance upgrade
BOA [23:44:38] ==> FATAL ERROR:: DNS looks broken for server myserver.example.com
BOA [23:44:38] ==> FATAL ERROR:: Aborting Barracuda installer NOW!

**Comment by ar-jan** [comment]
P.S. the reason for the full upgrade was that besides _AUTO_UP_WEEKLY, the _AUTO_UP_MONTH and 
_AUTO_UP_DAY variables were configured for what was a day in the past in 2019, and I hadn't updated these this year.

**Comment by omega8cc** [comment]
I can see at least three problems here:

1. Your disk is almost full and BOA will refuse to work properly
2. You are using PHP CLI 5.6 by default, so you can't upgrade until you switch CLI to 7.2 or 7.0
3. You are still running MariaDB 10.1, and HEAD will force the upgrade to 10.2

**Comment by ar-jan** [comment]
Thanks, solved after setting `_PHP_CLI_VERSION=7.2`.
