### ISSUE TITLE
Query re how to install platform with 7.x hardened core ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1494]
Hello,

I just want to get your confirmation that to setup a new 7 platform with your recommanded hardened core we:

1) set the platform type as :
Deploy from Git repository (not managed by Composer)

and

2)  Git repository URL  is  https://github.com/omega8cc/7x

and 

3)  Git reference  is  7.x-om8

Is this the recommanded way to do it?

I ask this, because this is what I did, and since migrating sites to the news platform built with 7.x-om8 (from a platform that was built with regular core as downloaded by drush) - I cannot get /admin/config page to display - and I can't get the sites to do a status report - both give errors that aren't written to the log.

Thanks,

Ed

**Comment by EdNett** [comment]
The drush update to 8.3.5.2 solved the problem of errors displaying /admin/config and doing a status report - both of which work once again. 

I won't close this until I get confirmation that building a 7.x boa static platform is done in the way I described it, above (rather than taking a file from files.aegir.cc/core/ etc and buildign from a make file etc)?

or are the two appraoches the same thing?

**Comment by omega8cc** [comment]
We never considered using this repo as a source for Git based platforms.

You don't control this repository so you shouldn't use it via Git.

You should either use makefile referencing the correct D7 core or upload it manually.

It's explained in the docs at: https://learn.omega8.cc/how-to-add-custom-platform-properly-140
