### ISSUE TITLE
Bind upgrade problem

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1495]
I had hoped to get latest head 4.0.2-dev and was on a screen session, and had no choice (unless there's a way to stop an upgrade on a screen session that I don't know about), and 

BOA [19:00:58] ==> INFO: Downloading drush 8.3.5.1...
BOA [19:01:07] ==> INFO: Installing Aegir Provision backend...
BOA [19:01:07] ==> INFO: Downloading Drush and Provision extensions...
BOA [19:01:17] ==> FATAL ERROR: Drush is broken (/opt/php73/bin/php /var/aegir/drush/drush.php help failed)
BOA [19:01:17] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
BOA [19:01:17] ==> FATAL ERROR: AegirUpgrade installer failed
BOA [19:01:17] ==> FATAL ERROR: Aborting Barracuda installer NOW!

errors in gist here:  (error configuring bind9):
https://gist.github.com/EdNett/93440b222720f090f3cceadbf234a4ed

boa info more here:
https://gist.github.com/EdNett/38b2185a5cdc871c900ee1904b3109a3

**Comment by timlie** [comment]
Have you tried a second time?
I had the same on a server four days ago (before last php an Drupal9 commits) but after trying upgrade again, drush succeeded.

**Comment by EdNett** [comment]
running the barracuda up-head again does not solve the bind9 error which remains partially configured.  Getting the upgraded drush 8.5.3.2 is critical however, and necessary.

**Comment by omega8cc** [comment]
Bind is not a part of the default installation, it's optional like webmin, and is rarely tested these days. You may need to resolve the Debian packages upgrades problems manually if running barracuda upgrade again doesn't help.

**Comment by EdNett** [comment]
This poroblem still exists on new up-head 4.1.1 2 months later. I will give error on gist and list steps I have taken to resolve for others:

gist:  https://gist.github.com/EdNett/9285c114e00d3237a1a5e6ee8023f960

boa info more:  https://gist.github.com/EdNett/d5ca59826b056150adf0eaa92c79fbb6

**Comment by EdNett** [comment]
running



mkdir /var/lib/bind

and then 

aptitude install bind9  or dpkg configure bind9

allows bind9 to be configured and stops the error notices

the problem was:  Setting up bind9 (1:9.10.3.dfsg.P4-12.3+deb9u6) ...
/var/lib/dpkg/info/bind9.postinst: 28: /var/lib/dpkg/info/bind9.postinst: cannot create /var/lib/bind/bind9-default.md5sum: Directory nonexistent

I'll leave this open in case soemone wants to change the script itself so this directory is created when adding "BND" as an option in the barracuda update script.
