### ISSUE TITLE
Query re naming of stable and dev versions

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1496]
Hello,

I was on 4.0.2-dev, and then did an up-head and got 4.1.1-dev - which was a shock. If I try to go to stable now I get 4.0.1 stable (NOT the 4.0.2 that I would expect).

So,  wouldn't it be clearer if there weren't a 4.1.1-dev until there is a 4.0.2 stable or a 4.1.0 stable ?

Best regards,

Ed

**Comment by omega8cc** [comment]
The last digit is for bug fix releases only. New stable comes with many new features and should be actually 4.3.x but we will probably keep it at 4.1.x for now, at least until we decide how to number the new stable release after so many changes in many months. You shouldn't be surprised, as head can use any number we plan to use for next stable, and it's also used to trigger required scripts updates for head based instances, which wouldn't happen if you have kept upgrading from head to head.
