### ISSUE TITLE
Compile GD and ImageMagick libraries with WebP support

### ISSUE THREAD

**Issue by tourtools** [omega8cc/boa#1501]
Feature request

**Comment by pricejn2** [comment]
Subscribed. This is more challenging to manually add via `_PHP_EXTRA_CONF` because of different compile flags for PHP 7.4 https://www.php.net/manual/en/image.installation.php

**Comment by hodbakhalaf** [comment]
+1

**Comment by omega8cc** [comment]
We have merged the PR kindly submitted by @pricejn2 -- thank you!
