### ISSUE TITLE
No migration due to missing packages

### ISSUE THREAD

**Issue by mabo1972** [omega8cc/boa#1502]
Procedure:

1. new platform created
2. required modules copied to the /sites/all/modules folder
3. verify the new platform
4. migration cannot be started due to missing modules that are present in the /sites/all/module folder.

What is the reason for this?

![2020-06-18_14h42_28](https://user-images.githubusercontent.com/8982685/85022173-3a8e9680-b173-11ea-8b3e-11c251ae693c.png)

https://gist.github.com/mabo1972/70edf358abeb449c4c85d150f3dedb32

**Comment by omega8cc** [comment]
These modules are marked as downgrade and blocked, because they have lower schema registered for some reason. It's explained in the docs at https://learn.omega8.cc/your-drupal-site-upgrade-safe-workflow-298
