### ISSUE TITLE
BOA version mismatch / weekly system update error

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1504]
I recently updated my BOA install to head (4.1.1-dev). As part of the upgrade a requirement was to use PHP >= 7.3, so I configured 7.4. Today I also updated from jessie to stretch. Everything seems to work fine, but now the automatic weekly update email gives this error:

```
BOA [00:12:15] ==> Skynet Agent v.BOA-4.0.1 welcomes you aboard!
BOA [00:12:18] ==> INFO: UPGRADE
BOA [00:12:29] ==> VIRT: This system is supported: Linux KVM guest
BOA [00:12:29] ==> Aegir on o1.example.com Debian/stretch x86_64 PHP 7.4
BOA [00:12:38] ==> ERROR: This BOA version depends on PHP 7.1 or newer
BOA [00:12:38] ==> Please add 7.1 and/or 7.2 to _PHP_MULTI_INSTALL
BOA [00:12:38] ==> in /root/.barracuda.cnf before trying again
BOA [00:12:38] ==> Bye
```

The version listed here is not correct (when I login the welcome message says correctly states BOA 4.1.1-dev). Also, the system update works fine when I manually run `barracuda up-head system`.

Or is the auto update running `barracuda up-stable system` instead and trying to revert to stable? I had initially updated to HEAD but then noticed that later update emails mentioned 4.0.1. Today I upgraded (again?) to 4.1.1/stretch, and disabled old PHP versions as discussed [here](https://github.com/omega8cc/boa/issues/801#issuecomment-228538725). So PHP 7.2 can no longer be used, maybe that's why the update is now failing? Here's my boa [info](https://gist.github.com/ar-jan/d99dce8798106efb6a67cfb627e7ae2b). Hope you have any suggestions.

**Comment by omega8cc** [comment]
This message is not from head, so not sure where do you see it while running head scripts? Please make sure they are up to date per: https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt#L10

If you are using autonomous upgrades, make sure you have `AUTO_VER=head` in your `/root/.barracuda.cnf`

**Comment by ar-jan** [comment]
Oh I see! Yes this is the auto-upgrade, manual updates were working.

I didn't know about `_AUTO_VER`, in fact the variable is not in my .barracuda.cnf or I would have known to change it!

**Comment by ar-jan** [comment]
My issue has been fixed, but maybe it would be a good idea if BOA would add `_AUTO_VER` to .barracuda.cnf and set it to stable/head, depending on what applies?

**Comment by lexsoft00** [comment]
+1 to get this committed to the docs https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf
