### ISSUE TITLE
HEAD upgrade tries to upgrade PHP 5.6 a number of times after Jessie to Stretch upgrade

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1505]
Hi,

Yesterday I upgraded my BOA server to latest HEAD.
This is my "boa info more" gist file:

https://gist.github.com/timlie/d2ad9b98863f28f064bbc9a9476890eb

After this upgrade I made the switch from Jessie to Stretch.

The output of the upgrade is this:

https://gist.github.com/timlie/b6bd18d1755527398e0752adc5137881

I use:

_PHP_MULTI_INSTALL="7.3 7.2"

since yesterday (before it was only 7.2, and really long time ago it was on PHP 5.6) to make the switch to latest HEAD.

When doing a new:

barracuda up-head

php 5.6.40 is trying to be build from sources:

BOA [22:11:39] ==> INFO: Building PHP 5.6.40 from sources, please wait...
BOA [22:11:45] ==> INFO: Building PHP 5.6.40 part 1/3
BOA [22:11:46] ==> INFO: Building PHP 5.6.40 part 2/3
BOA [22:12:10] ==> INFO: Building PHP 5.6.40 part 3/3
BOA [22:12:10] ==> INFO: Building PHP 5.6.40 part 2/3 (again)
sed: can't read /var/opt/php-5.6.40/Makefile: No such file or directory
BOA [22:12:36] ==> INFO: Building PHP 5.6.40 part 3/3 (again)

a couple of times.

Thanks!

**Comment by ar-jan** [comment]
PHP versions that are no longer used are not actively removed by BOA, so if there are updates they are (apparently) rebuilt as part of the normal upgrade process. You can deactivate unused versions like so: `mv -f /opt/php56/bin/php /opt/php56/bin/.old.php` ([source](https://github.com/omega8cc/boa/issues/801#issuecomment-228538725)).

**Comment by timlie** [comment]
Hi Ar-jan, thanks for your reply.
Will try this, this evening. As far as I can see that referenced issue is indeed what I experience on my server.

**Comment by omega8cc** [comment]
@ar-jan is right.
