### ISSUE TITLE
ERROR: This BARRACUDA version is outdated and will not work correctly

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1506]
Hi,

I have tried to upgrade the BOA system due to recent updates with the command: `barracuda up-head`
```
BOA [15:00:22] ==> Skynet Agent v.BOA-4.0.2-dev welcomes you aboard!

BOA [15:00:25] ==> INFO: UPGRADE

BOA [15:00:38] ==> VIRT: This system is supported: Linux KVM guest

BOA [15:00:39] ==> Aegir on Debian/stretch x86_64 PHP 7.3

BOA [15:00:47] ==> ERROR: This BARRACUDA version is outdated and will not work correctly
BOA [15:00:47] ==> Bye
```

BOA INFO
https://gist.github.com/lexsoft00/f5dc7234bb43736d0b8713d3dfa47917

**Comment by omega8cc** [comment]
You have an old installer, not updated for some reason. If it was powered off system or cron disabled or auto-updates disabled, you need to run this first: https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt#L10

**Comment by lexsoft00** [comment]
Thank you, it worked!
