### ISSUE TITLE
Crontab file keeps growing

### ISSUE THREAD

**Issue by egoosmann** [omega8cc/boa#1507]
We are experiencing a growing crontab our servers which have been deployed before friday july 10th. 

All these servers have auto-updates enabled. We have read your twitter post on which said the following:

```
If you manage your own #BOA #Aegir #Drupal system as root, you need to run this command to unlock system cron auto-updates and tasks (it’s a onetime fix):

sed -i "s/.*mysql_.*//gi" /etc/crontab

There was a bug in the auto-update which managed to lock itself and needs this fix.
```
https://twitter.com/omega8cc/status/1282105646436036609

We have run the specified command, but we are still seeing the below lines added every few minutes.

```
# Barracuda weekly system only upgrade
11 0    * * 1   root    /opt/local/bin/barracuda up-head system
14 0    * * 1   root    /opt/local/bin/barracuda up-head system
# Barracuda head full upgrade
05 0  1 1 *   root    /opt/local/bin/barracuda up-head log
08 0  1 1 *   root    /opt/local/bin/barracuda up-head log
# Octopus head full upgrade
05 5  1 1 *   root    /opt/local/bin/octopus up-head all force log
# Barracuda weekly system only upgrade
11 0    * * 1   root    /opt/local/bin/barracuda up-head system
14 0    * * 1   root    /opt/local/bin/barracuda up-head system
# Barracuda head full upgrade
```

Note that the server which was deployed on friday july 10th was not affected by this and has a clean crontab file.

Here is a gist with our server info: https://gist.github.com/egoosmann/f8bca1dd54644cb999e54da540982eec

**Comment by omega8cc** [comment]
Thanks for the report, now you will need to run on each server this command to get it finally fixed:

`bash /var/xdrago/clear.sh`

**Comment by egoosmann** [comment]
Thanks @omega8cc!
