### ISSUE TITLE
NginX killed

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#1508]
I'm on BOA 3.2.2, today Nginx stopped (killed) and the only way to make it run again is by rebooting the server.
Unfortunately after 25 minutes the service killed again. And so on...

I runned daily.sh manually but at the end the script failed to start NginX too.

Any idea?

Is it possible to upgrade to BOA 4 if NginX is down? I think wget not work too.

Thank you in advance for your help

**Comment by velpan** [comment]
service nginx status
[warn] Nginx Server... found running with processes: 24243 24242 24241 24240 24238 12052 ... (warning).
what is this message meaning?

**Comment by omega8cc** [comment]
We no longer support old versions, unfortunately. You need to find the real culprit behind this problem. Check the nginx error log, try to disable cron and see what happens, but you should absolutely upgrade to HEAD as soon as possible.

**Comment by velpan** [comment]
thank you for your answer. By stopping the cron the nginx is still alive for more than an hour now. 
I want to upgrade from 3.2.2 to BOA 4.0.1 stable. Is there a reason you write to upgrade to HEAD?

**Comment by omega8cc** [comment]
Stable is outdated and over one year old, only head should be used until new stable is out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
