### ISSUE TITLE
Enabling repo activity monitoring in Slack

### ISSUE THREAD

**Issue by Anoesj** [omega8cc/boa#1511]
I'd like to set up a Slack integration, that notifies our company in Slack whenever there's activity on this repository. I can only do so, if you have the Slack GitHub app installed and enabled for this repo. Are you willing to do so?

More information here: 
- https://slack.github.com/
- https://github.com/integrations/slack

Enable here: https://github.com/apps/slack/installations/new

Thank you!

**Comment by omega8cc** [comment]
We have enabled Slack integration, however can’t verify if it works if you don’t control the repo. But you can try. Let us know!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Anoesj** [comment]
It seems to work now, thank you!

**Comment by omega8cc** [comment]
Good to know, thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
