### ISSUE TITLE
Error COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#1512]
Trying to migrate site from Drupal 7.37 to Drupal 7.72 and I get the error:

exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8''

Aegir 7.x-3.x creates new settings.php with

  $databases['default']['default'] = array(
    'driver' => "mysql",
    ...
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_general_ci',
   );

Migration continues but ends with a failure and leaves both site folders (old and new) untouched in both platforms.
The site remains in 7.37 platform but now produces an HTTP ERROR 500

Verifying site produces same error.

I tried to overcome the error by putting in local settings.php 

$database['default']['default']['charset'] = 'utf8';
$database['default']['default']['collation'] = 'utf8_general_ci';

with no results.

Is there a way to get out of this situation?

**Comment by omega8cc** [comment]
You are skipping too many core releases in a single upgrade. Please upgrade both barracuda and octopus to head (forced mode), re-verify the original site, remove the ghost site copy in the target platform if exist manually and then try again. If this doesn’t help, you may have to manually edit hostmaster database to attach the existing site to its correct platform if hostmaster points to wrong platform.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Closing old tickets related to issues fixed already. Feel free to reopen if something is still relevant. Thank you!
