### ISSUE TITLE
Clean installation failed for BOA-4.1.1-dev

### ISSUE THREAD

**Issue by egoosmann** [omega8cc/boa#1516]
Hello,

Last night we tried to setup a VPS with a clean installation of BOA. We had several backups of the server, so we rebuilt it with a clean Debian 9.12 x64 image.

We followed the INSTALL.txt in the docs as usual (getting and executing the BOA Meta Installer) and executed the Barracuda and Octopus installer with the following command:

`boa in-head public [OUR_FQDN] [OUR_EMAIL] o1 none php-7.3 mariadb`

After waiting for a couple of minutes, we got some errors like "AegirSetupM installer failed" and a failed drush download (see https://imgur.com/a/SlsUwfH for the errors. Unfortunately we do not have a text copy of the image).

We tried several things like:
- Running the installer again, but the installer quit after a couple of seconds, because of a missing "_EASY_HOSTNAME" and "_EASY_PUBLIC" variable in the .barracuda.cnf (even after adding it manually to see what will happen, it still give errors about the missing variables)
- Running "barracuda up-head" to see if it will/do fix the missing drush or something, but it threw the same errors as the previous point
- A complete reinstall with php-7.2 instead of php-7.3, but that didn't change anything.

On wednesday 29th of July we did exactly the same on a different VPS (and on 4 other server before the 29th) and it was working perfectly.

Is there a possibility that something has been changed since July 29th and is causing a problem with initial installations? And what can we do to fix/bypass this error?

Thanks a lot!

**Comment by omega8cc** [comment]
We have just tested this with `php-7.3 mariadb` on Linode and Digital Ocean, both Debian Stretch, and we couldn't reproduce the problem. Perhaps it's something specific to your host?

You can debug this further if you run the boa installer after adding control file:

`touch /root/.debug-barracuda-installer.cnf`

Then grab details and post as Gist:

`cat /var/backups/barracuda-install-*.log`

**Comment by egoosmann** [comment]
Thank you for your reply and the procedure to debug this!

I forgot to tell you that we use Digital Ocean as well.

My colleague created a new VPS with the same command and said that everything works fine. So it's probably a temporary issue (like a failed download), or some specific issue with the base image of the server (if that's even possible).

While I'm writing this comment I thought about the firewall (in Digital Ocean) that is active on the server. Could that be a problem when I try to install BOA? The firewall only allows incoming HTTP(S) requests on port 80 and 443 from all IP addresses and only our own IP address for incoming SSH requests.

**Comment by omega8cc** [comment]
You should allow BOA to maintain its own firewall and avoid firewall maintained by your host, or you need to familiarize yourself with firewall rules BOA is expecting to work, ports open etc. The main BOA readme explains the basic requirements: The outgoing TCP connections via ports: 25, 53, 80 and 443 must be open.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
If you need any custom firewall restrictions outside of BOA own firewall, at least don’t enable the firewall before the initial installation and required initial upgrade is complete.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by egoosmann** [comment]
Thank you for the explanation!

I did not mention (sorry!) that we do not block any outgoing TCP connections:

**Type | Protocol | Port Range | Destinations**  
ICMP | ICMP |   | All IPv4 All IPv6
All TCP | TCP | All ports | All IPv4 All IPv6
All UDP | UDP | All ports | All IPv4 All IPv6

Like you said, I think it's worth a try when the firewall is completely turned off during installation.

Thank you for the support so far! We will let you know if it solves our problem.

**Comment by egoosmann** [comment]
After some testing and debugging (without a firewall as well), we have explained our situation to Digital Ocean and asked them if they might have an idea of what is happening.

Their answer was:

"_I found that both of your older Droplets were initially created with a Debian 7 image and are indeed quite old. Though you're attempting to rebuild it with a newer base image, in very rare occurrence we've seen some odd issues with Droplets rebuild in this fashion._"

Unfortunately we are still not sure about the underlying problem, but it looks like it has something to do with this, because a clean installation on a new droplet seems to work fine and a clean installation on the same server image on an older droplet seems to fail.

It does not seems to be a BOA related issue I think.
