### ISSUE TITLE
Upgrading from HEAD to STABLE?

### ISSUE THREAD

**Issue by gmeans** [omega8cc/boa#1517]
Hello!

I've just completed a clean install using 4.1.1-dev per the current recommendation since stable is a bit out of date. I'm assuming stable will eventually catch up and I was wondering how I should handle upgrading?

- Should I wait until a 4.1.1-stable is released (or later version) and then use `barracuda up-stable`?

- Or now that the server is using the HEAD version should I stick with `barracuda up-head`?

Thanks!

**Comment by omega8cc** [comment]
Currently `barracuda up-head == barracuda up-stable` and the fast moving and breaking commits happen only in `barracuda up-dev`
