### ISSUE TITLE
Nginx custom rewrites documentation points to broken links

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1518]
This line https://github.com/omega8cc/boa/blob/0960f23318d1a76aeb746d50ae5dc73419dc827d/docs/HINTS.txt#L23
points to broken links.

The `nginx_modern_include` exists no more. https://github.com/omega8cc/boa/blob/master/aegir/conf/nginx_compact_include.conf exists however.

**Comment by omega8cc** [comment]
Fixed, thanks.
