### ISSUE TITLE
barracuda up-head unable to resolve debian mirror redirect? for 2 days now ...

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1520]
Hello we have a test vps in australia, for which a barracuda up-head hangs at:

BOA [14:21:53] ==> INFO: Updating packages sources list...
BOA [14:21:53] ==> INFO: We will use Debian mirror httpredir.debian.org

This problem has persisted for 2 days now.

When I open another terminal window (I run the up-head on a screen session and see the tail), and issue the command "ps -a", say 2 or 3 hours after starting the upgrade, I get:

 Barracuda System managed by Skynet Agent v.BOA-4.1.1-dev welcomes you aboard

server1:~# ps -a
  PID TTY          TIME CMD
 3279 pts/2    00:00:00 ps
 7455 pts/0    00:00:00 screen
 7835 pts/1    00:00:00 barracuda
12583 pts/1    00:00:00 bash
17134 pts/1    00:00:01 apt-get
17137 pts/1    00:00:00 http
17138 pts/1    00:00:00 http
17139 pts/1    00:00:00 http
17140 pts/1    00:00:00 http
17141 pts/1    00:00:00 http
17156 pts/1    00:00:00 gpgv
17221 pts/1    00:00:05 store
server1:~#

Ed

**Comment by EdNett** [comment]
Hello,  This problem still exists, and nothing is being written to the logs except:


BOA [04:21:50] ==> Skynet Agent v.BOA-4.1.1-dev welcomes you aboard!

BOA [04:21:53] ==> INFO: UPGRADE

BOA [04:22:02] ==> VIRT: This system is supported: Linux KVM guest

BOA [04:22:03] ==> Aegir on server1.fastdrupalhost.com Debian/stretch x86_64 PHP 7.4

BOA [04:22:03] ==> INFO: Updating packages sources list...
BOA [04:22:03] ==> INFO: We will use Debian mirror httpredir.debian.org
~

althogh it isn't necessary, I will provide boa infor more here:
https://gist.github.com/EdNett/ca8977419efc2db54e5a19e222c0a3f8

best regards,

Ed

**Comment by reswild** [comment]
I have been running updates on several of my servers this week, and I haven't noticed any problems when running barracuda up-head.

You could always try to specify a different Debian mirror in barracuda.cnf instead of httpredir.debian.org.

**Comment by EdNett** [comment]
Thank you so much for pointing this out to me. I hadn't even realized that I could set the mirror in the barracuda .cnf file!

Best regards,

Ed
