### ISSUE TITLE
Thunder latest distro needs more than 2 GB RAM for Composer Resolver to function. How to Increase? and Request default of 3 GB instead of 2 GB.

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1521]
Thunder latest distro needs more than 2 GB RAM for Composer Resolver to function. How to Increase? and Request default of 3 GB instead of 2 GB.

Gives out of memory - memory exhausted fatal error:

Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Boa info more here:
https://gist.github.com/EdNett/48b64d301870779d29a2e33248aa9d7d

**Comment by reswild** [comment]
You should be able to allow more memory for Composer using an environment variable:
`export COMPOSER_MEMORY_LIMIT=3G`

**Comment by EdNett** [comment]
Hello, Thanks for that idea. I have already tried similar things that also haven't worked.   I might not be using that command correctly, however. Does it need to be set for the octopus instance, only the root, of for each platform (distro) that needs the memory increased? That is to say, do I need to do what you suggested in a particular directory? Which one?  I have tried all the permutations, and none of them work for me. Thanks for any more ideas.

**Comment by reswild** [comment]
I'm not really sure where's the best place to define this. You could try setting it globally by adding `COMPOSER_MEMORY_LIMIT=3G` to `/etc/environment`

**Comment by omega8cc** [comment]
You need VPS with more RAM, since BOA will not allow to grant all RAM available to PHP. That's the reality with Composer, unfortunately.

**Comment by EdNett** [comment]
open social problems with composer 2:
https://www.drupal.org/project/social/issues/3197017#comment-13993172

**Comment by omega8cc** [comment]
This should be no longer an issues with Composer 2.
