### ISSUE TITLE
Reinstalling the platform(s)

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1523]
I wanted to delete all platforms and force octopus to deploy new ones but it refused.

Is there a way to force it or to reinstall just one platform?

```
root@boa 17:39:07 # octopus up-stable o1 platforms 
load is 4 while maxload is 600
Octopus upgrade for User /data/disk/o1

This Aegir Instance o1 is already up to date!
If you wish to run/force the upgrade again,
please use the forced upgrade mode, as shown below

Usage: octopus up-stable o1 force


This Aegir Instance is already up to date!
If you wish to run/force the upgrade again,
please specify desired upgrade mode:
aegir, platforms or both - as shown below

Usage: octopus up-stable o1 {aegir|platforms|both}

Done for /data/disk/o1

OCTOPUS upgrade completed
Bye
```

**Comment by EdNett** [comment]
Hello,  We have the same problem, (and after up-stable to 4.1.3 the D7 platforms did not install properly - the same error as before) - should I re-open  https://github.com/omega8cc/boa/issues/1522 ?

Best regards,

Ed

**Comment by omega8cc** [comment]
Ouch! Now fixed both the forced upgrade mode and synced correct archives to mirrors.

You can force new platforms being added by switching these two lines in `/root/.o1.octopus.cnf`

```
_HOT_SAUCE=YES
_USE_CURRENT=NO
```
