### ISSUE TITLE
Automatically created MyQuick.info

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1525]
Hi,

This is my boa info output:

https://gist.github.com/timlie/a40b6bb8d11ba724323bfd548aa63102

As I can read here:

https://github.com/omega8cc/boa/blob/master/aegir/tools/system/conf/control-readme.txt

we can use the MyQuick.info file to have super fast migration and cloning for our sites, this at the cost of not having database backups anymore in the aegir backups archive and no restore functionality in Aegir for the site.

I noticed that my backups where much smaller since a couple of days. I noticed that the MyQuick.info file is already created by BOA. Is this intended? 
Because I have to adapt my backup strategy to this I wanted to remove the file to go to normal behaviour at the moment, but the MyQuick.info file is created again automatically...

Thanks!

**Comment by omega8cc** [comment]
Oh, that wasn't intended. Just stopped adding it by default.

**Comment by omega8cc** [comment]
That said, system backups will use the new fast mode anyway, only Aegir will not if you delete `MyQuick.info` -- we could perhaps add a switch for it?

**Comment by timlie** [comment]
Thanks, is fixed now.

**Comment by timlie** [comment]
Just to let you know, the myquick.info file is regenerated every day. After manually removing, it's back the next day.

**Comment by timlie** [comment]
Is fixed now. Thanks!

**Comment by hodbakhalaf** [comment]
Hello @omega8cc ,

I am facing the same issue on 4.1.3

The MyQuick.info file is automatically created. My installation is a regular one with no custom modifications. I managed to do a workaround by creating a cron to delete the file, but this is not a permanent solution. Any advice?
