### ISSUE TITLE
Composer 2 seems to solve insane memory issues

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1528]
In relation to #1521 and the text published by Gabor Hojtsy [Testing Composer 2 RC1 with Drupal 9: huge memory and time savings; and what does it mean for Drupal](http://hojtsy.hu/blog/2020-sep-28/testing-composer-2-rc1-drupal-9-huge-memory-and-time-savings-and-what-does-it-mean) and the fact that [Drupal 8 and 9 core were already made compatible with Composer 2 back in May](https://www.drupal.org/project/drupal/issues/3126566) it seems that new Composer 2 may be included and used?

**Comment by Amstercad** [comment]
Thumbs up to this idea. Not long ago I had to start paying more to double the RAM for BOA, just to run 'composer up'.

**Comment by 7o7o** [comment]
+1 for this. I cant do a composer require with a couple of modules, even if i set 8 GB of Ram, 6 GB of PHP memory limit, and give 4 GB of swap memory: 
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=4096
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

I'm using PHP 7.2 with MariaDB 10.2. I tried to update to composer 2 with root but that has a lot of dependencies issues. Is there a way to set composer 2 or will BOA add it on a near future? If composer 2 solves this memory issues as tests show it would be great if it can be added.

**Comment by EdNett** [comment]
I agree that we should move to composer 2 if possible. We need a min of 4 + GB Ram now for even the simplest of composer managed sites, and 6 GB + for anything even slightly complicated...

Ed

**Comment by EdNett** [comment]
Composer 2 (which I just got with a boa stable install) doesn't allow install or update of the new open social default of 10.0.0 (which seems to be incompatible with boa) to the latest version of 8.9.8 which is what I need.  Is there a way to have two version of composer installed and call whichever one is needed?  Can anyone install a static platform of social 9 - any version with current stable? 

See social issue:
https://www.drupal.org/project/social/issues/3197017#comment-13993172

**Comment by omega8cc** [comment]
This has been done already. Please report any other issues separately. Thank you.
