### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#1532]
Upgrading a previously migrated server I have the following issues:

BOA [04:30:31] ==> INFO: Installing extra Drush versions...
BOA [04:30:32] ==> INFO: Drush 9.7.2 already installed
BOA [04:30:38] ==> INFO: Drush 9.7.2 setup complete
BOA [04:30:38] ==> INFO: Running system packages update...
BOA [04:31:13] ==> INFO: Upgrading required libraries and tools...
BOA [04:31:38] ==> WARN: SQL upgrade to 5.7 from 10.1.45 not supported
BOA [04:31:38] ==> HINT: You can upgrade to 5.7 only from 10.2
BOA [04:31:38] ==> INFO: Running aptitude full-upgrade...
BOA [04:32:02] ==> INFO: Installed MyQuick line for not (10.1.45), rebuild required
BOA [04:32:02] ==> INFO: Building MyQuick 0.10.1 from sources, please wait...

BOA [04:32:19] ==> INFO: Aegir Master Instance upgrade skipped
cp: cannot create regular file '/etc/nginx/mime.types': No such file or directory
BOA [04:32:22] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...
BOA [04:33:28] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...

**Comment by MetaBureau** [comment]
modified .barrcuda.cnf with _FULL_FORCE_REINSTALL=YES .
Progress is great but then :
BOA [05:17:29] ==> INFO: Installing Redis update for Debian/stretch...

BOA [05:18:56] ==> INFO: Aegir Master Instance upgrade skipped
BOA [05:18:57] ==> INFO: Building Pure-FTPd server from sources, please wait...
BOA [05:19:29] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...
BOA [05:20:35] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...
BOA [05:21:41] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...
BOA [05:22:46] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...
BOA [05:23:52] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...

**Comment by MetaBureau** [comment]
Switched my barracuda.cnf from Percona 5.7 to mariaDB 10.2 ... seems to have resolved the issue.

**Comment by MetaBureau** [comment]
no sites loading ... switched barracuda config back to Percona 5.7 which has triggered reinstall

**Comment by luxio** [comment]
@MetaBureau I'm having the same issue (`BOA [08:00:09] ==> UPGRADE B: FATAL ERROR: Required file does not exist:`). How did you solve it?

**Comment by omega8cc** [comment]
Remember, contributions to this repository should follow its contributing guidelines: https://github.com/omega8cc/boa/blob/83a5efc83ff042d178be064e57f5c38d1ee619e4/CONTRIBUTING.txt
