### ISSUE TITLE
high server load on clean BOA 4.1.3 / Aegir down

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1533]
Hi all,

I installed current BOA 4.1.3 on a new Digital Ocean droplet 4GB / 2 CPU's (same as I have used before for several years with no problems)

Today the Aegir site (and other sites) went down with HTTP error 500. The server load seems consistently high (over 2) and spiked at over 30 earlier today = 

https://i.imgur.com/T1HHU1E.jpg

The only thing I could see in the error log was this (repeated many times)

```
angel:/var/log/php# ls
fpm-o1-slow.log     fpm-www73-slow.log   php73-fpm-error.log
fpm-www72-slow.log  php72-fpm-error.log
angel:/var/log/php# cat php73-fpm-error.log
[08-Oct-2020 10:11:52] WARNING: [pool o1] child 27782, script '/data/disk/o1/static/platforms/897-071020/index.php' (request: "POST /index.php?id=2&op=do_nojs&op=do&_format=json") executing too slow (63.230401 sec), logging
[09-Oct-2020 11:49:12] WARNING: [pool o1] server reached max_children setting (96), consider raising it
[09-Oct-2020 11:50:13] WARNING: [pool o1] child 10941, script '/data/disk/o1/static/platforms/773-071020/index.php' (request: "GET /index.php") executing too slow (60.743424 sec), logging

```

Aegir and other sites are currently loading but I am concerned they will go down again.

I don't understand it because it is clean BOA (nothing else installed) / same Digital Ocean  droplet resources I have used before / low website traffic. Any ideas please for troubleshooting?

 boa info = https://pastebin.com/3vspStwr

**Comment by Juc1** [comment]
PS I checked with Digital Ocean but as I expected they referred me to my application. Load average is currently over 6...

**Comment by 7o7o** [comment]
Hey Juc1. I have a similar setup and i dont have the problem you have. I even use 1 CPU and 2 GB of RAM at Digital Ocean and Aegir still works. 
The differences i have with your setup is that i still use PHP 7.2 in conjunction with MariaDB as DB_SERVER with version 10.2. Maybe you can try with that setup if PHP 7.3 is not a requirement to see if the problem goes away.

**Comment by Juc1** [comment]
@7o7o thanks for your reply. The high server load problem seemed to resolve after about 24 hours in which time Aegir and all sites went down twice. All I had done in Aegir was create one platform and two sites ie nothing unusual. I can only guess that there was a problem on the DO end even though DO support told me there was no problem. I have used DO for a few years and never had this problem before. Anyway I will be watching the metrics agent stats carefully in the DO UI.

**Comment by Juc1** [comment]
@7o7o or anyone else using DO + BOA if you are interested in a quick chat about using DO + BOA please hit me up on my profile.
