### ISSUE TITLE
low priority info -- today boa install loops with 'Retrieving 8507EFA5 key.. gpg: WARNING: nothing exported'

### ISSUE THREAD

**Issue by mysty** [omega8cc/boa#1536]
Hello, 

been years since I've installed boa - wow, it's come so far! Delighted to be working with it again

Yesterday test install went fine (aside from no packages installed) using 
`boa in-stable public boa-f.q.d.n email@address o1`
However today, having reset the host and starting completely afresh (with same confirmed working DNS wildcarding, etc), am getting endless loop of: 

```
BOA [11:33:20] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
BOA [11:33:24] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
```
.. repeating on and on ..

Current server load avg 0.15 0.10 0.21 so it's definitely not proceeding with boa installation ;)

Thanks for this amazing project and will update this if I can get around this

**Comment by keramsey** [comment]
I am new to BOA but not Aegir. I am running into infinite loops trying to install Percona as reported here. Is there an older revision available in github besides master that will not encounter the Percona key errors?

I am looking forward to using BOA once I get it installed. Thanks for any assistance you can provide, 

Here are my errors:
BOA [19:13:18] ==> INFO: Installing extra Drush versions...
BOA [19:13:24] ==> INFO: Running system packages update...
BOA [19:13:42] ==> INFO: Installing required libraries and tools, please wait...
BOA [19:14:03] ==> INFO: Installing Percona...
BOA [19:14:07] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported

As mysty reported the last 2 lines repeat indefinitely.

**Comment by mysty** [comment]
this is resolved, install completes fine now

**Comment by dserrato** [comment]
I've been trying to install a new server on our organization's system this whole week and the install hangs for hours at the line
`INFO: Installing required libraries and tools, please wait...`

I have tried adjusting settings and new Debian installs, etc. to no avail. 

To test away from our systems, I tried it on a local virtual machine and then a Digital Ocean droplet this morning. In both instances I am getting the same loop as the previous posts:
BOA [20:35:41] ==> INFO: Installing Percona...
BOA [20:35:59] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported

Hoping to find out if there is some setting that needs to be adjusted or something. I've installed and used BOA for years and have not encountered this kind of install issue. 
Thanks for any insight that anyone might be able to provide.

**Comment by bitf1ipper** [comment]
This is a new issue related to deprecation of sks-keyservers.net.
