### ISSUE TITLE
Removing services not listed in `.barracuda.cnf` anymore like webmin, collectd, jetty9, bind9

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1538]
I had previously configured these services to be included with my installation: `webmin, collectd, jetty9, bind9` but found that I do not need them anymore.

What would be the procedure to remove them?

Is it ok to do this for each of the services:

```
service cron stop           # stop the cron
service stop webmin         # stop the service
update-rc.d webmin remove   # remove the service
service cron start
```

**Comment by omega8cc** [comment]
Yes, it's OK to remove the no longer used service manually like this. Just remember about removing their keywords from the barracuda config too.
