### ISSUE TITLE
Extremely slow performance for logged in users

### ISSUE THREAD

**Issue by kaszarobert** [omega8cc/boa#1542]
Drupal 8 sites' speed is okay with page_cache for anonymous users. But if someone logs in, the performance of the sites drops hugely. Logged in users are experiencing 5-7 seconds of average page loads even when the Dynamic Page Cache and Redis modules are enabled. On localhost, in a non BOA development environment, the same pages are loading under a fraction of a second (With the same amount of content in the database - we imported the database dump from the production server where the slowdowns occur).

Please give us a few tips on how could we investigate what is causing this major bottleneck.

boa info output:
https://gist.github.com/kaszarobert/ad03fc351ebc1f002da37da3ba23e630

**Comment by omega8cc** [comment]
I know it's an old issue, but I would start with php slow logs in the `/var/log/php` and then find if you have a problem with host blocking access to itself. Drupal depends on the ability to contact itself via web requests and some hosts block this kind of loop-access.
