### ISSUE TITLE
Delete site task destroyed wrong database!

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1543]
Hi all

This issue is now fixed by restoring a back up of the production site but I post it here for the record and out of curiosity about how this can happen.

My production site is example.com. I cloned this to 211020.example.com. A few days later I was finished with the clone and ran the delete site task on 211020.example.com 

My production site example.com immediately went down. 

After the delete 211020.example.com task I can see that the database for example.com did not exist (and I got "user cannot connect to db" errors)

Reviewing the task notes I can see that the clone example.com task correctly created a database suitably named for 211020.example.com

But the delete 211020.example.com task a few days later repeatedly refers to the database for example.com ie the wrong database

The site example.com remained in the Aegir UI with the correctly named (but destroyed) database and in /data/disk/o1/config/server_master/nginx/vhost.d

Therefore it seems that the delete site task for 211020.example.com destroyed the database for example.com

This server was only a couple of weeks old and I did nothing unusual just run a few tasks add platform / add site etc

temple:~# boa info

Aegir BOA-4.1.3 on Debian/stretch x86_64
  VPS Linux KVM guest
  DSK 14/100
  CPU 2
  RAM 3955
  NGX 1.19.2
  PHP 7.3.23
  DBV 5.7.31
  RDS 6.0.8
  SSH 7.4p1
  SSL 1.1.0l
  CRL 7.52.1
  STG _STRONG_PASSWORDS=NO
  CSF _CUSTOM_CONFIG_CSF=NO
  LSH _CUSTOM_CONFIG_LSHELL=NO
  RIS _CUSTOM_CONFIG_REDIS=NO
  SQL _CUSTOM_CONFIG_SQL=NO
  XTR _XTRAS_LIST="ADM CSF FTP CSS"
  MFX _MODULES_FIX=YES
  PFX _PERMISSIONS_FIX=YES
  DNS _DNS_SETUP_TEST=YES
  PKG _EXTRA_PACKAGES=
  CLI _PHP_CLI_VERSION=7.3
  DBS _DB_SERIES=5.7
  TUN _USE_MYSQLTUNER=YES
  BIN _STRICT_BIN_PERMISSIONS=YES
  ARM _SSH_ARMOUR=NO

Fri Oct 16 12:09:04 UTC 2020 / Debian.stretch x86_64 Linux KVM guest / Aegir BOA-4.1.3 / Barracuda BOA-4.1.3 / Nginx 1.19.2 / PHP-MI 7.3 7.2 / PHP-SE / FPM 7.3                                                                                                                                                              / CLI 7.3 / Percona-5.7.31 localhost

**Comment by reswild** [comment]
I've been having similar issues when migrating sites: The newly migrated site is left referring to the old database (which at this point no longer exist) instead of the new migrated database, making the site inaccessible. I've found that running Verify Site solves the problem, so I suspect that the cause of the problem is that Verify Site runs before the migration or cloning is finished.

**Comment by pricejn2** [comment]
I ran into a similar issue where the wrong database was restored during a migration too. In my case, I believe it's related simultaneous migration tasks running (easy to dupe with .fast.cron.cnf enabled) and the fact that myquick appears to always dump dbs to `/data/disk/o1/backups/tmp_expim`.

**Comment by omega8cc** [comment]
We need to stop using the `tmp_expim` to avoid race conditions.

**Comment by EdNett** [comment]
Hello,

It seems to me that if we could fix this issue, then we could release a stable 4.2.0 that many could update to - and the other 6 release blockers could be put off to 4.2.x.  What do you think?  I'd still love to know if any (and all) updates at this point - i.e. to head of 4.1.3 stable only give composer 2?

Best regards,

Ed
