### ISSUE TITLE
Install not working - can reach master, not octopus site, ? possible percona problem?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1545]
Hello,  We are unable to login after re-starting the server after the initial install. When we restart the server (following instructions to run "barracuda up-head system" to completely remove system D and complete installation of sysv-init on debian 9), we cannot re-login via ssh!

this is install command:
boa in-stable public server1.example.com info@example.com o1 none php-7.3

(we actually used our own "o1" name - not "o1")

Percona status gives: (is lack of IPv6 entry in /etc/hosts causing this?):

root@server1:~# service mysql status
● mysql.service - Percona Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-11-22 12:38:02 CET; 18min ago
 Main PID: 29315 (mysqld)
    Tasks: 157 (limit: 4915)
   CGroup: /system.slice/mysql.service
           └─29315 /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.521567Z 0 [Note]
Skipping generation of SSL certificates as certificate files are present in data directory.
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.525009Z 0 [Warnin
g] CA certificate ca.pem is self signed.
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.525835Z 0 [Note]
Skipping generation of RSA key pair as key files are present in data directory.
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.526330Z 0 [Note]
Server hostname (bind-address): '*'; port: 3306
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.526403Z 0 [Note]
IPv6 is available.
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.526430Z 0 [Note]
  - '::' resolves to '::';
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.526459Z 0 [Note]
Server socket created on IP: '::'.
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.545020Z 0 [Note]
Failed to start slave threads for channel ''
Nov 22 12:38:02 server1.example.com mysqld[29311]: 2020-11-22T11:38:02.568802Z 0 [Note]
Event Scheduler: Loaded 0 events
Nov 22 12:38:02 server1.example.com systemd[1]: Started Percona Server.

boa info more doesn't work: (neither does boa info):
root@server1:~# boa info more
bash: /usr/local/bin/boa: No such file or directory

Lastly, can we specify using MariaDB instead of Percona on initial install? How?

Thanks,

Ed

**Comment by EdNett** [comment]
Our vps provider had initially in the /etc/hosts file a line:

127.0.1.1  their-server-name

we changed this to 127.0.1.1 server1.example.com server1

but I saw that after the boa in-stable command, that line was erased. (probably by the boa install). Is that line necessary?

**Comment by EdNett** [comment]
the 127.0.0.1 localhost line , of course, still remains in /etc/hosts

**Comment by reswild** [comment]
To specify using MariaDB instead of Percona, just edit your .barracuda.cnf file and set `_DB_SERVER=MariaDB`. I doubt that Percona is your problem here though.

Whether you ought to keep the 127.0.1.1 entry in your /etc/hosts file is probably something you should ask your hosting provider about, but it's not usually needed.

**Comment by EdNett** [comment]
I meant on the initial install of course as regards MariaDB. Because we have re-installed debian 9 4 times and have had the same problem; I didn't want to start with a .barracuda.cnf file specifying mariaDB since that could be part of the problem.

I have verified with the server cloud company that there is no network firewall enabled, and that I have successfully modified the cloud-init system which would prevent writing to the /etc/hosts file.

My communications with them regarding cloud-init:
"
 We don't want to use your cloud-init, so after installing the server from one
of your images (we must use debian 9 for this application), I edit
/etc/cloud/cloud.config and I add the line:
manage_etc_hosts: false

and I modify the line:
disable_root: true to disable_root: false (so that root ssh login - which we need
- does work) (why does ssh root login work when this is set to true immediately
after installing from image?)

and I modify the line:
preserve_hostname: false to preserve_hostname: true

Is this all I need to do so that manual changes to /etc/hosts are saved and not
reverted with a reboot?

Furthermore, I add the IPv4 to /etc/hosts: (we don't use IPv6 for this
application):

valid.IP.v.4 server1.example.com server1
"

They confirmed that this was correct. What could the problem be with a boa stable install. It doesn't work even with Percona. Initial install doesn't work. Can anyone duplicate this?  Are we suppossed to be using head now, not stable for new installs?

Thanks 

Ed

**Comment by reswild** [comment]
You can use a .barracuda.cnf file to set options on the initial install too, although this feature seems poorly documented, so I'm not sure what's best practice here. If you want to run MariaDB you will need to specify `_DB_SERIES=10.2` (or whatever version you want to run) in addition to `_DB_SERVER=MariaDB`.

However, it sounds to me like your real problem is with cloud-init, which I guess doesn't play nicely with Boa. So my suggestion would be to start with fully uninstalling cloud-init from your system, and then manually configure your network in /etc/network/interfaces. Once you have a clean system, Boa should install fine with either Percona or MariaDB.

**Comment by EdNett** [comment]
@reswild I can't continue to respond to you - I don't have the time and your posts aren't helping. Thanks.  

I am hiping that someone from the BOA team can respond to this. For the third time, upon initial install (this time in-head), we can only login to the barracuda master instance. We are unable to login to the octopus instance. When we do what the screen message asks us to do (for either an in-stable or an in-head) - reboot and run a barracuda up-whatever system, we can never login again.

How could this be happening? Why would we be unable to login to the octopus instance (before the reboot, of course)? and why would a reboot cause login with accepted ssh key to fail? This time (for the first and only time) we added the IPv6 to the /etc/hosts file.

We noticed the same thing as before - after the barracuda install, the line in the /etc/hosts file:
127.0.1.1 server1.example.com server1
is missing. This must be the doing of the boa install.

We can't login, so I can"t give boa infor more (and anyuways, last time this failed 2 days ago, the boa info more command gave an error "not found" when tried BEFORE attempting reboot

I'd love to know if anyone else can successfully install either stable or head these days.

Best,

Ed

**Comment by EdNett** [comment]
UPDATE:

We have found old dns a record and ns record entries from the registrar, which conflict with ouir own nameserver entries, which might be causing this problem. We will wait until the registrar has deleted the old entries, and then try the install again 24 hours later and will report.

Ed

**Comment by EdNett** [comment]
Has anyone been able to install boa on a hetzner public cloud server/ vps?

**Comment by EdNett** [comment]
I'll close this due to inactivity
