### ISSUE TITLE
delete 8.9 site task fails with "Drush command terminated abnormally due to an unrecoverable error."

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1546]
Hi all

I am using vanilla BOA-4.1.3 

On more than one 4.1.3 server the delete 8.9 site task fails with "Drush command terminated abnormally due to an unrecoverable error." and no further info in the task log

Task log and $ boa info here https://pastebin.com/tyr38eMX

In December 2019 @omega8cc said
Drupal 8.8 is not yet fully tested and supported in Aegir...

https://github.com/omega8cc/boa/issues/1454#issuecomment-566635611_

Are there any task limitations with the current BOA 4.1.3 / drush re Drupal versions ?

Or any ideas please why my delete sites tasks are failing ?

**Comment by Juc1** [comment]
update on this - other tasks - create / clone / migrate etc work correctly

The delete site task is listed by Aegir as failed and the site node still exists in Aegir. But actually the site has been destroyed (database, /data/disk/o1/config/server_master/nginx/vhost.d etc) So the problem is that the task status is incorrect in Aegir. After running the delete site for a second time, the zombie site is removed from Aegir. This is not just one site but I think every site on three different BOA 4.3.1 servers.

Create site task log https://pastebin.com/5hrF1mNv
 
first delete site task log (failed) https://pastebin.com/9mUfVr83
 
second delete site task log (successful) https://pastebin.com/djURjQwe

**Comment by GValFr35** [comment]
Hi, this can be related to this issue reported on aegir provision:
[https://www.drupal.org/project/provision/issues/3187556](https://www.drupal.org/project/provision/issues/3187556)
