### ISSUE TITLE
Installation of BOA freezes after initial installation command

### ISSUE THREAD

**Issue by egoosmann** [omega8cc/boa#1548]
Hi,

While installing a fresh instance of BOA I encountered a weird hangup.

After the `boa in-stable` command the system just hangs and nothing is reported/updated during this time.

I decided to try and see if there were any logs in /var/backups, but it only contained the mirrors file. After checking all the links in that file, I saw that au.files.aegir.cc wasn't responding, which is causing the entire setup to hang. After removing the mirror from the file, the BOA installation works again!

**Comment by lexsoft00** [comment]
I have the same issue

The install is stuck on Drush

`
BOA [10:22:45] ==> INFO: Installing extra Drush versions...
BOA [10:22:46] ==> INFO: Drush 9.7.2 re-installation required
`
```
Aegir BOA-4.1.4-dev on Debian/stretch x86_64
  VPS Linux KVM guest
  DSK 6/100
  CPU 2
  RAM 3859
  NGX 1.19.2
  PHP 7.3.24
  DBV 5.7.32
  RDS 6.0.8
  SSH 7.4p1
  SSL 1.1.0l
  CRL 7.52.1
  STG _STRONG_PASSWORDS=NO
  CSF _CUSTOM_CONFIG_CSF=NO
  LSH _CUSTOM_CONFIG_LSHELL=NO
  RIS _CUSTOM_CONFIG_REDIS=NO
  SQL _CUSTOM_CONFIG_SQL=NO
  XTR _XTRAS_LIST="ADM CSF FTP CSS"
  MFX _MODULES_FIX=YES
  PFX _PERMISSIONS_FIX=YES
  DNS _DNS_SETUP_TEST=YES
  PKG _EXTRA_PACKAGES=
  CLI _PHP_CLI_VERSION=7.3
  DBS _DB_SERIES=5.7
  TUN _USE_MYSQLTUNER=YES
  BIN _STRICT_BIN_PERMISSIONS=YES
  ARM _SSH_ARMOUR=NO

Thu Dec 3 17:27:49 UTC 2020 / Debian.stretch x86_64 Linux KVM guest / Aegir HEAD / Barracuda BOA-4.1.4-dev / Nginx 1.19.2 / PHP-MI 7.3 7.2 / PHP-SE / FPM 7.3 / CLI 7.3 / Percona-5.7.32 localhost
```

**Comment by lexsoft00** [comment]
The issue is composer

You get prompted:


```
Changed current directory to /opt/tools/drush/9/drush
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
```

**Comment by mabo1972** [comment]
Have exactly the same problem here. After installing the BOA Head on a completely new Debian Stretch VM, a reboot was performed. Then as described in the instructions "barracuda up-head system" executed.
The system hangs at the point "Drush 9.7.2 re-installation required".

Does anyone know a solution here?

**Comment by lexsoft00** [comment]
You need to enable _DEBUG_MODE=YES in /root/.barracuda.cnf

Then you will see the prompt from the composer, after just type yes.
