### ISSUE TITLE
Installation of PHP 7.2 and 7.3 fails on AWS Lightsail Debian 9.5

### ISSUE THREAD

**Issue by meghead** [omega8cc/boa#1549]
Firstly here's the output of "boa info" -

Aegir BOA Cluster on Debian/stretch x86_64
  VPS Xen guest fully virtualized (HVM)
  DSK 14/100
  CPU 1
  RAM 490
  DBV not
  SSH 7.4p1
  SSL 1.1.0l
  CRL 7.52.1
  STG 
  CSF 
  LSH 
  RIS 
  SQL 
  XTR 
  MFX 
  PFX 
  DNS 
  PKG 

____________________________________________________________________________________

AWS Lightsail offers only Debian 9.5 Stretch version. 

Amazon normally only allows admin login - not root.  So I tried installing BOA in two ways - neither worked. 

1- logging into root via "sudo su -"
 
2. removing the following code from /root/.ssh/authorized_keys which prohibits root login 
"no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="
echo 'Please login as the user "admin" rather than the user "root".';
echo;sleep 10" 

Either way the BOA script fails at Php7.2 and 7.3 installations when using this command;

"boa in-stable public aegir.mysite.com myemail@gmail.com oct" 

Here's the failure;

BOA [11:29:11] ==> INFO: Building MyQuick 0.10.1 from sources, please wait...
BOA [11:29:30] ==> INFO: PHP 7.2.34 will be installed now
BOA [11:29:30] ==> INFO: Building PHP 7.2.34 from sources, please wait...
BOA [11:29:37] ==> INFO: Building PHP 7.2.34 part 1/3
BOA [11:29:41] ==> INFO: Building PHP 7.2.34 part 2/3
BOA [11:30:29] ==> INFO: Building PHP 7.2.34 part 3/3
BOA [11:34:45] ==> WARN: Building PHP 7.2.34 failed!
BOA [11:34:45] ==> INFO: PHP 7.3.24 will be installed now
BOA [11:34:45] ==> INFO: Building PHP 7.3.24 from sources, please wait...
BOA [11:34:53] ==> INFO: Building PHP 7.3.24 part 1/3
BOA [11:34:57] ==> INFO: Building PHP 7.3.24 part 2/3
BOA [11:35:50] ==> INFO: Building PHP 7.3.24 part 3/3

**Comment by omega8cc** [comment]
That's way too little RAM. Please check the BOA requirements.

**Comment by omega8cc** [comment]
Closing old tickets related to issues fixed already. Feel free to reopen if something is still relevant. Thank you!
