### ISSUE TITLE
can't install php mod mcrypt

### ISSUE THREAD

**Issue by tourtools** [omega8cc/boa#1551]
I need to implement an OTP generation for our customers Drupal login but I need the mcrypt php mod,

so I tried to install mcrypt through `_PHP_EXTRA_CONF="--with-mcrypt"` variable in .barracuda.cnf,
and launching `barracuda up-stable system` but nothing happens,

on the server we have multiple php installed, but only 5.6 has mcrypt installed by default (barracuda.sh), the other miss it:

```
###
_PHP_CLI_VERSION=7.4
_PHP_EXTRA_CONF="--with-mcrypt"
_PHP_FPM_DENY=""
_PHP_FPM_VERSION=7.4
_PHP_FPM_WORKERS=AUTO
_PHP_IONCUBE=NO
_PHP_GEOS=NO
_PHP_MONGODB=NO
_PHP_MULTI_INSTALL="7.4 7.3 7.2 5.6"
_PHP_SINGLE_INSTALL=
###
```

**Comment by omega8cc** [comment]
It's not supported as built-it extension since PHP 7.2, so 7.1 is the last version it still worked with `--with-mcrypt`

Now added as PECL extension.

**Comment by omega8cc** [comment]
Please note that you need to run BOA head.
