### ISSUE TITLE
Redis for Drupal 9

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1553]
Hi,

I migrated a dev site to test to Drupal 9 on BOA.
This worked very well. Only issue I encounter at the moment is the redis module added in o_contrib_eight
This version redis_eight (directory in o_contrib_eight) is not compatible with Drupal 9.
The version on github, https://github.com/omega8cc/redis (master 8.x-1.x) is compatible but apparantly not added.

Could you add it to o_contrib_eight directory?

My boa info command:

https://gist.github.com/timlie/ce8dde30f78fb5fd3ded5b7ac7d8d077

Thanks!

**Comment by timlie** [comment]
I can see there is a redis_compr version in o_contrib_eight, which supports Drupal9.
In boa/global.inc I see this directory will be set if there is a composer file:

https://github.com/omega8cc/boa/blob/master/aegir/conf/global.inc#L267

My custom platform uses composer, so the composer file is present but apparantly, the redis_compr module is not set but still the redis_eight version.

**Comment by timlie** [comment]
Ok, doublechecking, it checks for a composer directory not the file. Is checks for this directory in your web/docroot directory.
I don't have a composer directory in the web directory. Someone who can explain me the use of this folder?

**Comment by timlie** [comment]
In meanwhile to test I upgraded BOA to latest HEAD, yesterday.
Confirmed to install some "ready to use platforms" to force update the o_contrib_eight directory.
Installed the Thunder platform (D9) from BOA.

I installed a thunder site D9.
This site also can not enable the redis module because it is not compatible with D9.

Is there someone who has running D9 sites on BOA, with redis enabled?

Thanks!

**Comment by timlie** [comment]
Hi, want to pop this question up.
Is there someone using Redis for Drupal 9 on BOA?

**Comment by omega8cc** [comment]
This has been fixed in HEAD.
