### ISSUE TITLE
Query re stable or head for Feb 2021 - very General Question

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1554]
Hello,

Is there any important reason (security or performance ?) to move to head currently (Feb 7 2021)? (Will this be the only way to get composer 2?)?

I see the stable 4.1.3 is an "ongoing" kind of thing (i.e. there are outstanding issues, etc.). Is this what you mean by a rolling release?  Does this mean that we should occasionally do a barracuda up-stable to have fixes and added functionality in addition to updated versions of software and libraries?

Thanks for the heads up!

Best regards,

Ed

**Comment by EdNett** [comment]
And one more question - If stable is a rolling release, can we go backwards from a 4.1.4-dev to a 4.1.3-stable?  I jumped up to head and found that OpenSocial won't work with composer 2 (except for version 10.0.0 !) because of the unavailability of dependencies (composer-extenders ...)

**Comment by EdNett** [comment]
Hello,  I rebuilt the vps with stable just to get composer 1 so that I could install version 8.9.8 of open social, and I find that the stable now gives composer 2! This only allows building of social 10.0.0 - which is incompatible with boa.

Is there a way to call composer 1 from within boa and use it ?  From my point of view composer 2 completely breaks social.

See social issue:
https://www.drupal.org/project/social/issues/3197017#comment-13993172

**Comment by omega8cc** [comment]
Please check https://github.com/omega8cc/boa/commit/7fcc3f22937352e273c3e129bea75da8d9446bb0

As for composer, you can easily switch it to version you prefer, like this:

`/usr/local/bin/composer self-update --1`

or

`/usr/local/bin/composer self-update --2`


But on barracuda upgrade it will be switched back to Composer 2.
