### ISSUE TITLE
Logo for BOA project

### ISSUE THREAD

**Issue by theodorosploumis** [omega8cc/boa#1556]
After so many years of using this amazing product (which saved me a lot of money and time) I decided to start an effort to make it some more viable to the web development community. Because, I believe that **it has so many features and power that some competitors out there should be jealous of**.

In any case, in order to start this kind of "branding" the first thing I submit is a logo.

I used keywords like "aegir, sea, monster, master, sea, barracuda, octopus, paranoia, system" for inspiration and here are the results.

It would be helpful if the community of this project **selects the final logo** from the 5 suggestions bellow.

![g3001](https://user-images.githubusercontent.com/1315321/107714004-16b92b80-6cd5-11eb-88ce-053a81db593e.png)

For simplicity I will add each logo in it's own comment for like count.

**Comment by theodorosploumis** [comment]
![g2505](https://user-images.githubusercontent.com/1315321/107714114-5bdd5d80-6cd5-11eb-900e-ff476a904f92.png)

**Comment by theodorosploumis** [comment]
![g2483](https://user-images.githubusercontent.com/1315321/107714149-63046b80-6cd5-11eb-9a1d-db9ca5f3eb5f.png)

**Comment by theodorosploumis** [comment]
![g2465](https://user-images.githubusercontent.com/1315321/107714162-6a2b7980-6cd5-11eb-8011-6eea2a407dcb.png)

**Comment by theodorosploumis** [comment]
![g2450](https://user-images.githubusercontent.com/1315321/107714169-70b9f100-6cd5-11eb-9db2-cc9e3ea4151c.png)

**Comment by theodorosploumis** [comment]
![g2438](https://user-images.githubusercontent.com/1315321/107714185-77486880-6cd5-11eb-87c2-25532c485b11.png)

**Comment by omega8cc** [comment]
WOW! Thank you for this amazing contribution! All of them look fantastic, but the tribal stole my heart!

~Robert

**Comment by timlie** [comment]
+1 for tribal

**Comment by bserem** [comment]
Amazing work and very nice idea!

**Comment by sluc23** [comment]
mythology +1

**Comment by Amstercad** [comment]
mythology +1

**Comment by EdNett** [comment]
Personally I prefer the idea of a BOA Constrictor - that squeezes every last ounce of cpu and memory and disk I/O out of your server as well as restricting what you can do with the server ...
![boa_constrictor](https://user-images.githubusercontent.com/7894282/107918482-053c8180-6f6a-11eb-95cf-c13a82328752.jpg)

**Comment by omega8cc** [comment]
Thank you again for your fantastic contribution!
