### ISSUE TITLE
incorrect docroot in static platform composer.json file ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1558]
Hello,

We are running latest BOA stable and when we install a static platform in the composer.json file we always get something like:

 "drupal-scaffold": {
            "locations": {
                "web-root": "docroot/"

I believe the slash at the end of "docroot", or "web" or "html" is causing the modules and themes paths to have two consecutive slashes and producing errors. It doesn't matter whether the static platform is core-recommended D8, D9, Social or Thunder - they all put a trailing slash at that spot with a composer install. When combined with the below lines from the same composer.json file, the double slash is produced, I think.

           "docroot/modules/contrib/{$name}": ["type:drupal-module"],
            "docroot/profiles/contrib/{$name}": ["type:drupal-profile"],
            "docroot/themes/contrib/{$name}": ["type:drupal-theme"],

I believe that removing the trailing slash from the web-root and reverifying the platform and sites under it is the right thing to do for AEgir / BOA. Could somone please confirm this ?

**Comment by timlie** [comment]
How do you install your static platform?

I still use the classic "managed by you on SSH command line or SFTP" method followed by a composer install on the command line.

My composer files also have the trailing slash, like web/

I have no issues with modules or themes, only issue I have is the D9 version of Redis #1553

**Comment by EdNett** [comment]
Hi,  I always install D8 and D9 static platforms like this:

Deployment strategy:  Deploy a Composer project from a Git repository

That's how Thunder, Social, etc. are installed . I install my own d8 or d9 the same way with core-recommended as a composer project ...

I have noticed that for these composer projects in drupal 8 and 9, there are no modules in the /sites/all/modules and there are no contrib themes in the /sites/all/themes.

Do you have any added contrib modules or themes in those locations?  By adding the contrib module or theme to the docroot composer.json file, it won't put theme there. Is it the same for you?

Regards,

ed

**Comment by timlie** [comment]
Well, you quoted the composer locations for modules and themes in you first post in this topic. That's where modules and themes are placed with composer install.

**Comment by EdNett** [comment]
Closing this, since it works.
