### ISSUE TITLE
MariaDB or Percona update error: You can upgrade to 5.7 only from 10.2

### ISSUE THREAD

**Issue by lhaithaes** [omega8cc/boa#1559]
**On barracuda up-stable I got this error / warning. Which eventually fails and breaks the server. Luckily I have backups so I can try it again. Does anyone recognise this error? Do I have to mess around with the database settings before I try the upgrade again?** 

WARN: SQL upgrade to 5.7 from 10.1.44 not supported
BOA [11:03:42] ==> HINT: You can upgrade to 5.7 only from 10.2
E: Unable to locate package percona-release

**Then later..**

BOA [11:53:58] ==> INFO: Running Aegir Master Instance upgrade
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'aegir_root'@'localhost' IDENTIFIED BY 'Nr3Hsg2m4PcRRGvVfxo'' at line 1
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'aegir_root'@'localhost' IDENTIFIED BY 'Nr3Hsg2m4PcRRGvVfxo'' at line 1
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'masterserverpeak'@'localhost' IDENTIFIED BY '9uYK2a8nC6'' at line 1

Running hostmaster-migrate, please wait...
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'masterserverpeak'@'localhost' IDENTIFIED BY '9uYK2a8nC6'' at line 1

**And again on octopus**
 up-stable all both

server:~# octopus up-stable all both
load is 3 while maxload is 600
Octopus upgrade for User /data/disk/o1nf
Waiting 7 seconds...
 
BOA [12:11:19] ==> Skynet Agent v.BOA-4.1.3 welcomes you aboard!
 
BOA [12:11:23] ==> Octopus Satellite Instance Upgrade in progress...
 
BOA [12:11:24] ==> This Octopus URL address is o1.mydomain.com
BOA [12:11:24] ==> This Octopus PHP version is 7.2
BOA [12:11:24] ==> This Octopus System is Debian/jessie x86_64
 
BOA [12:11:32] ==> UPGRADE A: Shared platforms code v.003 (new) will be created
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'o1'@'localhost' IDENTIFIED BY 'a9AgsZjngpEpouCI6kG'' at line 1
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'o1'@'localhost' IDENTIFIED BY 'a9AgsZjngpEpouCI6kG'' at line 1
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'o1myuser_0'@'localhost' IDENTIFIED BY 'uQTCMjWqQH'' at line 1
BOA [12:11:47] ==> UPGRADE B: Downloading drush 8.4.5.1...
BOA [12:11:49] ==> UPGRADE B: Installing Aegir Provision backend...
BOA [12:11:49] ==> UPGRADE B: Downloading Drush and Provision extensions...
BOA [12:11:51] ==> UPGRADE B: Hostmaster STATUS: Upgrade in progress...
BOA [12:12:07] ==> UPGRADE B: Hostmaster STATUS: Upgrade completed
BOA [12:12:07] ==> UPGRADE B: FATAL ERROR: Required file does not exist:
BOA [12:12:07] ==> UPGRADE B: FATAL ERROR: /data/disk/o1/aegir/distro/003/sites/o1.mydomain.com/settings.php
BOA [12:12:07] ==> UPGRADE B: FATAL ERROR: Aborting AegirSetupB installer NOW!
BOA [12:12:07] ==> UPGRADE A: FATAL ERROR: AegirSetupB installer failed
BOA [12:12:07] ==> UPGRADE A: FATAL ERROR: Aborting AegirSetupA installer NOW!
BOA [12:12:07] ==> FATAL ERROR: AegirSetupA installer failed
BOA [12:12:07] ==> FATAL ERROR: Aborting Octopus installer NOW!
Waiting 6 seconds...
Done for /data/disk/o1

OCTOPUS upgrade completed
Bye

[https://gist.github.com/lhaithaes/d31b97f742627ece43909a4303d1922f](url) - AWS

**Comment by timlie** [comment]
Have you tried upgrading to 10.2 first?

**Comment by lhaithaes** [comment]
after a quick search. this is the new default. 

_DB_BINARY_LOG=NO #------------- Allows to enable binary logging when YES
_DB_SERIES=5.7 #---------------- Supported values: 5.7, 10.2, 10.3 or 10.4
_DB_SERVER=Percona #------------ Allows to install Percona or MariaDB server
_USE_MYSQLTUNER=YES #----------- Use MySQLTuner to configure SQL limits when YES

I perhaps have got Maria db and percona values mixed up when it failed last time. I wonder can you switch between Mariadb and percona ? after install

**Comment by timlie** [comment]
Yes, you can. I switched from mariadb 10.2 to percona 5.7 on a server.

**Comment by Amstercad** [comment]
You can upgrade to Percona 5.7 from MariaDB 10.2 only(!)

You can not upgrade to Percona 5.7 from MariaDB 10.1
You can not upgrade to Percona 5.7 from MariaDB 10.3
You can not upgrade to Percona 5.7 from MariaDB 10.4

You also can not downgrade to MariaDB 10.2 from MariaDB 10.3

**Comment by omega8cc** [comment]
Closing old tickets related to issues fixed already. Feel free to reopen if something is still relevant. Thank you!

Also: https://github.com/omega8cc/boa/blob/b41633c5db8bf87683594285f0583bf033cd506b/docs/FAQ.txt#L2
