### ISSUE TITLE
can not find PHP-CLI 

### ISSUE THREAD

**Issue by stevenwood** [omega8cc/boa#1567]
Hi Grace, I hope you are well, I used to use BOA a lot :), due to not being well I stopped about 4 years ago. Feeling much better now and getting back into the swing of things. 

I thought I would install a copy of BOA to host a few drupal sites. BOA has changed a bit, but I must be doing something wrong.

Following the INSTALL.txt  on a fresh copy of debian 9 on Digital Ocean, I run cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt 

I get a message and the screen clears. After rebooting I run barracuda up-stable and get: ERROR: I can not find PHP-CLI anywhere!

Just wondering if I need to give it more time after the screen clears. (i waited till my public inbound bandwidth dropped back down to nothing )

I have rerun cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt and get:

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs

I still get ERROR: I can not find PHP-CLI anywhere! when running  barracuda up-stable

**Comment by stevenwood** [comment]
lol.. Sorry grace.  my fault..
I had not run  boa in-stable public server.mydomain.org my@email o1 ... it's been a long time.

**Comment by omega8cc** [comment]
Please make sure to upgrade both barracuda and octopus to head, since "stable" is legacy mode at this moment.
