### ISSUE TITLE
Best practise for dealing with multiple composer versions

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1570]
On a clean boa-head install, what is the recommended method of handling multiple composer versions for sites that depend on different versions.

Thanks!

**Comment by omega8cc** [comment]
I know it's an old ticket, but we are moving fast with updates again, so adding this to the wishlist.

**Comment by omega8cc** [comment]
There are currently no plans to support multiple composer versions. If you need this, you will need to install the extra composer in some different path.
