### ISSUE TITLE
After recent head 4.1.4-DEV update (both B and O), after octopus up-head completes, all octopus tasks stop running. Tasks are frozen - ? permissions problem

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1571]
Hello,

We've tried updating both barracuda and octopus instances to current head (4.1.4 dev)  several times, and we get the same result.: After the octopus update, platforms are being verified, and a scheduled site backup occurs - that scheduled site backup completes successfully, but it stops all further tasks from running.  

UPDATE: It appears that each time we run the octopus up-head, that the task queue starts running again at a certain point, but that as soon as the octopus upgrade is finished, then the task queue freezes - so I'm not sure if it is the end of the upgrade that freezes the task queue (I now believe that it is this that triggers the task queue freeze - since I disabled all backups and disabled hosting queue manager, deleted all outstanding tasks in the queue, ran another octopus up-head, and the task queue froze with no backups having been completed), or whether it is the fact that the task queue usually freezes after one and only one backup has been successfully done ?  Counld this be a permissions problem? Have the permission for octopus tasks running from the GUI recently been modified?

For our D 7 static platform, cron stops running on all sites, too!

This has been occurring since our may 10 up-head, and reverting to php 7.3 on cli does not solve the problem.
We are using latest mariaDB 10.3.29

Boa info more  here:
https://gist.github.com/EdNett/29e2c4adec711ab64a618d15cb5a6fc8

What log can I check to get you the relevant error messages? Does this have something to do with MyQuick ? ctl files in static/control/MyQuick.info says: "ON" - by default I guess.

Some debug MyQuick entries in terminal during octopus up-head are here:
https://gist.github.com/EdNett/dcc1ada32f0f1929d112649657d2e3b1

Thanks for your help,

Additional NOTE: It looks like I could get the Octopus tasks to start running again if I disable "Backups sites by default" in the Octopus AEgir menu - Hosting -> Backup Manager - and then run the Octopus instance up-head. ( but it stopped running after the first site backup once again) [This is NEW. Previously I could leave that setting enabled and there would be no problem. ] What to do? Automatic site backups are important, and are a very much appreciated feature.  *** actually this only worked for a while, and on the D 7 platform, all tasks have stopped again and cron is not running for many sites. It did run for some sites, but not for all ?

Is only Percona supported now, and is that the fix - to move from MarisDB to Percona?

Best regards,

Ed

**Comment by EdNett** [comment]
Hello,

Well I just tried this up-head for both barracuda and octopus on a similar test server and it did NOT cause the same problem. I did update MaiaDB to 10.4.  I notice that there is no MyQuick.info file in either octopus' /static/control/ directory. I wonder how that file got into the /static/control/ directories of all the octopus instances on our production server.  I am going to try removing that file in all octopus instances, and running up-head again also upgrading MariaDB to 10.4 and see if that solves the problem.  (I tried changing the "ON" to "OFF"  in the MyQuick.info file on one octopus instance, but that didn't help.

**Comment by EdNett** [comment]
Hello,

I can't believe I'm the only one to have this problem with D7 platforms not running cron after an octopus up-head - has anyone done an oct up-head in the last 3 weeks and NOT had this problem?  

Also, I have found that if I do another optopus up-head and when the process gets to this point:

BOA [19:56:59] ==> UPGRADE A: Syncing hostmaster frontend db_passwd...
BOA [19:57:04] ==> UPGRADE A: Aegir Satellite Instance upgrade completed

Do you want to install some ready to use platforms? [Y/n]

If I just don't answer that question for 3 hours, then cron runs on all the sites on the octopus instance (but I fear that the sites are less well protected during these 3 hours) - so this allows me to keep the sites up without manually running cron on each. 

Does this fact help anyone listening to determine the cause of the error?

**Comment by EdNett** [comment]
Closing as this problem no longer exists as of August 31, 2021 with an up-head

**Comment by karudonaldson** [comment]
Adding a comment for future reference, hopefully, is helpful to others.

I came across a similar issue on an old instance being upgraded though it could easily happen at any point in an upgrade/install for a number of reasons I suppose?  It occurs if a build fails and is by design to wait 24/48 hours for drush to automatically clear its cache?

Or one can expedite that process by running:
`touch /data/disk/o1/static/control/clear-drush-cache.info`

usually fixes the task queue immediately :)
