### ISSUE TITLE
Can/should I run HEAD on a production environment?

### ISSUE THREAD

**Issue by tijmenve** [omega8cc/boa#1574]
I was wondering if I can/should user HEAD on production servers?

I'm running a Drupal 9 website which is having issues with Redis right now since the  Redis module is not ready for D9 yet on STABLE.

In this issue it says this is fixed in HEAD: https://github.com/omega8cc/boa/issues/1553#issuecomment-817237578

However in UPGRADE.txt is says: 
https://github.com/omega8cc/boa/blob/c03a5013013e7c787f619f0e59e3329a83de2be7/docs/UPGRADE.txt#L34-L35

So I'm stuck, apparently this has been fixed, but just in HEAD.
And I'm not supposed to use HEAD in a production environment.

Am I missing something?
Anny suggestions on where to go from here?

**Comment by Juc1** [comment]
@tijmenve hopefully @omega8cc can clarify but I think that UPGRADE.txt is old and out of date - see comments below

I am using head in production with Drupal 9 for a while now. Obviously you should have a server back up / roll back in place before upgrading in the unlikely event of a problem (I use Digital Ocean snapshots)

omega8cc commented on Oct 28, 2019
https://github.com/omega8cc/boa/issues/1443#issuecomment-546990438
> at the moment we recommend to upgrade to head which is production stable and we use it ourselves.

omega8cc commented on May 30, 2020
https://github.com/omega8cc/boa/issues/1493#issuecomment-636358457
> you shouldn't use stable anymore, only head.

omega8cc commented on Jul 22, 2020
https://github.com/omega8cc/boa/issues/1503#issuecomment-662465093
> We are running head in production for years.

**Comment by tijmenve** [comment]
@Juc1 Thank you for your response.

This makes things more clear.
In that case I Will switch to HEAD.
