### ISSUE TITLE
sks-keyservers.net deprecated: clean OS installs failing

### ISSUE THREAD

**Issue by bitf1ipper** [omega8cc/boa#1576]
Clean installs on Debian Stretch 9.13 fail.  sks-keyservers.net DNS pools no longer resolve.  e.g., lib/functions/sql.sh.inc line 559 fails and enters infinite loop: BOA [20:35:41] ==> INFO: Installing Percona...
BOA [20:35:59] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported

Faulting command: gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8507EFA5

In the meantime, you will need to export & import the Percona/MariaDB gpg keys manually as a workaround.

Also at "Installing required libraries and toosl, please wait..." can take a while to time out because it is waiting for confirmation to remove: bsd-mailx* exim4* exim4-base* exim4-config* exim4-daemon-light*, you may need to enter 'Y' and press Enter to proceed before it will start to install db server.

**Comment by omega8cc** [comment]
Fixed, thank you for the heads up, it's pretty new issue caused by disabling DNS for the pool.

**Comment by omega8cc** [comment]
The second issue should be a separate bug, if confirmed, though.
