### ISSUE TITLE
unzip problem on head when using composer to update d8 or d9 platform

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1579]
unzip problem on head when using composer to update d8 or d9 platform:

terminal command line errors printed:

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Failed to extract drupal/search_api_solr: (1) '/usr/bin/unzip' -qq '/data/disk/fast2/static/d907/vendor/composer/tmp-7e0461c984a503bdceef0d1c3726b567.zip' -d '/data/disk/fast2/static/d907/vendor/composer/eaa708ef'

Ed

**Comment by Anoesj** [comment]
Same here when running `composer install` in a fresh D9 platform! (BOA 4.1.3)

**Comment by omega8cc** [comment]
Please upgrade to BOA HEAD to get this fixed. The latest Composer version (several latest versions actually) are not compatible with Drupal, so BOA HEAD downgrades it back to working version 2.0.14

Alternatively you can downgrade only Composer itself, bit if you don't upgrade BOA to HEAD, it will upgrade to not working Composer version on another stable barracuda upgrade.

```
wget https://github.com/composer/composer/releases/download/2.0.14/composer.phar
mv -f composer.phar /usr/local/bin/composer
chmod 755 /usr/local/bin/composer

```
