### ISSUE TITLE
Problem after fresh install, then reboot

### ISSUE THREAD

**Issue by leevh** [omega8cc/boa#1583]
Wondering if anyone has encountered this at all, I've tested ~ 10 or so fresh installs now over 4 days trying to figure out what's happening:

- Linode 4gb 2cpu fresh install with debian 9
- run as root: cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
- run as root: boa in-head public server.domain.com email@email.com o1

Install completes, instance works.

- reboot linode ( or run "barracuda up-head" )

Now if I try to re-verify hostmaster intance in o1 or install new platforms I get several rysnc errors : "Could not rsync from '/data/disk/o1/platforms' to 'o1@server.domain.com:/'  ...  "Could not rsync from '/data/disk/o1/config/server_master' to 'o1@server.domain.com:/'

Also If I try to SSH to root I now get "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!" and have to re-add.

I've installed before and have other running instances. I'm trying to debug, but if anyone is on linode and can give that a quick try I would very much appreciate any advice.  I can supply whichever logs would be relevant.

thank you!

**Comment by omega8cc** [comment]
Have you run required barracuda upgrade after reboot? Many things may not work properly until systemd is removed during initial upgrade.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
SSH keys do change after upgrade, it’s expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Note: it’s not OR — you must reboot and then run upgrade.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leevh** [comment]
Thank you for the feedback.

You're correct, I had missed the step about reboot THEN upgrade.  However I've now tried that method 5 more times over the past two days and same results each time.  

My exact steps are now:

- rebuild 4gb linode with debian 9 and inject my ssh key
- run as root: cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
- run as root: boa in-head public server.domain.com email@email.com o1
- run reboot from command line
- ssh back in (and get "remote host identification has changed")
- run barracuda up-head 

After this I can no longer run verify on the o1.server.domain.com because it fails with "Could not rsync from '/data/disk/o1/platforms' to 'o1@server.domain.com:/' 

If any logs might help, please let me know.  Thank you again.

**Comment by leevh** [comment]
Found the issue.  Linode enables "Network Helper" by default now on new accounts and it was off on my account that I've had for a long time.  Enabling network helper for a new install fixed the problem.
