### ISSUE TITLE
 Retrieving 8507EFA5 key gpg: WARNING: nothing exported

### ISSUE THREAD

**Issue by klevinkona** [omega8cc/boa#1584]
Trying to install BOA on a new Amazon vps ( Debian 9 and Debian 10  )  i have the following loops

gpg: WARNING: nothing exported BOA INFO Retrieving 8507EFA5 key gpg: WARNING: nothing exported
BOA [20:57:50] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
BOA [20:57:53] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
BOA [20:57:56] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
BOA [20:57:59] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
BOA [20:58:02] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported
BOA [20:58:04] ==> INFO: Retrieving 8507EFA5 key..
gpg: WARNING: nothing exported

I tested also locally on vmware, but same output

**Comment by Juc1** [comment]
This sounds like https://github.com/omega8cc/boa/issues/1580#issuecomment-881965173 where the solution was to install head

**Comment by klevinkona** [comment]
Thank you for the reply @Juc1 
I did fixed it by add the key, hope this will help others
```
 gpg --keyserver pgpkeys.mit.edu --recv-key  8507EFA5
 gpg -a --export 8507EFA5 |  apt-key add -
```

**Comment by omega8cc** [comment]
We have switched to pgpkeys.mit.edu by default to make sure it's reliable source: https://github.com/omega8cc/boa/commit/17d3f799a8d48bf14de856976a7320cb23173083
