### ISSUE TITLE
MariaDB 10.4 update error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1586]
When using mariadb 10.4 on head, the update from 10.4.19 to 10.4.21 thows an error; the way to fix the error, we have found is to purge mariadb-server and mariadb-server-10.4, KEEPING ALL DATA, of course, adn then install both with aptitide as root from the command line. 

The error thrown is this:  
https://gist.github.com/EdNett/93bb25ce316a7fa51467db58d6f03d26

Cheers,

Ed

**Comment by omega8cc** [comment]
MariaDB support is not actively maintained and we plan to drop it altogether in the near future because it no longer plays fair with the community, intentionally breaking upgrade paths with both Percona and MySQL.
