### ISSUE TITLE
400 error Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1587]
Hello 
i have recreated ssl certificate for 2 domains on by following these steps 

1. Create empty `/data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid`
2. Run verify on any site with enabled Encryption
3. Remove `/data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid`
4. Run verify on the site from 2 above with enabled Encryption

_Originally posted by @omega8cc in https://github.com/omega8cc/boa/issues/1437#issuecomment-544506640_

However i am getting 400 error Request Header Or Cookie Too Large when i try to load the sites

**Comment by omega8cc** [comment]
This error has nothing to do with LE certificates. Please inspect your code and headers with browser devel tools to determine the culprit. BOA already comes with very high limits for Request headers, and if these limits are hit, something is not right with your code or site configuration.

**Comment by yazzou** [comment]
This happened after i tried to move an octopus plateform from one server to another by following the  guide here : 
https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt
When i noticed that i failed as the sites where not online as expected i tried to revert back and got the error on the original server. 
By the way is it safe to use this guide. I was influenced by this sentence  written in it : 
 "_It's a very safe and reliable (used in production) method when you need_"
When doing some searches in the issues  i saw  somewhere that you do not advice to use it...as it is not tested with the latest versions.
