### ISSUE TITLE
? Path from MariaDB 10.4 to Percona ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1588]
Hello,

Thanks for your response on #1586 - mariadb 10.4 update error; and for mentioning your reasons for moving back to Percona.

Since we will move back to percona ourselves, do you recommend downgrading MariaDB 10.4 to 10.3 before migrating to Percona?

and

Is the MariaDB to Percona migration an easy thing? Is there anytihgn we should look out for?  Of course I know to make backups of everything before attempting it.

Best,

Ed

**Comment by omega8cc** [comment]
Currently you can migrate to Percona only from MariaDB 10.2, at least that was the well tested upgrade path. Migration from MariaDB 10.2 to Percona is easy, no extra work, we have run this before on large scale, fully automatically. We shall probably revisit the requirements and see if it's possible to upgrade to Percona from MariaDB 10.3. I doubt about MariaDB 10.4, though, but we can try.

**Comment by EdNett** [comment]
this is too old so closing
