### ISSUE TITLE
Aegir UI not working properly on fresh install

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1589]
Hello
I have posted about this issue in gitter discussion thread, i was not sure if members were still active there. 
I have installed boa on a vm : 
https://gist.github.com/yazzou/73482d51ae59b3fce2d75f2c7bae6234
I have restarted the machine from command line and run barracud update-head system
I have tried to update octopus and added d6 and d7 plateforms

I have enabled logging during the upgrade. Here is the link : 
https://gist.github.com/yazzou/a43a01474dac4dc2e12498cbc7093926

It seems that there are some errors and my aegir UI is not working properly as modalframes are not triggering.

**Comment by omega8cc** [comment]
It was related to broken D7 core release, already fixed some time ago.
