### ISSUE TITLE
MariaDB 10.1 to 10.2 upgrade problems on older BOA instances

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1590]
Hi,

I am trying to upgrade some older BOA instances from  4.0.1 to the latest version and I have found on two different attempts that MariaDB gets corrupted and I need to restore the whole server from a snapshot.

The first attempt I left MariaDB on 4.1 in the barracuda cnf file and tried to update to stable and I received the errors outlined here https://github.com/omega8cc/boa/issues/1559

Next time I tried with MariaDB at 4.2 - resolved the key issue with the advice here - https://github.com/omega8cc/boa/issues/1584 and again ran had Mariadb update reporting errors

I understand these instances are quite out of date and was hoping you could give me guidance on how best to go about updating them from MariaDB 4.1 to 4.2 so that I can convert them to using Percona 5.7

I understand that doing a fresh server build and migrating the old sites  in is an option but I am hoping to avoid that if I can successfully upgrade the current server in place

Thanks
Gregg

**Comment by omega8cc** [comment]
We have switched to pgpkeys.mit.edu by default to make sure it's reliable source: https://github.com/omega8cc/boa/commit/17d3f799a8d48bf14de856976a7320cb23173083

**Comment by omega8cc** [comment]
Closing old tickets related to issues fixed already. Feel free to reopen if something is still relevant. Thank you!
