### ISSUE TITLE
Sites with CiviCRM fail during installation on a D8/D9 platform

### ISSUE THREAD

**Issue by VangelisP** [omega8cc/boa#1591]
There seems to be an ongoing issue when we try to create a site with CiviCRM 5.x on a Drupal 8 (or 9) platform in Aegir. It always fails during installation.

The error output is this:
```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'system' doesn't exist
```
Further lines down, the originating module appears to be this:
```
/data/disk/<user>/aegir/distro/002/profiles/hostmaster/modules/aegir/hosting_civicrm/drush/install.provision.inc(44): db_query('UPDATE {system}...')
```

Investigating a little bit further to the original repo (and in my code above), we managed to find the offending line [here - (hosting_civicrm)](https://github.com/omega8cc/hosting_civicrm/blob/7.x-3.x/drush/install.provision.inc#L44)

The actual commit that triggered this appears to be [this one](https://github.com/omega8cc/hosting_civicrm/commit/01ed3cf8e0a77b254a9d364cca4c4f2efe9865da)

Drupal 8 (and 9) do not have a table `system` anymore, that's by definition. Shouldn't we be having a conditional check there to see if the site that is being installed is a D8/9 or D7 site?

Cheers

**Comment by omega8cc** [comment]
We are open to accept patches, but please submit is as proper PR so it records the patch credits properly. Thanks!

**Comment by omega8cc** [comment]
We have committed the patch, thanks! https://github.com/omega8cc/hosting_civicrm/commit/16f5f7a657b012189b292eb14ac48f644cac2604

**Comment by VangelisP** [comment]
Thank you, next time (hopefully won't be needed :crossed_fingers: ) it will be a PR !

**Comment by VangelisP** [comment]
Hi @omega8cc , I've spotted another minor issue, resolved into [this PR](https://github.com/omega8cc/hosting_civicrm/pull/2)

Aegir tries to issue the command `menu_cache_clear_all()` twice (not needed, so i removed one of the 2) outside the conditional check if it's D7 or D8/9.

It should be sorted.

**Comment by VangelisP** [comment]
Closing issue as resolved
