### ISSUE TITLE
Request update of Adminer from current 4.7.7 to 4.8.1

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1593]
Request update of Adminer from current 4.7.7 to 4.8.1 - (We are stuck with MariaDB 10.4.x for the moment)

We are running latest 4.1.4-dev of BOA and mariadb 10.4.21 with php 7.4.25 on both fpm and cli

Adminer 4.8.1 contains the following bug fixes - see thier changelog at:
https://github.com/vrana/adminer/blob/master/changes.txt  :

MySQL: Do not export names in quotes with sql_mode='ANSI_QUOTES' (bug #749)
Quote values with leading and trailing zeroes in CSV export (bug #777)
Support function default values in insert (bug #713)
Allow SQL pseudo-function in insert
Skip date columns for non-date values in search anywhere
Add DB version to comment in export

Version 4.8.1 is also ready for php8 and mysql 8.

We are getting lots of errors trying to move D9 sites manually from one vps to another, when using adminer to overwrite a newly created db.

Please see other new issue #1594 (which has us using adminer to update db .tar file over existing db of newly created site, since extracting tar of sql backup on d9 sites doesn't just give us 1 .sql file, but many.).

Lastly - should we drop all the tables of the newly created db on the new vps, BEFORE importing the old .tar db dump boa creates nightly? Or can we just import it over the newly created db? 

This method which has us overwriting only the files directory in the newly created site on teh new vps with the old files directory - is guaranteed to work, isn't it?

Thanks,

Ed

**Comment by omega8cc** [comment]
Fixed.
