### ISSUE TITLE
request updated yii framework for chive db manager

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1595]
Hello,

We are using latest head 4.1.4-dev with php 7.4 and 7.3 and mariadb 10.4 (stuck there currently).

Chive cannot be used as it throws errors. Is chive depricated?

I think the reason chive cannot be used is that it is installed with version 1.1.4 of the yii framework (php development), and version 1 of the yii framework is depricated and for php versions above 5.4 the yii framework version 2.0 is required. Version 2.0 is composer friendly.

I cannot make modifications direct to the config table of a drupal 9 website's database with adminer - so as to uninstall a problematic module - with adminer and am trying to use sqlbuddy and/or chive.

Thanks for an update on chive.

Best,

Ed

**Comment by omega8cc** [comment]
Not sure I understand the problem with Adminer and Drupal 9?

Chive is no longer actively developed / maintained since  July 2014 - https://github.com/fusonic/chive

**Comment by EdNett** [comment]
Closing this now, since chive is not for php 7.4 and above.
