### ISSUE TITLE
sql buddy not working with php 7.4 - ? deprecated ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1596]
Hello,

Is SQL Buddy depricated?  The version installed with up-to-date head 4.1.4-dev does not allow login at all - a php error.   The last version is over 10 years old.   Any chance of getting phpMyAdmin installed on head?

Thanks,

Ed

**Comment by omega8cc** [comment]
It's deprecated for years, you should install Adminer instead.
