### ISSUE TITLE
Is mariaDB 10.4 to 10.3 downgrade supported and easy?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1600]
Hello,

We are trying to work our way from MariaDB 10.4 to latest Percona on BOA head.

Will a simple changing of the MariaDB version from 10.4 to 10.3 in the /root/.barracuda.cnf file, and running a barracuda up-head system do it? Is that a correct way to downgrade mariadb?

Thanks,

Ed

**Comment by EdNett** [comment]
I imagine that disabling binary logging before attempting a downgrade is necessary? Is that right?

**Comment by omega8cc** [comment]
No, downgrade is not supported and not possible without re-installing and restoring all databases from backups.
