### ISSUE TITLE
mariadb 10.4 cannot currently be installed - need to manually add keys.

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1601]
mariadb 10.4 cannot currently be installed - need to manually add keys:

gpg --keyserver pgpkeys.mit.edu --recv-key  C74CD1D8
 gpg -a --export C74CD1D8 |  apt-key add -

Best,

Ed

**Comment by omega8cc** [comment]
MariaDB is deprecated and shouldn't be used. The last officially supported and default version before we switched to Percona was MariaDB 10.3
