### ISSUE TITLE
xboa octopus migrate throws errors:

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1602]
Hello,  the xboa migrate instructions, followed carefully are throwing the following error: 
 On the target-host
  xboa pre-mig source-host  
  
 server1:~# xboa pre-mig source-host
Running pre_mig inside vm target-host
Preparing target target-host for incoming migration...
Add remote id_rsa.pub to authorized_keys here...
Ops.. /root/.ssh/auth_undefined_keys.txt does not exist in target-host
All done!

However when I on the source-host try to test the connection to target, I get the following error:

server1:~# ssh root@target-ip
The authenticity of host 'target-ip (target-ip)' can't be established.
ED25519 key fingerprint is SHA256:npIMwZ+string-of-letters.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'target-ip' (ED25519) to the list of known hosts.
root@target-ip's password:
ssh_dispatch_run_fatal: Connection to target-ip port 22: Connection timed out

boa info more for source is here:

https://gist.github.com/EdNett/071079bc5a5a5f2c3945a42b9792e8cd

boa info for target should be the same, just newer.

Best,

Ed

Update:

By manually copying the id_rsa.pub in source-host /root/.ssh/ to the target-host/root/.ssh/authorized_keys file after the existing ssh key, I was ableo to get the next step to work, however even though both source and target are running head latest, I got this error message on source-host terminal:

BOA [10:52:25] ==> Skynet Agent v.BOA-4.1.3 welcomes you aboard!

BOA [10:52:28] ==> ERROR: This octopus installer can be used only when the same version
BOA [10:52:28] ==> of boa or barracuda installer was used before. Your system must be
BOA [10:52:28] ==> upgraded with barracuda installer version BOA-4.1.3 first
BOA [10:52:28] ==> Bye

BOA in-octopus completed
Bye

Next,  when on the source-host I ran
server1:~# xboa transfer o2 target-ip
I got the following errors:

INFO: transfer for o2 to target-ip  start
rsync: mkdir "/data/disk/o2/distro" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
rsync: mkdir "/data/disk/o2/src" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
rsync: mkdir "/data/disk/o2/static" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
rsync: mkdir "/data/disk/o2/log" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
rsync: mkdir "/data/disk/o2/.drush" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
rsync: mkdir "/data/disk/o2/config/server_master/nginx/vhost.d" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
INFO: transfer for o2 to target-ip  complete

Finally - a big failure when on the target-host I 
xboa import o2 target-ip

the following error appears:

server1:~# xboa import o2 target-ip

ERROR: This version of xboa migration tool supports only BOA-3.2.2 or newer
ERROR: Please upgrade fast2 instance to current BOA head before trying again
Bye.

**Comment by EdNett** [comment]
The above was done on a target server which didn't have the octopus instance already installed (as is allowed per the notes)

I tried the exact same thing, on the exact two same vps's for an already-installed-on-the target octopus instance, and it worked much better, but left the sites unusable and un-verifiable. I am still working on getting the sites up and running again - they just give errors on the browser - no actual site is visible.  The following problems / erros were encountered when doing this (migration to an existing octopus platform on taret)

1) the exact same error as above:

Add remote id_rsa.pub to authorized_keys here...
Ops.. /root/.ssh/auth_undefined_keys.txt does not exist in target-host

and 2) the same "mydumper" error


** (myloader:15357): CRITICAL **: the specified directory is not a mydumper backup

operhaps this is why I don't have sites on the target - just browser error messages, and drush that tells me that there is no drupal site there - and I need a higher bootstrap level to run cron or updb on the command line with drush.

I will try importing adminer exports of the individual sites and see what I get.

**Comment by EdNett** [comment]
Unfortunately, both vps are now unusable - 

the failed o2 migrate did something to the target vps so that I can no longer even do a boa in-octopus and create it!

and the sites on the source o2 instance now don't resolve or show error after error

Be warned - the xboa migrate "tool" is not working at all right now

**Comment by EdNett** [comment]
After trying this migrate on an existing octopus instance, I can no longer add php7.4 to barracuda (to the migrate target) at all! Here's the error:

BOA [18:49:33] ==> INFO: THIS PHP EXTRA is --with-freetype-dir=/usr
BOA [18:49:33] ==> INFO: Building PHP 7.4.25 from sources, please wait...
BOA [18:49:45] ==> INFO: Building PHP 7.4.25 part 1/3
BOA [18:49:49] ==> INFO: Building PHP 7.4.25 part 2/3
BOA [18:50:13] ==> INFO: Building PHP 7.4.25 part 3/3
BOA [18:50:13] ==> INFO: Building PHP 7.4.25 part 2/3 (again)
sed: can't read /var/opt/php-7.4.25/Makefile: No such file or directory
BOA [18:50:33] ==> INFO: Building PHP 7.4.25 part 3/3 (again)
BOA [18:50:34] ==> WARN: Building PHP 7.4.25 failed!

I look in /var/opt/ and I see a folder named csf, and one named mydumper.x adn php7.4, but then I look in /var/opt/ again and there is nothing there!

What can this mean? And why can't I add php7.4 to the master barracuda?

**Comment by omega8cc** [comment]
Yes, it's a problem when yo don't have matching PHP versions installed on both servers. We are using the migration procedure very regularly, even this week, and we don't experience any issues while following the docs.
