### ISSUE TITLE
Install process stuck

### ISSUE THREAD

**Issue by tijmenve** [omega8cc/boa#1604]
When trying to install boa the Installation process gets stuck at 'Installing required libraries and tools, please wait...'

`boa in-head public sub.domain.tld email@email.com o1 none`

```
BOA [15:50:08] ==> Skynet Agent v.BOA-4.1.4-dev welcomes you aboard!

BOA [15:50:11] ==> INFO: NORMAL INIT
BOA [15:50:11] ==> INFO: Public Setup Mode Active
BOA [15:50:12] ==> INFO: Creating your /root/.barracuda.cnf config file
BOA [15:50:15] ==> VIRT: This system is supported: Linux KVM guest

BOA [15:50:16] ==> Aegir on boa3.ams.dutchdigital.io Debian/stretch x86_64 PHP 7.4

BOA [15:50:16] ==> INFO: Installing some basic tools now, please wait...
BOA [15:50:30] ==> INFO: Installing sysvinit-core on Debian stretch...

BOA [15:50:37] ==> NOTE: Please reboot and run 'barracuda up-head system'
BOA [15:50:37] ==> NOTE: after boa completes initial installation
BOA [15:50:37] ==> NOTE: in order to remove unused systemd packages!

BOA [15:50:50] ==> INFO: Installing more basic tools now, please wait...
BOA [15:51:12] ==> INFO: DNS test: OK

BOA [15:51:12] ==> INSTALL START -> checkpoint:

    * Your email address is email@email.com
    * Your IP address is 11.111.111.111
    * Your hostname is sub.domain.tld

BOA [15:51:12] ==> INFO: Installing supported Drush versions...
BOA [15:51:12] ==> INFO: Drush 8.4.9-dev re-installation required
BOA [15:51:12] ==> INFO: Drush 10.6.0 re-installation required
BOA [15:51:12] ==> INFO: Drush Launcher 0.9.1 re-installation required
BOA [15:51:17] ==> INFO: Drush 10.6.0 setup complete
BOA [15:51:17] ==> INFO: Running system packages update...
BOA [15:51:29] ==> INFO: Installing required libraries and tools, please wait...
```

Server is a VULTR Debian 9 Instance.

I have tried this multiple times with the same result every time.
I have also tried to install with php 7.3 but the result was the same.

Anyone has an idea what this could be or how to fix it?

**Comment by omega8cc** [comment]
What is your VPS RAM  size and CPU cores available?

**Comment by tijmenve** [comment]
Thank you for your response.

The VPS has 4GB of RAM and 2 CPU Cores.

**Comment by omega8cc** [comment]
Please check the verbose log during installation with `tail -f /var/backups/barracuda-install*.log` (or inspect it later) to see what actually happens or fails behind the scenes.

**Comment by EdNett** [comment]
Hello,  We have a similar setup 2 x64 xeaon cores and 4 GB ram - and we are unable to get boa to install on a dfresh install of debian 9. The errors are:

BOA [09:24:33] ==> INFO: PHP 7.4.27 will be installed now
BOA [09:24:33] ==> INFO: Building PHP 7.4.27 from sources, please wait...
BOA [09:24:40] ==> INFO: Building PHP 7.4.27 part 1/3
BOA [09:24:44] ==> INFO: Building PHP 7.4.27 part 2/3
BOA [09:25:00] ==> INFO: Building PHP 7.4.27 part 3/3
BOA [09:25:00] ==> INFO: Building PHP 7.4.27 part 2/3 (again)
sed: can't read /var/opt/php-7.4.27/Makefile: No such file or directory
BOA [09:25:16] ==> INFO: Building PHP 7.4.27 part 3/3 (again)
BOA [09:25:17] ==> WARN: Building PHP 7.4.27 failed!
BOA [09:25:18] ==> INFO: Installing Limited Shell 0.9.18.9...
BOA [09:25:32] ==> INFO: Installing Redis update for Debian/stretch...
BOA [09:27:35] ==> INFO: Installing Aegir Master Instance, please wait...
BOA [09:27:36] ==> INFO: Percona is listening on 217.182.74.94.
BOA [09:27:54] ==> FATAL ERROR: AegirSetupM installer failed
BOA [09:27:54] ==> FATAL ERROR: Aborting Barracuda installer NOW!
BOA [09:27:54] ==> HINT: Please check /var/aegir/install.log
BOA [09:27:54] ==> HINT: for more information on errors occured

BOA [09:28:03] ==> Skynet Agent v.BOA-4.1.4-rel welcomes you aboard!

BOA [09:28:06] ==> ERROR: This octopus installer can be used only when the same version
BOA [09:28:06] ==> of boa or barracuda installer was used before. Your system must be
BOA [09:28:06] ==> upgraded with barracuda installer version BOA-4.1.4-rel first
BOA [09:28:06] ==> Bye

BOA in-head completed
Bye

**Comment by EdNett** [comment]
I don't know why the bold and large font print appears when I edit a comment - I am not doing this on purpose!

**Comment by EdNett** [comment]
Hello again,

It seems to me that when installing php 7.4 - the install looks to place it in /var/opt/php74.2.27/...

when in fact it should be placed in /opt/php74/...

I can't seem to find teh place in the scripts where this is listed.  Where exactly is the instruction to build and make php 7.4 - that must be the error, I think.

**Comment by omega8cc** [comment]
@tijmenve We have just tried it on vanilla Linode VPS and it works without issues.

We are happy to assist you in debugging this if you could provide us the access to the vanilla VPS there, so we could try the BOA install ourselves. If that works for you, please let us know the IP address to use (and preferred hostname) and add our SSH keys to root:

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab https://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
cd
```

**Comment by tijmenve** [comment]
Thank you @omega8cc !

Sorry for the late response.
Today I looked into this and I'm still having the same issue.
However, in the window where I'm tailing the log I see this:

`The following packages will be REMOVED:
  bsd-mailx* exim4* exim4-base* exim4-config* exim4-daemon-light*
0 upgraded, 0 newly installed, 5 to remove and 0 not upgraded.
After this operation, 3973 kB disk space will be freed.
Do you want to continue? [Y/n]`

<img width="559" alt="image" src="https://user-images.githubusercontent.com/3774815/151572145-2e59e286-2add-4f05-996d-e25593592f01.png">

This explains why I can't continue.

I'll see if I can manually remove those packages before install of boa.
If that's not successful I'll be in touch and add your key to my vps.

Thank you!

**Comment by omega8cc** [comment]
This shouldn't happen, because BOA enables the silent mode by default. However, we should probably add it in all potentially affected procedures.

**Comment by tijmenve** [comment]
Manually removing the packages didn't work.
However I was able to get around it by typing `Y` in the installer window hen the message `Do you want to continue? [Y/n]` appeared in the window where I was tailing the log.

Thank you!
