### ISSUE TITLE
Remove | Delete | Uninstall Solr7

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1607]
I needed to remove solr7 on a box which wasn't using it (it was previously installed). I'm posting here for docs for others who may need the same.

Based on this [askubuntu](https://askubuntu.com/questions/680690/how-to-uninstall-solr) article I made a bash script to uninstall. @omega8cc Please update/comment as needed.

**uninstall_solr7.sh**
```
#!/bin/bash

service solr7 stop
update-rc.d -f solr7 remove
rm -f /etc/default/solr7.in.sh
rm -f /etc/init.d/solr7
rm -rf /var/solr7/
gpasswd -d solr7 users
deluser --remove-home solr7
deluser --group solr7
```

You may also opt to uninstall java (openjdk) via apt|aptitude if it's not needed for anything else.

**Comment by omega8cc** [comment]
Just a note that it's now possible to de-activate solr/jetty with empty `/root/.deny.java.cnf`
