### ISSUE TITLE
issues / bugs with latest 4.1.4-rel had release

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1609]
Hello, We received the email about the new release 4.1.4-rel, and we upgraded to it both barracuda up-head and octopus up-head, and the same problems remain:

1) It will not install php-7.4. It still ignores _PHP_MULTI_INSTALL="7.3 7.4" and does not install php-7.4 at all, rewriting that line to read _PHP_MULTI_INSTALL=" 7.3"

I notice that the following files exist for each octopus instance:

/data/disk/o1/static/control/.single-fpm.413prodQ28.pid  with a value of "OK", and 
vim /data/disk/o1/static/control/.ctrl.cli.413prodQ28.pid  with a value of "OK"

do these files need to be deleted to allow multi_install of 7.3 and 7.4 ?

2) using composer when logged in as the 01.ftp user is still impossible:

  [Composer\Downloader\TransportException]
  curl error 61 while downloading https://repo.packagist.org/packages.json: Unrecognized content
  encoding type. libcurl understands identity content encodings.

3) there appears to be a problem installing the hostmaster LE certs:

 + Received 1 authorizations URLs from the CA
 + Handling authorization for o1.server1.example.com
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for o1.server1.example.com authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
awk: fatal: cannot open file `/data/disk/o1/tools/le/certs/o1.server1.example.com/cert-163699574.pem' for reading (No such file or directory)
BOA [05:58:19] ==> UPGRADE B: Enhancing Aegir UI, please wait...

and later ... 

BOA [06:00:17] ==> UPGRADE A: Resending setup email on upgrade...
BOA [06:00:17] ==> UPGRADE A: le/certs/o1.server1.example.com/fullchain.pem doesn't exist!
BOA [06:00:17] ==> UPGRADE A: New entry added to /data/disk/o1/log/octopus_log.txt

**Comment by EdNett** [comment]
Hello,  Just tried the latest realease head from Dec 12, and the hostmaster LE certs problem is fixed, but it still won't install php-7.4 and I still can't use composer on the command line - same Curl problem as listed above. Cheers!
Ed

**Comment by lexsoft00** [comment]
It's easy to test this bug where it changes the  _PHP_MULTI_INSTALL="7.3 7.4" to _PHP_MULTI_INSTALL=" 7.3". 

run `barracuda up-head` but when it asks you to continue the upgrade type `n` and open the barracuda.cnf file and you will see the change.

Maybe they will fix it when PHP 8.0 and 8.1 will be added, but I can relate to the frustration where you can't use composer. I had to downgrade the drupal/core vendor packages to be compatible with PHP 7.3 then you can run composer. To do this you need to do a `composer update drupal/core* -W`

**Comment by omega8cc** [comment]
Please follow https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by EdNett** [comment]
boa info more is here:
https://gist.github.com/EdNett/bf956818757d4e2e11931cf1b5822ea4

**Comment by lexsoft00** [comment]
OHV VPS 8v cpu 16GB RAM Debian9
https://gist.githubusercontent.com/lexsoft00/70c03500c14435d6a4e276db828b0de4/raw/4edbcc6f018ab07d46ca0b32435ebf844cb8ff97/gistfile1.txt

**Comment by EdNett** [comment]
On an absolutely fresh install dec 14 10:00 UTC (not specifying anything in the boa in-head command):

BOA [10:06:57] ==> INFO: Building cURL 7.79.1 from sources, please wait...
BOA [10:13:40] ==> INFO: Installed MyQuick line for not (5.7.35), rebuild required
BOA [10:13:40] ==> INFO: Building MyQuick 0.10.7-2 from sources, please wait...
BOA [10:14:08] ==> INFO: Installed MyQuick version line, upgrade required
BOA [10:14:08] ==> INFO: Building MyQuick 0.10.7-2 from sources, please wait...
BOA [10:14:21] ==> INFO: PHP 7.3.33 will be installed now
BOA [10:14:21] ==> INFO: Building PHP 7.3.33 from sources, please wait...
BOA [10:14:28] ==> INFO: Building PHP 7.3.33 part 1/3
BOA [10:14:33] ==> INFO: Building PHP 7.3.33 part 2/3
BOA [10:15:43] ==> INFO: Building PHP 7.3.33 part 3/3
BOA [10:31:59] ==> INFO: Installing PhpRedis 5.3.4 for PHP 7.3.33...
BOA [10:32:25] ==> INFO: Installing APCu 5.1.20 for PHP 7.3.33...
BOA [10:32:39] ==> INFO: Installing MCRYPT 1.0.4 for PHP 7.3.33...
BOA [10:32:49] ==> INFO: Installing UploadProgress for PHP 7.3.33...
BOA [10:32:57] ==> INFO: Installing JSMin for PHP 7.3.33...
BOA [10:33:06] ==> INFO: Installing Imagick for PHP 7.3.33...
BOA [10:33:24] ==> INFO: Installing LibYAML for PHP...
BOA [10:33:48] ==> INFO: Installing YAML for PHP 7.3.33...
BOA [10:33:59] ==> INFO: PHP 7.4.26 will be installed now
BOA [10:33:59] ==> INFO: Building PHP 7.4.26 from sources, please wait...
BOA [10:34:07] ==> INFO: Building PHP 7.4.26 part 1/3
BOA [10:34:11] ==> INFO: Building PHP 7.4.26 part 2/3
BOA [10:34:28] ==> INFO: Building PHP 7.4.26 part 3/3
BOA [10:34:28] ==> INFO: Building PHP 7.4.26 part 2/3 (again)
sed: can't read /var/opt/php-7.4.26/Makefile: No such file or directory
BOA [10:34:45] ==> INFO: Building PHP 7.4.26 part 3/3 (again)
BOA [10:34:46] ==> WARN: Building PHP 7.4.26 failed!
BOA [10:34:47] ==> INFO: Installing Limited Shell 0.9.18.9...
BOA [10:35:01] ==> INFO: Installing Redis update for Debian/stretch...

boa info more is (before install finishes - immediately after errors):
Aegir BOA Cluster on Debian/stretch x86_64
  VPS Linux KVM guest
  DSK 6/100
  CPU 2
  RAM 3859
  NGX 1.21.4
  PHP 7.3.33
  DBV 5.7.35
  RDS 6.2.6
  SSH 7.4p1
  SSL 1.1.1l
  CRL 7.79.1
  STG
  CSF
  LSH
  RIS
  SQL
  XTR
  MFX
  PFX
  DNS
  PKG

**Comment by lexsoft00** [comment]
EdNett can you check /var/backups for the barracuda-install-*.log and put it in a gist?

**Comment by lexsoft00** [comment]
@omega8cc I can reinstall a fresh Debian10 on my VPS and give you access to it for testing purposes.

**Comment by omega8cc** [comment]
Debian 10 is not supported yet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
@EdNett  BOA will not run on 2GB RAM with 1 CPU, please check requirements.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
One test vps - without solr and anything else that uses cpu and ram - does indeed have only 1 vcpu and 2GB ram - and that is sufficient for a test vps - to test if boa upgrade is goign to produce problems or not on production vps.  I believe.  

The same problem happened with a bigger vps 4 Gb ram and 2 vCPU - you can see that in the boa info more #2 - also in-line above - these are zeon x64 virtual cpu's - which means that temp load can go as high as 32 cpu's and they still work , so I don't believe cpu or ram is a problem at all here. I think it would be worthwhile checking if php 7.3 and php7.4 are being built with the correct libcurl - and importantly a libcurl and curl version which are compatible with the composer boa is using 2.0.14 - (or something like that if my memory serves me right) - this is where i think the problem is. Best regards,

Ed

**Comment by omega8cc** [comment]
Please check the verbose installation log for details. We can’t reproduce the problem, and we install several new systems daily.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
the tail of the barracuda install log stops abruptly here (install of php-redis for 7.3 ?):

https://gist.github.com/EdNett/258279a5c70ba135fa2bfd07f54e5fc0

**Comment by EdNett** [comment]
could this be the problem:

composer/composer#10153

**Comment by lexsoft00** [comment]
Have re-tried the install today on OVH VPS  8cores 16GB RAM fresh Debian 9 and it still fails on PHP-7.4, please see the gist part when it reaches the PHP install:
https://gist.github.com/lexsoft00/ee8a5dad064f311ae7ba556a9aee73bc

I have tried an install on Debian 10 (for fun, even if it's not supported yet) and it has installed PHP-7.4 but failed to install mycrypt .

**Comment by timlie** [comment]
Hi,

Today I upgraded my BOA server latest HEAD.
This is my info file:

https://gist.github.com/timlie/2023b2c5af2961641331f8649ed65120

Before the upgrade I changed the _PHP_MULTI_INSTALL from _PHP_MULTI_INSTALL="7.3 7.2" to _PHP_MULTI_INSTALL="7.4 7.3 7.2" in .barracuda.cnf

I noticed when installing, only 7.3 version for php was installed:

BOA [21:59:40] ==> INFO: Building MyQuick 0.10.7-2 from sources, please wait...
BOA [22:00:04] ==> INFO: Installed PHP version 7.3.29, upgrade required
BOA [22:00:04] ==> INFO: Building PHP 7.3.33 from sources, please wait...
BOA [22:00:16] ==> INFO: Building PHP 7.3.33 part 1/3
BOA [22:00:20] ==> INFO: Building PHP 7.3.33 part 2/3
BOA [22:01:46] ==> INFO: Building PHP 7.3.33 part 3/3
BOA [22:18:34] ==> INFO: Installing PhpRedis 5.3.4 for PHP 7.3.33...
BOA [22:19:00] ==> INFO: Installing APCu 5.1.20 for PHP 7.3.33...
BOA [22:19:14] ==> INFO: Installing MCRYPT 1.0.4 for PHP 7.3.33...
BOA [22:19:24] ==> INFO: Installing UploadProgress for PHP 7.3.33...
BOA [22:19:33] ==> INFO: Installing JSMin for PHP 7.3.33...
BOA [22:19:43] ==> INFO: Installing Imagick for PHP 7.3.33...
BOA [22:19:59] ==> INFO: Installing YAML for PHP 7.3.33...
BOA [22:20:16] ==> INFO: Installed Redis version 6.2.4, upgrade required
BOA [22:20:16] ==> INFO: Installing Redis update for Debian/stretch...

Do you want to upgrade Aegir Master Instance? [Y/n]

When checking my .barracuda.cnf file I now only see this:

_PHP_MULTI_INSTALL=" 7.3"

7.2 is gone, ther is also no 7.4, there is also a space before 7.3.

When changing this back to:

_PHP_MULTI_INSTALL="7.4 7.3 7.2"

and starting upgrade but saying "no" as described by lexsoft00 [here](https://github.com/omega8cc/boa/issues/1609#issuecomment-992348026), it is set again to:

_PHP_MULTI_INSTALL=" 7.3"

Thanks for support!

**Comment by EdNett** [comment]
the install on a fresh debian 9 vps looks good up through the install of php 7.3.33 and then it fails trying to install php 7.4.27
This is on a 2 x x64 weon cores with 4 GB ram and NVMe ssd hard disk.


BOA [09:24:22] ==> INFO: Installing YAML for PHP 7.3.33...
BOA [09:24:33] ==> INFO: PHP 7.4.27 will be installed now
BOA [09:24:33] ==> INFO: Building PHP 7.4.27 from sources, please wait...
BOA [09:24:40] ==> INFO: Building PHP 7.4.27 part 1/3
BOA [09:24:44] ==> INFO: Building PHP 7.4.27 part 2/3
BOA [09:25:00] ==> INFO: Building PHP 7.4.27 part 3/3
BOA [09:25:00] ==> INFO: Building PHP 7.4.27 part 2/3 (again)
sed: can't read /var/opt/php-7.4.27/Makefile: No such file or directory
BOA [09:25:16] ==> INFO: Building PHP 7.4.27 part 3/3 (again)
BOA [09:25:17] ==> WARN: Building PHP 7.4.27 failed!
BOA [09:25:18] ==> INFO: Installing Limited Shell 0.9.18.9...
BOA [09:25:32] ==> INFO: Installing Redis update for Debian/stretch...
BOA [09:27:35] ==> INFO: Installing Aegir Master Instance, please wait...
BOA [09:27:36] ==> INFO: Percona is listening on 217.182.74.94.
BOA [09:27:54] ==> FATAL ERROR: AegirSetupM installer failed
BOA [09:27:54] ==> FATAL ERROR: Aborting Barracuda installer NOW!
BOA [09:27:54] ==> HINT: Please check /var/aegir/install.log
BOA [09:27:54] ==> HINT: for more information on errors occured

BOA [09:28:03] ==> Skynet Agent v.BOA-4.1.4-rel welcomes you aboard!

BOA [09:28:06] ==> ERROR: This octopus installer can be used only when the same version
BOA [09:28:06] ==> of boa or barracuda installer was used before. Your system must be
BOA [09:28:06] ==> upgraded with barracuda installer version BOA-4.1.4-rel first
BOA [09:28:06] ==> Bye

BOA in-head completed
Bye


the install log only shows this error:

root@server1:~# tail -f /var/backups/barracuda-install*.log
cache-oblivious    : 1
cxx                : 1
===============================================================================
cp include/jemalloc/internal/private_namespace.gen.h include/jemalloc/internal/private_namespace.gen.h

Hint: It's a good idea to run 'make test' ;)


Hint: It's a good idea to run 'make test' ;)

**Comment by EdNett** [comment]
boa info more here:
https://gist.github.com/EdNett/fc5d9a276c27ad4685773acda40d2b27

**Comment by EdNett** [comment]
It seems to me that when installing php 7.4 - the install looks to place it in /var/opt/php74.2.27/...

when in fact it should be placed in /opt/php74/...

I can't seem to find teh place in the scripts where this is listed. Where exactly is the instruction to build and make php 7.4 - that must be the error, I think.

**Comment by EdNett** [comment]
Can't you remove all references to php-7.4 as default so that boa doesn't expect it, since it won't install - that way with php-7.3 it should work ?

**Comment by omega8cc** [comment]
We have just tried the fresh BOA install again on vanilla Linode VPS and it worked flawlessly:

```
BOA [17:57:05] ==> INFO: PHP 7.4.27 will be installed now
BOA [17:57:05] ==> INFO: Building PHP 7.4.27 from sources, please wait...
BOA [17:57:13] ==> INFO: Building PHP 7.4.27 part 1/3
BOA [17:57:17] ==> INFO: Building PHP 7.4.27 part 2/3
BOA [17:58:10] ==> INFO: Building PHP 7.4.27 part 3/3
BOA [18:13:03] ==> INFO: Installing PhpRedis 5.3.4 for PHP 7.4.27...
```
We are happy to assist anyone still experiencing the broken PHP 7.4 build in debugging this if you could provide us the access to the **vanilla VPS** on the host where you experience issues, so we could try the BOA install ourselves. If that works for you, please use https://omega8.cc/contact to let us know the IP address to use (and preferred hostname) and add our SSH keys to root:

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab https://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
cd
```

**Comment by omega8cc** [comment]
We also would like to kindly ask everyone a few things, because it's ongoing issue with some of your bug reports, which are appreciated, but from now on please make sure to strictly follow our project issue queue rules to be helpful:

1. Do not post duplicate issues
2. Do not add comments in someone's else issues which report different problems
3. If you believe that your problem is connected to someone else issue, please only link it in your own issue
4. Do not post any errors in the comments, only link them as separate gist
5. Always link as gist the current output of the command `boa info more`
6. Before running the `boa info more`, update the script with `bash /var/xdrago/clear.sh`

Once you follow all six steps outlined above, it will be way easier to use the information provided for debugging it further.

Thank you.

**Comment by EdNett** [comment]
Hello,

I can confirm that on a fresh install both php7.3 and php7.4 are installed! Great and thank you.    

The problem for boa servers which installed php7.3 only at first, still exists, however - php7.4 will not be installed. I set the _PHP_MULTI_INSTALL="7.4 7.3" and remove the 7.3 entries from the _PHP_SINGLE_INSTALL=  in the /root/.barracuda.cnf file  and run the barracuda up-head.  php7.4 is not installed (no references to it in the log) and the _PHP_MULTI_INSTALL line is modified to _PHP_MULTI_INSTALL=" 7.3" (with the preceeding space before the 7.3) and as well it is copied to the bottom of the /root/.barracuda.cnf file.  I will try it again, since php7.3 just got upgraded - and maybe that will change the result.

clean boa info more is here: https://gist.github.com/EdNett/4a15bdbdc2e4a2a88e4592f518e8d2c6

Sorry my bug reporting wasn't up to your standards. I can do better! Thank you for your help.

**Comment by EdNett** [comment]
I don't know if I should close this issue now, since only this one issue remains (sorry for listing 3 bugs in the original issue! - won't do it again). But since I am off of the other issue #1606  mentioning this, I'll just list the error here in a gist. When I do as is indicated in #1606 to get php-7.4 to install (namely: remove the deformed "_PHP_MULTI_INSTALL=" data and add _PHP_SINGLE_INSTALL=7.4, leaving CLI and FPM set to 7.3, (if I change CLI and FPM to 7.4 - it also fails) I get this error:

https://gist.github.com/EdNett/bffa8abcc1222cce609d294761211b69

and 7.4 is not installed, and the aegir upgrade fails.  Don't know what to do.

**Comment by EdNett** [comment]
OK, so I did a barracuda up-head one more time (with the newly upgraded curl, etc) with the important parts of the .barracuda.cnf file set to:
_PHP_CLI_VERSION=7.4
_PHP_FPM_VERSION=7.4
_PHP_MULTI_INSTALL="7.4 7.3"
_PHP_SINGLE_INSTALL=7.4

 and this time - for the 1st time in 2months for me-  php7.4 was installed (after an existing 7.3 previously installed. Great.) the .barrracuda.cnf file was re-written to:


_PHP_CLI_VERSION=7.4
_PHP_FPM_VERSION=7.4
_PHP_MULTI_INSTALL=7.4
_PHP_SINGLE_INSTALL=7.4

with the line _PHP_MULTI_INSTALL=7.4 also written twice at the end of the file!

Closing this issue now, as it appears to be working. Thank you.  Might resolve #1606, too ?

**Comment by omega8cc** [comment]
Yes, the extra lines are also fixed now and will be removed if you run another barracuda upgrade.
