### ISSUE TITLE
bad link on newer boa release notice

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1611]
There is new BOA-4.1.4-rel version available.

 Please review the changelog and upgrade as soon as possible
 to receive all security updates and new features.

 Changelog: http://bit.ly/boa-changes   - this link leads to the notice for the 4.1.3 stable version!

 --
 This email has been sent by your Barracuda server upgrade monitor.

**Comment by omega8cc** [comment]
Fixed, thanks.
