### ISSUE TITLE
Drush installation broken after upgrade

### ISSUE THREAD

**Issue by ginovanmiddendorp** [omega8cc/boa#1612]
It seems Drush is broken after the auto-upgrade today (BOA-4.1.3)

> 
> BOA [00:11:55] ==> INFO: Installing extra Drush versions...
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> /opt/tmp/boa/lib/functions/system.sh.inc: line 2106: cd: /opt/tools/drush/7/drush/: No such file or directory
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> /opt/tmp/boa/lib/functions/system.sh.inc: line 2115: cd: /opt/tools/drush/8/drush/: No such file or directory
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> BOA [00:11:55] ==> INFO: Drush re-installation required
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> chmod: cannot access '/opt/tools/drush/*/drush/drush': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/drush.complete.sh': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/drush.launcher': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/drush.php': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/unish.sh': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/examples/drush.wrapper': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/examples/git-bisect.example.sh': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/examples/helloworld.script': No such file or directory
> BOA [00:11:56] ==> FAIL: Drush installation failed! Trying again..
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> chmod: cannot access '/opt/tools/drush/*/drush/drush': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/drush.complete.sh': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/drush.launcher': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/drush.php': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/unish.sh': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/examples/drush.wrapper': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/examples/git-bisect.example.sh': No such file or directory
> chmod: cannot access '/opt/tools/drush/*/drush/examples/helloworld.script': No such file or directory
> BOA [00:12:11] ==> FAIL: Drush installation failed again! Oops..

Anyone who's running into the same issue and knows how to fix it?

**Comment by tijmenve** [comment]
Having the same issue here on multiple servers.
This means you can't use Drush from the cli.
However verifying websites from the web interface still seems to work.
