### ISSUE TITLE
PHP 8.0 / 8.1 support

### ISSUE THREAD

**Issue by egoosmann** [omega8cc/boa#1613]
Are there plans for supporting PHP 8.0 and/or PHP 8.1 on BOA?

As far as I can see in the documentation PHP 7.4 is the highest supported version, but active support for this version has already been stopped and security support will be ended on 28 November 2022. PHP 8.0 is supported (and recommended) by Drupal 9.1.0 and above. PHP 8.1 is supported (and recommended) since Drupal 9.3.0.

**Comment by omega8cc** [comment]
Both 8.0 and 8.1 will be supported in the next two weeks.

**Comment by egoosmann** [comment]
Great! And thanks for the quick response :)

**Comment by omega8cc** [comment]
Looks like it's two months instead, but we are on it!

**Comment by egoosmann** [comment]
Thank you for the update! :)

**Comment by omega8cc** [comment]
This has been added in https://github.com/omega8cc/boa/commit/fcabb2fba656a34c1167d3562d935061cba22c93
