### ISSUE TITLE
issues with drush version

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1614]
Hello 
I am working on migration from d7 to d9. 
When using default drush installed with boa 10.6.0 (?) i have many errors. 

I have to install drush 10.6.1 on the platform itself in order to work. 
`sudo -u octopus composer require drush/drush:10.6.1

sudo -u octopus composer remove drupl/migrate_upgrade:^3`

However, everytime i need to verify a site with aegir (in the concerned platform) i need to downgrade drush again to be able to do it

any chance to get the upgraded drush version by default ? 
Thanks

**Comment by omega8cc** [comment]
There are two, or even several unrelated issues:

1. Aegir will not use Drush 10, only Drush 8.
2. Aegir removes local Drush on the platform on verify to avoid conflicts
3. We will upgrade Drush to 10.6.2 but it will affect only command line, not Aegir
4. We still need to implement reliable workaround to make Aegir ignoring site local Drush

**Comment by yazzou** [comment]
Thanks for getting back. Upgrading Drush to 10.6.2 but it will affect only command line will for sure allow to save some time by not having to reinstall locally the latest drush after every verify task.

**Comment by omega8cc** [comment]
Closing old tickets related to issues fixed already. Feel free to reopen if something is still relevant. Thank you!
