### ISSUE TITLE
unable to login as octopus user - "passwd: Authentication token manipulation error"

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1615]
We are trying to update our d7 sites to 7.84 (subdomain session problem) and update search_api_pages (security update) and we can't login due to forced password change for octopus user that fails!:
--------------------------
 Barracuda System managed by Skynet Agent v.BOA-4.1.4-dev welcomes you aboard

WARNING: Your password has expired.
You must change your password now and login again!
Changing password for o1.ftp.
(current) UNIX password:
passwd: Authentication token manipulation error
passwd: password unchanged
-----------------

We can't update head since it's broken. We do use long octopus passwords 128 - 250 characters including special characters, and this has never been a problem before. We last successfully updted the o1.ftp password on 10 september of this year to a complcated 184 character including special characters password. Has anythinng in boa changed since then that restricts length of passwords or characters used for passwords? 

The error is being produced when we are asked to enter a valid current password for the o1.ftp user. Also caveat: we do not use o1 as the octopus instance name we use something else that is quite regular, which we have been using for 5 years, like "hot1", for example.

1) Is there any way to disable this forced password change temporarily so that we can update and be secure (we use subdomains actively) ?

2) Would it help to login as root and change the o1.ftp password to something very simple and retry logging in as o1.ftp user?  would the newly changed password have to be synced to something? What? (I don't really like this idea).

boa info more here: https://gist.github.com/EdNett/23824fd907e12262050b5eb6b86aee92

This is on our main production machine adn it's pretty alarming. Any help would be appreciated.

Thanks,  

Ed

**Comment by timlie** [comment]
Try to change it as root...

**Comment by EdNett** [comment]
Is this a PAM settings problem - has something changed there?

Is it a read only permission on one of the /etc/passwd  /etc/group /etc/gshadow or /etc/shadow files ? I see that there are duplicate files for all of these with a "-" at the end, i.e. /etc/shadow-   which tells me that a password change is being attempted - shoudl I delete the files with the "-" (dash) at the end, give temp write permissions to the 4 above-listed files (those without the dash at the end) and try again?

**Comment by lexsoft00** [comment]
@EdNett have you tried to log in as root and have the password changed with `passwd o1.ftp` and re-login with the new password and change it again with `passwd`. 

Both passwords can be strong, no need to use a simple one.

**Comment by EdNett** [comment]
Hello, Thanks for the advice, but I fear that changing the password is not the best idea. It would probably have to be synced elsewhere ...   Also, this problem ought to be resolved. I know I can su o1.ftp and do things that way temporarily. I have tried rebooting the server, that didn't help. I don't know if we use PAM or not.

**Comment by omega8cc** [comment]
This is not really BOA related, just standard sysadmin stuff you should handle as root.
