### ISSUE TITLE
Custom nginx rules on site

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1617]
Hello 
I am trying to create some redirections to get rid of old pages on a site. Ihave read the doc and noted that we do have to use the if statement inside location block.
https://github.com/omega8cc/boa/blob/d823192abd759261d390a64bb28ee4105bf7d09a/docs/HINTS.txt#L36
As this rule applies only to one site and to many URI at the same time i have to use regex rules inside the custom file. 

Example : 
https://www.example.com/Greece/sport%20?page=55

I would like to get :

https://www.example.com/greece.html?page=55

Normally, this rule works : 
` location ~* ^(/[^/]+)/ {
       return 301 $scheme://$host$1.html$is_args$args;
   }`

However if i have to follow the instructions [https://github.com/omega8cc/boa/blob/d823192abd759261d390a64bb28ee4105bf7d09a/docs/HINTS.txt#L36](url)
i would maybe do 
```
location ~* ^(/[^/]+)/  {
  if ($host ~* ^(www\.)?(example\.com)$) {
 
       return 301 $scheme://$host$1.html$is_args$args;
   }
   return 404;
}

```
This breaks the original url and leads to nowhere 
Also, i saw in the nginx doc that we need to avoid using if inside location blocks : https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/
So i am not sure hw to handle redirections in Boa environment 
Thanks

**Comment by omega8cc** [comment]
You can't avoid the "evil' `if` if you have to configure URI and site-specific redirects, but you should use rewrites, like this:

```
  if ($http_host ~ "^(www\.)?foo-bar\.com$"){
    rewrite ^/legacy-uri-foo$ https://site-name/new-uri-one? permanent;
    rewrite ^/legacy-uri-bar$ https://site-name/new-uri-two? permanent;
    rewrite ^/legacy-uri-any$ https://site-name/new-uri-any? permanent;
  }
```
