### ISSUE TITLE
recent php path and naming errors in recent commits ? - php 7.4 not building at all for 2 months now ... errros in boa/lib/functions/php.sh.inc   at line 1125, for example or at line 1234 and 1268

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1621]
Hello,  for about 2 months now php 7.4 has not been building on head. I think I have found one reason why (after spending a few hours looking at the code on your site):

I guess that (unless you are moving all php from /opt/ to /var/opt and unless you are in the process of changing all path references to php74 from php74 to php-74), 
then recent commits have made errors that prevent php 7.4 from being installed or upgraded:

Please see your boa/lib/functions/php.sh.inc   at line 1125, for example or at line 1234 and 1268

they have some (only some) references to /var/opt/php-${_PHP_VERSION}  which I think break everything - shouldn't all such lines be:
/opt/php${_PHP_VERSION}

making those changes might allow php 7.4 to install.  

Please help solve this issue since recent updates to d9 platforms have dependencies which now REQUIRE php greater than or equal to 7.4.

Also an update to composer is required also. #1619  Thank you,

Ed

**Comment by omega8cc** [comment]
No, you are confusing temporary build paths and install paths, it's irrelevant to the previously reported problem affecting some hosts (just none of ours). Also, please do not open duplicate issues about the same problem. This problem has been already solved in head and PHP 7.4 build was tested on several recent BOA installs. if you still experience issues, please follow up on existing issues.
