### ISSUE TITLE
Error on octopus up-head latest in /opt/tmp/boa/lib/functions/satellite.sh.inc:

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1622]
Error on octopus up-head latest in /opt/tmp/boa/lib/functions/satellite.sh.inc:

gist is here:  https://gist.github.com/EdNett/9d8f0960ddd5dfba01285ea0337e9eac

boa info more is here:  https://gist.github.com/EdNett/3ad827e06cb438893c41cebd69d53b91

(We use "fast2" as the name of the octopus instance)

Thank you for php 8!

Best regards,

Ed

**Comment by omega8cc** [comment]
Typo has been fixed, thanks.
