### ISSUE TITLE
Question on recent php additions

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1624]
Hello,

Thank you for the php 8.0 and 8.1 additions. I have a question - I don't know if it is a bug report or not:

Befrore the latest barracuda up-head I modified my .barracuda.cnf file to make php_multi = "7.4 8.0"
and I set both fpm and cli to be = 8.0

when I ran the up-head, it installed 7.3, 8.0 and 8.1! (The server only had 7.4 on it before the upgrade).  

near the end of the up-head the AEGIR upgrade failed with an error message that the version of php was not supported.

My question is:  Is there a file somewhere that needs to be set so that php 8.0 is set, before putting it in the .barracuda.cnf file as both fmp and cli = 8.0?

By the way, I modified the .barracuda.cnf file to have 7.4 for both fpm adn cli, ran the up-head again and this error was not reproduced - the last part of the up-head AEGIR setup A, B and C proceeded normally.

boa info more is here: https://gist.github.com/EdNett/3ad827e06cb438893c41cebd69d53b91

Thank you,
Ed

**Comment by omega8cc** [comment]
You should not use PHP 8.x by default yet, it's still experimental addition for hosted sites only, not for Aegir yet.

**Comment by EdNett** [comment]
closing this cause once the /root/.sorted.multi.php.cnf empty file is present, adding 8.0 and / or 8.1 to the _PHP_MULTI_INSTALL variable in the .barracuda.cnf file and running barracuda up-head php-all installs 8.0 and 8.1. (might have to "barracuda up-head php-all twice it that /root/.sorted.multi.php.cnf empty file isn't present - the second time 8.0 and 8.1 are installed.).

Thanks,  Ed
