### ISSUE TITLE
php 8.0 and 8.1 failing to build on a second server (production)

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1625]
Hello,  

with php_multi = "7.4 8.0" in the .barracuda.cnf file:

php 8.0 and 8.1 built successfully on our test server, and then a few hours later, they failed to build on the production server! (just my luck). I am trying to figure out why. I ran the barracuda up-head twice and they failed to build both times.

Boa info more here:  https://gist.github.com/EdNett/77c758aa6f51667176a1f78806a6d544

Best regards,

ed

**Comment by EdNett** [comment]
I wonder if this problem is caused by php74-fpm failing and failing to restart because of extremely high memory settings in /opt/php74/etc/php74.ini  and /opt/php/etc/fpm-pool-common.conf ?

I noticed that after the recent barracuda up-head that my octopus instance AEgir GUI was showing an Nginx 502 error.

I looked at the above-mentioned files and made the following changes (for a 4GB server - I feel this is more reasonable. [Perhaps the default settings need to be adjusted lower to allow 4-8GB RAM instances to stay up during and after the upgrade?]

/opt/php/etc/fpm-pool-common.conf :

php_admin_value[memory_limit] = 1024M > 324M
php_admin_value[apc.shm_size] = 1024M > 64M  

and for each /opt/php74/etc/php74.ini file :

memory_limit=1024M > 336M
apc.shm_size=1024M > 64M
opcache.memory_consumption=2048 > 48

This works for us, but each up-head resets everything to the defaults. Could this be the reason 8.0 and 8.1 fail to install.? Because fpm is already failing because the upgrade script changes these values? If you can't lower the defaults, what about installing new php versions BEFORE upgrading any existing php versions? Would that work?

**Comment by omega8cc** [comment]
These limits are fine as long as your system has the required 4GB of RAM at minimum, and it was well tested on 2CPU/4GB Linode, with zero issues. It doesn't affect the installation at all. Perhaps it's something specific to your VPS host?

**Comment by EdNett** [comment]
I have decided to upgrade ram to 8 GB - I started hitting composer dependency-resolver memory problems as well - so 8 Gb with SOLR should be OK

**Comment by EdNett** [comment]
I am reopening this, as php 8.0 and 8.1 will NOT install on a boa head server with php7.4 running currently

**Comment by EdNett** [comment]
I upgraded ram to 8 gb and still cannot install php 8.0 or 8.1   new boa info more is here:

https://gist.github.com/EdNett/e8d8f18d42cb1328d861a86059f09349

**Comment by omega8cc** [comment]
The built-in cleanup of PHP versions not used by any Octopus instance on the server is a one-time operation which results with file `/root/.sorted.multi.php.cnf` being created which prevents from running the cleanup again (so don't delete it), unless `/root/.barracuda.cnf` doesn't have a line with `_PHP_MULTI_INSTALL` which forces the cleanup again and removes any not used versions from `_PHP_MULTI_INSTALL`. Please don't confuse the steps and make sure that either `/root/.sorted.multi.php.cnf` exists **before** you add 8.x versions to `_PHP_MULTI_INSTALL`, or simply force them on upgrade with `barracuda up-head php-all`.

**Comment by EdNett** [comment]
Thank you for that information.  Running teh barracuda up-head, leaving the /root/.sorted.multi.php.cnf empty file in place having set _PHP_MULTI_INSTALL="8.1 8.0 7.4"  did NOT install 8.0 or 8.1. Running it again with barracuda up-head php-all  did install both 8.0 and 8.1.  

Now, how do we stop instances of fpm (for example php73-fpm) that we do not want running, so they are not auto-restarted?

Can we remove those versions with aptitude or dpkg ? Or should we remove the /etc/init.d entries and the run level entries in /etc/rc2.d /etc/rc3.d  , etc.  ? and then rm -R /opt/php73/*  etc. ? 

or is there a boa specific way to remove them, so un-needed version of php-fpm are not running, taking up RAM?

Thank you.

Ed

**Comment by omega8cc** [comment]
There is no feature to disable not used PHP versions yet. Please open a feature request, unless it already exists.
