### ISSUE TITLE
nginx failing to start after upgrade

### ISSUE THREAD

**Issue by dserrato** [omega8cc/boa#1627]
Ran through the upgrade process for both barracuda and octopus this morning and everything seemed to go well. Received the upgrade email with all of the new information for the 4.1.4 release. 

Aegir dashboard site was not loading. Tried an extra reboot with still no success. Then noticed sites were not loading. 

Checked nginx status and it was not running. When trying to start nginx, got the following message:

Starting Nginx Server...:nginx: [emerg] PEM_read_bio_DHparams("/etc/ssl/private/nginx-wild-ssl.dhp") failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: DH PARAMETERS)

Anyone have any knowledge on this or ideas as what to do?

**Comment by omega8cc** [comment]
It’s a very rare exception that nginx-wild-ssl.dhp ends up empty. Please find any other .dhp file in the same directory and copy it as nginx-wild-ssl.dhp

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
