### ISSUE TITLE
request modification of default apc cache settings so php-fpm doesn't fail

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1628]
Hello,

I think that many of the current and recent problems with php not installing or not installing properly, nginx going down, etc. 
are caused by too high default memory settings in each fpm instance of two settings:

apc.shm_size=1024M  (This is the real problem, I believe - I would set this to 64M as a default)
opcache.memory_consumption=2048 >(I would set this to 48 - this means 48 M for eash site served by fpm I believe)

these two default settings will cause pfp-fpm to fail when restarting (thus causing nginx to go down, and both php-fpm and nginx will remain down until these two settings are lowered to a reasonable value for the specific server, at which point php-fpm and nginx restart automatically!).

Servers and VPS's with only 4 to 8 GB of ram will have this problem - especially if using more than one or two versions of php-fpm.

I realize that my suggested values are low, but they allow the upgrade to take place with no problems, and, of course, you could always:

1) offer sugggestions to users with higher memory servers to modify these values, or
2) automatically increase them with your script, but at the end of the barracuda up process.

Or do we now require 8 - 16 GB ram to run and update BOA?

Best regards,

ed

**Comment by omega8cc** [comment]
Closing as duplicate.
