### ISSUE TITLE
Migrate task stalling at MyQuick.info

### ISSUE THREAD

**Issue by dserrato** [omega8cc/boa#1631]
I have completed a successful upgrade to the latest head of 4.1.3. Everything is going well, and I was able to run some clones and migration tests. 

But, on a migration test this morning on a clone of one of my larger more important sites, it seems to stall at the following line for MyQuick.info:

```
DEBUG MyQuick import_dump mysql.php pass_php_inc /data/disk/o1/.o1.pass.php | - | info
DEBUG MyQuick import_dump mysql.php enable_myquick /data/disk/o1/static/control/MyQuick.info
```

But, I do not have the MyQuick.info file in the /o1/static/control folder. I had initially put it in there to see if how well it works, but I took it our right away, and I've already run another barracuda up-head after that. I would assume that there wouldn't be any settings that are referencing it. 

Is there is an extra place I need to check to make sure the migrate or clone process doesn't use the MyQuick?

**Comment by omega8cc** [comment]
The debug info will be there no matter if you have `~/static/control/MyQuick.info` or not. For large site you either need big enough RAM and enough CPU power or you should create `~/static/control/MyQuick.info` to make the tasks running much faster, as explained in the built-in docs: `~/static/control/README.txt`
