### ISSUE TITLE
D9: `cache-clear all` is deprecated for Drupal 8 and later. Please use the `cache-rebuild` command instead.

### ISSUE THREAD

**Issue by fotiDim** [omega8cc/boa#1633]
Trying to clear the cache using the GUI on a D9.3.3 website gives this error: `cache-clear all` is deprecated for Drupal 8 and later. Please use the `cache-rebuild` command instead.

It works fine on D8.9.7 on the same website (prior to migration)

**Comment by omega8cc** [comment]
Please make sure you have upgraded both barracuda and octopus to head. Te code in head clearly runs correct command against Drupal 8+ based sites: https://github.com/omega8cc/hosting_tasks_extra/commit/ab7610586a425639c85af0c31b75d53625fd9916

**Comment by fotiDim** [comment]
I ran `barracuda up-head system` and `octopus up-head all both` rebooted and the issue persists.

**Comment by omega8cc** [comment]
You should run `octopus up-head all force` as otherwise you will not upgrade to latest head.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Also, you should run full upgrade not just system, with `barracuda up-head`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fotiDim** [comment]
I did `octopus up-head all force` and `barracuda up-head` and still the same problem.

Upon login I am getting `Barracuda System managed by Skynet Agent v.BOA-4.1.4-rel welcomes you aboard`. 

```
server:~# drush --version
Drush Version   :  8.4.10
```
I suppose I am up to date. Do I need to recreate the platform, perhaps?

**Comment by omega8cc** [comment]
Try to reverify platform and site and make sure it’s discovered as D9 platform. If this doesn’t help, try with one of the built-in D9 platforms per docs in ~/static/control/README.txt — maybe your platform is not recognized for some reason. We have tried this several times and it’s working properly in all tests.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fotiDim** [comment]
I managed to solve the issue. I had to do `octopus up-head all both` but it was failing because fpm.info and cli.info were using an old version of PHP. I needed to bump it to 5.6 and then run `octopus up-head all both` again.
