### ISSUE TITLE
Drush permissions

### ISSUE THREAD

**Issue by davyrhys** [omega8cc/boa#1635]
My server management company has just installed BOA on Debian 10 on a VPS but we are having some challenges.

**Problems with Adminer**
When trying to import a 26MB gzipped db :

- when logged is using root username/password I get a timeout error. 
- When logged in  using the username/password/db details from the sites drushrc.php file I get a superuser error:
```
 /*!50003 CREATE*/ /*!50017 DEFINER=`[REMOVED]`@`localhost`*/ /*!50003 TRIGGER civicrm_acl_after_insert after insert ON civicrm_acl FOR EACH ROW BEGIN  IF ( @civicrm_disable_logging IS NULL OR @civicrm_disable_logging = 0 ) THEN INSERT INTO log_civicrm_acl (`id`, `name`, `deny`, `entity_table`, `entity_id`, `operation`, `object_table`, `object_id`, `acl_table`, `acl_id`, `is_active`, log_conn_id, log_user_id, log_action) VALUES ( NEW.`id`, NEW.`name`, NEW.`deny`, NEW.`entity_table`, NEW.`entity_id`, NEW.`operation`, NEW.`object_table`, NEW.`object_id`, NEW.`acl_table`, NEW.`acl_id`, NEW.`is_active`, COALESCE(@uniqueID, LEFT(CONCAT('c_', unix_timestamp()/3600, CONNECTION_ID()), 17)), @civicrm_user_id, 'insert'); END IF; END */

Error in query (1227): Access denied; you need (at least one of) the SUPER privilege(s) for this operation
541 queries executed OK
```

Can you advise what the settings should be?

.
**Drush won't work for o1.ftp** 
When I log in as o1.ftp I get this when I run drush commands
```
o1.ftp:~$ drush status
/usr/bin/sh: line 661: /usr/bin/sh: Argument list too long
/usr/bin/sh: line 661: /usr/bin/sh: Success
```

But the server admin team are able to use drush. This is what they said:

```
... the drush command was executable if we login to the o1.ftp user as /bin/bash and using the full path of the drush.php. Please check the below snippet for your reference.

o1.ftp@server:~/static/platforms$ php /opt/tools/drush/8/drush/drush.php status
 PHP configuration      :  /opt/php74/lib/php.ini /home/o1.ftp/.drush/php.ini         
 PHP OS                 :  Linux                                                     
 Drush script           :  /opt/tools/drush/8/drush/drush.php                         
 Drush version          :  8.4.10                                                     
 Drush temp directory   :  /home/o1.ftp/.tmp                                         
 Drush configuration    :                                                             
 Drush alias files      :  /home/o1.ftp/.drush/devnew.siteurl.co.za.alias.drushrc.php

We have also tried restoring the MySQL database with the same command and it was successfully restored.
```

They have asked me to check the permissions  the drush.php file and configuration. 
And is there anything else we should be checking?

**Comment by davyrhys** [comment]
> 

Thank you
I understand you're working on Debian 10 support. Any projections of when it might be ready?
Or would you recommend we reinstall on Debian 9?

**Comment by omega8cc** [comment]
There is no ETA, it's still a work in progress.

**Comment by luxio** [comment]
@davyrhys I'm facing the same issue with

```
o1.ftp:~$ drush status
/usr/bin/sh: line 661: /usr/bin/sh: Argument list too long
/usr/bin/sh: line 661: /usr/bin/sh: Success
```

Have you found a solution? Is it related to Debian 10?

**Comment by luxio** [comment]
@davyrhys 

> . **Drush won't work for o1.ftp** When I log in as o1.ftp I get this when I run drush commands
> 
> ```
> o1.ftp:~$ drush status
> /usr/bin/sh: line 661: /usr/bin/sh: Argument list too long
> /usr/bin/sh: line 661: /usr/bin/sh: Success
> ```


I think this line causes an infinite loop:

https://github.com/omega8cc/boa/blob/01a69ae09c178564f25d743673315cc15ee42a44/aegir/helpers/websh.sh.txt#L614
