### ISSUE TITLE
Absence of cli.info and fpm.info creates error of PHP 5.2

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1636]
Was just updating an octopus instance (only 1 on the machine) and got an error as generated from https://github.com/omega8cc/boa/blob/93877594ec1c972507def029a60ea31d4371075b/lib/functions/satellite.sh.inc#L4164

```
BOA [12:23:59] ==> ERROR: This instance o1 still depends on the old PHP version
BOA [12:23:59] ==> FPM.5.2 CLI.5.2
BOA [12:23:59] ==> It is not possible to upgrade it to BOA-4.1.4-rel
BOA [12:23:59] ==> Please switch FPM and CLI on o1 to PHP 5.6 or newer
BOA [12:23:59] ==> Then please run the octopus upgrade again
BOA [12:23:59] ==> Bye
```

I'm assuming the files didn't previously exist. Despite the server having been updated recently.
It's been running fine with PHP 7.4 on both CLI and FPM.

Listing /data/disk/o1/static/control revealed they were just created on the most recent update. Don't know if previous versions existed or had been killed.
```
-rw-r--r-- 1 o1.ftp users   4 Feb  4 11:29 cli.info
-rw-r--r-- 1 o1.ftp users   4 Feb  4 11:29 fpm.info
root@server:/data/disk/o1/static/control# date
Fri Feb  4 11:45:34 CST 2022
```

Regardless, if BOA created them now, it defaulted to 5.2 and doesn't allow octopus to run successfully. Maybe try deleting those two files and running **octopus up-head all force** as a test?

Required info
Linode: https://gist.github.com/petrowsky/e84beeab97fe01a2e6b7c5987b02cc77

**Comment by lexsoft00** [comment]
I can confirm that I had a similar issue with PHP 5.2 when updating to the latest head and o1 aegir went down but doing an `octopus up-head o1 force` got it back running.

**Comment by reswild** [comment]
This happens to me every time I run `barracuda up-head` as long as I use _PHP_SINGLE_INSTALL. I'll post a PR for this.

**Comment by Anoesj** [comment]
We have this problem too with several (not all) up-to-date BOA servers. On every weekly update, our `fpm.info` and `cli.info` are changed to `5.2`. This breaks all sites on these servers until we manually update both files to the correct PHP version. Really annoying, so if @reswild's  PR (#1641) works, please merge! :smile:

**Comment by omega8cc** [comment]
It wasn't a bug, but intentional trick to force PHP-FPM re-configuration by changing the version to obviously unsupported. The problem is that due to changes in the logic elsewhere after adding 8.0 and 8.1 the trick stopped working on systems using _PHP_SINGLE_INSTALL
