### ISSUE TITLE
gzip / tar error in up-head octopus

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1638]
DEBUG AegirSetupB
BOA [07:00:21] ==> UPGRADE B: Aegir automated install script part B
BOA [07:00:21] ==> UPGRADE B: Creating directories with correct permissions
BOA [07:00:21] ==> UPGRADE B: Running standard installer
BOA [07:00:21] ==> UPGRADE B: Downloading drush 8.4.10.2...
BOA [07:00:25] ==> UPGRADE B: Installing Aegir Provision backend...
BOA [07:00:25] ==> UPGRADE B: Downloading Drush and Provision extensions...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
BOA [07:00:39] ==> UPGRADE B: Drush test result OK

**Comment by petrowsky** [comment]
I can also confirm getting this error.

**Comment by omega8cc** [comment]
It was a deprecated module missing on our mirrors, now fixed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
