### ISSUE TITLE
Nginx service running but no port 80, 443 active

### ISSUE THREAD

**Issue by klevinkona** [omega8cc/boa#1640]
Installed fresh server debian 10 and after that installed boa but nginx service is not listening on port 80, 443 ( netstat -lpun ) .
If i do systemctl status nginx the service looks active.

From the logs i can see the following error

unlink() "/var/run/nginx.pid" failed No such file or directory)

And after i did reboot and barracuda up-head looks like systemd is gone

-bash: systemctl: command not found

**Comment by omega8cc** [comment]
Debian 10 is not fully supported yet, it's a work in progress now.
