### ISSUE TITLE
backboa not working anymore

### ISSUE THREAD

**Issue by cwaone** [omega8cc/boa#1643]
hello,

some days ago backboa stopped to work probably.

Just updatet the system to the actual head but getting the same error anyway:

18226 (process ID) old priority 10, new priority 19
Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 42, in <module>
    import fasteners
ImportError: No module named fasteners

any ideas?

thanks

**Comment by omega8cc** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/omega8cc/boa/blob/dc07147d452562f0fd6654c52a71655a24bfdeed/CONTRIBUTING.txt).
