### ISSUE TITLE
Mirrors offline? XX.files.aegir.cc is not available, cannot update system

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1646]
My long-running BOA system went offline. Found I had extremely high CPU load, with dozens of `mysqladmin` processes running. Had to bring down the database with `service mysql stop` and killing all mysql-related processes to investigate further as the system was unresponsive otherwise.

[boa info](https://gist.github.com/ar-jan/edaaff87488ac4a713bc9a6a7faec2a2)

The system was on auto-update, but I see it stopped updating in January. So I thought I'd try a manual update, but this doesn't work:

`cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`
ERROR: de.files.aegir.cc is not available, please try later

It seems like it should try all available mirrors, but instead the update stops after one. I tried removing the failing mirror from `/var/backups/boa-mirrors-2021-08.txt`, but that only leads to the next mirror being listed as unavailable:
`ERROR: uk.files.aegir.cc is not available, please try later`

Same with `barracuda up-head`.

Am I right I should first get the system updated and if so how to get there with mirrors failing for me? And if not, any clues why mysql was completely messed up?

**Comment by ar-jan** [comment]
Found a relevant error.

> tail -f /var/log/kern.log
> Mar 10 19:38:15 web02 kernel: [71123.243308] mysqladmin[21183]: segfault at 21 ip 00007f39fa145378 sp 00007ffc66731310 error 4 in libcrypto.so.1.1[7f39f9f9f000+2e0000]

**Comment by omega8cc** [comment]
It’s a sign of crashing drives or memory, unfortunately. Check your hardware status urgently.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reswild** [comment]
The 'de.files.aegir.cc is not available' error message can be a bit misleading as this is more likely caused by a curl error when trying to connect, rather than the mirror being offline. I got this error recently on one of my servers after an aborted update had left me with mismatching versions of curl and libcurl. This left me a bit mystified for a while, but I eventually figured out that all I had to do was to downgrade my curl version.

It sounds like your potential hardware error is more urgent though.

**Comment by ar-jan** [comment]
Ugh. It's a VPS though so hardware issue seems less likely.

Could a failed upgrade have caused this, like maybe a mismatched libssl-dev version due to an upgrade failing?

**Comment by ar-jan** [comment]
According to my provider there is no issue with either the host or my instance. So I still wonder whether this is due to some package issue, given the the segfault occurs in libcrypto.so, and:

> curl --version
> curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
> Release-Date: 2022-01-05
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
> Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
> WARNING: curl and libcurl versions do not match. Functionality may be affected.
> curl: symbol lookup error: curl: undefined symbol: curl_mime_free

**Comment by ar-jan** [comment]
Relevant versions seem identical -- this different from your case @reswild ?

```
dpkg -l | grep curl
ii  curl                                 7.52.1-5+deb9u16
ii  gnupg-curl                           1.4.18-7+deb8u5 
ii  gnupg1-curl                          1.4.21-4+deb9u1 
"classic" version)
ii  libcurl3:amd64                       7.52.1-5+deb9u16
flavour)
ii  libcurl3-gnutls:amd64                7.52.1-5+deb9u16
flavour)
ii  libcurl4-openssl-dev:amd64           7.52.1-5+deb9u16
```

**Comment by reswild** [comment]
You'll have version 7.52.1 installed by the package manager, but now BOA also build curl from sources, so a newer version is added to /usr/local/bin. I think all I needed to do was rename these, and then my barracuda update worked again using the older curl version. So something like this might be all you need to do:
```
mv /usr/local/bin/curl /usr/local/bin/curl.bak
mv /usr/local/bin/curl-config /usr/local/bin/curl-config.bak
```

**Comment by omega8cc** [comment]
@ar-jan You still have some libs from the the previous major Debian version on this system, so it may cause unexpected issues: `1.4.18-7+deb8u5`

**Comment by ar-jan** [comment]
After removing `gnupg-curl gnupg1-curl` and renaming `/usr/local/bin/curl` I got this:

Running `barracuda up-head log` in a screen session, and `tail -f /var/backups/reports/up/barracuda/220314/barracuda-up-220314-224100.log`:

> BOA [02:25:27] ==> INFO: Upgrading Limited Shell to version 0.9.18.9...
> BOA [02:25:47] ==> INFO: Running Aegir Master Instance upgrade
> BOA [02:28:31] ==> INFO: Downloading drush 8.4.10.2...
> BOA [02:29:34] ==> INFO: Installing Aegir Provision backend...
> BOA [02:29:34] ==> INFO: Downloading Drush and Provision extensions...
> BOA [02:29:42] ==> FATAL ERROR: Drush is broken (/opt/php74/bin/php /var/aegir/drush/drush.php help failed)
> BOA [02:29:42] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
> BOA [02:29:42] ==> FATAL ERROR: AegirUpgrade installer failed
> BOA [02:29:42] ==> FATAL ERROR: Aborting Barracuda installer NOW!

But the BOA part seems to have worked:
`curl --version`
> curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) nghttp2/1.18.1 librtmp/2.3 OpenLDAP/2.4.44
> Release-Date: 2022-01-05

`octopus up-head all force`
BOA [10:54:49] ==> Skynet Agent v.BOA-4.1.4-rel welcomes you aboard!
BOA [10:54:52] ==> ERROR: This octopus installer can be used only when the same version
BOA [10:54:52] ==> of boa or barracuda installer was used before. Your system must be
BOA [10:54:52] ==> upgraded with barracuda installer version BOA-4.1.4-rel first
BOA [10:54:52] ==> Bye

Hmm that's strange as it was already 4.1.4-rel. What if I do another system upgrade:

`barracuda up-head system`
> REPORT: Successful Barracuda upgrade on web.example.com sent to xxx
> BARRACUDA upgrade completed

All update steps succeeded, but there's some changes for mysql listed, and the main problem seems to be with mysql:

> BOA [11:15:16] ==> INFO: Running MariaDB system tables (2) upgrade...
> BOA [11:15:22] ==> INFO: MariaDB diff1 18c18
> < collation_server        = utf8mb4_unicode_ci
> ---
> > collation_server        = utf8mb4_general_ci
> 24d23
> < #show_compatibility_56   = ON
> 30,34c29,33
> < max_allowed_packet      = 256M
> < max_connect_errors      = 16
> < max_connections         = 32
> < max_user_connections    = 16
> < myisam_sort_buffer_size = 938K
> ---
> > max_allowed_packet      = 64M
> > max_connect_errors      = 12
> > max_connections         = 24
> > max_user_connections    = 12
> > myisam_sort_buffer_size = 1024K
> 46,48c45,47
> < wait_timeout            = 3600
> < tmp_table_size          = 469M
> < max_heap_table_size     = 469M
> ---
> > wait_timeout            = 9999
> > tmp_table_size          = 512M
> > max_heap_table_size     = 512M
> 55,58d53
> < sync_binlog             = 0
> < open_files_limit        = 294912
> < innodb_autoinc_lock_mode= 2
> < group_concat_max_len    = 10000
> 64a60,62
> > sync_binlog             = 0
> > open_files_limit        = 294912
> > innodb_autoinc_lock_mode= 2
> 79,80c77,78
> < innodb_lru_scan_depth   = 10
> < innodb_buffer_pool_size = 469M
> ---
> > innodb_lru_scan_depth   = 100
> > innodb_buffer_pool_size = 512M
> 89c87
> < innodb_flush_log_at_trx_commit = 2
> ---
> > innodb_flush_log_at_trx_commit = 0
> 91c89
> < innodb_lock_wait_timeout = 300
> ---
> > innodb_lock_wait_timeout = 15
> 102,103d99
> < innodb_checksum_algorithm=NONE
> < innodb_flush_log_at_timeout = 5
> 105d100
> < innodb_temp_data_file_path = ibtmp1:12M:autoextend:max:900M
> 115c110
> < max_allowed_packet      = 256M
> ---
> > max_allowed_packet      = 64M
> 119d113
> < default-character-set   = utf8mb4
> BOA [11:15:22] ==> INFO: MariaDB diff2 18c18
> < collation_server        = utf8mb4_unicode_ci
> ---
> > collation_server        = utf8mb4_general_ci
> 24d23
> < #show_compatibility_56   = ON
> 30,34c29,33
> < max_allowed_packet      = 256M
> < max_connect_errors      = 16
> < max_connections         = 32
> < max_user_connections    = 16
> < myisam_sort_buffer_size = 938K
> ---
> > max_allowed_packet      = 64M
> > max_connect_errors      = 12
> > max_connections         = 24
> > max_user_connections    = 12
> > myisam_sort_buffer_size = 1024K
> 46,48c45,47
> < wait_timeout            = 3600
> < tmp_table_size          = 469M
> < max_heap_table_size     = 469M
> ---
> > wait_timeout            = 9999
> > tmp_table_size          = 512M
> > max_heap_table_size     = 512M
> 55,58d53
> < sync_binlog             = 0
> < open_files_limit        = 294912
> < innodb_autoinc_lock_mode= 2
> < group_concat_max_len    = 10000
> 64a60,62
> > sync_binlog             = 0
> > open_files_limit        = 294912
> > innodb_autoinc_lock_mode= 2
> 79,80c77,78
> < innodb_lru_scan_depth   = 10
> < innodb_buffer_pool_size = 469M
> ---
> > innodb_lru_scan_depth   = 100
> > innodb_buffer_pool_size = 512M
> 89c87
> < innodb_flush_log_at_trx_commit = 2
> ---
> > innodb_flush_log_at_trx_commit = 0
> 91c89
> < innodb_lock_wait_timeout = 300
> ---
> > innodb_lock_wait_timeout = 15
> 102,103d99
> < innodb_checksum_algorithm=NONE
> < innodb_flush_log_at_timeout = 5
> 105d100
> < innodb_temp_data_file_path = ibtmp1:12M:autoextend:max:900M
> 115c110
> < max_allowed_packet      = 256M
> ---
> > max_allowed_packet      = 64M
> 119d113
> < default-character-set   = utf8mb4

Tried aegir update again: `octopus up-head all force`:
> BOA [12:40:26] ==> Skynet Agent v.BOA-4.1.4-rel welcomes you aboard!
> BOA [12:41:12] ==> Octopus Satellite Instance Upgrade in progress...
> BOA [12:41:14] ==> This Octopus URL address is arjan.web02.slimternet.nl
> BOA [12:41:14] ==> This Octopus PHP version is 7.4
> BOA [12:41:14] ==> This Octopus System is Debian/stretch x86_64
> BOA [12:41:23] ==> UPGRADE A: Shared platforms code v.003 (new) will be created
> BOA [12:42:41] ==> UPGRADE B: Downloading drush 8.4.10.2...
> BOA [12:43:45] ==> UPGRADE B: Installing Aegir Provision backend...
> BOA [12:43:45] ==> UPGRADE B: Downloading Drush and Provision extensions...
> BOA [12:44:06] ==> UPGRADE B: Hostmaster STATUS: Upgrade in progress...
> BOA [12:54:07] ==> UPGRADE B: Hostmaster STATUS: Upgrade completed
> BOA [12:54:07] ==> UPGRADE B: FATAL ERROR: Required file does not exist:
> BOA [12:54:07] ==> UPGRADE B: FATAL ERROR: /data/disk/arjan/aegir/distro/004/sites/o1.web.example.com/settings.php
> BOA [12:54:07] ==> UPGRADE B: FATAL ERROR: Aborting AegirSetupB installer NOW!
> BOA [12:54:07] ==> UPGRADE A: FATAL ERROR: AegirSetupB installer failed
> BOA [12:54:07] ==> UPGRADE A: FATAL ERROR: Aborting AegirSetupA installer NOW!
> BOA [12:54:07] ==> FATAL ERROR: AegirSetupA installer failed
> BOA [12:54:07] ==> FATAL ERROR: Aborting Octopus installer NOW!

I guess I'm giving up on this install. I've been trying to figure it out though to prevent any such issues in the future. My provider double checked and there were no disk or memory problems (they use ECC), but they moved my instance just in case. The corruption must have occurred through some misconfiguration or update problem which is a bit worrying.

Any clues how this might have occurred without hardware problems? Maybe lack of disk space?

**Comment by EdNett** [comment]
Hello,

I've seen similar problems before, and they usually go away if you try to update head again in a few days. But, if you are asking if such a problem could occur with a lack of disk space - I don't understand you at all. A lack of disk space is the worst thing that can happen to any server, and especially with BOA - if your main disk is more than 88 - 89 % full - than everything fails. (I believe they cut off all updates if a disk is 90 % full). I know you're a smart guy, because we've both been using BOA for quite a few years, but the command "df -l" run as root - wil tell you if you're more than 60 - 75 % % full on the main partition - if so, it's time to get a bigger disk! Seriously!

Good luck!

**Comment by ar-jan** [comment]
Well, I ask because I know updates are not run when disk is at 90% usage, but afaik that only blocks further updates, and it **shouldn't** cause corruption.

**Comment by EdNett** [comment]
Run apt autoremove, and delete all the site backups, and other backups - even old log files if they are huge - that have been made recently - they're probably no good - until you get that disk less than 85% full - and then things should start working again.

**Comment by ar-jan** [comment]
I'd already made sure there was plenty of space and updates are still failing. The question that's on my mind is what caused the corruption that corruption.
