### ISSUE TITLE
unexplained problems with Integrity Constraint Violations in sessions table

### ISSUE THREAD

**Issue by EarthAngelConsulting** [omega8cc/boa#1650]
hello BOA team!

i have a possible bug report here.

we are running two AWS servers, with an identical codebase, each one serving up multiple Drupal sites.

here is my gist link for the 'boa info' output for "server 1"  https://gist.github.com/EarthAngelConsulting/47c1cee284e8df883816bc996ab2cf44 and "server 2" https://gist.github.com/EarthAngelConsulting/d26688602aef690b9d60326158766837

we are running Drupal 7.89, were running 7.69 at the beginning of this "situation".

approximately on Apr 15 or 16, we started to have issues with one of our busiest websites (on Server 1, call it "Site A"), which involved Ubercart orders being assigned to incorrect user IDs, users unable to log in, and similar problems.  at first, maybe 3 or 4 per day, yesterday it was as high as 10 per day at least.

no code changes or server changes were made to trigger this situation, as far as we can tell, it "just started happening" (though we did find that there were a _few_ other sporadic cases of order/user binding errors, maybe five in previous six months... possibly due to a different cause, but our logs don't go far enough back to tell.)  

initially this problem was just happening on Site A, but within a few days, it was being reported on other sites (usually just the busiest ones) on both servers.

we have narrowed the main problem down to multiple occurrences of this error:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;mNSiO1dBRDir6fJ2aw_9xijM5pvr_kKgKCEz_T-6cm4-mNSiO1dBRDir6fJ2aw_9&#039; for key &#039;PRIMARY&#039;: UPDATE {sessions} SET sid=:db_update_placeholder_0, ssid=:db_update_placeholder_1
WHERE (ssid = :db_condition_placeholder_0) ; Array
(
[:db_update_placeholder_0] =&gt; mNSiO1dBRDir6fJ2aw_9xijM5pvr_kKgKCEz_T-6cm4
[:db_update_placeholder_1] =&gt; mNSiO1dBRDir6fJ2aw_9xijM5pvr_kKgKCEz_T-6cm4
[:db_condition_placeholder_0] =&gt; _0n_fV894qsNTn9rm4IY08x2MiPCZ4AgSZ0GJgT5JDg
)
```

(see this gist for a full backtrace: https://gist.github.com/EarthAngelConsulting/9c882dec968015a4e509551997ed7c5c )

the error is occurring in this function: drupal_session_regenerate()

there are also sporadic errors of 'integrity constraint violation' happening in a few _other_ tables (focal_point, file_managed, users, email_auto_login_tokens)... which _may_ have been due to user sessions getting confused as to 'who was who', though not necessarily, ie: if this is some kind of table caching or general database problem, then it may be affecting these tables directly, or else it may just be affecting sessions, which fails and then causing cascading errors in other tables.

there were also issues on one site (on Server 2) where a user with the appropriate permissions wasn't able to masquerade as a certain user, the error it was giving was the same as above (Integrity constraint violation in sessions table).

we have tried various things to fix this, including

- upgrading to Drupal 7.89, which had no effect, in fact the error frequency may have increased after that, but definitely did not decrease.

- based on these two articles: https://www.drupal.org/project/masquerade/issues/3210117 and https://drupal.stackexchange.com/questions/89372/what-would-cause-a-duplicate-session-key and others indicating same, we decided to see if the explicit setting of $conf['https'] = TRUE in settings.php or similar (rather than relying on other things to just keep the whole site in HTTPS mode at all times, as we have it configured that way) may have been an issue.  we edited /data/conf/global.inc directly (knowing of course that this could get overwritten without warning) and just commented out the two lines where $conf['https'] was set, without any other changes.    at first, it seemed like this had fixed it, but within an hour the errors started happening again.  however, that _did_ seem to permanently fix the problem with the masquerading not working!

- we also did a 'drush rr' on Site A and Site B, as a test.  for over an hour there were no errors, but then they started again.

right now, Site A has shown this specific error (integrity constraint violation in sessions table) only twice in the last 24 hours, the previous 24 hours it was eight or ten times, and similar the period before that.  (Site A is a busy site, probably our busiest.  to give you an idea: the sessions table shows 1205 distinct login sessions and 8072 distinct anonymous sessions, in last 24 hours.  our session garbage collection seems to be working, as there are no transactions older the 24 hours.  the total number of users on this site is 184,168 though obviously some of them are inactive.)

**we are running out of ideas and are wondering if there's any chance that this sessions problem is a BOA issue of some kind, and if anyone else has reported it?**

also, i am not sure if Redis is involved in caching reads to the sessions table in any way, or just other tables, but there _have_ been sporadic Redis errors as well (though not at the same time as the "Integrity constraint violation in sessions" errors). see this gist for some examples: https://gist.github.com/EarthAngelConsulting/a7a66ac6080e7d540cc9907bc2d65ad4

note: we currently have the 'past' module running on two sites from each server, to get the backtraces; other sites are running watchdog, or no logging at all.  therefore, we can't give accurate numbers on just how many sites are showing these errors, however the four sites running 'past' are all very busy ones, and _all_ of them have shown errors of integrity constraint violations in sessions, and other misc. errors as described above.

please let us know if there is any further information that you need, and/or what we should try next!

thanks,
Peter Fisera, Earth Angel Consulting (for Brainflex)

**Comment by EarthAngelConsulting** [comment]
update:

about 10 days ago, we restarted the server entirely, and the integrity constraint errors in the sessions table seem to have stopped entirely.

however:

**the issues with order/user binding** (ie: order created by one user actually ends up associated with another user) and the various other user-related errors are still there... and they all seem to be stemming from one thing:  in some sporadic cases, function `user_save()` (called from function `user_register_submit()`, and there is no uid specified yet, as it is a new user) **is returning `$account` but it is _not_ a new user account, it is a uid already in use!**  therefore, the information from `$form_state` (which we hand off to various other processes, including Ubercart) has the firstname, lastname, email address of the person who just registered, but a uid that points to a different, existing user record.  most of the other errors we have found seem like they could be caused by this alone.

i have looked closely at `user_save()` and at `db_next_id()` and i just _can't_ see how this would be happening, unless there was some confusion at the database level, eg: some kind of database caching like Redis?

we did find numerous references online that for busy sites, the transaction isolation level in MySQL (or MariaDB in our case) should definitely be set to `READ-COMMITTED` and not `REPEATABLE-READ`, we made that change (just on "Site A", the busiest one and where most of the errors are happening), hoping that this would solve the problem.  it did _not_, though the frequency seemed to drop a bit (these errors with the uid not being 'new' are only happening once or twice per day now).

we are still getting sporadic  'integrity constraint violation' errors happening in a few other tables (focal_point, file_managed) however these are likely due to the initial confusion about the uids.  we don't know that for sure, but it seems likely.

**we really need some help on this... are there reported cases of Redis or some other level of the BOA stack having problems with generating 'unused' uids?**  

**also, if we suspect that Redis might be the problem, is it worth disabling Redis just for Site A, by doing one of these:**

"Create a directory named "cache" as in: sites/all/modules/cache for platform wide effect -- or as in: sites/site.example.com/modules/cache to affect a particular site -- with an empty file named NO.txt. Note the uppercase file name." (as suggested at https://groups.drupal.org/node/173219 )

or

"To disable Redis integration temporarily for debugging, either per site or per platform, you can set redis_cache_disable = TRUE in either site or platform level INI file" (as suggested at https://learn.omega8.cc/how-to-disable-all-caching-and-aggregation-115)

this site (and the other one on Server 1) is very busy, we have the fastest AWS instance available and server loads are still quite high, we are worried that if we disable Redis, the extra server load could crash the server... so we really want to be sure that there's a chance of success before trying this!

thanks,
Peter Fisera, Earth Angel Consulting (for Brainflex)

**Comment by EarthAngelConsulting** [comment]
note: we just now tried setting `redis_cache_disable = TRUE` in `boa_platform_control.ini` and the server load seemed to go up a bit but not much.   and then, we realized that cron had stopped running (it triggers every 10 minutes on our site, though not all processes run that frequently, we use elysia_cron to manage them).  as soon as we changed it back (well, two minutes later) cron started running again.

is there something in BOA that tells cron not to run (for performance reasons, i assume) if Redis is disabled?

**Comment by omega8cc** [comment]
You are running way to old BOA version, which is no longer supported  for over two years.

The first step is to upgrade both barracuda and octopus to head. There is no way around this, and we will not debug anything if you don't keep your system up to date.

The next step is to remove duplicate code -- you have the wrong and conflicting Redis integration modules in your codebase and you should remove it and then run registry rebuild -- example:

[type] (string): 64
[message] (string): Cannot redeclare redis_autoload() (previously declared in /data/all/000/modules/redis_edge/redis.autoload.inc:16)
[file] (string): /data/disk/wwoof/static/cwp_usa/sites/all/modules/contrib/redis/redis.autoload.inc
[line] (string): 22

The module copy to delete is in this case: /data/disk/wwoof/static/cwp_usa/sites/all/modules/contrib/redis

**Comment by EarthAngelConsulting** [comment]
thank you for the response!

we are sadly aware of the upgrade issue, i assume you have had some contact from Andrea about how to resolve this?

we did remove that redundant redis module, and that particular error stopped.  all other errors are still there.   

note that the redis module was actually _disabled_, according to the `system` table.   therefore, i am not sure how much it would have been affecting operations, other than triggering an error when sites/all/modules/contrib/redis/redis.autoload.inc was somehow invoked every 24 hours, and finding redis_autoload already declared (i am assuming this timing might be a cron process from BOA, to check if required modules are enabled, etc.?  as far as i can tell it wasn't one of our cron processes.)

**Comment by omega8cc** [comment]
The redis module is not really a module, it doesn't even have to be enabled at all, so you should never had extra copies in the codebase to avoid issues. We have responded to support ticket but never received any response from your team.

**Comment by impara** [comment]
Had the same issue this fixed the problem https://www.drupal.org/files/pdo_exception_one_time_login_https-2075405-1.patch
