### ISSUE TITLE
Release Policy

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1653]
@omega8cc said on Gitter on Jan 23 2020 "Don’t use stable the head is new stable already. We just have to figure out how to change naming convention to avoid confusion" . 

https://github.com/omega8cc/boa/blob/master/CHANGELOG.txt

### Milestone URL: https://github.com/omega8cc/boa/milestones/4.1.3

# Release Notes:

This BOA release is a second transitional release before switching to rolling release policy...

@omega8cc can you please clarify the naming convention / release policy?

Does this mean that 4.2.0 https://github.com/omega8cc/boa/milestones won't ever be released? And instead we should just keep updating head? If so how often should we update head?

Thanks...

**Comment by omega8cc** [comment]
It will be clarified in the upcoming updates to reactivated changelog and then readme.
