### ISSUE TITLE
duobackboa fails to install duplicity

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1654]
Hi,

I was testing duobackboa on a Windows WSL Ubuntu-20-04 image.
The following steps where used as root:
1. Got the duobackboa script:
wget https://raw.githubusercontent.com/omega8cc/boa/master/aegir/tools/bin/duobackboa

2. Made the script executable
chmod u+x duobackboa
3. Added the /root/.duobackboa.cnf with access credentials
4. Installed duobackboa: ./duobackboa install

[Install output](https://gist.github.com/lexsoft00/ed5ee4bfc8f7f540e53276581a2edd83)

**Comment by omega8cc** [comment]
Thanks for the heads up.
