### ISSUE TITLE
nginx can't restart after "Aborted connection to db" in syslog

### ISSUE THREAD

**Issue by leevh** [omega8cc/boa#1657]
Hoping someone else has experienced this one.  I've had 3 times in the last 6 months I'm alerted to all sites down.  Nginx is not running and trying to restart gives :

`nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/ssl/private/o1.server.ca1.mysite.com.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

I've checked daily log and o1 LE renewed fine 4 days earlier. I did find something odd in my syslog at the time sites went down:  "Aborted connection to db"
https://gist.github.com/leevh/cbd51dcab2ca1e09e85995a5552a9be3

boa info command on Linode server:
https://gist.github.com/leevh/6a83158b6272ba20dbe0b048bf27a16c

My fix has been running `octopus up-head all force` to fix the certs and get everything running again.

Any thoughts would be awesome, thank you!

**Comment by leevh** [comment]
This happened again two days ago, however this time it didn't say it "aborted".  Mysql crashed somehow and upon restart there seems to become a cert problem.

https://gist.github.com/leevh/24cff860e1a040ee87e5d296b29c6993

**Comment by omega8cc** [comment]
This looks more like failing filesystem, unfortunately..
