### ISSUE TITLE
Composer install platform = Composer killed

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1666]
Hi all, since the recent automatic update my new platform installs fail with "composer killed" - see below and $ boa info here https://pastebin.com/J8DGfVJf

Any ideas please?

```
o1.ftp@barbican:~/static/platforms/93-19-200722$ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Killed
o1.ftp@barbican:~/static/platforms/93-19-200722$ composer --version 
Composer version 2.0.14 2021-05-21 17:03:37
```

**Comment by Juc1** [comment]
Could this be a memory issue - has the recent automatic update affected my memory_limit somewhere?

**Comment by Juc1** [comment]
Hi all my Composer used to run fine but since the recent automatic update i always get out of memory errors - if I need to increase my memory limit can anyone please tell me the relevant file I need to edit.

boa info more = https://pastebin.com/MRemgEyf

**Comment by omega8cc** [comment]
4 GB RAM should be more than enough for Composer 2, and BOA will not kill any high memory php process anyway, it's normally a sign of your parent host system intervention killing high-mem processes arbitrarily.
