### ISSUE TITLE
Query re custom static platform core /modules permissions - no o_contrib_seven link (actual directory and modules placed there) !

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1667]
Hello, 

On some D7 custom platforms built with the standard core and drush (so, not built with composer and not using the om-7.x core) we are repeatedly finding that the o_contrib_seven link is not present in platform/modules (and thus those modules are not available ) - because the platform core modules directory is set to 2755 and not 2775 as needed. Setting that directories' permission to 2775 will cause the o_contrib_seven directory with the o_contrib_seven modules in it ( not the symlink !) to be put there where needed on a platform verify task. I repeat after changing the platform/modules directories permission to 755 the o_contrib_seven directory with the modules inside it are put there and become available to the sites using that platform.  However on our other BOA server, it is a symlink to /data/ ... o_contrib_seven , which directory + modules are shared by all platforms (I believe). Is this new? Or Is this intended - to put the actual o_cnotrib_seven modules directly into platform/modules ?  Or am I making a mistake changing the permissions to allow that to happen, and my real problem is elsewhere?

The reason why I notice this is because the platform fails to verify on a platform verify task and the reason given is that the core modules directory is not writable!

So my questions are - 
1) would using the omega8 7.x core change this behavior and mean that I wouldn't need to set the permissions manually?
and
2) Wouldn't it be a good idea (if teh above is intended) to force the permissions on that directory to be set to 2775 at an earlier point in the task verify procedure so that the links to the o_contrib_7 directory are always there?

This is on latest head with a standard setup and enough RAM, etc. 

boa info more is:
https://gist.github.com/EdNett/57e98b37eaaf08e31424e2ae62ebe5e3

Best regards,

Ed

**Comment by omega8cc** [comment]
If you have a `o_contrib_seven` directory and not a symlink, it's usually a result of creating platform with codebase using rsync with symlinks converted to local copy of directory by the person managing the platform creation.

BOA will always create only symlinks there.

In the meantime we have improved the logic in Aegir so on platform verify it will check and rename `modules/o_contrib_seven` to `modules/.o_contrib_seven_dont_use` if it's a directory and will then add expected symlink instead.
