### ISSUE TITLE
Ruby 3.0.2 install reported as failed on new head install on Buster

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1670]
BOA [08:32:44] ==> INFO: Installing Adminer Manager...
BOA [08:32:44] ==> INFO: Adminer Manager installed

BOA [08:32:44] ==> INFO: Running Ruby with RVM install...
BOA [08:38:10] ==> WARN: Ruby 3.0.2 install failed!

boa info more : https://gist.github.com/EdNett/cc50ed88b6b4a5e9f0b6d55ab1b92627

**Comment by EdNett** [comment]
error seen here during second (head upgrade failure) attempt to install:
https://gist.github.com/EdNett/6ba37a5b05951def642d24bc256e1ed8

**Comment by omega8cc** [comment]
Buster support was fixed along with added all other supported Debian/Devuan variants recently.
