### ISSUE TITLE
libstring-mkpasswd-perl needs to be installed for buster

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1673]
server1:~# mkpasswd
-bash: mkpasswd: command not found
server1:~# aptitude show libstring-mkpasswd-perl
Package: libstring-mkpasswd-perl
Version: 0.05-1
New: yes
State: not installed
Priority: optional
Section: perl

the lack of it is producing this error on fresh head install on buster:

BOA [08:45:48] ==> INIT A: Adding ftps/lshell user
/opt/tmp/boa/lib/functions/satellite.sh.inc: line 2974: mkpasswd: command not found
BOA [08:45:48] ==> INIT A: Adding symlink to the sites backups

boa infor more:  https://gist.github.com/EdNett/cc50ed88b6b4a5e9f0b6d55ab1b92627

**Comment by zanami** [comment]
this one is strangely enough resolved by _apt install whois_

**Comment by omega8cc** [comment]
Buster support was fixed along with added all other supported Debian/Devuan variants recently.
