### ISSUE TITLE
initial install of head on stretch fails - hangs at mysql set innodb log size = 256 MB ->  "--skip-innodb-use-native-aio" argument should be used for percona  5.7 install / start command , I believe

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1674]
initial boa install:

gist is here:  https://gist.github.com/EdNett/5152c022388ffad5c9c3caebed38210b

boa info more:  (had to abort initial install because it hung for over an hour - with no load at all):

https://gist.github.com/EdNett/ad1da6d9abade4302d1973c85a77063d

Is it necessary to install/start mysql with innodb_native_aio ?  I think this is the problem - as it is a change from previous install/start commands, isn't it?

You can disable Linux Native AIO by setting innodb_native_aio = off in my.cnf - ( but doing that after the failed install doesn't help.),  but mysqld --verbose --help says you must do --skip-innodb-use-native-aio

**Comment by omega8cc** [comment]
It should work normally for a long time already.
