### ISSUE TITLE
Aegir page not working (throwing http error 500)

### ISSUE THREAD

**Issue by r-unny** [omega8cc/boa#1675]
I expect my page to be reachable at https://o1.[SERVER-HOSTNAME]

In error logs only thing I see is:
```
2022/08/18 17:16:13 [warn] 31172#0: *37 using uninitialized "user_socket" variable, client: [IP], server: [HOSTNAME], request: "GET / HTTP/2.0", host: "[HOSTNAME]"
2022/08/19 04:09:37 [warn] 27721#0: *2199 using uninitialized "user_socket" variable, client: [IP], server: [HOSTNAME], request: "GET / HTTP/1.1", host: "[HOSTNAME]"
```

It was working properly before, I don't know when and what caused this error. 

When I tried to update system I get:

```
BOA [14:38:11] ==> Skynet Agent v.BOA-4.1.4-dev welcomes you aboard!
BOA [14:38:14] ==> INFO: UPGRADE
BOA [14:38:19] ==> VIRT: This system is supported: Linux KVM guest
BOA [14:38:19] ==> Aegir on [[HOSTNAME]]([HOSTNAME]) Debian/stretch x86_64 PHP 7.3
BOA [14:38:28] ==> ERROR: This BARRACUDA version is outdated and will not work correctly
BOA [14:38:28] ==> Bye
```

Somehow I switched to dev branch of BOA, I don't know how to go back to release.

**Comment by r-unny** [comment]
I did run the following: 
```
    $ screen
    $ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
    $ barracuda up-head log
```

**Comment by omega8cc** [comment]
The error referencing `user_socket` means you have configured PHP-FPM version which is not installed or broken.

Make sure you have the expected PHP-FPM running and then switch back and forth versions in `~/static/control/fpm.info` and `~/static/control/multi-fpm.info` to available versions (wait 5-6 minutes after each update).

If this doesn't help, force the update by deleting these files in ~/static/control/

`rm -f ~/static/control/.ctrl*`
`rm -f ~/static/control/.multi*`
`rm -f ~/static/control/.single*`

**Comment by omega8cc** [comment]
Note, the `v.BOA-4.1.4-dev` was actually new stable and later renamed to `v.BOA-4.1.4-rel`, as we no longer make releases, since it covers too many components which can be upgraded by Debian packages on every `barracuda up-head`, even without any BOA release, so BOA releases for just some components upgrades and nothing major otherwise were pointless.
