### ISSUE TITLE
errors with barracuda up-head - plus rvm install when not wanted ...

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1679]
There are errors with a current barracuda up-head - it failed -

and then I ran barracuda up-head system and there was a ruby rvm install even though I didn't want one!

Here is terminal :
https://gist.github.com/EdNett/725200e5dba1ca2d29b08eb6de2f315d

boa info more here:
https://gist.github.com/EdNett/a8cf30f4b91c7d1e299d4dafe77f9c26

Best regards,

Ed

**Comment by omega8cc** [comment]
BOA will install RVM if you have either `ALL` or `CSS` keywords in the `_XTRAS_LIST` variable in `/root/.barracuda.cnf`
