### ISSUE TITLE
Bug on Fresh Linode / Debian9 included gist **need help PLS**: Starting Nginx Server...:nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/conf.d/aegir.conf:90 

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#1681]
Sorry for my earlier posts. I really need your help.... or if you can point me in the right direction that would be great.
**If you need any specific log, or there is any log I can check please let me know**.

No matter what, I cant get octopus/barracuda running. 

**The only commands I type after ssh into my server are :**

**_**I have not tried to do a fresh install by not sshing into server and logging in manually. I will do that next.**_**

cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
boa in-head public server.ifiwaspotus.com robertp.eaton@gmail.com o1
BOA [16:55:18] ==> INSTALL START -> checkpoint:
```

    * Your email address is robertp.eaton@gmail.com
    * Your IP address is 74.207.244.244
    * Your hostname is server.ifiwaspotus.com

```
- I have set my wildcard  in A records to *  my domain. 
- I have also tried setting A records to include "server"  And   "master. There is no effect.

see screenshot:
https://snipboard.io/qFZ6rh.jpg

** I am running the 8gb/4cpu server
no matter what I do I get

**ERR_CONNECTION_REFUSED**

- I reboot after install, run upgrade, and reboot again.
- I can'i connect to domain. 

So, I have no seen that nginx status shows:

```
erver:~# service nginx status
[warn] Nginx Server... is NOT running. ... (warning).
server:~# service nginx start
[....] Starting Nginx Server...:nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/conf.d/aegir.conf:90
```

https://gist.github.com/AntiNSA/40ffdee91fd533f20893f10644977ae7

**Comment by AntiNSA** [comment]
And when I remove the TLSv1.3 from the aegir.conf I get a new error

server:~# service nginx start
[....] Starting Nginx Server...:nginx: [emerg] unknown directive "geoip_country" in /etc/nginx/conf.d/aegir.conf:95

**Comment by AntiNSA** [comment]
okay, just rebooted after a fresh install. No database error after the upgrade... I did not attempt to add any other php versions or install postfix first. 

however nginx isnt running and still gives the error and doesnt start/run

[....] Starting Nginx Server...:nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/conf.d/aegir.conf:90
. ok

**Comment by AntiNSA** [comment]
after removing ttlsv1.3 still recive the message
[emerg] unknown directive "geoip_country" in /etc/nginx/conf.d/aegir.conf:95

**Comment by AntiNSA** [comment]
If I comment that out I recieve the error [....] Starting Nginx Server...:nginx: [emerg] unknown directive "fastcgi_cache_purge" in /var/aegir/config/server_master/nginx/pre.d/nginx_speed_purge.conf:20
. ok

**Comment by AntiNSA** [comment]
If I delete that section I get the error when trying to start nginx

[warn] invalid value "TLSv1.3" in /var/aegir/config/server_master/nginx/pre.d/nginx_wild_ssl.conf:12
. ok

**Comment by AntiNSA** [comment]
when commenting that out I get the following error 

[....] Starting Nginx Server...:nginx: [emerg] unknown directive "flv" in /data/disk/o1/config/includes/nginx_vhost_common.conf:672

**Comment by AntiNSA** [comment]
well no matter how I do it, I cant get nginx to run after a fresh install on a linode / debian 9. I have tried wiht the network helper off and on. I will try debian 10, but always the TLSv1.3 issue.

**Comment by AntiNSA** [comment]
Am I shadowbanned or something from this group? Can anybody hear me?

**Comment by AntiNSA** [comment]
Okay, I have read a post in this issue queue that suggested to set a 

**-    *.server.mydomain.com wildcard in the domain "A" records.
_I have done that._  

Right now I am in the process of updating my server with 

`barracuda up-head system` 

I will restart it twice after that.

- I have also removed the www from my aname dns setup and placed it instead in the CNAME section of the DNS zone.

**I have just noticed that when I type** 

_- **ifiwaspotus.com** I am receiving the error_

```

www.ifiwaspotus.com refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```


[Screenshot]   https://snipboard.io/ajg2vr.jpg


So... thats wierd.  I didnt type www,ifiwaspotus.com . Yet the error message is showing as if I would have.


Shot in the dark, but I r**emoved the www  from the A section and instead placed it in the CNAME section** so that it will be redirected to the ifiwaspotus.com domain.

Maybe that is creating some sort of loop.

I will do a fresh install after that A-name adjustment to see if there is any positive result.

After that I will download every log I can find and see if there is anything that stands out.

**Comment by AntiNSA** [comment]
Okay, I have read that www must point to an actual ip for https stuff.

So I did the following:
removed from cname entry and added it in A name record only.

I created a separate issue about linode trying to add a certain port to the network interfaces:
https://github.com/omega8cc/boa/issues/1683

So I disabled network helper, ant this is now what my /etc/network/interfaces looks like:

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
address 74.207.244.244
netmask 255.255.255.0
gateway 74.207.244.1
```

So after going through the setup, updating and restarting twice, and:

- Added *.server.ifiwaspotus.com

I still have  a problem that nginx hasnt started and gives the same error

**Comment by AntiNSA** [comment]
Hi ... I have been working on this in every bit of my spare time to try to figure out why this is not working on my server. 

I know you guys must be very busy with all of your hard work too. I appreciate it you letting everyone use this code.

 Im not giving up yet, but if I am making a stupid mistake or  you could point me in the right direction to help me with this troubleshooting that would really be awesome.

**Comment by omega8cc** [comment]
It should work normally for a long time already.
