### ISSUE TITLE
Linode Network Helper Adds [port 24] 74.207.244.244/24 in /etc/network/interfaces on every fresh linode. IS this a bad thing for boa?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#1683]
On a fresh linode the port is being defined as 24 in the /etc/network/interfaces

- After a fresh boa install it is also listed the same.
- Is this okay? 
- Should I remove that port entry? 
- This is a result of the default Network helper setting in the admin control panel which is switched on by default. 
Screenshot: https://snipboard.io/6YOBC7.jpg
- Does Boa need network helper on or off on a fresh Linode?

source /etc/network/interfaces.d/*

auto eth0

allow-hotplug eth0

iface eth0 inet6 auto
iface eth0 inet static
    address 74.207.244.244/24
    gateway 74.207.244.1

**Comment by omega8cc** [comment]
You don't need to modify anything in the networking, it should work. By the way, it's not a port but subnet.
