### ISSUE TITLE
Hello? Is there anyone out there?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#1684]
I really hope this project is still alive. I am only writing this post because I am afraid I am talking to myself. Ive been trying more than a week to get Boa running on linode to no avail. Is this project alive? has anyone got it to run on debian 9 fresh linode?

**Comment by AntiNSA** [comment]
Hi... We are really not a rich family and I am trying for so many valuable hours to get this going on a server. I am using debian 9 and have tried everything I can think of. Can anyone help really appreciate it. If we can ever make any money I will pay for the omega8cc hosting service. We are somewhat poor and I am just tryong to make something successfull so I can spend more time with my kids. Thanks for any help.

**Comment by Juc1** [comment]
@AntiNSA if you look at the issue queue you will see that many issues are unresolved / unanswered - even if you resolve your current issue you are likely to run into another one. Also https://gitter.im/omega8cc/boa used to be busy but is now almost dead. So I would suggest that the self install BOA project is not healthy and you should  look at alternatives.

**Comment by omega8cc** [comment]
BOA is a mature / legacy project with stalled development in the public repository because it is under major rewrite which negates or fixes or makes irrelevant most of still opened tickets here. We are still not ready to make it public, so in the meantime we will gradually review and close tickets and submit patches to make it compatible with current Debian stable — it will happen later this month.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AntiNSA** [comment]
LAter this month? Thank God! So we can use BOAs new version that will work later this month? I am so happy to hear that. I will not attempt going through the huge process of trying to make a unefficient multisite failure on my linode and will wait for BOA.

I can not thank you enough.

IS it possible to get the equivalent VPS like the linode I have, 4 cpu 8 gig of ram 160 gb of storage for 50USD a month with a working copy of BOA on it? 

If so I will stop linode and join your omega8 hosting service.

**Comment by RamPer46** [comment]
@AntiNSA, I can _totally_ relate to your feeling. Like you, I was concerned about whether this project is still active. Web development is basically a hobby for me, but instinctively I recognized the quality and the extensive effort behind the BOA setup. However, I have been frustrated multiple times in the years past in getting it to work. When it works, it's beautiful. So I am sticking with BOA despite the frustrations! Like you, I do intent to pay the BOA developers someday. :)

I really do not want to go back to manual set up of Drupal sites. I am not even too keen on setting up just Aegir alone, although many times I was tempted to do so. I am even concerned if the Aegir project is still active. So many things have changed in the Drupal landscape itself, IMO, that it feels somewhat less friendly these days to the la(z)y hobbyist like me.

Best of luck! There are too many "moving parts" in this set up that I invariably keep my fingers crossed during installation and even during updates. Things have gotten better over the years though (in my experience, obviously), so I keep coming back to BOA after months of inactivity on my part and the occasional frustrations during the install process.

**Comment by AntiNSA** [comment]
@RamPer46 

You know, you're absolutely right.

I was a teacher in China for about 18 years and I used boa heavily until my wife got very ill and I had to stop working so hard.

I was never successful money-wise, but wasn't trying to really make money with it I was doing it for my students.

I never knew how to manage the server. I had a donated host from a long time ago, but all my students using it were too much for the donation and I had to figure out how to manage my own server.

I was in some IRC chat room during the Arab spring and listening to the guys that worked at Al Jazeera talk about using Nginx, and then I learned how to put the lemp stack on a linode server.

Then I discovered boa.

I must have spent like hundreds of hours with it. It was so awesome.

After being out of the loop, it seems that everybody is doing K8s...

Which seems super awesome actually, except for the fact that from what I could tell they managed to charge for every kind of operation. If it wasn't for the high cost the scalability and simplicity would be great.

But from what I understand if you make a mistake you could be paying $15,000 a month.

My budget is about $50 a month.

After coming back to the United States after about 25 years away in Eastern Germany and China, my life has no meaning here.

I don't have an American degree, and there's no company that cares about my experience. I'm struggling after being fired is an Uber driver for 3 years for some stupid passenger making a false accusation that I was driving intoxicated to get a free ride.

I'm not suicidal, but I was almost when that happened. I have two disabled kids and my wife has disabilities so I'm the only guy working.

So I know everybody's got a challenge in life.

I own a bunch of different domains, that I really want to try to do stuff with.

I know it's like a lottery ticket but it's my only hope for my family one day I guess.

I'm getting my CDL but I delivered groceries from Walmart and my life is little meaning other than to give my children a future.

I own the following domains

Thecenterofthenet.com
Ifiwaspotus.com
Haveread.com
Usedthat.com
Carpoolu.com
Mancanthink.com
Whatsizetool.com
Newcipher.com
Newscypher.com

I want to try to develop
Ifiwaspotus.com

And make a reading tracker for my kids and for the classrooms for other kids to use to track their reading and so they could discover good books to read from other kids and other people and maybe the public could use ithaveread.com

And I'm the only person that drives in my family and the public transportation sucks in the United States and I'm trying to make a car point site for my child and other kids to network for their parents to find the kids ride to school no way I could afford three circles right now.

From what I could tell aeigir is not really being developed anymore.

I guess I'll do rich commercial developers that charge $45,000 for a Drupal website they could afford to pay for the K8s...

I can't even get a job as tech support in the United States without a degree.

So if forward doesn't ever get into development, right now I'm trying to figure out how to run a multi-site d9 or d10 linode..

And I work 70 to 90 hours a week delivering groceries. So it's really a pain in the butt.

I really hope that BOA doesn't die. I can't afford to take a day off of work or two or three to hit my head up against the wall to get the multisite going.

**Comment by omega8cc** [comment]
BOA now supports all supported/latest Debian and Devuan releases.
