### ISSUE TITLE
Theory: New installations of  BOA cant work on Debian 9 because  Let's Encrypt cant be installed due to certbot not working on D9 creating SSL issues = BOA failure

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#1685]
Okay , here is what I  think:

I am having an issue no matter what I do with not being able to get nginx running due to the 
TLSv3 https://github.com/omega8cc/boa/issues/1681 issue.

When I try to disable that, I get a slew of other issues.

I am not sure what TLSv3 is, but accorging to the config section it is related to SSL.

 
In the SSL readme Doc, it lists a lot of clear warnings about jusing elts encrypt and SSL in general.

SO I read linodes guide to installing lets encrypt on a linode, and the process always fails due to the fact that certbot will not work or doesnt support Debian 9 anymore.

And I cant get BOA installed on Debian 10, and the disk image of Ubuntu on linode is too new and it wont intall on that either.

SO without a newer linux distro that certbot supports, you can no longer install BOA at all.

SO how is it running on so many systems already?

My guess is that the people running Boa installed it on their systems back when certbot and lets encrypt supported Debian 9 and have maintained that running installation without doing a fresh install...

At least thats my theory.

**Comment by RamPer46** [comment]
@AntiNSA, you may be right. I tried installing BOA on VPS. The installation went through fine, got the initial login links, but they were not redirecting to the "https" address automatically like they used to. Further probing shows with what little I know shows the same issue you've referred to: "TLSv1.3".

And your guess about people running BOA based on an earlier install is spot on too!
I suppose I'll wait for the new release to come along.

P.S.
Please disregard my email to you (yes, I emailed you! :) ) about offering my BOA installation for you to try it out until the new release comes along. Even though the installation went through fine, it's not redirecting to https.

**Comment by omega8cc** [comment]
BOA now supports all supported/latest Debian and Devuan releases.
