### ISSUE TITLE
After recent barracuda + octopus head updates (on stretch) - Cron is disabled on all sites when verification is performed. Thus hostmaster and barracuda master are not running cron since they auto-verify on up-head! Problem!

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1687]
After recent barracuda + octopus head updates (on stretch) - Cron is disabled on all sites when verification is performed. This happens also on the barracuda master and octopus hostmaster sites which are automatically verified after the up-head. This is a serious problem as websites will start going down. Editing the site settings (for any period of cron) does not work, because as soon as it verifies, it is disabled again.

boa info more here:
https://gist.github.com/EdNett/ac87b3993bf3966264fd2e9d5f6d2985

What to do? Can I provide you with any additional information to help resolve/fix this bug?  

Best,

Ed

**Comment by 7o7o** [comment]
I'm seeing this too after upgrade, also on stretch. Everything else seems to work fine.
I haven't checked on a fresh BOA yet.

**Comment by EdNett** [comment]
This problem appears to have been resolved. Although in the Octopus GUI the site that has been verified has its Cron setting listed as disabled, and although doing a "Status Report" on the site as a logged-in Admin will report that cron hasn't been run for 2 or 3 weeks (since the last up-head), today I find that editing the site to have cron run at once per hour, or 3 min, etc. will trigger cron running - and it is verified in the logs. So - the display issue of cron still being listed as Disabled on the Octopus GUI remains, but the chosen cron setting is being respected, and cron is being run!

**Comment by omega8cc** [comment]
Please run Octopus upgrade to get this regression fixed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
