### ISSUE TITLE
Remote import fails if MyQuick is enabled

### ISSUE THREAD

**Issue by zanami** [omega8cc/boa#1691]
Just FYI and YMMV

This is what I'm trying to do [/omega8cc/boa/blob/master/docs/REMOTE.txt](/omega8cc/boa/blob/master/docs/REMOTE.txt)

The "target" server is empty, just installed with boa in-head

If [MyQuick](https://github.com/omega8cc/boa/blob/master/docs/MYQUICK.txt) is enabled (it is by default) I get this during "import remote site" task

```
DEBUG MyQuick import_site_database db.php fail oct_db_dirx /data/disk/o1/backups/tmp_expim
Database import failed (dir: /data/disk/o1/backups/tmp_expim)
```

After disabling MyQuick on both target and source servers everything works as expected.

to disable remove ~/static/control/MyQuick.info
to keep it disabled add ~/static/control/MyClassic.info otherwise looks like MyQuick.info [is recreated](https://github.com/omega8cc/boa/blob/master/BOA.sh.txt#L744) at BOA update

**Comment by omega8cc** [comment]
That's correct, thank you for the report.
