### ISSUE TITLE
Query re Newer updated versions of PHP - can we safely update php ourselves or must we wait until you add newer versions to the update script?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1692]
Hello,

I would like to know if we can safely update php 7.4, 8.0 and 8.1 ourselves with an aptitude safe-upgrade or aptitude full-upgrade or must we wait until you add newer versions to the update script?

Thanks for your response.

Best,

Ed

**Comment by reswild** [comment]
Boa builds PHP from source, so you can't update these version using apt.
