### ISSUE TITLE
Question re possible drush error when atttempting a dbup

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1696]
Running latest head with percona and php 8.0.28

I cannot do a database update on a drupal 9.54 site and I keep getting this error. Does this mean that the version of drush I am using is incompatible with something in this site? If so, is there any way to call a different version of drush from the o2 command line when running the dbup command? How? Could anyone knowledgable please answer? Thanks

The error is:

Error: Call to undefined method                                                          [error]
Drupal\Core\Entity\EntityDefinitionUpdateManager::applyUpdates() in
drush_update_entity_definitions() (line 315 of
/opt/tools/drush/8/drush/commands/core/drupal/update.inc)

Thanks for any help,

Ed

**Comment by omega8cc** [comment]
Drush 8 still needs more work before it's ready for PHP 8, even if PHP 8.1 and 8.2 are listed as supported officially. In reality there are still some issues.
