### ISSUE TITLE
Failed up-head caused Master Barracuda instances to not resolve (? php8.0-cli error?) - They resolve to "Under Construction" Page or NginX 404 error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1697]
Hi,

I'm on head - last barracuda update was feb 27 2023, in which I changed php-cli to 8.0 from 7.4 for the first time, as I couldn't install a social platform with composer otherwise. I am going to run a new up-head as soon as daily script finishes and will close this issue if that resolves the problem - UPDATE - after a new up-head the problem persists.  Could this be a php version error? Hard to believe?

I just noticed that the Master Barracuda instances no longer resolve - They resolve to "Under Construction" Page or NginX 404 error

I can see that in /var/aegir/host_master/024/sites/ there is a master barracuda site, 
but in /var/aegir/host_master/025/sites there is nothing at all

/025/ is the last hostmaster platform directory.  What to do? Should I copy everything from /024/sites/ to /025/sites/  ? Could that be a simple workaround for now? Also, how to verify that hostmaster master site is running hourly cron?

I also notice that in /var/aegir/backups/ there is a backup of the master, but not from the last barracuda up-head on feb 27, but from the next-to-last barracuda up-head I did on feb 17! (so I shouldn't try to restore this backup into today's march 11 /025/ sites/ ? Is that right?

INFO: on the feb 27 barracuda up-head it abotred while installing provision- there was a failure "drush is broken", etc shown here: 
https://gist.github.com/EdNett/fcc25254c654ee64098cbf90df1732af

So I waited an hour and ran another barracuda up-head and although it appeared to be a success there were errors in the log here:
https://gist.github.com/EdNett/3c5c19c9e8859cb9bdf877f75b7cbf81

I hope the barracuda cron is running, because I noticed that tasks had stopped on the octopus instance today.

boa info more is here:
https://gist.github.com/EdNett/bdf16f8a852b01ca2cf3c0ddbca217c4

Thanks for help

Best regards,

Ed

**Comment by EdNett** [comment]
Does anyone know if it would be possible to get the master barracuda instances resolving so that I could login to them by simply creating a symlink somewhere?  Or by modifying the path to the working hostmaster site somewhere? If so, could you tell me the file name, and symlink location, please? 

Thanks

**Comment by timlievens** [comment]
> Not a solution for your problem but you can install platforms with dependency on higher php version:

composer install --ignore-platform-reqs

**Comment by EdNett** [comment]
Thanks for that - I hadn't thought of it.

**Comment by EdNett** [comment]
I can confirm that re-running a barracuda up-head specifying php7.4 as cli reinstalls properly it seems, the barracuda master instance. Shall I leave this issue open since I imagine the goal is to be able to use 8.0 and 8.1 in the cli ?

**Comment by omega8cc** [comment]
Do not use PHP 8 for cli yet -- at least not when you plan to run Aegir upgrades, we are still working on remaining issues.
