### ISSUE TITLE
Mar 20 up-head caused additional redis module to be put in /sites/all/modules:  problem causing HTTP Error 500 - no resolution

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1698]
The March 20 up-head we did caused an additional copy of the redis module to be put in sites/all/modules producing - HTTP Error 500 - the "fix" is to remove addiitonal redis module in /sites/all/modules  This is for D7 only.

Gist of errors shown is here:
https://gist.github.com/EdNett/5520185d691f506bd9263c0824374253

Probably a good idea to check resolution of sites using redis.

boa info more here:
https://gist.github.com/EdNett/d6ade76a348d964610813e06537a3e2e

Best Ed

**Comment by EdNett** [comment]
Actually thi sproblem is worse than I originally thought. It affects all the sites in drupal 7 (all are 7.95) with redis enabled (not just the sites also with httprl enabled)!

**Comment by omega8cc** [comment]
Not sure why you would experience the very old bug now, since it was fixed a long time ago, although you may need to delete the extra redis module in /sites/all/modules if it's still there for some reason -- but  it was there probably for a long time, not recently added.
