### ISSUE TITLE
mongodb driver for php 7.4.33 and 8.1.18 fail on pre-chimera up-head on stretch also fail on up-stable 4.2.0 chimera

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1704]
[10:36:36] ==> INFO: Installing MongoDB driver 1.2.5 for PHP 7.4.33...
BOA [10:37:10] ==> WARN: Installing MongoDB driver for PHP 7.4.33 failed!

BOA [10:53:26] ==> INFO: Installing MongoDB driver 1.2.5 for PHP 8.1.18...
BOA [10:53:54] ==> WARN: Installing MongoDB driver for PHP 8.1.18 failed!
 
 BOA [10:56:22] ==> INFO: Installing MongoDB 1.6.14 PHP driver upgrade for PHP 8.1.18...
BOA [10:56:50] ==> WARN: Installing MongoDB driver for PHP 8.1.18 failed!

boa info more is here:
https://gist.github.com/EdNett/8c0b8e0f6dfcfaf0f7c91fa125360c5f

Perhaps the error will be rectified in up to Chimera / devuan which I will now do. The error did not go away.

**Comment by omega8cc** [comment]
We no longer test this driver for years, so not sure, perhaps it's too old. Are you using it for anything?

**Comment by EdNett** [comment]
no, we are not using it anylonger; Thanks for asking. I was just bug reporting.
