### ISSUE TITLE
after upgrade to Chimera, barracuda up-head installs php 5.6 which is unwanted

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1705]
after upgrade to Chimera, barracuda up-head installs php 5.6 and other unwanted versions of php.  This problem still exists in recent up-stable 4.2.0, it appears. Even with the control file , 5.6 is not removed. Is this because of the /static/control/multi-fpm.info placeholder line with 5.6 listed? I'll try changing that to 7.4 and run it again, once I think octopus up-stabel or upè-head is working again.

I saw the added line
_PHP_MULTI_INSTALL = "5.6 7.4 8.0 8.1" at the bottom of the /root/.barracuda.cnf file
after the upgrade from beowolf to chimera, and I deleted the 5.6 from it, but it is installing 5.6 anyways!

boa info more is here:
https://gist.github.com/EdNett/afbd232ce4ee2e05a2345cb15dc57b9e

**Comment by omega8cc** [comment]
You need to replace 5.6 with 7.4 in the line `place.holder.dont.remove` added in `~/static/control/multi-fpm.info` file.
