### ISSUE TITLE
Octopus up-stable (4.2.0)  xdrago post-upgrade tasks start but they never complete (neither of them finish) - daily.sh & manage_ltd_users.sh

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1706]
for up-head:
after upgrading to chimera, and doing barracuda up-head system, and barracuda up-head  and a few reboots, I had the following drush is broken error in doing the octopus-up head:

https://gist.github.com/EdNett/aa125770f36d628ce01363c2bb0929d3

boa info more is here:

https://gist.github.com/EdNett/730e1039e1de2f34b5e93ae2712b03e0

I have tried to run the xdrago post-upgrade tasks, but they never complete (neither of them finish) - even after 2 hours. 
bash /var/xdrago/manage_ltd_users.sh  and
bash /var/xdrago/daily.sh 

I noticed this error earlier in the upgrade process, is it related to xdrago problem? Would it prevent xdrago manage_ltd_users and daily scripts from running and compteing successfully?

BOA [14:40:29] ==> INFO: Fix for PHP libs in Devuan/chimaera
touch: cannot touch '/var/xdrago/log/.php_libs_fix_chimaera_230505-1440.pid': No such file or directory
touch: cannot touch '/var/xdrago/log/.php_libs_fix_beowulf_230505-1440.pid': No such file or directory
BOA [14:40:30] ==> PROC: nginx_install_upgrade

for up-stable (4.2.0) 

I saw this error:
BOA [07:08:03] ==> PROC: provision_backend_dbpass_generate
/opt/tmp/boa/lib/functions/master.sh.inc: line 47: python: command not found
BOA [07:08:05] ==> INFO: Running hosting-dispatch...

and octopus up-stable failed:
1) it failed adding MongoDB php driver for 8.1 and 7.4 (and I imagine 8.0 but I didn't see the failure notice)

2):
BOA [07:15:47] ==> UPGRADE A: Aegir automated install script part A
BOA [07:15:47] ==> UPGRADE A: Checking OCTOPUS version...
BOA [07:15:47] ==> ERROR: This OCTOPUS version is outdated and will not work correctly
BOA [07:15:47] ==> Bye
BOA [07:15:47] ==> FATAL ERROR: AegirSetupA installer failed
BOA [07:15:47] ==> FATAL ERROR: Aborting Octopus installer NOW!

boa info more for up-stable is here:
https://gist.github.com/EdNett/fa4eb4a3fd37be3d9358db4b06e186e0

**Comment by EdNett** [comment]
I don't know if I should close this out, but I just did an octopus up-stable (without doing another barracuda up-stable), and although the message was a failure, the task queue did start running again on the octopus instance. I will issue the new bug report separately. Thanks for the quick fix - I think enforcing php7.4 for octopus was what did the trick.

**Comment by omega8cc** [comment]
We have moved the fast moving and breaking stuff updates to dev branch, so please use head/stable for production systems.
