### ISSUE TITLE
Platform build fail - deploying from a Git repository

### ISSUE THREAD

**Issue by dserrato** [omega8cc/boa#1707]
Wondering if anyone has any insight. As of a few days ago, could build platforms from a Git repository just fine. 

Yesterday, went to build a new platform from one of our composer.json files on Bitbucket and it failed right away and had the following error:

```
Finished running: `cd '/data/disk/o1/static/test_agc_2.0.13' && git checkout '2.0.13'` | - | success
-- | -- | --
Executing: `cd '/data/disk/o1/static/test_agc_2.0.13' && composer create-project --no-dev --no-interaction --no-progress` | - | notice
  | - | notice
  | - | notice
[Symfony\Component\Console\Exception\CommandNotFoundException] | - | notice
Command "cd" is not defined. | - | notice
  | - | notice
  | - | notice
An error occured when running command! (returned 1)
```

I've tried different composer.json files for different sites and the same result. 

We have not done any server updates recently that would have changed things, so I'm really perplexed on this brand new problem. 

Tested creating a platform using an old Makefile and it worked just fine. 

Tried using a composer.json file on github repo to see if it was related to Bitbucket, but had the same failure. 

Hoping someone else might have some insight.
Thanks.
Dan

**Comment by dserrato** [comment]
Ok. So, when you say separately configured... does that mean there is a way for us to change configuration so that it is working as before? We have been using composer builds for the last couple of years for numerous platforms and they work absolutely great and we've been so thankful for that feature.

**Comment by dserrato** [comment]
Thank you so much for responding with so much information. We will do our best to test or assist if we can, but we might not know what to do. 
Would a BOA update maybe set things in proper order?

**Comment by omega8cc** [comment]
Yes, since we now know about the problem thanks to your bug report, we know what to check and fix to make it working again. Thank you!

**Comment by omega8cc** [comment]
This update has caused more problems than we expected, so we are reverting it in BOA stable to pre-rewrite state -- automatically in the next few minutes for everyone. Once the new version with new feature is ready, it will be a part of new BOA dev release, not stable, until it's confirmed to work flawlessly. We are sorry for the hiccups, it was moving a bit too fast.

**Comment by dserrato** [comment]
Just tested and was able to build the same platform that failed previously. Thank you so much for your attention to this issue. It's so gratefully appreciated!!

**Comment by omega8cc** [comment]
@dserrato We would be grateful for testing this dev version with your workflow, if possible:

https://raw.githubusercontent.com/omega8cc/boa/5.x-dev/aegir/helpers/websh.sh.txt

Simply replace the contents of your `/bin/websh` with the above file, preferably (if something fails) uncommenting also all lines with `### echo` and then running the Aegir task or any other command you are using and see if that still works.

Thanks in advance!

**Comment by omega8cc** [comment]
Since there is no feedback for 3 weeks and our own testing shows no issues, we will introduce the latest changes from 5.x to 4.x
