### ISSUE TITLE
/root/.allow-php-multi-install-cleanup.cnf control file does NOT remove users and groups associated with unwanted php versions

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1710]
/root/.allow-php-multi-install-cleanup.cnf control file does NOT remove users and groups associated with unwanted php versions. Shouldn't it? 
I have removed all references to 56, 70, 71, 72 and 73 on my system manually.

It is not cleaning up all the unwanted entries in /home  either

May 8 boa info more is here:
https://gist.github.com/EdNett/857fdb236862d5636db9a2dc653e4b45

Best,

Ed

**Comment by omega8cc** [comment]
No, it doesn't and shouldn't, because otherwise re-enabling them would be an extra step. It's OK to leave them as-is. Please avoid any manual cleanup like this to avoid problems in the future.
