### ISSUE TITLE
error connecting to DB in octopus up-stable - could be python: command not found error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1711]
During octopus up-stable 4.2.0 to up-stable 4.2.0, I noticed this error connecting to the db by aegir_root : this might be the cause of our boa server problems, and inability to su to o1.ftp, etc..

error here:  https://gist.github.com/EdNett/eeda26ecfbe4c26c2a239cac79a96f8e

Boa info more here: https://gist.github.com/EdNett/0b07e3051196e3806541e3107cd7214d

I tried to use the syncpass fix command, but encountered this error "python: command not found) - which error I have seen numerous times - on each barracuda up and each octopus up , I believe - since upgrading from stretch - those error are shown here:  https://gist.github.com/EdNett/d716278ac99e47346b1248a23c574dcc

server1:~# syncpass fix aegir
INFO: Expected file /var/aegir/backups/system/.aegir_root.pass.txt does not exist
INFO: We will generate new random strong password (32)
/opt/local/bin/syncpass: line 72: python: command not found
ERROR: Auto-generated password for aegir_root system user
ERROR: did not work as expected, please try again
server1:~#

I do not know if you are installing python from sources, or which version 2.7 or 3.x, but aptitude shows python 2.7 is not installed:

server1:~# aptitude show python
No candidate version found for python
Package: python
Version: 2.7.16-1
State: not installed (configuration files remain)
Multi-Arch: allowed
Priority: standard
Section: python
Maintainer: Matthias Klose <doko@debian.org>
Architecture: amd64
Uncompressed Size: 69.6 k

Regards

Ed

**Comment by omega8cc** [comment]
An this server is still on Stretch with latest BOA stable tested:

```
 Skynet Agent v.BOA-4.2.0-stable on Debian/stretch welcomes you aboard

tr5:~# which python
/usr/bin/python
tr5:~# ll /usr/bin/python
lrwxrwxrwx 1 root root 9 Jan 24  2017 /usr/bin/python -> python2.7*
tr5:~# python2 --version
Python 2.7.13
tr5:~# python3 --version
Python 3.5.3
tr5:~#

```

**Comment by EdNett** [comment]
I had to install python with aptitude, now a which python returns /usr/bin/python

which python2 and
which python3 both worked.

Now I have the error, when trying to connect as an octopus user (o1.ftp for example):

Traceback (most recent call last):
  File "/usr/bin/lshell", line 25, in <module>
    from lshell.checkconfig import CheckConfig
ImportError: No module named lshell.checkconfig

I will try to resolve it. Any help is appreciated.

There must have been an error when upgrading from stretch head to chimera stable somewhere...

**Comment by omega8cc** [comment]
Delete these files and then run barracuda upgrade-- it will force rebuild for lshell and any stuff build from sources but broken. Hopefully this helps!

```
 rm -f  /var/xdrago/log/*.pid 
 rm -f  /var/xdrago/log/*.log 
 rm -f  /var/xdrago/log/lshe*

barracuda up-head system

```

**Comment by EdNett** [comment]
Hello,

Thanks for that, yes that worked - I upgraded on stable, not head though.

I'll close this out.

**Comment by omega8cc** [comment]
For clarity, `head == stable` now, while the fast moving `master` moved to `dev`
