### ISSUE TITLE
pp 8.2 doesn't install on up-stable  - neither does php8.1-19 update

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1712]
pp 8.2 doesn't install on up-stable  - neither does php8.1-19 update

**Comment by omega8cc** [comment]
It works in all our tests.

**Comment by EdNett** [comment]
Hi, I tried it again, this time first:

1) removing the /root/allow-php-multi-install-cleanup.cnf file,  AND

2) adding 8.2 to one line in the static/control/multi-fpm.info file as a placeholder.

Could either of these changes have allowed both 8.2 to install and 8.1.18 to update to 8.1.19 ?

Best,

Ed

**Comment by omega8cc** [comment]
In the future please provide such details on your non-standard configuration. Yes, it was absolutely expected with that cleanup file present.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
