### ISSUE TITLE
Upgrade to 4.3 failed on network interface name

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1714]
I am using KVM in ProxMox 7.1 for the Aegir

After the first step to the upgrade Debian 9 to Devuan

    cd;rm -f BOA*; wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt

I was told that it cannot proceed

	ERROR: BOA requires the classic network interface naming convention.
	ERROR: Typically it should be eth0 and not ens3 systemd convention.

	HINTS: You can check your active network interfaces with command:
	HINTS:   ip addr show
	HINTS: to make sure you are in fact using supported naming convention.
	HINTS: You may see names like eth0, eth1, eth2 -- they are supported.

	HINTS: Add these two required parameters to GRUB_CMDLINE_LINUX variable:
	HINTS:   net.ifnames=0 biosdevname=0
	HINTS: in your /etc/default/grub configuration and then activate with
	HINTS:   grub-mkconfig -o /boot/grub/grub.cfg
	HINTS: Once this is done, reboot your system and run this installer again.

	Bye

Once I changed **grub**, the server failed to boot. I did manage to mount and revert so the machine managed to boot again.

This is reported by `ip`

    2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000

Any suggestion how can I solve this?

**Comment by reswild** [comment]
It might not be enough to just edit the grub configuration, you have to make sure that your network actually uses eth0 when it reboots. I had a similar issue on one of my servers where I had to manually change this from ens3 to eth0 in /etc/network/interfaces to get it to boot again.

One potential issue is that many cloud providers use cloud-init to configure your network, so you might have to disable or reconfigure this.

**Comment by EdNett** [comment]
I may have the same problem. After going back in in rescue mode mount /dev/md2 /mnt chroot /mnt and erasing the additions I had made like you, I can't get an update-grup command or other to work. I get these errors:
rescue:/# nano /etc/default/grub
rescue:/# update-grub
/usr/sbin/grub-probe: error: cannot find a device for / (is /dev mounted?).
rescue:/# grub-mkconfig -o /boot/grub/grub.cfg
/usr/sbin/grub-probe: error: cannot find a device for / (is /dev mounted?).

I mounted the entire filesystem, of course mount /dev/md2 /mnt - this for a Hetzner dedicated with two mirrored disks - a software raid, of course!.
root@rescue ~ # cat /proc/mdstat
Personalities : [raid1]
md2 : active raid1 nvme1n1p3[0] nvme0n1p3[1]
      465895744 blocks super 1.2 [2/2] [UU]
      bitmap: 0/4 pages [0KB], 65536KB chunk

md1 : active raid1 nvme1n1p2[0] nvme0n1p2[1]
      523712 blocks super 1.2 [2/2] [UU]

md0 : active raid1 nvme1n1p1[0] nvme0n1p1[1]
      33521664 blocks super 1.2 [2/2] [UU]

I don't have to mount md0, do I, to get grup updates to work? (I rarely do this kind of thing).

My ip addr show returns fine with #2 being eth0 and a state of UP.

Best,

Ed

**Comment by macmladen** [comment]
@EdNett You need to have some mounts before `chroot`

```
# Mounting however that you do it, this was mine, VM virtual ZFS disk
mount -t auto /dev/zd16p1 /mnt/vm102/

# Go into it
cd /mnt/vm102/

# Mount required directories
mount -t proc /proc proc/
mount --rbind /sys sys/
mount --rbind /dev dev/

# Now you can chroot
chroot /mnt/vm102/

# ...and update
update-grub
	Generating grub configuration file ...
	Found linux image: /boot/vmlinuz-4.9.0-19-amd64
	Found initrd image: /boot/initrd.img-4.9.0-19-amd64
	Found linux image: /boot/vmlinuz-4.9.0-18-amd64
	Found initrd image: /boot/initrd.img-4.9.0-18-amd64
	Found linux image: /boot/vmlinuz-4.9.0-17-amd64
	Found initrd image: /boot/initrd.img-4.9.0-17-amd64
	Found linux image: /boot/vmlinuz-4.9.0-16-amd64
	Found initrd image: /boot/initrd.img-4.9.0-16-amd64
	Found linux image: /boot/vmlinuz-4.9.0-13-amd64
	Found initrd image: /boot/initrd.img-4.9.0-13-amd64
	Found Debian GNU/Linux 9 (stretch) on /dev/zd0p1
	done

# Exit chroot
exit

# Reboot your VM
```

**Comment by EdNett** [comment]
Thanks for the tips - I don't understand your style of mount syntax, but I tried to do as you said - and other guides advise the same, but I always hit this error:

root@rescue /mnt # chroot /mnt /bin/bash
rescue:/# update-grub
/usr/sbin/grub-mkconfig: line 253: /boot/grub/grub.cfg.new: No such file or directory

this didn't work either:
ln -s /etc/resolv.conf /mnt/etc/resolv.conf
root@rescue ~ # ln -s /etc/resolv.conf /mnt/etc/resolv.conf
ln: failed to create symbolic link '/mnt/etc/resolv.conf': File exists

I appreciate help - I don't want to take up your time. I'll learn about mount and see if I can't fix this. Thanks for any ideas.
I know I need to umount in reverse order each filesystem I've mounted, and I get  busy signal:
root@rescue ~ # umount /mnt
umount: /mnt: target is busy.

Best,

Ed

**Comment by macmladen** [comment]
@EdNett there are many places to read about the `mount` essentially

    mount -t [type of file system] [device] [mount point]

**Mount point** must be an empty directory, usually at `/mnt/` so mine is `/mnt/vm102/`

The whole idea with `chroot` is to **change the root** temporarily of the file system to that directory for the moment so the commands which assume a certain absolute path can work their job, just like `update-grub`.

So you need to (after booting into rescue)

1. mount the disk you want to fix to the mount point you need to make first (e.g. `mkdir /mnt/mydisk` and then `mount /dev/path-to-my-device /mnt/mydisk`
2. mount `/dev` and others as noted above
3. `chroot /mnt/mydisk` now it is just like you booted into the failed disk
4. repair what is needed, e.g. `update-grub`
5. you may then `reboot`
6. if you wish to unmount but it fails, try `umount -l /mnt/mydisk` which stands for lazy as it will be more patient for the other operations to stop

I'm glad to help as I first hand know how hard and frustrating it is when you get stuck but one also needs to know their way into all of this as this is a very complex game to play.

Explore and read first, be careful as not all mistakes can be corrected.

**Comment by omega8cc** [comment]
Also useful on Devuan: https://www.devuan.org/os/documentation/dev1fanboy/en/network-configuration.html
