### ISSUE TITLE
Redis errors + redis module is being auto-enabled even when set off in site_control_ini - on drupal 7 sites

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1716]
Redis errors + redis module is being auto-enabled even when set off in site_control_ini

error:

Drush command terminated abnormally due to an unrecoverable error. Error: Cannot redeclare redis_autoload() (previously declared in /data/all/000/modules/redis_edge/redis.autoload.inc:16) in /data/all/000/modules/redis/redis.autoload.inc, line 16 | - | error

The external command could not be executed due to an application error.

This is happening on drupal 7 sites

boa info more is here:
https://gist.github.com/EdNett/9999c0f11bcd7330bfd5c1f286e26ddd

Best,

Ed

**Comment by omega8cc** [comment]
We should probably get rid of the legacy `/data/all/000/modules/redis/` at this point.

The `INI` directives will not prevent the module from being enabled, only from being used.

If you want to prevent to auto-enable, disable the procedure with `_MODULES_FIX=NO` in `/root/.barracuda.cnf`

**Comment by EdNett** [comment]
Hello,

This problem still isn't fixed in stable 4.2.0 stable T02 - - Is it suppossed to be? DO I need to move to HEAD for the fix? Can I manually remove the entire /data/all/000/modules/redis_edge/ directory and everything in it? I can see that there is a very recently added file to this directory: "ver-7.x-3.19.1.420prodT02.info"  I still can't enable redis on d7 sites at all.

**Comment by omega8cc** [comment]
No,stable will not receive any non-critical fixes from dev and we can't reproduce this issue anywhere. Please follow the hints in another issue and please don't post duplicates.

**Comment by EdNett** [comment]
This is still a major problem for me - failing to set reis to FALSE in boa_site_control.ini give a 500 no response error! In other words currently redis has to be disabled or the d7 site is down - this is for d7 sites only.
