### ISSUE TITLE
BOA Install stable on Bullseye fails 

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1719]
BOA [05:10:50] ==> INFO: Creating your /root/.o1.octopus.cnf config file
BOA [05:10:51] ==> New Octopus Setup on server1.example.com in progress...

    * Your email address is ...
    * Your client email address is ...
    * Your Aegir control panel for this instance will be available at:
        https://o1.example.com
    * Your Aegir system user for this instance will be o1
    * This Octopus will use PHP-CLI 7.4 for all sites
    * This Octopus will use PHP-FPM 7.4 for all sites
    * This Octopus includes platforms: none
    * This Octopus options are listed as POWER / M / 1 C

BOA [05:10:59] ==> INIT A: Shared platforms code v.001 (new) will be created
BOA [05:26:47] ==> INIT B: FATAL ERROR: Drush is broken (/opt/php74/bin/php /data/disk/o1/tools/drush/drush.php help failed)
BOA [05:26:47] ==> INIT B: FATAL ERROR: Aborting AegirSetupB installer NOW!
BOA [05:26:47] ==> INIT A: FATAL ERROR: AegirSetupB installer failed
BOA [05:26:47] ==> INIT A: FATAL ERROR: Aborting AegirSetupA installer NOW!
BOA [05:26:47] ==> FATAL ERROR: AegirSetupA installer failed
BOA [05:26:47] ==> FATAL ERROR: Aborting Octopus installer NOW!

BOA in-stable completed
Bye

root@server1:~#

boa info more is here: https://gist.github.com/EdNett/050805f926192392bd99a0349bed68d2

**Comment by EdNett** [comment]
When I reboot and try to install an octopus instance I get his error:

ERROR: Please install complete BOA system before trying
ERROR: to install additional Aegir / Octopus instances
Bye

And when I reboot and try to do a barracuda up-stable I get this error: (it hangs on mysql tuning - which I didn't specify and don't want - for at least 1 hour (reattaching screen 1 hour later):

BOA [06:34:17] ==> INFO: Waiting for MySQLD availability before tune_sql_memory_limits...
BOA [06:36:25] ==> INFO: Running MySQLTuner check on all databases
BOA [06:36:25] ==> WAIT: This may take a while, please wait...

So I guess I have to reinstall bullseye and wait for a fix, or try head?  I doubt this problem can be fixed without a complete os reinstall, right?

Best,

Ed

**Comment by omega8cc** [comment]
Have you followed the installation instructions closely? The procedure has changed significantly. We have tested this dozens of times and never had any problems on two different clouds.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
I followed them to the letter. Have you tried a fresh install on bullseye in the last 24 hours?

**Comment by omega8cc** [comment]
We are testing fresh installation and upgrades many times a day, just finished two fresh installations without any issues.

That being said sometimes this error happens during upgrade although I have never seen it during installation.

We have the automated procedure to enforce reinstall when the master Aegir installation fails, but we don’t have similar procedure to enforce reinstalling satellite Octopus instance if this happens at that point.

Still, it’s a side effect of using many downloads from GitHub during installation instead of the old static downloads from our own mirrors which limited the chances to get hit by failed download of some component like in this case.

It’s quite frustrating so definitely a room for improvement exists.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
Great! It installed perfectly this time. Thanks.

**Comment by omega8cc** [comment]
Reopening since it needs more work anyway.

**Comment by EdNett** [comment]
I just did the up-stable to chimera and it gave errors:

EXIT on error due to missing helpers
Please try to run this script again in a few minutes
Also, make sure that the outgoing connections via port 443 work
Bye


BARRACUDA upgrade completed
Bye

but the upgrade appeared tio work:

root@server1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Devuan
Description:    Devuan GNU/Linux 4 (chimaera)
Release:        4
Codename:       chimaera

**Comment by EdNett** [comment]
I tried it again and there was an extremely long wait before a message printed to the screen giving me the tail to watch (I had specified barracuda up-stable log) and then there was another 10 min wiat before seeing any of the tail (this used to happen lightnig fast) and then after a while:

BOA [17:13:26] ==> EXIT on error (provision) due to GitHub downtime
BOA [17:13:26] ==> Please try to run this script again in a few minutes
BOA [17:13:26] ==> You may want to check https://status.github.com/messages
BOA [17:13:26] ==> Bye

I'll give it a pause for the WE.

Best,

Ed

**Comment by EdNett** [comment]
Hello,  I just ran a couple more up-stables (we are already updated to Devuan Chimera) and we have the same nginx permissions problem:  (nginx won't start at all and isn't running):

BOA [11:42:11] ==> JOKE: Just kidding !!! Enjoy your Aegir Hosting System :)

BOA [11:42:15] ==> Final post-upgrade cleaning, one moment...
BOA [11:42:15] ==> PROC: barracuda_cnf_cleanup
BOA [11:42:16] ==> PROC: php_deprecated_cleanup
BOA [11:42:16] ==> PROC: php_single_initd_cleanup
BOA [11:42:16] ==> BYE!

BARRACUDA upgrade completed
Bye

root@server1:~# service nginx status
/etc/init.d/nginx: You don't have permissions to execute nginx.
root@server1:~# service nginx force-reload
/etc/init.d/nginx: You don't have permissions to execute nginx.


boa info more here: https://gist.github.com/EdNett/141a58d32f8fadbdf40c8de967a91ec5

Best regards,

Ed

**Comment by EdNett** [comment]
Even a full_force_reinstall does not fix this problem. How could root no have permissions to execute nginx ?

**Comment by omega8cc** [comment]
Please open separate issue for unrelated stuff.
