### ISSUE TITLE
Feature Request - ability to see progress during upgrade

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1720]
Update - I thought a barracuda up-stable was in progress bullseye to chimera, and I saw no progress in the screen, and after 45 min the screen printed unable to connect to de.omegacc ....  so, althougd ps -a showed 2 barracuda, 1  bash, 1 curl or wget, etc. 1 ps and 1 screen, I guess nothing happened and I am still on bullseye - trying again.

Hello,

A barracuda up-stable does not show any progress in the screen. This has been verified 2 times. At the very end of the upgrade, a message will appear giving the tail of the log (If I specify log in the up-stable command), but by then it's over. 

It would be nice to see the upgrade as it is happening, but it's not essential.

Best,

Ed

**Comment by omega8cc** [comment]
We have reduced the log noise to absolute minimum, but if you wish to watch details it's enough to trigger the "debug" mode, which is basically very verbose messaging for all running procedures -- just `touch /root/.debug-barracuda-installer.cnf` before launching upgrade. It will also display the path to even more verbose log you can watch in another screen/window.

**Comment by omega8cc** [comment]
By the way, if the `/root/.debug-barracuda-installer.cnf` exists, barracuda will skip the Master Aegir upgrade, so it's a system-only upgrade mode.
