### ISSUE TITLE
pdnsd not able to start after up-stable

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1723]
root@server1:~# service pdnsd status
could not access PID file for pdnsd ... failed!
root@server1:~# service pdnsd start
pid file is exist in /var/run/pdnsd.pid, stop it or restart ... (warning).
root@server1:~# service pdnsd restart
Stopping pdnsd.
Starting pdnsd failed!
root@server1:~#

boa info more here:  https://gist.github.com/EdNett/541bbbf7fc177e74e5682b7565beca1f

**Comment by omega8cc** [comment]
This is a consequence of your broken system and not a separate issue, so closing. Please follow up in the original issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
