### ISSUE TITLE
#1716 is not fixed for me on stable - is the fix head only?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1724]
Hello,

This problem - enabling redis in modules/boa_site_control.ini  is causing the entire site to go down and be HTTP ERROR 500 - still isn't fixed in stable 4.2.0 stable T02 - - Is it suppossed to be? DO I need to move to HEAD for the fix? Can I manually remove the entire /data/all/000/modules/redis_edge/ directory and everything in it? I can see that there is a very recently added file to this directory: "ver-7.x-3.19.1.420prodT02.info"  I still can't enable redis on d7 sites at all.

new boa info more is here: https://gist.github.com/EdNett/ec2ef93e07fb64702250118e423cea28

error is the same.

Best,
Ed

**Comment by omega8cc** [comment]
All work is being done in `dev` only, with rare backports to `head/stable`.

Please don't touch anything in `/data/all/000/` !!!!

You ca still delete just the extra `redis` symlink from the affected platform `modules/o_contrib_seven/` and leave only `redis_edge` there.

**Comment by EdNett** [comment]
Hello,

This is such an important issue, with disastrous results - I just did another up-stable and all the sites which I verified after running it were all unreachable with a 500 error - since I use redis on all sites - couldn't you put this in stable, please?

Thanks,

Ed

**Comment by omega8cc** [comment]
All fixes preventing this from happening in the future are already in both stable/head and dev, but it will not automatically remove any duplicate modules from your codebase for you.

Please make sure to run octopus upgrade and not just barracuda upgrade.

Also, remove any duplicate redis module in the affected platform `sites/all/modules/redis` and run registry rebuild if needed.

**Comment by EdNett** [comment]
OK, Thanks for your response. I am getting the error message as follows, and removing the redis symlink - which has been done - doen't help and there is no extra redis modules anywhere including /sites/all/modules:

[I know you said "Please don't touch anything in /data/all/000/ !!!!" - so I haven't - but I want to just remove the redis directory and its contents there! - that would seem to solve the problem] Here's the error:

Successfully connected to the Drupal database. | - | bootstrap
-- | -- | --
Drush bootstrap phase : bootstrap_drupal_full() | - | bootstrap
Drush command terminated abnormally due to an unrecoverable error. Error: Cannot redeclare redis_autoload() (previously declared in /data/all/000/modules/redis_edge/redis.autoload.inc:16) in /data/all/000/modules/redis/redis.autoload.inc, line 16 | - | error
The external command could not be executed due to an application error. | - | error
All caches cleared | - | notice
Command dispatch complete | - | notice
Invoking hosting_flush_cache_task_rollback hooks.

I will run octopus up-stable again and try rebuilding the registry too.  Thanks for the support,

Ed

**Comment by EdNett** [comment]
I guess I am confused as to why I need to delete the symlink for redis and leave alone the symlink for redis_edge - that keeps on reappearing with each new platform of shared default contrib modules -with every octopus upgrade, for example: /data/all/068/o_contrib_seven/

Are you saying that in fact enabling redis in /site/modules/boa_site_control.ini - is actually enabling redis_edge and not redis? 

Why can't I simply get rid of /data/all/000/modules/redis_edge - wouldn't that take care of my drupal 7 site problems? I don't believe I am suing redis_edge unless that is being used by BOA by default ?

Thanks for the advice - please know that the symlink to both redis and redis_edge is being places in each new o_contrib_seven directory with every octopus update.

Best,

Ed

**Comment by EdNett** [comment]
Well, in  any case, I can't recommend that anyone hosting drupal 7 sites who wishes to use redis use stable - it simply doesn't work. I have to disable redis from every d7 site now for the second time.

**Comment by omega8cc** [comment]
It's a duplicate of https://github.com/omega8cc/boa/issues/1661
