### ISSUE TITLE
nginx not starting when NAXSI=YES - may be NAXSI WAF ACCEPT error ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1725]
root@server1:~# service nginx status
/etc/init.d/nginx: You don't have permissions to execute nginx.
root@server1:~#

NginX won't start and it gives me this bizare error; Why? and What to do?

boa info more here: https://gist.github.com/EdNett/e862f0760cf3ec37bcae6a767051050f

Best,

Ed

**Comment by EdNett** [comment]
I'm just going to reinstall the entire server - this thing has never woked properly!

**Comment by EdNett** [comment]
This error arises when I set:

_NGINX_HEADERS=YES
and
_NGINX_NAXSI=YES

in the barracuda.cnf file

I am checking if a full ngx reinstall with those set to NO will allow Nginx to be restarted.

**Comment by omega8cc** [comment]
`_NGINX_NAXSI` was not tested for years, please avoid in production any feature not enabled by default.

**Comment by omega8cc** [comment]
By the way, perhaps `/etc/init.d/nginx` is not executable so you can't use it.

Please check `ll /etc/init.d/nginx`

**Comment by EdNett** [comment]
Hello,  No there is nothing wrong with the permissions of that file. I checked that first thing of course.

Naxsi behaves like a DROP-by-default firewall, the only task is to add required ACCEPT rules for the target website to work properly.  Are the ACCEPT rules being added?

**Comment by omega8cc** [comment]
This experimental feature is not supported currently. We may review it at some point in the future, though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
