### ISSUE TITLE
Querry re grub setup

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1726]
On an initial install on debian 11 bullseye, I find this by default in the /etc/default/grub (I have added the obligitory "net.ifnames=0 biodevname=0")

GRUB_CMDLINE_LINUX_DEFAULT="consoleblank=0"
GRUB_CMDLINE_LINUX="consoleblank=0 systemd.show_status=true net.ifnames=0 biosdevname=0"

Should I leave the "systemd.show_status=true"  in there ? Or should I remove it since BOA is removing systemd?

Best,

Ed

**Comment by omega8cc** [comment]
Never remove anything related to `systemd` manually before the full migration to `systemd-free` Debian or Devuan is complete.
