### ISSUE TITLE
How to enable "usage.sh" on self-hosted servers

### ISSUE THREAD

**Issue by cmastro-ixiam** [omega8cc/boa#1728]
The update of usages of each site has stopped working. 

As we can see in the commit "Fix for xdrago/usage.sh logic" (https://github.com/omega8cc/boa/commit/1af11934c1df5f86b68f5363b6c1d091ea813562) this is the cause of the "issue". 

Is there any way to re-enable this feature?

Thanks!

**Comment by sluc23** [comment]
@omega8cc would be possible to add a new `.barracuda.cnf` variable to avoid removing `usage.sh` from self-hosted servers (or any other variant you prefer)?

**Comment by omega8cc** [comment]
This script is sending omega8.cc branded emails which depend on our hosted options limits, so it was never designed to be used on self-hosted BOA, but you can always add it to `/opt/local/bin` and run from cron in the silent mode like this:

`du -s /var/lib/mysql/* > /root/.du.local.sql; bash /opt/local/bin/usage.sh silent`
