### ISSUE TITLE
Hello, up-stable not giving latest php versions even though update states php upgrades are happening!

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1730]
Hello,

I just ran a barracuda up-stable in which the log reported that php8.0 had ben updated to 8.0.29, php8.1 had been updated to 8.1.20 and php 8.2 had been updated to 8.2.7 - and yet after restarting the server, etc - none of those updates were actually made!

I have confirmed that the updates were not actually made wia the sites' php.info reports.

Here is the gist: https://gist.github.com/EdNett/a364c686e703a813ded32ef7169f044c

Here is boa info more: https://gist.github.com/EdNett/d02d50125e5ead66f4acfbc079895a7c

Best,

Ed

**Comment by omega8cc** [comment]
Have you checked the versions installed?

```
/opt/php56/bin/php -v
/opt/php70/bin/php -v
/opt/php71/bin/php -v
/opt/php72/bin/php -v
/opt/php73/bin/php -v
/opt/php74/bin/php -v
/opt/php80/bin/php -v
/opt/php81/bin/php -v
/opt/php82/bin/php -v

```

**Comment by EdNett** [comment]
server1:~# /opt/php82/bin/php -v
PHP 8.2.7 (cli) (built: Jun  9 2023 15:27:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
server1:~# /opt/php81/bin/php -v
PHP 8.1.18 (cli) (built: May  5 2023 15:36:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.18, Copyright (c) Zend Technologies
server1:~# /opt/php80/bin/php -v
PHP 8.0.28 (cli) (built: May  5 2023 16:10:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies

It looks like only 8.2 was in fact properly updated, whereas 8.1 and 8.0 were not.

**Comment by EdNett** [comment]
Running a barracuda up-stable again did not fix the prblem - even though barracuda did recognize that 8.2.7 was up-to-date and 8.0 and 8.1 were not.

See here:  https://gist.github.com/EdNett/37ef8bf47354ea5456d7d768cefff50f

I will try to do a barracuda up-stable with a full reinstall of php now.

**Comment by omega8cc** [comment]
You may need to examine the barracuda verbose log to determine the culprit. The path is displayed at the top of the output when you enable debugging.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
If by the verbose barracuda log, you mean the barracuda update log in /var/backups - there is nothing there at all. After upgrading php 8.2 and restarting 8.2-fmp it immediately restarts 8.0-fpm and that is the only mention of 8.0 or 8.1 - which it does not update. I just removed 8.2 from the lsit of php version to install and I set GEOS to NO, re-ran an up-stable and no versions of php were updated, even though there is still the line about 8.0 and 8.1 need to be upgraded - but nothing happens. I don't know how to debug this further; I always enable debugging when I run an upgrade. I can try taking off IONCUBE, too and see if that might be the problem, but that would suprise me. 
Any more ideas and I'll try them. 
Best,

Ed

**Comment by omega8cc** [comment]
The verbose log contains precise details of PHP Installation progress you should investigate.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
We can’t reproduce this anywhere so we can’t assist you in debugging this further, I’m afraid. The culprit could be either unsupported PHP component defined related or even parent system killing the build process.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
would running this command help, in your opinion?

barracuda php-idle enable

**Comment by EdNett** [comment]
Still having the same problem in 5.0.0 and 5.1.0 HEAD
