### ISSUE TITLE
Upgrading Maria 10.2 to Percona fails because of libmariadb3

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1732]
Hi all,

I've been trying to upgrade my BOA server from Maria 10.2 to Percona 5.7 for some time now. I keep running into the log message listed below.  How can I make sure that libmariadb3 gets uninstalled before it tries to install Percona?

Preparing to unpack .../percona-server-server-5.7_5.7.36-39-1.stretch_amd64.deb ...
.
Unpacking percona-server-server-5.7 (5.7.36-39-1.stretch) ...
dpkg: error processing archive /var/cache/apt/archives/percona-server-server-5.7_5.7.36-39-1.stretch_amd64.deb (--unpack):
trying to overwrite '/usr/lib/mysql/plugin/[dialog.so](http://dialog.so/)', which is also in package libmariadb3 10.2.44+maria~stretch
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
/var/cache/apt/archives/percona-server-server-5.7_5.7.36-39-1.stretch_amd64.deb
Setting up percona-server-common-5.7 (5.7.36-39-1.stretch) ...
 -------------
   *  The suggested mysql options and settings are in /etc/mysql/percona-server.conf.d/mysqld.cnf
   *  If you want to use mysqld.cnf as default configuration file please make backup of /etc/my.cnf
   *  Once it is done please execute the following commands:
 rm -rf /etc/mysql/my.cnf
 update-alternatives --install /etc/mysql/my.cnf my.cnf "/etc/mysql/percona-server.cnf" 300
 -------------

**Comment by omega8cc** [comment]
How do you run the upgrade? With barracuda script?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aDarkling** [comment]
Yes.  I edited /root/.barracuda.cnf to replace the old db specification with this:

_DB_SERIES=5.7 #---------------- Supported values: 5.7
_DB_SERVER=Percona #------------ Install Percona or MariaDB (deprecated)

and then ran barracuda up-head system

**Comment by omega8cc** [comment]
Honestly, we haven’t tested this for years after BOA switched to Percona, so perhaps something has changed in the meantime because it worked on thousands of servers for us before. We may need to install legacy code to debug this somehow but it’s problematic because legacy code doesn’t support available now Debian versions for new VM.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Closing as MariaDB is not supported anymore.
