### ISSUE TITLE
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

### ISSUE THREAD

**Issue by fotiDim** [omega8cc/boa#1733]
I was trying to install [crowdsec](https://www.drupal.org/project/crowdsec) in a new platform and it required PHP 8 so I had to set:
```json
"platform": {
            "php": "8.1.0"
        }
```
in my composer.json.

Before it was:
```json
"platform": {
            "php": "7.4.33"
        }
```

I am using "Deploy a Composer project from a Git repository" and the platform and site verified but when visiting it I am getting:
`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0"`.
I suppose this is because the host Aegir environment only supports PHP 7 for now. I just wanted to point out that this not only blocks using Drupal 10 but also certain modules like crowdsec.

**Comment by aDarkling** [comment]
That's one of the problems I've been beating my head against! 
The solution is that Drupal supports PHP 8.1 for Drupal installations > 7.92.
As long as you have no older installations on that server, I would change the specifications in the following files from 7.4 to 8.1

/root/.barracuda.cnf
/root/.o1.octopus.cnf
/data/disk/o1/static/control/cli.info
/data/disk/o1/static/control/fpm.info
/data/disk/o1/static/control/multi-fpm.info

**Comment by omega8cc** [comment]
PHP 8.1 is fully supported, but please make sure that your codebase doesn’t include local Drush taking over Aegir tasks and invoking system PHP version instead of Octopus version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fotiDim** [comment]
@omega8cc I have no custom code on my website. Just installing some modules and nothing else. Are you suggesting that I should set Hostmaster's PHP version to 8.1?

**Comment by omega8cc** [comment]
Yes, although I already forgot if full compatibility is in 4-stable or 5-dev since we run 5-dev in production. Nonetheless, 4-stable will receive new release this week anyway.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
