### ISSUE TITLE
Best practice for debugging site installation?

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1734]
I'm trying to install a site onto a Varbase platform that I've loaded from the command line:

composer create-project Vardot/varbase-project:~9 varbase9.0.14_01 --no-dev --no-interaction

The platform verifies ok, but a subsequent site install using the GUI with the "Varbase" installation profile fails with "Drush command terminated abnormally due to an unrecoverable error".  

I'm stuck here.  I need to see what that error is.  
How should I do that?  Is there some sort of Debug setting?

**Comment by omega8cc** [comment]
Check PHP cli error logs in `/var/log/php/`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aDarkling** [comment]
Thanks!
