### ISSUE TITLE
Composer error messages

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1736]
Every time I install a platform, I get loads of Unzip error messages.  
Is anyone else getting these?
I'm trying to figure out if this is a Devuan or a Composer thing so I can report it to the right place.

    Failed to extract symfony/polyfill-php80: (1) '/usr/bin/unzip' -qq '/data/disk/o1/static/platforms/varbase9.0.14_01/vendor/composer/tmp-836c941e55da5701f7d303d93ffc2276' -d '/data/disk/o1/static/platforms/varbase9.0.14_01/vendor/composer/b80203e6'

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

**Comment by omega8cc** [comment]
It’s a bug in the `/bin/websh` fixed in 5-dev and will be backported to 4-stable on September 1st release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
