### ISSUE TITLE
Hello New install on Bullseye isn't allowed, only Buster or Beowolf supported

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1738]
Hello,

Is it really intended that a new install on bullseye isn't allowed. It won't work for me at all, and the server providors no longer even offer Buster. I'd hate to have to downgrade to buster just to install and upgrade again.

"
It is not any supported Devuan or Debian version.

You need Devuan Beowulf (recommended) or Debian Buster first.

Bye
"

boa info more is here:  https://gist.github.com/EdNett/f3eab561cd94dd4d435464c53c7775fb

What gives?

**Comment by omega8cc** [comment]
Buster is not required, Bullseye works just fine in all our tests for months. What’s your vps provider?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
ovh and hetzner - and I can't test this now, so I'll close
