### ISSUE TITLE
After successful install, boa in-octopus fails to install additional octopus instance - nginx permission problem?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1739]
After a successful BOA install, (on buster, and upgraded to beowulf), adding a second octopus instance fails. these are errors:
https://gist.github.com/EdNett/19d97f77590e21663559267c7407651b

If I look in the data/disk/o2/config directory I see there are missing files and folders:
folder /ssl.d/
folder /none/
and file nginx.conf  are all missing

Folders:
/server_master/
/server_localhost/  and
file 02.nginx.conf are there

What to do to add octopus instance?

boa info more is here:  https://gist.github.com/EdNett/f3eab561cd94dd4d435464c53c7775fb

Best,

Ed

**Comment by EdNett** [comment]
Fixed by updateFx06

**Comment by omega8cc** [comment]
Not sure how it could be related, but glad it worked.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
