### ISSUE TITLE
BOA 5.0.0-head (Debian Strech) Drupal 10.1 platform does not appear?

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1742]
I was delighted to see that finally Drupal 10 is finally supported.

BOA upgrade to 5.0.0-head went fine but then on `octopus` upgrade, new Drupal 7.98 appeared but Drupal 10 did not while I see that the code was there in `/disto`

I locked Drupal 7 sites to 7.4 and tried to install new platforms but only Drupal 7 appeared in the Platforms list.

Although I changed `~/static/control/cli.info` to 8.1 command line still uses 7.4

Is it because of Debian/Strech?

` Skynet Agent v.BOA-5.0.0-head on Debian/stretch welcomes you aboard`

```
root@aegir 10:07:14 # octopus up-head o1 platforms
load is 17 while maxload is 600
Octopus upgrade for User /data/disk/o1
 
BOA [10:08:11] ==> Skynet Agent v.BOA-5.0.0-head welcomes you aboard!
 
BOA [10:08:17] ==> Octopus Satellite Instance Upgrade in progress...
 
BOA [10:08:17] ==> This Octopus System is Debian/stretch x86_64
BOA [10:08:17] ==> This Octopus PHP FPM/CLI version is 8.1/8.1
BOA [10:08:17] ==> This Octopus URL address is o1.aegir.dx.rs
 
BOA [10:08:25] ==> UPGRADE A: Shared platforms code v.006 (new) will be created
BOA [10:08:36] ==> UPGRADE A: Satellite Instance Hostmaster upgrade skipped
 
Do you want to install some ready to use platforms? [Y/n] 
BOA [10:09:20] ==> UPGRADE A: Running o_contrib_ten forced upgrade...
BOA [10:09:20] ==> UPGRADE A: Running o_contrib_nine forced upgrade...
BOA [10:09:20] ==> UPGRADE A: Running o_contrib_eight forced upgrade...
BOA [10:09:21] ==> UPGRADE C: Shared platforms code v.006 (new) will be created
Drupal 10.1.5 [006] - https://drupal.org/project/drupal/releases/10.1.5 [Y/n] 
BOA [10:09:32] ==> DISTRO: Drupal 10.1.5 P.006 installed
Drupal 7.98.1 [006] - https://drupal.org/project/drupal/releases/7.98 [Y/n] 
BOA [10:09:33] ==> DISTRO: Drupal 7.98.1 P.006 installed
BOA [10:09:33] ==> UPGRADE C: Running Platforms Verify tasks, please wait...
BOA [10:09:34] ==> UPGRADE A: Platforms installed
BOA [10:09:34] ==> Final post-upgrade cleaning, one moment...
BOA [10:09:38] ==> BYE!
Done for /data/disk/o1

OCTOPUS upgrade completed
Bye
```

**Comment by omega8cc** [comment]
Debian Strech is not supported and not tested anymore, please upgrade to supported OS version.

If you have run the Octopus upgrade early after release there was a problem with templates including drushrc.php which prevents these platforms from being installed. Please delete all added platforms in Aegir, then manually delete ghost leftovers in the Aegir distro directory and run the upgrade again. You must switch CLI to 8.1, though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by macmladen** [comment]
I think that should be noted in DOC as requirement, both.

I issued `touch /root/.run-to-chimaera.cnf` and `service clean-boa-env start` and was confused with

```
root@aegir 11:45:13 # service clean-boa-env start
Starting clean-boa-env: clean-boa-env 1 nothing to do.
clean-boa-env 2 nothing to do.
clean-boa-env 3 nothing to do.
clean-boa-env 4 nothing to do.
clean-boa-env 5 nothing to do.
```

but checking the `htop` revealed that the process is started.

How can we track the process, know it is finished or why it failed?

**Comment by omega8cc** [comment]
You can monitor the progress in /root/.autochimaera.log but note that after the first reboot you won’t be able to log in unless you will clear respective line in your known host file, which will fix itself once SSH is rebuilt.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by macmladen** [comment]
**Thank you** for the support, I just did the "two-step magic" and it went from Strech to Chimera like a breeze.

I have monitored the progress but the server is also sending emails so the progress is also trackable.

The service/script has done everything but CLI was still 7.4.

I had to change in `.barracuda.cnf` PHP to default to 8.1 and also in `.o1.octopus.cnf` for FPM and CLI to really have CLI move from 7.4 to 8.1.

If anyone is having similar problems, both crucial configurations should be read carefully and adjusted to the new reality, in my case it was reducing _MULTI_PHP keys to only "7.4 8.1" and checking _PLATFORMS_LIST

The server is up and running and the sites are healthy. That is good.

I've run once more `barracuda up-head` and `octopus up-head all platforms`, I tried all I knew but still...

The Drupal 10 platform is missing.

```
root@aegir 15:02:05 # barracuda up-head
 
BOA [15:02:30] ==> Skynet Agent v.BOA-5.0.0-head welcomes you aboard!
 
BOA [15:02:33] ==> MODE: UPGRADE
 
Do you want to proceed with the upgrade? [Y/n] 

BOA [15:02:43] ==> VIRT: This system is supported: Linux KVM guest
 
BOA [15:02:43] ==> Aegir on aegir.dx.rs Devuan/chimaera x86_64 PHP 8.1
 
BOA [15:02:51] ==> INFO: Running aptitude full-upgrade...
BOA [15:03:17] ==> INFO: Running system packages update...
BOA [15:03:43] ==> INFO: Upgrading required libraries and tools...
BOA [15:03:59] ==> INFO: Running aptitude full-upgrade...
BOA [15:04:07] ==> INFO: Upgrading a large list of libraries and tools...
BOA [15:04:07] ==> WAIT: This may take a while, please wait...
BOA [15:05:45] ==> INFO: PHP SSL Version => OpenSSL/1.1.1w, looks OK
BOA [15:06:21] ==> INFO: Installing New Relic Apps Monitor...
BOA [15:06:28] ==> INFO: Installing latest version of New Relic Apps Monitor...
BOA [15:06:43] ==> INFO: Installing supported Drush versions...
 
Do you want to upgrade Aegir Master Instance? [Y/n] 
BOA [15:07:03] ==> INFO: Running Aegir Master Instance upgrade
BOA [15:07:25] ==> INFO: Running hostmaster-migrate, please wait...
BOA [15:07:55] ==> INFO: Aegir Master Instance upgrade completed
BOA [15:08:00] ==> INFO: Upgrading csf/lfd firewall...
BOA [15:08:10] ==> INFO: Running MySQLTuner check on all databases
BOA [15:08:10] ==> WAIT: This may take a while, please wait...
BOA [15:08:17] ==> INFO: Percona Uptime: 28 min 56 sec
BOA [15:08:29] ==> CARD: Now charging your credit card for this magic show...
BOA [15:08:32] ==> CARD: It will take a moment to process your payment...
BOA [15:08:38] ==> JOKE: Just kidding !!! Enjoy your Aegir Hosting System :)
 
BOA [15:08:42] ==> Final post-upgrade cleaning, one moment...
BOA [15:08:42] ==> BYE!

BARRACUDA upgrade completed
Bye
```

```
root@aegir 15:20:05 # octopus up-head o1 platforms
load is 16 while maxload is 600
Octopus upgrade for User /data/disk/o1
 
BOA [15:29:32] ==> Skynet Agent v.BOA-5.0.0-head welcomes you aboard!
 
BOA [15:29:39] ==> Octopus Satellite Instance Upgrade in progress...
 
BOA [15:29:39] ==> This Octopus System is Devuan/chimaera x86_64
BOA [15:29:39] ==> This Octopus PHP FPM/CLI version is 8.1/8.1
BOA [15:29:39] ==> This Octopus URL address is o1.aegir.dx.rs
 
BOA [15:29:47] ==> UPGRADE A: Shared platforms code v.009 (new) will be created
BOA [15:29:59] ==> UPGRADE A: Satellite Instance Hostmaster upgrade skipped
 
Do you want to install some ready to use platforms? [Y/n] 
BOA [15:30:30] ==> UPGRADE A: Running o_contrib_ten forced upgrade...
BOA [15:30:30] ==> UPGRADE A: Running o_contrib_nine forced upgrade...
BOA [15:30:30] ==> UPGRADE A: Running o_contrib_eight forced upgrade...
BOA [15:30:31] ==> UPGRADE C: Shared platforms code v.009 (new) will be created
Drupal 10.1.5 [009] - https://drupal.org/project/drupal/releases/10.1.5 [Y/n] 
BOA [15:30:34] ==> DISTRO: Drupal 10.1.5 P.009 installed
Drupal 7.98.1 [009] - https://drupal.org/project/drupal/releases/7.98 [Y/n] 
BOA [15:30:35] ==> DISTRO: Drupal 7.98.1 P.009 installed
BOA [15:30:35] ==> UPGRADE C: Running Platforms Verify tasks, please wait...
BOA [15:30:35] ==> UPGRADE A: Platforms installed
BOA [15:30:35] ==> Final post-upgrade cleaning, one moment...
BOA [15:30:40] ==> BYE!
Done for /data/disk/o1

OCTOPUS upgrade completed
Bye
```

I am really left out of ideas about what I might do and where I might be wrong.

**Comment by macmladen** [comment]
Every time, the directory is created within `distro` but the platform is not on the Platform list.

I tried creating one in static and it works as expected:

`~/static root@aegir 16:26:17 # sudo -u o1 composer create-project drupal/recommended-project drupal_10.1.5`

I added platform as **Add new Platform -> Classic** and created Standard and Umami sites.

**Comment by omega8cc** [comment]
OK, there was a typo affecting only Drupal 10.1.5 P, while both Drupal 10.1.5 S and Drupal 10.1.5 D worked fine. Please delete the hidden codebase in `/data/disk/o1/distro/009/drupal-10.1.5-prod` and run `octopus up-head o1 platforms` again. It should work this time.

Here's the patch: https://github.com/omega8cc/boa/commit/6057008dec87f7221ba752ad2f311a3141b81a94

**Comment by macmladen** [comment]
I tried but I cannot locate the script where the typo should be fixed on the server, which path?

**Comment by omega8cc** [comment]
You don't need to fix anything, just delete the ghost codebase and run the platforms upgrade.

**Comment by macmladen** [comment]
The very bottom line is that I effortlessly upgraded from Debian/BOA-4.2.0 to Chimera/BOA 5.0.0 very easily, sites were probably alive all the time, I just followed the commands (cautiously tracking progress) and (besides the typo bug) everything went smoothly and everything works as expected and **blazingly fast**.

**Comment by omega8cc** [comment]
To be precise, older Debian OS versions are deprecated by Debian, not BOA. Also, you could still host Drupal 10 on Debian Stretch, so it’s not a requirement either.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Better link: https://github.com/omega8cc/boa/blob/6057008dec87f7221ba752ad2f311a3141b81a94/README.txt#L107

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by macmladen** [comment]
True! 😂

The bug was in the typo (and in my hardcoded configurations) but I assumed it was the Debian Stretch.

However, probably running PHP 8.1 on Stretch is not the best idea and having the current distribution is certainly a better choice.

**Comment by omega8cc** [comment]
Regarding Stretch the critical point is that its LTS ended already a year ago and with time its packages may be archived or deleted, so at some point you won’t be able to reliably upgrade to newer OS.

We hope that we have made the OS major upgrades easy enough for everyone so there’s no point in avoiding upgrade due to some manual procedures required before.

We have been able to upgrade some clients even from Jessie, albeit with some minor issues, so it’s always a good idea to keep your system regularly updated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dserrato** [comment]
In following this conversation, @macmladen indicated in an early comment that:

> I had to change in .barracuda.cnf PHP to default to 8.1 and also in .o1.octopus.cnf for FPM and CLI to really have CLI move from 7.4 to 8.1.

Just wondering if that is still the case and at which point we should be making those changes. At the beginning before upgrades or after it's complete?

Or, if the updates should automatically take care the default php version and FPM and CLI configurations. 

Thanks so much.

**Comment by omega8cc** [comment]
You don’t need to switch to PHP 7.4 unless you host Drupal 10. It also doesn’t matter if you change both barracuda and octopus because Octopus has its own configuration, also affecting cli and composer, no matter which version is used in barracuda.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
I mean you don’t need to switch to 8.1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dserrato** [comment]
Ok, thank you so much for the feedback.
