### ISSUE TITLE
BOA Migrate not working - ssh problem

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1743]
Hello, 

All this on latest head 5.0.0 on both source and taget servers.

Now that BOA is working I am trying to move all the sites on an octopus instance to a new server, and am following the MIGRATE  docs, and am having a simple error. On the target-host I get:

Running pre_mig inside vm target-host
Preparing target target-host for incoming migration...
Add remote id_rsa.pub to authorized_keys here...
Ops.. /root/.ssh/auth_undefined_keys.txt does not exist in target-host
All done!
server1:~#

then on the source-host I cannot ssh in to the target:

Preparing source source-host for outgoing migration...
Create id_rsa.pub...
All done!
root@server1:~# ssh root@target-ip
The authenticity of host 'target-ip (target-ip)' can't be established.
ED25519 key fingerprint is SHA256:aXgR...EVb...jvU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'target-ip' (ED25519) to the list of known hosts.
root@target-ip's password:
Permission denied, please try again.
root@target-ip's password:
Permission denied, please try again.

With correct root passwd, it does not work. Is this perhaps an sshd configuration issue? IS XBOA toolkit MIGRATE suppossed to work?

Thanks for help.

Best,

Ed

**Comment by omega8cc** [comment]
Make sure to run this command on the source host first and then on the target host -- it's important that DNS for the 'undefined' subdomain works fine too. Also, both system should run the same BOA version already. You may want to examine if the `/var/www/nginx-default/auth_undefined_keys.txt` on the source host looks fine.

**Comment by omega8cc** [comment]
Also, examine the `/root/.ssh/authorized_keys` on the target host and remove any unexpected lines there, not related to ssh keys.
