### ISSUE TITLE
not getting both php8.1 and php8.2 updates! on upgrade to 5.0.0 head or 5.1.0-head

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1744]
Hello,

Upgrading barracuda (and octopus too half of the time) doesn't update both php 8.1 and 8.2 to latest versions.  I seem to be stuck at 8.2.7 on one server which updated 8.1 to 8.1.25  and on the other I can update 8.2 to 8.2.12 but 8.1 remains at 8.1.18!

I am serious. At first I thought it mattered what the CLI and FPM setting were in the .barracuda.cnf file, and it seems like manipulating them allowed either an 8.1 or an 8.2 update, but I no longer think that since all combinations and permutations of settings in that file still do not allow an update for both 8.1 and 8.2.

This reminds me of issue #1730 

boa info more is here:

https://gist.github.com/EdNett/b1791bf891fdb8ad3da2581b82bd1788

**Comment by omega8cc** [comment]
We can’t reproduce this anywhere so we can’t assist you in debugging this further, I’m afraid. The culprit could be either unsupported PHP component defined related or even parent system killing the build process.
