### ISSUE TITLE
Error when testing install 

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1745]
Trying to install a platform
Drupal 10.0.11
git repository url: https://git.drupalcode.org/project/drupal.git
using strategy:
Deploy from Git repository (not managed by Composer)
git reference: 10.0.11
docroot leaving empty

It errors. 

I get the following error:
There is no /data/disk/o1/platforms/drupal-10.0.11/vendor/autoload.php

Why would there be a "vendor/autoload.php" if I am using git without composer.

Drush command terminated abnormally due to an unrecoverable error.
Error: Uncaught Error: **Failed opening required '/data/disk/o1/platforms/drupal-10.0.11/vendor/autoload.php'** (include_path='.:/opt/php81/lib/php') in /data/disk/o1/platforms/drupal-10.0.11/autoload.php:14
Stack trace:
#0 /data/disk/o1/tools/drush/includes/drupal.inc(18): require()
#1 /data/disk/o1/tools/drush/lib/Drush/Boot/DrupalBoot10.php(41): drush_drupal_load_autoloader()
#2 /data/disk/o1/tools/drush/includes/drupal.inc(44): Drush\Boot\DrupalBoot10->get_version()
#3 /data/disk/o1/tools/drush/lib/Drush/Boot/DrupalBoot.php(279): drush_drupal_version()
#4 /data/disk/o1/tools/drush/includes/bootstrap.inc(430): Drush\Boot\DrupalBoot->bootstrap_drupal_root_validate()
#5 /data/disk/o1/tools/drush/includes/bootstrap.inc(351): drush_bootstrap_validate()
#6 /data/disk/o1/.drush/sys/provision/platform/verify.provision.inc(130): drush_bootstrap()
#7 /data/disk/o1/tools/drush/includes/command.inc(422): drush_provision_drupal_pre_provision_verify()
#8 /data/disk/o1/tools/drush/includes/command.inc(231): _drush_invoke_hooks()
#9 /data/disk/o1/tools/drush/includes/command.inc(199): drush_command()
#10 /data/disk/o1/tools/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch()
#11 /data/disk/o1/tools/drush/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 /data/disk/o1/tools/drush/drush.php(12): drush_main()
#13 {main}
  thrown in /data/disk/o1/platforms/drupal-10.0.11/autoload.php, line 14

**Comment by omega8cc** [comment]
Drupal 10 is currently supported as classic install only — you build the codebase w/ Composer on command line and then add as platform in Aegir. Other methods have not been tested yet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by socialnicheguru** [comment]
I was able to install Drupal 10 in classic mode
