### ISSUE TITLE
Auto Upgrade to Chimera Successfully completes, but will not start nginx

### ISSUE THREAD

**Issue by dserrato** [omega8cc/boa#1747]
Went through the upgrade process following the directions for the Auto-upgrade method. Everything seemed to go well and was able to log into server, follow the logs and watch all the updates over and over. After about 3 hours, it completed. 

All sites and hostmaster were unavailable. 

Checked php81 status and it was running
Checked nginx status and it was giving me "Killed" as the result. 

If I tried restarting nginx, I'd get:
```
service nginx restart
Stopping Nginx Server...: failed!
Starting Nginx Server...:Killed
```

Tried to run barracuda up-head and got:

```
Another BOA installer is running probably
  because /var/run/boa_run.pid exists
```

oh well. This is the second time I've tried on this server. Thinking I might spin up a new server, put Devuan Chimera on it and just install fresh. Then, I'll just migrate sites over little by little. 
It's 2:30am, I gotta get some sleep.

**Comment by omega8cc** [comment]
You may need to investigate detailed barracuda logs in `/var/log/barracuda*` to find the culprit. Or at least check Nginx own `error.log`
