### ISSUE TITLE
I cannot install if any of the uninstalled modules on my system still have "core: 8.x"

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1750]
There are several modules that have upgraded their main module to D10 but have not upgraded some of the submodules. 
Is there a way to allow for BOA to allow the install .

In this example the support module has not been updated:

Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' key must be present in modules/contrib/commerce_loyalty_points/modules/pos/commerce_pos_loyalty_points_support.info.yml in /data/disk/o1/platforms/mysite/html/core/lib/Drupal/Core/Extension/InfoParserDynamic.php:68
Stack trace:

**Comment by omega8cc** [comment]
Codebase internal dependencies and versions is not something Aegir or BOA can fix for you, I'm afraid. It will throw Drush error and will make Aegir task fail, as it's designed to fail if anything goes wrong. You should probably remove legacy code you have already uninstalled before trying to use it as a platform.

**Comment by socialnicheguru** [comment]
I understand. all the modules for Drupal 10 must be Drupal 10 compatible.

**Comment by omega8cc** [comment]
Yes, probably.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
