### ISSUE TITLE
What is the proper way to add php extensions?

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1753]
I read the very helpful PHP.txt documenation at https://github.com/omega8cc/boa/blob/5.x-head/docs/PHP.txt which did not give me much help around this particular question. 

I added a repository to add php8.1-extensions
I was able to add them but not in the right place. 

Barracuda has this folder and contents:
```
 /opt/php81/lib/php/extensions/no-debug-non-zts-20210902/
apcu.so*      imagick.so*  mcrypt.so*   redis.so*           yaml.so*
igbinary.so*  jsmin.so*    opcache.so*  uploadprogress.so*
```

I was able to install the extension, exif, but it was in another location:
```
ls /opt/php81/lib/php/extensions/
no-debug-non-zts-20210902/
prime:/var/log# updatedb
prime:/var/log# locate exif.so
/usr/lib/php/20210902/exif.so
```

**Comment by omega8cc** [comment]
You can’t and you shouldn’t. You can always open a feature request, though.

One of the key BOA principles is that it’s taking over your system and you should avoid installing anything else to avoid issues.

There are exceptions, though. Please read the docs explaining core configuration variables and options:

https://github.com/omega8cc/boa/tree/5.x-head/docs/cnf

https://github.com/omega8cc/boa/tree/5.x-head/docs/ctrl

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by socialnicheguru** [comment]
Feature request: Add the following php-extensions #1756 https://github.com/omega8cc/boa/issues/1756
