### ISSUE TITLE
Best practice: Help needed to setup the right BOA structure (Barracuda with multiple Octopus servers), Dev, Test, and Production. 

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1754]
I need help thinking through the appropriate setup to reduce this type of issue.

How can I create my various Octopus servers? 
Can I create them on a different server?
Does that mean that the database will be separate for each site?

In Aegir I can have remote servers. Since BOA is built on Aegir can the same happen?

In addition what is the proper way to setup 
dev, test, and production platforms for sites?
The default path is /data/disk/o1/static/ .
Do I create a different folders: dev, test, production and place the respective platforms there for example? 

I had an instance where the Barracuda server got corrupted and I couldn't recover. I am hopint that with the proper setup if one instance goes down not all of them go down.

**Comment by socialnicheguru** [comment]
I see from https://github.com/omega8cc/boa/blob/5.x-head/docs/INSTALL.txt that I can add multiple Octopus servers:
 $ boa {in-octopus} {email} {o2} {mini|max|none} {head|dev|2.4}

Should I setup up three octopus servers, one each for dev, testing, and production?

**Comment by omega8cc** [comment]
Please refer to the main README.txt to understand how BOA stack is designed to be used.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
To be more specific, BOA doesn’t support remote servers, at least not yet, but it comes with its own db cluster support. The stack main purpose is to manage multi-tenant architecture with multiple *isolated* with virtual jail Aegir instances on the same server. This means that your hosted website lifecycle happens like with normal Aegir system within the same instance, using multiple platforms.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
