### ISSUE TITLE
Feature request: Add the following php-extensions 

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1756]
These extensions are used by various modules that I have installed. 
Can they be added to BOA?
Maybe there can be a variable that will allow them to be added to the system

php8.1, php8.2, and possibly php7.4 

sudo apt install php8.1-bz2
sudo apt install php8.1-curl
sudo apt install php8.1-ffi
sudo apt install php8.1-fileinfo
sudo apt install php8.1-gd
sudo apt install php8.1-gettext
sudo apt install php8.1-gmp
sudo apt install php8.1-intl
sudo apt install php8.1-imap
sudo apt install php8.1-mbstring
sudo apt install php8.1-exif
sudo apt install php8.1-dom
sudo apt install php8.1-filter
sudo apt install php8.1-hash
sudo apt install php8.1-xml

**Comment by omega8cc** [comment]
Have you checked extensions already enabled and installed by default on the PHP info page in any created site or on command line? BOA already comes with everything Drupal needs, and more. If you find anything missing, please let us know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
