### ISSUE TITLE
Where is the _HOURLY_DB_BACKUPS variable

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1757]
I read this https://github.com/omega8cc/boa/tree/5.x-head/docs/cnf.

_HOURLY_DB_BACKUPS is not in the .barracuda file that I have installed.

What am I missing? Am I supposed to install something?

**Comment by omega8cc** [comment]
It was optional feature, no longer working currently.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
