### ISSUE TITLE
Should I remove BOA installed modules like redis from my composer.json file?

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1758]
In https://github.com/omega8cc/boa/blob/5.x-head/docs/MODULES.txt, redis is supported, bundled, and used without enabling.

If I have redis in my composer.json file, should I remove it?

[NA] means that
this module is used without the need to enable it
redis ---------------------- [D6-D10] ----- [S] [B] [NA]

**Comment by omega8cc** [comment]
Yes, you should remove it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
I mean the Redis module only, because only the bundled is supported.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
