### ISSUE TITLE
Do changes in barracuda.cnf take effect on upgrade or is it instant?

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1759]
I changed a few variables in /root/.barracuda.cnf per https://github.com/omega8cc/boa/blob/5.x-head/docs/cnf/barracuda.cnf.
How and when do the changes take effect? Do I have to run the boa upgrade command?

**Comment by socialnicheguru** [comment]
I think I had to run:

`barracuda up-head`

https://github.com/omega8cc/boa/blob/5.x-head/docs/UPGRADE.txt

**Comment by omega8cc** [comment]
Most of them are used on barracuda upgrade.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
