### ISSUE TITLE
Examples of extra services and apps that might need to be specified in .barracuda.cnf?

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1760]
Could you give examples of extra packages that this might refer to?
https://github.com/omega8cc/boa/blob/5.x-head/docs/FAQ.txt

> Q: Can I install services and apps not included in BOA?
> It depends. BOA uses very aggressive upgrades procedures and if it is not
>    aware of extra services installed and running, it may even uninstall them
>    if the system packages dependency autoclean will trigger such action,
>    so you need to watch closely what happens during and after barracuda upgrade.
>    Note that you can specify extra packages in the special _EXTRA_PACKAGES
>    veriable in the /root/.barracuda.cnf file -- This should help, but you should
>    still watch closely what happens during and after barracuda upgrade.

**Comment by omega8cc** [comment]
You don’t need any extra packages really. BOA is pretty complete stack for Drupal by default. This option is for experienced BOA users and sysadmins who wish to extend the stack with something they are willing to maintain themselves.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
