### ISSUE TITLE
Which version of platforms specified in Platforms.txt are run?

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1761]
In https://github.com/omega8cc/boa/blob/5.x-head/docs/PLATFORMS.txt, the platforms that are supported are listed.

I can specify the Drupal 10.1 version of Thunder. Which version is actually being used.

It takes effect on every future
###

Does this mean that if I manually install a later version of Thunder for 10.1, that version will be overwritten? 

Also where are the platforms written? Is it to ~/o1/platforms? 
Should no other platforms go into this folder?

**Comment by socialnicheguru** [comment]
ok. so I found it not in the platforms.txt file but in selfupgrade.txt, https://github.com/omega8cc/boa/blob/master/docs/SELFUPGRADE.txt.

Please update platforms.txt to point to the selfuprade.txt to enable the platforms.

> ### You can now launch Aegir upgrade to (re)install platforms listed in the file
> ### ~/static/control/platforms.info (see below) by creating empty pid file:
> ###
> ###   ~/static/control/run-upgrade.pid

**Comment by socialnicheguru** [comment]
If I enabled platforms in the platforms.txt file does that mean I can have no other Drupal distributions in ~/o1/static?

**Comment by socialnicheguru** [comment]
Octopus platforms are placed:
/data/disk/oX/distro

where X is the octopus number

**Comment by omega8cc** [comment]
It will install versions currently listed in the BOA README.txt, which are provided as easy starting points but normally you should follow general guidelines on managing your platforms:  

https://learn.omega8.cc/how-to-add-custom-platform-properly-140

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
