### ISSUE TITLE
How to enable ssl for octopus or  master.fqdn barracuda/octopus install?

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1762]
When I install an Octopus or Barracuda instance I see the following:

BOA [14:33:49] ==> INIT B: LE -- !!! WARNING
BOA [14:33:49] ==> INIT B: LE -- Don't enable SSL option for the Hostmaster site in Aegir
BOA [14:33:49] ==> INIT B: LE -- SSL for Aegir control panel is handled outside of it
BOA [14:33:49] ==> INIT B: LE -- !!! WARNING

How then is ssl enabled for the o1.f-q-d-n or other instances?

**Comment by socialnicheguru** [comment]
Octopus ssl:

I see that for octobus you have to remove this file
/data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid
(https://github.com/omega8cc/boa/blob/5.x-head/docs/SSL.txt)

then force an upgrade:
octopus up-head oX.  (X= the octopus number)

https://github.com/omega8cc/boa/blob/5.x-head/docs/UPGRADE.txt

Now how about master.fqdn. What do you do?

**Comment by omega8cc** [comment]
The Octopus welcome email template is also a good starting point: https://github.com/omega8cc/boa/blob/5.x-head/aegir/conf/setupmail.txt

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Also the old docs still provide tons of useful information: https://learn.omega8.cc/library/good-to-know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by socialnicheguru** [comment]
Thanks for that. I read through the docs already. I was able to figure it out for Octopus and I placed that above.

But I am still at a loss for how to SSL enable master.fqdn

But will look again

**Comment by omega8cc** [comment]
The README answers your question. You should not use the master instance for anything.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lexsoft00** [comment]
Is there a way to block master on nginx level? I'm a bit paranoid of having the Aegir master accessible from the internet, more over if I'm not monitoring it.

**Comment by omega8cc** [comment]
@lexsoft00 We should perhaps block it by default, but you can simply move away it’s vhost and reload nginx after each full barracuda upgrade.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by socialnicheguru** [comment]
master.fqdn also is not ssl enabled. 
That is why I asked. 
I can ssl enable octopus.
but I do not see a way to ssl enable master.fqdn
I did not see that in the docs unless I misread it

**Comment by omega8cc** [comment]
It doesn’t matter, because it’s instances you should never use. Also, it does have SSL but via system self signed certificate like all hosted sites with no LE cert enabled.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lexsoft00** [comment]
Thanks @omega8cc 

I will give it a try and let you know.

I'm having some issues to enable SSL let's encrypt on new install.
Removed the file /data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid
Run `octopus up-head all force`

https://gist.github.com/lexsoft00/45bd3cd042acc1281c94efc59de343ca
o1 certificate not updated, I've done a barracuda up-head system but that not helped either. I know sometimes let's encrypt blocks you for no reason so I'm going to try octopus up-head all force again in a few hours.

Usually I could still access the private certificate in the browser but on recent browser updates it's blocked and you don't see the proceed button anymore so I leave this here for anybody that is having issues as well.

If you are using Brave or Chrome and are trying to access o1 with self signed certificate, the fix was surprisingly easy. When you are on the error page, type the characters “thisisunsafe“.

Is there a command that it's doing a health check of the system? Like looking if redis server is running, etc?

**Comment by omega8cc** [comment]
You are removing wrong file. Please follow the instructions boa displays on screen during installation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Also, don’t confuse barracuda upgrade with octopus upgrade, it’s not related in any way.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lexsoft00** [comment]
@omega8cc this is the output that boa displays on screen on fresh install:
```
BOA [15:11:33] ==> INIT B: Letsencrypt SSL initial mode: DEMO
BOA [15:11:33] ==> INIT B: LE -- No real SSL certs will be generated
BOA [15:11:33] ==> INIT B: LE -- To enable live SSL mode, please delete file:
BOA [15:11:33] ==> INIT B: LE -- /data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid
BOA [15:11:33] ==> INIT B: LE -- Then run octopus forced upgrade

```

**Comment by omega8cc** [comment]
Hmm.. looks like we overlooked this because there’s separate control file to handle LE for hostmaster.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Also, if I remember correctly, you need to run first sql backup to have LE enabled on octopus upgrade. It’s an old way to avoid having LE locked on incomplete system installation.. we need to improve this old logic.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alpha-omega-labs** [comment]
> You are removing wrong file. Please follow the instructions boa displays on screen during installation.
> 
> Sent with [GitHawk](http://githawk.com)

Hello,
Thank you for a great product! 
Can you please provide some updated instruction about how to correctly switch to LE certificate because here we got same issue with deleting "wrong" file but following exactly readme/ssl docs.

Thanks

**Comment by omega8cc** [comment]
By the way, you can't enable LE cert on master.fqdn, it's not supported because master.fqdn shouldn't be used.
