### ISSUE TITLE
Adminer Percona manager gives an under construction page

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1763]
https://github.com/omega8cc/boa/blob/5.x-head/docs/NOTES.txt

 Your (optional) Adminer Percona Manager will be available at https://adminer.master.f-q-d-n

This page is under construction.

**Comment by socialnicheguru** [comment]
I did not have it installed. 

I had to modify the baracuda.cnf according to https://github.com/omega8cc/boa/blob/5.x-head/docs/NOTES.txt

The run the upgrade:

` barracuda up-head`

**Comment by omega8cc** [comment]
That’s how optional features work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
