### ISSUE TITLE
Varbase install from BOA failed

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1765]
I tried to install Varbase that I installed on octopus by modifying the .o1.octopus.cnf

If failed with the following error

> Drush command terminated abnormally due to an unrecoverable error. Error: Declaration of Drupal\syslog\Logger\SysLog::log($level, Stringable\|string $message, array $context = []): void must be compatible with Drupal\Core\Logger\RfcLoggerTrait::log($level, $message, array $context = []) in /data/disk/o2/distro/001/varbase-9.0.16-10.1.6/docroot/core/modules/syslog/src/Logger/SysLog.php, line 68 | - | error
> -- | -- | --

<br class="Apple-interchange-newline">

**Comment by omega8cc** [comment]
We have left this one missing patch as an example discussed in the announcement: https://github.com/omega8cc/boa/issues/1678#issuecomment-1782341467

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
The patch has been added in the new release.
