### ISSUE TITLE
Cron / CPU related performance issue since 27th October

### ISSUE THREAD

**Issue by airbbria** [omega8cc/boa#1769]
Hi,

we experience a higher (~100-120%) average CPU usage on our servers (2 Linodes w. 2 CPU 4 GB RAM) same issue on both.
We tried to update BOA. The update was successful but the issue remained.

The crontab settings (fire and clead) doesn't take effect.
When we completely stop cron service, the Load goes back to normal (~30-50%).

The sites didn't change, the issue persists since the 27th October daily update(?) or usual process in BOA.

Not sure what to add as attachment and also no idea where to look for the solution.

On one of our servers in mysql log I see a repeating process 20+times a minute:
INSERT to cache_bootstrap where cid=variables
than delete, load from variables table, cache again, than delete, etc.

On the other instance, the cache_bootstrap table is empty.

Both on instances I see

_hosting_dispatch_last_run_

and

_hosting_queue_cron_last_run_

change value very often, sometimes once in 2-3 seconds.

Can be multiple simultaneous run of these processes at the same time?

How can we slow this down or change the frequency? I didn't find such an option.

Thank you.
Best regards,
bcs

**Comment by omega8cc** [comment]
Perhaps you want to delete the `/root/.fast.cron.cnf` which was enabled by default (but no longer is).

If you want to have the tasks/cron running faster than every minute, but every 5 seconds is too fast, you can create empty `/root/.slow.cron.cnf` and it will run every 15 seconds.

**Comment by airbbria** [comment]
Thanks, deleting /root/.fast.cron.cnf solved the issue.
