### ISSUE TITLE
Limit for nofile set too high

### ISSUE THREAD

**Issue by reswild** [omega8cc/boa#1773]
I went through my server logs the other day, and I noticed that my auth log was being filled up with endless warnings about
`su: pam_limits(su-l:session): Could not set limit for 'nofile' to soft=2097152, hard=2097152: Operation not permitted; uid=0,euid=0`
I can see that this was caused by this commit from a few months ago: https://github.com/omega8cc/boa/commit/7227341116e4039e4fe4b8af978c888559eecc21

It appears that 1048576 is the highest value my system will accept as a nofile limit, so I manually edited /etc/security/limits.conf, and restored the previous values.

**Comment by EdNett** [comment]
Thanks for the fix; I had the same problem.

**Comment by omega8cc** [comment]
@reswild what is your virtualization system and host?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reswild** [comment]
@omega8cc I had the issue on both Hetzner and DigitalOcean. I believe they both use KVM.

**Comment by lexsoft00** [comment]
Same thing

`Mar  3 06:34:27 lon su: pam_limits(su-l:session): Could not set limit for 'nofile' to soft=2097152, hard=2097152: Operation not permitted; uid=0,euid=0`

[<script src="https://gist.github.com/lexsoft00/b012f26597fa36047d92b8b4690de0a4.js"></script>](https://gist.github.com/lexsoft00/b012f26597fa36047d92b8b4690de0a4)

**Comment by omega8cc** [comment]
This should be reverted and made configurable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
This has been reverted in 5.2.0 release.
