### ISSUE TITLE
Problem with permissions on a drush folder prevent composer updating - fix is easy

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1774]
On Thunder and Drutopia distros (at the least) we are unable to update composer packages (drupal 9 and 10) because the permissions on a drush folder are set to 400. The fix is easy - setting the permissions to allow reading, writing and executing through the folder. The error message encountered is:

In Filesystem.php line 260:

  /data/disk/o2/static/drutopia/vendor/drush/drush does not exist and could no
  t be created:

chmod 770 /data/disk/o2/static/drutopia/vendor/drush allows updating via composer, and a verification task on the platform changes the permissions back to 400, so something isn't working properly here.

boa info more is here: https://gist.github.com/EdNett/59fe3156aa2f3fcff935b062b0d162b9

Best,

Ed

**Comment by omega8cc** [comment]
It works as designed, please read the docs/DRUSH.txt

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
