### ISSUE TITLE
Errors when trying to install new core 10.2 site - on diverse platforms

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1775]
I am getting fatal errors when trying to install a new site on a custom drupal 10.2 platform, a social 10.2 (core) platform and a drutopia 10.2 (core) platform. I have just verified that I am able to successfully install a site on the provided core 10.2.0 platform. I wonder what the difference is (I have always used custom core platform which I find easier to maintain than BOA's installable core platforms - or could the difference be between 10.2.0 and 10.2.3/10.2.4 ?). In any cse this error prevents install of drutopia or social 10.2 platforms. The errors are numerous and relate to psr on the one hand and symfony/console mostly on the other. For example:

Including /data/disk/o2/.drush/sys/provision/http/install.provision.inc | - | bootstrap
-- | -- | --
Including /data/disk/o2/aegir/distro/009/profiles/hostmaster/modules/aegir/hosting_civicrm/drush/install.provision.inc | - | bootstrap
Including /data/disk/o2/.drush/sys/provision/platform/install.provision.inc | - | bootstrap
Drush command terminated abnormally due to an unrecoverable error. Error: Declaration of Drush\Command\DrushInputAdapter::getFirstArgument() must be compatible with Symfony\Component\Console\Input\InputInterface::getFirstArgument(): ?string in /data/disk/o2/tools/drush/lib/Drush/Command/DrushInputAdapter.php, line 54 | - | error
Invoking hosting_install_task_rollback hooks. | 1 s. | notice

I am also getting a lot of these fatal errors:
Drush command terminated abnormally due to an unrecoverable error.                       [error]
Error: Declaration of Drupal\Core\Logger\LoggerChannel::log($level, Stringable|string
$message, array $context = []): void must be compatible with
Psr\Log\LoggerTrait::log($level, $message, array $context = []) in
/data/disk/o2/static/d10full/web/core/lib/Drupal/Core/Logger/LoggerChannel.php, line
94

I wonder if this second error is related to this longstanding drupal core issue:
https://www.drupal.org/project/drupal/issues/3354316
We don't have the psr php extension installed, and reinstalling symfony/psr-http-message-bridge psr/log did not help. 

Or this issue ? (drush installed globally conflicts with local drush installations):
https://www.drupal.org/project/drupal/issues/3423346

running drush --version on the command line when cd'd to the site in the pertinant platform gives:
 Drush Version   :  8.4.12

Are we suppossed to start adding a drush requirement in our platform composer.json files?  I notice that core 10.2.3+ requires drush 12.4.3

running commands as "drush12 updb" or "drush11 updb" for a 10.1 core site  - does not produce output and does not work. I understand that "drushlr" is no longer used. Should we be calling specific drush versions on the command line per specific core version? If so, how exactly, please do we do this? 

This thread: 
https://drupal.stackexchange.com/questions/314072/drush-fatal-error-with-declaration-of-drupal-core-logger-loggerchannellog  
contains this at the end, which worries me since I believe boa/aegir + platforms does this by default:
"We discovered in chat that the reason this occurred is because there is a custom module installing its own Composer dependencies which clash with the ones loaded by Drupal."

Am I on track to a solution here? Is this a bug report? I have tried with various combinations of php 8.1 and 8.2 for cli and fpm - none of it works, and of course we can't use drush at all on the command line - it appears to be trying to use drush8 sometimes.

This happens with dore 10.2.3 and 10.2.4. This is on boa head.

Boa info more here:
https://gist.github.com/EdNett/a17d21effb0b2481d8fbb304dd51484b

**Comment by EdNett** [comment]
I'm going to close this down because I just installed a new d10.2.4 platform - a custom one with nothing added, and teh platform verifies OK and a site can be added, so the problem must be with add-on modules which I use, the social and drutopia distros use, I guess. This is getting very complicated. I will re-open if I can find a real problem after more testing.

**Comment by EdNett** [comment]
I am reopening since I believe the problem may be with 10.2.3 and above. On a newly installed custom 10.2.4 platform, which verifies, and I add a site, it all shows green on hte o2 octopus hostmaster GUI, yet there is an http 500 error if I try to visit the site - a blank page, and if I cd to the site, I get this error trying to do a db update, for example - or anything - it appears that drush 8 is trying to be used:
 drush updb -y
Drush command terminated abnormally due to an unrecoverable error.                       [error]
Error: Declaration of Drush\Command\DrushInputAdapter::getFirstArgument() must be
compatible with Symfony\Component\Console\Input\InputInterface::getFirstArgument():
?string in /opt/tools/drush/8/drush/lib/Drush/Command/DrushInputAdapter.php, line 54

**Comment by EdNett** [comment]
OK - I'll leave this open because I don't know if this is a hack, or is new required behavior, but adding the requirement:
"drush/drush": "^12.4.3", to the custom platform composer.json file

solved the problem even though at the site level in the terminal drush --version still gives 8.4.12 !

**Comment by fotiDim** [comment]
I am facing the same issue. Upgrading from Drupal 10.1 to 10.2 has been impossible. Adding `"drush/drush": "^12.4.3"` to the dependencies did not help.

**Comment by omega8cc** [comment]
That’s fixed in DEV. Should be released in the next 48 hours.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
Hello again. I'll test this. 
So DEV is different from HEAD? Is that right? Can I just do "screen", "barracuda up-dev" and then do you also recommend an 
"octopus up-dev all both" ?

Best, Ed

**Comment by fotiDim** [comment]
> That’s fixed in DEV. Should be released in the next 48 hours.
> 

Was there a release? Shall we try again?

**Comment by omega8cc** [comment]
Fixed in 5.2.0 release.
