### ISSUE TITLE
Locked out of new install; Can't login to server

### ISSUE THREAD

**Issue by graveguardian** [omega8cc/boa#1777]
Found this issue (SSH-RSA Keys broken after recent BOA update #1648) after being locked out of three successful installs... ;-(

As I'm on an unmanaged server, my hosting company isn't being much help...just telling me that SSH is locking me out.

How can I regain access to my server. The aegir system itself is accessible, but can't login to server.

**Comment by graveguardian** [comment]
In reading the SSH release doc, it states:

> "Incompatibility is more likely when connecting to older SSH
> implementations that have not been upgraded or have not closely tracked
> improvements in the SSH protocol. For these cases, it may be necessary
> to selectively re-enable RSA/SHA1 to allow connection and/or user
> authentication via the HostkeyAlgorithms and PubkeyAcceptedAlgorithms
> options. For example, the following stanza in ~/.ssh/config will enable
> RSA/SHA1 for host and user authentication for a single destination host:
> 
>     Host old-host
>         HostkeyAlgorithms +ssh-rsa
> 	PubkeyAcceptedAlgorithms +ssh-rsa
> 
> We recommend enabling RSA/SHA1 only as a stopgap measure until legacy
> implementations can be upgraded or reconfigured with another key type
> (such as ECDSA or Ed25519)."

So, if I understand this correctly, I need to modify ~/.ssh/config to add those lines, correct? How do I do that if I can't log in to the server? Via VNC from within my account on my host?

Thanks for any direction!

**Comment by omega8cc** [comment]
Have you added your SSH keys on the server as explained in the docs before running installation?

**Comment by omega8cc** [comment]
Perhaps you have too old OpenSSH version installed locally? Try to upgrade and generate new SSH keys to make sure, I don't see any other reason why you would be locked. Also, make sure to read: https://github.com/omega8cc/boa/blob/bb81faee0f79e9bd1e70cbb00a892d5c888b4524/docs/INSTALL.txt#L45

**Comment by graveguardian** [comment]
Will do! Thank you for your help.

Has been years since I've installed this, but looking forward to getting it up and running again.

The front-end works fine, except no platforms were installed, even though I used the command to prompt for them. Primarily need CiviCRM ones. I know I can load from front-end.

Thanks again...will work on my SSH problem.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
