### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by graveguardian** [omega8cc/boa#1778]
I know it's new (as of this month) that there is a free and paid tier...but the install doc needs to be updated to reflect that. The new command for the free (lite) version should be: boa in-lite...rather than boa in-head.

However, when I did it that way, I go this error:

root@hwsrv-1205082:~# boa in-lite public server.domain.org me@myemail.net
ERROR:  username is already taken
Please choose different username
root@hwsrv-1205082:~#

Where is my username set?

Thanks!

**Comment by graveguardian** [comment]
I see it is noted in the changelog; perhaps install.txt just hasn't been updated yet.

No mention of username, though.

**Comment by omega8cc** [comment]
You have checked old branch probably, everything is now updated.

The error says that default Octopus user (`o1`) already exists and you need to specify different user, like `o2`

**Comment by graveguardian** [comment]
Gotcha. Thanks...will try again. 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by graveguardian** [comment]
Is it me? Tried again...but email and hostname seem to be reversed. ;-(

root@hwsrv-1205082:~# boa in-lite aegir.cemeterians.org maynard@graveguardian.net

BOA [16:38:49] ==> Skynet Agent v.BOA-5.2.0-lite welcomes you aboard!

BOA [16:38:52] ==> MODE: NORMAL INIT
BOA [16:38:52] ==> INFO: Public Setup Mode Active
BOA [16:38:52] ==> INFO: Creating your /root/.barracuda.cnf config file
BOA [16:38:54] ==> VIRT: This system is supported: Linux KVM guest

BOA [16:38:54] ==> Aegir on hwsrv-1205082.hostwindsdns.com Debian/bullseye x86_64 PHP 8.1

BOA [16:39:06] ==> INFO: Installing more basic tools now...
BOA [16:40:13] ==> INFO: Running aptitude full-upgrade...
hostname: the specified hostname is invalid
hostname: the specified hostname is invalid
BOA [16:42:02] ==> INFO: DNS test: OK

BOA [16:42:02] ==> INSTALL START -> checkpoint:

    * Your email address is
    * Your IP address is 108.174.196.142
    * Your hostname is maynard@graveguardian.net

BOA [16:42:12] ==> INFO: Running system packages update...

**Comment by graveguardian** [comment]
New error. Can this be reopened? Added details in issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by omega8cc** [comment]
You are using incomplete command. Please double check the instructions. The public keyword is missing. Also make sure that dns is working properly before installing BOA.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by graveguardian** [comment]
My bad...Guess I'm getting sloppy after the 20th time!

Sorry to waste your time. I'll get this up and running again if it kills me!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
