### ISSUE TITLE
Question : Does the move to Backdrop CMS mean that upgrading from Debian 11 to 12 or to Devuan 3 or 4 won't work? What version of Debian recommended for fresh install?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1783]
Question : Does the move to Backdrop CMS mean that upgrading from Debian 11 to 12 or to Devuan 3 or 4 won't work? I tried an upgrade from Bullseye to Bookwork, which failed, and then tried to upgrade to Chimera - which also failed - this on a test server - and I haven't reported it because I guess it isn't supported now. SO, what version of Debian (Bullseye or Bookwork) do you recommend we start with on a fresh install?

Thanks,

Ed

**Comment by omega8cc** [comment]
These things are not connected nor related. You can find all relevant details about supported OS versions in https://github.com/omega8cc/boa/blob/e3953a72d35feb2fab8927298e38518d1c44d6bf/README.txt#L110
