### ISSUE TITLE
Error while upgrading to boa lite from head.

### ISSUE THREAD

**Issue by Chester01010** [omega8cc/boa#1785]
So I tried to run the upgrade script to lite.  Everything is great till I get this error and it bombs out with the following error

BOA [14:12:43] ==> ALRT! Percona server not running properly!
BOA [14:12:43] ==> EXIT: We can't proceed and will exit now
BOA [14:12:43] ==> HINT: Please check /var/backups/barracuda-upgrade-240418-134154.log for more information,
BOA [14:12:43] ==> HINT: (re)start Percona server, then run the installer again
BOA [14:12:43] ==> Bye
 
BARRACUDA upgrade completed
Bye

Wierd part is that it verifies in the aegir console. Any help appreciated!

Aegir BOA-5.1.0-head on Devuan/chimaera x86_64

  VPS VMware ESXi guest

  DSK 3/100

  CPU 4

  RAM 5928

  NGX 1.24.0

  PHP 8.1.28

  DBV 5.7.44

  RDS 7.0.15

  SHD 8.4p1

  SSH OpenSSH_8.4p1 Debian-5+deb11u3, OpenSSL 1.1.1w  11 Sep 2023

  SSL 1.1.1w

  CRL 8.4.0

  CRL_From_Packages NO

  CRL_Local_Bin YES

  _AUT _AUTOPILOT=NO

  _CCC _CUSTOM_CONFIG_CSF=NO

  _CCL _CUSTOM_CONFIG_LSHELL=NO

  _CCR _CUSTOM_CONFIG_REDIS=NO

  _CCS _CUSTOM_CONFIG_SQL=NO

  _DBG _DEBUG_MODE=NO

  _DBS _DB_SERIES=10.2

  _DNS _DNS_SETUP_TEST=YES

  _EXP _EXTRA_PACKAGES=

  _MFS _MAGICK_FROM_SOURCES=NO

  _MFX _MODULES_FIX=YES

  _PCV _PHP_CLI_VERSION=8.1

  _PEC _PHP_EXTRA_CONF=""

  _PFD _PHP_FPM_DENY=""

  _PFV _PHP_FPM_VERSION=8.1

  _PFX _PERMISSIONS_FIX=YES

  _PMI _PHP_MULTI_INSTALL="7.4 8.1"

  _PSI _PHP_SINGLE_INSTALL=

  _SAR _SSH_ARMOUR=NO

  _SBP _STRICT_BIN_PERMISSIONS=YES

  _SFS _SSH_FROM_SOURCES=YES

  _STP _STRONG_PASSWORDS=YES

  _SUO _SYSTEM_UPGRADE_ONLY=NO

  _UMY _USE_MYSQLTUNER=NO

  _XTR _XTRAS_LIST="ADM CSF FTP CSS DCS"

  _AUT _AUTOPILOT=NO
 
Mon 18 Mar 2024 06:38:24 PM EDT / Devuan.chimaera x86_64 VMware ESXi guest / Aegir HEAD / Barracuda BOA-5.1.0-head / Nginx 1.24.0 / PHP-MI 7.4 8.1 / PHP-SE / FPM 8.1 / CLI 8.1 / Percona-5.7.44 localhost
 
Please link this information in your submission,

but only in a form of Gist snippet and not inline,

along with your hosting provider name

in the BOA issue queue on GitHub.

Rob D.

**Comment by omega8cc** [comment]
Have you checked the detailed log and successfully restarted mysql?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Not sure why you see this because it’s only displayed when one of two required files created by properly started MySQL server is missing.

Also it looks like haven’t completed system upgrade before because you are still running SSH from packages instead of from sources.

Since this check is used only when you attempt full barracuda upgrade including master Aegir instance, I would recommend that you run barracuda system only upgrade without Aegir and if that brings your SSH to 9.7p1 then you should be able to run full upgrade followed by octopus upgrade.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Besides you have wrong DB_SERIES in you barracuda.cnf — you have 10.2 instead of 5.7 which also suggests that something was not done right before to bring your system up to date.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
