### ISSUE TITLE
Site install error on new platform

### ISSUE THREAD

**Issue by graveguardian** [omega8cc/boa#1786]
Added a new platform, and tried to install a site using that platform, but got this error:

CiviCRM: civicrm is in /data/disk/o1/static/civicrm/sites/all/modules/civicrm | - | notice
DRUSH_DRUPAL_ROOT: /data/disk/o1/static/civicrm | - | ok
DRUSH_SITE_ROOT: sites/crm.graveguardian.net | - | ok
CiviCRM: Initializing the CiviCRM database. | - | notice
Loading CiviCRM database structure .. | - | notice
Drush command terminated abnormally due to an unrecoverable error. Error: Array and string offset access syntax with curly braces is no longer supported in /data/disk/o1/static/civicrm/sites/all/modules/civicrm/packages/DB/common.php, line 265

Also, my first attempt at installing this platform ended up breaking the platform, and now it's stuck with no way to delete...won't verify, won't delete. ;-(

**Comment by graveguardian** [comment]
Tried another makefile...fails also, different error:

DRUSH_DRUPAL_ROOT: /data/disk/o1/static/civi50d7 | - | ok
-- | -- | --
DRUSH_SITE_ROOT: sites/crm.graveguardian.net | - | ok
CiviCRM: Initializing the CiviCRM database. | - | notice
Loading CiviCRM database structure .. | - | notice
WD  php: TypeError: count(): Argument #1 ($value) must be of type  Countable\|array, string given in DB::parseDSN() (line 793 of  /data/disk/o1/static/civi50d7/sites/all/modules/civicrm/packages/DB.php). | - | error
Drush command terminated abnormally due to an unrecoverable error.

Are these errors due to Drush, CiviCRM, or Aegir?

The first attempt was using a makefile for civiCRM 5.9-d7 and the second was trying to use civicrm 5.0-d7.

Thanks for your help!

**Comment by omega8cc** [comment]
It looks like you’re using PHP not compatible with the platform codebase, see: docs/PHP.txt

**Comment by graveguardian** [comment]
Even with a fresh install? I made no mods.

But, I did notice on install that csd/lfd couldn't install, and no platforms installed.

Will read the doc. Thanks.

**Comment by graveguardian** [comment]
Did totally Vanilla install...

Boa in-lite public aegir.cemeterians.net ***@***.*** o1

No options. Expected to be prompted for platforms.

Used civi makefiles from omega8cc boa.

**Comment by omega8cc** [comment]
Platforms are no longer installed by default. Please check `~/static/control/README.txt`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Also, make sure you have completed post-installation upgrade as explained in the documentation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by graveguardian** [comment]
I did that, exactly according to install.txt and upgrade.txt.

Missed the part about no platforms installed anymore; install.txt mislead me. Sorry.

Thanks for your help...everytime I think I've read it all, there's still more! ;-)

**Comment by graveguardian** [comment]
Why does the octopus update ask me if I want to install pre-built platforms if they're no longer installed? I'm confused, sorry.

Years ago, when I first installed this, I remember the install asking me which platforms to install if I indicated that with "ask" or something similar.

**Comment by omega8cc** [comment]
It should be updated to reflect the current behavior which is also a few years old.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by graveguardian** [comment]
All good. I understand; the work you do on this must be very time-consuming. And very appreciated.

I've installed this at least 10 times in the last month, on a completely Vanilla debian 11 box, and it seems each time something is different each time. ;-(

Will wipe and install again. Completely stock, and see what happens this time...AFTER re-reading all the docs again that you've indicated.

Thanks again!

**Comment by graveguardian** [comment]
OK. Got all platforms installed, no problem.

HOWEVER, I'm trying to install CiviCRM from your makefiles, and cannot get it to work. Platform will not verify, and then can't be deleted. How can I clean this up?

What is the correct procedure to use the makefiles? You had indicated earlier that it may be a PHP version compatibilty error, but from what I can see, your 7.100.1 drupal version indicated in the makefile is compatible with PHP 8.1.

**Comment by omega8cc** [comment]
Using makefiles is deprecated since Drupal 8. They are still there for testing purposes but we don’t test them anymore. Also, they probably referenced old version of contrib which requires PHP 7.4. Please not that it’s something you should investigate yourself. We don’t support any specific Drupal codebase anymore and any included platform and makefiles are exclusively for testing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by graveguardian** [comment]
OK. Deleted plaform files from .drush directory and deleted from front end. All gone.

But still can't get Civi installed. ;-(

Have tried installing from Git Repository as well as from makefile. I'm sure it's me.

**Comment by graveguardian** [comment]
Just trying to do things the "BOA" way! I'll figure it out, somehow.

**Comment by graveguardian** [comment]
Have looked for the install profiles for BOA's 'canned' platforms, but can't find them anywhere...was thinking I could modify one of them. Where are they located?

**Comment by omega8cc** [comment]
Modern Drupal platforms are not installed with makefiles nor profiles. They are build with composer and then added as platforms. Still, old makefiles may not work because Drupal disabled D7 support in many areas of d.o

**Comment by graveguardian** [comment]
Thanks for the info...many things have changed since I needed to do this...dunno how you all keep up!

Will figure it out somehow.

**Comment by omega8cc** [comment]
Yes, things change fundamentally in Drupal after it replaced old core with Symfony. There are many docs on this, and in the BOA context it’s explained in docs/COMPOSER.txt

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by graveguardian** [comment]
Yes, thanks. Working through it.

It's been about 10 years since I've used any of this...even with sys admin experience back then, my skills have gotten rusty and the platforms have changed drastically.

I appreciate your patience with me. And I love BOA, or I would be trying so hard to get it to work for my use case! ;-)
