### ISSUE TITLE
csf/lfd firewall can not be installed on this system

### ISSUE THREAD

**Issue by graveguardian** [omega8cc/boa#1787]
Out of the last 10 installs, the last two were the only ones that wouldn't install csf/lfd. ALL installs on plain vanilla Debian 11 box, same aegir install parameters. All other installs before these last two would generate 100s of csf/lfd emails per day.

BOA [22:25:36] ==> INFO: Installing csf/lfd firewall...
BOA [22:25:41] ==> INFO: Upgrading csf/lfd firewall...
BOA [22:25:43] ==> TEST: csf/lfd firewall can not be installed on this system
BOA [22:25:47] ==> INFO: Updating init scripts
BOA [22:27:57] ==> INFO: InnoDB log file will be set to 256M...

What's up?

**Comment by omega8cc** [comment]
Please provide all information required when submitting issues to check.

**Comment by graveguardian** [comment]
What would you like?

Curiously, in the update, it says it's installed, but there are no blockage emails.

**Comment by graveguardian** [comment]
How do I turn on debug for initial install...or logging? Understand turning on debug for upgrades...

Thanks.

**Comment by omega8cc** [comment]
To enable both barracuda and octopus debug mode `touch /root/.debug-boa-installer.cnf`

To enable only barracuda debug mode `touch /root/.debug-barracuda-installer.cnf`

**Comment by graveguardian** [comment]
OK. Gonna try this ONE more time. I've wiped my box clean and installed Debian 11.

Do I create the ".debug-boa-installer.cnf" file BEFORE initiating BOA INIT? And will that collect all the info you need?

It's very odd. I've installed this exactly the same numerous times and csf/lfd has never been a problem before.

**Comment by cwaone** [comment]
Hi, 

i have the same error on my fresh boa install with 5.2.0-lts on chimaera. impossible to get csf installed, and i tried it two times right now. i also tried a boa up-lts after the normal installation, almost the same message

BOA [22:25:43] ==> TEST: csf/lfd firewall can not be installed on this system

the installation itself runs without any errors, also aegir works as expected - only csf is missing.

boa info more looks like -> https://gist.github.com/cwaone/6d89075f56f1c441a850fb7ac3aea448

@omega8cc any ideas?

thank you!

**Comment by omega8cc** [comment]
That’s a result of csf test, not any BOA problem. Perhaps your VM has unexpected restrictions. To determine the culprit I would recommend to try installing csf without running BOA scripts.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cwaone** [comment]
on debian 12 or devuan chimaera the iptables are just in usr/sbin/iptables and not in sbin/iptables, thats wy the test failes and csf is not installed, i got it working now :) thanks for your fast answer!
