### ISSUE TITLE
Varbase requires php-cli version 8.2

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1789]
I'm moving ~/static/control/cli.info up to 8.2 because the Varbase composer installation won't run on less than php version 8.2

The BOA upgrade fails with these messages:

BOA [14:28:47] ==> INFO: Running aptitude full-upgrade...
BOA [14:30:56] ==> ERROR: This BOA version depends on PHP 7.4 or newer
BOA [14:30:56] ==> Please add 7.4 or 8.1 to _PHP_MULTI_INSTALL
BOA [14:30:56] ==> in /root/.barracuda.cnf before trying again
BOA [14:30:56] ==> NOTE: You can still install also legacy PHP 7.x and 5.6 versions
BOA [14:30:56] ==> NOTE: but you must also include at least 7.4 to support Drupal 9
BOA [14:30:56] ==> Bye

**Comment by omega8cc** [comment]
BOA now requires at least PHP 8.1 installed, and it's still the default version unless you configure it differently. For Aegir tasks you can use the instant PHP-CLI version modification now: https://github.com/omega8cc/boa/blob/5.x-dev/docs/DRUSH.md#php-cli-version-configuration-is-much-smarter
