### ISSUE TITLE
Installing new Octopus instance

### ISSUE THREAD

**Issue by g33k-g1rl** [omega8cc/boa#1791]
Brand new aegir convert here, so be gentle please. I so appreciate everything you have done with creating BOA and I am looking forward to using this amazing program. 

I am trying to install a new octopus instance from root. 

I download the BOA.sh.txt script from 5.x-lite using these commands: 
`wget -q -U iCab https://raw.githubusercontent.com/omega8cc/boa/5.x-lite/BOA.sh.txt`
`bash BOA.sh.txt`
`screen`
`boa in-octopus email username mini stable`

The error I am getting is:
`/var/backups/OCTOPUS.sh.txt: line 1: 400:: command not found`

So I downloaded the OCTOPUS.sh.txt to the /var/backups folder. 
`wget -q -U iCab https://raw.githubusercontent.com/omega8cc/boa/5.x-lite/BOA.sh.txt`

Edit the file to include the username / instance name and email address.

Then run:
`bash OCTOPUS.sh.txt`

Then I get this error:

` EXIT: Required lib file not available?`
` EXIT: `
 `EXIT: Cannot continue`
 `EXIT: Bye (0)`

I know I am just missing something simple, but I cannot seem to figure out what it is. All suggestions are welcome.

**Comment by g33k-g1rl** [comment]
Ok after much troubleshooting I figured out we had not converted from Debian to Devuan and once I completed the migration using the .autochimaera script, it allowed me to create a new instance.

**Comment by omega8cc** [comment]
Hello and welcome to the Aegir community!

We are about to publish new release where it will be more prominently explained that we no longer officially support BOA on Debian and we have also made the conversion to latest Devuan much faster. 

We still plan to further test Debian and also hopefully re-add Ubuntu as supported for those who standardized their work on Ubuntu, though, at least until its reliance on systemd will allow the conversion to systemd-free OS.

Feel free to share your feedback and ask questions openly, we are always listening and happy to assist.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
