### ISSUE TITLE
How to upgrade from lite to lts ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1793]
Hello, I am on lite 5.2.0 and (following instructions from the UPGRADE doc) an up-lts gives an error of the command not found variety. Is there a missing LITE_TO_LTS = YES option in the barracuda.cnf file, or am I just premature.

**Comment by omega8cc** [comment]
It has been fixed because the branch rename needs some time to sync everything, but we are about to release 5.3.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
I just tried again and running up-lts from lite now works, so closing. Thank you.
