### ISSUE TITLE
Request php 8.3 be added to lite/lts

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1794]
Hello, I understand that the latest and greatest software will never be available in the lts branch, howeve,r I respectfully submit that having two current and well-used supported versions of php 8 at all times is important to enable site migrations to newer current versions of php periodically, and noting that php 8.4 is now in alpha and is scheduled for GA in November, I would like to leave php 8.1 behind now and would need 8.3 to start doing this properly. Thank you.

**Comment by omega8cc** [comment]
It will be added in the 5.3.0 release over the weekend.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by serrato-dan** [comment]
Hi there. As I've been looking to add php 8.3 to my current 5.2.0 installation and not having success, I found this thread and I'm wondering if I should be waiting for 5.3.0 for PHP 8.3 to be available. Is this correct?

**Comment by omega8cc** [comment]
Correct. The release has been delayed because we continue some important debugging which cannot be automated in any way, so it takes time. But it should be ready this week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by serrato-dan** [comment]
@omega8cc Thank you so much for the info. I thought I might have been doing something wrong. ;-) Thanks for your help and appreciate the direction the project is going. You guys are great! Take care.

**Comment by EdNett** [comment]
Thank you. Closing this since it has been added.
