### ISSUE TITLE
up-lts from Chimaera to Daedalus is taking very long due to 20-30 min waits when configuration files are updated ...

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1796]
I am running up-lts (on a screen session with log - looking at the tail of the detailed log) with the _Chimaera_TO_Daedalus=YES flag, and every time there is something like this:

put on gist here: 
https://gist.github.com/EdNett/2ce87e319c1c52276658d669ef352992

the upgrade hangs for about 20 to 30 + minutes, and there have been 4 of them so far.

Probably upgrade still works, but it's strange that it hangs for so long at each of those places.

Best,

Ed

**Comment by omega8cc** [comment]
It’s a known issue fixed in DEV. We recommend to wait for upcoming new release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Please note that currently LTS is not supporting Daedalus. It was only for debugging purposes added with very clear instructions to use only Chimaera.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
