### ISSUE TITLE
Transfer platforms with sites on Drupal 7 with BOA 4.x to a new server with BOA 5.x

### ISSUE THREAD

**Issue by OlegBesch** [omega8cc/boa#1799]
Is there any way to transfer platforms with sites on Drupal 7 with BOA 4.x to a new server with BOA 5.x, bypassing the standard export/import procedure? The sites use PHP 7.2 and a number of old unsupported modules (yes, I realize that this is not very good, but the sites still work fine and I have no reason to abandon these modules so far). On a server (8 CPUs, 12 GB RAM, 150 GB Storage) with Devuan Daedalus I have BOA 5.4.0 lts installed. I changed the PHP version in the control to 7.2 as well. 
When I try to import according to the old instructions [https://learn.omega8.cc/import-your-sites-to-aegir-in-8-easy-steps-109] at step 7 (Rename the site (using Migrate task) twice) I start getting numerous errors referring to incorrect modules code (syntax, etc.) and the first attempt to rename fails. Maybe I need to fix something in the settings so that the import procedure does not react to the old PHP code?

I have looked at the description of MIGRATE.md. If I understand correctly, the BOA versions for migration according to the instructions should be identical.

I probably would have continued to use the old server with BOA 4.x, but I needed to make a few more clones of one of the sites and was unable to do so, probably due to lack of space on the server. I've been working with BOA for quite some time now, starting as far back as BOA 3.x versions, and I'm very grateful to the developers for a great stack that freed up my hands to work on other projects. I will be very sorry if, due to porting issues with BOA 5.x, I have to abandon BOA and look for another multisiting option for D7. Rewrite modules and upgrade sites from D7 to D8,9,10,11 I, unfortunately, do not have time, and I do not want to remake what works well. 

I will be very appreciate any ideas.

**Comment by omega8cc** [comment]
Any reason to not upgrade your existing server instead? Why to migrate if you can upgrade instead? We regularly test upgrades from very old BOA 4.x and it just works.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
As for the xboa tool, it does require both servers to run the same BOA version, simply to avoid ending up in the compatibility chaos, but we are working on opening possibility to also import legacy non-BOA Aegir running on Apache so that limitation will be removed very soon (later this month we hope).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
You will not break anything. Current BOA release has been tested on Debian Stretch. It even has improved compatibility with previous Debian Jessie. You can upgrade to current BOA without upgrading your OS version.

But if you’re still afraid, then waiting for improved xboa tool is also an option.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OlegBesch** [comment]
> You will not break anything. Current BOA release has been tested on Debian Stretch. It even has improved compatibility with previous Debian Jessie. You can upgrade to current BOA without upgrading your OS version.
> 
> But if you’re still afraid, then waiting for improved xboa tool is also an option.
> 

Sounds good! Okay, I will try to update BOA on the old server and then do the migration.
Thanks for the information!
