### ISSUE TITLE
Unable to Login with o1.ftp user via su command from commandline

### ISSUE THREAD

**Issue by cwaone** [omega8cc/boa#1800]
Hi,

i installed a fresh BOA LTS 5.4 - on this system everything is working fine, on my old servers i´m unable to login to o1.ftp with the su command.

Traceback (most recent call last):
  File "/usr/bin/lshell", line 25, in <module>
    from lshell.checkconfig import CheckConfig
ImportError: No module named lshell.checkconfig

i have updatet the system to the newest release today, but still getting the same error. Any ideas?

thank you!

**Comment by omega8cc** [comment]
Run `wget -qO- http://files.aegir.cc/BOA.sh.txt | bash` twice. It should install newer Python and rebuild Lshell.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cwaone** [comment]
i tried to, seems to be an ssl error on pypi.org ?
![ssl-error-python](https://github.com/user-attachments/assets/56fcad4b-4bf5-425d-9f90-c7488a9592f2)

**Comment by omega8cc** [comment]
No, it’s a sign of broken local Python which needs to be reinstalled from sources to use newer OpenSSL version. Try to move away `/usr/local/bin/python3` and run the installer again.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cwaone** [comment]
ok, it seems to be a symlink to python3.12 - ill try it on saturday. thanks for your fast answer ;)

**Comment by cmastro-ixiam** [comment]
Running `wget -qO- http://files.aegir.cc/BOA.sh.txt | bash` twice did not fix the problem (in my case).

![image](https://github.com/user-attachments/assets/c0eb6fe9-30f8-4858-b462-bd896a81f161)

The solution I have applied is the following:
- Update `pip` with a trusted host: `# pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --root-user-action ignore  --upgrade pip`

![image](https://github.com/user-attachments/assets/92885727-f2a6-4f78-87b0-f80f510441d0)

- Run `BOA.sh.txt` twise: `# wget -qO- http://files.aegir.cc/BOA.sh.txt | bash`

![image](https://github.com/user-attachments/assets/d8882b5b-fb0f-4892-94cb-c51da24ee1f1)
