### ISSUE TITLE
Query re Unbound and Bind on server running PDNSD

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1804]
Hello,

This server (Chimera 5.4.0-lts) used to run pdnsd and bind9 perfectly. Now I see that unbound has been installed, but it will not run, and I cannot see whether or not bind9 and / or pdnsd are running. My guess is that none of the three are running, even though /etc/init.d/ files or symlinks exist for bind and pdnsd.

server1:~# service unbound status
unbound is not running ... failed!
server1:~# service unbound start
Starting DNS server: unbound/etc/init.d/unbound: 35: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 36: /usr/libexec/unbound-helper: Permission denied
[1724679277] unbound[23315:0] error: can't bind socket: Address already in use for ::1 port 53
[1724679277] unbound[23315:0] fatal error: could not open ports
 failed!
server1:~# service pdnsd status (no return) - the "(no return)" is my addition
server1:~# service pdnsd restart (no return) - the "(no return)" is my addition
server1:~# service bind status
bind: unrecognized service
server1:~# service bind9 status
bind9: unrecognized service

Do we need to manually remove pdnsd and / or bind9 ?

Boa info more is here: https://gist.github.com/EdNett/f8fa5a56da6a7b1e5a4b361511f53def

Best regards,  Ed

**Comment by EdNett** [comment]
After running today's upgrade ( Friday Aug 30 10:30 UTC -up-lts-5.4.0T02 I believe), I can see an unbound process when viewing htop, but on the command line I get the following errors still:

server1:~# htop
server1:~# service unbound status
unbound is not running ... failed!
server1:~# service unbound start
Starting DNS server: unbound/etc/init.d/unbound: 35: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 36: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 38: /usr/libexec/unbound-helper: Permission denied
.
server1:~# /etc/init.d/unbound status
unbound is not running ... failed!
server1:~# /etc/init.d/unbound help
Usage: /etc/init.d/unbound {start|stop|restart|status|reload|force-reload}
server1:~# /etc/init.d/unbound force-reload
Restarting DNS server: unbound/etc/init.d/unbound: 59: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 61: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 62: /usr/libexec/unbound-helper: Permission denied
.
server1:~# /etc/init.d/unbound restart
Restarting DNS server: unbound/etc/init.d/unbound: 59: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 61: /usr/libexec/unbound-helper: Permission denied
/etc/init.d/unbound: 62: /usr/libexec/unbound-helper: Permission denied
.

**Comment by EdNett** [comment]
Wow - on a similar but different server, which I just upgraded up-lts (Friday Aug 30 11:45 UTC), unbound IS running:

root@server1:~# service unbound status
unbound is running.
root@server1:~#

**Comment by EdNett** [comment]
And now "service unbound status" shows unbound as running on the first server a few hours after restarting it - perhaps it just takes an hour or two to get going!

**Comment by EdNett** [comment]
on the server where unbound is running there are 3 "unbound.conf" files:

1) one in /usr/etc/unbound/

2) one in /usr/etc/unbound/etc/unbound/ (also exists 4 other .pem and .key files)
 
3) and the third in:  /usr/etc/unbound/etc/unbound/unbound.conf.d/ (also exists one other file here)



on the server where unbound is not running and fails to start there is only one unbound.conf file in /usr/etc/unbound/  and there exists only that one file !!!

**Comment by EdNett** [comment]
Is there a flag to reinstall unbound completely (as there is for nginx and percona, etc) ?

**Comment by omega8cc** [comment]
`touch /usr/etc/unbound/unbound.pid`
`barracuda up-lts system`

This should reinstall unbound from scratch.

**Comment by EdNett** [comment]
Hello, Thank you for that. I followed those instructions, and the other directories with their respective files were added, and after the up-lts system unbound was shown as running. I restarted the server, and it wasn't running any longer with these messages:

server1:~# htop
server1:~# service unbound status
unbound is not running ... failed!
server1:~# service unbound status
unbound is not running ... failed!
server1:~# service unbound start
Starting DNS server: unbound.
server1:~# service unbound status
unbound is not running ... failed!
server1:~# service unbound status
unbound is not running ... failed!
server1:~# service unbound restart
Restarting DNS server: unbound/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
.
server1:~# service unbound status
unbound is not running ... failed!
server1:~# unbound version
usage:  unbound [options]
        start unbound daemon DNS resolver.
-h      this help.
-c file config file to read instead of /usr/etc/unbound/unbound.conf
        file format is described in unbound.conf(5).
-d      do not fork into the background.
-p      do not create a pidfile.
-v      verbose (more times to increase verbosity).
-V      show version number and build options.

Version 1.21.0
BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
server1:~# unbound -v
[1725090762] unbound[23246:0] notice: Start of unbound 1.21.0.
server1:~# /etc/init.d/unbound status
unbound is not running ... failed!
server1:~# /etc/init.d/unbound start
Starting DNS server: unbound.
server1:~# /etc/init.d/unbound status
unbound is not running ... failed!
server1:~# /etc/init.d/unbound restart
Restarting DNS server: unbound/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
.
server1:~#

**Comment by EdNett** [comment]
After rebooting again, service unbound status shows unbound not running and it fails to restart with the same error messages as above, yet in htop I can see an unbound process (/usr/sbin/unbound),
  and there is nothing in the /var/log/unbound/unbound.log - it is an empty file.

server1:~# unbound -vvv
[1725092087] unbound[9614:0] notice: Start of unbound 1.21.0.
[1725092087] unbound[9614:0] debug: creating udp6 socket ::1 53
[1725092087] unbound[9614:0] debug: creating tcp6 socket ::1 53
[1725092087] unbound[9614:0] debug: creating udp4 socket 127.0.0.1 53
[1725092087] unbound[9614:0] debug: creating tcp4 socket 127.0.0.1 53
[1725092087] unbound[9614:0] debug: module config: "validator iterator"
[1725092087] unbound[9614:0] debug: switching log to syslog

So I will check syslog: during restart:

Aug 31 07:42:04 server1 acpid: starting up with netlink and the input layer
Aug 31 07:42:04 server1 acpid: 0 rules loaded
Aug 31 07:42:04 server1 acpid: waiting for events: event logging is off
Aug 31 07:42:04 server1 unbound: [2925:0] error: cannot open pidfile /run/unbound/unbound.pid: No such file or directory
Aug 31 07:42:04 server1 unbound: [2925:0] notice: init module 0: validator
Aug 31 07:42:04 server1 unbound: [2925:0] notice: init module 1: iterator
Aug 31 07:42:04 server1 unbound: [2925:0] info: start of service (unbound 1.21.0).

that repeats a few times and finally:

Aug 31 07:53:28 server1 unbound: [30219:0] error: cannot open pidfile /run/unbound/unbound.pid: No such file or directory
Aug 31 07:53:28 server1 unbound: [30219:0] notice: init module 0: validator
Aug 31 07:53:28 server1 unbound: [30219:0] notice: init module 1: iterator
Aug 31 07:53:28 server1 unbound: [30219:0] info: start of service (unbound 1.21.0).
Aug 31 07:54:04 server1 unbound: [23247:0] info: resolving sg.files.aegir.cc. A IN
Aug 31 07:54:04 server1 unbound: [23247:0] info: resolving sg.files.aegir.cc. AAAA IN
Aug 31 07:54:04 server1 unbound: [23247:0] info: response for sg.files.aegir.cc. A IN
Aug 31 07:54:04 server1 unbound: [23247:0] info: reply from <aegir.cc.> 2001:4b98:aaab::f6#53
Aug 31 07:54:04 server1 unbound: [23247:0] info: query response was ANSWER
Aug 31 07:54:04 server1 unbound: [23247:0] info: response for sg.files.aegir.cc. AAAA IN
Aug 31 07:54:04 server1 unbound: [23247:0] info: reply from <aegir.cc.> 2001:4b98:aaaa::13#53
Aug 31 07:54:04 server1 unbound: [23247:0] info: query response was ANSWER

etc.

So maybe unbound is running, and it is just showing as not running ? That's my guess. I'll leave this open for now - for you to close if you agree unbound is running properly. I don't know how else to debug it.

Best,

Ed

**Comment by omega8cc** [comment]
Yes, it’s starting duplicate instances probably. You can just `killall -9 unbound` and allow the system to start it properly, but it shouldn’t be necessary so there’s still something we need to fix.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
This should be fixed now if you run `barracuda up-lts system`

**Comment by EdNett** [comment]
Hello,  I just tried this twice - with the same result - unbound is running after the up-lts , and it restarts fine, but after rebooting the server it is not running and failed to start. I even removed it completely, recreated the /usr/etc/unbound/ directory, put the unbound.pid file in there and re-ran the up-lts - with the same results.

I have noticed that I do not have the daily, second.sh etc. scripts in /var/xdrago/, but rather they are in /var/xdrago_wait/ subdirectory, and when I try to run a few manually from the command line (like used to be advised) for example, I get erros, and a daily.sh which seems to run, but runs so quickly that I don't believe it actually ran:

server1:~# service unbound status
unbound is not running ... failed!
server1:~# bash /var/xdrago_wait/manage_ltd_users.sh
4800 (process ID) old priority 0, new priority 19
Missing /var/xdrago/conf/lshell.conf template
server1:~# bash /var/xdrago_wait/daily.sh
4884 (process ID) old priority 0, new priority 19
INFO: Daily maintenance start
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Reloading (via HUP) Nginx Server...:.
INFO: Daily maintenance complete
server1:~# bash /var/xdrago_wait/second.sh
du: cannot access '/usr/fastcgi_temp/*/*/*': No such file or directory

Is this /xdrago_wait/ directory suppossed to exist, and could this be the problem?

Best,

Ed

**Comment by EdNett** [comment]
I decided to remove the nearly empty /var/xdrago/ folder and rename the /xdrago_wait/ foler to xdrago, and try everything again. It must have been from a past aborted up_to_dedalus attempt ?

**Comment by omega8cc** [comment]
It seems that you have had seriously broken system if the critically important self-healing was not in place. No wonder it couldn't manage services properly.

**Comment by EdNett** [comment]
Well that situation existed for less than 20 min. That wasn't the problem. (I tried to "solve" the problem by upgrading chimera to daedalus, but that stalled immediately at an atp-keyring problem).

When I look at /etc/init.d/unbound, I find:
NAME="unbound"
DESC="DNS server"
DAEMON="/usr/sbin/unbound" - that exists
PIDFILE="/run/unbound/unbound.pid"  - there is no "unbound" directory here! and no "unbound.pid file anywhere that I can find. 

HELPER="/usr/libexec/unbound-helper" -that exists

So, I have created the unbound directory in the /run/ folder and now it starts! I will try another up-lts and then reboot to see if it is dependable and resilient.

**Comment by EdNett** [comment]
So, I have found the problem on this server - when I restart (reboot) the server, the /unbound/ directory and the "unbound.pid" file within it are no longer there. That is why unbound is working after the up-lts and fails to start with the server reboot. 

Any ideas?

Best,

Ed

**Comment by omega8cc** [comment]
We believe that we have finally fixed all those confusing problems. It should be enough to run:

`barracuda up-lts system`

**Comment by EdNett** [comment]
FIXED!

Thank you for this fix. Thank you also for putting the unbound log back in its own log and out of syslog since there are literally hundreds of entries per second. Glad I could be of some small help!
Best, Ed
