### ISSUE TITLE
System Integrity checking detects /bin/sh changes if _SKYNET_MODE=OFF

### ISSUE THREAD

**Issue by reswild** [omega8cc/boa#1806]
I recently turned off the 'Skynet Mode' on some of my servers, and after this, I started getting regular 'System Integrity checking detected a modified system file' emails warning me about changes to `/bin/sh` and `/usr/bin/sh`.

I looked into this a bit, and what appears to be happening is that once _SKYNET_MODE is set to OFF, the BOA.sh.txt script executes `service clean-boa-env start` every time it runs, which changes these two symlinks to point to `/bin/dash` instead of `/bin/websh`. Then, every time the manage_ltd_users.sh script runs, this changes it back to `/bin/websh`.

I was also able to reproduce this on a fresh BOA install.

**Comment by omega8cc** [comment]
This behavior shouldn't occur because the script is only triggered if `/etc/csf/csfpost.sh` is missing. When this happens, it forces a `csf/lfd` self-upgrade, which temporarily switches the system's default shell from `websh` to `dash`. We also don't recommend setting `_SKYNET_MODE=OFF` unless there's a specific reason to use an outdated BOA version. However, I don't believe that disabling `_SKYNET_MODE` is the cause of the issue here.

**Comment by reswild** [comment]
OK, but `/etc/csf/csfpost.sh` is present on all my servers, and as I mentioned, I was able to reproduce this on a fresh BOA install: All I did was run `boa in-lts` and then set `_SKYNET_MODE=OFF`.

Looking through the BOA.sh.txt script, I can see there is a code block there that only executes if `/etc/csf/csfpost.sh` is present, but the next code block also executes `service clean-boa-env start`, and this code block doesn't have this restriction. If I stop `clean-boa-env` from executing, the behaviour stops, and the behaviour also stops if I re-enable `_SKYNET_MODE`.

**Comment by omega8cc** [comment]
You are right, we never disable it so it went unnoticed that the regex in the second occurrence was wrong — now fixed: https://github.com/omega8cc/boa/commit/1a369c5f783bcb493828d633575423378ad48920

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reswild** [comment]
Thanks, that appears to have resolved the issue.
