### ISSUE TITLE
percona-server-5.7 not installed on Debian 11

### ISSUE THREAD

**Issue by DigitalForceEU** [omega8cc/boa#1808]
Today installed a fresh Debian 11 machine and installed BAO exactly like the documentation.

boa in-lts public host.domain.nl email@domain.com o1 php-min verbose

I see the following on screen (not in the log);
`/usr/bin/apt-get -fuy --allow-unauthenticated -q --config-file /opt/apt/apt.conf.noi.dist install percona-server-server failed.  Error (if any): 0`

In the log I do see that i installs only a part of the percona setup.
libperconaserverclient20-dev mysql-common percona-server-common-5.7
But not, percona-server-5.7

It seems like percona-server-server is written wrong. I cannot manually correct it afterwards (afaik). It's a test so I will wait if it works later.

```
boa info
Aegir BOA Cluster on Devuan/daedalus x86_64
  HOST QEMU
  VPS Linux KVM guest
  DSK 2/100
  CPU 6
  RAM 15958
  NGX 1.27.1
  PHP 8.3.10
  DBV 5.7.44
  RDS 7.0.15
  SHD 9.8p1
  SSH OpenSSH_9.8p1, OpenSSL 3.0.14 4 Jun 2024
  SSL 3.0.14
  CRL 8.9.1
  CRL_From_Packages NO
  CRL_Local_Bin YES
```

I think this is wrong. Will try to test it myself :-)
https://github.com/search?q=repo%3Aomega8cc%2Fboa++percona-server-server&type=code 

Thanks for the great software. If i do something wrong, excuse me :-)

**Comment by omega8cc** [comment]
Thanks, that was a weird regression introduced during Percona 8 support related work.

**Comment by DigitalForceEU** [comment]
it's missing the dot in the package;
package is named; percona-server-server-5.7
not percona-server-server-57

Thanks.

**Comment by omega8cc** [comment]
Ouch! Fixed finally.
