### ISSUE TITLE
How to cleanly redirect a site to an external domain e.g facebook.com/page

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#1810]
Just wanted feedback on the cleanest way to temporarily redirect a hosted site to an external website such as a facebook.com/page?

I was going to override the nginx vhost file for that site but thought I'd reach out and ask how others might achieve the same result.

I'm aware BOA does all sorts of checks and resets and thought I'd ask to make sure this specific vhost/site is ignored from any of such checks, if that's even possible?

**Comment by omega8cc** [comment]
It's explained in the docs: https://github.com/omega8cc/boa/blob/5.x-dev/docs/REWRITES.md

Basically, create `nginx_force_include.conf` in  `/data/disk/USER/config/server_master/nginx/post.d/` and add there lines:

```
  if ($host ~* ^(www\.)?(foo\.com)$) {
    return 301 https://facebook.com/page;
  }

```
Or if the site has aliases, to avoid listing them all:

```
  if ($main_site_name ~* ^(www\.)?(foo\.com)$) {
    return 301 https://facebook.com/page;
  }

```

Now run `service nginx reload`
