### ISSUE TITLE
Where to install modules using composer

### ISSUE THREAD

**Issue by g33k-g1rl** [omega8cc/boa#1811]
Hi there,

I'm trying to install a module using composer. I am cd'ed into the site folder at /data/disk/lms/distro/002/drupal-10.3.1-prod/web/sites/d10.smll.dev

It gives me the error message:   /data/disk/lms/distro/002/drupal-10.3.1-prod/vendor/drush/drush does not exist and could not be created:     

This is the full log I am getting:
`No composer.json in current directory, do you want to use the one at /data/disk/lms/distro/002/drupal-10.3.1-prod? [Y,n]? 
Always want to use the parent dir? Use "composer config --global use-parent-dir true" to change the default.
./composer.json has been updated
Running composer update drupal/bootstrap_layout_builder
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Downloading drupal/media_library_form_element (2.1.1)
  - Downloading drupal/bootstrap_styles (1.1.6)
  - Downloading drupal/bootstrap_layout_builder (2.1.2)
    Failed to download drush/drush from dist: /data/disk/lms/distro/002/drupal-10.3.1-prod/vendor/drush/drush does not exist and could not be created: 
    Now trying to download from source
  - Syncing drush/drush (12.5.2) into cache
  - Installing drupal/media_library_form_element (2.1.1): Extracting archive
  - Installing drupal/bootstrap_styles (1.1.6): Extracting archive
  - Installing drupal/bootstrap_layout_builder (2.1.2): Extracting archive
    Install of drupal/media_library_form_element failed
    Install of drupal/bootstrap_styles failed
    Install of drupal/bootstrap_layout_builder failed

In Filesystem.php line 261:
                                                                               
  /data/disk/lms/distro/002/drupal-10.3.1-prod/vendor/drush/drush does not exist and could not be created:                                                
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
`

**Comment by omega8cc** [comment]
Two things. Firstly, composer commands must be run from app root, not web root and certainly not site directory. Secondly, before trying to run composer please run the Unlock Drush task for the platform you are working on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
We normally don’t cover this our docs, but it’s important to note that Composer based codebase management is very different than the Drush based workflow for Drupal 7 or Drupal 6. Composer doesn’t know anything about sites or aliases, it just cares about the codebase only and always has to be run from the codebase app root (where vendor exists). There’s nothing specific to Composer use in the BOA context, apart from the requirement to Unlock Drush (which actually unlocks also other parts of the codebase) before attempting to use Composer.

**Comment by g33k-g1rl** [comment]
Thank you! I'm used to working on Drupal 7 on vanilla Aegir, so Drupal 10 on BOA is a whole new experience.
