### ISSUE TITLE
Unable to Login with o1.ftp user via su command from commandline (ModuleNotFoundError: No module named 'readline')

### ISSUE THREAD

**Issue by cmastro-ixiam** [omega8cc/boa#1812]
Following the steps in the issue https://github.com/omega8cc/boa/issues/1800 I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/lshell", line 26, in <module>
    from lshell.shellcmd import ShellCmd, LshellTimeOut
  File "/usr/local/lib/python3.12/site-packages/lshell/shellcmd.py", line 26, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

If I install the "readline" module manually (`pip install readline`), I can log in via SSH but I can't run any commands. Also, Python doesn't seem to work properly.

**Comment by omega8cc** [comment]
Please provide required system report.

**Comment by cmastro-ixiam** [comment]
Hello, Is this report helpful?

- `cat /var/log/barracuda_log.txt`
```
Mon Sep 9 10:42:10 AM EDT 2024 / Devuan.daedalus x86_64 / Aegir lts / Barracuda BOA-5.4.0-lts / Nginx 1.27.1 / PHP-MI 8.1 / PHP-SE 8.1 / FPM 8.1 / CLI 8.1 / Percona-5.7.44 localhost
```


- `# wget -qO- http://files.aegir.cc/BOA.sh.txt | bash`

```
STATUS: Skynet Agent is Active, OK!
STATUS: You can add the _SKYNET_MODE=OFF line in
STATUS: /root/.barracuda.cnf to disable me, if needed.

BOA Meta Installers setup completed
Please check INSTALL.md and UPGRADE.md at https://github.com/omega8cc/boa
Bye

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (23.0.1+dfsg-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pip in /usr/local/lib/python3.12/site-packages (24.2)
Processing /var/opt/lshell-0.9.18.10
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lshell
  Building wheel for lshell (pyproject.toml) ... done
  Created wheel for lshell: filename=lshell-0.9.18-py3-none-any.whl size=63781 sha256=d668fca565322fd9491679295ff5921443cfbdba52027bff8ab78c851387f658
  Stored in directory: /root/.cache/pip/wheels/8d/35/33/fc3c84065101960e3859cf654e3e445d5b424f07fbf0f5f346
Successfully built lshell
Installing collected packages: lshell
Successfully installed lshell-0.9.18
Reloading nginx configuration: nginx.
```

Thanks!

**Comment by omega8cc** [comment]
I meant what is explained for years in https://github.com/omega8cc/boa/blob/5.x-dev/docs/CONTRIBUTING.md

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmastro-ixiam** [comment]
Hi,

Thank and I apologize for this misunderstanding :sweat_smile: . I've seen several of the latest reported issues (including #1800) and none of them had what you mention, and I tried to use the structure of those issues. I've now learned it and will add it if I create new issues. Thanks again!

If you allow me a suggestion for this, maybe CONTRIBUTING could be copied under the name BUGS_REPORTING or a template (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates) could be created for the issues with a link to the CONTRIBUTING file.

Back on topic, here is the system report:
- https://gist.github.com/cmastro-ixiam/7abc797a7f7de01f9c30b448bc61128f

Thanks!

**Comment by omega8cc** [comment]
Thank you for the suggestion, but it’s already covered in the project README.

**Comment by omega8cc** [comment]
Something is wrong on your server if you see: VPS unknown / not a virtual machine. It will affect many components in the unexpected way. Have you installed anything beyond BOA which would remove essential components?

**Comment by cmastro-ixiam** [comment]
Hello,

Thanks for your reply.

I've checked all our servers and all the installations we have say `VPS unknown / not a virtual machine`, but only on this server we have this lshell problem.

Executing the `wget ​​-qO- http://files.aegir.cc/BOA.sh.txt | bash` didn't fix it.
Any ideas how to fix it?

Many thanks!

**Comment by omega8cc** [comment]
You need to debug your custom lshell configuration or remove `_CUSTOM_CONFIG_LSHELL=YES`

Still, you need to debug the broken VM identification, because it will cause more issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmastro-ixiam** [comment]
Thanks!
