### ISSUE TITLE
Request ReOpen this issue - it is BOA specific - Terminal for octopus user gets automatically shutdown since recent update - cannot su o1.ftp either

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1813]
Hello,

I just noticed that the octopus terminal (when I login to boa-lts latest) as the o1.ftp user - the terminal is automatically shutdown within less than a second. This happens even if I also have a root terminal open. (Logging in as rppt  - that terminal stays open). This is new behavior - this has never happpened before. Is it intentional? 

[I prefer to ssh in as the octopus user when using composer to update and create new platforms and attempt migration of sites. ] 

My ssh client - which I like very much - uses the protocol "xterm" and "use bvterm if available" is enabled, and the character set is UTF-8.

boa info more is here:
https://gist.github.com/EdNett/9c3d40cca7c6be2fab332052ec880c6a

Is this related to this issue: https://github.com/omega8cc/boa/issues/1800, and should I follow those instructions (move away python so running the barracuda upgrade will reinstall it) ? Thanks.

Best, ED

**Comment by omega8cc** [comment]
No idea, can you comment more on the VM you are running?

`VPS unknown / not a virtual machine`

**Comment by omega8cc** [comment]
Furthermore, you are pretty much on your own when you disable this:

`_SKYNET_MODE=OFF`

**Comment by EdNett** [comment]
Hello, I will re-run the barracuda up-lts command with _SKYNET_MODE=ON, and report back here. This is a dedicated server, which I prefer to use as-is (without dividing it up into virtual machines). This has always worked.

I ran the upgrade and this appeared to work, the terminal informing me that I needed to set a new password for o1.ftp user, which I did. Then I logged out, and when trying to login again in ssh as the o1.ftp user I encountered this error message (on a terminal window that was - and stated "disconnected":

 Skynet Agent v.BOA-5.4.0-lts on Devuan/chimaera welcomes you aboard

Traceback (most recent call last):
  File "/usr/bin/lshell", line 26, in <module>
    from lshell.shellcmd import ShellCmd, LshellTimeOut
  File "/usr/local/lib/python3.12/site-packages/lshell/shellcmd.py", line 26, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'


After that I am unable to login at all with the same results as before (no terminal windows opens at all, my ssh client telling me "Terminal channel closed by server".

**Comment by omega8cc** [comment]
Running BOA on bare metal is not supported and was never tested. We just don’t consider this enough safe and reliable because once system is broken or unable to boot it’s hard to recover. It may work, but please don’t expect our support.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
It seems to be this issue: https://github.com/omega8cc/boa/issues/1812  and when I first started the barracuda up-lts I could see it automatically did something with pip and lshell ... which printed out on the terminal before the up-lts command could be given, once I gave the wget command:

0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Requirement already satisfied: pip in /usr/local/lib/python3.12/site-packages (24.2)
Processing /var/opt/lshell-0.9.18.10
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lshell
  Building wheel for lshell (pyproject.toml) ... done
  Created wheel for lshell: filename=lshell-0.9.18-py3-none-any.whl size=63782 sha256=079b3aa0daed2e7d3fa2f2118c5f413ffbec956b44286e283ff0728cf762f755
  Stored in directory: /root/.cache/pip/wheels/8d/35/33/fc3c8406510196df3859cf654e3e445d5b424f07fbf0f5f346
Successfully built lshell
Installing collected packages: lshell
Successfully installed lshell-0.9.18

**Comment by EdNett** [comment]
I just had a thought. Are there any limits for the length of the o1.ftp password which, if exceeded, might cause this behavior? I like to use longer passwords than most: my o1.ftp and o2.ftp passwords are from 80 to 255 characters including special characters. Is this perhaps the problem? If so, would 128 character passwords be OK? and can they contain special characters? Thank you.

**Comment by EdNett** [comment]
This must be BOA specific. I don't believe that password length has anything to do with this, since I can sftp in. On a different server, which is also on boa-lts updated yesterday, When I login as root and su o2.ftp I cannot and also receive this error:

server1:~# su o2.ftp
Warning: your password will expire in 6 days.
Traceback (most recent call last):
  File "/usr/bin/lshell", line 26, in <module>
    from lshell.shellcmd import ShellCmd, LshellTimeOut
  File "/usr/local/lib/python3.12/site-packages/lshell/shellcmd.py", line 26, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
server1:~#

Has this bug been fixed in dev but not synced to lts?  What to do? I cannot use the server at all with composer or drush now. How was issue #1812 resolved?

Best,  Ed

**Comment by omega8cc** [comment]
We have already stated that we cannot so we will not respond further to any reports about running BOA on unsupported system configuration. You are free to experiment but without our assistance. I’m locking this issue because you apparently ignored what has been clearly stated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
