### ISSUE TITLE
Jetty 9 not installed on chimera boa-lts

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1814]
Hello, I just noticed that jetty 9 is not installed on latest lts on Chimera. What to do?  There is no /etc/init.d/jetty9 entry, and  solr 7 is installed and running.  There is no jetty9 or jetty entry in the /opt/ directory. There is no jetty9 file inside /etc/default/.

boa info more is here:  https://gist.github.com/EdNett/9c3d40cca7c6be2fab332052ec880c6a

I see this:

server1:~# java -version
openjdk version "11.0.24" 2024-07-16
OpenJDK Runtime Environment (build 11.0.24+8-post-Debian-2deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.24+8-post-Debian-2deb11u1, mixed mode, sharing)
server1:~# update-alternatives --list java
/usr/lib/jvm/java-11-openjdk-amd64/bin/java
/usr/lib/jvm/java-17-openjdk-amd64/bin/java

and this:

server1:~# ps ax |grep java
 3338 ?        Sl     1:54 /usr/lib/jvm/java-11-openjdk/bin/java -server -Xms64m -Xmx8013m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:-OmitStackTraceInFastThrow -Xlog:gc*:file=/var/solr7/logs/solr_gc.log:time,uptime:filecount=9,filesize=20M -Dsolr.log.dir=/var/solr7/logs -Djetty.port=9077 -DSTOP.PORT=8077 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -Djetty.home=/opt/solr7/server -Dsolr.solr.home=/var/solr7/data -Dsolr.data.home= -Dsolr.install.dir=/opt/solr7 -Dsolr.default.confdir=/opt/solr7/server/solr/configsets/_default/conf -Dlog4j.configurationFile=file:/var/solr7/log4j2.xml -Xss256k -Dsolr.jetty.https.port=9077 -Dsolr.log.muteconsole -XX:OnOutOfMemoryError=/opt/solr7/bin/oom_solr.sh 9077 /var/solr7/logs -jar start.jar --module=http
17111 pts/0    SN+    0:00 grep --color=auto java
server1:~#

Best, Ed

**Comment by omega8cc** [comment]
Please check https://github.com/omega8cc/boa/blob/5.x-dev/docs/NOTES.md

**Comment by EdNett** [comment]
Thank you. I hadn't understood that "SR7" alone would not install jetty, and that specifying "SR4" would install jetty 9. Running barracuda up-lts specifying "SR4 SR7" did install it. Best, Ed
