### ISSUE TITLE
Inconsistent checks for SSL version in check_php_rebuild

### ISSUE THREAD

**Issue by reswild** [omega8cc/boa#1815]
I've been having some issues with rebuilding PHP on my servers, and while debugging this, I noticed that the checks for OpenSSL version when updating Barracuda gives inconsistent results. In the `check_php_rebuild()` function in php.sh.inc, there is a check for `/opt/php$1/bin/php -i | grep "SSL Version"`, but this gives you the version of SSL that is used by Curl, which appears to be whatever is set as system default. If you want to check what version of SSL PHP is built with, I think you'll have to check either `OpenSSL Library Version` or `OpenSSL Header Version` instead.

On the server I'm currently testing `/opt/php82/bin/php -i | grep "SSL Version"` gives me
`SSL Version => OpenSSL/3.0.15`
while `/opt/php82/bin/php -i | grep "OpenSSL Library Version"` gives me
`OpenSSL Library Version => OpenSSL 1.1.1w  11 Sep 2023`

There is another identical check in system.php.inc which triggers when OpenSSL needs updating and this sets `_PHP_FORCE_REINSTALL=YES` which triggers a PHP rebuild, but only once, so if I have multiple PHP versions installed only the first PHP version is rebuilt. And no further rebuilds are triggered by re-running `barracuda up`.

**Comment by omega8cc** [comment]
It was intentionally left like this before, so we don't affect legacy systems, but we should fix this already. However, we should test `OpenSSL Header Version` instead:

```
stretch:~# /opt/php81/bin/php -i | grep "OpenSSL"
SSL Version => OpenSSL/3.0.15
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 3.0.15 3 Sep 2024
OpenSSL Header Version => OpenSSL 3.0.13 30 Jan 2024
OpenSSL support => enabled
stretch:~#

```
```
stretch:~# /opt/php80/bin/php -i | grep "OpenSSL"
SSL Version => OpenSSL/3.0.15
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 3.0.15 3 Sep 2024
OpenSSL Header Version => OpenSSL 3.0.14 4 Jun 2024
OpenSSL support => enabled
stretch:~#

```
```
stretch:~# /opt/php74/bin/php -i | grep "OpenSSL"
SSL Version => OpenSSL/3.0.15
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 3.0.15 3 Sep 2024
OpenSSL Header Version => OpenSSL 3.0.14 4 Jun 2024
OpenSSL support => enabled
stretch:~#

```
