### ISSUE TITLE
Did skynet do anything today, Oct 1 2024 at 14:00 UTC ? Our BOA server went down then and has been down since - 2h30 min.

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1820]
Hello,
Did skynet do anything today, Oct 1 2024 at 14:00 UTC ? Our BOA server went down then and has been down since - 2h30 min.
Unreachable by SSH. I have asked teh server providor if there's a problem at their end.
Best,

Ed

**Comment by omega8cc** [comment]
No.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
I noticed that the server was down and I couldn't ssh in I enabled rescue mode and logged-in, mounted the boa system and saw that the /etc/passwd, /etc/group and /etc/shadow files all had duplicate files with a "-" at their end with very slightly different sizes, and some octopus users had been added, which I deleted, so I had to enable a network firewall, which stopped the strange activity, and have replaced ssh key - now the server is running again - and I've noticed that more of the sites on the server all have failed ssl certs now whereas 2 days ago it was just 3 of them!
