### ISSUE TITLE
Server crashed segfault errors

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1821]
Hi,

Any help on this would be greatly appreciated. 
We are a school and are running BOA already for years. Since the last year we did not manage to keep BOA updated. But it did still work.
Today we had some issues with LE certificates. I checked on this and rebooted the server. After that, ther is no website available anymore.

I want to show our boa info output but I get these errors:

"Segmentation fault"

In the logs I can find this:
kernel: [  348.471382] grep[6326]: segfault at 5638a47f3eb0 ip 00007fd868a7e187 sp 00007fffc891c4b8 error 4 in libc-2.24.so[7fd868992000+195000]
kernel: [  348.506188] bash[6316]: segfault at 0 ip 00007f9396cd2425 sp 00007ffdbd9b6e20 error 4 in libc-2.24.so[7f9396c08000+195000]

When starting the server I also get the error:

<img width="366" alt="java fout" src="https://github.com/user-attachments/assets/4e8eff6d-0d3b-425a-b339-e6646a983072">

and:

<img width="334" alt="umask error" src="https://github.com/user-attachments/assets/c46a62f1-bcee-49df-aad4-238e86e1318f">

Is there someone who can help on this?

Thx a lot!!

**Comment by timlie** [comment]
It's 4.x version of BOA

**Comment by omega8cc** [comment]
It’s always a good idea to search the issues for hints. Please try this: https://github.com/omega8cc/boa/issues/1442

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timlie** [comment]
Thanks a lot @omega8cc this fixed it!!
Very very greatfull for your fast reply!
