### ISSUE TITLE
502 Bad Gateway Errors Caused by PHP Pool Reloads on BOA Lite/LTS

### ISSUE THREAD

**Issue by GValFr35** [omega8cc/boa#1824]
For several weeks, I've been experiencing intermittent 502 Bad Gateway errors on BOA LTS.

Every 6 minutes, all PHPxx pools are reloaded, resulting in 502 errors for longer PHP requests (those exceeding the process_control_timeout = 5s).

After some investigation, I discovered that the issue is caused by the xdrago clear.sh script, which downloads and runs the BOA.sh script.

In the BOA.sh script, there’s a line:
`[ ! -e "/var/xdrago/usage.sh" ] && rm -f ${pthLog}/*.ctrl.${tRee}.${_X_SE}.pid`
This line deletes many control PID files if the usage.sh file is missing. 
As a result, PHP-FPM services are forcefully reloaded every time, leading to these 502 errors.

The problem is that in self-hosted environments, the usage.sh file doesn’t exist—it’s deleted by the same script—causing this unwanted behavior.

I applied a temporary fix by creating an immutable usage.sh file.

**Comment by omega8cc** [comment]
Thank you for reporting this bug. The usage.sh script should no longer be deleted. It was previously updated to generate useful reports, but its results are only logged and not sent via email on self-hosted BOA.
