### ISSUE TITLE
Getting nginx warning "Listen... http2 directive is deprecated" message when going to upgrade

### ISSUE THREAD

**Issue by serrato-dan** [omega8cc/boa#1825]
When starting an update on server and I run the initial command
`wget -qO- http://files.aegir.cc/BOA.sh.txt | bash`

getting the following message for a large number of sites:
**nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /data/disk/o1/config/server_master/nginx/vhost.d/EXAMPLE.DOMAIN.org:19**

At the end of the list of warnings, get the following lines:
**nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Reloading (via HUP) Nginx Server...:.**

So, it seems that everything is ok, but when running service nginx status, get the following:
**Nginx Server... found running with processes: 30914 30912 30910 3565 ... (warning).**

Maybe status message is not connected, but I figured I would include since getting all the previous nginx messages.

Do I need to go in and make changes by hand for these numerous site files? Does anyone have any information on what we are experiencing and any advice. 

Thank you so much.
Dan

**Comment by omega8cc** [comment]
These warnings are safe to ignore. To resolve them, you’ll need to run the Verify task on all hosted sites to re-generate their vhosts and align them with the current Nginx version. You can run a mass Verify from the list of sites—there’s no need to click on each one individually.

**Comment by serrato-dan** [comment]
Thank you so much. I ran verify on those sites and it cleared those warnings.
