### ISSUE TITLE
Unable to reach Adminer - nginx 403 Forbidden error message

### ISSUE THREAD

**Issue by FemPriv** [omega8cc/boa#1827]
Hi,

I'm new and can't reach adminer.master.fqdn   or on ipv4 either

nginx gives 403 Forbidden error.

boa info: https://gist.github.com/FemPriv/74da30f7d8bb4d0631d9f57f064dd819

adminer.master.fqdn.vhost is here:  https://gist.github.com/FemPriv/6763341a4523899c82cc0204c67e99f3

/var/log/nginx/error.log :  https://gist.github.com/FemPriv/094a39935169dd00e1135f447176f91a

/var/log/nginx/access.log  :  https://gist.github.com/FemPriv/a1bb7d7f1759d4df1d76382c0e17b2cc

Thank you!

**Comment by omega8cc** [comment]
Try `killall -9 nginx`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Also, make sure you have active SSH session when trying to access Adminer.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FemPriv** [comment]
Thank you - that didn't work and I do have a root ssh connection open.

I received this report by email last night: could it be related?

Sat Oct 26 09:20:01 PM UTC 2024 Nginx BIND
Sat Oct 26 09:20:04 PM UTC 2024 NGX Nginx BIND detected
Sat Oct 26 09:20:04 PM UTC 2024 NGX Nginx BIND incident Nginx service restarted
Sat Oct 26 09:20:04 PM UTC 2024 NGX Nginx BIND incident response completed
Sending Incident Report Email on Sat Oct 26 09:20:04 PM UTC 2024

I also notice this at the bottom of my /root/.barracuda.cnf file (is this relevant? I don't understand this):

_CPU_TASK_RATIO="3.1"
_NGINX_DOS_LINES="1999"
_NGINX_DOS_MODE="2"
_NGINX_DOS_DIV_INC_NR="40"
_NGINX_DOS_INC_MIN="3"
_NGINX_DOS_LOG="VERBOSE"
_NGINX_DOS_IGNORE="doccomment"
_NGINX_DOS_STOP="foobar"

**Comment by FemPriv** [comment]
I ran a barracuda up-lts today, and now I have access to adminer. Thank you.

**Comment by FemPriv** [comment]
I spoke too soon, after the upgrade I saw the adminer login screen - which I hadn't seen for weeks, but when I entered in the root passswd, I got the same Forbidden 403 error page - and that's all I get now, even after rebooting, killall -9 nginx doesn't work either.

**Comment by FemPriv** [comment]
Now I am able to see the login screen and to successfully login!
