### ISSUE TITLE
Drush Status on unlocked Local Drupal 10.3.6 platform returns error

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1828]
composer create-project drupal/recommended-project:10.3.6 drupal_10.3.6

Create a site on that platform  via Octopus browser
Unlock local drupal via Octopus browser

cd /data/disk/o1/static/platforms/drupal_10.3.6/web/sites/example.com
drush status

returns...
Error: Call to undefined method Drush\Drupal\DrupalKernel::addServiceModifier() in Drush\Boot\DrupalBoot10->bootstrap_drupal_configuration() (line 134 of /opt/tools/drush/8/drush/lib/Drush/Boot/DrupalBoot10.php).
Drush command terminated abnormally due to an unrecoverable error. 

After "Verify + Lock Drush", everything works again as expected.

**Comment by aDarkling** [comment]
After reading , I tried the following commands while the platform is unlocked and got the following:

> o1.ftp:[web]$ cd  /data/disk/o1/static/platforms/drupal_10.3.6/web
> o1.ftp:[web]$ vdrush
> The drush command 'vendor/drush/drush/drush.php' could not be found.  Run `drush cache-clear drush` to clear [error]
> the commandfile cache if you have installed new extensions.
> Could not find a Drupal settings.php file at sites/default/settings.php.                                     [error]
> o1.ftp:[web]$ drush10
> The drush command '/data/disk/o1/static/platforms/drupal_10.3.6/vendor/drush/drush/drush' could not be found.[error]
>  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.
> Could not find a Drupal settings.php file at sites/default/settings.php.                                     [error]
> o1.ftp:[web]$ drush11
> The drush command '/data/disk/o1/static/platforms/drupal_10.3.6/vendor/drush/drush/drush' could not be found.[error]
>  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.
> Could not find a Drupal settings.php file at sites/default/settings.php.                                     [error]
> 

However, I verified that '/data/disk/o1/static/platforms/drupal_10.3.6/vendor/drush/drush/drush' **is** there, with permissions 0775 set.  I don't know why it cannot see it.

**Comment by omega8cc** [comment]
@aDarkling You should run `vdrush` in the app root, not web root, as explained in the docs. So in your example `cd /data/disk/o1/static/platforms/drupal_10.3.6`

**Comment by omega8cc** [comment]
Also, please upgrade to BOA-5.5.0 if you have Drush 13 in the codebase. Otherwise it may point to shell script instead of php file (they changed the entry point in Drush 13).

Furthermore, please don't run system drush like `drush10` or `drush11` in the codebase. It's also explained in the docs. You should use it outside of any codebase to avoid conflicts.

**Comment by aDarkling** [comment]
Thanks!!!
