### ISSUE TITLE
Excessive email notifications due to DHCP error checks (_if_fix_dhcp)

### ISSUE THREAD

**Issue by cmastro-ixiam** [omega8cc/boa#1829]
Since the last update of "[system.sh](https://github.com/omega8cc/boa/blob/5.x-dev/aegir/tools/system/monitor/check/system.sh)," we have noticed a significant increase in emails with the subject "Incident Report: DHCP error detected, firewall updated..." and this surge is due to a check being performed on the DHCP.

Upon reviewing the code, we found that the issue arises from the following code block:
https://github.com/omega8cc/boa/blob/a87d19da97cc554ec87dc46bee3b0b4fd550739a/aegir/tools/system/monitor/check/system.sh#L118C1-L118C13

The script checks the last 100 lines of the "daemon.log" or "syslog" every minute. If the DHCP fails for any reason, the script sends emails continuously every minute. In our case, it takes time to accumulate 100 lines in the "daemon.log," which exacerbates the issue.

If you allow me, I would like to suggest replacing the "Failed" reference with an alternative. 
For example, before calling `_incident_email_report` on line [141](https://github.com/omega8cc/boa/blob/a87d19da97cc554ec87dc46bee3b0b4fd550739a/aegir/tools/system/monitor/check/system.sh#L141), you could apply a sed command as follows:
```bash
sed -i '/dhclient.*Failed/s/Failed/-- Error --/g' "${_DHCP_LOG}"
```

Thanks for your attention to this matter.

**Comment by omega8cc** [comment]
Thank you for the bug report. It should be enough to check only the last three lines after we have moved most of noisy logging to separate log files.
