### ISSUE TITLE
Daily Email Notification Issue for "BOA-5.5.0-pro Release" in LTS version

### ISSUE THREAD

**Issue by cmastro-ixiam** [omega8cc/boa#1835]
Hello,

I am writing to report an issue regarding the daily email notifications we receive with the subject line: "New BOA-5.5.0-pro release available, upgrade now!" in LTS version.

We are consistently receiving these emails, and upon investigation, I found that the CURL command for the LTS version is returning the PRO version:

```
curl -L -k -s --max-redirs 10 --retry 3 --retry-delay 15 -A iCab http://files.aegir.cc/versions/lts/boa/aegir/conf/version/barracuda-release.txt
```

Output:
> BOA-5.5.0-pro

It appears that the comparison in the Daily.sh script is failing, which results in the email being sent out:
- https://github.com/omega8cc/boa/blob/5.x-lts/aegir/tools/system/daily.sh#L3164

Maybe you can update the version in the file retrieved by the CURL command or modify the script to ignore the suffix in the "_VERSIONS_TEST" and "_X_VERSION" variables during the comparison.

Thanks!

**Comment by omega8cc** [comment]
Fixed. Thanks for the report.
