### ISSUE TITLE
Query re failed install

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1836]
Hello, I have an install which seemed to work half-way except that there is no working master instance, and no octopus instance was installed. The logs show nginx failing to restart 3 or 4 times. This was on a devuan daedalus prepared.

There is no /data/u directory.  and there was no /data/disk directory, but after a day and a few attempted barracuda up-lts there is now a /data/disk direectory with a few sql backups inside!

I have tried reinstalling all, but it never gets to the "hostmaster" part, and ends saying that percopna can't be restarted - and to start percona and try again, which doesn't work:
BOA [10:05:40] ==> PROC: _aegir_master_install_upgrade

BOA [10:05:40] ==> PROC: _if_to_do_fix
BOA [10:05:40] ==> ALRT! Percona server not running properly!
BOA [10:05:40] ==> EXIT: We can't proceed and will exit now
BOA [10:05:40] ==> HINT: Please check /var/backups/barracuda-upgrade-241126-092208.log for more information,
BOA [10:05:40] ==> HINT: (re)start Percona server, then run the installer again
BOA [10:05:40] ==> Bye

BARRACUDA upgrade completed. 
"
I see that there is no /etc/mysql directory, rather there is an /etc/mysql_pre directory with percona stuff inside - is this normal?

I also tried installing an octopus instance, but it won't do it, telling me to "Please install complete boa system before trying to install additional AEgir / Octopus instances" 

The barracuda install log stops with:
mode of '/etc/init.d/csf' retained as 0755 (rwxr-xr-x)
'/etc/csf/csfwebmin.tgz' -> '/usr/local/csf/csfwebmin.tgz'

Installation Completed

Restarting OpenBSD Secure Shell server: sshd.
Stopping enhanced syslogd: rsyslogd.
Starting enhanced syslogd: rsyslogd.

and there is even an install.log giving this:
Congratulations, Aegir has now been installed.

You should now log in to the Aegir frontend by opening the following link in your web browser: (but the link doesn't resolve).

I can reach adminer.master.FQDN great, and redis-server php83-fpm, nginx, percona csf, etc - are all running OK

In the /root/.octopus.exit.exceptions.log is filled with "REASON bookworm on+ date...."
There is also a /root/.boa.exit.exceptions.log with three lines of the same "Reason bookworm on + date

running "lsb_release -a" from the command line gives daedalus 5 correctly

So, my question is:

1) Is there a command to reinstall the whole thing, or just the AEgir master instance like barracuda in-hostmaster" or something?

or 2) without rebuilding the whole server is there a way to wipe the incomplete install and try again ?

Thanks,

Ed

**Comment by EdNett** [comment]
I had originally tired to do the "autoinit" directly from a fresh install of debian bullseye, but it never worked - that is, I could never ssh in again, so I tried, above, to migrate manually, first from bullseye to bookworm, and then from bookworm to dqaedalus. After following the upgrade/migrate instuctions meticulously, I still had lsb_release -a show debian and so I had to install a specific version of base-files 12.7 for devuan 5 which then gave a return of devuan. Now I have reinstalled bullseye again, and once again "autoinit" never allows me to ssh in again.

Nowhere in the docs does it say if we have to do the following procedure before running "autoinit":
(Would you please comment on whether or not these steps are still necessary to prepare a vps for boa, please?):

nano /etc/default/grub  
GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
sudo grub-mkconfig -o /boot/grub/grub.cfg
reboot
dmesg | grep -i eth  # to check
then:
nano /etc/network/interfaces   or nano /etc/network/interfaces.d/50-cloud-init  and modify to eth0
check after rebooting with "ip a"

Best regards,
Ed

**Comment by ColdSunERA** [comment]
Same issue with using autoinit. The server stops accepting network connections during the process

Was attempting autoinit on Debian bookworm.

**Comment by EdNett** [comment]
Hello, I reinstalled the vps, and this time left it at bookworm, set the grub and neworking as described, and ran autoinit and once again still couldn't ssh in. This was just after the [Serial 550ltsT02](https://github.com/omega8cc/boa/commit/0877d1e9b82e476945b388c7f99fb04242f69056)  sync on lts.

Best,

Ed

**Comment by omega8cc** [comment]
Hello,  

We’ve recently introduced a new branches structure to prevent such issues from recurring.  

For more details, you can refer to:  
https://github.com/omega8cc/boa/blob/5.x-dev/docs/BRANCHES.md  

We sincerely apologize for any inconvenience or disruption this may have caused.

**Comment by EdNett** [comment]
Hello,

I don't know how to test your fix, since I don't plan on re-installing BOA unless I have to. I have since successfully reinstalled BOA - although there are many errors currently, and I don't know what the current state of an install is. Shall I leave it open ? Or close?

**Comment by omega8cc** [comment]
I'm closing this because BOA install is stable again in all our tests on three Debian versions.
