### ISSUE TITLE
Drush no longer works at all to update DB - I can ONLY do it in the site admin area.

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1839]
Hello,

For some time now I have been trying to follow this guide for updating a sites db (including the post update procedure which I believe handles entity updates) using drush from the o1 command line, and it doesn't work - it throws error after error. UNfortunately, cd ing to the directory where the sites' index.php file resides (i.e. /static/d1038/web/sites/example.com) adn running drush updb or drush10 updb or drush 11 updb (for a drupal core 10.3.8 sites whose local drush is 13.3.x usually) no longer works either. So, I can now ONLY updb by logging into the site and putting the site in maintainence mode and going through the GUI procedure! Am I alone in this?

This is the guide I have been following:

Steps to Use Site-Local Drush:
Run the 'Unlock Local Drush' task on the site's Platform in Ægir.
Find the correct Drush @site-alias with the drush11 aliases command.
Switch to the Platform app root where vendor exists using cd.
Run vdrush --version or install it with composer require drush/drush.
Use vdrush @site-alias updbst, vdrush @site-alias updb, etc.
Run the 'Platform Verify' task to restore compatibility with Drush 8.

BOA info more is here: https://gist.github.com/EdNett/9578160fa801103b7be1781dea760b07

Best,

Ed

**Comment by omega8cc** [comment]
Hello,  

Could you please run the following command and let us know if it resolves the issue?  

```  
wget -qO- http://files.aegir.cc/BOA.sh.txt | bash  
```  

We’ve recently introduced a new branches structure to prevent such issues from recurring.  

For more details, you can refer to:  
https://github.com/omega8cc/boa/blob/5.x-dev/docs/BRANCHES.md  

We sincerely apologize for any inconvenience or disruption this may have caused.

**Comment by EdNett** [comment]
Hello.

I ran it and here is what printed to the screen:  https://gist.github.com/EdNett/0519c6aec0563e93459f49c74d2a6168

And I can confirm that I can once again use drush to updb, etc. a site. Thank you.



I guess I will try to barracuda up-lts now.

**Comment by EdNett** [comment]
at the end of the third barracuda up-lts the vps is back to Daedalus, but there are no files in /var/xdrago/ - as the errors, below, show. They are in /var/xdrago/xdrago_wait. I guess I'll mv the daily.sh etc. scripts from within that directory to be in /var/xdrago - and I'll move the other directories back, but won't overwrite any files currently residing in /var/xdrago/  Please let me know if this is not the right way to fix this.

*** Is this from the failed migration that didn't work properly - this vps was the target ? or is this a problem with the current up-to-daedalus ? I think it is the latter, because I manually ran /var/xdrago/daily.sh after the partially successful migration, so the script must have been there then. ***

BOA [08:40:38] ==> INFO: Reloading Redis, PHP-FPM and Nginx...
BOA [08:40:52] ==> INFO: Running Percona system tables (2) upgrade...
BOA [08:41:36] ==> INFO: Percona diff0 empty
BOA [08:41:36] ==> INFO: Percona Uptime: 1 hour 16 min 26 sec
BOA [08:41:37] ==> PROC: _apticron_update
sed: can't read /var/xdrago/checksql.pl: No such file or directory
sed: can't read /var/xdrago/daily.sh: No such file or directory
sed: can't read /var/xdrago/usage.sh: No such file or directory
sed: can't read /var/xdrago/monitor/check/segfault_alert.pl: No such file or directory
sed: can't read /var/xdrago/monitor/check/escapecheck.pl: No such file or directory
BOA [08:41:37] ==> PROC: _barracuda_log_update
BOA [08:41:37] ==> INFO: New entry added to /var/log/barracuda_log.txt
BOA [08:41:37] ==> PROC: _complete
BOA [08:41:37] ==> PROC: _fix_lfd_whitelist
BOA [08:41:37] ==> PROC: _fix_lfd_uidignore
BOA [08:41:37] ==> PROC: _fix_cnf_postfix
BOA [08:41:37] ==> PROC: _re_set_default_php_cli 8.1
BOA [08:41:37] ==> PROC: _switch_php_cli 81
BOA [08:41:37] ==> PROC: _composer_install_upgrade
BOA [08:41:39] ==> INFO: Installed Composer 2.8.3, update required
BOA [08:41:39] ==> INFO: Installed Composer 2.8.2
BOA [08:41:40] ==> PROC: _symlink_to_dash
BOA [08:41:40] ==> PROC: _switch_to_dash
BOA [08:42:03] ==> PROC: _strict_bin_permissions
BOA [08:42:20] ==> PROC: _finale
BOA [08:42:20] ==> CARD: Now charging your credit card for this magic show...
BOA [08:42:23] ==> CARD: It will take a moment to process your payment...
BOA [08:42:29] ==> JOKE: Just kidding !!! Enjoy your Aegir Hosting System :)

BOA [08:42:33] ==> Final post-upgrade cleaning, one moment...
BOA [08:42:33] ==> PROC: _barracuda_cnf_cleanup
BOA [08:42:36] ==> PROC: _php_deprecated_cleanup
BOA [08:42:36] ==> PROC: _php_single_initd_cleanup
BOA [08:42:37] ==> BYE!

**Comment by EdNett** [comment]
octopus up-lts all force failed miserably. I'll try to post a gist of the errors.

gist of errors for o2 is here: https://gist.github.com/EdNett/cb52c4502af623673d2d95e0664edb7c


gist of errors for o1 (which was target of unsuccessfully-completed-migrate platform) is here:
https://gist.github.com/EdNett/6d32dd2fa03e28f5dbe7d9557f4b8a93

The octopus up-lts all force left both Octopus GUI's down - don't resolve in the browser and nginx is running, as are the necessay phpxx-fpm's, and mysql and unbound.

current boa info more is here: https://gist.github.com/EdNett/dcc88d7fb804b732aa0cf5ba54578e31  (can't scroll up the screen to see more

current boa info (different!) is here: https://gist.github.com/EdNett/3c404a9581b7899c620e9735a09f20c1

I will try starting redis: error:  root@server1:~# service redis-server start
Starting redis-server: touch: cannot touch '/run/redis/redis.pid': No such file or directory
root@server1:~# service redis-server restart
Stopping redis-server: redis-server.
Starting redis-server: touch: cannot touch '/run/redis/redis.pid': No such file or directory

I will try re-running barracuda up-lts system to see if I can't get redis-server up

**Comment by EdNett** [comment]
So now all of the sites on both octopus platforms are down - total loss of business! Redis won't start.

redis-server log is here: https://gist.github.com/EdNett/6bf9a555d25da0ca9d98f5daf87673b3

re-running barracuda up-lts did get redis-server started again, and teh sites are coming back up, but it gives this error:

BOA [10:28:43] ==> DNLD: Attempt 1 of 10: Downloading revision_deletion-7.x-1.3.tar.gz...
BOA [10:28:44] ==> DNLD: Attempt 1 of 10: Downloading strongarm-7.x-2.0.tar.gz...
BOA [10:28:44] ==> DNLD: Attempt 1 of 10: Downloading userprotect-7.x-1.3.tar.gz...
BOA [10:28:50] ==> INFO: Testing previous install...
BOA [10:28:50] ==> INFO: Test OK, we can proceed with Hostmaster upgrade
BOA [10:28:50] ==> INFO: Moving old directories
BOA [10:28:50] ==> INFO: Downloading drush 8.4.12.9...
BOA [10:28:50] ==> DNLD: Attempt 1 of 10: Downloading drush-8.4.12.9.tar.gz...
BOA [10:28:59] ==> PROC: _php_cli_local_ini_update
BOA [10:28:59] ==> INFO: Installing Aegir Provision backend...
BOA [10:28:59] ==> INFO: Downloading Drush and Provision extensions...
BOA [10:29:08] ==> DNLD: Attempt 1 of 10: Downloading clean_missing_modules.tar.gz...
BOA [10:29:08] ==> DNLD: Attempt 1 of 10: Downloading utf8mb4_convert-7.x-1.3.tar.gz...
Drush command terminated abnormally due to an unrecoverable      [error]
error.
Error: Uncaught Error: Call to undefined function
provision_autoload_register_prefix() in
/var/aegir/host_master/009/profiles/hostmaster/modules/aegir/aegir_objects/drush/aegir_objects.drush.inc:15
Stack trace:
#0
/var/aegir/host_master/009/profiles/hostmaster/modules/aegir/aegir_objects/drush/aegir_objects.drush.inc(23):
aegir_objects_register_autoload()
#1 /var/aegir/drush/includes/command.inc(226):
aegir_objects_drush_init()
#2 /var/aegir/drush/includes/command.inc(199): drush_command()
#3 /var/aegir/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch()
#4 /var/aegir/drush/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#5 /var/aegir/drush/drush.php(12): drush_main()
#6 {main}
  thrown in
/var/aegir/host_master/009/profiles/hostmaster/modules/aegir/aegir_objects/drush/aegir_objects.drush.inc,
line 15
BOA [10:29:08] ==> FATAL ERROR: Drush is broken (/opt/php81/bin/php /var/aegir/drush/drush.php help failed)
BOA [10:29:08] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
BOA [10:29:08] ==> FATAL ERROR: AegirUpgrade installer failed
BOA [10:29:08] ==> FATAL ERROR: Aborting Barracuda installer NOW!


I will try re-running with up-lts system only now

**Comment by EdNett** [comment]
The last failed barracuda up-lts which got redis-server and jetty9 restarted, did add the daily.sh files, etc. to /var/xdrago/ and it left /var/xdrago/xdrago_wait/ in place with all of the old logs and subdirectories, etc.. There is one subdirectory "back" which was not included in the /var/xdrago/  adn which does exist in /var/xdrago/xdrago_wait/

**Comment by EdNett** [comment]
Leaving this open because of errors in both barracuda up-lts and octopus up-lts -

OR

do you want me to file separate issues for those errors?

Currently boa info shows:

  _XSE Key Services Uptime Report

  _XSE Running services:

  _XSE sshd is running for 28 minutes.
  _XSE crond is running for 5 minutes.
  _XSE nginx is running for 38 minutes.
  _XSE php74-fpm is running for 5 minutes.
  _XSE php81-fpm is running for 5 minutes.
  _XSE php82-fpm is running for 5 minutes.
  _XSE php83-fpm is running for 5 minutes.
  _XSE mysql is running for 38 minutes.
  _XSE redis is running for 11 minutes.
  _XSE solr7 is running for 38 minutes.
  _XSE jetty9 is running for 14 minutes.
  _XSE lfd is running for 38 minutes.
  _XSE unbound is running for 28 minutes.
  _XSE vnstat is running for 38 minutes.

  _XSE Not running services:

  _XSE pure-ftpd is not running (PID file not found).
  _XSE rsyslogd is not running (PID file not found).

I may not really need pure-ftp - but I have to think about it...

**Comment by omega8cc** [comment]
Hello,  

Migrating any live site to a server with a visibly broken system was not advisable. 

Resolving this at this stage requires an expert level of Aegir knowledge, and we strongly recommend against attempting it.  

Instead, we suggest the following:  

1. Bring the sites back online on the old server by running the sites Verify tasks.  
2. Create a new target server from scratch and ensure it’s fully functional before proceeding with the migration.  

For the best results, we recommend testing the migration procedure on a test Octopus instance with dummy sites before attempting to migrate live sites. This helps ensure a smoother and safer transition.  

Please let us know if you need any assistance with this process.
