### ISSUE TITLE
Request adding INCUS to Vitualization Types Supported

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1841]
Hello,

I know you are very busy, but this is just a request to add INCUS to the vitualization types BOA supports. I am learning how to virtualize a dedicated, and was going to install LXC, but it is clear that LXC is going private and will be a paid service soon, and INCUS is the LXD/LXC replacement for Debian bookworm and Trixie going forward. It is available in the Bookworm backports. It has a great UI and seems to work very well so far. I installed on bookworm and during the install process chose an incus managed bridge for networkign which is "eth0".

INCUS allows creation of both containers and VMs, and containers can be devuan, but not VM's - so I don't know if a container is OK for a BOA install. I will test. In the Devuan Daedalus container, there is no /etc/default/grub file, but there is eth0 in /etc/network/interfaces.  

I wonder if this issue prevents incus-agent from being used on VMs created without systemd ?: https://discuss.linuxcontainers.org/t/incus-install-ans-sysv/21960/2

and

https://dev1galaxy.org/viewtopic.php?id=6517

This work looks like it may solve the problem, but I'm no expert on this:
https://github.com/MoltenArmor/incus-init-scripts/blob/main/etc/init.d/incus-containers

Best,

Ed

**Comment by omega8cc** [comment]
If it depends on systemd in one way or another, it won't be supported, because we are not going to use/support systemd. It must support classic Debian sysvinit.

**Comment by omega8cc** [comment]
To clarify, BOA requires a full OS/system, not just some limited container to operate.

We don't plan to work on this as we don't see any use of it, but feel free to test and report back.

**Comment by EdNett** [comment]
OK, thank you.
