### ISSUE TITLE
Up-lts fails immediately with log stating a valid license is needed to up-dev!

### ISSUE THREAD

**Issue by FemPriv** [omega8cc/boa#1842]
Up-lts fails immediately with log stating a valid license is needed to up-dev!

I tried to run from bookworm to daedalus - since the vps seems to have reverted to bookworm - I recently reinstalled BOA on a fresh bookworm.

log is here: https://gist.github.com/FemPriv/0729940ddea55bd44f07fd0181524821

**Comment by omega8cc** [comment]
Hello,  

Could you please run the following command and let us know if it resolves the issue?  

```  
wget -qO- http://files.aegir.cc/BOA.sh.txt | bash  
```  

We’ve recently introduced a new branches structure to prevent such issues from recurring.  

For more details, you can refer to:  
https://github.com/omega8cc/boa/blob/5.x-dev/docs/BRANCHES.md  

We sincerely apologize for any inconvenience or disruption this may have caused.

**Comment by FemPriv** [comment]
Hello,

OK, I ran that command, ( wget -qO- http://files.aegir.cc/BOA.sh.txt | bash  ) and it didn't seem to do anything. There were a few lines of text which indicated that the server was ready for boa install ? Sorry, I didn't copy them and can't see them any longer.

Then I ran "barracuda up-lts log" and this was echoed to the screen:

BOA [04:44:04] ==> Skynet Agent v.BOA-5.5.0-lts on Hetzner welcomes you aboard!

BOA [04:44:07] ==> MODE: UPGRADE

BOA [04:44:10] ==> PROC: _symlink_to_dash
BOA [04:44:10] ==> PROC: _switch_to_dash
BOA [04:44:30] ==> PROC: _check_exception_mycnf
BOA [04:44:30] ==> PROC: _virt_detection
BOA [04:44:30] ==> VIRT: This system is supported: Linux KVM guest

BOA [04:44:30] ==> HINT: Command to run in another terminal window to watch details
BOA [04:44:30] ==> CMND: tail -f /var/backups/barracuda-upgrade-241205-044330.log
BOA [04:44:30] ==> PROC: _os_detection

BOA [04:44:30] ==> Aegir on server1.fqdn.com Debian/bookworm x86_64 PHP 8.3

BOA [04:44:30] ==> PROC: _os_detection_minimal
BOA [04:44:30] ==> PROC: _if_rebuild_src_on_major_os_upgrade
BOA [04:44:30] ==> PROC: _if_long_generate_on_major_os_upgrade
BOA [04:44:30] ==> PROC: _if_php_idle_on_off
BOA [04:44:35] ==> PROC: _php_if_versions_cleanup_cnf
BOA [04:44:35] ==> INFO: _OPENSSL_NEW_VRN is
BOA [04:44:35] ==> INFO: _local_PHP_MULTI_INSTALL is 8.3
BOA [04:44:35] ==> PROC: _php_multi_uniq
BOA [04:44:35] ==> PROC: _php_not_used_disable
BOA [04:44:37] ==> INFO: /etc/init.d/php74-fpm moved to /var/backups/initd-php74-fpm
BOA [04:44:37] ==> INFO: /opt/php74 moved to /var/backups/off-php74-arch
BOA [04:44:39] ==> INFO: /etc/init.d/php81-fpm moved to /var/backups/initd-php81-fpm
BOA [04:44:39] ==> INFO: /opt/php81 moved to /var/backups/off-php81-arch
BOA [04:44:41] ==> INFO: /etc/init.d/php82-fpm moved to /var/backups/initd-php82-fpm
BOA [04:44:41] ==> INFO: /opt/php82 moved to /var/backups/off-php82-arch

BOA [04:44:41] ==> Bye

and the details were:

root@server1:~# tail -f /var/backups/barracuda-upgrade-241205-044330.log
Terminating php74-fpm.... done
Terminating php81-fpm.... done
Terminating php82-fpm.... done

The original screen showed this:

GRUB: NEVER USE LIVE MODE IF YOU ARE NOT SURE IF YOU NEED IT

You are in a screen session now

Preparing the upgrade in silent mode...

NOTE: There will be no progress displayed in the console
but you will receive an email once the upgrade is complete

You could watch the progress in another window with command:
  tail -f /var/backups/reports/up/barracuda/241205/barracuda-up-241205-044330.log
or wait until you will see the line: BARRACUDA upgrade completed

Waiting 5 seconds...
Starting the upgrade in silent mode now...

ALERT: Failed (msg) Barracuda upgrade on server1.fqdn sent to info@fqdn

BARRACUDA upgrade completed
Bye

**Comment by omega8cc** [comment]
If this was a new server, we recommend to re-install it from scratch.

If you prefer to debug this further, run only `system` upgrade with `barracuda up-lts system` and check your email for results or examine logs in `/var/backups/reports`

**Comment by FemPriv** [comment]
Hi,

I ran a few barracuda up-lts system, then barracuda up-lts, then octopus up-lts and everything is workign fine now.
Thank you!
