### ISSUE TITLE
I tried to download the om8 drupal7 project and microsoft anti-virus said it contained a virus - dropal.org d7 downloads OK - just thought I'd let you know.

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1845]
I tried to download the om8 drupal7 project and microsoft anti-virus said it contained a virus - dropal.org d7 downloads OK - just thought I'd let you know.

**Comment by omega8cc** [comment]
It's obviously a false alarm. Just check the codebase yourself.
