### ISSUE TITLE
Fatal Error: _Easy_Hostname not defined on fresh installs

### ISSUE THREAD

**Issue by ColdSunERA** [omega8cc/boa#1846]
Attempted multiple fresh installs including from bullseye -> Chimera -> Daedalus and Bookworm to Daedalus via autoinits and then doing the boa execution. Install appears to go through and an email is sent. However the master.fqdn and o1.fqdn sites do not work. Some expected files such as those that would populate /data/disk/ do not exist.
<code>
BOA [16:11:07] ==> Skynet Agent v.BOA-5.5.0-lts on Xen welcomes you aboard!

BOA [16:11:10] ==> MODE: FORCED INIT
BOA [16:11:11] ==> FATAL ERROR: You must define also _EASY_HOSTNAME

Ready for BOA Vanilla System on Devuan/daedalus x86_64
  HOST Xen
  VPS Xen guest fully virtualized (HVM)
  NGX 1.27.3
  PHP 8.3.14
  DBV 5.7.44
  RDS 7.0.15
  SHD 9.9p1
  SSH OpenSSH_9.9p1, OpenSSL 3.3.2 3 Sep 2024
  LSH 0.10
  PY3 3.11.2
  SSL 3.3.2
  CRL 8.10.1
  CRL_From_Packages NO
  CRL_Local_Bin YES
  _NRC command

  _XSY System Uptime/Load/Kernel/CPU/Memory/Disk Report

  _XSU System Uptime: up 1 hour, 28 minutes
  _XSL System Load: 1.90, 1.73, 2.15
  _XSK Current Kernel Version: 6.1.0-28-amd64
  _XSG GRUB: GRUB_CMDLINE_LINUX=""
  _CPU Number: 4
  _RAM Total: 3.81 GB
  _RAM Usage: 19%
  _DSK Usage for relevant partitions:
  _DSK /dev/xvda2: 3% used (/)
  _DSK /dev/xvda1: 20% used (/boot)

  _XSE Key Services Uptime Report

  _XSE Running services:

  _XSE sshd is running for 9 hours.
  _XSE crond is running for 9 hours.
  _XSE nginx is running for 1 hours.
  _XSE php74-fpm is running for 4 minutes.
  _XSE php81-fpm is running for 4 minutes.
  _XSE php82-fpm is running for 4 minutes.
  _XSE php83-fpm is running for 4 minutes.
  _XSE mysql is running for 1 hours.
  _XSE redis is running for 5 minutes.
  _XSE rsyslogd is running for 1 hours.
  _XSE unbound is running for 1 hours.

  _XSE Not running services:

  _XSE solr7 is not running (PID file not found).
  _XSE jetty9 is not running (PID file not found).
  _XSE pure-ftpd is not running (PID file not found).
  _XSE lfd is not running (PID file not found).
  _XSE vnstat is not running (PID file not found).
</code>

The barracuda and octopus logs do not have any notable errors.
Both the master aegis website does not load, more does the o1 octopus install. 
It should be noted that /data/disk/ does to exist like I would expect.

 BOA [16:11:07] ==> Skynet Agent v.BOA-5.5.0-lts on Xen welcomes you aboard!

BOA [16:11:10] ==> MODE: FORCED INIT
BOA [16:11:11] ==> FATAL ERROR: You must define also _EASY_HOSTNAME

Ready for BOA Vanilla System on Devuan/daedalus x86_64
  HOST Xen
  VPS Xen guest fully virtualized (HVM)
  NGX 1.27.3
  PHP 8.3.14
  DBV 5.7.44
  RDS 7.0.15
  SHD 9.9p1
  SSH OpenSSH_9.9p1, OpenSSL 3.3.2 3 Sep 2024
  LSH 0.10
  PY3 3.11.2
  SSL 3.3.2
  CRL 8.10.1
  CRL_From_Packages NO
  CRL_Local_Bin YES
  _NRC command

  _XSY System Uptime/Load/Kernel/CPU/Memory/Disk Report

  _XSU System Uptime: up 1 hour, 28 minutes
  _XSL System Load: 1.90, 1.73, 2.15
  _XSK Current Kernel Version: 6.1.0-28-amd64
  _XSG GRUB: GRUB_CMDLINE_LINUX=""
  _CPU Number: 4
  _RAM Total: 3.81 GB
  _RAM Usage: 19%
  _DSK Usage for relevant partitions:
  _DSK /dev/xvda2: 3% used (/)
  _DSK /dev/xvda1: 20% used (/boot)

  _XSE Key Services Uptime Report

  _XSE Running services:

  _XSE sshd is running for 9 hours.
  _XSE crond is running for 9 hours.
  _XSE nginx is running for 1 hours.
  _XSE php74-fpm is running for 4 minutes.
  _XSE php81-fpm is running for 4 minutes.
  _XSE php82-fpm is running for 4 minutes.
  _XSE php83-fpm is running for 4 minutes.
  _XSE mysql is running for 1 hours.
  _XSE redis is running for 5 minutes.
  _XSE rsyslogd is running for 1 hours.
  _XSE unbound is running for 1 hours.

  _XSE Not running services:

  _XSE solr7 is not running (PID file not found).
  _XSE jetty9 is not running (PID file not found).
  _XSE pure-ftpd is not running (PID file not found).
  _XSE lfd is not running (PID file not found).
  _XSE vnstat is not running (PID file not found).

The barracuda and Octopus logs do not mention any errors.
The Nginx log states. 
<code>2024/12/06 16:09:01 [emerg] 11955#0: open() "/etc/nginx/conf.d/aegir.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:23</code>

**Comment by ColdSunERA** [comment]
Another attempt resulted in an error while trying to install the aegis master server, but stated it failed and to check the /var/aegir/ log..... but /var/aegir (and therefore its contents) do not exist.

**Comment by ColdSunERA** [comment]
Latest commits address the hostname issue. Marking this as fixed.

**Comment by omega8cc** [comment]
If any commit fixes the problem, please reference it to provide helpful feedback. While we could reproduce the problem in LTS, most of the commits are happening in DEV first and they are often reverted during testing.

**Comment by aDarkling** [comment]
This problem still occurs on fresh installs today, so the fix must've been reverted somewhere.
