### ISSUE TITLE
Platforms are not installing at all 5.5.0-lts

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1849]
Hello,

I see that you have changed paths for many things and that the "src" directory is no longer being used.

I also notice that platforms are not being installed, even though a default octopus up-lts indicates that some are being installed (ezcreator, drupal, etc) and even when specified in the .o1.octopus.cnf file.

The terminal echoes this (but nothing can be found on the server):

BOA [12:52:07] ==> DEBUG: _d_dist_platform_install
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install url is 'https://drupal.org/project/commerce_kickstart'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install version is '3.0.0'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install description is 'Commerce Kickstart 3.0.0 10.3.6 [104]'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install php_version is '8.3'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install profile_name is 'commerce_kickstart'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install web_dir is '/web'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install core_version is '10.3.6'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install profile_path is 'contrib/'
BOA [12:52:07] ==> DEBUG: _d_dist_platform_install dist is 'CK3'

Additionally, specifying a few platforms in the .o1.octopus.cnf file seems to have all of them indicated as downloaded (like the above), but in reality - none are downloaded or installed. Must be a path problem.

boa info is here:  https://gist.github.com/EdNett/561d2335a6d833493761a29d9b77831b

**Comment by omega8cc** [comment]
BOA doesn't install any platforms by default for a very long time (years), please check the note at the bottom of the section: https://github.com/omega8cc/boa/blob/5.x-dev/docs/INSTALL.md#installing-boa-system-on-a-public-servervps

The DEBUG lines you see only indicate the code lines being executed, not platforms being installed.

**Comment by EdNett** [comment]
My fault. Sorry; I will re-read all the docs to familiarize myself with the changes made.
