### ISSUE TITLE
octopus: command not found

### ISSUE THREAD

**Issue by radimklaska** [omega8cc/boa#303]
I've got following error during latest upgrade:

```
$ octopus up-stable all
-bash: octopus: command not found
```

Running `$ bash BOA.sh.txt` once again after `$ barracuda up-stable` fixed the path to octopus script.

**Comment by BrianGilbert** [comment]
as the link to changeling wasn't hashed you need to execute the following:

```
export PATH=$PATH:/opt/local/bin

**Comment by omega8cc** [comment]
You should always follow the docs: https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt

`$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`
