### ISSUE TITLE
Drush Make Local

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#332]
is it possible to install Drush Make Local for octopus users?
https://www.drupal.org/project/make_local

would be very useful for development instances, when drush make local install profiles very often without need to push them to git

**Comment by omega8cc** [comment]
We are moving to Drush 7 in the next BOA release, so not sure if we could still consider adding this extension. If you could test this on BOA HEAD to make sure that it still works, it would be great.

**Comment by ixiam** [comment]
Is it possible to re-enable drush make_local module for drush7?

I cannot make it work in drush8 a drush make with local profile.
I've tried all the combinations using file:// protocol as specified in [docs](http://www.drush.org/en/master/make/#project-download-options) (with type: url, file, copy) , but it's not working.

For us, in dev environments, makes our life easier to have this feature on, so we can deploy & test platforms much more faster without commiting every change.

tx

**Comment by omega8cc** [comment]
All you need is to use absolute path in `[url]` -- without the `file://` prefix. It works with Drush 8, and is used in BOA, too: https://github.com/omega8cc/hostmaster/blob/feature/3.0.x-profile/hostmaster.make

**Comment by omega8cc** [comment]
@ixiam That said, if you are using vanilla Drush 8, you may need this patch we have in BOA: https://github.com/omega8cc/drush/commit/56f0568cd37d3f14e2b2fe8db468be366d7de35f

**Comment by ixiam** [comment]
:) super! great patch!
Thanks for the tip, it was driving me crazy..
cheers
