### ISSUE TITLE
Octopus SFTP user (client) ownership

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#337]
Wanted clarification how octopus handles clients and its FTP ownership. I'm using BOA 2.2.7. Haven't found answer in documentation nor in previous issues, so hopefully it's not a duplicate (which would be annoying).

So, my situation - created new client node, added it as client of a site, verified that site.

After that, barracuda created SFTP user with pass located in /home/o1.ftp/users/o1.username. Login with these credentials went smooth. But what I experienced as a problem, when I tried to modify any file - it just had o1:users ownership and o1.username doesn't have ownership to modify or create any file/folder.

My question is, do we have to manually add ownership to client SFTP username of certain allowed to edit folders with command like inside site "chown -R o1.username:users themes/*", or is it has to be auto managed fully by barracuda/octopus?

**Comment by omega8cc** [comment]
Just a note that `_PERMISSIONS_FIX=YES` is now the default value again.
