### ISSUE TITLE
[csf] whitelist Cloudflare and New Relic IPs

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#346]
CloudFlare's IPs - https://www.cloudflare.com/ips

New Relic IPs - https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/networks

**Comment by macmladen** [comment]
Is there a way to add names, like dynamic names (my home is on dynamic IP pool)?

So I understand it is desirable (and future proof) way to include IPs in `/root/.local.IP.list` ?

What about custom `csf` setting, how could we add our stuff that can **survive** integrity checking and upgrade?

**Comment by omega8cc** [comment]
You can add only IP numbers, not names, but if you have dynamic range, you may want to whitelist entire range, although it is not recommended. No, not via `/root/.local.IP.list`, via csf command, as explained in my comment above.

**Comment by omega8cc** [comment]
> What about custom csf setting, how could we add our stuff that can survive integrity checking and upgrade?

It was discussed in detail in https://github.com/omega8cc/boa/issues/719

**Comment by macmladen** [comment]
Precisely. Thanks.
