### ISSUE TITLE
Consider the possibility to share contrib code between platforms?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#363]
I was thinking that almost all of the contrib modules I have in my platforms are at the same version for the different platform environments (-dev, -stage, -prod). Considering this statement from the BOA readme: *"Sharing the code between instances is of critical importance, because it allows you to dramatically lower RAM and CPU usage, because most of the actively used code is opcode cached"*, I wonder:

Does it make sense to try to apply the same principle to contrib code shared between multiple platforms (within an Octopus instance)?

I imagine we could specify a contrib folder for each platform via ini file, that would then be symlinked. You would then add module updates to the sites/all/modules of one platform, overriding the shared contrib versions, while the majority of the contrib modules is still shared via the symlinked folder.

This could make keeping track of your module versions per platform slightly harder. Maybe it would make the system too complex? On the other hand, contrib modules usually make up the largest part of the codebase and are now duplicated for each platform, so perhaps the benefits for the opcode caching could be worth it?

**Comment by macmladen** [comment]
I am doing this myself as I have some common libraries/modules/themes that I use for all my sites so I want to have them in all platforms (meaning dev/prod/stage).

My way of doing that is that I put them in the same directory as the platform (like `distro/013/`) because they get updated with platform update and I put them in `d6_contrib` and `d7_contrib`. In each I have all three directories so it looks like:

    d6_contrib
      libraries
      modules
      themes
    d7_contrib
      libraries
      modules
      themes

And then I _symlink_ them to `sites/all` in each of corresponding dev / prod / stage platforms. I've made a script that makes it easy for me to update modules and make symlinks.

**Comment by macmladen** [comment]
But I find this suggestion as the better idea to handle common contributed code handling.

I'd suggest an easy approach that may be suitable: make two contrib folders like `6_contrib` and `7_contrib` in distro by default, put inside libraries / modules / themes folder structure and symlink them each platform, like

    distro
      013
        6_contrib
          libraries
          modules
          themes
        7_contrib
          libraries
          modules
          themes
        ...
        drupal-7.34.1-dev/
          sites
            all
              libraries
                7_contrib -> 7_contrib/libraries
              modules
                7_contrib -> 7_contrib/modules
              themes
                7_contrib -> 7_contrib/themes

and like that in `prod` and `stage` as well, so any module that is added appears on every platform.

The downside it that every operation that reads all module tree will have to read all of them and that could lead to performance issues. My sites are low traffic so I do not observe issues but I think it may affect those with higher loads.

**Comment by omega8cc** [comment]
My conclusion is that adding more complex layers of contrib code shared between platforms may negate most of the benefits of platforms based code managed, not to mention it would never work with Git based workflow. It is a good thing to experiment and try to push things further, but In this particular case the direction looks like a dead end to me.

**Comment by macmladen** [comment]
Probably you are right and although I've done this, that doesn't mean it should be done. Currently it works for me but as said, I'm not sure how would it perform under heavier load and also brings much more problems and questions than it solves.

Still I hope this discussion will be helpful to someone.
