### ISSUE TITLE
forbidden char on sql-sync

### ISSUE THREAD

**Issue by MuschPusch** [omega8cc/boa#373]
my aliases:

```php
$aliases['remote-site'] = array(
  'uri' => 'someuri.nl',
  'root' => '/data/disk/o5/static/site/public',
  'db_type' => 'mysql',
  'db_host' => 'localhost',
  'db_passwd' => '****',
  'db_name' => 'name',
  'db_user' => 'user',
  'remote-host' => 'superduperhosting.host8.biz',
  'remote-user' => 'o5.ftp',
  'path-aliases' => array(
    '%files' => 'sites/default/files',
  ),
);

$aliases['local-site'] = array (
  'root' => '/vagrant/bla',
  'uri' => 'http://site.local',
  'path-aliases' =>
  array (
    '%drush' => '/usr/bin/drush',
    '%site' => 'sites/default/',
    '%files' => 'sites/default/files',
  ),
  'databases' =>
  array (
    'default' =>
    array (
      'default' =>
      array (
        'database' => 'name',
        'username' => 'name',
        'password' => 'name',
        'host' => 'localhost',
        'port' => '',
        'driver' => 'mysql',
        'prefix' => '',
      ),
    ),
  ),
);
```

The command which causes the error:

> The command could not be executed successfully (returned: *** forbidden char/command over SSH: > "drush6  --backend=2 --yes --uri=site.nl                                    [error]
> --root=/data/disk/o/static/site/public  sql-conf   --all --db_type=mysql --db_host=localhost --> db_passwd=pass --db_name=dbname --db_user=dbuser 2>&1"

> This incident has been reported.

For further reference for others: https://omega8.cc/how-to-use-drush-aliases-321

**Comment by omega8cc** [comment]
Reopening then.

**Comment by omega8cc** [comment]
Only partially fixed, so we need more tricks to ignore 'env' sent by Drush remotely over SSH in front of actual command.

**Comment by omega8cc** [comment]
This should be fixed now!

**Comment by omega8cc** [comment]
Please make sure to read and follow updated docs at: https://omega8.cc/how-to-use-drush-aliases-321

It is important to no longer specify options removed in Drush, like `--no-cache` `--dump-dir`
