### ISSUE TITLE
How to setup a Drupal 8 platform

### ISSUE THREAD

**Issue by geofftech** [omega8cc/boa#377]
Does BOA currently support Drupal 8 Platforms?

I have tried a quick bash at one with a very simple makefile of this content

> api = 2
> core = 8.x
> projects[drupal][version] = 8

But I get this error

> The directory /data/disk/o1/static/drupal-8 does not contain a valid Drupal installation
> Drush could not bootstrap this platform. Please check the platform directory exists and is readable.

Any ideas?

**Comment by omega8cc** [comment]
And we support D8 again! https://github.com/omega8cc/boa/blob/master/CHANGELOG.txt#L16
