### ISSUE TITLE
using fabric for deployment

### ISSUE THREAD

**Issue by MuschPusch** [omega8cc/boa#386]
Hey, i'm curious if it's possible to use fabric for deployment to omega8cc hosted instances. I'm using this fabric tools for deploying other servers: https://github.com/stmh/fabalicious and it works great. Since there is no 'complete shell' on omega8cc it fails. Even when changing the environment shell to '/usr/bin/lshell' it doesn't work. Do you think it would be possible in some way??

**Comment by omega8cc** [comment]
This should be documented, perhaps.

**Comment by MuschPusch** [comment]
Hey we have added complete BOA support in fabalicous in the latest release and use it in production. What kind of documentation do you need?

**Comment by omega8cc** [comment]
If there is no BOA specific extra docs or magic required to use it, then why not to share the how-to in the BOA wiki, if there is anything which could be useful for BOA users who want to try it out, but are not sure where to even start?

**Comment by Pls** [comment]
Would love to try it using wiki.
2015 Saus. 19 11:53 "Barracuda Team" <notifications@github.com> rašė:

**Comment by MuschPusch** [comment]
Will try to create a wiki entry end of day :)

**Comment by Pls** [comment]
Sounds great!
2015 Saus. 19 12:02 "Volkan Florchinger" <notifications@github.com> rašė:

**Comment by omega8cc** [comment]
Great! Thanks in advance!

**Comment by MuschPusch** [comment]
There we go: 

https://github.com/omega8cc/boa/wiki/Fabric-based-deployment

**Comment by omega8cc** [comment]
Thank you!
