### ISSUE TITLE
SSL setup for TLS/SNI on server with one IP, multiple certificates

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#465]
I think I may be confused on how to set up SSL on a server with only one IP address and multiple certificates. I've looked in the Aegir issue queues, and it seems like this is a little ways off yet, so following [this comment](https://www.drupal.org/node/1244318#comment-7704213) I added a server_name to the nginx_wild_ssl.conf and then added more server configurations based on the template for extra_ip_ssl.conf, so something like

```
upstream extra_ip_ssl {
  server  YO.UR.AEGIR.IP:80;
}
###
### FOR abc-ssl-enabled-domain.com
###
server {
  listen                       *:443;
  server_name                  abc-ssl-enabled-domain.com;
  ssl                          on;
  ssl_certificate              /etc/ssl/private/abc-ssl-enabled-domain.crt;
  ssl_certificate_key          /etc/ssl/private/abc-ssl-enabled-domain.key;
  ssl_session_timeout          5m;
  ssl_protocols                TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                  RC4:HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers    on;
  keepalive_timeout            70;
  access_log                   off;
  log_not_found                off;
  ###
  ### Deny known crawlers.
  ###
  if ($is_crawler) {
    return 403;
  }
  location / {
    proxy_pass                 http://extra_ip_ssl;
    proxy_redirect             off;
    gzip_vary                  off;
    proxy_buffering            off;
    proxy_set_header           Host              $host;
    proxy_set_header           X-Real-IP         $remote_addr;
    proxy_set_header           X-Forwarded-By    $server_addr:$server_port;
    proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header           X-Local-Proxy     $scheme;
    proxy_set_header           X-Forwarded-Proto $scheme;
    proxy_pass_header          Set-Cookie;
    proxy_pass_header          Cookie;
    proxy_pass_header          X-Accel-Expires;
    proxy_pass_header          X-Accel-Redirect;
    proxy_pass_header          X-This-Proto;
    proxy_connect_timeout      180;
    proxy_send_timeout         180;
    proxy_read_timeout         180;
  }
}
```

This also allows one to use the securepages code in override.global.inc to set up mixed sites.

I would love to know if anyone foresees any pitfalls in this approach. I know that one may be if there are any changes that need to take place to nginx_wild_ssl.conf, as recently happened when SSLv3 was eliminated, but I figure if I monitor those files on upgrades I should be okay. Also I'm not that great at nginx configuration, so if this is a valid approach it would be nice to know if anything should be done differently than it is for multiple IP addresses. The upstream, for example, seems like it should be redundant if you're using only one IP.

**Comment by Amstercad** [comment]
Wow! The published roadmap is a great idea!

If it helps, here's what I have been using for several months to achieve an A+ score at SSL Labs. Credit goes to <a href="https://www.zufallsheld.de/2013/06/26/performance-spdy/">this web post</a> and their github version somewhere which is more uo-to-date. Of course credit also to Omega8 for making it so easy to include SPDY, and Perfect Forward Secrecy. OCSP Stapling is something I've yet to invest time in. I replaced the BOA wildcard ssl files with this file/text (and noted/remembered to put it back whenever I performed an upgrade to BOA).

#########################################################
### BEGIN *.example.com
###
### /var/aegir/config/server_master/nginx/pre.d/example_single_ip_ssl.conf
upstream nginx_http {
  server  localhost:80;
}
server {
# The 'spdy' at the end of the listen command below turns on SPDY support.
  listen                       *:443 ssl spdy;
  server_name                  _;
  ssl                          on;
  ssl_certificate              /etc/ssl/private/*.example.com.crt;
  ssl_certificate_key          /etc/ssl/private/*.example.com.key;
# Tell browsers to require SSL (warning: difficult to change your mind)
  add_header Strict-Transport-Security max-age=31536000;
# Turn on session resumption, using a 10 min cache shared across nginx processes,
# as recommended by http://nginx.org/en/docs/http/configuring_https_servers.html
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;
# Cut out (the old, broken) SSLv3 entirely.
# This **excludes IE6 users** and (apparently) Yandexbot.
# Just comment out if you need to support IE6, bless your soul.
  ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
  ssl_ciphers                  'kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 kEECDH+AES128 kEECDH+AES256 kEDH+AES128 kEDH+AES256 DES-CBC3-SHA +SHA !aNULL !eNULL !LOW !MD5 !EXP !DSS !PSK !SRP !kECDH !CAMELLIA !RC4 !SEED';
  ssl_prefer_server_ciphers    on;
  keepalive_timeout            70;
# Buffer size of 1400 bytes fits in one MTU.
# nginx 1.5.9+ ONLY
  ssl_buffer_size 1400;
# SPDY header compression (0 for none, 9 for slow/heavy compression). Preferred is 6.
#
# BUT: header compression is flawed and vulnerable in SPDY versions 1 - 3.
# Disable with 0, until using a version of nginx with SPDY 4.
  spdy_headers_comp 6;
# Now let's really get fancy, and pre-generate a 2048 bit random parameter
# for DH elliptic curves. If not created and specified, default is only 1024 bits.
#
# Generated by OpenSSL with the following command:
# openssl dhparam -outform pem -out dhparam2048.pem 2048
#
# Note: raising the bits to 2048 excludes Java 6 clients. Comment out if a problem.
  ssl_dhparam /etc/ssl/private/dhparam2048.pem;
  ###
  ### Deny known crawlers.
  ###
  if ($is_crawler) {
    return 403;
  }
  location / {
    proxy_pass                 http://nginx_http;
    proxy_redirect             off;
    gzip_vary                  off;
    proxy_buffering            off;
    proxy_set_header           Host              $host;
    proxy_set_header           X-Real-IP         $remote_addr;
    proxy_set_header           X-Forwarded-By    $server_addr:$server_port;
    proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header           X-Local-Proxy     $scheme;
    proxy_set_header           X-Forwarded-Proto $scheme;
    proxy_pass_header          Set-Cookie;
    proxy_pass_header          Cookie;
    proxy_pass_header          X-Accel-Expires;
    proxy_pass_header          X-Accel-Redirect;
    proxy_pass_header          X-This-Proto;
    proxy_connect_timeout      180;
    proxy_send_timeout         180;
    proxy_read_timeout         180;
    access_log                 on;
    log_not_found              on;
  }
}
###
### END *.example.com
###

**Comment by ar-jan** [comment]
I'm also trying to get this to work. I posted a question on GDO before I saw this: [SSL certificate configuration with SNI](https://groups.drupal.org/node/458663).

I've tried various combinations of SSL configs based on the current examples, but basically whatever I try, I end up serving everything with the specific abc-ssl-enabled-domain.com certificate as if it were the default wildcard certificate, while I want to use it only for `server_name                  abc-ssl-enabled-domain.com;`

Any pointers for single IP, SNI SSL configurations? Questions:

- Should we add more server definitions in nginx_wild_ssl.conf, or add custom config files per domain name?
- Do we need to use `upstream` groups like in the `upstream extra_ip_ssl` example?
- Any clue on how I can make a server definition with `server_name                  abc-ssl-enabled-domain.com;` apply **only** to abc-ssl-enabled-domain.com?

**Comment by Amstercad** [comment]
Did you completely remove nginx_wild_ssl.conf?

Did you create a new file in its place, using any name you like, and paste in the example text I made above, then search/replaced example.com with your own desirable domain name? Also, copy/paste example.com and search/replace again, using the same file (so the single file just keeps getting longer, with each domain name you add)?

Also do not forget to remove this new file you created, replacing it with the original nginx_wild_ssl.conf when you upgrade BOA for any reason. When finished upgrading, remove nginx_wild_ssl.conf again, and put your custom version back, and restart nginx.

Whenever you change these files, don't forget to restart nginx (service nginx reload). Hope this helps you.

**Comment by Amstercad** [comment]
Also my example above uses a wildcard certificate.  That means you must buy a wildcard certificate first. Otherwise remove the '*.' from *.example.com and use a cheaper single domain certificate.

**Comment by ar-jan** [comment]
I did not remove nginx_wild_ssl.conf, I want to use certificate-abc.crt for  abc-ssl-enabled-domain.com, while using BOA's self-signed certificate for e.g. *.boa.example.com and any other sites without an explicitly defined certificate. Perhaps this is possible by defining a priority somewhere? Basically, I was expecting  `server_name  abc-ssl-enabled-domain.com;` to make the certificate be used only for abc-ssl-enabled-domain.com but instead it takes over BOA's wildcard config.

So my configuration looked basically like the one by @dnotes above, with `server_name                  abc-ssl-enabled-domain.com;` while you are using `server_name  _`, i.e. any hostname.

**Comment by ar-jan** [comment]
Looks like my problems was trying to have more than one config file at a time, I guess this only works when you have separate IPs. When I add the wildcard server definition and my  abc-ssl-enabled-domain.com in one file it does work as expected.

Now what would be great is if we did not have to manually put back and replace the SSL configs on update as @Amstercad describes. Does this get overwritten on update, or why is that?

**Comment by attiks** [comment]
server_name should work, we use it all the time, we create a new config file inside /var.aegir/config/server_master/nginx/pre.d for each site, we left the original file in place.

**Comment by omega8cc** [comment]
The magic behind this is simple, we just need to document this:

1. Nginx loads config files in the alphabetical order, so the filename matters when using separate files
2. The wildcard `server {}` with `server_name _;` must be loaded/listed as the first (not last)

This means that you either add more `server {}` sections in `pre.d/nginx_wild_ssl.conf` - just make sure they are added below the default wildcard `server {}` there. This file is not overwritten on upgrade.

You can also create separate config files in `pre.d/`, but you must use safe, filenames, like `pre.d/z_foo.com_ssl.conf` to make sure they will be loaded after  `pre.d/nginx_wild_ssl.conf`

You can then use `listen *:443` in every extra `server {}` with its own SSL cert/key defined, and the will use the same IP address in the TLS/SNI mode.

**Comment by Amstercad** [comment]
That was the information I lacked! Thank you very much. I'll work to write documentation for the wiki this week.

**Comment by ar-jan** [comment]
Excellent, thank you @omega8cc!

**Comment by ar-jan** [comment]
I believe the single-IP solution needs some more work:

I followed the new recipe.

    o1:~# cat /root/.ssl.proxy.cnf 
    example.com 12.34.56.78 o1 info@example.com 12.34.56.78

`xboa ssl-gen` generated to proxies: z_example.com_pln_proxy.conf and z_example.com_ssl_proxy.conf, like this https://gist.github.com/ar-jan/daac5071e4f72164edfc.

    o1:~# service nginx reload
    nginx: [warn] conflicting server name "example.com" on 0.0.0.0:80, ignored
    nginx: [warn] conflicting server name "www.example.com" on 0.0.0.0:80, ignored
    nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    nginx: configuration file /etc/nginx/nginx.conf test is successful
    Reloading (via HUP) Nginx Server...:.

And example.com gives an nginx 502 error.

    o1:~# tail -f /var/log/nginx/error.log
    2015/03/09 01:32:19 [warn] 22760#0: conflicting server name "www.example.com" on 0.0.0.0:80, ignored
    2015/03/09 01:33:08 [alert] 22767#0: 512 worker_connections are not enough
    2015/03/09 01:34:08 [alert] 22767#0: 512 worker_connections are not enough
    2015/03/09 01:34:52 [alert] 22765#0: 512 worker_connections are not enough
    2015/03/09 01:35:08 [alert] 22765#0: 512 worker_connections are not enough
    2015/03/09 01:35:09 [warn] 4326#0: conflicting server name "example.com" on 0.0.0.0:80, ignored
    2015/03/09 01:35:09 [warn] 4326#0: conflicting server name "www.example.com" on 0.0.0.0:80, ignored
    2015/03/09 01:35:43 [alert] 4345#0: 512 worker_connections are not enough
    2015/03/09 01:35:44 [alert] 4345#0: 512 worker_connections are not enough
    2015/03/09 01:36:08 [alert] 4345#0: 512 worker_connections are not enough
    2015/03/09 01:36:33 [alert] 4345#0: 512 worker_connections are not enough

I removed the plain proxy file, and in z_example.com_ssl_proxy.conf changed `proxy_pass http://12.34.56.78` with `proxy_pass http://nginx_http` and now `service nginx reload` is OK and the site works.

Looks like two files for plain and ssl proxy don't work correctly? (nginx_wild_ssl.conf is the default, no extra server definitions).

**Comment by omega8cc** [comment]
Right, it shouldn't add conflicting plain HTTP proxy with single IP mode. Fixed in head and stable. Thanks!

**Comment by Amstercad** [comment]
This thread has become a wiki page: https://github.com/omega8cc/boa/wiki/Drupal-BOA-NGINX-setup-for-multiple,-secure-HTTPS-domains

**Comment by omega8cc** [comment]
Thank you! However, please note that we have added the `xboa` tool to standardize and automate this procedure, along with completely rewritten how-to: https://github.com/omega8cc/boa/blob/master/docs/SSL.txt

**Comment by arbelaezjm** [comment]
Is it posible to change the nginx config to improve the ssl score of the sites on evaluations with tools like this ..
https://www.ssllabs.com/ssltest/
https://www.ssllabs.com/ssltest/viewMyClient.html
Please refer to this approach
https://sethvargo.com/getting-an-a-plus-on-qualys-ssl-labs-tester/

**Comment by omega8cc** [comment]
Please just enable this and run `barracuda up-stable system`

`_NGINX_SPDY=YES`
`_NGINX_FORWARD_SECRECY=YES`

We will probably enable this by default soon.
