### ISSUE TITLE
_STRONG_PASSWORDS - only works on install, not up-stable, locals always "broken" evon though they are not broken

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#506]
Hello,

On 4 different complete barracuda and octopus up-stables on two different servers in the past 3 days, trying various settings for _STRONG_PASSWORDS   ,mysql and redis passwords are always 8  alphanumeric characters long no matter what setting for _STRONG_PASSWORDS.

I tried  _STRONG_PASSWORDS=YES
_STRONG_PASSWORDS=128
_STRONG_PASSWORDS=64  and
_STRONG_PASSWORDS=40

I always got 8 character alpha-numeric passwords.

This relates to - 
https://github.com/omega8cc/boa/issues/495
and
https://github.com/omega8cc/boa/commit/efa2d3bdaa469ee813d253b0229dcd4a33f7de10

Thank you.

Ed

**Comment by omega8cc** [comment]
OK, so here is why it doesn't work for you (I think): https://github.com/omega8cc/boa/blob/master/BARRACUDA.sh.txt#L274

You need to get locales fixed on your system first. This forced mode has been introduced because broken locales may explode _STRONG_PASSWORDS if used.

**Comment by EdNett** [comment]
I'd like to reopen this. I was able to get strong password to work (with minor caveats - like mysql root password truncating at 85 characters, whle redis gave a full 96 character password when set to _STRONG_PASSWORDS=96) - only by re-installing boa from scratch. On EVERY up-stable, the passwords are reset to 8 characters, no matter what is in the .barracuda.cnf file.

Also, I always set locales to have 3 en_gb locales, and en_us-UTF8, which I choose as the default. So, then how can locales be broken (that is what the barracuda up-stable scripts response tells me everytime) - so this must be the problem. SO, it is impossible to keep strong passwords and up-stable, until this is fixed.  What must be done, have only ONE locale, en_us-UTF8, set?

Thanks for help fixing this problem.

**Comment by ar-jan** [comment]
What is the output of `locale`? (logged in with your usual shell / connection manager).

**Comment by EdNett** [comment]
Barracuda System managed by Skynet Agent v.BOA-2.3.8 welcomes you aboard

server1:~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
server1:~#

This doesn't look right, does it? I always do dpkg-reconfigure locales and choose en_us-UTF-8 as the default (but leave other locales included). What do you suggest? I  guess I'll try reconfiguring locales again and removing all but en_us-UTF-8, and restarting the vps or server, then running the up-stable system again and see it the upgrade respects the .barracuda.cnf settings for strong passwords.  OR do you sugget I try to manually edit the locales file and add the en_us-UFT8 default?

Thanks for your help - don't want to have to use 8 character passwords.

**Comment by EdNett** [comment]
I just reconfigured the locales deselecting all locales except en_US-UTF-8, and for the first time received an error message:

 Barracuda System managed by Skynet Agent v.BOA-2.3.8 welcomes you aboard

server1:~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
server1:~# dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
*** update-locale: Warning: LANGUAGE (en_US.UTF-8) is not compatible with LC_ALL (). Disabl
ing it.
server1:~#

What do you make of this, and how to fix? Is it my error or an error in the barracuda script?

Best regards

Ed

**Comment by EdNett** [comment]
This is a debian wheezy vps x64 installed with the distribution kernel and English selected as install language.

**Comment by EdNett** [comment]
Still 8 character passwords when upgrading with:

1) ONLY en_US-UTF-8 set as locale via dpkg-reconfigure locales

and

2) all three en_US variations chosen with en_US-UTF-8 chosen as default.

**Comment by ar-jan** [comment]
I'm just going by what I remember, as I don't have time to check right now.

In [this comment](https://github.com/omega8cc/boa/issues/506#issuecomment-71455082), although it looks a bit weird to have POSIX for all those settings, it shouldn't be a problem, I think, since there is no warning, and POSIX is always available (it's an alias for the C locale). What I don't remember right now is whether there's a check looking for en_US.UTF-8 as well which could explain why BOA thinks there's a problem.

Can you also check the output of `locale -a`?

What's really strange is the warning `update-locale: Warning: LANGUAGE (en_US.UTF-8) is not compatible with LC_ALL (). Disabling it.`, since LC_ALL is empty as it should be.

I think those POSIX settings are being passed from your ssh client as environment variables.

Here's what *should* work to enforce correct settings: define all LC_* variables in /etc/default/locale (LANGUAGE is just a fallback and needn't be set, I think):

    LANG=en_US.UTF-8
    LC_CTYPE=en_US.UTF-8
    LC_NUMERIC=POSIX
    LC_TIME=en_US.UTF-8
    LC_COLLATE=POSIX
    LC_MONETARY=en_US.UTF-8
    LC_MESSAGES=en_US.UTF-8
    LC_PAPER=en_US.UTF-8
    LC_NAME=en_US.UTF-8
    LC_ADDRESS=en_US.UTF-8
    LC_TELEPHONE=en_US.UTF-8
    LC_MEASUREMENT=en_US.UTF-8
    LC_IDENTIFICATION=en_US.UTF-8
    LC_ALL=

The important things to enforce here (functionally) are these:
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=POSIX
LC_COLLATE=POSIX
LC_ALL=

All the other variables should be enforced just to make sure we know exactly what's being used  (An alternative is to disable `AcceptEnv LANG LC_*` in your /etc/ssh/sshd_config, but I'd go with the above approach since it makes it easy to see that you're explicitly enforcing particular locales).

If you have 1) all LANG/LC_ variables enforced as above, 2) en_US.UTF-8 and C/POSIX are available (see `locale -a`) and 3) There's no warning shown when running `locale`, well I can't really think of anything else. (Of course also make sure to log out and back in after changing these settings).

**Comment by EdNett** [comment]
Hello,

I think there is something wrong with your script:
https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc
on lines 502 and 503: (I added the 2 line numbers and provided a fix, below): - so the system up doesn't find that my locales are BROKEN when they are not:

#
# Fix locales.
fix_locales() {
  if [ -e "/etc/ssh/sshd_config" ]; then
    _SSH_LC_TEST=$(grep "^AcceptEnv LANG LC_" /etc/ssh/sshd_config 2>&1)
    if [[ "$_SSH_LC_TEST" =~ "AcceptEnv LANG LC_" ]]; then
      _DO_NOTHING=YES
    else
      sed -i "s/.*AcceptEnv.*//g" /etc/ssh/sshd_config
      echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
    fi
  fi
  if [ -e "/usr/etc/sshd_config" ]; then
    _SSH_LC_TEST=$(grep "^AcceptEnv LANG LC_" /usr/etc/sshd_config 2>&1)
    if [[ "$_SSH_LC_TEST" =~ "AcceptEnv LANG LC_" ]]; then
      _DO_NOTHING=YES
    else
      sed -i "s/.*AcceptEnv.*//g" /usr/etc/sshd_config
      echo "AcceptEnv LANG LC_*" >> /usr/etc/sshd_config
    fi
  fi
  _LOCALE_TEST=BROKEN
  _LOC_TEST=$(locale 2>&1)
502    if [[ "$_LOC_TEST" =~ LANGUAGE=.*UTF-8 ]] \     #shouldn't this be LANGUAGE=*.UTF-8
503  && [[ "$_LOC_TEST" =~ LANG=.*UTF-8 ]]; then      #shouldn't this be LANG=*.UTF-8
    _LOCALE_TEST=OK
  fi
  if [[ "$_LOC_TEST" =~ "Cannot" ]]; then
    _LOCALE_TEST=BROKEN
  fi
  if [ "${_LOCALE_TEST}" = "BROKEN" ]; then
    msg "WARNING!"
    cat <<EOF

**Comment by EdNett** [comment]
The other problem, is that when I visually inspect /etc/default/locale it is correct as you state it should be. But when I issue the command locale, the result, given below is different. Is it possible that the command locale is taking information from a location/file that no longer exists? ( I also give you the output of "locale -a", below, which appears to be correct.

 Barracuda System managed by Skynet Agent v.BOA-2.3.8 welcomes you aboard

server1:~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
server1:~# locale -a
C
C.UTF-8
POSIX
en_US.utf8
server1:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
STATUS: Skynet Agent is Active, OK!
STATUS: You can add the _SKYNET_MODE=OFF line in
STATUS: /root/.barracuda.cnf to disable me, if needed.

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
Bye

[ ok ] Reloading configuration files for periodic command scheduler: cron.
server1:~# barracuda up-stable system

Preparing the upgrade in silent mode...

NOTE: There will be no progress displayed in the console
but you will receive an e-mail once the upgrade is complete

You could watch the progress in another window with command:
  tail -f /var/backups/reports/up/barracuda/150127/barracuda-up-150127-0833.log
or wait until you will see the line: BARRACUDA upgrade completed

Waiting 8 seconds...
Starting the upgrade in silent mode now...

REPORT: Successful Barracuda upgrade on server1.toutpourleweb.info sent to info@toutpourlew
eb.info

BARRACUDA upgrade completed
Bye

server1:~# vim /etc/locale.gen
server1:~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
server1:~# locale -a
C
C.UTF-8
POSIX
en_US.utf8
server1:~#

**Comment by EdNett** [comment]
Lastly, I noticed in the usr/sbin/locale-gen script (which is part of the wheezy install, right?), there is a path error, which I have corrected as follows:

LOCALEGEN=/etc/locale.gen
LOCALES=/usr/share/i18n/locales
#USER_LOCALES=/usr/local/share/i18n/locales  # this was in the file, and it doesn't exist
USER_LOCALES=/usr/local/share/locale


could this be a problem? It does not solve the 8 character only password problem, however, as I have tried it with my fix.

Thanks for your help on this issue, which must be affecting more that just me

**Comment by EdNett** [comment]
I my fix for your script, above, the asterisk doesn't appear, I believe that you must have the dot after the asterisk, and not before it as you have on lines 502 and 503 of the 
https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc
script.

**Comment by ar-jan** [comment]
The /usr/sbin/locale-gen is part of Debian, and is unlikely to have anything to do with the problem. In this case, it is just looking if any user-defined locales exist, if not it uses the default ones.

If I find anything else I'll continue in #583 since it's open.

**Comment by ar-jan** [comment]
Actually the first question is why your system does not use the correct locales, so I guess we can keep that in this issue (I think it's unlikely to be a BOA problem, but rather a generic problem with your system).

I realize I've run into exactly the same thing before, but never solved it: see [Locale environment variable settings do not take effect](http://unix.stackexchange.com/q/155559/20865). That was on Debian 6, and IIRC I replicated that without BOA. Maybe some weird virtualization configuration?

What's the output of `env | grep "LC_\|LANG"`

**Comment by EdNett** [comment]
The output was nothing at all.   After purging, reinstalling and reconfiguring locales, and adding the line LANGUAGE=en-US.UTF-8 to the single line in /etc/default/locale, the output of your command, above, is:

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8

and the output of "locale" is everything is set to en_US.UTF-8 except LC_ALL= which is empty.

Thanks for your help.

**Comment by EdNett** [comment]
Actually, It was adding the following lines to my /root/.bashrc file that allowed the output of the "locale" command to be en_US.UTF-8 rather than the POSIX that was the previous output:

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
