### ISSUE TITLE
MongoDB: MNG keyword on extras list not working?

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#521]
The changelog has an entry about mongodb (https://github.com/omega8cc/boa/blob/master/CHANGELOG.txt#L3684). It is from an old release (v2.0.7) of BOA though, and states that MNG in the extras list will add mongodb support.

This is not documented in the NOTES.txt. I could not find anything in the changelog stating if support has been dropped or not.

**Comment by Pls** [comment]
I added Mongo/mongodb PHP extension and it works really great on PHP 5.6. But every time I upgrade BOA, php.ini and similar ini PHP files are regenerated and I have to readd extension=mongo.so or extension=mongodb.so lines to those ini files.

Is there any way to add this override and add some custom PHP extensions, which can be left/reapplied after upgrade?

**Comment by omega8cc** [comment]
Currently it is limited to PHP 5.3 -- not sure why, but I suppose it didn't work with other versions before. We could simply remove the restriction and see what happens.

**Comment by omega8cc** [comment]
Done!

**Comment by Pls** [comment]
Nice, thanks!

**Comment by Pls** [comment]
Just wanted to update that latest mongo PHP driver version is 1.6.14 (compatible up to PHP 5.6), all versions listed here - https://pecl.php.net/package/mongo.

Too bad that http://drupal.org/project/mongodb doesn't support newest mongodb PHP extension, which supports PHP 7. Related issue comment: https://www.drupal.org/node/2669050#comment-11240823. Would love to test PHP7 with mongodb in excellent multi-FPM mode :)

**Comment by omega8cc** [comment]
@Pls Please open a new issue! :)

**Comment by Pls** [comment]
Alright, sorry :)
