### ISSUE TITLE
Omega header tags are not outputted

### ISSUE THREAD

**Issue by attiks** [omega8cc/boa#522]
See also https://www.drupal.org/node/2384597#comment-9390765

I'm running on the latest legacy version, and I think I have a problem with the redis caching. All is fine but after a while the header tags from the omage base theme are no longer outputted, if I add ?noredis=1 to the URL it is fixed, or if I resave the theme settings.

Any ideas?

**Comment by omega8cc** [comment]
Feel free to reopen if there will be any further action required.

**Comment by attiks** [comment]
Not for the moment, I kinda gave up and added the headers to my template

**Comment by omega8cc** [comment]
OK
