### ISSUE TITLE
Backboa not working - no backup files uploaded to bucket

### ISSUE THREAD

**Issue by aanjaneyam** [omega8cc/boa#529]
Hi I Configured the new s3 backup feature as per instructions on https://github.com/omega8cc/boa/blob/master/docs/BACKUPS.txt.

My bucket (daily.boa.<output of uname -n> is located in Ireland with barracuda.cnf containing the following:
_AWS_KEY='xxxxxxxxxxxxxxxxxxx' ### From your AWS S3 settings
_AWS_SEC='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' ### From your AWS S3 settings
_AWS_PWD='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' ### Generate with 'openssl rand -base64 32'
_AWS_REG='eu-west-1' ### By default 'us-east-1'
_AWS_TTL='30D' ### By default '30D'

However after waiting for almost one week I see nothing in my bucket (it is empty). Back is not being uploaded.

If I try to run any of the following commands :
$ backboa backup
$ backboa cleanup
$ backboa list
$ backboa status

The output is "The duplicity backup is already running!"

**Comment by omega8cc** [comment]
I guess it is not needed in default setup, but if anyone would like to convert this non-standard recipe into wiki entry, feel free to document this.

**Comment by c-archer** [comment]
When I try and save this in the S3 bucket I get `Missing required field Principal`, has anybody else had this?
