### ISSUE TITLE
Piwik

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#531]
Is it possible (and is it of interest) to run a piwik instance on a BOA installation?

Not necessarily by having it installed through the installer (although that would be really cool, if we could a PWK on the extras list). A way of manually installing would also be fine.

Piwik, in general, needs php and a database (mariadb). Some extra php plugins for geolocation are also nice to have.

For info: http://piwik.org/

**Comment by macmladen** [comment]
However this may add unnecessary complexity to BOA system which is not really desired (**not** your everything and kitchen sink). Some lightweight statistics and analytics are needed but it may add overhead that is not too necessary so I think it is maybe better to be left for some **add on** tutorial(s) that would be very handy for those willing to try such things but with warnings about risks.

For instance, I thought how it is better to have own analytics and forgot about adding load to server and database. So I wouldn't go for it on my own server and makes complete sense to go on other server just like @Juc1 mentioned with some other services (like mail) that could be run there.

**Comment by Amstercad** [comment]
If I could just remind thread-watchers here, I raised a similar issue regarding functionality similar to Piwik not long ago. For reference, here's the link to it: https://github.com/omega8cc/boa/issues/367

I'm hugely in favor of log monitoring in a human way. I do fault Piwik however, as good as it is (very), because it doesn't report on malicious behavior at all like Real Logs do. Piwik is one technology, ELK Stack is another.

**Comment by omega8cc** [comment]
My conclusion is that we should avoid adding non-Drupal or non-Aegir directly related features. As I said before, we plan to even remove Webmin and Bind as an options to avoid further confusion and better prioritize our work on the BOA stack to make it even better than it is now.

You will be able to still install both Bind and Webmin, and once installed, add them to `_EXTRA_PACKAGES` list, though.

The Piwik support belongs to how-to in the wiki, so please feel free to add your recipes in the BOA project wiki.

Thank you!

~Grace

**Comment by macmladen** [comment]
I totally agree.

BOA should stay Aegir and Drupal focused and light on anything else.

And How To / Wikis are way for the brave and adventurous.

**Comment by pricejn2** [comment]
I just had to do this again for someone so put together a starter Wiki -- https://github.com/omega8cc/boa/wiki/Piwik

**Comment by omega8cc** [comment]
@pricejn2 Awesome! Thank you!

**Comment by bserem** [comment]
@pricejn2 thanks a lot!

Any reason to prefer one or the other option (barracuda or octopus level) ?

**Comment by bserem** [comment]
Update:
the wiki article is working fine to install piwik. However, the nginx configuration provided will not allow any site to communicate with piwik due to the fact that everything is redirected to the https.
Since the certificate is untrusted, browsers do not get it.

Either we should not redirect anything to https, or (which is what I'm trying to do) allow piwik.php and piwik.js to be used without https.

**Comment by pricejn2** [comment]
Sure thing. 

The primary reason would be user access to the piwik files. If installed at /var/www/piwik (what I'm calling barracuda-level), then only root user would have access to the directory. On the other hand, if installed at /data/disk/o1/static/piwik, then the octopus user o1.ftp, would have full access. 

The configuration provided in the Wiki is strictly https. You can easily use Cloudflare as a free SSL provider, or replace the wildcard certificate lines with your own purchased SSL. Alternatively, you can remove the `rewrite ^ https://$host$request_uri? permanent;` rule and allow http traffic. This will require some additional nginx vhost config, but most of this can just be reused from the 443 section (ie, fastcgi_param, limit_conn, root, index, and include).

**Comment by bserem** [comment]
Yes, cloudflare would probably do the trick as a free SSL provider.

I ended up with vhosts file in the non-https part.

```
###
### Piwik Web Analytics Redirect to HTTPS.
### Allow only tracking to be used over plain HTTP.
###
server {
  listen                       *:80;
  server_name                  piwik.ganymede.seremetis.net stats.srm.gr;
  root                         /data/disk/o1/static/piwik;
  #  access_log /var/log/nginx/piwik_access.log;
  #  error_log /var/log/nginx/piwik_error.log error;
  index                        piwik.php;
  include                      /var/aegir/config/includes/nginx_compact_include.conf;

  location = /piwik.js {
  }

  location = /piwik.php {
    fastcgi_pass unix:/var/run/o1.fpm.socket;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include         fastcgi_params;
  }

  location ~* ^.+\.php$ {
    deny all;
    rewrite ^ https://$host$request_uri? permanent;
  }
}
```

I hope it isn't too bad (it works of course).

Btw, I am using an octopus instance but I get the include file from
/var/aegir/config/includes/nginx_compact_include.conf;
contrary to your wiki page. I did not have
data/disk/o1/config/includes/nginx_compact_include.conf;
in my system (BOA 2.4.0 fresh install).

What's more, I had to chown to o1.ftp:www-data and chmod the tmp folder of piwik to 775.

**Comment by pricejn2** [comment]
I added a few notes to the Wiki to try and cover the HTTPS question. I'm only using HTTPS only Piwik installations, but feel free to update the Wiki with any changes.

Also, it's true that `data/disk/o1/config/includes/nginx_compact_include.conf` doesn't exist by default, but it can easily be copied from `/var/aegir/config/includes/nginx_compact_include.conf`.

**Comment by bserem** [comment]
Excellent. I simply added a link from the wiki page to this issue/discussion.

Thanks for all your effort :+1:
