### ISSUE TITLE
Install fresh BOA 2.3.8 on Debian Wheezy (minimal) throws PHP_CLI ERROR

### ISSUE THREAD

**Issue by ck-at-itizzimo** [omega8cc/boa#537]
During fresh installation on a new debian system the barracua script throws folling error in the install.log

Barracuda [Wed Dec 10 16:39:30 CET 2014] ==> INFO: Installing drush in /var/aegir
Barracuda [Wed Dec 10 16:39:31 CET 2014] ==> FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported values
Barracuda [Wed Dec 10 16:39:31 CET 2014] ==> FATAL ERROR: Aborting AegirSetupM installer NOW!

in the .barracuda.cnf the value is correct

_PHP_CLI_VERSION=5.3 #---------- PHP-CLI used by Master Instance: 5.{3,4,5}

Any hints? 
Thanks in advance

Heres my .barracuda.cnf
http://pastebin.com/wgpgWSnh

**Comment by omega8cc** [comment]
Feel free to reopen if there will be any further action required.
