### ISSUE TITLE
Unable to install IMG libraries

### ISSUE THREAD

**Issue by mindi1** [omega8cc/boa#539]
I installed fresh BOA 2.3.8. Changed barracuda.cnf before running up-stable to add IMG. I don't think it installed those libraries. Help?

**Comment by pricejn2** [comment]
I duped this on a fresh 2.4.0 install. 

I believe https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc#L3219 should be 

```
  if [[ "${_XTRAS_LIST}" =~ "IMG" ]]; then
```

**Comment by omega8cc** [comment]
Indeed, what a bug! Thanks for the heads-up!
