### ISSUE TITLE
I can't build custom platform Drupal way after updating on BOA 2.3.8

### ISSUE THREAD

**Issue by danielbehina** [omega8cc/boa#540]
After updating from BOA 2.3.5. to 2.3.8. I can't build platform via Drush with shell script, adopted for custom platform. I am using script which use Drupal to build platform and now, when all modules are downloaded, script fails with `line 114: 17119 Segmentation fault      drush make drupal-org-core.make $TEMP_BUILD`

Here is the part of shell script code:
```
...

DESTINATION=$(realpath $DESTINATION)

case $OSTYPE in
  darwin*)
    TEMP_BUILD=`mktemp -d -t tmpdir`
    ;;
  *)
    TEMP_BUILD=`mktemp -d`
    ;;
esac
# Drush make expects destination to be empty.
rmdir $TEMP_BUILD

if [ -d $DESTINATION ]; then
  echo "Removing existing destination: $DESTINATION"
  if $ASK; then
    confirm && chmod -R 777 $DESTINATION && rm -rf $DESTINATION
    if [ -d $DESTINATION ]; then
      echo "Aborted."
      exit 1
    fi
  else
    chmod -R 777 $DESTINATION && rm -rf $DESTINATION
  fi
  echo "done"
fi

# Build the profile.
echo "Building the profile..."
drush make --no-cache --no-core --contrib-destination="." build-tatiana.make tmp
echo "Profile build done."
# Build a drupal-org-core.make file if it doesn't exist.
if [ ! -f drupal-org-core.make ]; then
  cat >> drupal-org-core.make <<EOF
api = 2
core = 7.x
projects[drupal] = 7
EOF
fi

# Build the distribution and copy the profile in place.
echo "Building the distribution..."
drush make drupal-org-core.make $TEMP_BUILD
...
```

And when it starts to make drupal-org-core.make, it fails with error above.

As user o1 I am using directory ~/custom/build-profiles to build custom platforms and then move them with this script to the destination to ~/static. It works fine before BOA 2.3.8. May be some permission troubles or something with limited shell issues? Or something specific was changed in BOA or in BASH?

Great work guys, thank you for your work.
Daniel

**Comment by omega8cc** [comment]
Feel free to reopen if there will be any further action required.
