### ISSUE TITLE
Install fresh BOA 2.3.8 on Debian Wheezy throws MariaDB error

### ISSUE THREAD

**Issue by alexxo** [omega8cc/boa#548]
During fresh installation on a new debian wheezy system the barracuda script throws following error:

Barracuda [Fri Dec 26 05:18:35 CET 2014] ==> ALRT! MariaDB server not running properly!
Barracuda [Fri Dec 26 05:18:35 CET 2014] ==> EXIT: We can't proceed with installation and will exit now
Barracuda [Fri Dec 26 05:18:35 CET 2014] ==> HINT: Please check /var/backups/barracuda-install-141226-0501.log for more information,
Barracuda [Fri Dec 26 05:18:35 CET 2014] ==> HINT: (re)start MariaDB server and then run installer again
Barracuda [Fri Dec 26 05:18:35 CET 2014] ==> Bye
Octopus [Fr 26. Dez 05:18:36 CET 2014] ==> ALRT! MariaDB server not running properly!
Octopus [Fr 26. Dez 05:18:36 CET 2014] ==> EXIT: We can't proceed and will exit now
Octopus [Fr 26. Dez 05:18:36 CET 2014] ==> HINT: Please (re)start MariaDB server and then run installer again

From the install.log:
The first time the MariaDB server is restarted it works but the second it does not

Setting up mariadb-client-core-5.5 (5.5.41+maria-1~wheezy) ...
Setting up mariadb-client-5.5 (5.5.41+maria-1~wheezy) ...
Setting up mariadb-server-core-5.5 (5.5.41+maria-1~wheezy) ...
Setting up mariadb-server-5.5 (5.5.41+maria-1~wheezy) ...
[ ok ] Stopping MariaDB database server: mysqld.
[ ok ] Starting MariaDB database server: mysqld ..
[info] Checking for corrupt, not cleanly closed and upgrade needing tables..
.
.
.
Stopping MariaDB database server: mysqld.
Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!

The .barracuda.cnf is the default created by the BOA script. 
Installation run with following command:
$boa in-stable public my.server.com my-mail@my-domai.com o1 mini my-new-relic-ID

Any hints? 
Thank you

**Comment by omega8cc** [comment]
Feel free to reopen if there will be any further action required.

**Comment by alexxo** [comment]
Running /root/.barracuda.cnf with:
_FULL_FORCE_REINSTALL=YES 
_DEBUG_MODE=YES

Gives the same error:
ALRT! MariaDB server not running properly!
EXIT: We can't proceed with installation and will exit now
...
Please (re)start MariaDB server and then run installer again

Watching the verbose log : tail -f /var/backups/barracuda-install-150104-1734.log | grep mysql

https://gist.github.com/alexxo/25d9042dc23cc42bfc28#file-barracuda-install-150104-1734-log

**Comment by omega8cc** [comment]
Something is clearly not right with this system. Are you using clean, minimal OS with no services installed, so also w/o mysql running?

>>> mariadb-common : Depends: mysql-common but it is not going to be installed

This shouldn't happen, unless packages on this system are seriously broken.

I would suggest to re-image the system and start with clean install.

**Comment by Yusadolat** [comment]
ERROR: The only acceptable exceptions are: sshd and mail servers

This is what am getting any way out?
