### ISSUE TITLE
pdnsd not running

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#549]
I have a fresh server which installed OK and seems to be working, but the pdnsd service isn't running. The barracuda-install-141227-2236.log ended with:

    pdnsd is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Stopping pdnsd.
    Starting pdnsd failed!
    Stopping pdnsd.
    Starting pdnsd failed!

Starting and stopping manually also doesn't work (also not by removing pdnsd.pid).

    # service pdnsd stop
    [ ok ] Stopping pdnsd.
    # service pdnsd start
    [warn] pid file is exist in /var/run/pdnsd.pid, stop it or restart ... (warning).
    # service pdnsd restart
    [ ok ] Stopping pdnsd.
    [FAIL] Starting pdnsd failed!

Do you have any advice?

barracuda_log.txt:
`Sat Dec 27 23:25:48 CET 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.8 / Barracuda BOA-2.3.8 / Nginx 1.7.7 / PHP 5.4 / FPM 5.4 / CLI 5.4 / MariaDB-5.5.41 localhost`

Other installation logs are [here](https://gist.github.com/ar-jan/fe32e81895d6fb2febf8).

**Comment by omega8cc** [comment]
I suspect it could be related to incorrect pid files used in the procs monitor. If pdnsd is not started for some reason, /etc/resolvconf/run/interface/lo.pdnsd doesn't exist, so its contents is never written in /etc/resolv.conf, and the resolver just doesn't work. Could you test this again after these probably related commits?

https://github.com/omega8cc/boa/commit/f7fba5c93461bb490d14f5be8ab8826e06fae4a3
https://github.com/omega8cc/boa/commit/f006712e6c5cee40335b4867b5a642b609591e4f

**Comment by ar-jan** [comment]
Yes, fixed now after running `barracuda up-head`. Thanks!

**Comment by omega8cc** [comment]
Thanks!
