### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#550]
Dec 31 2014 upgrade to 2.3.8 head has so many errors, I can't list them all. This is on a vps with 1 core and 1GB ram - that has been getting high load averages - over 10 - a few times a day 2 weeks ago, 5 or 6 times a day recently, and in the last 24 hours every hour at 45 minutes past the hour.  It has only PHP5.5 on it. This vps has always had only boa on it, and has just 1 site + the hostmaster site. It has all platforms (but without any sites on them) plus a huge custom (static) platform with 300 modules on it (of which only 200 are active) on the single test site on the static platform.

1) Won't update anything:
make --quiet failed.  Error (if any): 0

Displaying the last 15 lines of /var/backups/barracuda-upgrade-141231-1215.log to help troubleshoot this problem
If you see any error with advice to run 'dpkg --configure -a', run this
command first and choose default answer, then run this installer again

Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 21 not upgraded.
Need to get 544 kB of archives.
After this operation, 0 B of additional disk space will be used.
Err http://ftp.debian.org/debian/ wheezy/main libmagickwand-dev amd64 8:6.7.7.10-5+deb7u3
  Could not resolve 'ftp.debian.org'
Err http://security.debian.org/ wheezy/updates/main libmagickwand-dev amd64 8:6.7.7.10-5+deb7u3
  Could not resolve 'security.debian.org'
Cannot find config.m4.
Make sure that you run '/opt/php55/bin/phpize' in the top level source directory of the module

2) Stalled completely tying to "Installing New relic Apps and Service Monitor" (over 1 hour) - and I had NO new relic key - so it shouldn't be trying to install it anyways.  

Looks like I'll have to reinstall wheezy and start from scratch.

**Comment by narayanis** [comment]
I get the same behavior with a new BOA 2.3.8 install on a Linode with a fresh install of Debian 7.7. 3Gb of RAM and 24Gb disk. I have two IPs, so I set my own DNS configuration (and set /.barracuda.cnf to the primary IP with valid MY_HOSTN and MY_FRONTN settings). The INSTALL.txt file says that it's not required to set up the hostname ahead of time, but the install failed completely until I set that up.
