### ISSUE TITLE
FATAL ERROR: DNS looks broken

### ISSUE THREAD

**Issue by asztalos-zolee** [omega8cc/boa#553]
Dear friends!

My provider increased the parameters of my virtual server (RAM, cores, disk space). After that, some tasks does not works on my BOA instance:
Octopus upgrade (octopus up-stable all both log) fails with errors: 
Octopus [Tue Dec 23 13:10:50 CET 2014] ==> UPGRADE A: FATAL ERROR: DNS looks broken for ignatius
Octopus [Tue Dec 23 13:10:50 CET 2014] ==> UPGRADE A: FATAL ERROR: Aborting AegirSetupA installer NOW!

All tasks via Aegir control panel fails with error:
Could not rsync from '/data/disk/o1/platforms' to 'o1@ignatius.zzzz.eu:/'

/data/disk/o1/platforms could not be synced to remote server
ignatius.zzzz.eu. Changes might not be available until this has been
done. (error: Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9])

Could you please help me, how to solve these problems? thank you!

UPDATE:
configs and logs: https://gist.github.com/asztalos-zolee/0953cc7c1c27fd7b25f5
provider: websupport.sk

**Comment by omega8cc** [comment]
Please follow guidelines: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by asztalos-zolee** [comment]
configs and logs: https://gist.github.com/asztalos-zolee/0953cc7c1c27fd7b25f5
provider: websupport.sk

**Comment by omega8cc** [comment]
It seems that you have changed system hostname, so it is now different than set up by BOA on initial install, hence all database grants are now broken and the Aegir backend thinks it is an alien system and not his own, so it switches automatically into "remote" mode, which obviously fails.

Please don't modify system like this.

Make sure the system uses the same IP address as before and then update its hostname to the FQDN hostname defined on BOA install.
