### ISSUE TITLE
sed: can't read after upgrade

### ISSUE THREAD

**Issue by impara** [omega8cc/boa#554]
Getting error messages after successful barracuda up-stable:
sed: can't read /var/aegir/.drush/sys/provision/http/Provision/Config/Nginx/Inc/vhost_include.tpl.php: No such file or directory
sed: can't read /var/aegir/.drush/sys/provision/http/Provision/Config/Nginx/Inc/vhost_include.tpl.php: No such file or directory
sed: can't read /var/aegir/.drush/sys/provision/http/Provision/Config/Nginx/subdir.tpl.php: No such file or directory
sed: can't read /var/aegir/.drush/sys/provision/http/Provision/Config/Nginx/subdir.tpl.php: No such file or directory
sed: can't read /var/aegir/config/includes/nginx_vhost_common.conf: No such file or directory
sed: can't read /var/aegir/config/includes/nginx_vhost_common.conf: No such file or directory

**Comment by omega8cc** [comment]
Please follow guidelines: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt
