### ISSUE TITLE
Bad gateway after upgrade when using SSL3

### ISSUE THREAD

**Issue by impara** [omega8cc/boa#555]
This issue may not be boa related but it did happened after a barracuda upgrade getting "Bad gateway".

Some of my /var/log/nginx/error.log has the following:

2014/12/23 23:37:40 [info] 8442#0: *573 SSL_do_handshake() failed (SSL: error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number) while SSL handshaking, client: 10.0.0.247, server: 0.0.0.0:443

2014/12/23 23:38:34 [info] 8427#0: *713 SSL_read() failed (SSL: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:SSL alert number 48) while processing SPDY, client: "SOME IP ADDRESS", server: 0.0.0.0:443

2014/12/23 23:38:41 [info] 8427#0: *720 peer closed connection in SSL handshake while SSL handshaking, client: "SOME IP ADDRESS", server: 0.0.0.0:443

2014/12/23 23:38:41 [info] 8427#0: *721 SSL_do_handshake() failed (SSL: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:SSL alert number 48) while SSL handshaking, client: "SOME IP ADDRESS", server: 0.0.0.0:443

2014/12/23 23:38:52 [info] 8427#0: *714 client "SOME IP ADDRESS" closed keepalive connection

It could be related to the latest openssl and must backport to older version to fix that but maybe omega8cc has seen it before?

**Comment by omega8cc** [comment]
This happens because we have removed support for SSLv3 in BOA for security reasons: https://github.com/omega8cc/boa/blob/master/CHANGELOG.txt#L350 

Please read articles linked in the commit comment for more information: https://github.com/omega8cc/boa/commit/f5ccf4e43bf1ce89f4c4abc936f6f3fe4daed7d1
