### ISSUE TITLE
Can't upgrade modules with drush 

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#556]
Hello 
I have tried to update my contributed modules on one hosted site without success. 
Here are the error messages i get when i launch "drush up --no-core" : 

/home/octopususer/drush-backups/mydb/20150105111058/modules/path_breadcrumbs.
Destination directory                                                [error]
/data/disk/octopus/distro/018/drupal-7.34.1-prod/modules/o_contrib_seven
is not writable.
File robotstxt-7.x-1.3.tar.gz is corrupt (wrong md5 checksum).       [error]
Updating project robotstxt failed. Attempting to roll back to        [error]
previously installed version.
Destination directory                                                [error]
/data/disk/octopus/distro/018/drupal-7.34.1-prod/modules/o_contrib_seven
is not writable.

Here are the required files : 

https://gist.github.com/yazzou/4f3f3c46139890b48724#file-barracudalog
https://gist.github.com/yazzou/f7653c316ec251772448#file-barracuda-cnf

https://gist.github.com/yazzou/f7653c316ec251772448#file-octoupus-cnf
https://gist.github.com/yazzou/9f0fef125792788de511#file-octospuslog

Regards
Yazzou

**Comment by omega8cc** [comment]
You can't upgrade contrib in a batch like this if it affects module you don't control because it is included in the o_contrib space. The `robotstxt` module will be updated in o_contrib in the next BOA release.
