### ISSUE TITLE
Make it possible to opt-out from otherwise recommended BOA Skynet auto-updates

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#557]
The BOA Skynet auto-updates were initially limited to checking for new BOA release and notifying the system admin daily, until the system was upgraded to latest stable release.

Next, since people tend to forget about running meta-installers update before running barracuda or octopus upgrade, and it generated a ton of unneeded tickets, confusion and frustration, we have automated these updates, so all your meta-installers were updated daily.

Then #drupageddon happened, and we realized that we could make all existing BOA systems secure, auto-magically, in the first 60 minutes after #drupageddon alert was published. Only if we could have a running mechanism in place to apply very trivial but how important patch to all your D7 sites/codebases while you were on vacation, out of town, or just AFK anywhere.

So we have added Drupal core monitoring and auto-patching to make sure you never run vulnerable codebase again. To make it effective, we have scheduled to run these checks hourly.

Then we have added also hourly updates for a few key scripts responsible for your system security, self-monitoring and self-healing.

Gradually it grew into its current incarnation, so at the moment BOA Skynet auto-updates do these things for you, while you sleep:

1. Daily version/release check and notification
2. Hourly update for all meta-installers and related tools
3. Hourly check for D7 core vulnerability and patching if detected
4. Hourly update for key BOA specific tools, monitors and self-healing agents
5. Hourly check if your DNS resolver still works as expected and repair if needed

While it is a very convenient to have all this work done for you, and we believe that it should be still enabled by default, we should make it possible to opt-out from all those auto-updates, if you prefer that your BOA system never calls home and whatever happens, is totally under your control.

**Comment by petrowsky** [comment]
Funny, I was just thinking about this today as I saw the update to websh just automatically happen on issue 552. My thought was "Dang, I hope Omega's server's don't get hacked. They are pushing out to their own servers plus who knows how many self-hosted instances."

Personally, I am EXTREEEEMLY grateful for what Omega has done and their generosity.  I can only hope the community reports have made it worth the efforts in the issue queues. As any developer becomes more aware of how things are SO interconnected, their paranoia can easily escalate. The level of trust regarding software is just phenomenal these days.

Of course, it's either trust, by those who know what's going on, or ignorance, which is the rest of the general public.

Given the focus you guys have towards security, allow me to be one of the many self-hosters who can only exclaim "THANK YOU, THANK YOU, THANK YOU! You guys are awesome and I have learned so much just from studying your scripts and technical approach!" You have my trust and praise and it's well deserved!

Ok, enough of hijacking the issue. Getting off of soapbox now (as I noticed my SMS based notice about the 'System Integrity checking detected'). ;)

**Comment by omega8cc** [comment]
Thank you for the feedback!

Note that this is only the first step to be included in the upcoming BOA-2.4.0 release, while BOA-2.4.1 should switch this to opt-in mode and disabled by default. It should be left for the system admin decision, but we also can't introduce opt-in mode without prior notice, which should be published in the upcoming release notes.

**Comment by zkrebs** [comment]
BOA is the awesomeness, hands down. Have used it for years and am impressed.
