### ISSUE TITLE
Update platforms stopped working

### ISSUE THREAD

**Issue by marko420** [omega8cc/boa#560]
Running "octopus up-stable o1 platforms" doesn't create new set of platforms. No errors are are reported, but neither are actual installs listed in log. Created a new BOA instance (client o3) and platforms were installed in the same sub-path "../platforms/005", but re-running the process doesn't generate another set of platforms.

Thanks!

**Comment by omega8cc** [comment]
This is normal when you have all latest platforms already installed. To created new set you need to use:

_HOT_SAUCE=YES #----------------- Forces new platforms tree on install when YES
_USE_CURRENT=NO #-------------- Forces new platforms tree on upgrade when NO
