### ISSUE TITLE
Node/add returning 403 for anonymous users

### ISSUE THREAD

**Issue by kevinob11** [omega8cc/boa#561]
When I try to access any node add pages as an anonymous user I receive a 403 error. I read in documentation that redirecting to the homepage is expected behavior (not quite what I'm seeing), and that I can override that behavior using a boa_platform_control.ini file. I attempted to create a boa_platform_control.ini file to fix the issue, but it didn't affect anything. It looked like nginx is returning the 403 much earlier. My site included nginx_octopus_include.conf from /var/aegir/config/includes, which explicitly returns 403 for all node add pages on line 620 (see gist below).

https://gist.github.com/kevinob11/8b783f87e75f8e078d85

Here are my barracuda config and log files, please let me know what else I can provide to help!
https://gist.github.com/kevinob11/d37b646c33c17dae17ce
https://gist.github.com/kevinob11/a62278dabb14f679f74e

Am I missing something about how to adjust config using the platform ini file rather than allow the nginx conf file to just explicitly return?

Thanks!

**Comment by omega8cc** [comment]
We don't support hosting sites on the Master Instance, and almost all features like this work only in the Satellite Octopus instances. Please move your sites to supported setup and avoid using the Master Instance for anything Drupal related.

Plus, we don't support such old systems like BOA-2.2.2-dev

**Comment by kevinob11** [comment]
Fair enough. Thanks!
