### ISSUE TITLE
Heads up for strong passwords - mysql 5.6 truncates a password of 100 character length - 64 chars OK

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#562]
Hello,

This relates to issue 506, which is still a problem for me (can't get a barracuda up to give me anything other than 8 character passwords):
https://github.com/omega8cc/boa/issues/506

I have a vps for a little ad server and I use mysql 5.6, and I just  discovered that 100 character passwords are too long. Since mysql 5.6 encrypts passwords, the password gets truncated, so that it still works (i.e. it doesn't break anything, but you don't know exactly how long it is or exactly what it is), but you can't use it to login to mysql since you don't know what it is. I have verified that a 64 ASCII password does work. I don't know the exact maximum.

So, this is just a heads up to test and see if mariadb 5.5 and 10.0 really do accept 128 character mysql root passwords. I don't mean to imply that you hadn't, but it won't work with mysql 5.6.

Best regards

Ed

**Comment by omega8cc** [comment]
I have just tested this and both MariaDB 5.5 and 10.0 works just fine with long passwords:

https://gist.github.com/omega8cc/eb446d5b834a758172b6
