### ISSUE TITLE
Is still necessary to disable l10n_update module?

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#563]
We use frequently the l10n_update module for Drupal multilingual web sites.
But it is automatically disabled by BOA. Explanation is:

*Disable l10n_update module by default to avoid issues when d.o servers are down.*

Is there any way to avoid disabling it?

Tx

**Comment by omega8cc** [comment]
Yes, on self-hosted instances you can whitelist it via `_MODULES_SKIP`

See: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L31
