### ISSUE TITLE
Adobe Edge Animate not rendered

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#564]
Hi all,

Is anyone familiar with https://www.drupal.org/project/edge_suite ?

If not http://tv.adobe.com/product/edge-animate/ renders animations in the form of a .oam file which unzips to html, image and .js files.  https://www.drupal.org/project/edge_suite is the Drupal plugin which uploads and processes the .oam file as a block.

[Here](http://www.desertpig.co.uk) is https://www.drupal.org/project/edge_suite  working fine on a non-BOA site (you should see clouds) and [here](http://i.imgur.com/Kn3Q6xV.png) is how it looks in firebug.

But when I use the same .oam file on a BOA 2.3.8 site the block is empty space  for example [here](http://edge-271214.desertmouse.co.uk) and you can see in firebug that the [content is missing](http://i.imgur.com/ac36ifQ.png). The files on the BOA server (which are basically the unzipped contents of the .oam file) [look ok](http://i.imgur.com/Nm2dWcf.png).  

Any ideas please what is wrong?

Thanks...

**Comment by Juc1** [comment]
ps in case anyone wants to try the https://www.drupal.org/project/edge_suite module -

1) use the git clone command [here](https://www.drupal.org/node/2354307#comment-9278585) (the version on https://www.drupal.org/project/edge_suite is out of date).
2) go to /admin/structure/edge_suite to upload an .oam file (such as the example .oam file [here](https://www.drupal.org/node/2354307#comment-9334065) - this creates a new block corresponding to the name of the .oam file)
3) Place the block

In my [non-BOA site](http://www.desertpig.co.uk) the module works fine. In my [BOA site](http://edge-271214.desertmouse.co.uk) the block is empty and the console gives the error "Uncaught ReferenceError: AdobeEdge is not defined"

Thanks....

**Comment by pricejn2** [comment]
I just tested using your steps on a 2.3.6 server and it works fine for me on foo.dev.domain.  But on the regular domain, same error in console and empty white space. ```?nocache=1&noredis=1``` do not change the results for the regular domain.

**Comment by pricejn2** [comment]
My guess is its a bug with the module.  From what I can see, ```http://animate.adobe.com/runtime/5.0.0/edge.5.0.0.min.js``` doesn't get loaded when Drupal caching /aggregation is enabled.

**Comment by omega8cc** [comment]
Good find. So it looks like a bug in the module if it doesn't work with Drupal standard CSS/JS aggregation enabled.

**Comment by Juc1** [comment]
@ pricejn2 and omega8cc 

Yes I can now see that enabling "Aggregate JavaScript files" in the non-BOA site causes the "AdobeEdge is not defined" problem = awesome, thank you...
