### ISSUE TITLE
Document adding ip to /etc/hosts for _MY_FRONT & _MY_HOSTN

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#566]
This is a suggestion for being added to NOTES.txt or INSTALL.txt

While adding public DNS entries for aegir master and satellites is ideal, it's not always desired - at least for self-hosting.

In my use case, I run a BOA server just for myself so no 'clients' are hitting a public aegir instance. Instead, I opt to omit the aegir domains and simply add them to my local machine's /etc/hosts.

As part of a public BOA install, I'm suspect that not having them found by DNS causes a bad mysql install. When installing to a new box, I opted to simply add them (as additional lines) within /etc/hosts (on the server) so the BOA installer would not complain. Since I initially forgot to add _MY_FRONT for resolution the first time I ran BOA installer, I was seeing the following within /var/log/syslog

	Jan 13 19:27:02 li836-36 mysqld: 150113 13:27:02 [Warning] Access denied for user 'my.front.domain'@'xxx.xxx.xxx.xx' (using password: YES)

I had to add the host manually to mysql via root to get the master aegir working properly. At least this is what I think I did.

Would it make sense to add notes about resolving _MY_FRONT & _MY_HOSTN via /etc/hosts for those boxes which don't set them up in public DNS?

**Comment by omega8cc** [comment]
This is rather an edge case and as such belongs to wiki area. Feel free to document this use case in a wiki. As for the main docs, there is already a hard to navigate amount of information. We need to clean it up and not extend like this, IMO.
