### ISSUE TITLE
Add safe_cache_form_clear Drush extension by default

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#568]
We are looking into integrating https://www.drupal.org/project/safe_cache_form_clear (or similar/perhaps more efficient module - https://github.com/saitanay/force_fct) into our BOA stack. Our cache_form grows to unreasonable size (3-5 GB). So to solve it, we plan to execute drush command (drush @site.com safe-cache-form-clear) using cron. In BOA it needs to be executed as o1 user to make aliases work.

As I see we have this option to add cron entries:
> nano /var/xdrago/cron/custom.txt

So, how to execute this drush command (in bash file) as o1 (o1.ftp) user?

**Comment by omega8cc** [comment]
You should add it to `/etc/crontab` instead, because you can easily specify the user there and it doesn't need cron reload and is not overwritten on upgrade.

**Comment by omega8cc** [comment]
Note that Drush aliases work also for o1.ftp, but you will have trouble to add non-defaut Drush extension for o1.ftp user.

**Comment by Pls** [comment]
Ok, thanks for your tips, will try to test it out.

Actually, I tried to add it to dev site as a module, enable it, and tried executing "drush safe-cache-form-clear" command. But drush can't see this command, running "drush cache-clear drush" doesn't help.

I suspect that I should place this module in /data/disk/o1/.drush/xts folder, to make it work globally on drush, right?

**Comment by omega8cc** [comment]
Drush extensions belong in the .drush subdirectory in the account home and not in the Drupal codebase.

**Comment by Pls** [comment]
Thanks for your explanation, makes sense. But in our situation, we had ugly code, which triggered form cache entry on every SINGLE anonymous page. With that solved now, we have managable size of cach_form.

Anyway, this should be great and safe form cache cleanup option for high traffic sites. Thanks!
