### ISSUE TITLE
Refine kill -9 in graceful.sh for keyword 'tomcat'

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#570]
Well, here I am again with an edge case. Turns out my install of confluence, or many other Atlassian products, may include the keyword 'tomcat' within their startup strings, even if the Tomcat service is not being used.

	# ps aux | grep tomcat
	1006     28502 58.9 17.5 2106248 1443372 pts/0 Sl   00:15   2:33 /opt/atlassian/confluence/jre//bin/java -Djava.util.logging.config.file=/opt/atlassian/confluence/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms1024m -Xmx1024m -XX:MaxPermSize=256m -XX:+UseG1GC -Djava.awt.headless=true -Xloggc:/opt/atlassian/confluence/logs/gc-2015-01-16_00:15:28.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M -XX:-PrintGCDetails -XX:+PrintGCTimeStamps -XX:-PrintTenuringDistribution -Djava.endorsed.dirs=/opt/atlassian/confluence/endorsed -classpath /opt/atlassian/confluence/bin/bootstrap.jar:/opt/atlassian/confluence/bin/tomcat-juli.jar -Dcatalina.base=/opt/atlassian/confluence -Dcatalina.home=/opt/atlassian/confluence -Djava.io.tmpdir=/opt/atlassian/confluence/temp org.apache.catalina.startup.Bootstrap start

This is matching against **/opt/atlassian/confluence/bin/tomcat-juli.jar** within **-Djava.endorsed.dirs**

This is therefore killing any java instance with the keyword tomcat.

Since I've not used Solr with Tomcat, I can't advise on the solution. Is there a better pattern that can be used on this line?
https://github.com/omega8cc/boa/blob/master/aegir/tools/system/graceful.sh#L33

**Comment by omega8cc** [comment]
Should be fixed now.
