### ISSUE TITLE
CAS module doesn't appear to work

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#577]
I get a 502 Bad Gateway when trying to authenticate from 1 site with CAS module enabled to another site on the same server with CAS Server enabled.

Output from access log:
```
2015/01/21 12:03:07 [error] 44305#0: *15568 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: mpc.ld, request: "GET /cas?destination=node&ticket=ST-Sfo6Pr8p24 HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "mpc.ld", referrer: "https://mpc.ld/"
```

**Comment by omega8cc** [comment]
This is expected, because BOA no longer runs php-fpm with port mode. It listens only on socket. It has been explained in detail in the changelog for BOA-2.3.0, I think.

**Comment by BrianGilbert** [comment]
just to confirm this should work if using socket instead?

**Comment by omega8cc** [comment]
Yes, but correct socket, of course. As explained (for any custom vhosts managed outside of Aegir) in the changelog/release notes last year.

**Comment by BrianGilbert** [comment]
Not working using socket, get's into a redirect loop..

**Comment by omega8cc** [comment]
Rediect loop is probably a result of your custom vhost rewrites/locations misconfiguration and has nothing to do with port/socket change, IMO.

**Comment by BrianGilbert** [comment]
the setup I tested on using socket is a vanilla barracuda (not octopus) install.

**Comment by BrianGilbert** [comment]
I've replicated the nginx and php-fpm configs from BOA on my local mac and still get a 502 error, I think it may be due to ipv6?

```
2015/02/04 15:15:44 [error] 3569#0: *257 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "POST /node?destination=node HTTP/1.1", upstream: "http://[fe80::1]:80/node?destination=node", host: "mpc.ld", referrer: "https://mpc.ld/"
2015/02/04 15:15:44 [error] 3569#0: *257 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /cas?destination=node HTTP/1.1", upstream: "http://[::1]:80/cas?destination=node", host: "mpc.ld", referrer: "https://mpc.ld/"
2015/02/04 15:15:45 [error] 3569#0: *274 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: mpc.ld, request: "GET /cas?destination=node&ticket=ST-m3LejJjsn7 HTTP/1.0", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "mpc.ld", referrer: "https://mpc.ld/"
```

Any suggestions?
