### ISSUE TITLE
Use recommended beta releases for views404 and views_accelerator

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#578]
Maybe we can have updated built-in modules, using the recommended beta over the current -dev releases :

- views_accelerator 7.x-1.0-beta1
- views404 7.x-1.0-beta1

Both of these modules don't have any updates in the -dev releaes after the beta1 release (and it looks like for views_accelerator the -dev is actually more outdated).

**Comment by omega8cc** [comment]
Thanks!
