### ISSUE TITLE
o_contrib and o_contrib_seven added to custom static platform

### ISSUE THREAD

**Issue by mrconnerton** [omega8cc/boa#580]
I've created a custom platform in my /home/*.ftp/static/my-platform directory but o_contrib in addition to o_contrib_seven is being automatically added. The modules in o_contrib are being somehow loaded and causing errors. Any thoughts?

**Comment by omega8cc** [comment]
Please follow guidelines. Thanks.

**Comment by mrconnerton** [comment]
I apologize, I always forget the different requirements for different projects. I will pull that together for you shortly.

**Comment by mrconnerton** [comment]
config files here: https://gist.github.com/mrconnerton/5b677e817151f0baea70

**Comment by mrconnerton** [comment]
I looking at fix_o_contrib_symlink() in https://github.com/omega8cc/boa/blob/171f97afa1ffb8f77a1b13335ff364faa05b8d5f/aegir/tools/system/daily.sh#L418 I see my project is missing /web.config for some reason. I assume this is an error in my deployment.
