### ISSUE TITLE
[xtra: rvm] Failed to build gem native extension.

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#581]
Currently on a BOA 2.3.6 Debian 7 server I cannot install some gems as non-root user:

```
o1.ftp:~$ rvm all do gem install ffi
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    /home/o1.ftp/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb

extconf failed, exit code 1

Gem files will remain installed in /home/o1.ftp/.rvm/gems/ruby-2.1.2/gems/ffi-1.9.6 for inspection.
Results logged to /home/o1.ftp/.rvm/gems/ruby-2.1.2/extensions/x86_64-linux/2.1.0/ffi-1.9.6/gem_make.out
```

However, as root there is no problem:

```
$ rvm all do gem install ffi
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.6
Parsing documentation for ffi-1.9.6
Done installing documentation for ffi after 2 seconds
1 gem installed
```

**Comment by pricejn2** [comment]
Verbose error log at http://pastebin.com/QH3cHYaF.  The step ```linking shared-object ffi_c.so```for this particular gem is failing.

Presumably, any gems that require building a dynamically linked shared object libraries will fail for non-root users.

**Comment by omega8cc** [comment]
It is explained in the how-to: 

https://github.com/omega8cc/boa/blob/master/docs/RVM.txt#L46
https://github.com/omega8cc/boa/blob/master/docs/RVM.txt#L51
https://github.com/omega8cc/boa/blob/master/aegir/tools/system/manage_ltd_users.sh#L313

Please upgrade to latest BOA stable and then re-initialize RVM on the account.

**Comment by pricejn2** [comment]
Thanks for the references.  Re-initializing RVM did the trick!

Re-initialize = removing ~/static/control/compass.info, waiting for rvm to be removed, and then re-adding ~/static/control/compass.info
