### ISSUE TITLE
Unable to up-stable - is my IP or domain blocked?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#585]
Hello,

I am unable to receive any response on my production server when I 

cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt

that is, there is never any completion, and I am unable to "barracuda up-stable system" or anything at all. Yesterday I tried to do a pull/fork of the boa master in order to try to submit a patch, and I mistakenly tried to push to the boa master instead of my own pull/fork on github once - could this have gotten my IP or domain banned?  I don't want to give the IP in clear text, but it begins with
37.187.

Could someone please check on this and un-ban me if that is what has happened. I have over 70 updates that I'd like to do, please.

**Comment by omega8cc** [comment]
We have experience large scale botnet attacks with POST requests killing the target from this subnet, involving too many IPs to block them individually, so it is blacklisted globally, at least on the US mirror.

```
DROP       all  --  37.187.142.0/24      0.0.0.0/0
DROP       all  --  37.187.144.0/24      0.0.0.0/0
DROP       all  --  37.187.0.0/16        0.0.0.0/0
LOGDROPOUT  all  --  0.0.0.0/0            37.187.142.0/24
LOGDROPOUT  all  --  0.0.0.0/0            37.187.144.0/24
LOGDROPOUT  all  --  0.0.0.0/0            37.187.0.0/16
```

I'm afraid we can't remove this block after the DDoS attack on the scale we have seen.

What is your hosting provide name and URL?

**Comment by omega8cc** [comment]
I have disabled it temporarily, but we may be forced to block it again.
