### ISSUE TITLE
var/xdrago/daily.sh: line 462: syntax error near unexpected token `_BCC_EMAIL=" error on latest dev

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#587]
Hi I am troubleshooting the latest dev version on a fressh linode install....

var/xdrago/daily.sh: line 462: syntax error near unexpected token `_BCC_EMAIL="${_MY_EMAIL}"'
/var/xdrago/daily.sh: line 462: `    _BCC_EMAIL="${_MY_EMAIL}"'
base:~#

is received when trying to run var/xdrago/daily.sh script....... shout I post my config.log files?

**Comment by omega8cc** [comment]
Fixed, thanks!

**Comment by AntiNSA** [comment]
/var/xdrago/daily.sh: line 578: syntax error near unexpected token `}'
/var/xdrago/daily.sh: line 578: `}'


now receiving this error...

Im goint to reinstall a fresh version of head to see if it clears.... is it my mistake?

**Comment by omega8cc** [comment]
This has been fixed in #588

Thanks!
