### ISSUE TITLE
/var/xdrago/daily.sh: line 578: syntax error near unexpected token `}'  new error

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#588]
Im not sure if this is my mistake, I am going to  reinstall head fresh...

/var/xdrago/daily.sh: line 578: syntax error near unexpected token `}'
/var/xdrago/daily.sh: line 578: `}'

and comment if I receive it again... not sure it seems everything has stopped working this last week...

Tons of trouble shooting going on..

**Comment by omega8cc** [comment]
Fixed. Thanks for the report!
