### ISSUE TITLE
find: `/var/backups/jetty*': No such file or directory find: `/var/run/*_backup.pid': errors.. important?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#589]
Ive received these errors a couple of days ago, and after fixing the script Im seeinngn them again.. is this a serious error?Im in the middle of troubleshooting a lot of things.... sorry if its not serious..
INFO: Daily maintenance start
INFO: Checking BARRACUDA version
INFO: Version test result: OK
INFO: Fixing permissions in the /data/all tree...
Permissions in sites/all tree just fixed
find: `/var/backups/jetty*': No such file or directory
find: `/var/run/*_backup.pid': No such file or directory
INFO: Redis server will be restarted in 5 minutes

**Comment by omega8cc** [comment]
This is normal and safe to ignore.

**Comment by omega8cc** [comment]
But we can silence this to avoid confusion.
