### ISSUE TITLE
Where to set _USE_MYSQLTUNER variable?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#594]
Hi I am having huge problems for a week. which cnf/ini is the proper file to set this to yes?

Use MySQLTuner only if _USE_MYSQLTUNER=YES is set

Thanks for your help..

**Comment by AntiNSA** [comment]
Im not sure if this would belong in the config folder in the sites/modules, or the barracuda conf file or octopus conf file. ... There seems to be no sommented out or read me file related to the proper placement of it that I can find...

**Comment by omega8cc** [comment]
All such directives belong to `/root/.barracuda.cnf`It is not documented yet, perhaps.
