### ISSUE TITLE
System configuration with increasing server capacity

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#595]
Hi,

I read in a couple of docs (like here https://github.com/omega8cc/boa/blob/master/docs/FAQ.txt#L47) that php memory limit and some other configuration depends on the available RAM and CPU cores.
Is this still true?
I installed a new server with 8GB of RAM and 4 cores. The php memory limit is still at 256MB. This is the same on another config I have where I have only a single core and 1GB RAM.

The main reason why I ask this is because if it would be better to increase capacity of a VPS or install a new VPS with more resources.
Or will the configuration (like for php memory limit) change on a new barracuda up-stable if it detects that the system has more power?

Thanks!

**Comment by omega8cc** [comment]
BOA does that already for you, but not by increasing PHP allowed memory beyond safe limits, but by allowing more PHP-FPM child processes to run and by adjusting the most RAM-hungry service: MariaDB to use as much RAM as possible.

The 256 MB is currently considered to be a safe limit per PHP-FPM process. No Drupal site should ever need more, but we could make it optionally configurable, perhaps.

If any site demands more than that, it usually has memory leaks to detect and fix, so no amount of memory could help.

**Comment by timlie** [comment]
Ok, thanks!
And thanks agian for the new shiny 2.4.0 version!!

**Comment by omega8cc** [comment]
Thanks!
