### ISSUE TITLE
$PATH and randpass availability

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#596]
With BOA 2.3.8 I would run the meta-installer, then log out and back in in order for the `randpass` command to be available, and be able to use strong passwords.

Now when I run the meta-installer the tool is installed in `/opt/local/bin/randpass` as expected, but the $PATH variable is not exported in /root/.bashrc so the randpass test will fail.

Did something change here?

**Comment by omega8cc** [comment]
There were no changes and the path is exported: https://github.com/omega8cc/boa/blob/master/aegir/conf/boa.bashrc.txt#L25

**Comment by ar-jan** [comment]
I guess this question isn't relevant now that I'll use regular `boa in-stable` for new installs anyways, which means the .bashrc will be there when I later update with _STRONG_PASSWORDS=YES configured (but, the .bashrc isn't yet written after doing only `cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`, which would otherwise have been a problem).
