### ISSUE TITLE
Single PHP-version installation fails

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#598]
Doing an installation with a single PHP-version doesn't succeed:

    ...
    FATAL ERROR: AegirSetupM installer failed
    FATAL ERROR: Aborting Barracuda installer NOW!
    HINT: Please check /var/aegir/install.log
    HINT: for more information on errors occured

cat /var/aegir/install.log

    INFO: Installing drush in /var/aegir
    FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported values
    FATAL ERROR: Aborting AegirSetupM installer NOW!

I could post logs (later), but it's reproducible with this:

`boa in-stable public boa.example.com info@example.com o1 none php-5.6`

**Comment by omega8cc** [comment]
Thanks for the report! Fixed in head and stable.
