### ISSUE TITLE
Webform Directory Private Files Accessible 

### ISSUE THREAD

**Issue by escapeit** [omega8cc/boa#599]
I'm using Aegir BOA-2.0.8 which I realized is a bit dated but i didn't see a change log topic for this.  

Files that are within the "webform" directory (http://domain.com/sites/domain.com/private/files/webform/*) are publicly accessible.  Files in directories with a name other than "webform" (http://domain.com/sites/domain.com/private/files/{otherDirName}/*) receive a 404 as expected.

Private files uploaded through the standard file field upload are protected as expected.  This issue presents regardless of whether the webform module is present.

I have to think there's a nginx.conf that is overriding the default behavior when the directory has the name of "webform" but I can't find it.

Any thoughts/help/wisdom/guidance would be greatly appreciated!

**Comment by omega8cc** [comment]
Hmm, this is weird. We have this location:

````
###
### Deny crawlers and never cache known AJAX and webform requests.
###
location ~* /(?:ahah|ajax|batch|autocomplete|webform|done|progress/|x-progress-id|js/.*) {
  if ($is_bot) {
    return 403;
  }
  access_log off;
  log_not_found off;
  set $nocache_details "Skip";
  try_files $uri @nobots;
}
````

But it is below/after this location:

````
###
### Deny direct access to private downloads in sites/domain/private.
### Note: this location works with X-Accel-Redirect.
###
location ~* ^/sites/.*/private/ {
  internal;
  if ($is_bot) {
    return 403;
  }
  access_log off;
}
`````

While both are regex locations, the `^/sites/.*/private/` should take precedence, IMO.

**Comment by escapeit** [comment]
FWIW, it's returning the 404, not 403.  Also, it's returning the nginx default 404 not the drupal 404 page.  if the file doesn't actually exist, it returns the drupal 404 page.  I just installed a minimal profile to test.  Here are some live links:

http://test.incitehost.com/sites/test/private/files/webform/x.txt - Returns visible file
http://test.incitehost.com/sites/test/private/files/testDir/x.txt - Returns NGINX 404
http://test.incitehost.com/sites/test/private/files/webform/doesntExist.txt - Returns Drupal 404

And I'm not sure if it helps, but the file permissions and ownership are identical.
```Batchfile
host:/var/aegir/platforms/boa_d7/sites/test/private/files# la
total 12K
-r--r--r-- 1 aegir    www-data  491 Feb  5 10:09 .htaccess
drwxrwsr-x 2 www-data www-data 4.0K Feb  5 10:02 testDir/
drwxrwsr-x 2 www-data www-data 4.0K Feb  5 10:16 webform/
host:/var/aegir/platforms/boa_d7/sites/test/private/files# la testDir/
total 4.0K
-rw-r--r-- 1 root www-data 20 Feb  5 10:16 x.txt
host:/var/aegir/platforms/boa_d7/sites/test/private/files# la webform/
total 4.0K
-rw-r--r-- 1 root www-data 20 Feb  5 10:16 x.txt
```
If I can provide any other details to help, please let me know.

**Comment by omega8cc** [comment]
OK, both locations are regex based, so apparently that one with `webform` keyword is considered as most specific, so Nginx decides to use it instead of /sites/.*/private/

**Comment by omega8cc** [comment]
Fixed in https://github.com/omega8cc/provision/commit/5af1794ad977244b4a0e3147fe0eea1c0bd117b4

**Comment by escapeit** [comment]
Great. Thanks guys.
