### ISSUE TITLE
PHP 5.5.21 fails to build

### ISSUE THREAD

**Issue by adamsro** [omega8cc/boa#600]
BOA [12:01:41] ==> INFO: Building PHP 5.5.21 part 2/3
sh ./configure --quiet --prefix=/opt/php55  [...] --enable-opcache failed.  Error (if any): 0
Displaying the last 15 lines of logfile
[/var/backups/barracuda-upgrade-150205-1158.log](https://gist.githubusercontent.com/adamsro/25db22c5788494fb9d81/raw/34348bdbf192729c4d58ff309d1b5c87294fd4af/barracuda-upgrade-150205-1158.log)

[barracuda.cnf](https://gist.githubusercontent.com/adamsro/924c80f7b03dd1d3eecc/raw/751f3ff98dc01aa14afd636bc8887e8c6cc52cfa/.barracuda.cnf)

**Comment by omega8cc** [comment]
We need to see also /var/log/barracuda_log.txt

**Comment by adamsro** [comment]
Oh sure, the last relevant lines are:

Thu Feb 5 11:46:57 PST 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.0 / Barracuda BOA-2.4.0 / Nginx 1.7.9 / PHP-MI 5.5 / PHP-SE / FPM 5.5 / CLI 5.5 / MariaDB-10.0.14 localhost
Thu Feb 5 12:06:15 PST 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.0 / Barracuda BOA-2.4.0 / Nginx 1.7.9 / PHP-MI 5.5 / PHP-SE 5.5 / FPM 5.5 / CLI 5.5 / MariaDB-10.0.14 localhost
Thu Feb 5 12:34:47 PST 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.0 / Barracuda BOA-2.4.0 / Nginx 1.7.9 / PHP-MI 5.6 / PHP-SE 5.6 / FPM 5.6 / CLI 5.6 / MariaDB-10.0.14 localhost

**Comment by adamsro** [comment]
I tried to install 5.6 which also failed and the installer deleted 5.5 so I seem to have compounded the problem for myself. "ERROR: I can not find PHP-CLI anywhere!"

**Comment by omega8cc** [comment]
How do you run the upgrade exactly? These logs/lines are out of sync - last installed PHP version was 5.6 but you are reporting problems with 5.5, which we can't reproduce.

**Comment by adamsro** [comment]
I ran the upgrade previously with "barracuda up-stable", in the last run I changed the _PHP_SINGLE_INSTALL variable to "5.6"

**Comment by omega8cc** [comment]
Please don't modify variables manually when you want to install single PHP version, and use correct option on command line instead. Not sure if that is the problem here, though.

**Comment by omega8cc** [comment]
I have just tried it on Debian/wheezy x86_64 twice and can't reproduce the problem.

**Comment by adamsro** [comment]
Yes, really not sure what is wrong with my install. Would you have any tips as to how to get php reinstalled at this point? I was looking at replicating the commands in the install_php_multi function.

**Comment by omega8cc** [comment]
You should just run "barracuda up-stable php-5.5" and it should work.

**Comment by omega8cc** [comment]
Try to find existing cli version here:

/var/backups/bin-php55-cli
/var/backups/bin-php54-cli
/var/backups/bin-php53-cli

And copy them to their original dirs before trying the upgrade again:

cp -a /var/backups/bin-php55-cli /opt/php55/bin/php
cp -a /var/backups/bin-php54-cli /opt/php54/bin/php
cp -a /var/backups/bin-php53-cli /opt/php53/bin/php

**Comment by adamsro** [comment]
It seems I've run into the same error: 
BOA [13:23:52] ==> INFO: Building PHP 5.5.21 part 2/3
sh ./configure --quiet --prefix=/opt/php55 --enable-fpm --enable-bcmath --enable-calendar --enable-exif --enable-ftp --enable-gd-native-ttf --enable-mbstring --enable-pcntl --enable-soap --enable-zip --with-curl --with-fpm-group=www-data --with-fpm-user=www-data --with-freetype-dir=/usr --with-gd --with-imap --with-imap-ssl --with-jpeg-dir=/usr --with-kerberos --with-mcrypt --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-mysql=/usr --with-mysqli=/usr/bin/mysql_config --with-openssl --with-pdo-mysql=/usr --with-pear --with-png-dir=/usr --with-t1lib=/usr --with-xmlrpc --with-xsl --with-zlib --with-ldap --with-gmp --with-xpm-dir=/usr --enable-opcache failed.  Error (if any): 0
Displaying the last 15 lines of logfile
...

BTW, huge thanks for helping me out with this.

**Comment by omega8cc** [comment]
When the PHP install fails, abort the script with ctrl-c, so it doesn't clean-up files in the /var/opt

Then go there and try to run inside the php* build directory

  make
  make install

and let us know with what errors exactly it fails.

**Comment by omega8cc** [comment]
By the way, where this instance is hosted (provider name) and what is the RAM available? If weird things happen to the PHP build which can't be reproduced, it is usually OOM failure.

**Comment by adamsro** [comment]
Makes sense. The provider is ProfitBricks, 11 GB assigned to VPS.

**Comment by omega8cc** [comment]
11 GB RAM? That is plenty. OOM happens on DigitalOcean with 512 MB RAM. Please try the make command manually and let us know how it fails.

**Comment by adamsro** [comment]
No makefile was created so I ran configure with the params the script ran, the same ones posted above, and got the following error:

configure: error: Cannot find MySQL header files under /usr.
Note that the MySQL client library is not bundled anymore!

**Comment by omega8cc** [comment]
Wow, that is super-weird. Please add in the /root/.barracuda.cnf this line:

_FULL_FORCE_REINSTALL=YES

and run "barracuda up-stable php-5.5" again

if THIS will not help, switch to _DB_SERIES=5.5 and add _FULL_FORCE_REINSTALL=YES again etc.

**Comment by adamsro** [comment]
I now, embarrassingly, suspect this may have something to do with my previous manual upgrading of mariadb 5.5 -> 10. Full reinstall still in process.

**Comment by omega8cc** [comment]
> manual upgrading of mariadb 5.5 -> 10. 

Hmm.. this doesn't sound good. You should never run manual upgrades. There is no reason for this.

**Comment by adamsro** [comment]
Would you be up to logging in and fixing this for me? Emergency hours of course. I'm at a loss.

**Comment by omega8cc** [comment]
We don't offer any emergency service for BOA support if you don't have a support subscription, unfortunately. Furthermore, it doesn't cover situations when something is broken because you have introduced changes manually which break things. I could only recommend to contact our sales team and/or just purchase the remote support subscription.

**Comment by adamsro** [comment]
Solved! I had assigned "10" to the  _DB_SERIES var instead of "10.0" so it was trying to install 5.5, probably why I tried to force it to begin with. Thanks again for spending time on this.
