### ISSUE TITLE
How to increase the site request limit?

### ISSUE THREAD

**Issue by mindi1** [omega8cc/boa#601]
My IP (dynamic) keeps being blocked. I want to set a custom limit.

Time:    Fri Feb  6 10:32:48 2015 +0000
IP:      ...................... (....)
Hits:    20
Blocked: Temporary Block

Edit: its a problem with port scan. I see 20 tries in 45 seconds. I changed the port it scans from 400-5000 and tried a port scan app and scanned ports from 0-79; got a temporary block

**Comment by omega8cc** [comment]
You should never run port scan against BOA system,
