### ISSUE TITLE
Document how to remove unused php versions

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#602]
Followup to #460.

If you previously had e.g. `_PHP_MULTI_INSTALL="5.3 5.4"` and now you have changed it to `_PHP_MULTI_INSTALL="5.4 5.5"`, PHP 5.3 will still be compiled again when you update BOA.

Is the compiled PHP version completely self-contained, so we could just do `rm -rf /opt/php53`?

And where should this be documented? It's related to the explanation of _PHP_MULTI_INSTALL in `lib/settings/barracuda.sh.cnf` but that's not directly part of the docs, is it?

**Comment by omega8cc** [comment]
The only method to disable (not really completely remove) not needed versions is to use the single version install mode first and then add more versions, if needed.

**Comment by omega8cc** [comment]
Related config option: `_PHP_SINGLE_INSTALL` -- see: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L69
