### ISSUE TITLE
Permissions preventing Drush dl into themes directory

### ISSUE THREAD

**Issue by caldenjacobs** [omega8cc/boa#603]
On running "$ drush dl [any drupal 8 theme]" as the Octopus user ("control.ftp" in my case) in the sites/all/themes directory of Drupal 8.0.0 Beta 6, installed by the Octopus installer, I get the following warning & error:

[warning]
is_writable(): open_basedir restriction in effect. File(/home/control.ftp) is not within the allowed path(s):
(.:/data/all:/data/conf:/data/disk/all:/opt/php53:/opt/php54:/opt/php55:/opt/php56:/opt/tika:/opt/tika7:/opt/tika8:/opt/tika9:/opt/tools/drush:/usr/bin:/home/control.ftp/.drush:/data/disk/control/.drush/usr:/data/disk/control/distro:/data/disk/control/platforms:/data/disk/control/static:/home/control.ftp/.tmp)
environment.inc:713

[error]
Directory /data/all/000/core/drupal-8.0.0-beta6/themes exists, but is not writable. Please check directory permissions.

I'm running a clean install of the latest BOA 2.4.0 stable release, on Debian 7.

On running drush dl in another platform's sites/all/themes directory, such as drupal-7.34.1, I get the same warning, but not the error, and the command successfully executes.

**Comment by omega8cc** [comment]
You are running drush commands in the wrong directory. You should either use drush alias for the site or cd to the site directory and not its themes nor modules subdirectories.

Example:

````
o3.ftp:~$ cd /data/disk/o3/distro/001/drupal-8.0.0-beta6/sites/d8b.o3.quad.tt.o8.io/
````

````
o3.ftp:[d8b.o3.quad.tt.o8.io]$ drush dl tao
Project tao (8.x-3.x-dev) downloaded to /data/disk/o3/distro/001/drupal-8.0.0-beta6/sites/d8b.o3.quad.tt.o8.io/themes/tao.            [success]
Project tao contains 0 themes: .
o3.ftp:[d8b.o3.quad.tt.o8.io]$
````

````
o3.ftp:[d8b.o3.quad.tt.o8.io]$ cd themes/tao
o3.ftp:[tao]$ ls -la
total 172
drwxrwsr-x 4 o3.ftp users  4096 Feb  6 19:02 .
drwxrwsr-x 3 o3     users  4096 Feb  6 19:02 ..
-rw-rw-r-- 1 o3.ftp users 18092 Nov  1  2013 LICENSE.txt
-rw-rw-r-- 1 o3.ftp users  6155 Jul  9  2014 README.md
-rw-rw-r-- 1 o3.ftp users   188 Jul  9  2014 base-rtl.css
-rw-rw-r-- 1 o3.ftp users  3376 Jul  9  2014 base.css
drwxrwsr-x 2 o3.ftp users  4096 Feb  6 19:02 drupal
-rw-rw-r-- 1 o3.ftp users  1019 Jul  9  2014 drupal-rtl.css
-rw-rw-r-- 1 o3.ftp users  7723 Jul  9  2014 drupal.css
-rw-rw-r-- 1 o3.ftp users   167 Jul  9  2014 ie.css
-rw-rw-r-- 1 o3.ftp users   388 Jul  9  2014 reset-rtl.css
-rw-rw-r-- 1 o3.ftp users  1392 Jul  9  2014 reset.css
-rw-rw-r-- 1 o3.ftp users 69829 Jul  9  2014 screenshot.png
-rw-rw-r-- 1 o3.ftp users   903 Jul  9  2014 tao.info
-rw-rw-r-- 1 o3.ftp users 15805 Jul  9  2014 template.php
drwxrwsr-x 2 o3.ftp users  4096 Feb  6 19:02 templates
o3.ftp:[tao]$
````

**Comment by caldenjacobs** [comment]
Thanks for the quick response! 

What about downloading a theme into a whole platform, rather than a specific site? 

A popular use case, which is feasible using BOA in D7, is to make the same theme available to all sites on the same platform under (distro)/(platform)/sites/all/themes.

Thanks again!

**Comment by omega8cc** [comment]
Yeah, there are apparently weird issues with Drush 7 head version we are using at the moment, so it throws those errors also when you type:

````
drush dl tao --destination=/data/disk/o3/distro/001/drupal-8.0.0-beta6/sites/all/themes/
````

Tao theme is downloaded in this case, but warning are displayed anyway (even if they are expected to be silenced)

We need to (constantly) review our customizations in Drush 7, because it is currently a (fast) moving target, so some hiccups like this are possible.

**Comment by caldenjacobs** [comment]
I see! Cheers!

**Comment by omega8cc** [comment]
No, wait, it is actually a bug, I think, because `open_basedir` should list also the lshell user home directory and not just tmp subdirectory.

**Comment by caldenjacobs** [comment]
Ok! After further testing, the D8B site isn't recognizing a theme downloaded using drush into either its own themes directory or to the whole platform, even when done properly using an alias, so that makes sense.

**Comment by omega8cc** [comment]
OK, the `open_basedir` problem is fixed, but Drush just doesn't use correct directories with aliases, apparently:

````
o3.ftp:~$ drush @d8b.o3.quad.tt.o8.io dl zen
Directory /data/all/000/core/drupal-8.0.0-beta6/themes exists, but is not writable. Please check directory permissions.                 [error]
Project zen (8.x-7.x-dev) could not be downloaded to /data/disk/o3/distro/001/drupal-8.0.0-beta6//themes/zen.                           [error]
o3.ftp:~$
````

This should be reported in the Drush queue, probably.

**Comment by omega8cc** [comment]
As for the themes itself, it has nothing to do with Drush or BOA. It is just Drupal 8 compatibility issue in any theme which is not "visible", I think.
