### ISSUE TITLE
Txt files in the drupal and/or modules dir should not be accessible directly

### ISSUE THREAD

**Issue by xbery** [omega8cc/boa#604]
I found an interesting thing which could be considered to be a security risk - all install, upgrade and readme files are directly accessible through browser. If you think of growing number of bots targeting drupal sites on the web, this could be a really simple way how to harvest information about your site's installation.

An easy fix would be to disable direct access to these files through browser in nginx.

**Comment by omega8cc** [comment]
I think that BOA/Aegir by default sends 404 for all those files. Since 2009, I think. Is there anything we have missed? An example URL which allows to display the file?

**Comment by omega8cc** [comment]
This works as designed. Feel free to reopen if you will find any exception to fix.

**Comment by xbery** [comment]
Sorry for me being an idiot, custom change of one of my colleague broke this feature.
