### ISSUE TITLE
master instance offline after barracuda-up - unable to connect to master instance db error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#605]
I have this error on a dedicated and a vps. Shouldn't the master instance user try to connect to user@localhost, instead of user@ipv4 ? Could that be the error?  See below for upgrading aegir instance feedback:

Platforms path /var/aegir/platforms exists. [0.96 sec, 7.45 MB]                   [success]
Platforms ownership of /var/aegir/platforms has been changed to aegir. [0.96 sec, [success]
7.45 MB]
Platforms permissions of /var/aegir/platforms have been changed to 755. [0.96 sec,[success]
7.45 MB]
Platforms path /var/aegir/platforms is writable. [0.96 sec, 7.46 MB]              [success]
Drush bootstrap phase : _drush_bootstrap_drupal_configuration() [0.96 sec, 7.46   [bootstrap]
MB]
Cache MISS cid: 7.0-dev-install_profile-2ce2edad53cd4c835ad237290cbac9b3 [0.96        [debug]
sec, 7.47 MB]
sql-query: SELECT 1; [0.96 sec, 7.62 MB]                                          [status]
Executing: mysql --defaults-extra-file=/var/aegir/.tmp/drush_7nD86r --database=masterserver1n
et --host=server1.netfast.us --port=3306 --silent  < /var/aegir/.tmp/drush_DQDtiu
  ERROR 1045 (28000): Access denied for user 'masterserver1net'@'correct ipv4' (using passwor
d: YES)
Drush was not able to start (bootstrap) the Drupal database.                      [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured
database. In this case you can select another site with a working database setup
by specifying the URI to use with the --uri parameter on the command line. See
`drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the
php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

**Comment by EdNett** [comment]
Why did you close this? This is a BUG REPORT and it's a very serious problem. You are not acting very professionally. What is going to happen to my sites and my octopus instances when the master instance is offline, and can't be reached?

**Comment by omega8cc** [comment]
https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by omega8cc** [comment]
Please stop trolling, or all your posts will be ignored/deleted if you will continue this aggressive behaviour and also continue to ignore guidelines.
