### ISSUE TITLE
Master barracuda instance offline after barracuda up-stable 240 feb 8 2015 - unable to connect to db error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#607]
I have tried repeatedly with 2 servers (one vps and one dedicated server - both running wheezy x64) to successfully perform a barracuda up-stable (240) for the past 2 days. In all cases I have a barracuda master instance offline, and this means that I cannot connect to chive sql manager, etc.

I do not believe I have a reverse problem, as the reverses are set for both servers (to server1.domain.com - not to master.server1.domain.com); and I have never had this problem before February 7th.  The only change I made on Feb 7th was to add hhvm, but I have not tried to use it, and I see that it is not running.
The error message was always unable to connect to db, and it changed a few times but only in the part AFTER the @ , so that the error was at first:  master-username@ipv4 using password = YES, 
then  master-username@ipv6 using password = YES finally,
master-usename@localhost using password = YES
The error is as inability to connect to database using masterusernam@localhost using password = YES  type of error.  I have looked at issue https://github.com/omega8cc/boa/issues/566 and wonder if I now need to add master.server1.domain.com  to my /etc/hosts file (after the IPv4   server1.domain.com). I tried this, but it did not help.  I also have an IPv6 address in the /etc/hosts file  pointing to server1.domain.com

The relevant logs, etc are here:

https://gist.github.com/EdNett/0d958631d1cd4dad38f0   - barracuda.cnf

https://gist.github.com/EdNett/4669d9c6cc6d180fab09  - barracuda_log.txt

In the master instances' drushrc.php file I note that the db_passwd is a 10 character alpha-numeric (not a 96 character string password as the .barracuda.cnf file calls for).

I also note that in the master instances' settings.php file I find this line in the global conf section:
$conf['allow_authorize_operations'] = FALSE;

Could either of these be causing the problem?

**Comment by EdNett** [comment]
Please remove the defamatory and erronious and harmful comment in https://github.com/omega8cc/boa/issues/605. I have been a valuable member of the BOA community for 4 years and have found scores of real bugs, reported them, and even helped to fix a few.  This is a real bug, even if you close it stating that you can't reproduce it. It has to be a BOA bug, because there has only been BOA on this server and on a vps with the exact same problem. Therefore the problem MUST come from one of the update scripts, and in this case something that was changed or added in the past 5 days.  I have always tried to help, and since I copied the 2 lines giving the exact error and put it in issue 605 - I did not think it relevant to include a link to the log files - as they are not going to help solve this. By the way, whoever defamed me when closing issue 605 also removed the error I had quoted, and also removed the posting I made in issue 530 (https://github.com/omega8cc/boa/issues/530) which is perhaps relevant. The goal should be to solve the error and fix it, right, ?

Best regards

Best regards

**Comment by omega8cc** [comment]
This is likely related to your custom setting:

`_STRONG_PASSWORDS=96`

But why it doesn't work, I have no idea. We have discussed this in a few previous tickets on GitHub and I believe that it must be related to your locales related problems.

That is why BOA ignores `_STRONG_PASSWORDS` when locales are not working as expected.

But since we can't reproduce the problem, we can't offer further advice, I'm sorry.

Please continue debugging this, but please understand that we can't help if there is no way to reproduce the problem.
