### ISSUE TITLE
Use strict options filtering to avoid installing New Relic on barracuda upgrade with no valid license key provided

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#608]
I did not have new_relic set to install on my .barracuda.cnf file, and it installed anyways, and modified the barracuda.cnf file adding the line   _NEWRELIC_KEY=aegir   at the bottom.

Here are the relevant logs:
https://gist.github.com/EdNett/0d958631d1cd4dad38f0   - barracuda.cnf

https://gist.github.com/EdNett/4669d9c6cc6d180fab09  - barracuda_log.txt

**Comment by omega8cc** [comment]
What was the upgrade command you have used exactly?

**Comment by omega8cc** [comment]
You have probably used "aegir" in the arguments list. There is no other chance it could get entered like this. We need a better validation to prevent triggering the installer into thinking that it got NR license key on command line.
