### ISSUE TITLE
heavy load and driver type not specified notices

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#609]
I have had a few attempted barracuda up-stables 240 recently with too heavy loads so that drush command aborts - the notices at the time indicate mysql, dns, nginx driver types not specified - could this be one cause of a heavy load?

terminal-output-failed-barracuda-up-stable-240-driver-type-notices-heavy-load

The relevant log is here:

https://gist.github.com/EdNett/3044324a8805fdd779f0

Required logs are here:

https://gist.github.com/EdNett/0d958631d1cd4dad38f0   - barracuda.cnf

https://gist.github.com/EdNett/4669d9c6cc6d180fab09  - barracuda_log.txt

**Comment by EdNett** [comment]
I was able to stop the daily /periodic super high load problem (at least it has stopped for 5 days now) by running barracuda up-stable with the following modified settings in the .barracuda.cnf file ( I had them all set to the opposite setting until now.I still have a barracuda master instance offline, however, but that's a different issue):

_SSH_FROM_SOURCES=NO
_SSL_FROM_SOURCES=NO
_FULL_FORCE_REINSTALL=YES
_USE_MYSQLTUNER=NO
_SKYNET_MODE=OFF

**Comment by omega8cc** [comment]
Only `_USE_MYSQLTUNER=YES` could cause high load on upgrade. The others settings are not related to the problem which may cause weak VPS systems.
