### ISSUE TITLE
mysqlnd is missing, why?

### ISSUE THREAD

**Issue by thebennos** [omega8cc/boa#612]
Hey

I realized that mysqlnd is missing in php. Maybe the Omega8 team had something in mind to kickout the default mysqlnd. (It is default from php 5.4). 

Normaly Drupal does not need it, but we are coding some module for big data and it would be nice to use the MySqli Async, because og non-blocking and there is a little performance improvement.

So why is Mysqlnd not installed? any reason?

Is it possible to install it like this 
_PHP_EXTRA_CONF="--with-mysql=mysqlnd \--with-mysqli=mysqlnd \--with-pdo-mysql=mysqlnd \"

???

There is also  good performance module "Asynchronous Prefetch Database Query Cache"
that uses Mysqlnd and Async. I open a other ticket (feature request) for it.

**Comment by omega8cc** [comment]
We use `--with-mysql=/usr` and not PHP built-in version to always stay compatible with latest MariaDB/Galera features. There are no plans to change this, because there are no better options/reasons, at least for now.
