### ISSUE TITLE
Asynchronous Prefetch Database Query Cache with Mysqlnd 

### ISSUE THREAD

**Issue by thebennos** [omega8cc/boa#613]
Hey

I asked in an other issue "why is mysqlnd not available in BOA". 
Here is a good reason to support it. 
Asynchronous Prefetch Database Query Cache
https://www.drupal.org/project/apdqc

Some setting are needed. Maybe something is in conflict with boa. 
Locking and Caching in Boa is done over REDIS and apdgc module maybe overwrites it.

I have not the knowledge, to say how it impacts the performance on boa. 
Maybe it good, maybe it breaks some settting and or slow a site down. 

In normaö Aegir with apache and Mysql it shows good performance improvement. 

Dear Omega8 team, have a look at it. Would be nice to hear your feedback.

**Comment by omega8cc** [comment]
There is no point in using tricks to make SQL caching faster, since it just can't compete with Redis.
