### ISSUE TITLE
[xtra: rvm] re-initialize on upgrade

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#614]
Following #581, it would make sense to re-initialize octopus rvm installations given changes from version to version in root compiled gems (https://github.com/omega8cc/boa/blob/master/aegir/tools/system/manage_ltd_users.sh#L312).  This would prevent any manual intervention by users to account for the addition of known gems which require building a dynamically linked shared object libraries.

**Comment by omega8cc** [comment]
Not sure if we should force RVM re-initalization. Probably not, because normally it will wipe out all existing gems the user installed. But we should document this better.

**Comment by pricejn2** [comment]
True, unless we're going to start moving gems between installs wiping out an existing gemset is probably not a good idea.

**Comment by pricejn2** [comment]
I believe your previous commit covers this 8cc8ba90

**Comment by omega8cc** [comment]
Right.
