### ISSUE TITLE
Error 500 in Non-Drupal AJAX Request

### ISSUE THREAD

**Issue by itizzimo** [omega8cc/boa#615]
Hello Omega Team,

we've installed a fresh 2.4.0 Version on Debian Wheezy Minimal without any errors.
Our old application (works fine von barracuda 2.3.1) runs now into a server 500 error by requesting json from an ajax service 

the ajax function doesn't use the Drupal Standard - it is a JQGrid Field Widget that uses the following url

<siteur>/DSCallback/<Options>

If i enter the REST Service manually into browser adress bar - it works

I've not installed a CSF Firewall (CSF was not in extra settings)
And i've deactived the redis cache in site_boa_control_ini but with no success

Any ideas?

Do you use any other mechanism? 

Thanks in advance

**Comment by omega8cc** [comment]
No idea. You should probably start debugging with inspecting PHP error logs in /var/log/php/
