### ISSUE TITLE
Is it possible to change default Under construction page? 

### ISSUE THREAD

**Issue by rokelvisar** [omega8cc/boa#618]
Hi!

I'm trying to serve all requests that don't have its own virtual server. Currently theese requests show black Under construction page, but I would like to change it with my custom-branded one. 

I know I can change it in /var/www/nginx-default, but it gets rewritten every time I upgrade the sytem.

Is there any config to set default page folder in .o1.octopus.conf or .barracuda.conf?

**Comment by omega8cc** [comment]
The trick is to convert those two files into symlinks:

/var/www/nginx-default/index.html
/var/www/nginx-default/under_construction.jpg

For example:

mv /var/www/nginx-default/index.html /var/www/nginx-default/my_index.html
mv /var/www/nginx-default/under_construction.jpg /var/www/nginx-default/my_under_construction.jpg
ln -s /var/www/nginx-default/my_index.html /var/www/nginx-default/index.html
ln -s /var/www/nginx-default/my_under_construction.jpg /var/www/nginx-default/under_construction.jpg

This will stop overwriting them on every upgrade.

**Comment by rokelvisar** [comment]
It works! Thanks, man. 

Is it possible to permanently change default folder, So I have more control of how the files are served?

**Comment by omega8cc** [comment]
The symlinks may link to any file you wish and that file may further reference other files, so you don't need to change the default folder, which is not possible anyway.
