### ISSUE TITLE
Is Google Being Blocked in Somehow being blocked? Strange results

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#620]
I have noticed strange search engine results....

Whenever you search for open learning study groups or collaborative learning study groups in Duck Duck Go, or Yahoo, etc/// My site, Thecenterofthenet.com is within the first search results, yet with google it is nowhere to be fround?

https://duckduckgo.com/?q=open+learning+study+groups

Are google search bots being treated differently than others?

Thanks for your help.

**Comment by ar-jan** [comment]
If you search for "site:thecenterofthenet.com" you see the site is indexed, so I'd say it must be due to Google's algorithms, or perhaps a (manual) penalty. You could look into Google Webmaster Tools to see if there are any warnings.

**Comment by omega8cc** [comment]
BOA doesn't block Google indexing bots.
