### ISSUE TITLE
All sites failing after upgrade - nginx error

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#621]
Hi all,

This is not a production server but o1, master and all created sites are failing to load:

This web page is not available 
Error code: ERR_CONNECTION_REFUSED  

I upgraded to 2.4.0 and when I looked at the o1 site everything looked ok (going through the verify platform tasks) but the the problem started after I did $ reboot. I have tried $ barracuda up-stable again but it does not help.  

    $ service nginx reload
    nginx: [emerg] open() "/data/disk/o1/config/includes/nginx_modern_include.conf" failed (2: No  such file or directory) in /data/disk/o1/config/server_master/nginx/vhost.d/test-310714.example.com:9
    nginx: configuration file /etc/nginx/nginx.conf test failed
    $

Any ideas please?

Thanks...

/data/disk/o1/log/octopus_log.txt = http://pastebin.com/WBcH99QK
/root/.o1.octopus.cnf = http://pastebin.com/n9qKevae
/var/log/barracuda_log.txt = http://pastebin.com/bzufQJwA
/root/.barracuda.cnf = http://pastebin.com/zuNbGxQQ

**Comment by omega8cc** [comment]
You have to remove all such broken vhosts leftovers until there will be no error during nginx reload.

`rm /data/disk/o1/config/server_master/nginx/vhost.d/test-310714.example.com`
`service nginx reload`

**Comment by Juc1** [comment]
@ Omega8cc ok problem fixed, thank you...
