### ISSUE TITLE
Unable to connect to SOLR on latest head

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#623]
HI! Using SOLR4 and Drupal 6 receiving error unable to connect to solr and solr is no longer functional.... tried manually restarting  service jetty9 restart and no go. Am rebooting server and rerunning update to see if that helps... running php 5.5

**Comment by AntiNSA** [comment]
OK, I have rebooted my server, and forced octopus upgrade on both..... till unable to connect to server error when trying to search.

**Comment by AntiNSA** [comment]
START_INI      =  /opt/jetty9/start.ini
JETTY_HOME     =  /opt/jetty9
JETTY_BASE     =  /opt/jetty9
JETTY_CONF     =  /opt/jetty9/etc/jetty.conf
JETTY_PID      =  /var/run/jetty9.pid
JETTY_START    =  /opt/jetty9/start.jar
JETTY_LOGS     =  /var/log/jetty9
JETTY_STATE    =  /opt/jetty9/jetty9.state
CLASSPATH      =
JAVA           =  /usr/bin/java7
JAVA_OPTIONS   =  -Xms8m -Xmx512m -Djava.awt.headless=true -Dsolr.solr.home=/opt/solr4 -Djetty.logs=/var/log/jetty9 -Djetty.home=/opt/jetty9 -Djetty.base=/opt/jetty9 -Djava.io.tmpdir=/tmp
JETTY_ARGS     =  jetty.state=/opt/jetty9/jetty9.state jetty-logging.xml jetty-started.xml
RUN_CMD        =  /usr/bin/java7 -Xms8m -Xmx512m -Djava.awt.headless=true -Dsolr.solr.home=/opt/solr4 -Djetty.logs=/var/log/jetty9 -Djetty.home=/opt/jetty9 -Djetty.base=/opt/jetty9 -Djava.io.tmpdir=/tmp -jar /opt/jetty9/start.jar jetty.state=/opt/jetty9/jetty9.state jetty-logging.xml jetty-started.xml

Jetty running pid=446

**Comment by AntiNSA** [comment]
updating to stable fixes issue.  : ) But I am looking forward to jumping back to head :) Living on the edge.

**Comment by omega8cc** [comment]
Honestly, we didn't test Jetty/Solr in head yet. It is possible that it is broken after Jetty version upgrade. But on clean install it seems to work.

**Comment by AntiNSA** [comment]
ok thanks : ) looking forward to tested with Jetty/Upgrade commit. THanks for all your hard work. Im your #1 fan.

**Comment by Nebel54** [comment]
I'm having the same issue, in my case /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java is missing.

**Comment by Nebel54** [comment]
@AntiNSA i did just find out that i destroyed my sources.list, so apt-get install openjdk-7-jre did not work. Maybe you have the same issue on your machine. Just check if apt-get update runs through without errors.

**Comment by AntiNSA** [comment]
ap-get update no problem... 

apt-get install openjdk-7-jre

runs until:

to provide /usr/bin/policytool (policytool) in auto mode
Setting up policykit-1-gnome (0.105-2) ...
Setting up powermgmt-base (1.31) ...
Setting up sane-utils (1.0.22-7.4) ...
Adding saned group and user...
Adding user saned to group scanner
insserv: warning: script 'K01jetty9' missing LSB tags and overrides
insserv: warning: script 'jetty9' missing LSB tags and overrides
saned disabled; edit /etc/default/saned

**Comment by AntiNSA** [comment]
as of today solr still not functional on latest head with new dolr test commit on upgrade

**Comment by omega8cc** [comment]
Thanks for the bug report!

**Comment by AntiNSA** [comment]
Thank you the fix works great! Now back to head : )
