### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by arttus** [omega8cc/boa#624]
I'm not sure where the Nginx community is at with this, but HTTP/2 has been in the news of late, so I'm wondering what the roadmap for this might look like?

**Comment by omega8cc** [comment]
Why to repost news here? Please delete it and leave only the question.

**Comment by omega8cc** [comment]
There is some controversy around this push for SPDY replacement, so we are not going to rush to be first to support it. We will see what Nginx does in this regard, though.

See also: http://www.matiasvangsnes.com/nginx/http2-spec-gets-green-light-faster-web-or-needless-complexity/

**Comment by Pls** [comment]
+1, progress is being made - https://www.nginx.com/blog/early-alpha-patch-http2/

**Comment by omega8cc** [comment]
Yes, however the deal breaker (for now) is that it requires OpenSSL 1.0.2+

http://nginx.org/en/CHANGES
http://nginx.org/en/docs/http/ngx_http_v2_module.html

**Comment by bserem** [comment]
Are there any reasons not to update to OpenSSL 1.0.2 ?

**Comment by omega8cc** [comment]
We would need to build OpenSSL from sources on all systems which come with older version from packages. Which can be problematic, because it may break some other OS distro packages which depend on packaged OpenSSL version. We did this on Squeeze before (to support PFS and SPDY) and it did cause problems for some people.

**Comment by omega8cc** [comment]
Even latest Debian Jessie comes with 1.0.1 -- https://packages.debian.org/jessie/openssl

**Comment by bserem** [comment]
Got it, thanks!

**Comment by omega8cc** [comment]
Fixed in #803
