### ISSUE TITLE
Deploy module isn't working since a recent update

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#625]
Can you think of any changes that may have an effect on this?

**Comment by AntiNSA** [comment]
Maybe has somethimg to do with the reason solr can't connect either?

**Comment by AntiNSA** [comment]
Did you figure anything out? I am going to wait a couple of more hours to see if there is a hot fix, and then I will try to upgrade to stable from head if there isnt a release. I find the overall backup/reinstall process takes at least 1-2hours to set up on a fresh server... Im using php 5.5.... wondering if the lates php update did it... but actually I think solr was down before that so maybe its the new nginx version... barracuda is awesome : )

**Comment by BrianGilbert** [comment]
I'm actually using a stable version.. haven't had time to investigate at the moment, I don't really know what to look for in this instance.

**Comment by omega8cc** [comment]
@BrianGilbert This is report is too cryptic to me, could you decrypt it and comment, so i could figure out what it is about?

**Comment by BrianGilbert** [comment]
pebkac.  not an issue with BOA
