### ISSUE TITLE
Configuring weekly system only upgrade

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#628]
I have configured the following in .barracuda.cnf in order to run weekly system-only upgrades every Sunday:

    _AUTO_UP_WEEKLY=7
    _AUTO_UP_MONTH=1
    _AUTO_UP_DAY=1

But the update hasn't run yet. I see the corresponding entries that should've been created in /etc/crontab aren't there. Am I missing something to activate this?

**Comment by omega8cc** [comment]
It should be added via `autoupboa` which is run via `/var/xdrago/clear.sh` unless `/var/run/boa_run.pid` or  `/var/run/daily-fix.pid` exist (usually because other important tasks are running).

You could also just add it manually with:

`$ bash /opt/local/bin/autoupboa`

**Comment by omega8cc** [comment]
Alos, it will not be added after initial system install, since it checks for `/data/disk/arch` which is created only after first nightly backup run.

**Comment by ar-jan** [comment]
A small question related to this: I'm wondering, why are the tasks started twice (5 minutes apart)?

    # Barracuda weekly system only upgrade
    35 2    * * 7   root    /opt/local/bin/barracuda up-stable system
    40 2    * * 7   root    /opt/local/bin/barracuda up-stable system

**Comment by omega8cc** [comment]
It is to make sure that it really started and run as expected. There can be temporary network issue when the first is scheduled etc, so there is the second added, just in case. If the first does run, the second will be ignored automatically.

**Comment by ar-jan** [comment]
Thanks!
