### ISSUE TITLE
Update to duplicity-0.7.01

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#630]
I'm trying out backboa, and am running into problems with the s3 connection, similar to what is described here:
- https://bugs.launchpad.net/duplicity/+bug/1278529
- https://github.com/boto/boto/issues/2262

Presumably I'm having authorization problems, but this is hard to establish without the proper errors passed along, and duplicity-0.7.01 is supposed to fix this.

**Comment by omega8cc** [comment]
Thanks for the heads-up.
