### ISSUE TITLE
Octopus Drush does not support features

### ISSUE THREAD

**Issue by kepford** [omega8cc/boa#631]
Drush commands don't seem to work as the o1 user even though the site has features module installed. This used to work. Is this a bug or am I missing something?

Running the following command ```drush @sitealias.com feature-list```

Results in this output.
```The drush command 'feature-list' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.                  [error]```

* [/root/.barracuda.cnf](https://gist.github.com/kepford/a11f3a8fa740d907de51)
* [/var/log/barracuda_log.txt](https://gist.github.com/kepford/18917bff190d8bb1899a)
* [/root/.USER.octopus.cnf](https://gist.github.com/kepford/b5e4083d4b6b1253a9a8)
* [/data/disk/USER/log/octopus_log.txt](https://gist.github.com/kepford/a869d5b70dfb27384414)

**Comment by karudonaldson** [comment]
On the drush page: https://www.drupal.org/node/960926 it looks like you should be using 
"drush features-list" instead of 
"drush feature-list"

**Comment by omega8cc** [comment]
We don't modify Drush behaviour in this area, so it should work with correct command:

````
o1.ftp:~$ drush aliases
@ppy.o1.quad.tt.o8.io
o1.ftp:~$ drush @ppy.o1.quad.tt.o8.io features-list
 Name                             Feature                   Status    Version         State
 Date Migration Example           date_migrate_example      Disabled  7.x-2.8
 Features Tests                   features_test             Disabled  7.x-2.3
 migrate_example_baseball         migrate_example_baseball  Disabled  7.x-2.7
 Migrate example - Oracle         migrate_example_oracle    Disabled  7.x-2.7
 Migrate Extras Media             migrate_extras_media      Disabled  7.x-2.5
 Migrate Extras Pathauto Example  migrate_extras_pathauto   Disabled  7.x-2.5
 Panopoly Admin                   panopoly_admin            Enabled   7.x-1.18
 Panopoly Core                    panopoly_core             Enabled   7.x-1.18
 Panopoly Demo                    panopoly_demo             Enabled   7.x-1.18
 Panopoly Images                  panopoly_images           Enabled   7.x-1.18
 Panopoly Magic                   panopoly_magic            Enabled   7.x-1.18
 Panopoly Pages                   panopoly_pages            Enabled   7.x-1.18
 Panopoly Search                  panopoly_search           Enabled   7.x-1.18
 Panopoly Test                    panopoly_test             Disabled  7.x-1.18
 Panopoly Theme                   panopoly_theme            Enabled   7.x-1.18
 Panopoly Users                   panopoly_users            Enabled   7.x-1.18
 Panopoly Widgets                 panopoly_widgets          Enabled   7.x-1.18
 Panopoly WYSIWYG                 panopoly_wysiwyg          Enabled   7.x-1.18
 UUID Services Example            uuid_services_example     Disabled  7.x-1.0-alpha6
o1.ftp:~$
````

**Comment by kepford** [comment]
The issue was actually not my typo. However, I was logged in as the o1 user instead of the o1.ftp account. Thanks for the help

**Comment by omega8cc** [comment]
That could be a problem, right, because of our custom Drush and Provision hardening and privileges separation to protect system account from invoking evil code in its context. We still have a work to do in this area, though.

```
o1@quad:~$ drush @py.o1.quad.tt.o8.io features-list
Command features-list needs the following module(s) enabled to run: features. [error]
The drush command 'features-list' could not be executed. [error]
o1@quad:~$
```
