### ISSUE TITLE
Make barracuda wrapper available on initial install to avoid confusion

### ISSUE THREAD

**Issue by civiclix** [omega8cc/boa#633]
Noob here; please forgive my ignorance! ;-)

I have just installed BOA on a clean install of Wheezy; the generic installation went flawlessly, but in reading one of the issues, I saw that I should also do an upgrade immediately after. In reading the docs, and trying to do: barracuda up-stable, I get the following "command not found":

root@aegir:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
STATUS: Skynet Agent is Active, OK!
STATUS: You can add the _SKYNET_MODE=OFF line in
STATUS: /root/.barracuda.cnf to disable me, if needed.

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
Bye

[ ok ] Reloading configuration files for periodic command scheduler: cron.
root@aegir:~# barracuda up-stable
-bash: barracuda: command not found

Am I doing something wrong? Logged in as root...

Thanks in advance for your help! Looking forward to using this (have used regular Aegir in the past, and think I'll like all the extras with BOA version).

**Comment by bserem** [comment]
Try rebooting the machine and logging back in. 'barracuda' should be 
available then!

-- 
Bill Seremetis
Drupal Implementor
mob: +306997047042
web: http://srm.gr
email: bill@seremetis.net

**Comment by omega8cc** [comment]
No need to reboot, juts log out and log in again. We should probably fix this step automatically.

**Comment by bserem** [comment]
sourcing /root/.bashrc 
or
export PATH=$PATH:/usr/local/bin:/opt/local/bin

Should make it work. If only I knew where this place should be.

**Comment by civiclix** [comment]
You ROCK! Thanks for the prompt response!

All good...install/upgrade completed successfully (I think!). ;-)

Interestingly, I installed this yesterday, then cleared everything out and installed regular aegir, then decided I liked this setup better, although it will take some getting used to. I did notice, however, that immediately after installing both yesterday and this morning, I started to get a lot of emails with failed login attempts...emails like this, mostly from Hong Kong and China:

Time: Fri Feb 27 14:50:23 2015 +0000
IP: 58.218.211.180 (CN/China/-)
Failures: 5 (sshd)
Interval: 300 seconds
Blocked: Permanent Block

Log entries:

Feb 27 14:50:17 aegir sshd[1419]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=58.218.211.180 user=bin
Feb 27 14:50:17 aegir sshd[1451]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=58.218.211.180 user=bin
Feb 27 14:50:19 aegir sshd[1419]: Failed password for bin from 58.218.211.180 port 53476 ssh2
Feb 27 14:50:20 aegir sshd[1451]: Failed password for bin from 58.218.211.180 port 45668 ssh2
Feb 27 14:50:21 aegir sshd[1621]: Invalid user dff from 58.218.211.180 

That, alone, makes me glad I've gone with BOA, for it's security features... ;-)

Any specific docs I should reference to set up CiviCRM platforms?

Thanks again!

**Comment by omega8cc** [comment]
As for CiviCRM, just add the platform, nothing special to do. You can use makefiles examples:

https://github.com/omega8cc/boa/blob/master/aegir/makefiles/civicrm-4.5-d7.make

**Comment by omega8cc** [comment]
Oh, read also:

https://omega8.cc/library/development
https://omega8.cc/how-to-add-custom-platform-properly-140

**Comment by civiclix** [comment]
Thanks, again...think I've read all the doc so far...nothing more to do than plug my nose and jump in, head first! ;-)

**Comment by omega8cc** [comment]
:)

**Comment by civiclix** [comment]
Yikes! Getting inundated with those blocked login attempts...can I stop these emails, safely?

**Comment by bserem** [comment]
check /etc/csf/csf.conf and search for ALERT
Grace (omega8cc) might have a better solution, but this works.

What you can do of course is filter these emails in your inbox. I ask from Thunderbird to put them in a different folder and keep the last few.

**Comment by civiclix** [comment]
Thanks...probably good to filter these, rather than turn off completely. ;-) Now that I have everything set up...I think!... any suggestions for other configuration I should do? There's a pile of docs, but they're scattered, and just trying to get my system setup according to 'best practices'.Bill Seremetis  wrote:>check /etc/csf/csf.conf and search for ALERT

**Comment by bserem** [comment]
Well, spend some time with BOA. It is a stack that does what it does really good.
You are the one capable to understand if it suits your needs.

For example: personally I use boa with 'none' option and have my makefile to create a platform that suits 90% of the sites I host. If the site isn't in this 90% then it should be on its own server (might be BOA too). Others might use it differently :)

**Comment by civiclix** [comment]
What's the 'none' option?

I, too, will only use it for very specialized sites, 90% of which will be built on a specific platform...have added a few to check them out, but will be deleting everything but the one or two I use.

It's a learning curve, but I'm familiar w/ Aegir, so that helps...just trying to figure out how this is put together, and how much easier it will be...

Thanks so much for your help!

**Comment by bserem** [comment]
The 'none' option on boa install doesn't add any platforms at all. It is 
used instead of max/mini/ask.
You end up with a BOA system that has only the hostmaster.

**Comment by civiclix** [comment]
Ah...came to me after I asked. ;-/Open mouth, Insert foot!Bill Seremetis  wrote:>The 'none' option on boa install doesn't add any platforms at all. It is
