### ISSUE TITLE
Automatically delete stuck crons?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#639]
Hey If this is out of the scope, let me know. But Often I find I have stuck crons.....Which fix themselves over time.... but sometimes its stuck for hours. Clearing it with drush fixes no problem. Can we somehow automatically check for long running crons over a defined time and then run the drush delete command ito automate the process?

**Comment by omega8cc** [comment]
I don't think it can be automated reliably. if you can find a pattern which can be reproduced, please do let us know.
