### ISSUE TITLE
Drush version / migrate error

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#640]
Hi all, 

Using BOA-2.4.0, I am migrating a site from a D6 platform to a D7 platform. "Compare platforms" shows no errors but the migrate task fails with this error: 

    WD php: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hk020315desert_0.blocked_ips' doesn't exist: SELECT 1 FROM {blocked_ips} WHERE ip = :ip; Array
    (
    [:ip] => 127.0.0.1
    )
     in drupal_is_denied() (line 1947 of /data/disk/o1/static/hop-734-150215/includes/bootstrap.inc).

My drush version = 

    $ drush status 
    Drush version: 7.0-dev
    $

I asked about this on Aegir IRC and helmo replied that he has seen this before https://www.drupal.org/node/2382663 and suggested I try a different version of Drush.

So can I set the default version of Drush that BOA uses ie in general or for a particular task?

Thanks...

**Comment by omega8cc** [comment]
You can't use different Drush version with BOA, or some things may explode.

Also, it is Drupal core well known issue with well known workarounds, but it is OT here and not related to anything in BOA/Aegir nor Drush.

**Comment by Juc1** [comment]
@ omega8cc ok, thanks...
