### ISSUE TITLE
BOA.sh.txt should update installers when invoked interactively, also with _SKYNET_MODE=OFF

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#644]
Hello,

I am running barracuda up-stable from a 2.4.1-dev done yesterday (way too high load at all times), and I am receiving boa 2.4.0 so it is downgrading php and nginx, and will break everything probably.

thank you.

**Comment by EdNett** [comment]
here is gist of barracuda log:

https://gist.github.com/EdNett/ae2523c58906d680f8e9

**Comment by omega8cc** [comment]
https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt#L13

**Comment by omega8cc** [comment]
Also: https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt#L10

**Comment by EdNett** [comment]
Here is proof:

https://gist.github.com/EdNett/f84ed66168ced7173d7d

**Comment by omega8cc** [comment]
No, This is only a proof that you didn't follow the docs and that you have disabled auto-updates with `_SKYNET_MODE=OFF`

**Comment by EdNett** [comment]
We won't use auto updates. Is having skynet mode to ON now a requirement for upgrading?

Thank you for your answer. I can upload the .barracuda.cnf file, but that's not even relevant to what is happening, but will do if that is required for support. Thank you.

**Comment by omega8cc** [comment]
Please just read the the docs!

https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt#L10

**Comment by omega8cc** [comment]
We will not respond to any issue in the future if you will not submit ALL required config files.

**Comment by EdNett** [comment]
2nd barracuda up-stable system gives 2.4.0 also:
https://gist.github.com/EdNett/1ce2144d3235ecd936f2

I am reading docs again, perhaps something is not clear to me? Will submit everything - just trying to help so this doesn't happen to any others.

**Comment by omega8cc** [comment]
You must update all installers manually if you have disabled auto-updates, before running the upgrade. It is clearly listed in the docs: https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt#L10

**Comment by EdNett** [comment]
barracuda cnf file is at:

https://gist.github.com/EdNett/d7a900958ad15eebd22f

**Comment by EdNett** [comment]
octopus cnf file is here:

https://gist.github.com/EdNett/e086c07a8ecb618d8469

**Comment by EdNett** [comment]
This is what I did, starting with a 2.4.1-dev head as of Sunday:

 $ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
$ barracuda up-stable
$ octopus up-stable o1 both

**Comment by omega8cc** [comment]
This is a bug, indeed. The BOA.sh.txt just quits when you have `_SKYNET_MODE=OFF` set and doesn't update meta-installers. We need to fix this, so `_SKYNET_MODE=OFF` will work only for non-interactive invocations.

**Comment by omega8cc** [comment]
Please try again, it should work:

`$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`

```
quad:~# grep stable= /opt/local/bin/barracuda
stable="BOA-2.4.1"
quad:~#
```

**Comment by EdNett** [comment]
This does not fix it for me. I still receive 2.4.0 - I have to up-head to receive the 2.4.1:

On Tuesday march 10 8:00 AM UTC:

server1:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
server1:~# grep stable= /opt/local/bin/barracuda
stable="BOA-2.4.0"
server1:~# barracuda up-stable

BOA [09:06:12] ==> Skynet Agent v.BOA-2.4.0 welcomes you aboard!

BOA [09:06:15] ==> INFO: UPGRADE

Do you want to proceed with the upgrade? [Y/n] n
Upgrade aborted by you

BARRACUDA upgrade completed
Bye

server1:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
server1:~# grep stable= /opt/local/bin/barracuda
stable="BOA-2.4.0"
server1:~# barracuda up-head

BOA [09:07:14] ==> Skynet Agent v.BOA-2.4.1 welcomes you aboard!

BOA [09:07:17] ==> INFO: UPGRADE

Do you want to proceed with the upgrade? [Y/n] y

**Comment by omega8cc** [comment]
Please delete the old BOA.sh.txt you have, first.

`rm -f /root/BOA.sh*`

**Comment by omega8cc** [comment]
Also, please post the result of command:

`env`

**Comment by EdNett** [comment]
I can confirm that this is now working and fixed.

The output of the env command you asked me to run is:


server1:~# rm -f /root/BOA.sh*
server1:~# env
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=ipv4 49270 22
LC_NUMERIC=POSIX
SSH_TTY=/dev/pts/0
LC_ALL=
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:o
r=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz
=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31
:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.t
bz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;3
1:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=
01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:
*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng
=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;3
5:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv
=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:
*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;
35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.mi
di=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36
:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/opt/local
/bin
LC_COLLATE=POSIX
PWD=/root
LANG=en_US.UTF-8
PS1=\h:\w\$
SHLVL=1
HOME=/root
LOGNAME=root
LC_CTYPE=en_US.UTF-8
SSH_CONNECTION=ipv4 49270 ipv4
_=/usr/bin/env
server1:~#

**Comment by omega8cc** [comment]
OK, thanks for the bug report and for the confirmation on the fix!

**Comment by omega8cc** [comment]
OK, thanks for the bug report and for the confirmation on the fix!
