### ISSUE TITLE
All site down after upgrade attempt 

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#645]
Hello 
I have launched an upgrade to make to have the last baracuda system features and my sites are down even the octoupus instance showing the black screen with the image "under construction". 
Please find the logs here : 
https://gist.github.com/yazzou/a320e9b5a28736966a9b
I have successfully upgraded baracuda system. But when launching the octoupus upgrade, i have this : 

octopus up-stable all both
find: `/data/disk/': No such file or directory

OCTOPUS upgrade completed
Bye

Actually my octopus user directory is stored in /vara/data/disk

I have tried to amend this in the conf file of octopus withtout success. 
I have put the following line in the config to try : 
_ROOT=/var/data/disk/${_USER}

I would appreciate any advice to get the site back. 
Thanks 
Yazzou

**Comment by omega8cc** [comment]
`/vara/data/disk` ????

**Comment by omega8cc** [comment]
We don't support non-standard directory tree modifications.

**Comment by omega8cc** [comment]
You can't modify paths in any script. Don't even try this. if you are using moved directory (which may still fail and we can't help), you should symlink it to the standard layout, like:

`$ ln -s /var/data/disk /data/disk`

Still, this may fail anyway because PHP open_basedir expects standard layout.

**Comment by yazzou** [comment]
No i did not modify it. Since the very first time it was like that. I have installed it when it was 1.4 version just as is

**Comment by omega8cc** [comment]
So how it ended up in /var/data/disk?

**Comment by yazzou** [comment]
Ok i just did :
ln -s /var/data/disk /data/disk
and launched the upgrade
and nows seems to be processing

2015-03-09 13:54 GMT+01:00 Barracuda Team <notifications@github.com>:

> So how it ended up in /var/data/disk?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omega8cc/boa/issues/645#issuecomment-77847623>.
>



-- 
http://www.mediaterranee.com

**Comment by yazzou** [comment]
the very first time (maybe in 2011) i have installed your script in my server with /data/disk and the default partition did not have enough space in this directory, so i have used  ln -s /var/data/disk /data/disk and installed. After it all worked klike that since the very first install.

**Comment by yazzou** [comment]
I have launched and it works. Do you think that can cause problems in the future ? the fact that i have it such way ? It would be real pain to delete all files in the server and start again.

**Comment by yazzou** [comment]
The aegir panel of the octopus user is blanc after upgrade. But came back to normal.

**Comment by omega8cc** [comment]
Not sure what happened to your symlink, but if this worked up to 2.4.0, should work also with 2.4.1

**Comment by yazzou** [comment]
should i relaunch the upgrade ? I did not find any solution for that. It worked all this time. Now i am considering taking another server to set a clean install and allocate most of space to /data directory rather than /var (which is like that by default). 
But in the meantime i would appreciate any advice letting me know how to get the panel back in order to export sites in clean way

**Comment by yazzou** [comment]
Now having big troubel again with that. All sites disapread in the middle at 4 am and i did not do anything on the system. The same black screenon "under construction" on all sites

**Comment by omega8cc** [comment]
Please add our SSH keys and send your system IP address to omega8cc at gmail.com, so we could take a look.

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab http://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
```

**Comment by yazzou** [comment]
Hello
Thanks for getting back. I have sent you the ip.


2015-03-10 8:41 GMT+01:00 Barracuda Team <notifications@github.com>:

> Please add our SSH keys and send your system IP address to omega8cc at
> gmail.com, so we could take a look.
>
> mkdir -p /root/.ssh
> cd /root/.ssh
> wget -q -U iCab http://omega8.cc/dev/keys/authorized_keys.txt
> cat authorized_keys.txt >> authorized_keys
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omega8cc/boa/issues/645#issuecomment-78008109>.
>



-- 
http://www.mediaterranee.com

**Comment by omega8cc** [comment]
As we have suggested after recovering your system from that almost crashed state, it is the best idea to start cleanly. You could use our how-to, though: https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

**Comment by yazzou** [comment]
Thanks a lot. I have taken a new server and will make a fresh install.
