### ISSUE TITLE
drupal-8.0.0-beta7 archive is corrupt

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#646]
When installing Drupal 8.0.0 beta7 on an Octopus instance, you get:

    BOA [16:10:43] ==> UPGRADE A: Aegir Satellite Instance upgrade completed
    gzip: stdin: unexpected end of file
    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now
    BOA [16:10:58] ==> DISTRO: Drupal 8.0.0-beta7 [001] installed

I've verified that this happens also with e.g. `wget http://files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz | tar -xzf -`.

**Comment by omega8cc** [comment]
Hmm...

```
$ wget http://files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz | tar -xzf -
--2015-03-09 21:22:03--  http://files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz
Resolving files.aegir.cc (files.aegir.cc)... 104.245.208.226
Connecting to files.aegir.cc (files.aegir.cc)|104.245.208.226|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1966080 (1.9M) [application/octet-stream]
Saving to: `drupal-8.0.0-beta7.tar.gz'

100%[====================================================================================================>] 1,966,080   71.8K/s   in 31s

2015-03-09 21:22:35 (61.5 KB/s) - `drupal-8.0.0-beta7.tar.gz' saved [1966080/1966080]
```

```
$ du -s -h drupal-8.0.0-beta7.tar.gz
1.9M	drupal-8.0.0-beta7.tar.gz
```

Could you test this with other mirrors?

http://us.files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz
http://uk.files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz
http://nl.files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz
http://jp.files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz

**Comment by omega8cc** [comment]
It looks like I had to touch the archive on the source system to force its rsync again, since it got partially synced before. Thanks for the heads up!

**Comment by omega8cc** [comment]
This was broken:

````
$ curl -I http://files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 09 Mar 2015 20:22:44 GMT
Content-Type: application/octet-stream
Content-Length: 1966080
Last-Modified: Fri, 06 Mar 2015 13:45:01 GMT
Connection: keep-alive
ETag: "54f9af5d-1e0000"
Expires: Wed, 08 Apr 2015 20:22:44 GMT
Cache-Control: max-age=2592000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

This is complete archive:

````
$ curl -I http://us.files.aegir.cc/core/drupal-8.0.0-beta7.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 09 Mar 2015 20:27:02 GMT
Content-Type: application/octet-stream
Content-Length: 9497419
Last-Modified: Mon, 09 Mar 2015 20:21:01 GMT
Connection: keep-alive
ETag: "54fe00ad-90eb4b"
Expires: Wed, 08 Apr 2015 20:27:02 GMT
Cache-Control: max-age=2592000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
````
