### ISSUE TITLE
After upgrade to 2.4.1 cloning tasks messes up

### ISSUE THREAD

**Issue by lsolesen** [omega8cc/boa#647]
After an automatic upgrade to 2.4.1 my cloning tasks seems to work in the Aegir interface, but not site is actually created and it ended up destroying my actual production site also. 

I was able to restore the site from a backup into the same platform into a new site, and the I was able to clone it back to the production sites name. However, I was a little worried for a while.

**Comment by omega8cc** [comment]
When you close the issue you have opened, please add some comment.

**Comment by lsolesen** [comment]
I could not reproduce the error with other cloning tasks right now, so I am not able to give much more info.
