### ISSUE TITLE
DNS issue on fresh vanilla server install

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#648]
Hello 
I have taken another server after big trouble because of the non conventional path on my install. I just want to have an advice for my new install. 
You can see all the details in my file : 
https://gist.github.com/yazzou/90cdfd5a9d5402d36a8e

I am using the URL of the server to install BOA, but seem that it does not meet the requirement for DNS. 

If i decide to set the DNS check to NO, is it going to be a hassle after ? I prefer to ask in order not to have the same trouble again. 

Thanks a lot !
Yaz

**Comment by omega8cc** [comment]
Just follow docs/INSTALL.txt and *don't* disable DNS check.
