### ISSUE TITLE
Deployments with Ansible

### ISSUE THREAD

**Issue by mrconnerton** [omega8cc/boa#649]
I was hoping to get some advice about running deployments via ansible with the lshell. When I tried a simple deployment it failed immediately with:

```
2015-03-11 15:37:30,657 (o1.ftp): *** forbidden shell escape: /bin/sh -c mkdir -p HOME/.ansible/tmp/ansible-tmp-1426088235.85-213864032111476  chmod arx HOME/.ansible/tmp/ansible-tmp-1426088235.85-213864032111476  echo HOME/.ansible/tmp/ansible-tmp-1426088235.85-213864032111476
2015-03-11 15:37:32,307 (o1.ftp): *** forbidden shell escape: /bin/sh -c LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python This incident has been reported./setup
```

I know how to cheat and just change the shell of the o1.ftp user but I was looking to learn the RIGHT way to do something like this and hopefully get a wiki page together. Thanks!

**Comment by omega8cc** [comment]
What is the context of this error? What are you trying to do, and how?

**Comment by mrconnerton** [comment]
I have a simple playbook that is just doing a drush @sitename cc all. When I run this playbook this is the first thing that comes back. 

Ansible is more or less just running remote commands on the server. I assume it's trying to create HOME/.ansible to store tmp files, etc by executing /bin/sh

**Comment by omega8cc** [comment]
Limited shell accounts can't invoke any other shell (nor /bin/sh directly) or any not whitelisted commands, by definition, so this will not work, I think.

**Comment by mrconnerton** [comment]
Only slightly related but if I change the shell of o1.ftp from the limited bash to standard /bin/bash, would that survive upgrades to boa?

**Comment by omega8cc** [comment]
Yes, upgrades will never modify shell for any account on any Octopus instance.
