### ISSUE TITLE
Robots.txt Inconsistencies 

### ISSUE THREAD

**Issue by breuter-zq** [omega8cc/boa#651]
We are on BOA 2.4.1 we updated the robots.txt module and deleted the actual robots.txt file in the site's files folder.  For 2 days BOA has not regenerated the robots.txt file and NGINX is serving the default robots.txt content (which we also doesn't include our sitemap reference), not what we have edited in the robots.txt module.  This seems to be inconsistent with  the documentation, https://omega8.cc/how-to-use-robotstxt-properly-243.  Please advise.

**Comment by omega8cc** [comment]
Please make sure that the site has a working DNS for its main name, so the system can access it with cURL request. Does the site name include `.temporary.` or `.testing.` keywords, by any chance?

Also, how is it possible that robots.txt if served with no 404 error if it really doesn't exist in the files directory and it doesn't match what the module configuration displays? I seems logically impossible.

**Comment by breuter-zq** [comment]
After further investigation it does not seem that the robots.txt file is regenerated nighty nor is the module enabled overnight like it is stated in BOA documentation.  We have seen this in our testing and production environments.  This was working when on BOA 2.3.8. What script is supposed to be performing these actions and where should it be scheduled?

Our site names names also don't include either of the keywords that you mentioned.

**Comment by omega8cc** [comment]
Please attach required logs: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by breuter-zq** [comment]
Here are logs you requested.

*BARRACUDA.CNF*
###
### Configuration created on 141001-1218
### with Barracuda version BOA-2.3.3
###
### NOTE: the group of settings displayed below will *not* be overridden
### on upgrade by the Barracuda script nor by this configuration file.
### They can be defined only on initial Barracuda install.
###
_LOCAL_NETWORK_HN=""
_LOCAL_NETWORK_IP=""
_MY_FRONT="master.xxxxx.xxxxx.org"
_MY_HOSTN="xxxxx.xxxxx.org"
_MY_OWNIP="x.x.x.x"
_SMTP_RELAY_HOST=""
_SMTP_RELAY_TEST=YES
_THIS_DB_HOST=localhost
###
### NOTE: the group of settings displayed below
### will *override* all listed settings in the Barracuda script,
### both on initial install and upgrade.
###
_AUTOPILOT=NO
_DEBUG_MODE=NO
_MY_EMAIL="hosting-support@xxxxxxxx.com"
_XTRAS_LIST="CSF CHV FTP"
###
_MODULES_FIX=NO
_MODULES_SKIP=""
_PERMISSIONS_FIX=NO
###
_CPU_CRIT_RATIO=9
_CPU_MAX_RATIO=6
_CPU_SPIDER_RATIO=3
###
_DB_BINARY_LOG=NO
_DB_ENGINE=InnoDB
_DB_SERIES=5.5
_DB_SERVER=MariaDB
_INNODB_LOG_FILE_SIZE=AUTO
###
_DNS_SETUP_TEST=YES
_EXTRA_PACKAGES=
_FORCE_GIT_MIRROR=""
_LOCAL_DEBIAN_MIRROR=ftp.debian.org
_LOCAL_UBUNTU_MIRROR=archive.ubuntu.com
_NEWRELIC_KEY="xxxxxxxxxxxxx"
_SCOUT_KEY=
###
_NGINX_DOS_LIMIT=300
_NGINX_EXTRA_CONF=""
_NGINX_FORWARD_SECRECY=NO
_NGINX_LDAP=NO
_NGINX_NAXSI=NO
_NGINX_SPDY=NO
_NGINX_WORKERS=AUTO
###
_PHP_CLI_VERSION=5.3
_PHP_EXTRA_CONF=""
_PHP_FPM_DENY=""
_PHP_FPM_VERSION=5.3
_PHP_FPM_WORKERS=AUTO
_PHP_GEOS=NO
_PHP_MONGODB=NO
_PHP_MULTI_INSTALL="5.3"
###
_REDIS_LISTEN_MODE=PORT
_RESERVED_RAM=0
_SPEED_VALID_MAX=3600
_SSH_FROM_SOURCES=NO
_SSH_PORT=22
_SSL_FROM_SOURCES=NO
_STRICT_BIN_PERMISSIONS=YES
_STRONG_PASSWORDS=NO
###
_CUSTOM_CONFIG_CSF=NO
_CUSTOM_CONFIG_LSHELL=NO
_CUSTOM_CONFIG_REDIS=NO
_CUSTOM_CONFIG_SQL=NO
###
_AEGIR_UPGRADE_ONLY=NO
_SYSTEM_UPGRADE_ONLY=NO
###
### Configuration created on 141001-1218
### with Barracuda version BOA-2.3.3
###
_SKYNET_MODE=ON
_PHP_SINGLE_INSTALL=

*BARRACUDA_LOG.TXT*
Wed Oct  1 12:47:21 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.3 / Barracuda BOA-2.3.3 / Nginx 1.7.5 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.39 localhost
Thu Oct 23 06:36:36 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.5 / Barracuda BOA-2.3.5 / Nginx 1.7.6 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.40 localhost
Thu Oct 23 06:51:18 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.5 / Barracuda BOA-2.3.5 / Nginx 1.7.6 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.40 localhost
Wed Nov 19 10:15:45 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.6 / Barracuda BOA-2.3.6 / Nginx 1.7.7 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.40 localhost
Sat Nov 22 06:22:10 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.6 / Barracuda BOA-2.3.6 / Nginx 1.7.7 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.40 localhost
Tue Dec  9 18:11:19 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.8 / Barracuda BOA-2.3.8 / Nginx 1.7.7 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.40 localhost
Tue Dec 16 18:14:29 MST 2014 / Debian.wheezy x86_64 XEN / Aegir BOA-2.3.8 / Barracuda BOA-2.3.8 / Nginx 1.7.7 / PHP 5.3 / FPM 5.3 / CLI 5.3 / MariaDB-5.5.40 localhost
Tue Mar 3 19:25:46 MST 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.0 / Barracuda BOA-2.4.0 / Nginx 1.7.9 / PHP-MI 5.3 / PHP-SE / FPM 5.3 / CLI 5.3 / MariaDB-5.5.42 localhost
Tue Mar 10 16:47:00 MST 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.1 / Barracuda BOA-2.4.1 / Nginx 1.7.10 / PHP-MI 5.3 / PHP-SE / FPM 5.3 / CLI 5.3 / MariaDB-5.5.42 localhost


*O1.OCTOPUS.CNF*
###
### Configuration created on 141001-1248 with
### Octopus version BOA-2.3.3
###
### NOTE: the group of settings displayed below
### will *override* all listed settings in the Octopus script.
###
_USER="o1"
_MY_EMAIL="xxxx-xxxx@xxxxx.com"
_PLATFORMS_LIST="ALL"
_AUTOPILOT=NO
_HM_ONLY=NO
_DEBUG_MODE=NO
_MY_OWNIP=
_FORCE_GIT_MIRROR=""
_THIS_DB_HOST=localhost
_DNS_SETUP_TEST=YES
_HOT_SAUCE=NO
_USE_CURRENT=YES
_DEL_OLD_EMPTY_PLATFORMS=0
_DEL_OLD_BACKUPS=0
_DEL_OLD_TMP=0
_LOCAL_NETWORK_IP=
_PHP_FPM_VERSION=5.3
_PHP_CLI_VERSION=5.3
_PHP_FPM_WORKERS=AUTO
_PHP_FPM_TIMEOUT=AUTO
_PHP_FPM_DENY=""
_STRONG_PASSWORDS=NO
_SQL_CONVERT=NO
_RESERVED_RAM=0
###
### NOTE: the group of settings displayed below will be *overridden*
### by config files stored in the /data/disk/o1/log/ directory,
### but only on upgrade.
###
_DOMAIN="o1.xxxxx.xxxxx.org"
_CLIENT_EMAIL="xxxxx-xxxxx@xxxxx.com"
_CLIENT_OPTION="SSD"
_CLIENT_SUBSCR="Y"
_CLIENT_CORES="8"
###
### Configuration created on 141001-1248 with
### Octopus version BOA-2.3.3
###


*OCTOPUS_LOG.TXT*
Wed Oct  1 12:57:19 MST 2014 / Debian.wheezy x86_64 / Aegir BOA-2.3.3 / Octopus BOA-2.3.3 / FPM 5.3 / CLI 5.3
Thu Oct 23 06:57:33 MST 2014 / Debian.wheezy x86_64 / Aegir BOA-2.3.5 / Octopus BOA-2.3.5 / FPM 5.3 / CLI 5.3
Wed Nov 19 10:29:44 MST 2014 / Debian.wheezy x86_64 / Aegir BOA-2.3.6 / Octopus BOA-2.3.6 / FPM 5.3 / CLI 5.3
Tue Dec  9 18:20:13 MST 2014 / Debian.wheezy x86_64 / Aegir BOA-2.3.8 / Octopus BOA-2.3.8 / FPM 5.3 / CLI 5.3
Tue Dec 16 18:22:39 MST 2014 / Debian.wheezy x86_64 / Aegir BOA-2.3.8 / Octopus BOA-2.3.8 / FPM 5.3 / CLI 5.3
 / Debian.wheezy x86_64 / Aegir BOA-2.4.0 / Octopus BOA-2.4.0 / FPM 5.3 / CLI 5.3

**Comment by omega8cc** [comment]
You need to set `_MODULES_FIX=YES` to get the module auto-enabled and new robots.txt generated.

Please check also: https://github.com/omega8cc/boa/blob/master/CHANGELOG.txt#L159

**Comment by breuter-zq** [comment]
Thank you, didn't know what that line meant.  Should this be mentioned in the robots.txt documentation?  Does this 'Fix' any other modules as well?

**Comment by omega8cc** [comment]
We don't explain this at https://omega8.cc/how-to-use-robotstxt-properly-243 because we always enable this feature in our hosted environment. This should be improved in the upcoming complete docs rewrite.

For more details please check also:

https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L30
https://github.com/omega8cc/boa/blob/master/README.txt#L29
https://github.com/omega8cc/boa/blob/master/docs/MODULES.txt
