### ISSUE TITLE
How does Omega deal with possible virus infections?

### ISSUE THREAD

**Issue by santo74** [omega8cc/boa#652]
Is it correct that there are no precautions in place for virus detection on a BOA system?
With this I mean a process such as a virus scanner that checks for possible virus infections, either realtime or on a regular basis.
The reason I ask this is because I am a bit worried about possible virus infections that might occur when someone uploads - either intentionally or by accident - an infected file (with an allowed file extension) via a form on a website, e.g. an infected pdf file.

**Comment by omega8cc** [comment]
BOA doesn't support mail server and the probability of having infected file uploaded is too tiny to impose a giant overhead which would be associated with scanning all files for potential viruses. High performance and security are top priorities here, but the price of virus scanning is just too high.
