### ISSUE TITLE
xboa proxy remote_ip config

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#655]
I just tried the xboa migrate feature and it worked flawlessly, except for one detail at the end:

The `xboa proxy o1 target-ip` command gave this message for each hosted domain:
    Dom is example.com
    INFO: site example.com proxy conversion on o1 complete

But ended with:
    nginx: [emerg] host not found in upstream "remote_ip" in /data/disk/o1/config/server_master/nginx/vhost.d/example.com:10
    nginx: configuration file /etc/nginx/nginx.conf test failed

After adding this to the example.com vhost, nginx reload worked. I guess this should go in a generic config file but I don't know which one:

    upstream remote_ip {
      server target-ip:80;
    }

Thanks for this excellent feature!

**Comment by omega8cc** [comment]
Hmm.. The `remote_ip` was not intended to be used as an `upstream` but as a placeholder to be replaced with target IP address here:

```
  location / {
    proxy_pass                 http://remote_ip;
```

Apparently we forgot to add the same logic we have used for `ssl-gen` while converting our own scripts to this simplified version.

```
  location / {
    proxy_pass                 http://target_ip;
```

**Comment by omega8cc** [comment]
Actually, it is there:

https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/xboa#L354

But it works only if the vhost exists:

https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/xboa#L349
https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/xboa#L255

So maybe something was worn with the vhost of the migrated site.

**Comment by omega8cc** [comment]
Ops, now I managed to confuse myself.

The https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/xboa#L354 line should use `remote_ip` and not `target_ip`, or we should sync it with the proxy template
