### ISSUE TITLE
[newrelic] newrelic.license not replaced in php ini files

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#656]
After upgrading to BOA-2.4.1, `newrelic.license = "REPLACE_WITH_REAL_KEY"` in all php ini files is not updated with the actual license key. 

```
_THIS_FILE=/opt/php${e}/etc/php${e}.ini
_THIS_FILE=/opt/php${e}/lib/php.ini
```

The sed statement at https://github.com/omega8cc/boa/blob/master/lib/functions/php.sh.inc#L68 do not contain the replacement value `$_NEWRELIC_KEY`

`echo newrelic.license = "REPLACE_WITH_REAL_KEY" | sed "s/REPLACE_WITH_REAL_KEY/$_NEWRELIC_KEY/g" | sed "s/license_key=//g"`

**Comment by omega8cc** [comment]
This is by design, since license key is now managed on the Octopus instance level:

https://github.com/omega8cc/boa/blob/master/aegir/conf/fpm-pool-foo.conf#L27

**Comment by omega8cc** [comment]
Check also: https://omega8.cc/how-to-use-new-relic-apps-monitoring-335

**Comment by pricejn2** [comment]
Understood. I should have noted that I'm not having any issues with New Relic, but wasn't sure if this was intentional or not. Thanks!
