### ISSUE TITLE
Info request re MIGRATE xboa using existing not-empty remote octopus platform?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#657]
Hello,

I am excited to test the new xboa migrate feature. You state that " No Octopus instance is needed on the target system prior to migration." . My questions is, CAN the octopus instance of the same name exist on the new remote server, and can there be existing sites on the remote octopus instance, and the source sites being transferred are simply added to the remote existing octopus instance? Will this also work? Thank you for your clarification.

Ed

**Comment by omega8cc** [comment]
While you could do this (and thus skip the `xboa create o1 target-ip` step), it is potentially dangerous, because two things will happen anyway:

1. Hostmaster database on the target will be replaced with database from source (not merged)
2. If there are platforms and sites using the same paths, their files will be overwritten (data loss)

If all platforms use different paths on source and target, then the second problem doesn't apply, but you will still need to add all platforms existing already on target again after the migration, so Aegir could import them and associated sites to make them visible in Hostmaster again.

**Comment by EdNett** [comment]
In this case then, I want to remove my o3 instance on my vps so that it can be empty in case I want to move all sites to it with this migrate feature. When following your instructions about removal of an octopus instance, I am still left with the directory o3, a subdirectory called .drush and the php.ini file inside that directory that I cannot delete, even when trying to force, even when ignoring, etc.  What is the proper way to remove these last 2 directories and 1 file, please? (I assume that they should be removed?). I am trying to remove them as root and the error message is that I don't have permission to do that.

Thank you.

**Comment by omega8cc** [comment]
You need to unlock every such file and then its parent directory with:

`chattr -i /path/to/file/or/directory`
`rm -rf /path/to/file/or/directory`

**Comment by EdNett** [comment]
Thank you for this info - those commands did allow me to remove the o3 instance completely - or so I thought.  I found that the file /opt/php55/etc/pool.d/o3.conf still remained, and this caused php55-fpm to stop working, and fail to initialize and re-start. (This actually happened on another server on which I removed the o1 octopus instance, and the o3 instance sites were down. . on that server I had the error message:

server1:~# service php55-fpm restart
Gracefully shutting down php55-fpm../etc/init.d/php55-fpm: line 78: kill: (25771) - No such process
..... failed. Use force-quit
Starting php55-fpm..[01-Apr-2015 17:38:36] ERROR: [pool o1] the prefix '/data/disk/o1' does not exist or is not a directory
[01-Apr-2015 17:38:36] ERROR: failed to post process the configuration
[01-Apr-2015 17:38:36] ERROR: FPM initialization failed
 failed)

So, I think that adding this note about removing the pool.d/octopus instance conf file is a good idea to instructions on how to fully remove an octopus instance.

I think many people are going to want to completely remove an octopus instance, so that they can have recourse to the new migrate feature.  I'd be willing to write up a hot to do this, if you'd let me know where to post it, and check it for ommissions and/or inaccuracies?

Best regards,

Ed

**Comment by omega8cc** [comment]
There is a wiki entry about this already: https://github.com/omega8cc/boa/wiki/How-To-Delete-An-Octopus-Instance

**Comment by EdNett** [comment]
I added the instructions to remove the o1.web user and its home directory to the wiki page at:
https://github.com/omega8cc/boa/wiki/How-To-Delete-An-Octopus-Instance

Thank you.

**Comment by omega8cc** [comment]
Thank you.
