### ISSUE TITLE
 Warning: file_exists(): open_basedir restriction in effect. 

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#658]
Hi all,

I am getting this warning on numerous pages - any ideas please? is it a BOA issue?

Thanks...

    Warning: file_exists(): open_basedir restriction in effect. File(sites/all/themes/atif/../../../css/atif.styles.css) is not within the allowed path(s): (.:/data/disk/o1/distro:/data/disk/o1/static:/data/disk/o1/aegir:/data/disk/o1/platforms:/data/disk/o1/backup-exports:/home/o1.web/.tmp:/home/o1.web/.aws:/data/all:/data/disk/all:/data/conf:/var/second/o1:/mnt:/srv:/usr/bin:/opt/tika:/opt/tika7:/opt/tika8:/opt/tika9:/opt/php53:/opt/php54:/opt/php55:/opt/php56) in panels_renderer_standard->add_meta() (line 416 of /data/disk/o1/distro/002/commerce-2.21-7.34.1/sites/all/modules/panels/plugins/display_renderers/panels_renderer_standard.class.php).

/data/disk/o1/log/octopus_log.txt = http://pastebin.com/WBcH99QK
/root/.o1.octopus.cnf = http://pastebin.com/n9qKevae
/var/log/barracuda_log.txt = http://pastebin.com/bzufQJwA
/root/.barracuda.cnf = http://pastebin.com/zuNbGxQQ

**Comment by omega8cc** [comment]
Two suggestions:

1. Do not skip versions and always upgrade both barracuda and octopus
2. Do not use weird paths with directory traversal tricks like /../../../ because you can hit open_basedir

**Comment by Juc1** [comment]
@omega8cc - ok thanks. I did not intentionally create this weird path with " /../../../ "  but I think the problem was caused by symlinking my theme. I always symlink my themes to /data/disk/o1/static/themes without problems so I don't know what was different in this case. After using the theme itself instead of a symlink the open_basedir error message seems to have gone.
