### ISSUE TITLE
Importing to Aegir Boa

### ISSUE THREAD

**Issue by arbelaezjm** [omega8cc/boa#659]
Hello
Is it correct to do a site  import in aegir by this way ?
http://blog.donalddille.com/04/06/2013/importing-existing-dupal-7-websites-aegir
or the only correct procedure is this?

https://omega8.cc/import-your-sites-to-aegir-in-8-easy-steps-109

Thanks for this wonderful proyect

**Comment by omega8cc** [comment]
No, that how-to is not relevant in the BOA context. We recommend to use only official BOA docs.
