### ISSUE TITLE
Support more duplicity backends in backboa?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#663]
Duplicity supports many backends besides Amazon S3. Would it be possible for backboa to also support more backends?

If so I think especially these backends would be useful: 1) SSH (since it works with basically any server), 2) Swift (OpenStack object store, supported by multiple providers), 3) Mega (50 GB free storage).

P.S. duplicity 7.02 is out

**Comment by omega8cc** [comment]
This would add too much complexity we don't use and can't test enough to manage reliably. But you can use backboa as a base for custom scripts.

**Comment by ar-jan** [comment]
Fair enough. If I do I'll add it to the wiki.

**Comment by EdNett** [comment]
Hi ar-jan,

You might think of doing this with the free open source community edition of owncloud - version 8 is a very fine product. Sorry I am not a scripter.
