### ISSUE TITLE
Question: are o_contrib_seven modules being updated automagically even when SKYNET_MODE=off?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#664]
Hello,

I sshed into my boa 2.4.1 stable yesterday, Saturday, and noticed that there was a db update for the robotstxt  module. I had _SKYNET_MODE=OFF for the last update to 2.4.1 stable, which I did on March 13. I don't know if the db update comes from the March 13 up-stable (this would be suprising, since I had already checked for db updates, etc after the up-stable to 2.4.1), OR if this is an automagic update. If it is an automagic update, can those be stopped by setting _SKYNET_MODE=OFF? If yes, then this is a bug report.  (I just have to test everything on a test vps before allowing it onto the production server, that is why I can't go with _SKYNET_MODE.

Thank you. Will gist relevant logs and files.

**Comment by EdNett** [comment]
barracuda cnf file here: https://gist.github.com/EdNett/73a095fee0dbd16bdfae
octopus cnf file here: https://gist.github.com/EdNett/3058a93e527c06af7cc4

**Comment by EdNett** [comment]
barracuda log txt here: https://gist.github.com/EdNett/6c59a89b44dd75af3797
octopus log here: https://gist.github.com/EdNett/db9428100f1a169eddcd

**Comment by omega8cc** [comment]
No, BOA skynet never touches any codebase. The only exception was the drupalgeddon core patch. Even when you run octopus upgrade, it doesn't modify existing o_contrib.

**Comment by omega8cc** [comment]
Note that you force new platforms series on every octopus upgrade with:

```
_HOT_SAUCE=YES
_USE_CURRENT=NO
```

This is not needed normally.

Still, this doesn't touch any existing o_contrib on upgrade
