### ISSUE TITLE
Trying to upload a 150+MB file.  Recieve 413 Request Entity Too Large

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#665]
What is the correct method of altering the nginx vhost setting to allow uploading large files?
I thought I remember seeing this discussed a while back but couldn't find the article/issue.

Thanks,
Karu

**Comment by omega8cc** [comment]
I'm not a search engine! :)

**Comment by ar-jan** [comment]
I suppose that was #636.

**Comment by omega8cc** [comment]
Correct.
