### ISSUE TITLE
after upgrade client users can't use drush

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#666]
I did the upgrade following the steps:
    $ screen
    $ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
    $ barracuda up-stable
    $ barracuda up-stable system           (recommended on major upgrade)
    $ octopus up-stable all both
    $ bash /var/xdrago/manage_ltd_users.sh (recommended on major upgrade)
    $ bash /var/xdrago/daily.sh            (recommended on major upgrade)

and it worked fine.

Now logging in as a client user for the first time since then I see drush is unusable:
    o1.client:~$ drush
    Drush must have a writable cache directory; please insure that one of the following
    locations is writable: /home/o1.client,0
    Segmentation fault (core dumped)

o1 and o1.ftp can both use drush but client users can not.

cnf and log files here https://gist.github.com/ahillio/78a6eb3e8b8ad33267ad

thank you.

**Comment by omega8cc** [comment]
You need to wait 2-3 minutes after the upgrade until standard system configuration is activated again and then it should just work.

**Comment by ahillio** [comment]
Hi, thanks.  It was actually several days after the upgrade that I noticed this and it's still problematic.

**Comment by omega8cc** [comment]
Please try to run another upgrade then. This shouldn't happen. That said, we almost never test things on AWS and very rarely anything on Ubuntu, so maybe there is some OS or environment specific problem, but we support some Ubuntu systems remotely and we didn't see this anywhere. Maybe just re-create the client account?

**Comment by bserem** [comment]
I'm having the very same issue. Noticed this morning I tried to get a 'drush uli'.
I am getting this, even after updating to 2.4.1 today (and after running daily and ltd_users cron jobs):
```
$drush sa
Drush must have a writable cache directory; please insure that one of the following locations is writable: [error]
/home/srm.bserem,0
Segmentation fault
```

`srm.` is the name of the octopus instance.
and this is an ls -la
```
srm.bserem:~$ pwd
/home/srm.bserem
srm.bserem:~$ ls -la
total 20
drwx------ 5 srm.bserem users 4096 Mar 23 13:45 .
drwx--x--x 6 root       root  4096 Feb  7 19:13 ..
drwxr-sr-x 3 srm.bserem users 4096 Mar  9 04:05 .drush
drwx------ 2 srm.bserem users 4096 Feb  7 19:13 .ssh
drwxr-x--- 2 srm.bserem users 4096 Mar  5 21:52 incoming
lrwxrwxrwx 1 root       root    29 Mar 23 13:45 sites -> /data/disk/srm/clients/bserem
srm.bserem:~$
```

It is working fine for srm.ftp (o1.ftp equivalent) user.

This was a fresh setup with BOA 2.4.0 I did a couple of weeks ago.
It is a Debian system on Linode.

**Comment by omega8cc** [comment]
Hmm, I can't reproduce this.

**Comment by omega8cc** [comment]
Latest test shows the `.tmp` directory properly created.

```
quad:/home/o1.octopus963044# ls -la
total 20K
drwx------ 5 o1.octopus963044 users 4.0K Mar 23 15:44 ./
drwx--x--x 8 root             root  4.0K Mar 23 15:44 ../
drwxr-sr-x 3 o1.octopus963044 users 4.0K Mar 23 15:44 .drush/
lrwxrwxrwx 1 root             root    35 Mar 23 15:44 sites -> /data/disk/o1/clients/octopus963044/
drwx------ 2 o1.octopus963044 users 4.0K Mar 23 15:44 .ssh/
drwxr-sr-x 2 o1.octopus963044 users 4.0K Mar 23 15:44 .tmp/
```

**Comment by omega8cc** [comment]
Wait, what is `incoming` there?

**Comment by bserem** [comment]
A folder I have for pushing stuff through scp. I'm migrating my sites to this new BOA and in there I'm sending the db dumps and /files folder of each site.

I created this a couple of weeks ago. Don't really use it anymore but I keep it in case I have to send something.

**Comment by bserem** [comment]
btw the above folder was created and chowned as root. This is the only thing that is "non BOA" in this configuration, everything else is standard boa with
`boa in-stable .... ... none`
(notice the none, I asked for no platforms)

**Comment by ahillio** [comment]
I ran through the upgrade procedure again and still get the same
  Drush must have a writable cache directory; please insure that one of the following
  locations is writable: /home/o1.client,0
  Segmentation fault (core dumped)

So I created a new client and changed the ownership of a couple test sites to that new client and drush works there with newly created client.  So thank you for that advice.

**Comment by omega8cc** [comment]
Well, it seems that we have fixed the underlying problem while working on a hot-fix: https://github.com/omega8cc/boa/commit/694d2185a5600f18e06b6d653c59c8510870d483
