### ISSUE TITLE
Manage caching

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#670]
Hello
I am running boa for a while now and i really appreciate the speed it allows for my hosted sites. However, i would like on some actions refresh some blocks on a site i regularly publish articles. The frontpage slider does not display directly the new articles, it does it after a while like 30 minutes. Also any change applied on the page after publishing it not be displayed unless i completely empty the cache with drush and by taping the following : 
/etc/init.d/redis-server stop
killall -9 redis-server
rm -f /var/run/redis.pid
rm -f /var/lib/redis/*
/etc/init.d/redis-server start

Is there a way to display changes without completly emptying the cache ? 
Thanks

**Comment by theodorosploumis** [comment]
You can disable caching at all by using a site alias that contains "dev". But you should first read this article here https://omega8.cc/how-to-disable-all-caching-and-aggregation-115

**Comment by yazzou** [comment]
well. I want to keep the cache on my live site, just want to make sure the changes made on the news site are taken into account live. 
I have already read this page before asking. As i understand it, this is more for a dev version of the site, not for a production site where visitors come and need performance.

**Comment by omega8cc** [comment]
You could try these options, perhaps:

https://github.com/omega8cc/boa/blob/master/aegir/conf/default.boa_site_control.ini#L157
https://github.com/omega8cc/boa/blob/master/aegir/conf/default.boa_site_control.ini#L93
https://github.com/omega8cc/boa/blob/master/aegir/conf/default.boa_site_control.ini#L110
