### ISSUE TITLE
.tmp files have incorrect permissions.

### ISSUE THREAD

**Issue by matglas** [omega8cc/boa#673]
We have found all of our octopus instances have incorrect folder permisisons on the .tmp folder. We have not changed anything on that manually. Because of that files are unable to be uploaded.

I don't know the cause of that yet. A fix might be to change the directory to 777 but I can imagine that boa has some idea about that regarding seperating access based on the octopus instance that belongs to it.

**Comment by matglas** [comment]
This is the output of the directory permissions now. But `www-data` is not able to write into the directory now.

```
s1:/data/disk/c1/.tmp# ls -la
total 16K
drwxr-sr-x  3 c1   users 4.0K mrt 30 14:14 ./
drwx--x--x 25 c1   users 4.0K mrt 27 13:47 ../
-rw-rw-r--  1 root users    3 mrt 27 14:07 .ctrl.241stableU.txt
drwxrwsr-x  5 c1   users 4.0K mrt 30 02:58 cache/
```

Should the group permission not be set to the `c1` group here?

Is see changed to file perms on .tmp in 694d2185a5600f18e06b6d653c59c8510870d483. But I don't know if this is fixing anything or is the cause of the problem. I looks like that part is only run when a new users is created. But is does set the folder permissions to 2755 which is `u=rwx,g=rs,o=rx`.

**Comment by omega8cc** [comment]
These permissions and ownership are correct (if you run latest stable). There are three separate `.tmp` directories:

`/data/disk/o1/.tmp` -- used only by the Aegir backend tasks running as `o1` user
`/home/o1.web/.tmp` -- used by the web server / php-fpm only, running as `o1.web` user
`/home/o1.ftp/.tmp`-- used by your limited shell user only, so for everything Drush related

Please make sure you have upgraded both Barracuda and Octopus to latest stable and that the Octopus instance (php-fpm) is running as `o1.web` and not, for example `www53`.

**Comment by matglas** [comment]
Was something changed in the latest stable that affects the .tmp directory permissions in the /data/disks? Because there where setups where I tried to fix it by changing the directory permissions to 777 and that help out.

**Comment by omega8cc** [comment]
It could "help" only if you are still running some older BOA version. It was discussed in the issue queue already. In the future, please follow: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt so we don't need to guess anything and can just inspect the logs required. Thank you.

**Comment by matglas** [comment]
Thank you for your reply. I will read the CONTRIBUTING guidelines and work with them next time.
