### ISSUE TITLE
_PERMISSIONS_FIX=YES overwritten to NO

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#678]
I'm noticing on a BOA 2.4.1 system that `_PERMISSIONS_FIX=YES` in .barracuda.cnf keeps getting overwritten with `_PERMISSIONS_FIX=NO` (I said [here](https://github.com/omega8cc/boa/issues/677#issuecomment-89582830) that it was solved but I just checked and saw the setting was overwritten again.

This seems to happen in the update_agents() function, but prmfix.fixed.a282q.pid does exist:

    ls -la /var/xdrago/log/prmfix.fixed.a282q.pid
    -rw-r--r-- 1 root root 0 apr  4 06:03 /var/xdrago/log/prmfix.fixed.a282q.pid

(I'll be posting the config/log files).

**Comment by omega8cc** [comment]
Thanks. This has been fixed: https://github.com/omega8cc/boa/commit/7735767fc192737bab4bac5ceb26147b4e61b214

**Comment by omega8cc** [comment]
The hot-fix will overwrite your settings again, until there is non-version-specific `/var/xdrago/log/prmfix.pid` file, so you could create it, plus also `/var/xdrago/log/modfix.pid` to avoid this.

**Comment by omega8cc** [comment]
In fact, we should skip this step altogether for installs already upgraded to 2.4.1

**Comment by omega8cc** [comment]
OK, now really fixed.

**Comment by ar-jan** [comment]
Thanks!

**Comment by sluc23** [comment]
I'm having a similar issue now in BOA 3.2.2.
_PERMISSIONS_FIX=NO is daily overwritten with YES in /root/.barracuda.cnf

Is it possible any regression affects 3.2.2 on this issue?
