### ISSUE TITLE
Can't get the new plateform installed after upgrade

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#679]
Hello 
My sites are running under drupal 34.1 and would like them to be up to date. I have launched the upgrade on barracuda and octopus without seing the latest drupal versions appearing as plateforms. 
Here are my log files : 

https://gist.github.com/yazzou/9f149b2c408bad593346

Thanks
Yaz

**Comment by omega8cc** [comment]
New platforms are available in head only. You need to wait for BOA-2.4.2 release.
