### ISSUE TITLE
Override civicrm.settings.php with custom values?

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#680]
I need to set custom values in `civicrm.settings.php`

Is there a BOA-friendly way to do this so that it is preserved across migrations, etc?

Like a `local.civicrm.settings.php` or some such file?

**Comment by LunkRat** [comment]
Ignore this, I just noticed that the aegir-generated `civicrm.settings.php` is now including a site key, so I just need to go in there and look at it.

**Comment by LunkRat** [comment]
Is there documentation on this?

**Comment by LunkRat** [comment]
Is there a BOA way to set values in `civicrm.settings.php` without having them overridden by Aegir?

**Comment by omega8cc** [comment]
No, we don't have anything like that. Please consider a feature request in the https://www.drupal.org/project/provision_civicrm queue, where such request belongs.
