### ISSUE TITLE
Where to add the SSL redirect configuration snippet

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#681]
I followed docs/SSL.txt to get an SSL cert configured on a dedicated IP. 

I wanted a permanent redirect to https, so I followed the instructions at https://github.com/omega8cc/boa/blob/BOA-2.4.1/docs/SSL.txt#L63-L78

I created a _new_ file `/var/aegir/config/server_master/nginx/pre.d/example.com_pln_proxy.conf` and added this then edited for my domain name:

``` 
  ###
  ### Optional permanent redirect to HTTPS per domain/regex
  ###
  if ($host ~* ^(www\.)?((foo|bar)\.com)$) {
    rewrite ^ https://$host$uri? permanent;
  }
```

Then ran `service nginx restart`

But it reports:

```
[ ok ] Stopping Nginx Server...:.
[....] Starting Nginx Server...:nginx: [emerg] "if" directive is not allowed here in /var/aegir/config/server_master/nginx/pre.d/example.com_pln_proxy.conf:4
```

**Comment by omega8cc** [comment]
You should *not* create this file manually. It should be generated for you, as explained in the docs.

**Comment by LunkRat** [comment]
I suspected that; however the only file that was generated for me was:

`/var/aegir/config/server_master/nginx/pre.d/z_example.com_ssl_proxy.conf`

I don't have `/var/aegir/config/server_master/nginx/pre.d/example.com_pln_proxy.conf`

So it prepends `z_` to the domain name and creates it as `_ssl_proxy.conf` I didn't see anything about this in the docs. Do I add my if{} pseudo-location within the server{} configuration block of this file?

**Comment by omega8cc** [comment]
Then run the `xboa ssl-gen` again to get both files generated. The `pln` file will not be generated if you are using shared IP address, though, and `target_ip = dedicated_ip` in your `/root/.ssl.proxy.cnf`

**Comment by LunkRat** [comment]
Thanks for your explanation and for updating the docs. I understand the process better now.
