### ISSUE TITLE
BARRACUDA.sh.txt installer not available - try again later unable to upgrade to head or stable

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#683]
Hi, since yesterdays failed update after the latest dns fix, I am receiving this message.  I have never seen this error before, . /root/.barracuda.cnf does exist

base:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
STATUS: Skynet Agent is Active, OK!
STATUS: You can add the _SKYNET_MODE=OFF line in
STATUS: /root/.barracuda.cnf to disable me, if needed.

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
Bye

[ ok ] Reloading configuration files for periodic command scheduler: cron.
base:~# barracuda up-head

  BARRACUDA.sh.txt installer not available - try again later
  Make sure that required /root/.barracuda.cnf file also exists

**Comment by omega8cc** [comment]
If you have tried the upgrade while it was broken in head, try this:

`touch /root/.use.default.nameservers.cnf`
`barracuda up-head system`

**Comment by omega8cc** [comment]
This could be related to #685
