### ISSUE TITLE
lfd is blocking DNS traffic

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#685]
Hi, I have a linode VPS and this happened to me today (apparently) after upgrading to BOA 2.4.1. (following the upgrade instructions)

lfd is blocking DNS traffic as "port scanning". (false alarm)

Is there a way to whitelist linode resolvers to prevent future blocking? is there a way to better configure lfd to not block connections that actually it knows about?

Thanks

This an email example of the log:

>Time:    Tue Apr 14 12:05:00 2015 -0500
>IP:      72.14.188.5 (US/United States/resolver2.dallas.linode.com)
>Hits:    20
>Blocked: Temporary Block
>
>Sample of block hits:
Apr 14 12:03:44 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=160 TOS=0x00 PREC=0x00 TTL=63 ID=10575 PROTO=UDP SPT=53 DPT=64614 LEN=140
Apr 14 12:03:44 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=125 TOS=0x00 PREC=0x00 TTL=63 ID=10576 PROTO=UDP SPT=53 DPT=64614 LEN=105
Apr 14 12:03:54 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=160 TOS=0x00 PREC=0x00 TTL=63 ID=11795 PROTO=UDP SPT=53 DPT=64614 LEN=140
Apr 14 12:03:54 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=125 TOS=0x00 PREC=0x00 TTL=63 ID=11796 PROTO=UDP SPT=53 DPT=64614 LEN=105
Apr 14 12:04:03 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=87 TOS=0x00 PREC=0x00 TTL=63 ID=13050 PROTO=UDP SPT=53 DPT=61180 LEN=67
Apr 14 12:04:07 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=87 TOS=0x00 PREC=0x00 TTL=63 ID=13357 PROTO=UDP SPT=53 DPT=32219 LEN=67
Apr 14 12:04:09 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=160 TOS=0x00 PREC=0x00 TTL=63 ID=13547 PROTO=UDP SPT=53 DPT=14712 LEN=140
Apr 14 12:04:12 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=87 TOS=0x00 PREC=0x00 TTL=63 ID=14111 PROTO=UDP SPT=53 DPT=24755 LEN=67
Apr 14 12:04:13 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=87 TOS=0x00 PREC=0x00 TTL=63 ID=14329 PROTO=UDP SPT=53 DPT=61180 LEN=67
Apr 14 12:04:19 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=160 TOS=0x00 PREC=0x00 TTL=63 ID=15333 PROTO=UDP SPT=53 DPT=14712 LEN=140
Apr 14 12:04:22 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=87 TOS=0x00 PREC=0x00 TTL=63 ID=15566 PROTO=UDP SPT=53 DPT=24755 LEN=67
Apr 14 12:04:24 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=82 TOS=0x00 PREC=0x00 TTL=63 ID=16022 PROTO=UDP SPT=53 DPT=7247 LEN=62
Apr 14 12:04:27 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=90 TOS=0x00 PREC=0x00 TTL=63 ID=16112 PROTO=UDP SPT=53 DPT=27633 LEN=70
Apr 14 12:04:37 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=90 TOS=0x00 PREC=0x00 TTL=63 ID=18016 PROTO=UDP SPT=53 DPT=23682 LEN=70
Apr 14 12:04:37 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=90 TOS=0x00 PREC=0x00 TTL=63 ID=18094 PROTO=UDP SPT=53 DPT=27633 LEN=70
Apr 14 12:04:47 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=90 TOS=0x00 PREC=0x00 TTL=63 ID=19714 PROTO=UDP SPT=53 DPT=23682 LEN=70
Apr 14 12:04:47 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=203 TOS=0x00 PREC=0x00 TTL=63 ID=19750 PROTO=UDP SPT=53 DPT=11076 LEN=183
Apr 14 12:04:52 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=87 TOS=0x00 PREC=0x00 TTL=63 ID=20592 PROTO=UDP SPT=53 DPT=28455 LEN=67
Apr 14 12:04:52 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=160 TOS=0x00 PREC=0x00 TTL=63 ID=20668 PROTO=UDP SPT=53 DPT=3861 LEN=140
Apr 14 12:04:52 kronos kernel: Firewall: *UDP_IN Blocked* IN=eth0 OUT= MAC=f2:3c:91:73:95:75:84:78:ac:5a:0b:41:08:00 SRC=72.14.188.5 DST=69.164.201.85 LEN=125 TOS=0x00 PREC=0x00 TTL=63 ID=20669 PROTO=UDP SPT=53 DPT=3861 LEN=105`

**Comment by omega8cc** [comment]
It is a known issue caused by CSF latest version incompatibility with the config template used in BOA stable. To fix the problem, please update the csf config manually:

`csf -x`
`csf -uf`
`csf -e`

**Comment by omega8cc** [comment]
We should stop using csf direct download and use our tested copy, I think, to avoid such serious problems in the future.

**Comment by yaazkal** [comment]
Hi, thanks a lot. I will see if anything else happens.

I don't know if this is also related with this other issue that I'm having with CiviCRM after the upgrade (both BOA and CiviCRM) http://forum.civicrm.org/index.php/topic,36325.0.html

I post it first there hoping that it is a CiviCRM issue, but also last night I was unable to send mails trough mandrill as I always do (long time out).

Let me know if I must create another issue here if you thing is from from BOA than from CiviCRM.

**Comment by chriscroome** [comment]
csf/lfd is clearly not free software (as in https://www.fsf.org/ approved, rather than cost), it isn't clear to me if they allow other people to distribute modified versions? 

    3.  SCOPE OF LICENCE
    
        3.1     You shall not:
    
                3.1.1   modify, adapt, merge, translate, decompile, 
                disassemble, or reverse engineer the Product, except as 
                permitted by law; or

http://download.configserver.com/csf/license.txt
http://www.configserver.com/cp/csf.html

**Comment by omega8cc** [comment]
The CiviCRM issue is not related here. You may need to increase default values in the /etc/mysql/my.cnf

**Comment by omega8cc** [comment]
@chriscroome We don't modify, don't include and don't redistribute csf/lfd. BOA just installs it as-is, with some configuration only related changes.

**Comment by yaazkal** [comment]
@omega8cc Partially.
I just send a test mail again and now it works :) So this issue also affects the SMTP function in Civi.
Will check again the MySQL issue to see if (maybe) it was related too.

**Comment by chriscroome** [comment]
Fair enough, I just got the impression that you were considering doing that based on "We should stop using csf direct download and use our tested copy", sorry for misunderstanding.

Incidently csf/lfd blocked the Google DNS server, 8.8.8.8 on the BOA server I manage, see https://trac.transitionnetwork.org/trac/ticket/843

**Comment by omega8cc** [comment]
@chriscroome We just need to stop downloading it directly on every install and upgrade to avoid such serious bugs they may introduce. We will use our private download mirrors, just as we do with everything else.

**Comment by omega8cc** [comment]
We will also force live self-update on every barracuda and boa scripts run, to make sure that this doesn't happen again. This obviously means that our mirror will be used only during barracuda and boa run, while before and after the system will force an extra auto-upgrade to latest version from the source site. This is still not ideal, but better than allowing to use outdated configuration.

**Comment by omega8cc** [comment]
The hot-fix has been applied to meta installers, so it now protects both legacy, old stable and next stable BOA installs.

**Comment by ar-jan** [comment]
Is this fully fixed? I ran `cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt` to make sure, but I still have firewall problems. I've also done the manual update with csf -x, csf -uf, and csf -e.

Here's an example when I try do download a patch from drupal.org:

    wget https://www.drupal.org/files/issues/geshi_filter-decode_entities-2047021-12.patch
    --2015-04-15 17:27:31--  https://www.drupal.org/files/issues/geshi_filter-decode_entities-2047021-12.patch
    Resolving www.drupal.org (www.drupal.org)... 93.184.220.99
    Connecting to www.drupal.org (www.drupal.org)|93.184.220.99|:443...

    tail -f /var/log/syslog:
    Apr 15 17:28:35 boa kernel: [40958.624177] Firewall: *TCP_OUT Blocked* IN= OUT=eth0 SRC=MY.IP.ADD.RESS DST=93.184.220.99 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=24658 DF PROTO=TCP SPT=27308 DPT=443 WINDOW=29200 RES=0x00 SYN URGP=0 UID=997 GID=100

**Comment by yaazkal** [comment]
Hi @ar-jan I guess it will be included in 2.4.2 (this issue was just a few hours ago) so I don't think it is included in the file that you are downloading.

The manual fix works.

**Comment by omega8cc** [comment]
We have added the fix also in BOA.sh.txt, but you may need to run another upgrade (stable) if your pdnsd config is also broken for some reason.

**Comment by kunago** [comment]
I also started experiencing this issue few days ago, meaning my server blocking 8.8.8.8 etc. This line, if placed in */etc/csf/csfpre.sh* however fixed it all for me:

`/sbin/iptables -I INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`
