### ISSUE TITLE
Disable OPcache when accessing .dev. mode

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#687]
Is it possible to disable PHP OPcache when accessing the web site as *.dev.* alias?
Would be very helpful when developing/debugging web sites!

**Comment by bserem** [comment]
This issue has been discussed again in the past. Opcache is set to 1sec (instead of 60) when accessing the site from a .dev. alias.
You can check this by visiting php settings in: admin/reports/status/php
and search for "revalidate_freq".

**Comment by ixiam** [comment]
ok, thanks for the reply!
