### ISSUE TITLE
BOA.sh.txt disables csf and lfd on each run

### ISSUE THREAD

**Issue by kunago** [omega8cc/boa#688]
I have recently discovered my system keeps disabling csf and lfd every single hour, the traces were found in */var/log/lfd.log*.

Digging into it I found out the clear.sh running every hour is to blame, BOA.sh.txt its checks. The function **check_fix_csf** in BOA.sh.txt does this:
1. removes all IPs permanently denied
2. removes all IPs temporarily banned
3. adds omega8cc servers to allowed IPs
4. disables csf and lfd entirely
5. updates csf

However, it does not reenable csf and lfd. If those commands are run individually, the csf update says:
*Restarting csf and lfd...
csf and lfd have been disabled, use 'csf -e' to enable
Stopping lfd: Done
Starting lfd:csf and lfd have been disabled
Done*

csf and lfd then stay disabled until another cron that checks their status reenables them. Maybe it's a change in csf and lfd scripts themselves but unless reenabled by `csf -e`, it stays off and leaves a server vulnerable.

**EDIT**: SKYNET mode, even though not directly responsible, still needs to be enabled for this to be happening.

**Comment by kunago** [comment]
Apart from this, is there any need for csf to clear all *denies* and *temporary bans* every hour? csf can be configured not to store more than *n* IPs in csf.deny so this may not be fully useful to truncate all malicious IPs as soon as they get blocked.

**Comment by omega8cc** [comment]
It was intended as a temporary workaround for much more serious issue where the csf firewall was able to block its own outgoing connections considering them as remote port scans.

For some context please check #685
