### ISSUE TITLE
Unable to "enable access log"

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#689]
In /admin/config/system/statistics in any site hosted on BOA (custom "static" platform or BOA distro platform, a few different 7.x releases and profiles), I am unable to enable the Access log settings checkbox "Enable access log".

Is this prevented by the BOA platform (assume reason due to caching mechanism or similar)?

I'm using ip_geoloc module in a project and requirement is to store Anon user session info to store IP address and reverse geocode.

**Comment by omega8cc** [comment]
It is disabled by default with this line:

`$conf['statistics_enable_access_log'] = 0;   // Disable access log stats`

The reason is simple: it is useless when you have Speed Booster (nginx micro caching) layer in front of the Drupal backend.

**Comment by omega8cc** [comment]
You could disable Speed Booster per site, if you wish, and force `$conf['statistics_enable_access_log'] = 1;` in the `local.setiings.php`, though. Just make sure you understand that it will result with the lack of performance benefits and DoS protection provided by the Speed Booster cache layer.

**Comment by omega8cc** [comment]
For more details and code examples please check also: https://omega8.cc/node/108
