### ISSUE TITLE
weak cipher suites

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#690]
Chromium browser is reporting that one of our sites is using "obsolete encryption".  These ciphers are reported as weak
  TLS_ECDHE_RSA_WITH_RC4_128_SHA
  TLS_RSA_WITH_RC4_128_SHA
  TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
  TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
  TLS_RSA_WITH_3DES_EDE_CBC_SHA

Are these installed by BOA?  Is there a way I can update to stronger ciphers?

In case it's relevant BOA is installed on Amazon instance of Ubuntu, cnf and log files: https://gist.github.com/ahillio/78a6eb3e8b8ad33267ad

**Comment by chriscroome** [comment]
For what is it worth the guide to cipher suites I use is the Mozilla one: https://wiki.mozilla.org/Security/Server_Side_TLS 

The Intermediate compatibility list, https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29 is probably still the best one to use in case clients have old browsers, if the site is for people you know to have new browsers then the modern list would be fine.

**Comment by omega8cc** [comment]
This will be automagically "fixed" by #545

**Comment by omega8cc** [comment]
As for "obsolete encryption", you may also need to re-issue your SSL certificate so it uses SHA-2 algorithm: https://www.sha2sslchecker.com
