### ISSUE TITLE
How can I access Chive as root on self-hosted install

### ISSUE THREAD

**Issue by lsolesen** [omega8cc/boa#693]
For unknown reasons one of my sites on a platform has been dropped. It is in the Aegir interface, backups are listed, and when I go into the platform using SSH I can find the sites on my platform. However, only local.settings.php and settings.php are visible in the directory of the sites. And when going to /backups the reported backup is not really available. Therefore I wanted to go to the database to see whether there is some actual data there, I could recover from. Is it possible to get in there as root. I do not have a drushrc.php with credentials in the sites directory as expected.

**Comment by omega8cc** [comment]
Please check `/root/.my.cnf`
