### ISSUE TITLE
csf from server to outside world

### ISSUE THREAD

**Issue by danielbeeke** [omega8cc/boa#698]
Since a couple of upgrades we have to whitelist services that we call, google geocoder, mollie payments servers etc. Is this by design? Is it possible to turn off, if adviced? We have it on multiple servers.

https://gist.github.com/danielbeeke/72e198911070219a9980

**Comment by omega8cc** [comment]
You can modify CSF configuration to open extra ports and then use `_CUSTOM_CONFIG_CSF=YES` variable to protect customized configuration: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L79

**Comment by omega8cc** [comment]
Also, there were known issues with CSF in 2.4.1, as reported in the queue. Please upgrade to 2.4.2 as soon as possible.
