### ISSUE TITLE
Upgrade Drupal 7 platforms to 7.37

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#700]
We need to include expected new core. For details see: https://groups.drupal.org/node/468043

**Comment by EdNett** [comment]
Feature Request for 2.4.3

Would you consider also letting us add 8-beta-10 and dev once again. There is now a beta-to-beta project:

https://www.drupal.org/project/head2head

Thank you

**Comment by omega8cc** [comment]
Not this time. Please read about our D8 support policy: https://omega8.cc/page/supported-drupal-platforms-161
