### ISSUE TITLE
Broken pdnsd configuration breaks DNS resolver

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#701]
When trying to upgrade, the upgrade hangs on INFO: Running system packages update...
Temporarily disabling csf does not fix this.
It seems related to csf issues in BOA 2.4.1, where we had to whitelist ip-adresses used for drush dl etc.

**Comment by omega8cc** [comment]
There is no 2.4.3 yet. If disabling firewall doesn't fix the problem, then it suggests a problem with pdnsd and/or DNS resolver.

Please attach your `/etc/pdnsd.conf`and `/etc/resolv.conf` files.

Please also let us know your host (provider) name.

**Comment by florisvanwoudenberg** [comment]
pdnsd.conf: https://gist.github.com/florisvanwoudenberg/de1a97e03f8e14df3a32
resolv.conf: 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search sohosted-vps.nl

The server hostname is server3.aegirhosting.nl
Domain is hosted at Transip
VPS is hosted at Sohosted

**Comment by omega8cc** [comment]
It is `/etc/pdnsd.conf` broken. You probably have `/root/.use.local.nameservers.cnf`file.

Please run this:

```
rm -f /root/.use.local.nameservers.cnf
touch /root/.use.default.nameservers.cnf
rm -f /etc/resolv.conf
echo "nameserver 8.8.8.8" >/etc/resolv.conf
echo "nameserver 8.8.4.4" >>/etc/resolv.conf
barracuda up-stable system
```

**Comment by omega8cc** [comment]
We should detect such broken `/etc/pdnsd.conf` and fix it on the fly, also when `/root/.use.local.nameservers.cnf` exists or `/root/.use.default.nameservers.cnf` doesn't exist.

**Comment by florisvanwoudenberg** [comment]
Thanks.
In this case there is one other thing that seems to cause the freeze:
We have an extra ip-adres added to the server.
ater ifdown eth0:0 the upgrade completed.
Do not know how exactly this is related.

**Comment by omega8cc** [comment]
This could be just a coincidence, perhaps. No idea.

**Comment by florisvanwoudenberg** [comment]
As an addition to this: I also had to change the DNS in /var/spool/postfix/etc/resolv.conf
Different DNS in /etc/resolv.conf and /var/spool/postfix/etc/resolv.conf seem to block postfix sending mail.

**Comment by omega8cc** [comment]
Interesting. I guess we should watch/update also `/var/spool/postfix/etc/resolv.conf` when needed.

**Comment by petrowsky** [comment]
I also did an update to 2.4.3 just a few days ago. Still running squeeze :( Postfix stopped sending.

Saw this in the log
```
Jun  1 14:30:56 s1 postfix/postfix-script[28225]: warning: /var/spool/postfix/etc/resolv.conf and /etc/resolv.conf differ
Jun  1 14:30:56 s1 postfix/postfix-script[28231]: warning: /var/spool/postfix/lib/libnss_nis-2.11.3.so and /lib/libnss_nis-2.11.3.so differ
Jun  1 14:30:56 s1 postfix/postfix-script[28233]: warning: /var/spool/postfix/lib/libnss_hesiod-2.11.3.so and /lib/libnss_hesiod-2.11.3.so differ
Jun  1 14:30:56 s1 postfix/postfix-script[28235]: warning: /var/spool/postfix/lib/libnss_files-2.11.3.so and /lib/libnss_files-2.11.3.so differ
Jun  1 14:30:56 s1 postfix/postfix-script[28237]: warning: /var/spool/postfix/lib/libnss_compat-2.11.3.so and /lib/libnss_compat-2.11.3.so differ
Jun  1 14:30:56 s1 postfix/postfix-script[28239]: warning: /var/spool/postfix/lib/libnss_dns-2.11.3.so and /lib/libnss_dns-2.11.3.so differ
Jun  1 14:30:56 s1 postfix/postfix-script[28241]: warning: /var/spool/postfix/lib/libnss_nisplus-2.11.3.so and /lib/libnss_nisplus-2.11.3.so differ
```

This was in /etc/resolv.conf
```
domain members.linode.com
nameserver 72.14.188.5
nameserver 72.14.179.5
nameserver 8.8.8.8
nameserver 8.8.4.4
```
Looks like linode injected their own name servers when I updated?

**Comment by omega8cc** [comment]
Maybe. But this line is interesting:

>> /var/spool/postfix/etc/resolv.conf and /etc/resolv.conf differ

What is the contents of `/var/spool/postfix/etc/resolv.conf` ?

**Comment by petrowsky** [comment]
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
```
Curl also was not working so it led me to believe it was the firewall again related to https://github.com/omega8cc/boa/issues/685 after following the fix for csf there curl started working, but I'm still working on getting postfix to resolve and flush the queue.

**Comment by petrowsky** [comment]
mail.log is generating warnings like such.

(Host or domain name not found. Name service error for name=gmail.com type=MX: Host not found, try again)

**Comment by petrowsky** [comment]
In attempting to solve any issue with pdnsd I restarted the service and got this.

```
s1:~# service pdnsd restart
Stopping pdnsd.
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf
Starting pdnsd.
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf
```

**Comment by petrowsky** [comment]
In my case, /etc/resolv.conf was no longer a symlink as such
```
resolv.conf -> /etc/resolvconf/run/resolv.conf
```
I had to reconnect it, but the following looked ok.
```
root@s1:/etc/resolvconf/resolv.conf.d# tail  /etc/resolvconf/resolv.conf.d/*
==> /etc/resolvconf/resolv.conf.d/base <==

==> /etc/resolvconf/resolv.conf.d/head <==
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

==> /etc/resolvconf/resolv.conf.d/original <==
nameserver 8.8.8.8
nameserver 8.8.4.4

==> /etc/resolvconf/resolv.conf.d/tail <==
```
I couldn't get postfix to send out until I added the following to /etc/network/interfaces
```
  dns-search members.linode.com
  dns-nameservers 8.8.8.8 8.8.4.4
```
I haven't ever had an explicit name server on my interfaces but in my case it got things working again.

After an ifdown/ifup and resolvconf -u things started working again.

I checked out another server I have running BOA-2.4.3 for comparison and I don't have dns servers in the interface explicitly. It's running wheezy and working just fine with a resolve.conf as such.
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search members.linode.com
```
Maybe Linode VPS's have to use their DNS servers?

**Comment by omega8cc** [comment]
As I have said before, we should really add an auto-sync between `/var/spool/postfix/etc/resolv.conf` and `/etc/resolv.conf` but we have stopped testing Squeeze, so we didn't catch these issues. Not sure about Linode specific behavior, though.

**Comment by omega8cc** [comment]
Some Postfix processes are running in a chroot environment by default. Therefore Postfix startup script copies some required files automatically to `/var/spool/postfix/etc/`. We just need to restart Postfix if we modify anything in the system DNS: `/etc/hosts`, `/etc/resolv.conf` etc.
