### ISSUE TITLE
Support for Debian 8 Jessie

### ISSUE THREAD

**Issue by attiks** [omega8cc/boa#702]
Is this already supported?

**Comment by omega8cc** [comment]
Not yet.

**Comment by attiks** [comment]
I should have been more clear:

- did you test it yet?
- any ETA?

**Comment by omega8cc** [comment]
1. No.
2. https://github.com/omega8cc/boa/milestones/2.4.4

**Comment by pricejn2** [comment]
+1 Looking forward to this!
