### ISSUE TITLE
Sites with CiviCRM cannot be cloned in BOA 2.4.2

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#703]
When cloning a site with CiviCRM, I fails with this error in the log:

Found database dump at /data/disk/o1/distro/001/drupal-7.34.1-dev/sites/testcopy.o1.boa.example.nl/database.sql.
Database dump at /data/disk/o1/distro/001/drupal-7.34.1-dev/sites/testcopy.o1.boa.example.nl/database.sql is readable
Importing database using command: mysql --defaults-file=/dev/fd/3 testcopyo1boa
Database import failed: ERROR 1227 (42000) at line 1746: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
Returned from hook drush_db_provision_deploy

I believe this is a recent problem, probably since BOA 2.4.2. About two weeks ago I could still clone one of the same sites without problems. It occurred on a site with CiviCRM 4.5.7 and one with 4.6.2 (on different servers). Sites without CiviCRM can still be cloned.

Is there a way to inspect the database dump of a failed clone to see what statement there is around that line number? It seems likely it'll be something to do with MySQL views or security definers etc.

**Comment by omega8cc** [comment]
It is a known problem with recent Aegir Provision 3.x refactoring: https://www.drupal.org/node/2479885

**Comment by omega8cc** [comment]
This fixed the problem: https://github.com/omega8cc/provision/commit/260505e19b095d49af00c0a08b2659096eec14c2
