### ISSUE TITLE
Migration problems

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#704]
I am trying to migrate octopus "o3" and both server and the vps have an existing "o1". Both are wheezy, boa stable 2.4.2 and use php 5.6 only.

Following the instructions in migration, I receive the error message "_USR o1 is not elgible for migration: broken"

at the step: xboa import o3 target-ip

I also notice that in /var/xdrago/

5 cron scripts have had a "." added to their front and a ".off" added to their end, so that 
daily.sh becomes .daily.sh.off

restarting cron does not change these files back to their original names. 

even when restarting the server they do not revert to their names, and the sites in the other octopus instance (NOT the one I am trying to transfer) - no tasks are being run in the octopus UI.

So I will rename the 5 files back to their original names, restart cron, and run the cron run manually to see if things start working again. - This did indeed get the tasks running again on the original (existing) octopus instance on the target server.

The production sites on the source server never stopped working but the octopus UI site did go into maintenance mode - it's the sites on the target server's existing octopus instance that will have problems, I believe, if cron isn't set to run again, and they are all read-only now.

This is all running php 5.6 on both target and host for both barracuda and octopus, and of course both boa 2.4.2 stable.

The only unusual fact is that the source is a full server, while the target is a vps - both running debian 7 x64

**Comment by EdNett** [comment]
When I try to run 

bash /var/xdrago/run-o3  I receive the error/message:

no passwd entry for user 'o3'

**Comment by EdNett** [comment]
barracuda_log.txt at:
https://gist.github.com/EdNett/26edcd256f5e7ac87681

octopus_log.txt:
https://gist.github.com/EdNett/f11756cf6af93b5daedc

barracuda_cnf at:
https://gist.github.com/EdNett/159c4f2e886399ccc4c3

octopus_cnf at:
https://gist.github.com/EdNett/abdcc90d96ed19d3c250

Lastly, do you recommend that we run xboa post-mig on both servers in the case of a failed migration? OR, could that cause problems? Wouldn't want to lose data or change any cofig or system settings in or on the source server.

**Comment by EdNett** [comment]
FYI:  Last but not least (LBNL):

IWhen I try to add content to the main site (main domain) on this failed migrate target  - I receive the error: no content types defined, even though there are 5 content types defined, and 2 in use on this multilingual site. [I upgraded to drupal 7.27 and to i18n 1.13 latest stable after doing the failed migrate, and before discovering the error] So, I do not know if the error results from updating drupal or i18n - or is a result of the failed migration. I did run xboa mig-post on both target and source server after the failed upgrade.

Additionally, I do not have the "no content types defined" error on the source server (of the failes migrate) - only on the target server (which is a vps).

I reported this error / bug / issue on the drupal project page at:
https://www.drupal.org/node/2485527

**Comment by omega8cc** [comment]
There is nothing broken in the xboa script or anywhere on the BOA side. Migration moves codebase and sites with their databases as-is, so you are probably looking at the wrong place to find the source of your problems.

>> no passwd entry for user 'o3'

This only means that you have not used proper instance names.

We have run this procedure in some giant batches for thousands of instances and we have never experienced any such problems, while the script was not modified in the meantime.

I would recommend to strictly follow the procedure and run clean migration again.

Just make sure to run barracuda and octopus upgrade on the source system and re-verify all sites to restore their local vhosts.

**Comment by EdNett** [comment]
Hello,

The migration attempt is still failing at the step:

@=> On the source-host
  xboa create o1 target-ip

Instead of using "o1", I am using the platform name of my source octopus instance that I wish to move to the target server which is a 4 letter word followed by one number. 

There error message I receive states that _USR xxxx3 already exists and it cannot be created. (of course it does exist on the source server where I am issuing the command)
This is the script I am using to do the migrate:
https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

and when on the source server (the server with the existing octopus instance that is to be moved to the target server) the command

xboa create o1 target-ip  is suppossed to create an octopus instance named o1 on the target server (even though I am NOT connected via ssh to the target server at that time)? Well, I believe that the script is simply trying to create the octopus instance o1 on the source server (where it already exists, of course) and is returning the error message _USR o1 cannot be created. Already exists. 

What do you mean that I "have not used proper instance names"? (your comment above). I didn't know there were rules about "proper instance names" and I have been suing this name installing new and upgrading octopus instances for many years.

**Comment by EdNett** [comment]
As far as I am concerned this is broken. UNLESS you have suddenly, without warning, decided to only allow octopus user names which contain the letter "o" and are followed by a number...  We have been using octopus usernames like "fred3" and "fred1"  for 3 years now without any problems. COuld you please respond to our querry above about "what does proper instance names" mean, please?

Thank you.

**Comment by omega8cc** [comment]
You can't use `xboa create` when the instance with the same name already exists on the target. You need to skip this step, obviously.
