### ISSUE TITLE
Feature request: ability to add a _DB_NAME= to remove a db from sql optimisations in daily/weekly .sh

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#706]
I run one application on boa servers which uses myisam. Could we have the ability in the barracuda file to list databases by their name that we do NOT want the daily and weekly scripts to "fix"?

Ed

**Comment by omega8cc** [comment]
If you don't want the global option, use the platform and site level INI files instead, as explained in the built-in docs: https://github.com/omega8cc/boa/blob/master/aegir/conf/default.boa_platform_control.ini#L274
