### ISSUE TITLE
Consider using http header X-Frame-Options SAMEORIGIN

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#708]
We were having problems with saving Panel panes on one of our sites, with this error:

    An AJAX HTTP request terminated abnormally.
    Debugging information follows.
    Path: /system/ajax
    StatusText: 
    ResponseText: 
    ReadyState: 4

Following [this comment](https://www.drupal.org/node/1232416#comment-9553235) in the Drupal core issue, we added `drupal_add_http_header('X-Frame-Options', 'SAMEORIGIN');` which solved the problem. Maybe it's worth it to add this on the Nginx level?

**Comment by omega8cc** [comment]
I believe there is a module to add such header per site. I don't think that we should add it by default, because it will break sites which do this or allow by design.
