### ISSUE TITLE
Support views autorefresh

### ISSUE THREAD

**Issue by thebennos** [omega8cc/boa#709]
Hey
I run in to some problems with 
https://www.drupal.org/project/views_autorefresh

I want to use a simple ping script(see example in the module). 
The ping script (like ping.php) bypass the drupal bootstrap und provides a json respsone for the module. 

Problem is that I can get the ping script working on boa. I get a 404 error. 
I looked at the vhost template file, everything is blocked. 

Maybe you can give me some advice or a vhost config to get the ping script working.

**Comment by omega8cc** [comment]
You would need to extend default configuration by adding whitelisted php file. Take a look at the location for `/cron.php` in the `nginx_vhost_common.conf` and add similar for `/ping.php` in the extra config include as explained in https://github.com/omega8cc/boa/blob/master/docs/HINTS.txt

**Comment by omega8cc** [comment]
Or use already whitelisted `/rtoc.php` filename.

**Comment by omega8cc** [comment]
Or even also whitelisted `/boost_stats.php`
