### ISSUE TITLE
After Migrate / Clone some civicrm.settings.php variables are blank

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#713]
Tested in BOA 2.4.2 and BOA 2.4.3-dev
After Migrating / Cloning sites these variables in civicrm.settings.php are empty in the new web site.

define( 'CIVICRM_UF_BASEURL'      , '' );

define( 'CIVICRM_SITE_KEY', '' );

**Comment by omega8cc** [comment]
It looks like a provision_civicrm problem/regression, I think.

**Comment by ixiam** [comment]
reported in provision_civicrm issue tracker as well
https://www.drupal.org/node/2487429

**Comment by omega8cc** [comment]
This doesn't look like a new problem - see: https://www.drupal.org/node/2389235

**Comment by omega8cc** [comment]
This has been fixed in the upstream.
