### ISSUE TITLE
Beware of core update to 7.37 and / or i18n update to 7.13

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#714]
I do not know whether or not this has anything to do with BOA, but I recently updated a static platform to core 7.37 and i18n to 7.13 stables, and I am unable to add content to quite a few multilingual sites, including a newly installed site. In brief the content types are there, and set to translatable with localization, but when I try to add content, drupal error states "You have not created any content types yet..." and thus there are no content types to choose from and I cannot add content!

SO, do careful testing before adding drupal core 7.37 and / or i18n 7.13 to platforms.

https://www.drupal.org/node/2485527

and

https://www.drupal.org/node/2487500

I am running a stable 2.4.2 using only php 5.6, mariadb 10.x - the logs are all here in this error report:

https://github.com/omega8cc/boa/issues/710

Ed

**Comment by omega8cc** [comment]
This is not a BOA specific problem.
