### ISSUE TITLE
Add PHP 7 support

### ISSUE THREAD

**Issue by attiks** [omega8cc/boa#716]
No rush, just wondering if we'll wait till PHP 7 is stable

**Comment by omega8cc** [comment]
No ETA yet, but thanks for the request.

**Comment by Pls** [comment]
PHP7 is close to a release this year's fall, might be kind a similar with D8 release. Looking forward :+1:

**Comment by omega8cc** [comment]
Yep, we have HHVM support already, but PHP 7 should be added soon.

**Comment by Pls** [comment]
It happened, PHP7 released - http://php.net/archive/2015.php#id2015-12-03-1. Can't to test it out on BOA. Cheers :+1:

**Comment by omega8cc** [comment]
Let's include it on BOA-3.0.0 then.

**Comment by macmladen** [comment]
I tried PHP 7 in local environment, Drupal 8 was just fine but Drupal 7 showed some issues.

So I did not tried it on BOA but I am not sure that Drupal 7 with modules work out of the box with Drupal 7.

I used Drupal 8.0.2 with few modules and themes and status page was completely OK.

**Comment by omega8cc** [comment]
Adding PHP 7 support makes sense only once these issues are all green:

https://www.drupal.org/node/2454439
https://www.drupal.org/node/2656548

Otherwise Aegir Hostmaster would be broken, like any other D7 site.

**Comment by omega8cc** [comment]
Another showstopper is the lack of Redis integration C extension, not to mention that no other C extension used in BOA is ready for PHP 7, except yaml:

```
root@quad:/opt/php70/lib/php/extensions/no-debug-non-zts-20151012# ls -la
total 3.1M
drwxr-xr-x 2 root root 4.0K Feb 22 14:29 ./
drwxr-xr-x 3 root root 4.0K Feb 21 20:42 ../
-rwxr-xr-x 1 root root 2.0M Feb 22 14:29 opcache.a*
-rwxr-xr-x 1 root root 942K Feb 22 14:29 opcache.so*
-rwxr-xr-x 1 root root 239K Feb 22 14:29 yaml.so*
```

**Comment by omega8cc** [comment]
You can test/debug PHP 7 support using BOA-3.x dev branches for installation and upgrade. Don't use it on any production system, obviously.

You will need to add `7.0` to `_PHP_MULTI_INSTALL` first.

`barracuda up-head drush`
`octopus up-head o1 aegir drush`

**Comment by omega8cc** [comment]
Adding this to 3.3.0 milestone, just to keep an eye on this. There is a hope that Drupal 7 core will support PHP 7 at some point later this year.

**Comment by omega8cc** [comment]
Not fixed yet.

**Comment by omega8cc** [comment]
Progress! https://www.drupal.org/node/2704303#comment-11153029

**Comment by omega8cc** [comment]
The only thing which doesn't work with PHP 7 is Aegir backend (Provision), so it is very minor issue, because BOA allows you to run different PHP versions for FPM and CLI. Related issues on d.o:

https://www.drupal.org/node/2718437
https://www.drupal.org/node/2704303

I'm going to mark this one as fixed, because there is nothing left to do on the BOA side to support PHP 7.
