### ISSUE TITLE
Use HTTPS intermediate mode to support legacy systems like XP/IE8

### ISSUE THREAD

**Issue by obrienmd** [omega8cc/boa#718]
On a new BOA 2.4.2 server using the new SSL configuration tool (thanks, it's awesome!) the proxy configuration generated does not support XP / IE8 (no ciphers that work). While this is thankfully getting rare, it's still a requirement for a few of our sites where every donation / purchase matters.

Mozilla has a good resource on balancing this - the "Intermediate" level supports a few older platforms including IE 8 on Win XP:
https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_Server_Configurations

Lots of other general tips in that Mozilla article as well.

**Comment by omega8cc** [comment]
This is by design, or we couldn't introduce TLS/SNI support nor SPDY/PFS by default and BOA would be POODLE vulnerable. You would need to manually modify generated HTTPS vhost to downgrade it to break SPDY and PFS and/or use SSLv3, etc and use no longer supported/recommended settings.

Please check also:

https://github.com/omega8cc/boa/blob/BOA-2.4.2/CHANGELOG.txt#L48
https://github.com/omega8cc/boa/blob/BOA-2.4.2/CHANGELOG.txt#L108
https://github.com/omega8cc/boa/blob/BOA-2.4.2/CHANGELOG.txt#L815

**Comment by omega8cc** [comment]
Feel free to suggest improvements to our existing docs for anyone who needs to support this:

https://github.com/omega8cc/boa/blob/master/docs/SSL.txt

**Comment by omega8cc** [comment]
This is probably related here:

https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.8.0&openssl=1.0.1e&hsts=no&profile=intermediate

>>
nginx 1.8.0 | intermediate profile | OpenSSL 1.0.1e | link
Oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7
>>

**Comment by omega8cc** [comment]
Of course feel free to submit patches to make this a configurable built-in option instead of forced by default modern configuration.

**Comment by obrienmd** [comment]
Oh, I definintely understand keeping everything related to PFS/SPDY, turning off SSL v3 and not supporting SNI for XP.

What I'm asking for is adding for is the addition of a few additional cipher suites in the ssl_ciphers line so an updated IE8 on XP will work IF the BOA admin has provisioned a dedicated IP. 

With this change, you can still get an A on SSL Labs test (I checked by simply adding the Mozilla Intermediate ssl_ciphers list to an otherwise BOA-generated SSL proxy conf file) with PFS, SPDY supported and POODLE of course mitigated.

The list I used:
ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';

**Comment by chriscroome** [comment]
I also don't see why the Mozilla Intermediate compatibility list of cipher suites can't be used, FWIW I linked to this last month:

https://github.com/omega8cc/boa/issues/690#issuecomment-94434340

**Comment by omega8cc** [comment]
OK, let's make it an option then.

**Comment by obrienmd** [comment]
That sounds good, but to be honest I think it could be the default and keep complexity to a minimum - the configuration with a simple cipher suite swap is still VERY secure.

**Comment by omega8cc** [comment]
Indeed, it looks perfectly fine: https://www.ssllabs.com/ssltest/analyze.html?d=omega8.cc

**Comment by obrienmd** [comment]
Thank you! I love to avoid configuration options when possible :)

**Comment by omega8cc** [comment]
Thanks obrienmd and chriscroome!
