### ISSUE TITLE
CSF allow / ignore persistence

### ISSUE THREAD

**Issue by obrienmd** [omega8cc/boa#719]
For system monitoring, I need to add entries to /etc/csf/csf.allow and /etc/csf/csf.ignore that persist through BOA updates and auto-healing. If possible, I'd like to do this while keeping other csf improvements / tweaks that the BOA team makes. In reading through the docs, it doesn't look like there's a way to make these two goals work together - am I missing something or is this just not possible?

**Comment by obrienmd** [comment]
One thought - could your stock .allow and .ignore file include an include statement pointing to a custom file?

ex: Include /etc/csf/csf.customallow

**Comment by obrienmd** [comment]
Per this: https://github.com/omega8cc/boa/issues/346

It looks like I should be able to use the csf -a command to do this for a subrange. However, I did that yesterday and it seems the change was wiped at some point during the day. Is this expected behavior?

**Comment by omega8cc** [comment]
We don't modify anything in your `/etc/csf/csf.allow || ignore || deny` files and we don't have any BOA specific templates for these files.

Please check their built-in docs to see how can you make some entries permanent, if needed.

Note: BOA installs vanilla CSF/LFD and we don't modify anything in CSF/LFD beyond some little changes in the default configuration file. Please enable CSF config protection if you want to maintain your own modified configuration and then just remember to run `csf -uf` from time to time (or set `AUTO_UPDATES = "0"` in the `/etc/csf/csf.conf` file) to update the firewall only (it will merge in all your custom configuration settings).

Please check: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L79

**Comment by omega8cc** [comment]
BTW, I think that old entries are automatically wiped out only for deny file:

```
# Note: If you add the text "do not delete" to the comments of an entry then
# DENY_IP_LIMIT will ignore those entries and not remove them
```

Both allow and ignore files are apparently not affected by any such limit, so the entries there shouldn't get modified.

**Comment by omega8cc** [comment]
I have checked the code again and indeed we *do* modify both `/etc/csf/csf.allow and `/etc/csf/csf.ignore` hourly - to remove local IPs if added there for some reason, because they shouldn't be added.

If you think it is a bug, please  confirm if you have tried to whitelist remote or some local IPs?

Please note that IPs detected as local are listed in the `/root/.local.IP.list` file.

**Comment by ar-jan** [comment]
I can confirm that entries I added to csf.allow and csf.ignore have never been purged automatically. I think this works as it should.

**Comment by obrienmd** [comment]
Agreed - I believe there was a one-time change that purged those files. I'm not sure what it was, and the failure mode is reasonable (monitoring goes down, which is non-critical), so let's close this. Thanks for the consideration!
