### ISSUE TITLE
aegir > local workflow with site in git

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#720]
We're exploring best way to allow developers to work on sites locally (so they can use their own IDE etc).

It seems that giving developer the platform make file and having the site's directory (foo.com) in git is the simple solution.  But https://omega8.cc/git-or-platforms-based-workflow-in-aegir-251 says "You should never put entire sites/foo.com in a one repo. It will not work."

Does that mean "entire" literally, so if we gitignore appropriate files it's ok?  It does seem to work.  Will something expect to break?  What's wrong with putting foo.com in git?

The closest thing I can find to a recommendation for best practice here is https://groups.drupal.org/node/140949#comment-491954 but that thread seems philosophical to me (not sure how to practically implement it), and the Drupal on Git project (http://dgo.to/dog) that the thread discusses is looks rather abandoned.

This thread https://www.drupal.org/node/1935810 says BOA will support Devshop once Devshop uses Aegir 2.x (which I believe it does now) but http://dgo.to/devshop says "The only way to install DevShop is with the new standalone install.sh script." which means incompatible with BOA, right?

Is there a recommended approach for allowing developers to work on sites locally?

**Comment by omega8cc** [comment]
Our recommendation is to develop on the server and not locally. This makes the work a magnitude faster and easier. We do plan to extended supported workflows to include Git based, monolithic codebase, when we could introduce this officially and support also novice users.

**Comment by Pls** [comment]
Just curious, could you explain in more detail what you mean "to develop on the server and not locally"? Some example would help here.

**Comment by omega8cc** [comment]
Just use BOA installed on the server remotely.

**Comment by omega8cc** [comment]
Having multiple Octopus instances on a VPS is very handy for this exact purpose.

**Comment by ahillio** [comment]
Having multiple Octopus instances does seem like a great way of having
staging and live environments.

But for the scenario when hiring a developer who uses PhpStorm, for
example, a solution is needed for them to develop locally, as it's not
feasible to tell them "no, use vim"  -- right?  they would not like me
anymore ;^)

What we did recently was give the developer the makefile (which we keep in
git) to build the platform locally and then have the site in its own git
repo.  This seems to work.  But I'm confused why you say it will not work
<https://omega8.cc/git-or-platforms-based-workflow-in-aegir-251>.  Why
not?  If there are problems with doing that could you explain what they are
please?

Thanks!


On Wed, Jun 3, 2015 at 9:27 AM, Barracuda Team <notifications@github.com>
wrote:

> Having multiple Octopus instances on a VPS is very handy for this exact
> purpose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omega8cc/boa/issues/720#issuecomment-108410515>.
>



-- 
Alec Hill
(802) 279-8800
http://firestick.me

**Comment by ahillio** [comment]
Oh, I had read [this page](https://omega8.cc/managing-your-code-in-the-aegir-style-110) before but reading it again I noticed what I didn't see previously:
> then using Profiler module to create your custom Installation Profile and manage in your Git repo just your Makefiles, your Installation Profiles and only your custom modules and patches – in a separate repo per module and per theme."

I guess that's the sort of recommendation I was looking for.

**Comment by omega8cc** [comment]
The monolithic approach may not work on BOA by default because limited shell user doesn't have a write access to sites/foo.com and this will be totally against the default Aegir platforms based workflow. That is why we want to scare people before they will go into deep problems by using Aegir while ignoring it completely.

Yes, recommended workflow is explained in our docs: https://omega8.cc/library/development

Also recommended: https://omega8.cc/the-best-recipes-for-disaster-139

**Comment by ahillio** [comment]
Thanks.  Yeah, using it properly with limited shell users monolithic approach doesn't work.  I didn't obvserve that myself because I was using the Octopus user who does have write access to the sites/foo.com.  Thanks again!
