### ISSUE TITLE
sites/foo.com/solr.php not created

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#721]
I have enabled solr support in `boa_site_control.ini`:

~~~
[system_control]
;solr_integration_module = NO
solr_integration_module = search_api_solr
;solr_update_config = NO
solr_update_config = YES
;solr_custom_config = NO
;sql_conversion_mode = NO
;disable_user_register_protection = FALSE
~~~

but `solr.php` was not created at the next day.

Config Files:
https://gist.github.com/luxio/fc8d954afea7454f0f8e

Any ideas why?

**Comment by omega8cc** [comment]
It is because it depends on `_MODULES_FIX=YES` which is not default. See also: #592
