### ISSUE TITLE
Incorrect permissions on /usr/bin/optipng

### ISSUE THREAD

**Issue by mabo1972** [omega8cc/boa#722]
Hi,

i installed boa with the "IMG" extras. When i try to use "optipng" with the module "imageapi_optimize" i get an open basedir restriction error message.
i investigated the problem and found out that /usr/bin/optipng has no right to execute for anybody. 
With this rights i get no error message. 
Is there an appropriate reason why these rights do not exist?

**Comment by omega8cc** [comment]
Please provide more details, like the result of `ls -la /usr/bin/optipng` etc.

**Comment by omega8cc** [comment]
Indeed, for some reason `optipng` was missing in the exceptions list.

Thanks for the report!

You can fix this manually as root with:

`chgrp root /usr/bin/optipng`
`chmod 755 /usr/bin/optipng`
