### ISSUE TITLE
Panels / Panelizer Performance

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#724]
Thanks again for a fantastic contribution to Drupal.
May I ask a question re site configuration and performance related to Panels, Panelizer and Barracuda ...

How is performance impacted when a Panel Pane or a Panel Page Variant is selected/excluded via a domain (via Domain and Domain_Ctools modules), or a user role (Anon or Auth user) criteria. 

Put another way, Is it preferable to use a selection rule (eg: user role) for a Panels Page Variant than to set visibility rules for individual Panels on a Panels/Panelizer page?

Case A ... Which is preferable from a caching/performance point of view?
Scenario 1: Page variants for Anon User and Auth user, OR
Scenario 2: Pane visibility rules for Anon and Auth User.

Case B ... Which is preferable from a caching/performance point of view?
Scenario 1: Page variants for domain name, OR
Scenario 2: Panel visibility rule for domain name.

Thanking you kindly in advance for your time.

**Comment by omega8cc** [comment]
We don't have any direct experience with these settings, so maybe others could chime in to share their end-user experience.
