### ISSUE TITLE
problems restarting maria db during upgrade

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#725]
Im having issues when trying to run baracudda upgrade head that @ BOA [11:52:16] ==> INFO: Restarting MariaDB server...

the process stops, and my putty terminal times out... 

Any ideas how to get upgrade to complete and get maria db reboot to not stall?

Thanks. Im always on head releases....

**Comment by attiks** [comment]
I ran into the same problem, run pkill mysqld in another terminal when you see the message.

**Comment by AntiNSA** [comment]
running lish console in one window to monotor and the system upgrade option from a seperate putty window allows me to monitor it & it seems to be progressing without timing out ok

**Comment by AntiNSA** [comment]
ok timed out again nd new terminal I get :

 tail -f /var/backups/reports/up/barracuda/150525/barracuda-up-150525-1207.log
BOA [12:09:14] ==> INFO: Running aptitude full-upgrade...
BOA [12:09:42] ==> INFO: Updating MariaDB and PHP configuration
BOA [12:09:44] ==> INFO: OS and services upgrade completed

BOA [12:09:44] ==> INFO: Aegir Master Instance upgrade skipped
BOA [12:09:45] ==> INFO: Building Pure-FTPd server from sources, please wait...
BOA [12:09:45] ==> INFO: Generating DH parameters, 4096 bit, please wait...
BOA [12:26:55] ==> INFO: Restarting Jetty 9
BOA [12:27:01] ==> INFO: Restarting Redis, PHP-FPM and Nginx...
BOA [12:27:05] ==> INFO: Restarting MariaDB server...

**Comment by attiks** [comment]
Pkill kills the process by name, same as kill.

It will get restarted automatically, otherwise run sudo /etc/init.d/mysql start

**Comment by AntiNSA** [comment]
In doing so, this cancels the upgrade process.... or is rebooting the db the absolute final step in upgrading?

**Comment by attiks** [comment]
It is the last step if I'm not mistaken

**Comment by omega8cc** [comment]
No idea how to reproduce this?

**Comment by AntiNSA** [comment]
SImply upgrading dev versions, this happens each time....

**Comment by omega8cc** [comment]
The problem is that we can't reproduce this on head-to-head upgrades. Could you post all required config files and logs as listed at https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt ?

**Comment by AntiNSA** [comment]
A bit busy now... I have issued a reboot command from the terminal and tried the upgrade process with the same results.... yet manually going into the linode interface and shutting down/starting allowed the maria db to reboot durring the upgrade process with no probllem. Dont know if this is a fluke....but it worked for me

**Comment by BrianGilbert** [comment]
I have a server where mariadb had stopped working (5.5), I tried updating and was getting failed installations of mariadb due to the same error below (error below shows after trying to upgrade to 10.0 line)

```
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up mariadb-server-10.0 (10.0.19+maria-1~wheezy) ...
[....] Stopping MariaDB database server: mysqld^[[?25l^[7^[[1G[^[[32m ok ^[[39;49m^[8^[[?12l^[[?25h.
dpkg: error processing mariadb-server-10.0 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 mariadb-server-10.0
```

**Comment by BrianGilbert** [comment]
I was able to resolve by uninstalling mariadb, moving /var/lib/mysql to /var/lib/mysql-bac, reinstalling mariadb..

then copying back in the aegir DB's and recreating the users to access them..

**Comment by omega8cc** [comment]
This is not expected to fail like this on upgrade from 5.5 to 10.0 -- it is probably a separate issue then?

**Comment by omega8cc** [comment]
@BrianGilbert please open separate issue and attach all required logs and config files.
