### ISSUE TITLE
[advagg] 7.x-2.8 breaks advagg_cache_level in global.inc

### ISSUE THREAD

**Issue by Blackbaud-JoePrice** [omega8cc/boa#726]
advagg 7.x-2.8 breaks global.inc advagg_cache_level = 1 settings (https://github.com/omega8cc/boa/blob/master/aegir/conf/global.inc#L636)

advagg-7.x-2.10 reverts this change and adds back the cache level of 1 -- see http://cgit.drupalcode.org/advagg/commit/advagg.admin.inc?id=8ebe0b140f21e2e15205d1265184e04bebf2642d 

We should either upgrade advagg or implement a temporary fix for advagg 7.x-2.8

```
// advagg 7.x-2.8 equivalent to cache level 1
$conf['advagg_cache_level'] = 3;
```

**Comment by Blackbaud-JoePrice** [comment]
Accidentally created this issue with a secondary github account...

**Comment by omega8cc** [comment]
Thanks for the report! It seems that it is better to just switch to `3` which works for all versions and means more or less the same.

**Comment by pricejn2** [comment]
Looks good. Thanks!
