### ISSUE TITLE
firewall issues after failed upgrade

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#731]
Running BOA upgrade last night, `barracuda up-stable` worked but then `barracuda up-stable system` would just hang and time out.  Today the connection time outs during normal use became very prevalent, drush dl would timeout, wget would timeout.  One of us couldn't even ssh to the server without turning off the firewalls.  I saw this issue https://github.com/omega8cc/boa/issues/685 suggests `csf -x` then `csf -uf` and `csf -e`.  I don't totally understand that thread, but should I now try `csf -uf` and `csf -e` and then resume the BOA upgrade?  [cfn and log files](https://gist.github.com/ahillio/78a6eb3e8b8ad33267ad)  Thanks!

**Comment by omega8cc** [comment]
Yep, you may need to wipe out blocked IPs list to fix the problem. Closing as duplicate, because it was also auto-magically fixed on all instances with auto-updates enabled.
