### ISSUE TITLE
DNS no longer resolving - all of a sudden - Tuesday mid-day - all sites down

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#732]
All of a sudden our websites on a BOA 2.4.3-stable using php 5.6 just stopped resolving - the browser error messages tell us that it's a DNS problem. But there's no problem at the registry or registrar level.

This did not happen during an upgrade, etc... it just happend on a Tuesday mid-day. What could have caused this?

I looked at all the other issues with this and I am very VERY alarmed - BOA can't even claim a 99% uptime, much less the 99.999% uptime that we need to work professionally.  So, no matter what I do, I cannot get our BOA websited to resolve - and there is seemingly NOTHING to explain why the DNS resolver just quit on a Tuesday around noon.   

How can we get our sites up again - so that browsers see them? We have already tried both soft and hard reboots - no success; We have tried to upgrade (up-stable) barracuda and octopus, and no success.

I can't believe this - pdnsd must be the culprit here... it was found running with 0 bytes in cache and 0 entries...

Our questions:
Shouldn't you take this issue MUCH MUCH more seriously, and just make stable bind9 part of BOA, since keeping sites up is MUCH MUCH more important that the few milliseconds that pdnsd might save a web page in loading - IFF (if and only if) it's working properly. Obviously this isn't working properly - or you wouldn't have so many complaints about it.  We still can't get our sites to resolve, and that is fatal to us - we'll just ahve to use a different hosting system - since there is no logical explanation as to why this happened.

Can you please change this permanently so that we professionals can use BOA and keep our websites up and running (i.e. being displayed in the various browsers), please?

**Comment by EdNett** [comment]
We also have a test vps on which we test BOA before making any changes to the production server, and the test vps's domains weren't resolving either, and automagically they started resolving (without our having made any changes at all to is) just when the production servers' sites started resolving - so it is clear that this issue is either BOA skynet (which we do NOT use, SKYNET=NO) or Google.

We suggest that you no longer use Google as DNS resolver - they are not reliable. This system MUIST be changed, and the first (and perhaps the only necessary step is to simply remove Google as the resolver, and let each hosting company / vps or dedicated server rental company deal with dns - this will keep the sites up we believe.

**Comment by EdNett** [comment]
All our sites - production and test - were effectively DOWN - that is - were not reachable via the internet - for 2 to 3 hours today because fo this, and that is unacceptable. Please stop using Google - they are a commercial for-profit company that does not respects privacy and which one cannot and SHOULD NOT rely on to provide needed services like DNS. None of us are paying Google to provide DNS, yet all of us ARE paying the registrars AND the hosting companies we rent our vps's and dedicated servers from to provide DNS - it is these latter companies that MUST be responsible for DNS. Letting Google handle DNS resolution is letting a competitor control our fate, and it cannot be allowed.

Please confirm that you WILL make this change away from Google, and let the registrar and the server/vps companies handle this - it's the ONLY safe way to move forward and to ensure website uptime.

Thank you for your understanding.

**Comment by omega8cc** [comment]
BOA is not married to Google DNS. If you don't like it, use any other you prefer. It is configurable, as explained in the docs. That said, we run already thousands of BOA instances, both hosted and managed remotely and we have never seen any such problems. You are not forced to use BOA if you can't get it to work for some reason we couldn't reproduce.

**Comment by omega8cc** [comment]
Look here:

https://github.com/omega8cc/boa/blob/master/docs/ctrl/system.ctrl#L82
https://github.com/omega8cc/boa/blob/master/docs/ctrl/system.ctrl#L96

**Comment by EdNett** [comment]
We apologize for jumping to conclusions - I couldn't think of any other explanation as to why this should happen. It turned out that our server and vps provider was doing some re-wiring of the electrical connections (that is their explanation) to our server and vps - at the exact same time this problem occurred, and that somehow left us with a server that we could ssh into, which was running, but whoses pdnsd cache had 0 bytes and 0 entries in it - and thus we had no resolution of our hosted sites in the browser.

**Comment by omega8cc** [comment]
OK, thank you for the update.
