### ISSUE TITLE
Debug Migrate+CiviCRM upgrade problem

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#733]
I filed an [issue](https://www.drupal.org/node/2503369) on the provision_civicrm project:

> Recently, migrating a site to a platform with a newer CiviCRM version stopped working. (I'm using BOA 2.4.3 which uses provision_civicrm 2.x):

>    CiviCRM: in _provision_civicrm_upgradedb(), _civicrm_init() worked, comparing code and schema versions.
>    Starting with v4.5.7 -> v4.6.3 upgrade ..
    CiviCRM: db version is 4.5.7
>    **Drush command terminated abnormally due to an unrecoverable error.**
>    Returned from hook drush_provision_drupal_provision_migrate
>    Backend invoke: php /data/disk/o1/tools/drush/drush.php --backend=2 --root= --uri= --yes provision-save '@mysite.o1.server.example.com' --platform='@platform_DrupalCivi7341Prod' 2>&1
>    php /data/disk/o1/tools/drush/drush.php --backend=2 --root= --uri= --yes provision-save '@mysite.o1.server.example.com' --platform='@platform_DrupalCivi7341Prod' 2>&1

> With 4.5.8 on the target platform the same problem happens, but with 4.5.7 (no civicrm upgrade) the migration works fine.

> Manually updating civicrm in the platform to 4.6.3 and running the upgrade script works without errors, suggesting that there's no problem with the civicrm install itself.

> files/civicrm/ConfigAndLog is empty. Are there other places I could find more clues? Any other suggestions?

bgm responded:

> Hmm, seems like there's a PHP error, but if I recall correctly, the only way to see the error is to stop the queue-runner (if BOA uses it), and run the hosting-tasks manually on the command line.

> i.e. run the "migrate" task, then quickly go to `drush @hostmaster hosting-tasks` on the command line, as the Aegir user.

Could you advise what the exact steps would be to troubleshoot this further on BOA?

**Comment by omega8cc** [comment]
I'm not sure if there is anything BOA specific here. BOA doesn't use queue-runner, so you could simply stop system cron, wait a minute or two, queue the task in Aegir and then run it on command line as the instance backend user `o1`.

**Comment by omega8cc** [comment]
Feel free to reopen if you will find it to be BOA specific issue.
