### ISSUE TITLE
Drush make (for localized projects) fails to download translations

### ISSUE THREAD

**Issue by netdream** [omega8cc/boa#734]
The provided Drush Make is unable to create localized platforms, because it fails while downloading translations. (https://www.drupal.org/node/2484343)
An update has been cherry-picked to Drush Make 7.x and Master some days ago (https://github.com/drush-ops/drush/pull/1394)
Please take care of it when releasing next custom Drush in BOA.

**Comment by omega8cc** [comment]
Thanks for the heads-up! Cherry-picked: https://github.com/omega8cc/drush/commit/614056f9c50709be15f747a6fc857b6bb621ece2
