### ISSUE TITLE
CiviCRM cron does not run at interval set in Aegir

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#735]
Looking for insight into what might cause this?

![screenshot from 2015-06-16 11 27 31](https://cloud.githubusercontent.com/assets/1657096/8188328/d38ac1f2-141a-11e5-8eaa-1bd18e9b197f.png)

```CiviCRM cron run: Every 15 min
(Last run: 19 min ago)```

**Comment by LunkRat** [comment]
Okay, I think if CiviCRM cron follows the same logic, the answer to my question is here: https://omega8.cc/running-scheduled-sites-cron-in-aegir-118

Confirm?

**Comment by omega8cc** [comment]
No, CiviCRM cron is run via backend and Drush, while Drupal standard cron is run via local curl request to /cron.php. If the cron is reported in Aegir but doesn't really work, you need to try to run it manually in the backend to see possible errors.

**Comment by omega8cc** [comment]
I guess I should ask what the problem is: does the CiviCRM cron run at all? Or just not exactly when reported (like shown in your example)? If that is the case, then yes, it may follow the same logic we have explained in our docs and experience delays.
