### ISSUE TITLE
Can failed clones/migrations lead to duplicate databases?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#736]
I recently had some failures with cloning and migrating a site due to problems with CiviCRM on Aegir/BOA. I noticed there are now 3 databases for 1 site (recognizable by the database name), of which only one is used of course.

Is this expected with clone/migrate failures? And if so, perhaps we should document it to be able to prevent ghost databases in the system?

**Comment by ar-jan** [comment]
Hmm, perhaps this was not related to the failures, but to the size of the database (several GB), or something else. I just noticed a left over database from a clone which did not have any failed tasks, but where I'd just run a delete task. The delete task ran without errors, I think, but since the site is now gone I can't check its logs.

But cloning and migrating the same site worked, so it seems strange the the database couldn't just be dropped when deleting it. Any ideas?

**Comment by omega8cc** [comment]
These tasks *can* result with ghost databases and grants left, if the task fails at the "right" moment or it is caused by something like OOM incident or any other crash, or at least error, like packet max size exceeded etc.

**Comment by ar-jan** [comment]
I guess then it could be due to the size of this site. Should such an error be available in the log of the delete task, if it failed during that task, or do you have a suggestion for another way to find the cause? Thanks!

**Comment by omega8cc** [comment]
If SQL process crashes, then PHP layer should be able to catch and report it via Drush output (the task log), but when PHP crashes (or both, in a chain), then the only place where anything can be logged is /var/log/syslog, I think.
