### ISSUE TITLE
D6/Pressflow core themes?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#737]
Hi, is there a reason to remove the D6 / Pressflow core themes from their platforms, or could they be kept in place? I just migrated a site which uses Bluemarine, and since there isn't a standalone 6.x release of the theme it would be useful to have it included in the platform.

**Comment by omega8cc** [comment]
Not sure why we started to delete them by default. It doesn't make any sense to me.

**Comment by omega8cc** [comment]
Thanks for the patch!
