### ISSUE TITLE
Unable to run "Backup" - "Clone" - Etc. Error - "Could not write database backup file mysqldump"

### ISSUE THREAD

**Issue by HyperGlide** [omega8cc/boa#742]
Most recently we have been unable to run "Backup" - "Clone" - and other similar jobs.

The error noted in the "view" popup reports:

    "Could not write database backup file mysqldump" 

and

    Failed loading /usr/local/ioncube/ioncube_loader_lin_5.3.so:  /usr/local/ioncube/ioncube_loader_lin_5.3.so: wrong ELF class: ELFCLASS64

Requested files can be found:
 /root/.barracuda.cnf - https://gist.github.com/HyperGlide/f04a515b5a259d6765ee 
  /var/log/barracuda_log.txt - https://gist.github.com/HyperGlide/2e74ba601b1a187849e1
  /root/.USER.octopus.cnf - https://gist.github.com/HyperGlide/6cb4d4d316ca0e5f79bf
  /data/disk/USER/log/octopus_log.txt - https://gist.github.com/HyperGlide/67f8978f1b51233e9429

Thank you in advance for taking a look at this issue and helping to resolve it.

**Comment by omega8cc** [comment]
Try to add `_PHP_FORCE_REINSTALL=YES` and run `barracuda up-stable system` upgrade.

**Comment by HyperGlide** [comment]
Thank you for the response.

I did as advised. The updated did not complete. 

You can find the log here --> https://gist.github.com/HyperGlide/b047914064d2e358c793

**Comment by HyperGlide** [comment]
I followed the steps at https://github.com/omega8cc/boa/issues/685#issuecomment-93247107 to try to complete the upgrade.

The upgrade did run 100% failed.

A log can be found at https://gist.github.com/HyperGlide/b047914064d2e358c793

All help and support is greatly appreciated.

**Comment by HyperGlide** [comment]
@omega8cc any thoughts or further guidance please?

**Comment by omega8cc** [comment]
We will try to assist you once we have a moment after 2.4.4 release. Unfortunately it looks like problem may be related to Squeeze and OpenSSL 1.0.2a compatibility, but we no longer use nor test Squeeze at the moment, so we will need more time to debug this.

**Comment by HyperGlide** [comment]
@omega8cc Thank you for the response and help. Should I look to build a new server (Wheezy) and migrate the site over?

I had once tried the auto update but broke the server (running on Linode) and have read there was an unsupported bug.

My concern with doing this is that unless I can get the backups to run, even moving the barracuda instance from the old to new server would fail as well.

Please respond when you can and I am open to any option that helps get things moving.

Cheers

**Comment by omega8cc** [comment]
Please upgrade to current stable 2.4.4 -- we have changed the OpenSSL version to 1.0.1o and it works on Squeeze in our tests.

**Comment by omega8cc** [comment]
Here is how it works on fresh install on Squeeze: https://gist.github.com/omega8cc/f59aef88333f17109155

**Comment by HyperGlide** [comment]
@omega8cc 

Thank you for the replies.

Ran the update to 2.4.4. The log is posted here --> https://gist.github.com/HyperGlide/b36669b57be1ee91a5e1

Seems there is still an issue and similar errors are still present.

Anu sgguestions on 
    Failed loading /usr/local/ioncube/ioncube_loader_lin_5.3.so:  /usr/local/ioncube/ioncube_loader_lin_5.3.so: wrong ELF class: ELFCLASS64

Reading online I see this can be related to a Kernel update from 32 - > 64 which we did as part of a Linode "upgrade"

Is there any suggested steps to manually remove and reinstall this software? Or perhaps run some other command?

Thank you again!
 HG

**Comment by omega8cc** [comment]
We don't support and never even tested 32->64 upgrade. You could try to add `_FULL_FORCE_REINSTALL=YES` and then run `barracuda up-stable` again. If this will not help, please consider new VPS and migration with `xboa`-- https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

**Comment by HyperGlide** [comment]
Thanks for the additional information. 

I do recall and had a look for this thread that was related to myself and others that where in the same position of migrating from from the 32 to 64 bit kernel.

https://www.drupal.org/node/2271951

**Comment by omega8cc** [comment]
Have you run `barracuda up-stable` with `_FULL_FORCE_REINSTALL=YES` enabled now?

**Comment by HyperGlide** [comment]
Yes but doing it again just for old times sake.
