### ISSUE TITLE
Upgrade fails to recogise new Octopus platforms

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#743]
For some reason Octopus seems to be stuck on a older version (Drupal 7.37, Panopoly 1.21).

I have tried upgrade several times with various config settings but no luck.

Other BOA servers not having same issue. Is there a simple way to solve this?

**Comment by ar-jan** [comment]
The last release is BOA 2.4.3 with built-in platforms based on 7.37, so that's the expected version. I'm not sure what the difference with other BOA servers could be. But the next BOA release should be out soon, looking at the milestones.

**Comment by omega8cc** [comment]
Just compare:

https://github.com/omega8cc/boa/blob/BOA-2.4.3/README.txt
https://github.com/omega8cc/boa/blob/master/README.txt

**Comment by MetaBureau** [comment]
Sorry yes my mistake. I had seen Octopus updated on github and thought that platform updates were being referenced outside the barracuda major release cycle (as hotfixes).
