### ISSUE TITLE
BOA Cron switches from Drush to Wget 

### ISSUE THREAD

**Issue by Pieter-Lab** [omega8cc/boa#746]
Hi Guys
We have have been using BOA for awhile now and we are very happy with it.

That said, we have noticed, that It seems that when setting the BOA Cron Method to Drush - it reverts back to Wget after approx. a day.
We would like to get the Cron method to stay on Drush.
Is there anything we can do on our side to fix this or is it bug.

Thank you for time.
Pieter

**Comment by omega8cc** [comment]
You should avoid Drush method for security and performance reasons. That is why BOA forces wget/curl method by default. But when you know what are you doing and you have only trusted users on your BOA system, with no broken site which may break things by taking over system resources etc, you can now disable this forced mode with:

`touch /data/disk/o1/log/hosting_cron_use_backend.txt`

See also: https://github.com/omega8cc/boa/commit/f1b8c6149c63038f6a80e637b5827a82b7ac7e89

Now the daily.sh script will no longer revert this setting.
