### ISSUE TITLE
New Install: FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported values

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#747]
Hi all,

End of install session below, full session here http://pastebin.com/8Pzh39c9

Any ideas please?

Thanks...

========================================================

> Setting up libmagickwand-dev (8:6.7.7.10-5+deb7u3) ...
> BOA [21:35:21] ==> INFO: Installing IonCube x86_64 version for PHP...
> mv: cannot stat `composer.phar': No such file or directory
> BOA [21:35:22] ==> INFO: Installing Limited Shell 0.9.16.5-om8...              BOA [21:35:34] ==> 
> INFO: Installing Redis update for Debian/wheezy...         BOA [21:36:11] ==> INFO: Generating 
> random password for MariaDB
> BOA [21:36:11] ==> INFO: Updating MariaDB and PHP configuration
> BOA [21:36:12] ==> INFO: Restarting MariaDB server...
> BOA [21:36:16] ==> INFO: OS and services installed
> BOA [21:36:16] ==> INFO: Installing Aegir Master Instance, please wait...
> BOA [21:36:17] ==> INFO: MariaDB is listening on 101.100.101.100.
> BOA [21:36:20] ==> FATAL ERROR: AegirSetupM installer failed
> BOA [21:36:20] ==> FATAL ERROR: Aborting Barracuda installer NOW!
> BOA [21:36:20] ==> HINT: Please check /var/aegir/install.log
> BOA [21:36:20] ==> HINT: for more information on errors occured
>
> BOA [21:36:23] ==> Skynet Agent v.BOA-2.4.4 welcomes you aboard!
>
> BOA [21:36:26] ==> ERROR: This script should be used only when the same version of BOA
> BOA [21:36:26] ==> was used before. Your system has to be configured/upgraded by BOA
> BOA [21:36:26] ==> version BOA-2.4.4 first
> BOA [21:36:26] ==> Bye

> BOA in-stable completed
> Bye

> $ root@vultr:~# cat /var/aegir/install.log
> BOA [21:36:19] ==> INFO: Installing drush in /var/aegir
> BOA [21:36:20] ==> FATAL ERROR: _PHP_CLI_VERSION must be set to one of supported values
> BOA [21:36:20] ==> FATAL ERROR: Aborting AegirSetupM installer NOW!
> root@vultr:~#

**Comment by omega8cc** [comment]
This looks like a temporary connection problem, so it didn't download the php archive. Just try again.

**Comment by Juc1** [comment]
@omega8cc I should have said I tried the install three times with the same failure message each time before I posted here.

**Comment by omega8cc** [comment]
No idea. Please send us your system IP address to omega8cc at gmail.
