### ISSUE TITLE
How to run the BOND.sh script

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#748]
I will like to know if I ran the BOND script well, because I get some errors.

I just downloaded it from github (the script for the version I run on my server BOA 2.4.4 https://github.com/omega8cc/boa/blob/BOA-2.4.4/aegir/tools/BOND.sh.txt)

Then I just ran it and get this https://gist.github.com/yaazkal/bfa6bae9ccb9b0d8f1cf

Looking trough the file script there is a varable called *locCnf* that is used when those *cp* commands are executed, but that variable is never defined.

I don't know if is correct to run it the way I do, or if I have to place that script in another folder, or if I have to download the repository so I can run it; or if this is a bug.

Thanks a lot !

**Comment by omega8cc** [comment]
This is a bug, since this script is not expected to download anything and should have all variables defined locally, unless they are available in the system config files.

**Comment by omega8cc** [comment]
This script should be converted into built-in command.

**Comment by omega8cc** [comment]
This should be fixed now. Thanks for the report and for the patch!

**Comment by yaazkal** [comment]
Thanks to you ! just that I din't know where that locCnf should point. Great to see it fixed and included in the next 3.0.0 release :)
