### ISSUE TITLE
After Migrating an Octopus instance to a new server the active HostMaster Platform is not showing 

### ISSUE THREAD

**Issue by HyperGlide** [omega8cc/boa#755]
Recently migrated an existing Octopus instance from one BOA server to another using the steps outlined in:

https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

After doing so and running  `octopus up-stable all` both the active octopus install is not correct.

![2015-07-21 02 14 53 pm](https://cloud.githubusercontent.com/assets/892446/8794154/e3cb07f8-2fb2-11e5-8c3d-468436b0b443.png)

In the log it shows
`BOA [15:17:02] ==> UPGRADE B: Hostmaster STATUS: Fix 1/2 hosting_context 83107`
`BOA [15:17:34] ==> UPGRADE B: Hostmaster STATUS: Fix 2/2 hosting_context 83107`

Reference to:
https://github.com/omega8cc/boa/blob/7a48151e3bbfb09695489898f63e4279b5536006/lib/functions/satellite.sh.inc#L4199

**Comment by omega8cc** [comment]
This is the same edge case like in #763 so we can't really provide universal how-to.

Please read for hints:

https://github.com/omega8cc/boa/issues/763#issuecomment-132281592
https://github.com/omega8cc/boa/issues/763#issuecomment-137935394

**Comment by omega8cc** [comment]
Oh, and sorry for not responding earlier. We have confused this with some other request and assumed it is a duplicate, I think.

**Comment by HyperGlide** [comment]
This  can be closed you @omega8cc helped resolve via direct server support.

**Comment by omega8cc** [comment]
Ah, thanks for the confirmation :)
