### ISSUE TITLE
Protecting data backed up by backboa (duplicity) script - best practices

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#756]
I think it's good to discuss how BOA is practicing security of data backed up by automated scripts. https://github.com/omega8cc/boa/blob/master/docs/BACKUPS.txt is talking about backup up data, but how to prevent this data from getting accessed once the server is compromised (with all restore keys needed to for example destroy/damage backups) in some way?

How in this safe workflow 'duobackboa' can be integrated? I mean it's not safe to just back up data to S3 and feel safe. As I said if the VM is compromised then backups are too. What are you guys doing to make sure your data is safe? Configuring S3 to have versioning and have lifecycle rules to remove old ones (that duplicity tried to remove)? What backups full lifecycle do you have - 1M, 2M and why?

This can be out of scope for project maintainer to answer, but community input on best practices backuping up data would be awesome.

**Comment by omega8cc** [comment]
Backups are not really intended as a security measure. Backups are for disaster recovery and human error recovery scenarios. The `duobackboa` script allows you to have a duplicate S3 backups. It doesn't improve your system security, only your backups reliability. We recommend that you maintain also offsite backups (hosted sites owners are responsible for their own codebase, files and data backups, obviously). If your host offers backup add-ons, preferably versioned, like R1Soft/Idera, use them.
