### ISSUE TITLE
Update SSL Docs to add more detail about wildcard certificates

### ISSUE THREAD

**Issue by kepford** [omega8cc/boa#757]
I stumbled over myself trying to set up a new wildcard SSL on a dedicated IP address today. I did finally get it working but I may have discovered a bug. I was following the boa/docs/SSL.txt guide and maybe I did it wrong. Either way the doc could use more detail.

I will include example domain names to illustrate 

>Prepare the certificate and the private key files

>Paste your SSL certificate and all intermediate certificates (bundles)
>     below it in the file /etc/ssl/private/{domain_name}.crt

My crt was named `*.domainname.tld.crt`

>Generate HTTPS and HTTP proxy vhosts

>1. Create a config file: /root/.ssl.proxy.cnf with one record per line:

> domain_name target_ip o1 foo@email dedicated_ip

`*.domainname.tld target_ip o1 foo@email dedicated_ip`

These file names resulted in a file being generated at `/var/aegir/config/server_master/nginx/pre.d/z_*.domainname.tld_ssl_proxy.conf`
 
This seems correct but the Nginx test kept failing

```
nginx: [emerg] invalid server name or wildcard "www.*.domainname.tld" on 0.0.0.0:443
nginx: configuration file /etc/nginx/nginx.conf test failed
```

I had to edit the conf file and manually remove the www. server name from the file. Then the test worked just fine. I am concerned that BOA will override this conf file later as well. Again, maybe I got it wrong, or maybe this is a bug. Either way the Doc could be updated to make wildcard SSL more clear.

**Comment by omega8cc** [comment]
Thank you for the suggestion. Fixed!

**Comment by omega8cc** [comment]
Please note that BOA will not modify the files you have in `/etc/ssl/private/`. But if you will have `/root/.ssl.proxy.cnf` and you will run `xboa ssl-gen` again, it will create vhosts in `/var/aegir/config/server_master/nginx/pre.d/` again.

**Comment by omega8cc** [comment]
Please remove vhosts you have manually modified, fix your `/root/.ssl.proxy.cnf` file and run `xboa ssl-gen` again.

**Comment by kepford** [comment]
Based on the DOCS, I'm still not clear on how to set up a wildcard SSL cert. The only way I have been able to get it work is to create .crt and .key files for each domain. Unless I am missing something BOA supports wildcard SSL certs. The certs are working but you have to set up each domain. Not complaining, just mentioning this because it tripped me up.

**Comment by omega8cc** [comment]
With wildcard cert you just need to make sure you don't confuse proper filenames with wildcard names listed in the certificate. In short: drop all prefixes for filename needs. Other than that, you need only single .crt and single .key file per certificate, while the certificate can list either wildcard, subdomain, multi domain etc. It is explained at: https://omega8.cc/ssl-order

If you still have any issues, please provide more information on what exactly doesn't work for you and how are you trying to set this up.
