### ISSUE TITLE
Community IRC channel

### ISSUE THREAD

**Issue by Aciid** [omega8cc/boa#764]
Hey a friendly reminder to all of you BOA rockstars out there. The community has been hanging around in #omega8cc in Freenode IRC network. Anything BOA related is what we do and it's also a chill place to meet other infra-managers and devs.
Lately there has been a drop of vacant casuals, but thought posting here could wake up some people. Although I think a better place could be a drupal group also.

The channel is endorsed by Omega8cc, but it's not a official support channel.
Kind regards; Aciid

**Comment by Pls** [comment]
Idea is great to hangout with other people using BOA. What about using Slack group instead of IRC? Slack has some fancy notification features that beats IRC, actually, in a way killing it slowly.

**Comment by omega8cc** [comment]
The problem with IRC is that it is good only for people who use IRC all the time, since without bot like hefring at #aegir, all the conversations are lost for others. The g.d.o is just way too archaic at this point, so indeed, more modern chat tools, with built-in archive, like Slack or Gitter. I think Gitter is better thanks to its Github integration?

**Comment by omega8cc** [comment]
Join us in the omega8cc/boa chat room on Gitter https://gitter.im/omega8cc/boa

**Comment by omega8cc** [comment]
For those who never used Gitter before: http://research.gigaom.com/2014/01/gitter-is-a-github-based-chat-tool-for-developers/

**Comment by omega8cc** [comment]
@Aciid, thanks for the heads-up! The truth is that we have created this IRC room initially as an alternative to #aegir to avoid confusion, since some Aegir devs were not happy to see BOA specific stuff there, so let’s move to Gitter. This IRC room can be still used by hardcore IRC fans, though :)
