### ISSUE TITLE
DNS support in legacy version rsync key invalid from new dns server domain

### ISSUE THREAD

**Issue by gs9999** [omega8cc/boa#768]
Hello.  I recently install BOA on Wheezy.  Worked fine.  However, when I try to install a DNS server using BIND using the front end, the verification process results in errors.  Namely, the SSH key for rsync for my name server domain ns1.example.com is coming up as invalid, and therefore failing the verification process.

I tried to check /home/aegir/.ssh/authorized_keys and known_hosts file to see the keys... and even login to aegir user and ssh to the name server to accept the key verification (yes/no) to try to mitigate the problem.. but I can't even login as aegir!!! omg.... even after setting the password for the aegir user.  I don't know... this system just doesn't navigate like a strict debian/drupal install and so I am stuck... I searched google extensively for an entire day looking for a solution, but found none.

Could you assist me on this one... or  at least lead me in the right direction??

Thanks,

gs9999

**Comment by omega8cc** [comment]
Please don't install Bind. It is an old but no longer supported extra option. Remove bind9 with apt manually, remove its keyword from the cnf options and run barracuda upgrade. This has nothing to do with Aegir itself. Also, you are not expected to be able to log in as Aegir backend user.

**Comment by omega8cc** [comment]
Furthermore, please don't use legacy version. It is deprecated, not supported and may cause major headaches. It is left only for some backward compatibility and folks who are crazy enough to still run it.
