### ISSUE TITLE
DNS support in stable version not creating bind.conf file to include into bind's config

### ISSUE THREAD

**Issue by gs9999** [omega8cc/boa#769]
I installed the stable version of BOA on Debian Wheezy.  Fresh Install.  I went straight into the front end and installed a new server.  ns1.example.com.  It is listed as a nameserver in the registrar cpanel as a dns server hosted on own domain.  I am also deploying a live unused domain in BOA to see if the DNS support works in BOA.  

So the new server utilizing Bind in BOA frontend verifies.  However when I look at task logs, it never creates bind.conf or zone files which can be implemented into bind9.  I figure I can use bind9 because i    updated BOA with the bind option enabled, and the BOA update logs says it is installed.  Plus I can restart the bind9 service from the command line.

I noticed that with the legacy version, when I installed in on a Blank Debian Wheezy install, the task logs at least attempted to write zone files, etc. for bind to utilize.  However, now with the stable version, the logs verify good,  but there is no zone files being written.  And just to see if I am over analyzing the situation, I gave a domain I own which is not being used, dns servers ns1.example.com through my registrar, and deployed a site with the unused domain in BOA aegir frontend, and the DNS when checked independently through a lookup service, says that the servers are giving a loopback.  

This is one of the last things that I need to get working before I can really move along with my  project--working DNS bind support in Aegir BOA.  

I searched extensively on google.com for BOA DNS support and Aegir DNS support, but it seems that I can't find anything available regarding my issue to read.

Can you assist me, head me in the right direction--Thanks,

GS

**Comment by omega8cc** [comment]
BOA never supported Bind integration in Aegir. It allowed to install Bind, but it was intended to be managed either manually or via Webmin. We don't recommend to run name servers on your web server, though. It is much better to use free name servers provided by your registrar, as explained in our FAQ at: https://omega8.cc/faq#email-dns
