### ISSUE TITLE
CSF firewall brute force

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#770]
Hello,

We have some users which can not access our website which we host on BOA because they are blocked through the firewall.
When I check with:
csf -g IP-Address

I see the following:
Brute force Web Server 26 attacks - Tue Aug 18 23:10:21 2015

These users are actually legitimit users which do not trigger a brute force attack.

Is there a treshold which we can configure or do you know what could cause this action of the firewall?

Thanks!

**Comment by timlie** [comment]
Allright, found this topic:
https://github.com/omega8cc/boa/issues/728
I changed the dos limit to 900, hope this helps.
It is possible that this user was the only user visiting the website.

**Comment by omega8cc** [comment]
OR whitelist IP for web access only in /etc/csf/csf.allow with this line:
`tcp|in|d=80|s=123.123.123.123`
