### ISSUE TITLE
How do I setup AUTO_UP_MONTH (1-12) to a date in the past? 

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#772]
The document of the barracuda.cnf file says:
~~~
_AUTO_UP_WEEKLY= #-------------- Day of week (1-7) for weekly system upgrades
_AUTO_UP_MONTH= #--------------- Month (1-12) to define date of one-time upgrade
_AUTO_UP_DAY= #----------------- Day (1-31) to define date of one-time upgrade
~~~

and 

~~~
### You can set _AUTO_UP_MONTH and _AUTO_UP_DAY to any date in the past
### if you wish to enable only weekly system upgrades.
~~~

How do I setup `_AUTO_UP_MONTH` (1-12) to a date in the past?

**Comment by omega8cc** [comment]
Just any month earlier than the current, for example:

`_AUTO_UP_MONTH=7`

**Comment by luxio** [comment]
Thanks. This would be also a date in the future (next year) ;)

Is ist possible to enter multiple values for instance:

~~~
_AUTO_UP_MONTH=7,8,9
~~~

**Comment by omega8cc** [comment]
It works only for the current year, of course. No, you must enter single value, as required in the /etc/crontab
