### ISSUE TITLE
Merge htaccess changes with https://github.com/omega8cc/7x

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#773]
After following https://omega8.cc/how-to-add-custom-platform-properly-140 for a static platform, I realized there was a disconnect between the delivered .htaccess and the standard platform .htaccess (https://github.com/omega8cc/boa/blob/master/aegir/conf/get.htaccess.txt). 

Could the two be in sync going forward?

**Comment by omega8cc** [comment]
Yeah, we should sync them.

**Comment by omega8cc** [comment]
Done via https://github.com/omega8cc/boa/commit/4b06e466ec6ed900538cb95ee1cf049a43f6d10a and https://github.com/omega8cc/7x/commit/a4d07be79d49c7f71d025a0fb388574d662ea45f
