### ISSUE TITLE
HM user should have write access to static profiles/*

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#774]
There are many instances where a static (custom) platform will also contain a custom installation profile. Can the HM user have write access to these profiles without being required to disable all other permission fixing or skip.info?

**Comment by omega8cc** [comment]
Aegir backend user (if that is what you mean by HM) doesn't need write access to profiles. On any platform. Not sure what is the reasoning behind this suggestion?

**Comment by pricejn2** [comment]
After further testing, I'm able to chown the static/{platform}/profiles/{profile} folder to o1.ftp without it being reverted during daily permissions fixing. Sorry for the noise.
