### ISSUE TITLE
High Load every 3 hours on  BOA-2.4.5

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#775]
I have every 3 hours a high load and I can't find the issue:

![graph php](https://cloud.githubusercontent.com/assets/1497217/9544395/b81631c8-4d80-11e5-9969-042527d1ab41.png)

Here is the process list during one of this high load periods: https://gist.github.com/luxio/8ff6f8733b9c330febb7

Is there a certain job, which runs every three hours. Any help would be appreciated.

**Comment by angel0d** [comment]
Could it be that there is a site with a heavy/buggy cron job that runs every 3 hours ?

**Comment by luxio** [comment]
The sites were migrated from another server. I did not have this behavior there. But I should check,

**Comment by omega8cc** [comment]
There is nothing BOA specific or related here. You need to debug this site, and check what and how it does on cron run etc.
