### ISSUE TITLE
how to set/change php version for custom install?

### ISSUE THREAD

**Issue by santo74** [omega8cc/boa#776]
Anticipating the removal of PHP 5.3 and 5.4 in BOA 2.5, I would like to change the php version used for a custom install in /var/www in order to do some compatibility tests, but it's not clear to me how this can be achieved.

**Comment by omega8cc** [comment]
See how it is done for Chive in `/var/aegir/config/includes/nginx_compact_include.conf`:

```
###
### Send all non-static requests to php-fpm.
###
location ~ \.php$ {
  tcp_nopush off;
  keepalive_requests 0;
  try_files $uri =404;            ### check for existence of php file first
  fastcgi_pass unix:/var/run/www55.fpm.socket;
}
```
