### ISSUE TITLE
Question re redis-server

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#778]
We run latest boa stable 2.4.5 with php 5.6 on both barracuda and octopus, with solr 4 and jetty 9; Nothing unusual. I see this notice in the redis-server logs, below: (do you recommend we follow this advice?):

5771:M 02 Sep 17:39:02.093 # Server started, Redis version 3.0.2
5771:M 02 Sep 17:39:02.162 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
5771:M 02 Sep 17:39:02.162 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

Best regards,

ed

**Comment by omega8cc** [comment]
Interesting. While `vm.overcommit_memory` warning should be normally ignored, because following this advise may create critical problem on some VM systems, I have never seen the `THP` warning before. We will need to investigate this before disabling it by default.

**Comment by EdNett** [comment]
Here's a good article on this. I think it's important to follow this advice for the vm.overcommit_memory as well as the THP problem. If we modify these settings manually, will our settings get over-ridden with each BOA update that contains an update for redis?

http://redis.io/topics/faq#background-saving-is-failing-with-a-fork-error-under-linux-even-if-i39ve-a-lot-of-free-ram

**Comment by omega8cc** [comment]
We can't follow the advice and enable `vm.overcommit_memory` because, as I have mentioned above, it causes critical memory conditions on some VM systems/hosts. It is not safe to use by default.

**Comment by omega8cc** [comment]
As for the THP warning, we have never seen this before (kernel difference, perhaps), so if you see it, just follow the advice. You can do the same for `vm.overcommit_memory`, at your own risk.
