### ISSUE TITLE
Run most of crontab, install and upgrade tasks with low priority (nice, ionice)

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#780]
I think we should adjust how backboa is executed and use ionice and nice for system stability. Doing larger full backup it requires lots of system resources, and nice with ionice commands could help fix that problem.

Anyone else having this particular problem?

**Comment by Pls** [comment]
Blog post talking about this problem and fixes - http://blog.tayfunsen.com/2009/12/nice-and-ionice-for-resource-draining.html

**Comment by omega8cc** [comment]
Good idea. We don't experience any such issues, but of course anyone on a VPS with strictly limited I/O and other resources can see load spikes if you host enough sites with enough big files directories.
