### ISSUE TITLE
Assistance greatly appreicated with gtranslate configuration

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#782]
i am trying to use the enterprise version of gtranslate to provide a translation of my site for users.
it will take my sites url
thecenterofthenet.com

and add a prefix for the translated language to the url...

for example the prefix

es for spanish would change my site to 
es.thecenterofthenet.com (Im not realy happy with that feature, I am trying to see if I can get around changing my url) ,,,,,

However, I cant seem to get things to work, and am wondering if octopus needs any special care to allow this to work? here is the support doccumentation page http://gtranslate.net/docs/58-gtranslate-enterprise-documentation

I would really appreciate any help on this is I am in China and have about 800 middle school students who are going to start using the website and their parents cant speak English and it would be a great help to them. 

THanks!

**Comment by omega8cc** [comment]
We don't have any experience with this, so we can't really offer any hints. That said, I don't think you need something special, beyond proper DNS configuration for subdomains and proper aliases added in Aegir, of course without any redirection enabled.
