### ISSUE TITLE
System disk/memory/cpu monitoring

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#783]
I noticed that in the docs there is this:
@=> /root/.enable.newrelic.sysmond.cnf
  This file, if exists, allows to run newrelic-sysmond service, otherwise
  disabled for security reasons, because it exposes too much system level
  information/details in the New Relic control panel.

I usually use the NR panel for alerting of system resource monitoring but if it is a security issues, what tools are others using or are run in the omega8.cc hosting environment?

**Comment by omega8cc** [comment]
As listed at https://omega8.cc/remote, we are using Scout, Pagerduty and Pingdom.

The problem with newrelic-sysmond is that all sites owners (not just Barracuda / Octopus instance admin) can see probably too much than they should and need, which may expose you to some attacks more easily, at least in theory.

It is a matter of trust, and in the hosting business there is no place for such thing, when it comes to security. Unless your are the only admin on the system, for all sites hosted, which usually never is the case. You need to be at least a little paranoid to stay secure.
