### ISSUE TITLE
Octopus install fails DNS check by auto-detecting local rather than external IP

### ISSUE THREAD

**Issue by dbassendine** [omega8cc/boa#785]
My boa octopus install fails because it detects the IP of the VPS as being the local IP, rather than the external one - so when I run:

$ boa in-stable public [url] [email] o1

After the barracuda/aegir upgrade completes, I get the following from octopus:

ERROR: o1.boa.bluedotlab.org doesn't point to your IP: 10.1.1.31

As I understand, I should be able to override the automatically detected IP, by setting _MY_OWNIP="[external-ip]" in /root/.barracuda.cnf, or at least set _DNS_SETUP_TEST=NO to skip the DNS check altogether.

However, changes I make to /root/.barracuda.cnf don't seem to have any effect - the boa script always detects the IP as being 10.1.1.31. I've also tried setting the variable in bash directly, so when I $ echo $_MY_OWNIP I get the correct [external-ip]. This hasn't helped.

Any ideas on how to override the IP detected by boa/octopus, or skip the IP check? Or have I misunderstood?

**Comment by omega8cc** [comment]
Does it mean that once you set in `_MY_OWNIP` your public IP address which points to the hostname, it test overwritten on another boa install attempt? Or simply ignored? Please note that you will have to set `_MY_OWNIP` also in `.o1.octopus.cnf`. You don't need to use `_DNS_SETUP_TEST=NO` to make it work, and `_DNS_SETUP_TEST=NO` will not prevent some internal checks anyway, because they are needed to properly set db grants etc. Also, you can enable this option on command line with:

`$ boa in-stable public [hostname] [email] o1 nodns`

**Comment by omega8cc** [comment]
That said, it seems impossible to see this error if you have really set `_DNS_SETUP_TEST=NO` or disabled it with `nodns` on command line:

```
satellite_if_check_dns() {
  if [ "${_DNS_SETUP_TEST}" = "YES" ]; then
    if [ "${_VMFAMILY}" = "AWS" ]; then
      _LOC_DOM="${_DOMAIN}"
      if [ -z "${_MY_OWNIP}" ]; then
        find_correct_ip
        _MY_OWNIP="${_LOC_IP}"
      else
        _LOC_IP="${_MY_OWNIP}"
      fi
    fi
    if [ -z "${_MY_OWNIP}" ]; then
      _THISHTIP=$(ifconfig ${_IFCONFIG} \
        | grep 'inet addr:' \
        | cut -d: -f2 \
        | awk '{ print $1}' 2>&1)
      if [[ "${_THISHTIP}" =~ "127.0.0." ]]; then
        _THISHTIP=$(ifconfig ${_IFCONFIG}:0 \
          | grep 'inet addr:' \
          | cut -d: -f2 \
          | awk '{ print $1}' 2>&1)
      fi
    else
      _THISHTIP="${_MY_OWNIP}"
    fi
    _LOC_DOM="${_DOMAIN}"
    find_correct_ip
    _THISRDIP="${_LOC_IP}"
    if [ "$_THISRDIP" = "${_THISHTIP}" ]; then
      _DO_NOTHING=YES
    else
      msg "ERROR: ${_DOMAIN} doesn't point to your IP: ${_THISHTIP}"
      msg "Please make sure you have a valid A record in your DNS"
      msg "It is also possible that DNS change didn't propagate yet"
      msg "Bye"
      clean_pid_exit
    fi
  else
    if [ -z "${_MY_OWNIP}" ]; then
      _LOC_DOM="${_DOMAIN}"
      find_correct_ip
      _THISHTIP="${_LOC_IP}"
      _THISRDIP="${_LOC_IP}"
    else
      _THISHTIP="${_MY_OWNIP}"
      _THISRDIP="${_MY_OWNIP}"
    fi
  fi
}
```

**Comment by omega8cc** [comment]
So the problem is probably that you didn't set `_MY_OWNIP` in your `/root/.o1.octopus.cnf`

**Comment by omega8cc** [comment]
Yeah, I should have read the subject line "Octopus install fails". We need to document this better that you should either use `nodns` on command line or set `_MY_OWNIP` in both barracuda and octopus cnf files, if you have a system with private IP only, available locally.

**Comment by dbassendine** [comment]
You're right, the problem was that I needed to set _MY_OWNIP in .o1.octopus.cnf - now installed correctly.

Not sure how I missed that one, but thanks so much for the quick response!
