### ISSUE TITLE
Document changes affecting SSH root access

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#786]
I just upgraded to boa 2.4.6 stable - both barracuda and octopus using php 5.6 only and mariadb 10.0 series, with both ssh and ssl for sources. Can you help?

Will attach links to requested files.

BR,

Ed

**Comment by EdNett** [comment]
barracuda-cnf file here:  https://gist.github.com/EdNett/31def6b99cc6de12506e

octopus -cnf file here:  https://gist.github.com/EdNett/d059a32b36b2f05dfb9a

**Comment by EdNett** [comment]
I can login with my o1.ftp user and doing so requires me to immediately change my password.

I cannot give you the other two requested files, as I cannot login as root.

My root password is 109 characters long and uses special characters like  =  (  -  !  etc.

**Comment by EdNett** [comment]
Connecting to SSH2 server ipv4:22.
09:06:27.575 Connection established.
09:06:27.606 Server version: SSH-2.0-OpenSSH_7.1
09:06:27.622 First key exchange started.
09:06:27.731 Received a new host key from the server. Algorithm: RSA, size: 2048 bits, MD5 fingerprint: 16:fa:8a-etc, Bubble-Babble: xuhhh-etc
09:06:27.778 First key exchange completed using diffie-hellman-group14-sha1. Session encryption: aes256-ctr, MAC: hmac-sha2-256, compression: none.
09:06:27.810 Attempting none authentication.
09:06:27.841 Remaining authentication methods: 'publickey,password,keyboard-interactive'.
09:06:32.656 Attempting password authentication.

**Comment by EdNett** [comment]
I have tried this on 2 different ssh clients - cannot login as root - password authentication fails.

**Comment by EdNett** [comment]
It must be the new version of openssh - in the sshd-config the PermitRootLogin has to be uncommented.

**Comment by EdNett** [comment]
Having trouble connecting via ftp or sftp to verify that that is the problem and uncomment that line. Is it only TLS that can be used now?

**Comment by omega8cc** [comment]
If you are using `_SSH_FROM_SOURCES=YES` you should always check OpenSSH release notes before running the upgrade. Besides, it is a good practice to use SSH keys and disable password access for root.

There is no FTP access for root and SFTP is SSH based.

I guess you need to:

1. Read http://www.openssh.com/txt/release-7.1
2. Create good keys on your local machine: `ssh-keygen -b 4096 -t rsa -N "" -f ~/.ssh/id_rsa`
2. Add your public RSA key to root using remote console, hopefully provided by your host

**Comment by EdNett** [comment]
We can close this out, but it's a good warning for others to see.  My solution is just to modify the sshd_config file to allow rool logins and use a 255 character password or longer.

**Comment by ar-jan** [comment]
Alternatively you can allow password-logins based on IP address, e.g.

    # Allow password logins from trusted IP addresses
    Match Address "12.34.56.78,98.76.54.0/24"
    PasswordAuthentication yes

**Comment by omega8cc** [comment]
We need to document this better, I guess.

**Comment by AntiNSA** [comment]
Can you clearly document the exact process?

**Comment by EdNett** [comment]
For me, whenever I do a BOA system update, after the update is finished, before logging off, I:

vim /etc/ssh/sshd_config

and check that the following are set appropriately (before loggin out so that I can be sure to login again as root at a later time):

PermitRootLogin yes (or no to disable this)
StrictModes no (can this be set to yes safely for additional security?)
RSAAuthentication yes
PubkeyAuthentication yes

I notice that 
AuthorizedKeysFile 
is not set - is commented out, (any comments about whether this should be set if one has a public key with a server rental company, for example?), and

PermitEmptyPasswords is set to yes (and this is not recommended). Omega8, must this setting be left at yes for BOA to work properly?

Thanks for clarification.

**Comment by EdNett** [comment]
There's still a problem here, since I just updated to 2.4.7, by connecting via ssh with a 127 character password, and after the upgrade from 2.4.6 to 2.4.7, I cannot login, - authentication failure - I have tried different ssh clients, and I have looked at the /etc/ssh/sshd_config file and it looks fine StrictModes is set to no, but midifying it to yes does not help - root password login is set to yes. So something must have changed once again - without warning. I hope BOA is going to continue to support root ssh logins and long root passwords.  In my barracuda and octopus conf files I have strong passwords set to 96 characters, but this is not suppossed to affect the root password. Any clues on what is going on here, once again? I use only php 5.6 and I will paste the log files and cnf files, and reference them here. This is a real hassle.

Ed

**Comment by bserem** [comment]
My latest update to 2.4.7 gave no problems to me using private/public key pairs.

Though not a solution to your problem, but how come you don't switch to private keys and prefer 127char passwords?

**Comment by EdNett** [comment]
Well,

1. It appears that either the boa upgrade modified the root password, OR it changed something else that does not allow login from root to work.  I AM able to login ssh2 as the octopus user, o1.ftp.

I need to know which of the above happened, and so does Omega8 and so do other BOA users, right?

2. I can't get private keys to work right - maybe I don't understand this very well, or there is a problem with the server rental company?  Additionally, there are so many untrustworthy people hired by the biggest and cheapest server rental companies (which I am currently forced to use due to budgetary restraints), that I prefer not to give the occasional unscrupulous employee an easy way to hack us from home, etc. I consider this a serious security risk. I realize that any vps or dedicated server being rented can be used by an employee at the servers location - nothing I can do about this, I guess.

3. Lastly , I believe that a root password with all kinds of special characters that is very long (I'd use a 4096 character root password or longer if I thought I wouldn't have any problems with the ssh client - thus I only use 127 character passwords) is more secure that private keys.

**Comment by bserem** [comment]
I know see how some people see this the other way round. I never thought about it.

Personally, I find keys to be more secure, for 2 basic reasons:
1) I can have only one root password, whereas I can have many keys to login in to the root account (work, home, laptop, mobile phone). If any device gets compromised, I simply need to remove the key this device had. This helps a lot in my situation where there are more than one sysadmin.
2) A key with passphrase isn't an easy thing to hack, and requires you to have both the private key AND the passphrase. No need for 127c long passphrases too, since if at any point you suspect the key is compromised, you go to number 1.

Regarding how keys work, they aren't difficult (well, I run linux).
This wiki has all the info you need: https://wiki.archlinux.org/index.php/SSH_keys (go for RSA up to 2048, no reason to use something higher). If you have any problems you'll find me on irc or here.

Added bonus of keys:
Passwordless logins as long as the key is unlocked.
Passwordless logins if the key has no passphrase (great for server<>server communication).
filezilla, rsync, git, scp will all work... you guessed it: without a password :)

I suggest you spend some time on keys, it wouldn't take you more than a couple of hours to get them working.

**Comment by EdNett** [comment]
OK - I'll try that. I still need to know what happened:

Here are the logs.

barracuda log: https://gist.github.com/EdNett/5262ecbd6f995e3d484d
octopus log text: https://gist.github.com/EdNett/eaa93f03b7dcc4fa5644
barracuda cnf file: https://gist.github.com/EdNett/352f9d13132187275dc1
octopus cnf file: https://gist.github.com/EdNett/a3b55b50d589b9a02ec8

**Comment by omega8cc** [comment]
You should edit `/usr/etc/sshd_config` and not `/etc/ssh/sshd_config` if you want to change your SSH configuration.
