### ISSUE TITLE
Required /dev/pts/ptmx does not exist! We will fix this now...

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#788]
On a regular `barracuda up-stable` I see the following false positive error:
```
Required /dev/pts/ptmx does not exist! We will fix this now...
rm: cannot remove `/dev/pts/0': Operation not permitted
```

My fstab already has two entries for devpts -- one added by default at OS install and the other added by boa installer:
```
devpts                /dev/pts        devpts  defaults        0       0
devpts          /dev/pts        devpts  rw,noexec,nosuid,gid=5,mode=620 0  0
```

`cat /proc/mounts | grep devpts` also returns the expected results:
```
devpts /dev/pts devpts rw,nosuid,noexec,relatime,mode=600 0 0
```

**Comment by omega8cc** [comment]
Hmm, where this happens? I mean your host, OS etc?

**Comment by pricejn2** [comment]
This is a dedicated server with OVH running Debian Wheezy.

**Comment by omega8cc** [comment]
Hmm, we should somehow detect this and not apply VM specific stuff to dedicated box, perhaps.
