### ISSUE TITLE
BOA on Google Cloud

### ISSUE THREAD

**Issue by Pieter-Lab** [omega8cc/boa#793]
To Whom it may concern.

We are about to launch a BOA install on a Google Cloud VM.

Are there any issues or limitations your team is aware of when it comes to installing the BOA build on a Google Cloud VM.

Any information or insight would be greatly appreciated.

Regards

**Comment by omega8cc** [comment]
We don't have any experience with Google Cloud VM, but please share what you will find!

**Comment by Pieter-Lab** [comment]
Hi Guys

We would like to share our experience with the Google Cloud VM service.

Firstly we found that just doing a ssh into the box requires the Google Cloud SDK on your desktop.
Once you have gone through this process and setup ssh keys can you actually enter the box per normal using putty or terminal ssh.

In regards to FTP we have found it is best to use WinSCP with a key file, also if using the SFTP method you can get WinSCP to run a sudo command thus elavating you to sudo state on login.

The big issue we found is that Google Cloud service blocks outgoing port 25 and forces the usage of port 2525. All mails have to be relaid off the server, as Google doesn't want you to use their boxes for spamming. 

Because of this we could not receive any setup and welcome mails sent out by BOA.

We found that the BOA setup script does not have the power to write to the postfix config, even when we placed the smtp relay options into the BOA config script, it still could not change nor setup postfix to use the relay mail server, with the addition of the port 2525 suffix.

We had to go and manually setup postfix to use the mail server relay on port 2525 using smtp authentication.
This worries us, because what will happen when we do a BOA upgrade?

Lets us know your thoughts.
Kind Regards

**Comment by Pls** [comment]
BOA generates setupmail text and upgrade logs, so having mail server is not required really.

Setup mail (which get's emailed after installation):
>/data/disk/o1/log/setupmail.txt

Upgrade logs:
>/var/backups/reports/up/barracuda/*
 > /var/backups/reports/up/octopus/*

**Comment by omega8cc** [comment]
BOA will not touch your SMTP / Postfix stuff. It is rare problem, in our experience, but we could add some helpful docs, I think.

**Comment by omega8cc** [comment]
BOA will not overwrite custom SMTP server configuration, so if your host requires custom configuration, it's perfectly doable. We are doing it on some remotely supported BOA systems for years, although we don't use Google Cloud VMs.
