### ISSUE TITLE
duplicity: error: Bad time string "YBFC"

### ISSUE THREAD

**Issue by andrilablateral** [omega8cc/boa#795]
I have set up a new BOA instance and after that configured a S3 Bucket with default access policy.

When I run "backboa backup" command I get the following error:

duplicity: error: Bad time string "YBFC"

The acceptible time strings are intervals (like "3D64s"), w3-datetime
strings, like "2002-04-26T04:22:01-07:00" (strings like
"2002-04-26T04:22:01" are also acceptable - duplicity will use the
current time zone), or ordinary dates like 2/4/1997 or 2001-04-23
(various combinations are acceptable, but the month always precedes
the day).

Any ideas ?

**Comment by omega8cc** [comment]
Please post all relevant variables you have set in your .barracuda.cnf

**Comment by andrilablateral** [comment]
thank you - here's my .barracuda.cnf (I removed sensitive information as to not expose to the public)
-----------------------------------------------------

###
### Configuration created on 150331-1110
###
_LOCAL_NETWORK_HN=""
_LOCAL_NETWORK_IP=""
_MY_FRONT="server.domain.uk"
_MY_HOSTN="domain.uk"
_MY_OWNIP="11.11.11.11"
_SMTP_RELAY_HOST=""
_SMTP_RELAY_TEST=YES
_THIS_DB_HOST=localhost
###
_AUTOPILOT=NO
_DEBUG_MODE=NO
_MY_EMAIL="email@domain.uk"
_XTRAS_LIST="CSF CHV FTP"
###
_MODULES_FIX=NO
_MODULES_SKIP=""
_PERMISSIONS_FIX=NO
###
_CPU_CRIT_RATIO=9
_CPU_MAX_RATIO=6
_CPU_SPIDER_RATIO=3
###
_DB_BINARY_LOG=NO
_DB_ENGINE=InnoDB
_DB_SERIES=5.5
_DB_SERVER=MariaDB
_INNODB_LOG_FILE_SIZE=AUTO
###
_DNS_SETUP_TEST=YES
_EXTRA_PACKAGES=
_FORCE_GIT_MIRROR=""
_LOCAL_DEBIAN_MIRROR=ftp.debian.org
_LOCAL_UBUNTU_MIRROR=archive.ubuntu.com
_NEWRELIC_KEY=##################################################
_SCOUT_KEY=
###
_NGINX_DOS_LIMIT=300
_NGINX_EXTRA_CONF=""
_NGINX_FORWARD_SECRECY=NO
_NGINX_LDAP=NO
_NGINX_NAXSI=NO
_NGINX_SPDY=NO
_NGINX_WORKERS=AUTO
###
_PHP_CLI_VERSION=5.5
_PHP_EXTRA_CONF=""
_PHP_FPM_DENY=""
_PHP_FPM_VERSION=5.5
_PHP_FPM_WORKERS=AUTO
_PHP_GEOS=NO
_PHP_MONGODB=NO
_PHP_MULTI_INSTALL="5.5"
_PHP_SINGLE_INSTALL=
###
_REDIS_LISTEN_MODE=PORT
_RESERVED_RAM=0
_SPEED_VALID_MAX=3600
_SSH_FROM_SOURCES=NO
_SSH_PORT=22
_SSL_FROM_SOURCES=NO
_STRICT_BIN_PERMISSIONS=YES
_STRONG_PASSWORDS=NO
###
_CUSTOM_CONFIG_CSF=NO
_CUSTOM_CONFIG_LSHELL=NO
_CUSTOM_CONFIG_REDIS=NO
_CUSTOM_CONFIG_SQL=NO
###
_AEGIR_UPGRADE_ONLY=NO
_SYSTEM_UPGRADE_ONLY=NO
###
_AWS_KEY='##################'     ### [R] From your AWS S3 settings
_AWS_SEC='##################################' ### [R] From your AWS S3 settings
_AWS_PWD='##############'       ### [R] Generate with 'openssl rand -base64 32'
_AWS_REG='eu-west-1'         ### [R] By default 'us-east-1'
_AWS_TTL='Your Backup Rotation'       ### [O] By default '30D'
_AWS_FLC='Your Backup Full Cycle'     ### [O] By default '7D'
_AWS_VLV='Your Backup Log Verbosity'  ### [O] By default '1'
_AWS_PRG='Your Backup Progress'       ### [O] By default 'NO' -- can be YES/NO

**Comment by omega8cc** [comment]
You should either specify some valid values for the entries shown below, or omit them, and not paste them with placeholders/comments as values:

```
_AWS_TTL='Your Backup Rotation' ### [O] By default '30D'
_AWS_FLC='Your Backup Full Cycle' ### [O] By default '7D'
_AWS_VLV='Your Backup Log Verbosity' ### [O] By default '1'
_AWS_PRG='Your Backup Progress' ### [O] By default 'NO' -- can be YES/NO
```

**Comment by andrilablateral** [comment]
doh - cant believe i missed that! 

Thank you - it;s working great now!

**Comment by omega8cc** [comment]
Thank you for the confirmation!
