### ISSUE TITLE
Redis log is empty. Can't access anything from redis-cli.

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#796]
I can't verify whether redis is working properly or not. I just migrated a big site to its own BOA (finally) from an old custom server, and dumped memcached for redis.

The redis log file (only one under var/log/redis) is more less empty, with this in it:
```
30076:M 12 Oct 03:03:48.690 # Server started, Redis version 3.0.4
30076:M 12 Oct 03:03:48.690 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis/redis-server.log (END)
```

Is this expected?
How can somebody verify that redis is indeed working for Drupal?
Cache tables in the db are full. I don't know if this is ok, with memcache they used to be empty.

Thanks

**Comment by bserem** [comment]
I'm closing this, the monitor command on a site with traffic (I was afraid to run it at first) shows that it works. Sorry for being hesitant.
I was expecting less mysql requests though :)

**Comment by omega8cc** [comment]
$ cat /root/.redis.pass.txt (to be used in step #3)
$ redis-cli
$ AUTH password
$ monitor

**Comment by omega8cc** [comment]
Cache tables will be purged nightly, when SQL backups run. They are not used when Redis is active on the site.

**Comment by bserem** [comment]
Thanks for clearing this up.

Will the tables be purged when backups are disabled?

**Comment by omega8cc** [comment]
> Will the tables be purged when backups are disabled?

No. But make sure to not confuse remote S3 backups with built-in BOA backups, stored in `/data/disk/arch/sql`:

https://github.com/omega8cc/boa/blob/master/aegir/tools/system/mysql_backup.sh#L24

**Comment by bserem** [comment]
Ok.

Since the tables aren't used under normal operation I guess it doesn't hurt if they don't get purged.

**Comment by omega8cc** [comment]
It does matter when you import a site with cache garbage accumulated there. You should aim to make your SQL server fast, and leaving outdated garbage in these tables can lead to weird problems during system upgrades, Redis restarts etc, when even momentarily the site may attempt to load these tables.

**Comment by omega8cc** [comment]
Also, it will dramatically slow down operations in Aegir, because it will dump and import all existing tables, no matter if used, on every Clone and Migrate task.

**Comment by bserem** [comment]
I see.

The DB is a bit huge (uncompressed about 10gb) so I am worried about running backups, but I guess the pros are more than the cons :)
