### ISSUE TITLE
Advagg 2.16 and BOA 2.4.6 strip characters from JS

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#797]
On a fresh BOA installation, with Advagg enabled I am experiencing a strange issue. Some (one atm) characters are being stripped from our JS.

I'm pasting a git diff with what I did to solve the problem:
```
-    var close = $('<a href="javascript:void(0)" type="button" class="close" aria-label="Close"><span aria-hidden="true">×</span></a>').appendTo(this.element);
+    var close = $('<a href="javascript:void(0)" type="button" class="close" aria-label="Close"><span aria-hidden="true">x</span></a>').appendTo(this.element);
```

The first "x" comes from character map, I can't really recall which one it is, but it is an X icon to be used either in multiplication sequences or as a close signal.
The second line, the updated one, uses a normal "x" as we type it from the keyboard.

So, the first line was working (with advagg 7.x-2.11) up until a switch to BOA and Advagg 7.x-2.16 (bundled with boa).
Could this be a security measure by BOA?

Thanks

**Comment by omega8cc** [comment]
BOA doesn't filter the output like this. It could be a bug in the AdvAgg module or incompatibility with your theme, etc.

Have you tried to purge all aggregates and advagg tables with aggressive option in the site admin, followed by clearing all caches and restarting Redis?

**Comment by bserem** [comment]
I tried drastic measures in advagg but I never restarted Redis.
I'll do so by night.

Closing this issue since it is not BOA related.

**Comment by bserem** [comment]
This
```
-    var close = $('<a href="javascript:void(0)" type="button" class="close" aria-label="Close"><span aria-hidden="true">×</span></a>').appendTo(this.element);
+    var close = $('<a href="javascript:void(0)" type="button" class="close" aria-label="Close"><span aria-hidden="true">&#739;</span></a>').appendTo(this.element);
```
did the trick. The html notation is NOT of the same character as before, but it suits the theme just fine.

That was a weird issue.

**Comment by omega8cc** [comment]
Interesting.
