### ISSUE TITLE
Could not find the alias mysite.local [Error]

### ISSUE THREAD

**Issue by shmeterlin** [omega8cc/boa#800]
I'm trying something like ssh username.ftp@siteip 'drush @mysite status' and get the above error. 

The var/aegir/.drush folder has the file mysite.local.alias.drushrc.php and no errors were reported on install other than maybe some regular notice.

Not being able to work on drush using root or cd out of username.ftp folder means no drush.

Any ideas?

**Comment by omega8cc** [comment]
Apparently you are trying to access sites on the Master instance using account from the Satellite instance. This is not going to work.

**Comment by shmeterlin** [comment]
I don't quite follow.

I've created a client (other than the admin) then a platform with a site on it. I have boa installed on my vmware guest machine so I ssh into the o1.ftp account and try drush sa and get the response @none even though the right files are present in the .drush folder. 

Any other drush command tells me that I need to be in a valid drupal folder but those are setting on my /var/aegir/platforms/sites folder which can't be accessed by the o1.ftp user only by root and root can't use drush for security measures so it's almost like catch 22 here.

Of course I can grant o1.ftp access to the var/aegir/platform folder but there must be a better way.

What am I missing here?

**Comment by omega8cc** [comment]
There are two important things here:

1. You should NOT use the Aegir Master instance for sites, only the Octopus instance
2. BOA does everything to keep all Aegir instances jailed, so they can’t cross the walls

Just start using Octopus for sites and move there all sites from the Master instance.

**Comment by omega8cc** [comment]
Of course you can use Drush on Master instance, if you wish, but only with that instance system user `aegir`:

`$ su -s /bin/bash - aegir`
`$ drush @sitealias status`

etc.

**Comment by shmeterlin** [comment]
So I'm trying to install a new instance with: 

$ boa in-stable local mail@mail newuser

I'm using root but I get a permission error and another fatal error (can't find file). Here's the notices:

SQLSTATE[28000] [1045] Access denied for user                [error]
'o1'@'localhost' (using password: YES) [6.48 sec, 10.07 MB]
Returned from hook drush_db_provision_migrate_validate [6.48     [debug]
sec, 9.25 MB]
Command dispatch complete [6.48 sec, 9.22 MB]                   [notice]
Returned from hook drush_provision_hostmaster_migrate [6.5       [debug]
sec, 10.04 MB]
Command dispatch complete [6.5 sec, 9.99 MB]                    [notice]
BOA [14:47:49] ==> UPGRADE B: Hostmaster STATUS: Upgrade completed
BOA [14:47:49] ==> UPGRADE B: Simple check if Aegir upgrade is successful
BOA [14:47:49] ==> UPGRADE B: FATAL ERROR: Required file does not exist:
BOA [14:47:49] ==> UPGRADE B: FATAL ERROR: /data/disk/o1/aegir/distro/002/sites/o1.sub.aegir.local/settings.php

Any Ideas?

**Comment by omega8cc** [comment]
The "local" mode is not guaranteed to work. Usually the "public" mode s used for local tests, but we don't recommend it. It was discussed in several issues.
