### ISSUE TITLE
New OpenSSH config in /usr/etc/sshd_config have no custom Port setting

### ISSUE THREAD

**Issue by netdream** [omega8cc/boa#806]
I found a possible bug: during the nightly upgrade, the script that configures the new version of OpenSSH daemon ignored the custom port setting and went back to the standard port 22 (...and leaving me locked outside, because csf is still set to the custom port...)

In my environment, it happened to all the instances where is set _SSH_FROM_SOURCES=YES, I'm not able to confirm if it happens also using standard package.

My .barracuda.cnf states:
_SSH_FROM_SOURCES=YES
_SSH_PORT=22003

It's something related to the new OpenSSH 7 (#805), with the relocation of the config file to /usr/etc/sshd_config, because I've always used _SSH_FROM_SOURCES before, without any issue.

**Comment by omega8cc** [comment]
Please attach via Gist your complete .barracuda.cnf file.

**Comment by omega8cc** [comment]
It should work unless you have set `_CUSTOM_CONFIG_CSF=YES`

```
    sed -i "s/notify\@omega8.cc/${_MY_EMAIL}/g" /etc/csf/csf.conf &> /dev/null
    sed -i "s/TCP_IN = \"20,21,22,/TCP_IN = \"20,21,${_SSH_PORT},/g" \
      /etc/csf/csf.conf &> /dev/null
    chmod 600 /etc/csf/csf.conf &> /dev/null
    if [ -e "/etc/ssh/sshd_config" ]; then
      sed -i "s/^Port.*/Port ${_SSH_PORT}/g"  /etc/ssh/sshd_config
      sed -i "s/^#Port.*/Port ${_SSH_PORT}/g" /etc/ssh/sshd_config
    fi
    if [ -e "/usr/etc/sshd_config" ]; then
      sed -i "s/^Port.*/Port ${_SSH_PORT}/g"  /usr/etc/sshd_config
      sed -i "s/^#Port.*/Port ${_SSH_PORT}/g" /usr/etc/sshd_config
    fi

```

**Comment by netdream** [comment]
Sorry, maybe I didn't explained it very well...
The csf.conf is ok (it is updated to the custom port 22003).
The problem is in /usr/etc/sshd_config: there is just the default line "#Port 22", commented and not substituted by "Port 22003"

**Comment by tourtools** [comment]
same behaviour, as @netdream, i've just done a "barracuda up-stable" to update debian packages, but the ssh port was reset from mine custom (.barracuda.cnf _SSH_PORT=22930, still there) to the default 22.

**Comment by netdream** [comment]
I confirm the problem on two other systems, also when using standard port, but ssh from sources:
_SSH_FROM_SOURCES=YES
_SSH_PORT=22

The file /usr/etc/sshd_config was left unchanged (it contained `#Port 22`, still commented, while last `sed` execution should update it).
When I executed by hand your piece of code, it worked as expected.

So, I suppose it is something related to the sed execution... 

I have a possible idea: I found a similiar problem on other environments (Google Cloud, AWS) when executing a list of sed commands on the same file using the "-i" parameter, that I think have I/O limitations.

`sed -i` updates a file by copying it to a temporary file, making changes and copying it back.
It seems (many references of this in the net) that it is not really safe when doing it multiple times in the same (large) file: sometimes the new "sed" starts before the old one finished swapping files...

Safer way is to list all the changes in a single execution, like:
`sed -i "s/^Port.*/Port ${_SSH_PORT}/g;`
`        s/^#Port.*/Port ${_SSH_PORT}/g;" /usr/etc/sshd_config`

What do you think of it?

Also, I found another issue on the sed command that updates csf.conf: if you change 2 times the _SSH_PORT, second time port can't be updated with your code!

It should be updated like this:
`sed -i "s/TCP_IN = \"20,21,.*,53/TCP_IN = \"20,21,${_SSH_PORT},53/g" \`
`      /etc/csf/csf.conf &> /dev/null`

If you want, there is a pull request from which you can cherry pick this last one...

**Comment by omega8cc** [comment]
Nice find, thanks! Can you please create clean PR, so we could properly merge it in? It is not possible to cherry pick on GitHub when accepting PR.

**Comment by omega8cc** [comment]
As for `/etc/csf/csf.conf` -- it doesn't present any problem, I think, because we first copy a clean template there:

```
cp -af ${locCnf}/csf.conf /etc/csf/csf.conf
```

**Comment by omega8cc** [comment]
It is not always possible to use single line `sed` for multiple replacements (at least without making the code unreadable and prone to errors). But there is a method to make sure the every `sed` is completed before running another. Like this:

```
      sed -i "s/^Port.*/Port ${_SSH_PORT}/g"  /usr/etc/sshd_config
      wait
      sed -i "s/^#Port.*/Port ${_SSH_PORT}/g" /usr/etc/sshd_config
      wait
```

**Comment by netdream** [comment]
Nice, there are only 1270 "sed -i" executions to update in boa scripts :-) (ok, not all of them are running on the same file in a short timeframe...)

It would be interesting to understand why it happened only now... what i can say is that all my involved systems are running on Debian 7.x, with sed 4.2.1-10

Maybe is something related to a sed bug in Debian 7: 
http://sourceforge.net/p/gnuwin32/bugs/534/
http://sourceforge.net/p/gnuwin32/bugs/477/

**Comment by omega8cc** [comment]
Let's hope it is fixed now.
