### ISSUE TITLE
googlebot can't access sites over https://

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#809]
On my BOA 2.4.6 server, googlebot is unable to access any site that uses SSL. At first I thought it was because they don't support TLS 1.2 but it seems they do now: https://dev.ssllabs.com/ssltest/viewClient.html?name=Googlebot&version=Feb%202015&_ga=1.15683126.1816188030.1446145585

Any ideas?

**Comment by omega8cc** [comment]
Please post your HTTPS vhost contents. Some old templates blocked access for all bots by default (a few years ago).

**Comment by LunkRat** [comment]
Yes, ok, I did find this in the server block of each SSL site:
```
if ($is_crawler) {
    return 403;
}
```
But when I remove it and restart nginx the problem is still there. Here is the config for one of the affected sites, from `/var/aegir/config/server_master/nginx/pre.d/extra_ip_ssl.conf`
```
server {
  listen                       REDACTED:443;
  server_name                  _;
  ssl                          on;
  ssl_certificate              /etc/ssl/private/REDACTED.crt;
  ssl_certificate_key          /etc/ssl/private/REDACTED.key;
  ssl_session_timeout          5m;
  ssl_protocols                TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                  RC4:HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers    on;
  keepalive_timeout            70;
  ###

  if ($deny_on_high_load) {
    return 503;
  }

  location / {
    proxy_pass                 http://extra_ip_ssl;
    proxy_redirect             off;
    gzip_vary                  off;
    proxy_buffering            off;
    proxy_set_header           Host              $host;
    proxy_set_header           X-Real-IP         $remote_addr;
    proxy_set_header           X-Forwarded-By    $server_addr:$server_port;
    proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header           X-Local-Proxy     $scheme;
    proxy_set_header           X-Forwarded-Proto $scheme;
    proxy_pass_header          Set-Cookie;
    proxy_pass_header          Cookie;
    proxy_pass_header          X-Accel-Expires;
    proxy_pass_header          X-Accel-Redirect;
    proxy_pass_header          X-This-Proto;
    proxy_connect_timeout      180;
    proxy_send_timeout         180;
    proxy_read_timeout         180;
    access_log                 off;
    log_not_found              off;
  }
}

**Comment by omega8cc** [comment]
Please remove also:

```
  if ($deny_on_high_load) {
    return 503;
  }
```

**Comment by LunkRat** [comment]
Brilliant, that worked immediately! Thank you again @omega8cc

**Comment by lhaithaes** [comment]
Hi we have seen a dramatic increase in 403's since moving to BOA aegir and then going onto https via letsencrypt. Moz & Google Search Console both indicate this. 

what places do i remove this function? only I'm getting worried about our seo performance. i see..

 if ($is_crawler) {
    return 403;
  }

in # /var/aegir/config/server_master/nginx/pre.d/nginx_wild_ssl.conf
