### ISSUE TITLE
uname -n does not return fqdn after reboot

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#810]
After rebooting the server `uname -n` does not return the fqdn:

~~~
$ hostname -f
node.example.com
$ uname -n
node
~~~

As a result `backboa` does not backup any more, because the s3 bucket name changed. 

Any ideas, how to fix this?

[Config Files](https://gist.github.com/luxio/16525f89019dac61fd42)

**Comment by omega8cc** [comment]
You should fix this manually. Then investigate why your parent system ignored existing hostname and reverted it.

**Comment by omega8cc** [comment]
Example:

```
        hostname -b node.example.com
        echo "node.example.com" > /etc/hostname
        echo "node.example.com" > /etc/mailname
```
