### ISSUE TITLE
Document better BOA aggressive installation behavior and associated system requirements

### ISSUE THREAD

**Issue by millenniumtree** [omega8cc/boa#811]
The BOA install script is extremely unforgiving when it comes to any prior configuration of the server.

I made the mistake of actually setting a root password in mariadb before running the installer (standard practice, IMO), and have been battling with it ever since.

I added the mysql root password in ~/.my.pass.txt and ~/.my.cnf, but when I re-run "boa in-stable ...", these files are evidently REMOVED again.
To work around that, I finally made them immutable with
chattr +i /root/.my.pass.txt
chattr +i /root/.my.cnf

The script should attempt to access mysql right away.  If access fails, it should keep asking for passwords until you enter something that works.  Without mysql access, there is no hope, and it's an easy check.

You also have to wait through the PHP compile every time you run it.  Can this be skipped if it has already been done?

Where the BOA.sh.txt script symlinks /usr/local/bin/boa, barracuda, octopus...
It first checks if /data/disk is missing before adding the symlinks.  This makes no sense and left me without those symlinks after the second attempt.  Could it instead check to see whether the symlinks are missing before adding them?
Instead of:
    if [ ! -e "/data/disk" ]; then
      ln -s ${optBin}/boa       /usr/local/bin/boa
      ln -s ${optBin}/barracuda /usr/local/bin/barracuda
      ln -s ${optBin}/octopus   /usr/local/bin/octopus
    fi
Use:
    if [ ! -h "/usr/local/bin/boa" ]; then
      ln -s ${optBin}/boa       /usr/local/bin/boa
      ln -s ${optBin}/barracuda /usr/local/bin/barracuda
      ln -s ${optBin}/octopus   /usr/local/bin/octopus
    fi

I understand this is intended to be run on a brand new VPS with no configuration, but as it stands, any small error in the install process and you have to re-image the VPS or manually reset anything the script might complain about.

Some more documentation about how to use "boa in-octopus ..." would be helpful too.  Re-running the same command with 'in-octopus' instead of 'in-stable' results in terrible things.  The parameters to in-octopus are very different

A bit of idiot-proofing is worthwhile, always.

**Comment by omega8cc** [comment]
>> I understand this is intended to be run on a brand new VPS with no configuration

That is the key here.

Also: https://github.com/omega8cc/boa/blob/master/README.txt#L97

**Comment by millenniumtree** [comment]
Could you provide some reasonable explanation why the script does not check
for mysql access before proceeding?
Also maybe why it removes your .my.cnf, .my.pass.txt files?

I've written a fair share of bash scripts, and this seems to be a very
minimal request which would have saved me almost 10 hours of
troubleshooting over the last 2 days.

We have about 150-200 drupal sites we manage right now, and BOA seems like
the most sensible solution to bring them all 'into the fold'.  I'm thrilled
to be migrating to the platform, and will have plenty of questions along
the way for Aegir and Octopus.  With how normally helpful the Drupal
community is, I'm a bit disappointed with the entirely dismissive response
I got here.

If you'd like, I can write a few lines of code for the top of the script to
prevent this in the future.
Imagine if I had tried this on a physical machine instead of a VPS?
Re-imaging a drive is just not feasible.

Thanks for your time,
--Steve

**Comment by millenniumtree** [comment]
These sorts of 'check before doing' rules might also allow the script to work on more platforms.
This is the "./configure" step before "make".

Here are a few lines that solve the DB password problem without impacting users that use the script as you demand.

echo "SHOW DATABASES" | mysql > /tmp/test.tmp
if [ ! -f /tmp/test.tmp ] || [ ! -s /tmp/test.tmp ]; then
  echo 'Database password issue - please set password in ~/.my.cnf'
fi
rm -f /tmp/test.tmp

**Comment by omega8cc** [comment]
It is a *requirement* that the system is a **minimal** OS install with **no** services installed (beyond SSH server).

It is a bad idea to introduce workarounds for situations like this.

Instead, it could be a good idea to explain this better at the of the README, I think. In fact, it was previously clearly listed but somehow got lost after some rewrites.

BOA is very aggressive and demanding by design, and for very good reasons. We don't have time to support and troubleshoot all crazy things people could do if BOA would allow to ignore its forced install mode.

**Comment by omega8cc** [comment]
But sure, we could add some check to simply stop if boa detects mysql, apache, nginx etc, already installed.
