### ISSUE TITLE
accidentaly removed the root folder

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#814]
This a very stupid mistake i made but i deleted the root folder. I have previously posted here some issues and i can thanks to your guidelines for contributing recover my config files for octopus and barracuda. 
However i would like to have a reminder of what was there before (means default files created by baracuda)  to be able to run my server without  any issue after.

**Comment by omega8cc** [comment]
Wow. You have deleted `/root`? Then you are out of luck and we can't help, unless you have a backup which includes this directory. Basically, you have trashed all instances config files and mysql root password files etc. Pretty stupid mistake, indeed.

You need to manually create expected config files, set new mysql root password etc.

**Comment by yazzou** [comment]
I have thought to reinstall completely barracuda and octopus on the server. I have all sites running and i got a back up for each site. Would that fix my issue ?

**Comment by omega8cc** [comment]
Honestly, I don't know how you could plan to fix this. We have never tested such situation.
