### ISSUE TITLE
Allow to disable redis.path.inc feature via INI variable (enabled by default)

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#815]
I know BOA comes with Redis and makes it work magically (and I like it). However, I saw two redis folders under /data/all/000/modules, one called redis and one called redis_edge. The second one has the extra file redis.path.inc

How come there are two of them?
Which one is being used by Drupal?

I wanna give this a try: https://www.drupal.org/node/2342643 which, as far as I can tell, is not yet provided by BOA by default.

Thanks

**Comment by bserem** [comment]
Btw, after adding this:
[code]$conf['path_inc'] = '../../../../..//data/all/000/modules/redis_edge/redis.path.inc';[/code]
I made redis cache paths (it created a 'paths' bin). I even 'killed' paths.inc inside drupal, by adding a couple of exit(); calls and my site continued to work just fine.

**Comment by bserem** [comment]
On the other hand, when trying to enable the above on a different site (same server, same platform, same everything) I'm getting the following:
[code]Error: Class 'Redis_Client' not found in /data/all/000/modules/redis_edge/redis.path.inc, line 20[/code].

Pursuing...

**Comment by omega8cc** [comment]
The `redis_edge` is the version used by default, while `redis` is a legacy, patched version. Soon `redis_edge` will be 3.x (not used yet) and `redis` will be 2.x (the version used now). Anyway, the `redis.path.inc` feature could be optionally enabled via INI variable, perhaps.

**Comment by bserem** [comment]
Excellent!

I'd like to link #861 here just in case.
