### ISSUE TITLE
Possible to check say every 5 minutes if redis is running, and if not run restart command untill running (and not restart failed)?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#816]
Hi, I notices on the lates head redis was not running correctly, and had to run the restart command like 3 times until it was ok. I am worried that for whatever reason throughout the day redis may stop running. I woul like to know If I        could have like a functio , like every 5 minutes to heck reis status, and if redis wasnt runign to a reload until a successful restart, (not failed)... thanks

**Comment by omega8cc** [comment]
It is always monitored and restarted if needed, every 10 seconds.
