### ISSUE TITLE
Cannot create new octopus user due to system checkings

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#817]
After upgrade to BOA 2.4.6 I tried to create a new extra octopus user with the "boa in-stable ..." command, but I've got an error due to the system checkings:

```
srv2:~# boa in-stable public srv2.mydomain.org o3@email.com o3 mini
ERROR: BOA requires minimal, supported OS, with no services installed
ERROR: The only acceptable exceptions are: sshd and mail servers
Bye
```

Which is the right command to add an extra octopus user now to skip these checks?
If the process has changed, last paragraph in INSTALL.txt should be updated

**Comment by omega8cc** [comment]
It was a 1-day regression. Please update your installers first:

`$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`

**Comment by ixiam** [comment]
yes I've updated the installers, but getting the same error.

**Comment by omega8cc** [comment]
Ah, you are using wrong command.

The syntax is: https://github.com/omega8cc/boa/blob/BOA-2.4.6/CHANGELOG.txt#L1350

**Comment by omega8cc** [comment]
We should update our docs, though.

**Comment by ixiam** [comment]
ah ok, thanks for the lead.
Yes, it's a good idea to update INSTALL.txt 
( I always use it when don't remember the commands :) )
https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L124

**Comment by omega8cc** [comment]
Yeah, thanks for the heads-up!
