### ISSUE TITLE
Aegir's task queue stopped running, interrupted upgrade resulted in intermittent site availability

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#818]
Aegir's task queue is set to run every 5 seconds, but has not run in ten hours and before that had not run in two days

I did `barracuda up-stable` hoping that it would solve the problem.  But it stalled on `running aptitude full-upgrade`, so we finally killed the apt process and the BOA upgrade continued.
The server immediately ceased to serve any of the production sites it's hosting, so we ran the `barracuda up-stable` again.
That was followed by intermittent availability -- trying to visit hosted websites resulted in `ERR_CONNECTION_REFUSED` and `502 Bad Gateway`.

The Aegir task queue still won't run; queued tasks just sit in queue without being executed.  I tried deleting the variables `hosting_queue_cron_last_run: 1446777664` and `hosting_queue_tasks_last_run: 1446778151` per https://github.com/omega8cc/boa/issues/32#issuecomment-400531 but that didn't solve it.

Not being able to run Aegir tasks is problematic, but the intermittent availability is a much bigger problem.

Contents of .barracuda.cnf etc here https://gist.github.com/ahillio/abe3dfb0cdbf354d4f9d.

Is there anything you recommend?

Thank you!

**Comment by omega8cc** [comment]
It sounds like you have problems either with DNS or firewall, or it is broken curl or git.

Please add our keys there and send system IP to omega8cc at gmail dot com, and we will take a look.

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab https://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
```

**Comment by ahillio** [comment]
Sent.  Thank you!

**Comment by omega8cc** [comment]
You should never kill such updates before checking what they are doing. It was a very bad idea and now you have stuck kernel updates:

```
20299 pts/6    Ss+    0:00  \_ /bin/bash
29369 pts/6    S      0:00 /bin/sh -e /etc/kernel/postinst.d/initramfs-tools 3.13.0-67-generic /boot/vmlinuz-3.13.0-67-ge
29371 pts/6    S      0:00  \_ /bin/dash /usr/sbin/update-initramfs -c -t -k 3.13.0-67-generic -b /boot
29373 pts/6    S      0:00      \_ /bin/dash /usr/sbin/mkinitramfs -o /boot/initrd.img-3.13.0-67-generic.new 3.13.0-67-ge
30858 pts/6    S      0:00          \_ /bin/sh /usr/share/initramfs-tools/hooks/cryptroot
30866 pts/6    S      0:00              \_ /bin/sh /usr/share/initramfs-tools/hooks/cryptroot
30868 pts/6    S      0:00                  \_ /bin/sh /usr/share/initramfs-tools/hooks/cryptroot
30869 pts/6    D      0:00                      \_ vgs --noheadings -o pv_name clouding
```

```
19909 pts/6    S      0:00 sh -c DPKG_NO_TSTP=1 dpkg --configure -a
19910 pts/6    S      0:00  \_ dpkg --configure -a
19913 pts/6    S      0:00      \_ /usr/bin/perl /var/lib/dpkg/info/linux-image-3.13.0-67-generic.postinst configure
19938 pts/6    S      0:00          \_ run-parts --verbose --exit-on-error --arg=3.13.0-67-generic --arg=/boot/vmlinuz-3.
20076 pts/6    S      0:00              \_ /bin/sh -e /etc/kernel/postinst.d/initramfs-tools 3.13.0-67-generic /boot/vmli
20078 pts/6    S      0:00                  \_ /bin/dash /usr/sbin/update-initramfs -c -t -k 3.13.0-67-generic -b /boot
20080 pts/6    S      0:00                      \_ /bin/dash /usr/sbin/mkinitramfs -o /boot/initrd.img-3.13.0-67-generic.
21538 pts/6    S      0:00                          \_ /bin/sh /usr/share/initramfs-tools/hooks/cryptroot
21547 pts/6    S      0:00                              \_ /bin/sh /usr/share/initramfs-tools/hooks/cryptroot
21549 pts/6    S      0:00                                  \_ /bin/sh /usr/share/initramfs-tools/hooks/cryptroot
21550 pts/6    D      0:00                                      \_ vgs --noheadings -o pv_name clouding
```

I'm afraid it may result with bricked system once you will try to reboot.

**Comment by omega8cc** [comment]
Your system has processes which are not expected and can't be killed. You have tried too weird things. Please reboot and make sure there are no services running which are not a part of BOA stack.

**Comment by ahillio** [comment]
Yikes.  Thank you for inspecting that.

I can reboot... if there's a chance it will brick the system then maybe I should wait until after business hours since the sites are mostly available now?

Would it be safer to create a whole new BOA server and use https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt  to migrate this to that?

**Comment by omega8cc** [comment]
Yeah, I guess it is a good idea to migrate away from this system, since it is not guaranteed what will happen after reboot.

**Comment by ahillio** [comment]
Thanks for your guidance!

The xboa tool worked great.  But somehow all the sites and platforms that were imported disappeared from Aegir.  The site and platform files are still on the server, but nothing in Aegir.  The tasks that I ran a few hours ago have also disappeared from the /hosting/queues/tasks page.  There aren't any tasks showing that everything was deleted, it all just vanished.

**Comment by ahillio** [comment]
I created a new platform in Aegir from the existing codebase and that spawned import tasks for all the sites in the in platform.  But all of the import tasks failed with error like this `exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'mcw'@'localhost' (using password: YES)' in /data/disk/o1/static/standard-7.39.1/includes/database/database.inc:307`.

**Comment by ahillio** [comment]
So the migration with xboa seemed to work well, but while the script was running and importing sites a number of them had
```
load on system too heavy (5.47 4.8 4.37), aborting                                                                         [error]
Drush command terminated abnormally due to an unrecoverable error.                                                         [error]
```
though they seemed like they were successfully imported anyway.  But maybe that's why Aegir purged all the sites?

Anyway.  We just created a new BOA server (temporarily, until we move to your hosting service) and I'm importing all the sites individually as that's reliable.  Looking forward to being on your servers so I don't have to do this anymore!
