### ISSUE TITLE
Heads up for MariaDB 10.0.22 - bug or error in mysqli connect?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#819]
I don't mean to imply that you haven't already noticed this, but on a non-boa jessie server that I recently updated to MariaDB 10.0.22 - there is a change in the way mysqli connects to the database that causes a few scripts to fail:

formerly a "mysql -u root -p" command would allow one to enter in the mysql root password, however it now fails as it cannot connect to the db, and the only way to login is to use:
"mysql -u root -pPASSWORD" - entering the password directly after the flag with no space. This may be a non-issue with BOA, I don't know. Just trying to help.

regards,

Ed

**Comment by omega8cc** [comment]
Any such change never affects BOA, because we never run anything in the interactive mode.
