### ISSUE TITLE
Symlinking of js.php

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#821]
I have a custom platform where BOA does not add the js.php symlink to the Drupal core directory.

- BOA 2.4.6
- Created a new custom platform (D 7.41), with sites added to it
- `_PERMISSIONS_FIX=YES` in /root/.barracuda.cnf
- No platform overrides (no boa_platform_control.ini)
- Manually ran `bash /var/xdrago/daily.sh` (twice). The o_contrib_seven symlink was created as expected (and js module is present there), but the js.php symlink was not created.

Are there any other settings/configurations required for js.php symlinking I may have missed?

**Comment by ar-jan** [comment]
Edit: `daily.sh`, not `run-o2`.

**Comment by ar-jan** [comment]
Huh, is it possible that having the js module also in sites/all prevents the creation of the symlink? I ran daily.sh again after removing that copy, and this time the symlink was created.

**Comment by omega8cc** [comment]
No, it doesn't check for anything in sites/all. Not sure why it didn't work during the first run?
