### ISSUE TITLE
php-fpm: segfault 

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#822]
I am suddenly getting segmentation faults when calling drush commands (e.g. drush dis module) or accessing certain pages on the webpage.

Syslog:
~~~
Nov  9 20:07:36 aegir kernel: [ 9496.155225] php-fpm[120650]: segfault at 7ffecdd4bf78 ip 0000000000491a2a sp 00007ffecdd4be60 error 6 in php-fpm[400000+a31000]
Nov  9 20:07:36 aegir mysqld: 151109 20:07:36 [Warning] Aborted connection 7556 to db: 'developaegirlo_0' user: 'developaegirlo_0' host: 'localhost' (Unknown error)
~~~~

Any ideas what could cause this or how to debug it?

[Config Files](https://gist.github.com/luxio/16525f89019dac61fd42)

**Comment by luxio** [comment]
I have also got an email from boa (Subject: PHP Segfault Alert...):
~~~
### PHP: CRASH at 20:07:36 [1] discovered on 151109-200802 for develop.dev.aegir.local
### SYS: Nov  9 20:07:36 aegir kernel: [ 9496.155225] php-fpm[120650]: segfault at 7ffecdd4bf78 ip 0000000000491a2a sp 00007ffecdd4be60 error 6 in php-fpm[400000a31000]
### NGX: "192.168.114.1" example.com [09/Nov/2015:20:07:36 0100] "GET /admin/structure/features/module/diff HTTP/1.1" 502 568 2108 713 "http://example.com/admin/structure/features" "Mozilla/5.0 (Macintosh Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36" 33.373 "-"
### PTH: never
### VHT:
~~~

**Comment by angel0d** [comment]
i think you did not paste the complete email, did you ?

the most common segfault i've seen regards a known bug of PHP with files of exactly 4 kb

check if you have such files with

find /drupal/root/path -type f -size 4096c

**Comment by bserem** [comment]
It is this issue:
https://bugs.php.net/bug.php?id=52752

**Comment by omega8cc** [comment]
It is not BOA specific nor related, I think.

**Comment by luxio** [comment]
@angel0d I have deleted all 4k files, still getting the error.

**Comment by ar-jan** [comment]
You could try to `tail -f /var/log/syslog` and see if anything jumps out. For example, I've at some point seen segfaults because a module was trying to use an inaccessible/non-existant system path over and over.

**Comment by luxio** [comment]
@ar-jan thx, but the only things in syslog are the 2 lines I mentioned in my first post.

**Comment by angel0d** [comment]
@luxio could it be an 8kb file maybe ?

https://bugs.php.net/bug.php?id=48034

**Comment by omega8cc** [comment]
This could be also some bad PHP code in some of your views, or even duplicate views can cause this.

**Comment by luxio** [comment]
@omega8cc any hints how to debug this and find the "bad" php code?

**Comment by omega8cc** [comment]
You need to find and inspect any custom PHP code in views, check for duplicate views etc. The most obvious candidate is related to changes introduced in the site before it started to happen.
