### ISSUE TITLE
Having issues with site CRON

### ISSUE THREAD

**Issue by geofftech** [omega8cc/boa#825]
Hi Guys,

I am having issues with the sites CRON system. It works fine when the octopus instance is set to use "drush" for the cron. However, it seems to automatically revert to "wget" after about a day.

The wget method has a permission denied error and does not work. As soon as I log back into the octopus instance and change it back to "drush", it starts to work again.

This means I either have a problem with the octopus instance and it should not be reverting.

Or, the wget method should work.

Could you please help me debug this problem - I've hit a dead as to where to look.

Thanks in advance

Geoff

**Comment by omega8cc** [comment]
You should run BOA default (curl/wget) cron method, for best results and to avoid performance issues.

Please read everything at https://omega8.cc/running-scheduled-sites-cron-in-aegir-118 for details on when it may not work and how to fix this.

If nothing else works, please use this trick: #746

**Comment by omega8cc** [comment]
Well, we should document this.

**Comment by geofftech** [comment]
Hi Guys,

Thank you for your response.

Just for reference, this is a completely Vanilla BOA installation with nothing special happening.

So "wget" is the preferred method - and that is why it is being reverted back from the "drush" method every day. But the wget method fails.

When I run it manually from CLI to debug the error using the "wget" method via 
```bash
 /var/aegir/drush/drush.php @hostmaster hosting-cron --debug
```
I get the error
```
<em>http://domain.com/cron.php?cron_key=XXX</em> [15.52 sec, 33.09 MB]
WD hosting_cron: cron failed on site domain.com with error Forbidden [15.59 sec, 33.09 MB]                    [notice]
```
Also, when on wget, the site CRON is not being executed at the site level, so this error is probably what is causing the issue.

Any ideas as to what could be causing it? Or where I should be looking to debug it?

Thanks

**Comment by omega8cc** [comment]
You have probably the site protected with extra HTTP auth if it gets 403 response.

**Comment by omega8cc** [comment]
Please don't use `aegir` backed user for testing.

**Comment by omega8cc** [comment]
1. `su -s /bin/bash - o1`
2. `drush @hostmaster whatever`

**Comment by geofftech** [comment]
Wow, that was a quick response. Thanks

"extra HTTP auth" - this server is setup at AWS behind its firewall, so could it be a port that needs to be opened. It is a local wget so I has rejected that as a possible solution.

What would I need to open? Is this what you mean?

I was SSH'd as the octopus user when I ran the command - never as aegir. Occasionally ```root``` if I need to kick it hard.

**Comment by omega8cc** [comment]
I don't know any specific details of your setup, but there is a possibility that it is similar to this known problem: https://github.com/omega8cc/boa/blob/master/docs/CAVEATS.txt#L5 Just make sure that the server can connect to itself via its public IP address. Otherwise many other things will not work, not just cron.

**Comment by geofftech** [comment]
Thanks for your help - I am running Ubuntu, which in your caveats states is rarely tested. I will use the locked in drush option as per the link in your first email. And look at initialising the server in Debian in the future.

Thank you very much for your help.
