### ISSUE TITLE
No permission to edit node/task/queue

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#828]
Hi,
As stated here:
https://omega8.cc/aegir-task-fails-or-spins-forever-126
we should delete the task by going to the edit page.
With boa 2.4.6 this does not work anymore. If you go to edit you get the no permission error.
I'm not sure if this was already there in previous versions?
Thanks!

**Comment by omega8cc** [comment]
Just ignore the "error" and follow the how-to.

**Comment by timlie** [comment]
Maybe I was not clear.

I can't follow the howto because i have no acces to the page because:
You are not authorized to access this page.

I try this with the admin user.

**Comment by timlie** [comment]
Sorry!!!
I indeed had to just type delete.
