### ISSUE TITLE
Installing BOA and migrating single site to new server

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#829]
We are planning to move BOA system with our single website to larger host and wanted to clear some things. I know that there is 'xboa' tool, but it needs some practice to start using it in prod. We only have one single website, so manual import is not a problem I guess, xboa is mostly useful for large migrations with lots of sites, right? I would think manual rsync and mysql import would be easier in our situation. Do you agree?

1. Can we use same hostname on new BOA server install? Is this even possible? I guess we should add server1.website.com instead of server.website.com in our DNS settings to point to new server?
2. We use PHP 5.3 in old host and haven't tested new versions yet (although we know this version will be removed soon). So we can install BOA with 'boa in-stable public server1.mydomain.org my@email o1 none php-all' command? And then we can switch between versions from 5.3 to 5.6 easily?
3. Regarding previous question, it seems that newrelic can't be mixed together on install, so we should add the key to .cnf file and do the upgrade after install?

**Comment by omega8cc** [comment]
To migrate single site you could also take a look at: https://github.com/omega8cc/boa/blob/master/docs/REMOTE.txt

Or use standard site import how-to.

As for the system setup -- no extra magic is needed. Just follow standard procedures.
