### ISSUE TITLE
Support https://github.com/letsencrypt/letsencrypt/

### ISSUE THREAD

**Issue by thebennos** [omega8cc/boa#830]
Mozilla has an initiative 
https://github.com/letsencrypt/letsencrypt/

provides Free SSL Certificates for all. 

Setup is done via a python script. Nginx support is in development. 

Would be nice to integrate it with BOA an automatically generate SSL certificate and adjusting the config in one step.

**Comment by omega8cc** [comment]
This is a duplicate. Please search the queue first :-)
