### ISSUE TITLE
Reinstall broken BOA one same server (without wiping everything)

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#831]
I installed BOA partially, but had issues with DNS (had no proper subdomain wildcard in domain and now mysql connections are not working as expected).

Domain DNS records are updated right now, so we want to reinstall BOA (with forced init). However, there is critical error with o1 user already taken:

>ERROR: o1 username is already taken
>Please choose different username

Is it possible to do full forced BOA reinstall with partial/broken install? Should I manually delete octopus instance as described in https://github.com/omega8cc/boa/wiki/How-To-Delete-An-Octopus-Instance?

**Comment by omega8cc** [comment]
BOA doesn't use FQDN for SQL connections, only localhost. I would advise to first check what exactly doesn't work before attempting any destructive actions. You can't force clean re-install when there is an Octopus instance already installed (even partially), but you can either install/add new instance or rebuild services, as explained in the how-to:

https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L192
https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L202

**Comment by Pls** [comment]
Right, I made decision to wipe out everything and start again. But now I left one directory on /data/disk/o1/static directory and boa in-stable command seems skipped creating octopus user for that reason. Which then made bunch of errors about no permission to create stuff.

If I would delete octopus instance (using steps from wiki), should I again use this command:
>boa in-stable public server.domain.com my@email.com o1 none

Or maby I should install it with boa in-octopus command with o1 as user argument:

>boa in-octopus my@email.com o1 none

boa in-octopus command would skip master aegir install (it's working great now), but is it good practice to do so?

**Comment by Pls** [comment]
Ok, just documenting for myself and others in similar situation.

You can delete anyhow broken o1 octopus instance and install it again using simple command:
>boa in-octopus my@email.com o1 none

It works just fine. You just have to make sure that octopus instance was deleted properly before doing this command.

As for situation when /data/disk/o1 is not empty, I think BOA should check more if there are specific octopus files. Just checking if that directory is not empty is not perfect. Maby I'm overreacting here, but in my case that was creating problems, so I think we should evaluate if these checks are proper.

**Comment by omega8cc** [comment]
The current check is by design. Even empty `/data/disk/o1` should not exist to allow the script to use forced install mode.
