### ISSUE TITLE
Help request solving server down error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#832]
Hello, We had our BOA 2.4.6 stable (php 5.6 only for barracuda and octopus) server go down Dec 1 at about 17:18 UTC. we just noticed it and restarted the server via a hard start from the Server rental co's web interface. (there was no ssh access). There is nothing out of the ordinary in any of the .cnf files, with the possible exception of

barracuda file:
 _NGINX_FORWARD_SECRECY=YES
_NGINX_NAXSI=YES
_NGINX_SPDY=YES
_PHP_GEOS=YES
_USE_MYSQLTUNER=YES
_MODULES_FIX=YES
_PERMISSIONS_FIX=YES

There's nothing else in any BOA conf file that could be the source of this problem, and I doubt any of the above is causing any problems at all.

[So boa doesn't provide an email or sms notification of service down. Is that right? You recommend NewRelic or another monitoring service, I guess?].

I see these errors in /var/log/nginx/error.log:

2015/12/01 00:03:58 [crit] 7678#0: unlink() "/var/lib/nginx/speed/5b/05/14/6dbc53aabdfc1448f4f0a9342414055b" failed (2: No such file or directory)
2015/12/01 00:05:12 [crit] 7678#0: unlink() "/var/lib/nginx/speed/d9/a7/37/31241aaaf8cb808196a0b3768937a7d9" failed (2: No such file or directory)
2015/12/01 00:05:29 [crit] 7678#0: unlink() "/var/lib/nginx/speed/43/ed/26/f0b0ce8f34413cadfde0e2d0db26ed43" failed (2: No such file or directory)

and this notice in /var/log/nginx/speed_purge.log.1

speed_purge start Tue Dec  1 00:02:05 CET 2015
speed_purge complete Tue Dec  1 00:02:08 CET 2015

Those times don't really match the time when the server went down, and I can't seem to find anything in /var/log/* that gives me any useful information.

The last entry in the syslog before it went down is:
Dec  1 17:18:01 server1 kernel: Dec  2 06:00:27 server1 kernel: imklog 5.8.11, log source = /proc/kmsg started.

and just before that I see (should I be concerned about the guest-fire.sh being run?):

Dec  1 17:17:01 server1 /USR/SBIN/CRON[7846]: (root) CMD (/usr/local/rtm/bin/rtm 58 > /dev/null 2> /dev/null)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7847]: (root) CMD (   bash /var/xdrago/guest-fire.sh >/dev/null 2>&1)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7848]: (root) CMD (bash /var/xdrago/manage_ltd_users.sh >/dev/null 2>&1)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7849]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7850]: (root) CMD (bash /var/xdrago/minute.sh >/dev/null 2>&1)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7851]: (root) CMD (bash /var/xdrago/runner.sh >/dev/null 2>&1)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7852]: (aegir) CMD (/usr/bin/env php /var/aegir/drush/drush.php '@hostmaster' hosting-dispatch >/dev/null 2>&1)
Dec  1 17:17:01 server1 /USR/SBIN/CRON[7853]: (root) CMD (bash /var/xdrago/second.sh >/dev/null 2>&1)

lastly, 2 min before going down I see (is this cause for alarm? or a BOA malfunction? - we're seeing this on both octopus instances, for both backup and backup-delete tasks, and regularly; however these "tasks" do not show up in the octopus GUI, for which we have enabled "experimental" backup manager, backup scheduling/queue and task garbage collection):

Dec  1 17:16:07 server1 drupal: http://o3.server1.domain.com|1448986567|hostmaster|127.0.0.1|http://o3.server1.domain.com/||0||Attempt to backup-delete the Hostmaster site blocked.

I see in the Octopus Control Panle that for both octopus instances backups are not being made (Feature not available for the Hostmaster site.) but that under settings for the hostmaster site Backup settings is set to Default, and Scheduler Status is "Enabled"; Should we set this to off manually? - Octopus won't let me set this to disabled!

What could be causing this, and where do you suggest I look in the logs. Could this be a problem with an automated BOA cron or other run?

Or is this possibly a DDOS attack that took our server down (I see no evidence of such, and I see no evidence of anyone successfully loggin in - so that I don't believe we were hacked). I notice that at 17:18 December 1st the server "upload" traffic fell quickly to "0" (zero) for both traffic and packets - no errors. The download traffic was greatly reduced, but did not fall all the way to zero.

What could be causing this? This has happened before, and in fact happens about once a month. If someone wanted to "test" our server to see if we could handle a ton of traffic (or survive any common hacking attempt), could that "test" effectively cause our BOA server to go offline with no http or ssh access, so that we would have to do a hard reboot to get it up again? How ould someone most commonly do this? And how to protect againt it? (It's quite possible that we're being "tested" by people we are seeking VC from, and of course, if that is the case, we are failing the test! 

I appreciate any help on where to look in the logs. Thank you.

Ed

**Comment by omega8cc** [comment]
I don't see how it can have anything in common with BOA. These log entries are irrelevant. I would suggest to check the hardware and network, kernel panic etc.
