### ISSUE TITLE
Document new requirement: SSH keys for root

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#833]
BOA installs SSH from sources by default. We either need to revert to not install SSH from sources by default, or make sure that everyone understands that password based access for root will not work once BOA is installed or upgraded to current stable. This is a result of OpenSSH changes in recent releases and not BOA specific change.

**Comment by Juc1** [comment]
@omega8cc re "password based access for root will not work once BOA is installed or upgraded to current stable" - I have upgraded two password based access for root servers to 2.4.7 and with Digital Ocean (for example) you can only add keys at server creation ie not later - so am I now locked out of my servers??

**Comment by omega8cc** [comment]
You can add SSH keys easily on any server and not only on its creation. This is the first thing you should do before running boa installer. No, you are not locked out. You can modify `/etc/ssh/sshd_config` and reload `ssh` via console access and then add SSH keys. BTW,  anyone not using SSH keys for root is doing it wrong. It should be banned and OpenSSH did the right thing enforcing it.

**Comment by Juc1** [comment]
@omega8cc "You can add SSH keys easily on any server and not only on its creation. This is the first thing you should do before running boa installer." OK so I guess that should go in https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt etc Anyway re modifying /usr/etc/sshd_config - is that to allow root login with password while I set up SSH keys? What specifically in /usr/etc/sshd_config do I need to modify? Thanks...

**Comment by omega8cc** [comment]
It is already listed in the requirements (README) and boa+barracuda will throw the error and will not allow you to continue until you will add SSH keys for root. The new requirement basically tells you that you must learn how to use SSH keys if you are going to manage hosting system. It is beyond the scope of BOA project to teach people how to use SSH keys and how to configure root access. If we will provide how-to, you will never learn it the proper way, if you don't know it yet. It is something people must learn before even trying to use BOA, because it is that fundamental to your system security. Knowing it well is not an option, it is a must.

**Comment by Juc1** [comment]
"boa+barracuda will throw the error and will not allow you to continue until you will add SSH keys for root." OK but I did not get any error when I upgraded to 2.4.7. Anyway I am happy to use SSH keys from now on but for now can you please tell me what I need to modify in /usr/etc/sshd_config ? Am I modifying it to temporarily allow root login with password? Thanks...

**Comment by omega8cc** [comment]
You didn't get any error because you have run the upgrade before we have applied a hotfix.
