### ISSUE TITLE
 connection dropped during initial install

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#834]
First install on a new server - 

 > $ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
 > $ boa in-stable public server.mydomain.org my@email o1 

Script successfully creates Aegir master site but then closes / exits SSH session  before creating o1 site - just after "Final post-install cleaning, one moment..." (Test server screenshot below)

http://i.imgur.com/9VXHxNO.jpg

**Comment by omega8cc** [comment]
Thanks for the report, we have fixed this in https://github.com/omega8cc/boa/commit/e89450f7eb80dd8353a5dc3e0130632f597a6455
