### ISSUE TITLE
Install hangs on Nginx upgrade

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#835]
I have SKIP DNS test set to "Yes", otherwise all standard stuff with a cloud provider that has other Barracuda instances (larger and smaller) running.

BOA [06:00:51] ==> INFO: Installing extra Drush versions...
BOA [06:00:58] ==> INFO: Running system packages update...
BOA [06:01:56] ==> INFO: Installing required libraries and tools, please wait...
BOA [06:05:29] ==> INFO: Installed OpenSSH version 6.0p1, upgrade required
BOA [06:05:29] ==> INFO: Building OpenSSH 7.1p1 from sources, please wait...
BOA [06:06:46] ==> INFO: Installed cURL version 7.26.0, upgrade required
dpkg: warning: package not in database at line 1: libcurl4-openssl-dev
dpkg: warning: found unknown packages; this might mean the available database
is outdated, and needs to be updated through a frontend method
\BOA [06:06:49] ==> INFO: Building cURL 7.45.0 from sources, please wait...
\BOA [06:08:01] ==> INFO: Installing MariaDB...
\BOA [06:09:27] ==> INFO: Running aptitude full-upgrade...
|BOA [06:09:55] ==> INFO: Building Git 2.6.1 from sources, please wait...
-BOA [06:11:49] ==> INFO: Installed Nginx version nginx/1.2.1, upgrade required
BOA [06:11:49] ==> INFO: Installing Nginx...

**Comment by omega8cc** [comment]
Please run these commands and post the output here:

```
$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
$ boa info
```

**Comment by MetaBureau** [comment]
Aegir on Debian/wheezy x86_64
  VPS XEN
  CPU 2
  RAM 3968
  XTR _XTRAS_LIST="CSF CHV FTP"
  MFX _MODULES_FIX=NO
  PFX _PERMISSIONS_FIX=NO
  DBS _DB_SERIES=5.5
  DNS _DNS_SETUP_TEST=YES
  PKG _EXTRA_PACKAGES=
  NGX
  SSL 1.0.1e
  CRL 7.26.0
  SSH 6.0p1

**Comment by omega8cc** [comment]
I can't reproduce this. Please try with a fresh VPS and if this will happen again, please let us know your provider name/URL.

**Comment by omega8cc** [comment]
Also, note that "Installing Nginx..." will take a *long time* and it is normal, because it builds its own OpenSSL libs from sources on the fly.

**Comment by MetaBureau** [comment]
Something to do with Vultr (https://www.vultr.com/) -- still having issues. 
I ran the installer successfully with a Digital Ocean server but it keeps failing with Vultr.

**Comment by MetaBureau** [comment]
Update: It managed to complete BUT after reboot and "barracuda up-stable" I get "ERROR: I can not find PHP-CLI anywhere!"
Attached the log for your scrutiny.
[barracuda-install.txt](https://github.com/omega8cc/boa/files/70404/barracuda-install.txt)

**Comment by mojo6911** [comment]
Same issue here, also with Vultr
