### ISSUE TITLE
Commits listed on Github... are the available when running upgrade stable, or only available when running upgrade head?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#836]
I see lots of commits... like hotfixes, new maria db, etc. Are these commits applied when running upgrade stable, or must I run upgrade head?

**Comment by omega8cc** [comment]
At the moment there is no difference between HEAD and stable, because all commits listed in the changelog with hotfix label are included in stable, so it is enough to simply run `barracuda up-stable system`.
