### ISSUE TITLE
New install custom platform - errors with Drush Make - /data/disk/o1/.tmp/cache/download is not writable

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#837]
Hi all,

New install - when  creating the first custom platform, Drush make gives two errors = 

> o1@jupiter:~/static/opt-111215$ ls
> opt-111215.make
> o1@jupiter:~/static/opt-111215$ drush make opt-111215.make
> Make new site in the current directory? (y/n): y
> Beginning to build opt-111215.make.  [ok]
> Destination directory /data/disk/o1/.tmp/cache/download is not writable. [error]
> Failed to get available update data from https://updates.drupal.org/release-history/wysiwyg/7.x [error]
> o1@jupiter:~/static/opt-111215$ cd  /data/disk/o1/.tmp/cache
> o1@jupiter:~/.tmp/cache$ ls -a -l
> total 0
> o1@jupiter:~/.tmp/cache$ exit
> logout
> root@jupiter:/data/disk/o1/.tmp/cache#

/root/.barracuda.cnf etc are here http://pastebin.com/UFfSZHdH

Any ideas please?

Thanks...

**Comment by omega8cc** [comment]
Please use `o1.ftp` and not `o1` to run this type of Drush tasks.

**Comment by Juc1** [comment]
Ok thanks...
