### ISSUE TITLE
install always stops on instaling default SSL wildcard nginx proxy on Linode / debian 8.1

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#838]
trying to install latest head on clean linode server and cant get past the default ssl wildcard installation step. It just hangs on instal with no errors.......

**Comment by omega8cc** [comment]
It should display the line which halts the install if you run `killall sleep` (or just kill the "running" wait process - not the main install process) in another terminal window. That said, it is quite random and happened also in our tests, but no longer after these fixes: https://github.com/omega8cc/boa/commit/2c3fe7b377557c4d025fdd91f8d3c8231ad8e030

**Comment by AntiNSA** [comment]
I dont see this commit yet.... if I do a clean install now is the commit made? That fix was 16 hours ago. I have killed the sleep as directed in a new window, yet it is still hanging.... On a fresh install I will receive this error again,... and then kill sleep, and its an endless loop.... any ideas would be great I have tried all day to get this

**Comment by omega8cc** [comment]
It works w/o any issues now. Thanks for the report.
