### ISSUE TITLE
screen -r commans on ssh timeout, trying to install head on 8.1

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#839]
Hi, I am still having problems with head install timing out ssh session.... I followed the install instructions, and on screen -r command I get:

There is a screen on:
        3904.pts-0.base (12/15/15 03:03:37)     (Attached)

and I have not been able to rejoin the previous in progress installation with screen -r 

Perhaps I dont know how to use the correct context... I have tried
screen -r
and 
screen -r 3904.pts-0.base

and still cant resume session. Any ideas ?

**Comment by omega8cc** [comment]
We couldn't reproduce this. Always check for any detached screen sessions with `screen -ls` and either re-attach one of them or just force it with `screen -R`. For more details please read `man screen`
