### ISSUE TITLE
on fresh install, nginx not started verify error, and then if upgraded after fresh install, service masked and unable to start

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#840]
I rebooted my server several times, and had to unmask the nginx service to manually restart it on 8.1 systemctl unmask nginx.service  I dont know if I should remask it or what...... it definately did not restart by itself.

Also, FYI received the known ssh problem notice on running baraccuda upgrade head after a fresh install...  

I had to run the upgrade on fresh install to install SR4 option.

**Comment by omega8cc** [comment]
We couldn't reproduce the problem. The SSH keys notice is expected, we should probably better explain this in the docs.

**Comment by omega8cc** [comment]
Wait, the nginx start problem after reboot is real. Ouch..

**Comment by bserem** [comment]
Just wanted to say that the "Ouch.." made me laugh!

**Comment by omega8cc** [comment]
;)

**Comment by omega8cc** [comment]
Note: if you are already running Jessie for BOA testing, you need this:

```
apt-get install sysvinit-core sysvinit-utils
cp /usr/share/sysvinit/inittab /etc/inittab
apt-get remove --purge --auto-remove systemd
echo -e 'Package: systemd\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
echo -e '\n\nPackage: *systemd*\nPin: origin ""\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
```

Credits: http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_a_Debian_jessie/sid_installation

**Comment by bserem** [comment]
Bit confused. BOA3 will not use systemd?

Not that I have any problem with this, just curious.

**Comment by omega8cc** [comment]
No, because systemd breaks compatibility with VServer, which is supported and still popular VPS alternative.

**Comment by bserem** [comment]
good to know, thanks
