### ISSUE TITLE
Aegir control panel -> Backup -> Export fails for 250MB site

### ISSUE THREAD

**Issue by cvining** [omega8cc/boa#845]
Creating a site backup via the Aegir control panel works well, but when the backup.gz file gets as large as 250 MB, exporting from the CP fails. The "Export" task correctly creates a link, and a copy of the backup file appears in /data/disk/o1/backup-exports/client, but clicking the "Get" but fails. 

Firefox browser returns the following message:

Firefox can't find the file at https://o1.myaegir.mydomain.com/node/1301/backup/download/3881.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.

I did check and the file is still there. Chrome fails similarly. Curiously, Safari browser does download a file of the correct name, but has the size of zero bytes. 

I do have access to the backup files via other methods, but it would be nice if the CP method worked. Works fine for much smaller sites, and based on this page I'd thought it should work up to 1 GB or so:

https://omega8.cc/how-to-export-your-site-from-aegir-241

Thx!

-- Cronin

**Comment by omega8cc** [comment]
Please read https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by cvining** [comment]
I appreciate you need details, and I also appreciate all your support.

Here is my 'boa info' output:  https://gist.github.com/cvining/ea9e89b7f52c95a54b2f

Just to see if it helped, I set _DEBUG_MODE=YES and ran an upgrade with:

    $ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
    $ barracuda up-stable system

no change.

**Comment by omega8cc** [comment]
This feature is probably broken on BOA-3.x

**Comment by cvining** [comment]
Indeed it is broken in BOA-3.x. ALL exports are broken and throw an error such as:

```
`Drush was unable to export the backup.
The specific errors are below:
ln: failed to create hard link `./www.xxx.org-20160516.033007.tar.gz' => `/data/disk/o1/backups/www.xxx.org-20160516.033007.tar.gz': Permission denied
```
-

**Comment by omega8cc** [comment]
It has been fixed in https://github.com/omega8cc/hosting_site_backup_manager/commit/ce2ed14ece284328df927ad7d3a4e52627637e4f

See also: https://www.drupal.org/node/2619074#comment-11361591

By the way, the "failed to create hard link" can be a separate issue. It will never work if you are using different mount points (devices) for the backups directory.

**Comment by pricejn2** [comment]
Patches work like a charm. Thanks!
