### ISSUE TITLE
Allow to install a specific PHP version on a local install

### ISSUE THREAD

**Issue by dsnopek** [omega8cc/boa#848]
For a normal install, if you want PHP 5.6, you can do:

```
boa in-stable public server.mydomain.org my@email o1 mini php-5.6
```

However, when doing a local install, it's NOT possible to specify the PHP version like:

```
boa in-stable local my@email mini php-5.6
```

And so, I'm stuck with PHP 5.5. :-/ How to install PHP 5.6 on a local install?

Thanks!

**Comment by omega8cc** [comment]
Now it should work once you update installers with:

```
$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
```

**Comment by dsnopek** [comment]
Oh, awesome, thanks, what a great Christmas present! :-)

However, it's not working for me... I ran this command:

```
boa in-stable local admin@example.com mini php-5.6
```

And here's a gist with the error I'm getting at the end of installation:

https://gist.github.com/dsnopek/93fff8ddc804a3403fe8

**Comment by dsnopek** [comment]
It kinda looks like the installer is trying to use 'php-5.6' as the octopus name?

On the plus side, it's correctly installing PHP 5.6! When I run 'php --version', I get:

```
PHP 5.6.16 (cli) (built: Dec 27 2015 15:06:07) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

But otherwise the install is totally broken... :-/

**Comment by omega8cc** [comment]
Ah, thanks for testing this! It should be fixed once the commit propagates to all download mirrors in the next 5 minutes.

**Comment by dsnopek** [comment]
Tested it again - it worked this time! Thanks for implementing (and fixing) this so quickly! :-)
