### ISSUE TITLE
Cron could not run because an invalid key was used.

### ISSUE THREAD

**Issue by ahillio** [omega8cc/boa#850]
On a brand new BOA installation that used all default config in .barracuda.cnf except for `_DNS_SETUP_TEST=NO` we are getting this everytime cron is run on the site:
`Cron could not run because an invalid key was used.`
As per https://omega8.cc/running-scheduled-sites-cron-in-aegir-118 we're not using Cloudflare and running `drush cron` on the site works successfully without error.
Any suggestions on what I should check next?

**Comment by omega8cc** [comment]
Do you have redirect to an alias enabled on the affected site? You may need to apply this patch to Provision on your instance: https://github.com/omega8cc/provision/commit/c19de5449bb2bd90bede80606148362df84a0c60

Note: You should apply this patch in `/data/disk/o1/.drush/sys/provision/`

**Comment by pricejn2** [comment]
I noticed the same issue on one site. I can't find what is different with this particular site versus many others with the same Aegir alias redirection defined that are working fine.

In my case, watchdog indicates that `?cron_key` url parameter is getting defined twice:
```
https://www.foobar.com/cron.php?cron_key=OkhElIr7eHJ6i4GzONn9aPTUHIpj4FwT_LCPBytsXhs?cron_key=OkhElIr7eHJ6i4GzONn9aPTUHIpj4FwT_LCPBytsXhs
```

After applying patch omega8cc/provision@c19de54, now there is a single `?cron_key` parameter at expected and cron completes successfully.

Thanks for the heads up!

**Comment by omega8cc** [comment]
Thanks for the confirmation!

Note for others: after applying the patch you need to re-verify affected sites to re-generate their vhosts with proper redirect directives.

**Comment by ahillio** [comment]
This does not solve it for us.  I applied the patch and cleared drush's cache, and I verified the site a couple times.

We are indeed using a redirect to a site alias.  I don't know if this would make a difference but the site's name in Aegir is not a standard domain name, as I find it easier to use acronyms and short names for the sites; this has always worked but I have no idea if it would affect how cron is run.  I'm pretty sure it worked on our older BOA instance.

At this point cron is not even trying to run (and resulting in the error I posted) or there at least isn't any record of it in watchdog report.  `drush cron` still works every time.

Is there anything else you recommend I try?

Thanks!

**Comment by omega8cc** [comment]
@ahillio It should work if you have applied the patch on the correct instance and re-run the verify task on the affected site.

To debug this you could comment out the access log directive in the `/cron.php` location in /data/disk/o1/config/includes/nginx_vhost_common.conf, reload nginx and then watch the output of `tail -f /var/log/nginx/access.log | grep cron.php`

**Comment by ahillio** [comment]
With that directive commented out I see a log entry for each time cron runs.  It's GETing the site's correct cron key. However the site's watchdog does not indicate that jobs were triggered by cron or that cron itself was run (not sure if that's to be expected with this method of running cron or not).  When I un-comment the lines, the log ceases record cron events.  I'm not sure what to make of this, but appreciate your help.

**Comment by omega8cc** [comment]
Do you see 200 response in the respective line/site, or maybe 403? It happens when you have some extra HTTP auth enabled, which effectively blocks cron requests via web call.

**Comment by ahillio** [comment]
No, not 200 or 403. 
```
"ip" site.com [19/Jan/2016:14:13:11 +0000] "GET /cron.php?cron_key=keyxyz.... HTTP/1.1" 404 162 134 333 "-" "iCabProXy" 0.000 "-"
```

**Comment by omega8cc** [comment]
Interesting, it gets 404 error, which suggests that something is wrong with the vhost, perhaps?

It should work locally with any name, because the request is sent to IP with forced Host header, so it should work with any site name.

**Comment by omega8cc** [comment]
Please double check that you have `cron.php` file or not broken symlink in the affected site platform root.

**Comment by ahillio** [comment]
Yeah, it's there:
`-rwxr-xr-x  1 o1     users      720 Jan  8 01:08 cron.php`

**Comment by pricejn2** [comment]
In your nginx log, is "site.com" the redirected domain name or the site installation name that you said wasn't a standard domain name?

**Comment by ahillio** [comment]
In the log "site.com" is the name of the alias that's being redirected to, not the installation name.

**Comment by pricejn2** [comment]
Can you browse to site.com/cron.php?cron_key=keyxyz successfully?

**Comment by ahillio** [comment]
I get 403 Forbidden unless I specify https.

**Comment by ahillio** [comment]
We're routing all traffic https via local.settings.php file.

**Comment by pricejn2** [comment]
And from the server, does a manual curl initiate cron successfully?

```
curl https://site.com/cron.php?cron_key=keyxyz
```

**Comment by ahillio** [comment]
Yes that works.

**Comment by omega8cc** [comment]
>> We're routing all traffic https via local.settings.php file.

Please show us the contents of this file.

**Comment by ahillio** [comment]
```
<?php # local settings.php 
$request_type = ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') ? 'SSL' : 'NONSSL';
if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT'])) {
header('X-Accel-Expires: 1');
header("HTTP/1.1 301 Moved Permanently");
header("Location: https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
header("Connection: close");
exit;
}
$base_url = 'https://' . $_SERVER['HTTP_HOST'];
```

**Comment by omega8cc** [comment]
Does your site name have any keyword which auto-disables cron? I guess that is where from 404 comes:

```
/**
 * Site mode detection and cron protection - cron works only for live sites
 */
if (preg_match("/^\/cron.php/", $_SERVER['REQUEST_URI']) ||
    preg_match("/^\/cron\//", $_SERVER['REQUEST_URI'])) {
  if (isset($_SERVER['HTTP_HOST']) &&
      (preg_match("/(?:^dev\.|\.dev\.)/i", $_SERVER['HTTP_HOST']) ||
       preg_match("/(?:^devel\.|\.devel\.)/i", $_SERVER['HTTP_HOST']) ||
       preg_match("/(?:^tmp\.|\.tmp\.)/i", $_SERVER['HTTP_HOST']) ||
       preg_match("/(?:^temp\.|\.temp\.)/i", $_SERVER['HTTP_HOST']) ||
       preg_match("/(?:^temporary\.|\.temporary\.)/i", $_SERVER['HTTP_HOST']) ||
       preg_match("/(?:^test\.|\.test\.)/i", $_SERVER['HTTP_HOST']) ||
       preg_match("/(?:^testing\.|\.testing\.)/i", $_SERVER['HTTP_HOST']))) {
    $is_tmp = TRUE;
    // Ignore cron requests
    header('X-Accel-Expires: 300');
    header('HTTP/1.0 404 Not Found');
    header("Connection: close");
    exit;
  }
}
```

Please read for more information: https://omega8.cc/running-scheduled-sites-cron-in-aegir-118

**Comment by omega8cc** [comment]
The exact snippet is:

"Please note that cron is automatically disabled for sites with special keywords in the main site name: dev., devel., tmp., temp., temporary., test., testing. — in this case Aegir will still attempt to run cron (if enabled) and report it as “running”, but such requests will be ignored with forced 404 response, so the only way to run cron on sites using listed keywords in their name is to run it manually via site admin area or Drush."

**Comment by ahillio** [comment]
Neither the site name nor any of its aliases contain any of these `dev., devel., tmp., temp., temporary., test., testing`.

**Comment by omega8cc** [comment]
Then no idea.. I don't see any other reason for 404 response.

**Comment by omega8cc** [comment]
Maybe try to modify:

`if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT'])) {`

and use instead:

`if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT']) && !preg_match("/^\/cron\.php/", $_SERVER['REQUEST_URI'])) {`

**Comment by omega8cc** [comment]
Or:

if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT']) && !preg_match("/iCabProXy/", $_SERVER['HTTP_USER_AGENT'])) {

**Comment by omega8cc** [comment]
I think there must be a reason why we have this exception for hostmaster:

```
    if (!file_exists('/data/conf/no-https-aegir.inc')) {
      $request_type = ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' ||
      $_SERVER['HTTPS'] == 'on') ? 'SSL' : 'NONSSL';
      if ($request_type != "SSL" &&
          !preg_match("/^\/cron\.php/", $_SERVER['REQUEST_URI'])) { // we force secure connection here
        header('X-Accel-Expires: 5');
        header("HTTP/1.1 301 Moved Permanently");
        header("Location: https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
        header("Connection: close");
        exit;
      }
    }
```

**Comment by ahillio** [comment]
Ok I just tried the first one and I'll see in five minutes when it tries to run cron.  Then I'll try the other.

**Comment by pricejn2** [comment]
For what its worth, I also run an SSL only site with the same local.settings.php HTTPS redirect + Aegir-level alias redirection and cron runs without any problems for me.

**Comment by omega8cc** [comment]
Yes, but cron will work via SSL only if you have a proper SSL cert in place. It will fail with self-signed cert, because we don't have an argument in curl request (for cron.php) to ignore self-signed certs warnings.

**Comment by ahillio** [comment]
I tried both
`if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT']) && !preg_match("/iCabProXy/", $_SERVER['HTTP_USER_AGENT'])) {`
and
`if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT']) && !preg_match("/^\/cron\.php/", $_SERVER['REQUEST_URI'])) {`.

With each one Aegir indicated that it ran cron, but the site's watchdog did not.

I know the reason for this is that I'm cursed with bad luck, but usually there's a technical explanation... somewhere ;^)

Thanks a lot for both of your time trying to help!

**Comment by omega8cc** [comment]
The 404 response suggests that you may have some keyword in the site name which triggers this.

OR, you have cron.php with insufficient permissions, so web server can't access it. I would check this twice, and not just the symlink, but also its target.

**Comment by ahillio** [comment]
In the platform's doc root:
`-rwxr-xr-x  1 o1     users      720 Jan  8 01:08 cron.php`

Do you mean it's supposed to be a symlink instead of an actual file?

**Comment by omega8cc** [comment]
For built-in platforms it should be a symlink, for custom platforms in ~/static it is a file, and it should have `rw-r--r--` permissions. But it is not the real problem here, I guess.
