### ISSUE TITLE
Can't migrate/clone using a domain that was used in the past.

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#851]
I am trying to clone (or migrate) a site to a new one, using a domain name that was used in my Octopus in the past.

The task fails, but the report page doesn't open in the popup (it loads indefinitely).
Syslog reports this (just this!):
```
Jan 12 14:12:16 ganymede mysqld: 160112 14:12:16 [Warning] Access denied for user 'intntnllyInvalid'@'localhost' (using password: NO)
Jan 12 14:12:16 ganymede mysqld: 160112 14:12:16 [Warning] Access denied for user 'intntnllyInvalid'@'localhost' (using password: NO)
```

If I try to open the task from content management, it loads, but I'm suspecting that I am seeing the last successful clone, since I don't see the domain I asked the clone to use.

This all happens on a BOA 2.4.7, with Drupal 7.41 as a static platform.
Nothing really fancy except that one of the shell users is not in the limited group.

Cloning to an unused domains works fine.

**Comment by omega8cc** [comment]
You may need to disable Redis temporarily in the affected site INI file (unless you can simply restart it) and follow tips published at https://omega8.cc/how-to-debug-failed-migrate-task-328

**Comment by bserem** [comment]
Worked flawlessly! Thnx
