### ISSUE TITLE
Images and css files are not included in pdf files using wkhtmltopdf over ssl

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#858]
When I try to generate a pdf of a webpage over https using **wkhtmltopdf**, the pdf does not include any images and css files. If I access the website over http the pdf looks fine.

Any ideas? Do I have to rebuild wkthmltopdf for https?

[Config Files](https://gist.github.com/luxio/16525f89019dac61fd42)

**Comment by luxio** [comment]
After replacing the wkthmltopdf binary, which comes with boa with the current [stable](http://wkhtmltopdf.org/downloads.html) version (0.12.3),  images and css files are included in the pdf file when printing over https.

**Comment by omega8cc** [comment]
OK, so it is a bug to fix. Thanks for the report.

**Comment by omega8cc** [comment]
In the future: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt#L13

**Comment by luxio** [comment]
[boa info](https://gist.github.com/luxio/6531d349235cd65a02bc)
