### ISSUE TITLE
ODBC access through PHP

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#859]
If I set _PHP_SINGLE_INSTALL="5.5" and keep only one version of PHP then is it possible to install packages php5-odbc/php5-sybase with apt-get?

What if I already have a multiple-php environment and change it to single-php? Working octopus stays alive and going or I have to rebuild it?

**Comment by omega8cc** [comment]
No, it is not possible. We have explained this in detail here: https://github.com/omega8cc/boa/issues/781#issuecomment-140702985

**Comment by omega8cc** [comment]
As for the second and unrelated question: Octopus should be switched to available PHP version, but we have not tested this.

**Comment by velpan** [comment]
Thank you for your answer,
I found a solution so I write it for anyone 

First install unixODBC on your server (see http://www.unixodbc.org/ download)

then in the .barracuda.cnf set
_PHP_EXTRA_CONF="--with-pdo-odbc=unixODBC,/usr/local/unixODBC --with-unixODBC=/usr/local/unixODBC"
_BUILD_FROM_SRC=YES
_PHP_FORCE_REINSTALL=YES

and run barracuda up-stable system

**Comment by omega8cc** [comment]
@velpan Maybe convert your how-to into wiki entry? Thanks!
