### ISSUE TITLE
BOA.txt.sh is stuck 

### ISSUE THREAD

**Issue by hodba** [omega8cc/boa#860]
Hello,
I am trying to install BOA on my server but when running `bash BOA.txt.sh` it gives nothing (i waited for more than 3 hours) while it is working properly on all other servers that I got.
I searched the previous issues here and I followed the instructions but non of them matched my case where I think my IP address is block (I checked my firewall and disabled it).
Would you please check if my IP address is blocked:
IP: 216.120.248.147
Many thanks in advanced

**Comment by omega8cc** [comment]
No, your IP address is not blocked on our side. You could have an issue with DNS on this system, which prevents `apt-get` initial update, though. Take a looks via `ps axf` in another terminal window what happens while you are waiting for the progress?

**Comment by hodba** [comment]
It was the DNS

I change the `/etc/resolv.conf` to have the name servers: 8.8.8.8 and 4.2.2.4 and everything is working fine,

Thanks,
