### ISSUE TITLE
Redis_edge creates paths with random uppercase characters

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#861]
Based on the discussion here:
https://github.com/omega8cc/boa/issues/815
I have added redis for paths on a site of mine using the following line in local.settings.php:
```
$conf['path_inc'] = '../../../../../data/all/000/modules/redis_edge/redis.path.inc';
```

At some point, I noticed a strange behavior though. While our paths are lowercase, some characters were upercase with redis.path.inc.
For example, the path www.example.com/wohnen is printed out as www.example.com/wohNen when redis.path.inc is enabled.
The link is used in breadcrumbs and in the main menu mostly (so the DOM has links towards paths with the wrong case).
If I click on the link in question I get redirected to the proper one (www.example.com/wohnen), but a 301 redirect is happening, which I'd prefer to avoid.

Commenting out redis.path.inc eliminates the problem.

Hope I described the problem well.
Any ideas on why this is happening?

**Comment by omega8cc** [comment]
No idea, but we don't/can't support non-standard Redis configurations.

**Comment by bserem** [comment]
I understand that, but what do you mean by "non-standard" ?

I'm using Redis "as is" in BOA, with the only difference that I enabled redis.path.inc too, like discussed in issue #815 .
Am I doing something out of the ordinary here?

**Comment by omega8cc** [comment]
We don't support path caching in Redis, at least not in the 2.x version still used in BOA. It is an experimental feature which will not work for most sites. Any attempt to use it anyway is considered non-standard and is not supported. You are free to experiment and discuss your experience with the community at https://gitter.im/omega8cc/boa, though.

**Comment by bserem** [comment]
Good to know! At the moment I've isolated the issue to redis, I'll check to see if I can find more about it.

Thanks
