### ISSUE TITLE
_SSH_PORT seems not be be respected in SSH

### ISSUE THREAD

**Issue by rpsu** [omega8cc/boa#862]
I have (and have had for a long time) a setting to change SSH  port to non-default in `/root/.barracuda.cnf` -file. Since a month a go SSH is running in default port `22`.

- `/etc/ssh/sshd_config` has port set to my custom port (for example 2222) 
- firewall has a setting allowing traffic through custom port (`iptables -L |grep 22$`)
- ssh daemon is listening port 22 (`lsof -i TCP:22`)

I am pretty sure I have not touched barracuda configuration at all when this started. I can get around this manually, but it messes up for example automated backups done with rsync -scripts from external servers.

**Comment by ar-jan** [comment]
You probably need to customize your port settings (again) in `/usr/etc/sshd_config`, due to a change in OpenSSH (#786).

**Comment by rpsu** [comment]
Right, thanks. That solved it.
