### ISSUE TITLE
Does the the remote Octopus instance have to exist before migrating to a new server?

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#863]
I have a question regarding the doc [MIGRATE.txt](https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt). 

First it says:
>  Remote Octopus instance must already exist

and then 

> No Octopus instance is needed on the target system prior to migration.

Does the the remote Octopus instance have to exist before migrating to a new server?

**Comment by omega8cc** [comment]
The first four points are about `docs/REMOTE.txt`, for comparison. Is this confusing? Feel free to suggest improvements.

**Comment by luxio** [comment]
Thx for the reply. No it is not confusing, I must have missed the reference to `docs/REMOTE.txt`. Sorry.
