### ISSUE TITLE
Old nginx sever name after migrating to a new server

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#864]
I have followed the instructions in [MIGRATE.txt](https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt) to migrate an octopus instance to a new server.

The source server was also once migrated.

After the migration the nignx server name listed at /hosting/servers is set to the name of the server from which the source server was once migrated.

Do you know why? How can I set the server name to the target server name, without breaking the configuration?

[boa info](https://gist.github.com/luxio/5f560dd280ddfe75162e)

**Comment by omega8cc** [comment]
No idea, really. We have migrated hundreds of instances in the past and we have never experienced any such issues. You should see the problems displayed on screen while running the migration. But the output is not logged. I don't know details, so I don't know how/if this can be fixed (probably both in drush aliases and hostmaster db)
