### ISSUE TITLE
Feature: _WHEEZY_TO_JESSIE major upgrade procedure

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#870]
Hello,

We want to move our existing Wheezy BOA to Jessie. Are you going to automate this? Or, if not, can we just simply update the apt sources.list and run an full barracuda and octopus up-stable?

Thank you.

**Comment by omega8cc** [comment]
Yes, there will be the easy upgrade mode available, like it was in the past with _LENNY_TO_SQUEEZE=YES and _SQUEEZE_TO_WHEEZY=YES

**Comment by memtkmcc** [comment]
Tested on DigitalOcean -- works fine.
