### ISSUE TITLE
Locales check should not be used with screen session to not break _STRONG_PASSWORDS

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#871]
Hello,

We just installed 2.4.8 stable on jessie (with only locale set to en_US UTF8) and strong passwords did not work - we have 8 character passwords for both mysql and redis. We set them to 96 in the .cnf files, which are here (we ran a second up-stable for both barracuda and octopus after rebooting the server after the initial install):

octopus conf file: https://gist.github.com/EdNett/b90bcb25276cb289641c

barracuda conf file:  https://gist.github.com/EdNett/64052e845b8739920c6c

barracuda log:  https://gist.github.com/EdNett/cbe7ca321d05c2b97a91

output of boa info command: https://gist.github.com/EdNett/0571feafa80c4c33585f

**Comment by omega8cc** [comment]
This happens probably because we force this, while locales can appear "broken" when "screen" session is used/active:

```
###
### Do not allow strong passwords until locales work properly
###
if [ "${_LOCALE_TEST}" = "BROKEN" ]; then
  _STRONG_PASSWORDS=NO
fi
```

Example:

```
server:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
server:~#

server:~# screen

root@server:~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@server:~#
```

**Comment by omega8cc** [comment]
Note that to update also mysql root password you must create an empty `/root/.mysql.yes.new.password.cnf` file.
