### ISSUE TITLE
Update all supported platforms with Drupal 7.43 and Pressflow 6.38

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#872]
There are security releases for all Drupal versions:

https://www.drupal.org/drupal-8.0.4
https://www.drupal.org/drupal-7.43-release-notes
https://github.com/pressflow/6/pull/101

**Comment by fluxsauce** [comment]
https://github.com/pressflow/7/releases/tag/pressflow-7.43

**Comment by omega8cc** [comment]
@fluxsauce Good to know, thanks! We have used our own D7 fork: https://github.com/omega8cc/7x/releases, since Pressflow 7 introduced very few changes in the past, but maybe we could consider it again. Thanks!

**Comment by omega8cc** [comment]
Drupal 7.43 caused some regressions:

https://www.drupal.org/drupal-7.43-release-notes

We should postpone BOA-2.4.9 until these issues are fixed, so we could apply relevant patches.

**Comment by omega8cc** [comment]
Known regressions can be listed, but it shouldn't affect BOA-2.4.9 release.

**Comment by omega8cc** [comment]
We don't need to wait for fixes related to regressions affecting some contrib modules, but we do need to wait a few days for active distros new releases, because they tend to include updates beyond Drupal core.

**Comment by omega8cc** [comment]
Almost all supported distros released updated version, so we can release BOA-2.4.9 today.
