### ISSUE TITLE
Recent update to 2.4.8 leaves incorrect permissions on /static/name/sites/modules - disables o_contrib_seven modules

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#874]
Recent update to 2.4.8 leaves incorrect permissions of 2755 on /static/name/sites/modules - instead of the 2775 needed to verify, and this disables all the  o_contrib_seven modules, which aren't even seen in the sites modules' listings.  I have verified this error on a dedicated server and a vps - both wheezy with 2.4.7 stable recently updated to 2.4.8 stable. We do NOT use o1 as the octopus name, but rather use "fast1" - could this be the problem? or is it a symlink problem?

Gist is at https://gist.github.com/EdNett/16dd79501eb75c94f43e

regards,

Ed

**Comment by EdNett** [comment]
Of course, manually changing the permissions allows the static platform to verify and the o_contrib_modules to once again be recognized as existing by the sites in the static platform, however those o_contrib_modules are disabled, and this is a real problem.

**Comment by omega8cc** [comment]
You are responsible for correct permissions in ~/static and BOA will not fix them for you daily, unless you will enable `_PERMISSIONS_FIX=YES`

**Comment by EdNett** [comment]
Hello!

You don't seem to understand. Everything was working fine before the update to 2.4.8. I logged-in as root, rand the update stable as per your instructions, and found that my sole static platform had incorrect permissions of 2755 on sites/modules and sites/themes (the core modules and themes directories) and that all o_contrib_seven modules were disabled - print, advagg, entitycache, etc - and this affected all the sites being hosted in the static platform - so it IS a boa script problem. How could it not be?

**Comment by omega8cc** [comment]
BOA doesn't touch permissions on core modules in your static codebase, and there is no place in BOA which could set 2755 there. You are confusing some things, apparently. Also, grep the code for 2755, perhaps?
