### ISSUE TITLE
Is ftp upload speed limited/throttled?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#875]
Im uploading files from behind chinas gfw.... so I can tell if the government is limiting my speed, or if its my server. Using Filezilla w/ssh login, I am only getting like 50-60kbps on linode. Is this something that is being done in boa?

**Comment by bserem** [comment]
You can always try to sftp files from another linode, where there should 
be no throttling at all.

By the way, I always move files towards BOA over SCP, and never had any 
speed issues.

**Comment by omega8cc** [comment]
Could be network problems at Linode, or another DoS, whatever. BOA doesn't throttle it, but you may want to whitelist your IP with csf. SFTP (not FTPS) should be fast.
