### ISSUE TITLE
jsmin 2.x upgrade

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#878]
jsmin 2.x has been stable since late last year (https://pecl.php.net/package/jsmin). Can we update from 1.1.0?

From a Drupal perspective, jsmin 2.x is required by advagg to handle multibyte characters. See an example cron error message when using the current 1.1.0:
```
WD advagg_js_compress: The currently installed jsmin version does not handle multibyte characters, you may   [notice]
concider to upgrade the jsmin extension. Using JSqueeze fallback.
```

**Comment by omega8cc** [comment]
Done! Thanks for the heads up!
