### ISSUE TITLE
Unable to SSH into VM after BOA script successfully installed.

### ISSUE THREAD

**Issue by trevorlazarus** [omega8cc/boa#879]
Hello, after getting the BOA script to run successfully on a Google Compute Engine VM running Debian 8 , I got to access the Aegir frontend, but I'm not able to SSH into the VM, it's asking me for a password that I'm not aware of. Any help would be great. Thanks.

**Comment by omega8cc** [comment]
You don't know your root password? Unless you mean SFTP/FTPS password generated for you and listed the welcome email?

**Comment by trevorlazarus** [comment]
Thanks for the swift response. By default the VM had no root password. After BOA ran to completion and it generated the link to the Aegir frontend, the SSH session ended, when I tried to SSH back to the VM, it's asking me for a password for username: trevor@xxx.xxx.xxx.xxx

**Comment by omega8cc** [comment]
BOA doesn't create such user, but if you have not added SSH keys to your custom user before running the install, you could be locked out, because the SSH version which comes with BOA may change SSH behaviour to more strict mode, although it should affect only root.

I don't know how it works at Google, but elsewhere you always have root access, also via console, so you can always modify configuration, add keys etc, if something like this happens.

See also requirements: https://github.com/omega8cc/boa/blob/master/README.txt#L93

**Comment by trevorlazarus** [comment]
I never added SSH keys and got locked out, I'm going to have to try again, what do you suggest I do on a fresh Debian 8 install in terms of user management right before I run BOA, should I create a new user?

**Comment by omega8cc** [comment]
We recommend that you start with remotely available root login (not only via sudo and some local user), and with SSH keys added for root. You can always restrict the access later.

**Comment by omega8cc** [comment]
We should probably add more strict check to the install script -- it already checks for SSH keys but it seems it is not enough.

**Comment by trevorlazarus** [comment]
Thank you so much for the support, you guys are doing such a great job.

**Comment by omega8cc** [comment]
Thank you!

**Comment by trevorlazarus** [comment]
@omega8cc My VM has suddenly started allowing me to SSH into it and has stopped prompting for password :) 

`Barracuda System managed by Skynet Agent v.BOA-2.4.9 welcomes you aboard`

**Comment by omega8cc** [comment]
Interesting.. :)

**Comment by bery** [comment]
I had exactly the same issue - BOA is installed (with root user able to login using ssh key). After the installation was finished, I was promted to reboot the machine and never ever got in again, not even using Google's SSH console.

I tried to provide my own .barracuda.cnf as I suspect that Google's magic SSH stops working when compiled from source, yet BOA keeps overriding the file, especially 

https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L77

Is there any way to provide the install options? Have I missed something in the docs? 

I will do more testing on google compute engine, once I figure out how to force boa not to compile SSH from source :)
