### ISSUE TITLE
[xtra: ffmpeg] provide deb-multimedia ffmpeg package for FMG xtra

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#883]
In lieu of compiling from source or tolerating feature poor, stock Debian ffmpeg/libav binaries, can we provide ffmpeg from [deb-multimedia](https://www.deb-multimedia.org/) repos?

Granted, this is Debian specific, but I'm not sure the FMG XTRA works at all with current LTS, Ubuntu Trusty distro as ffmpeg isn't available altogether (http://packages.ubuntu.com/search?suite=trusty&searchon=names&keywords=ffmpeg).

I'm happy to provide a patch if this change is agreeable.

**Comment by omega8cc** [comment]
I don't know how reliable it can be. There is a huge confusion related to FFmpeg and Libav controversy/fork: https://en.wikipedia.org/wiki/Libav

Currently it is expected that Debian Stretch (9.0) will return to FFmpeg: https://lwn.net/Articles/650495/

**Comment by omega8cc** [comment]
Maybe we should build from sources then? http://ffmpeg.org/download.html#get-sources

**Comment by pricejn2** [comment]
I'll stay away from the whole FFmpeg / Libav debacle...

I've used dmo for years without issues, but any external reliance has its downsides. For example, they infrequently update builds for older repositories (see http://deb-multimedia.org/dists/oldstable/main/binary-amd64/package/ffmpeg). 

Looking at jessie-backports, ffmpeg is available in Jessie (see https://packages.debian.org/jessie-backports/ffmpeg) too and is quite feature rich. Though not as much so as dmo's equivalent.

I suppose building from source gets around all of the differences among distros but adds some overhead.

**Comment by pricejn2** [comment]
@omega8cc - What's your preference -- source or dmo? I can work on a patch for this.

**Comment by omega8cc** [comment]
@pricejn2 -- We prefer to use packages instead of source builds, I think: #955

Thanks!
