### ISSUE TITLE
composer directroy

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#884]
I am trying to install the AMP module (highly recommended by google for mobile version) and i am stuck with an error when i try install a required module 
```
 /home/octopususer/.drush  exists, but is not writable. Please check directory permissions.                                                                                 [error]
Project composer (8.x-1.x-dev) could not be downloaded to /home/octopususer/.drush/composer
``` 
Does it mean that on boa system it is not possible to run it ? 

I have looked at the documentation and seems that we can define some custom directories where files can reside on a multisite : 
https://www.drupal.org/node/2405805
I am not sure what to define to make run on BOA system.

**Comment by omega8cc** [comment]
BOA protects `~/.drush` by design, for security reasons, so the user can't modify anything there. Any extra Drush extension needs to be submitted as a feature request.

**Comment by yazzou** [comment]
THanks for your reactivity. After looking in the repository i have noticed that a similar issue has been posted on 3 september 2014, as a feature request.
