### ISSUE TITLE
Upgraded barracuda from 2.4.6 to 3.0: not able to upgrade octopus instance

### ISSUE THREAD

**Issue by netdream** [omega8cc/boa#886]
After upgrading master Barracuda instance from 2.4.6 to 3.0 (smooth upgrade... everything is working), I'm unable to upgrade the Octopus instance.

With standard "octopus up-stable" it says to upgrade before to 2.4.9, by running "octopus up-2.4".
But, it then says that it is the wrong installer... and you have to use an older one... 

How can it be done?

Here is the command output:
```
root@server:~# octopus up-stable all both
load is 55 while maxload is 600
Octopus upgrade for User /data/disk/o1
Waiting 9 seconds...

BOA [12:02:14] ==> Skynet Agent v.BOA-3.0.0 welcomes you aboard!

BOA [12:02:17] ==> ERROR: This octopus installer can be used only when the instance
BOA [12:02:17] ==> has been already upgraded to previous stable BOA-2.4.9 version
BOA [12:02:17] ==> Please run 'octopus up-2.4 o1 aegir' upgrade first
BOA [12:02:17] ==> Bye
Waiting 10 seconds...
Done for /data/disk/o1

OCTOPUS upgrade completed
Bye

root@server:~# octopus up-2.4 o1 aegir
load is 36 while maxload is 600
Octopus upgrade for User /data/disk/o1

BOA [12:03:32] ==> Skynet Agent v.BOA-2.4.9 welcomes you aboard!

BOA [12:03:35] ==> ERROR: This octopus installer can be used only when the same version
BOA [12:03:35] ==> of boa or barracuda installer was used before. Your system must be
BOA [12:03:35] ==> upgraded with barracuda installer version BOA-2.4.9 first
BOA [12:03:35] ==> Bye
Done for /data/disk/o1

OCTOPUS upgrade completed
Bye
```

**Comment by omega8cc** [comment]
It was announced before that you must upgrade to latest 2.4.x or you will not be able to easily upgrade to 3.0.0

Barracuda 2.4.6 to 3.0.0 should not work -- it should force you to run `barracuda up-2.4` first. We need to fix this, if it really worked for you.

Now, if you are sure that you have complete barracuda 3.0.0 (system+Aegir) upgrade, you need to trick BOA into thinking that it was upgraded to 2.4.9 before:

`echo BOA-2.4.9 >> /var/log/barracuda_log.txt`

Now you should be able to run:

`octopus up-2.4 o1 aegir`

**Comment by netdream** [comment]
Yes, barracuda major upgrade worked, without any warning, and it was an interactive update.

This is an extract from /var/log/barracuda_log.txt
```
Wed Sep 23 20:17:00 CEST 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.6 / Barracuda BOA-2.4.6 / Nginx 1.9.4 / PHP-MI 5.3 5.4 / PHP-SE / FPM 5.4 / CLI 5.4 / MariaDB-5.5.45 localhost
Fri Apr 1 11:40:16 CEST 2016 / Debian.wheezy x86_64 XEN / Aegir BOA-3.0.0 / Barracuda BOA-3.0.0 / Nginx 1.9.13 / PHP-MI 5.5 5.6 / PHP-SE / FPM 5.6 / CLI 5.6 / MariaDB-5.5.48 localhost
```
I didn't noticed at first that it was a major upgrade to 3.x when i ran the "barracuda up-stable"... but it was too late to stop it.

Now I've cheated with the barracuda_log as suggested and I've been able to update to octopus 2.4.9 and then to 3.0.0.

This is the extract from /data/disk/o1/log/octopus_log.txt:
```
Wed Sep 23 20:18:42 CEST 2015 / Debian.wheezy x86_64 / Aegir BOA-2.4.6 / Octopus BOA-2.4.6 / FPM 5.4 / CLI 5.4
Fri Apr 1 13:17:33 CEST 2016 / Debian.wheezy x86_64 / Aegir BOA-2.4.9 / Octopus BOA-2.4.9 / FPM 5.5 / CLI 5.5
Fri Apr 1 13:24:02 CEST 2016 / Debian.wheezy x86_64 / Aegir BOA-3.0.0 / Octopus BOA-3.0.0 / FPM 5.5 / CLI 5.5
```

**Comment by LunkRat** [comment]
@netdream I did the exact same thing, although I mistakenly assumed that my satellite instances were up to 2.4.9 when in fact they were not. 

@omega8cc thank you as usual for posting the remedy to our careless haste. It worked for me.

**Comment by omega8cc** [comment]
Thanks @/all for the helpful feedback!
