### ISSUE TITLE
Drush issues with o1.ftp user: no aliases available or Error: Call to undefined function conf_path()

### ISSUE THREAD

**Issue by netdream** [omega8cc/boa#887]
With BOA 3.0, when using a *.ftp user with limited shell, "@site.com" aliases cannot be found.
Also, drush is aliased to drush8 and drush7 is forbidden.

But it's only a part of the problem: when forcing a login with a bash shell (e.g.   su - o1.ftp -s /bin/bash) drush7 finds the aliases, but drush8 still doesn't!

I think that some work is needed in /etc/lshell.conf or possibly with *.ftp user parameters...

Here the tests done:

O1.FTP - LSHELL **KO**
```
server:/data/disk/o1/.drush# su - o1.ftp
      ======== Welcome to the Aegir, Drush and Compass Shell ========
[...]

o1.ftp:~$ drush @website.test status
Could not find the alias @website.test

o1.ftp:~$ drush8 @website.test status
*** forbidden command -> "drush8"
[...]

o1.ftp:~$ drush7 @website.test status
*** forbidden command -> "drush7"
[...]
```

O1.FTP - BASH **PARTIALLY KO**
```
server:/data/disk/o1/.drush# su - o1.ftp -s /bin/bash

o1.ftp@server:~$ drush @website.test status
Could not find the alias @website.test

o1.ftp@server:~$ drush8 @website.test status
Could not find the alias @website.test

o1.ftp@server:~$ drush7 @website.test status
 Drupal version                  :  7.43
[...]
```

O1 - BASH **OK**
```
server:/data/disk/o1/.drush# su - o1 -s /bin/bash

o1@server:~$ drush7 @website.test status
 Drupal version                  :  7.43
[...]

o1@server:~$ drush8 @website.test status
 Drupal version                  :  7.43
[...]
```

**Comment by omega8cc** [comment]
Thanks for the report! We should switch back to Drush 7 on command line until this is fixed.

**Comment by omega8cc** [comment]
It doesn't seem related to limited shell, because, as you have also discovered, `drush8 @website.test status` doesn't work for `o1.ftp` also with standard bash. Really weird!

**Comment by heliogabal** [comment]
So does this effectively mean that drush for drupal 8  is unusable until this is fixed? When trying to use drush now, I get:
`Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to undefined function conf_path() in
/opt/tools/drush/7/drush/lib/Drush/Boot/DrupalBoot.php, line 376`

Is this related to this issue?

**Comment by omega8cc** [comment]
@heliogabal Yes, correct. We need to either fix the underlying, unknown problem, or open an access to `drush8` directly, as a workaround.

**Comment by heliogabal** [comment]
@omega8cc OK, thanks for clearing that up. Then I can stop trying to make it work somehow and just have to wait until the problem is fixed. Good luck finding the reason!
