### ISSUE TITLE
Can't git pull

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#890]
"I can no longer use 'git pull' -- fatal: cannot exec 'fetch': Permission denied"

Thanks Yevgeny for the report!

**Comment by dbassendine** [comment]
I'm also seeing this:

`$ git fetch
fatal: cannot exec 'ssh': Permission denied
fatal: unable to fork`

`$ git pull
fatal: cannot exec 'fetch': Permission denied`

**Comment by omega8cc** [comment]
We are working to fix this ASAP (today). In the worst case scenario we will revert lshell update.

**Comment by omega8cc** [comment]
The source of the problem was trivial: a human error! We forgot to merge in some private branch used for lshell security updates.

We will update `lshell.conf` on all systems running BOA-3.0.0. It will fix the problem automatically in the next 1-2 hours only on systems with `_SKYNET_MODE` not set or set to `ON` (default).
