### ISSUE TITLE
Missing VBO options 

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#892]
"After Aegir upgrade there's no option to perform operations on sites or platforms... the selectable boxes are still there, but the operations are missing."

Thanks Alec for the report!

Note that this affects only non-superuser accounts, which is default setup on hosted BOA.

**Comment by Pls** [comment]
Is this security related adjustment when module is not upgraded to latest version? What versions are affected?

**Comment by omega8cc** [comment]
@Pls I'm not sure I understand your question?

**Comment by Pls** [comment]
Oh, my bad, I misread the problem description actually and thought that this affects aegir hosted sites. But it only affects Aegir instance itself. Sorry for the noise :)

**Comment by omega8cc** [comment]
Fixed in this commit: https://github.com/omega8cc/hosting_custom_settings/commit/7e0698b9462dcbeb52da12d55fe5a9fd59ad941d
