### ISSUE TITLE
boa in-2.4 fails to install on Debian Jessie

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#898]
I tried to install legacy BOA 2.4.9 in Debian Jessie and I've got some issues in barracuda install (but looks like it made it until the end of the script) and some issues on octopus install which finally fails.

`root@debian:~# boa in-2.4 public server.dev o1@email.com o1 none log`

I'm not sure but it looks like BOA script tried to install 3.0.0 instead of legacy 2.4.9

Attaching log files
[barracuda_log.txt](https://github.com/omega8cc/boa/files/202859/barracuda_log.txt)
[boa_install.txt](https://github.com/omega8cc/boa/files/202858/boa_install.txt)

**Comment by ixiam** [comment]
/var/log/install.log

[install.log.txt](https://github.com/omega8cc/boa/files/202907/install.log.txt)

**Comment by omega8cc** [comment]
Thanks for the report, it seems we have updated only `barracuda` and `octopus` and forgot about `boa` meta-installer in the previous commit.

**Comment by ixiam** [comment]
Thanks! now is installing properly fro BOA 2.4.9 under Debian Jessie.
I've executed `barracuda up-2.4` after the installation and it completed too.

One question, if I want to add an extra octopus user, running
` $ boa {in-octopus} {email} {o2} {mini|max|none}`

it will add an octopus user in 2.4.9 or stable 3.0.0 ?

**Comment by omega8cc** [comment]
@ixiam the `boa in-octopus` command doesn't support legacy version, it will try to install stable.

See:

https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L134
https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/boa#L1449

**Comment by ixiam** [comment]
mm ok, is there any easy way to set up an environment with multiple octopus
users in 2.4.9?


On Tue, Apr 5, 2016 at 2:22 PM, Barracuda Team <notifications@github.com>
wrote:

> @ixiam <https://github.com/ixiam> the boa in-octopus command doesn't
> support legacy version, it will try to install stable.
>
> See:
>
> https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L134
> https://github.com/omega8cc/boa/blob/master/aegir/tools/bin/boa#L1449
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/omega8cc/boa/issues/898#issuecomment-205776366>
>



-- 
*Luciano Spiegel*
iXiam Global Solutions
l.spiegel@ixiam.com
www.ixiam.com
@ixiam <https://twitter.com/ixiam>

Móvil: +34  662 131 618
España: +34 902 750 682
Argentina: +54 11 5199 0524

-----
Este mensaje y sus archivos adjuntos son confidenciales y previstos
unicamente para el uso de la persona o entidad a quien haya sido dirigida.
Su uso, difusión, distribución, impresión o copia no autorizados está
prohibido legalmente. Si usted ha recibido este mensaje por error, por
favor, bórrelo y notifíquelo al remitente.

El contingut d'aquest missatge i els arxius adjunts són confidencials i
previstos sols per a ser utilitzats per les persones i entitats a qui han
estat tramesos. El seu ús, difusió, distribució, impressió o còpia no
autoritzats està prohibit legalment. Si vostè ha rebut aquest missatge per
error si us plau esborri'l i notifiqui-ho al remitent.

This e-mail is for the sole use of the intended recipient and contains
information that may be privileged and/or confidential. If you are not an
intended recipient, please notify the sender by return e-mail and delete
this e-mail and any attachments.

**Comment by omega8cc** [comment]
@ixiam You would need to modify the `boa` installer before running it, because it is currently not supported/implemented.

**Comment by omega8cc** [comment]
@ixiam Why not to make it a feature request? :)

**Comment by omega8cc** [comment]
While clean 3.0.0 install worked in our tests before the release, it doesn't work for others. Until this problem is fixed properly without regressions, we are switching boa installer back to 2.4.9, which makes getting 3.0.0 a two step operation: first 'boa in-stable' install, and then 'barracuda up-stable' upgrade -- because upgrades to 3.0.0 work fine. This also means that 'boa in-octopus' will also install the legacy 2.4.9 octopus extra instances.

**Comment by ixiam** [comment]
@omega8cc so `boa up-stable ...` will install 2.4.9 or should we keep using `boa up-2.4` ?

**Comment by omega8cc** [comment]
@ixiam `boa in-stable` will install 2.4.9 until the problem is fixed and we will revert the temporary fix affecting only `boa` installer. But if you want to make sure you stay on 2.4.9, you should use `in-2.4` and `up-2.4`
