### ISSUE TITLE
3.0.0 clean install is broken

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#899]
## Installation steps taken:

Set up wildcard DNS for server:
eg. *.a01.domain.com

**Login as Root**

#Stop mysql password change on update. 
touch /root/.mysql.no.new.password.cnf 

**Set up key based access**
$ mkdir ~/.ssh;nano ~/.ssh/authorized_keys 
-paste pubkey and save  
$ chmod 700 ~/.ssh;chmod 600 ~/.ssh/authorized_keys 
-test key based login Configure SSH server  

**Harden sshd**
$ sudo nano /etc/ssh/sshd_config  
-Set PasswordAuthentication no  
-Set PermitRootLogin no  
-Set LoginGraceTime 30  
-Add AllowUsers aegir root 
-Restart ssh server  
$ sudo /etc/init.d/ssh reload 

**Set locale**
$ dpkg-reconfigure locales 

**Download and run BOA Meta Installer**
$ cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt

$ boa in-stable public a01.rl.cm sysadmin@realityloop.com o1 none

Break install after .barracuda.cnf is written

Edit to add specifics

$ rm /var/run/boa_run.pid
$ rm /var/run/boa_wait.pid

$ boa in-stable public a01.rl.cm sysadmin@domain.com o1 none

## Results
.barracuda.cnf I used (email sanitised): https://gist.github.com/BrianGilbert/50e34199b2ff965977f81dd06a5bfd46
Install log: https://gist.github.com/BrianGilbert/6d2e2afde709ae39ac12296c8f5453e3

When I use the 1 time login link I am greeted with a site with Bartik theme set as the default and only the following modules enabled:

- Field
- Field SQL Storage
- Filter
- System
- Text
- Update Manager
- User

If I log in as the aegir user the reported Drush version is:
```
aegir@a01:/root$ drush --version
 Drush Version   :  8.1-dev
```

The reported PHP version at CLI is:
aegir@a01:/root$ php -version
```
PHP 7.0.5 (cli) (built: Apr  5 2016 01:33:48) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

I tried installing again clean without php 7 in multi install and I still end up with Bartik theme and modules not enabled as you would expect.. this is happening in both master instance and octopus instances.

**Comment by BrianGilbert** [comment]
The octopous site has more modules enabled, but theme is still set to bartik and there are no servers configured within it's aegir instance..

**Comment by omega8cc** [comment]
Hardening SSH before installing BOA is useless, because it will switch to `/usr/etc/sshd_config` so `/etc/ssh/sshd_config` is no longer used.

**Comment by omega8cc** [comment]
I would recommend to run uninterrupted install, reboot, then modify .barracuda.cnf if needed, and then run barracuda upgrade, which is required step on Jessie, anyway.

Trying to reproduce this now, though.

**Comment by omega8cc** [comment]
We could reproduce this with Jessie and Wheezy, on Linode and DigitalOcean. While there are no visible errors on install, it silently and partially fails at the end:

```
Command hosting-setup needs the following extension(s) enabled to run: hosting. [23.78 sec, 11.74 MB [error]
The drush command 'hosting-setup' could not be executed. [23.78 sec, 11.74 MB] [error]
```

**Comment by omega8cc** [comment]
While clean 3.0.0 install worked in our tests before the release, it doesn't work for others. Until this problem is fixed properly without regressions, we are switching boa installer back to 2.4.9, which makes getting 3.0.0 a two step operation: first 'boa in-stable' install, and then 'barracuda up-stable' upgrade -- because upgrades to 3.0.0 work fine. This also means that 'boa in-octopus' will also install the legacy 2.4.9 octopus extra instances.

**Comment by BrianGilbert** [comment]
@omega8cc 
Have followed your workaround steps and have a working instance now, however I edited .barracuda.cnf and changed all PHP versions to 5.6 but 5.5.34 is what is running at cli and via fpm after running up-stable.

**Comment by omega8cc** [comment]
@BrianGilbert Upgrade doesn't switch PHP version used by Octopus instances. While for Barracuda it is managed in .barracuda.cnf, for Octopus it is defined in the respective .o1.octopus.cnf files per instance, or can be switched on the fly with control files: https://omega8.cc/how-to-quickly-switch-php-to-newer-version-330

**Comment by BrianGilbert** [comment]
@omega8cc after upgrade it seems that aegir still points to the wrong version of drush..

**Comment by omega8cc** [comment]
@BrianGilbert Why do you think it is wrong version?

Have you tried `cat /var/aegir/drush/drush.info` ?

**Comment by BrianGilbert** [comment]
Installing Drupal 8 sites are failing.

aegir@a01:~$ /var/aegir/drush/drush.info
-bash: /var/aegir/drush/drush.info: Permission denied

**Comment by omega8cc** [comment]
`cat /var/aegir/drush/drush.info` not `/var/aegir/drush/drush.info`

**Comment by BrianGilbert** [comment]
realised and had just updated that

aegir@a01:~$ cat /var/aegir/drush/drush.info
drush_version=7.0-dev

**Comment by omega8cc** [comment]
@BrianGilbert So you have not run paper barracuda upgrade yet.

**Comment by omega8cc** [comment]
```
aegir@quad:~$ cat /var/aegir/drush/drush.info
drush_version=8.1-dev
aegir@quad:~$
```

**Comment by BrianGilbert** [comment]
From bash history:

```
boa in-stable public a01.rl.cm sysadmin@domain.com o1 none
nano .barracuda.cnf
barracuda up-stable
```
Editing .barracuda.cnf was to change php to 5.6 and install IMG and SR4

I believe thats all I should have needed to do as per your instructions above?

**Comment by omega8cc** [comment]
If you have drush 7 there, then you have not run the Aegir upgrade which is a part of `barracuda up-stable` yet. Try to run it again. Also, use `_DEBUG_MODE=YES` in .barracuda.cnf

**Comment by omega8cc** [comment]
Aegir instances (both master and satellites) use their local Drush copies, not system default copies.

```
root@debian-8gb-nyc3-01:~# which drush
/usr/bin/drush
root@debian-8gb-nyc3-01:~# ls -la /usr/bin/drush
lrwxrwxrwx 1 root root 30 Apr  7 19:49 /usr/bin/drush -> /opt/tools/drush/8/drush/drush
root@debian-8gb-nyc3-01:~#
```

**Comment by omega8cc** [comment]
Also, to easily change PHP on the fly, you should use Octopus instances. We *don't* support hosting anything on the master instance.

**Comment by omega8cc** [comment]
This has been fixed, but we will revert the temporary workaround once BOA-3.0.1 is released (on Monday).

**Comment by BrianGilbert** [comment]
the changelog seems to indicate this hasn't been released yet?
