### ISSUE TITLE
Experimental hosting_git error, platform not installed. 

### ISSUE THREAD

**Issue by heliogabal** [omega8cc/boa#904]
Trying to test this new feature hosting_git, I can get a platform created on my own BOA, but on omega8.cc I get the following error when creating a new platform from a git repo (after Calling hook drush_provision_drupal_pre_provision_verify): 

> We could not find an applicable site for that command. Drush could not bootstrap this platform. Please check the platform directory exists and is readable.

I tried creating an empty directory with the right name, but the error remains. I then tried doing a checkout and a pull on the failed platform (just to see what happens, didn't really expect it to work), and I got:

> The drush command 'provision-git-checkout' could not be found. Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.

Complete Task log: https://gist.github.com/heliogabal/58f6599547c5c1139727860c9f87f012

**Comment by omega8cc** [comment]
Thanks for the report. Can you post the result of command `boa info more` on your own BOA instance, so we could determine why it doesn't work on the hosted instance? Thank you!

**Comment by heliogabal** [comment]
https://gist.github.com/heliogabal/2850a170a6278bc8cb6aa56d3bab1735 

I hope that helps. I have no idea, why it is working there...

**Comment by omega8cc** [comment]
Thanks.

**Comment by heliogabal** [comment]
I can confirm that after update to version 3.0.1 the error is gone and platform is created fine from git! Thanks for this nice and timely fix!

**Comment by omega8cc** [comment]
@heliogabal Thanks for the confirmation!
