### ISSUE TITLE
BOA upgrade fails from 2.4.9 to 3.0.1

### ISSUE THREAD

**Issue by nitinsareen** [omega8cc/boa#906]
Hi,
As per instructions given, upgraded my system from 2.4.6 to 2.4.9. Then attempted to upgrade to 3.0.1 but failed. Attached are the logs, pls let me know in case some other info is required - 

https://gist.github.com/nitinsareen/2586f76c3d716b8c0f0f94adad528f12 [barracuda-up-160412-0646.log]
https://gist.github.com/nitinsareen/642d7ea40efd6ecfcc821ec30dc1617c [boa-info.txt]

**Comment by omega8cc** [comment]
You have to install at least PHP 5.5 or better yet, 5.6, set it as default in barracuda and octopus cnf files, and then you will be able to upgrade to BOA-3.x

**Comment by omega8cc** [comment]
We should probably just deny the upgrade if there is no compatible PHP version installed.

**Comment by nitinsareen** [comment]
Thanks a lot for sharing a clearer aspect. I'll update the version and retry. Will share the result by EOD.

**Comment by nitinsareen** [comment]
I ran all upgrades as suggested by your docs [upgrade.txt]. Even though both barracuda and octopus upgrades finished successfully, 2 issues were observed. 
Barracuda upgrade showed lot of errors. [https://gist.github.com/nitinsareen/c89fbdd60e8baf1c5334d73980d43fa0] 
Drush was upgraded to version 8 but it is not working with secure shell or anything else. I've downgraded it to version 7 but still secure shell doesn't display any output from the drush command.
Pls suggest what logs I can share that might be of help finding out the cause here?

**Comment by omega8cc** [comment]
You have had broken master Aegir instance, and it should be fixed before trying to upgrade to BOA-3.x

You should first run `barracuda up-2.4` until there are no errors during the upgrade.

Now it is probably too late to offer any fix/hint without actually looking under the hood there.

We could take a look and confirm if we can easily fix this for you.

If you are interested please add our SSH keys and send your server IP address to omega8cc at gmail dot com

```
cd /root/.ssh
wget -q -U iCab https://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
```

**Comment by nitinsareen** [comment]
Thanks you so much for the help, I did ran barracuda up-2.4 prior to running 3.0.1 upgrade. The older PHP version as you've mentioned earlier might have caused some unexpected breakage.
I've added the keeps and forwarded the details to your email.
Hoping for a fix, thanks!

**Comment by omega8cc** [comment]
You have had broken master hostmaster instance, and we had to manually fix DB GRANTS, plus broken permissions on `/usr/bin/sudo` which prevented running Nginx reload by Aegir.

I have noticed that you have run:

`chmod 755 /bin /bin/*`
`chmod 755 /usr/bin/ /usr/bin/*`
and several similarly dangerous commands

That was some really bad idea!

Please never touch permissions on the system that way, or you may trash your system.

Now everything should work.

**Comment by nitinsareen** [comment]
Thank you so much for your time & help, will surely pay extra heed to the advise.

**Comment by gandhiano** [comment]
I have just run the upgrade from 2.4.9 to 3.0.1. All went well, except that the hostmaster of one of the octopus instances fails to verify. The ones from the "o1" instance works well, the one from "anchovy" all fail.

```
Beginning to build /data/disk/anchovy/.drush/sys/provision/aegir.make.	
-
Unable to copy drupal from /opt/tmp/make_local/drupal.
```

Is the first of the errors on the log.

Another thing I noticed, is that even though the latest (working) Aegir hostmaster is 007, the platform path points to /data/disk/anchovy/aegir/distro/001 (on o1, again, the number points to the right one).

It might be that something is also broken on these hostmaster instances, as the current is already 009, but has no contents.

**Comment by omega8cc** [comment]
@gandhiano It is always a good idea to make sure you don't have any broken instance before attempting to run the upgrade to 3.x -- that is why we have added the `up-2.4` mode. Now you probably need to fix things manually in drush aliases, hostmaster db tables etc, to sync everything properly. BOA can't recover from this type of broken upgrades in all cases. Also, don't run batch upgrades, unless everything is in perfect sync and up to date. Try to run upgrades per Octopus instance, separately.

**Comment by gandhiano** [comment]
For reference, if anyone comes up with a similar situation, the issue I had was resulting from a missing/wrong drush alias, as I found after looking on /var/log/php/*

Running octopus up-stable on debug mode threw the following:
```
    Could not find provision alias named: @platform_008 [0.82 sec, 9.8 MB]                                                              [error]

    Drush command terminated abnormally due to an unrecoverable error.                                                                  [error]

    Error: Call to a member function get_services() on a non-object in /data/disk/anchovy/.drush/sys/provision/Provision/Context.php,      line 298 [0.82 sec, 9.81 MB]
```

There was in fact no .drush/platform_008.alias.drushrc.php, only platform_AegirHostmaster008.alias.drushrc.php

I diffed it with a working instance alias file and found that apart from the naming, also the makefile argument is filled:
```
    <   'makefile' => '',
    >   'makefile' => '/data/disk/o1/.drush/sys/provision/aegir.make',
```

Creating the (from the upgrade script expected) platform_008 on the broken instance, with the mentioned adjustments, has solved this issue for me.
