### ISSUE TITLE
What is the right way to add custom provision extensions?

### ISSUE THREAD

**Issue by dsnopek** [omega8cc/boa#908]
Mainly, I'm wondering if I put something in `/data/disk/o1/.drush/`, will it be wiped out later in future updates? Should I make a subdirectory in there like `/data/disk/o1/.drush/custom` so my stuff is separate, like the existing `usr/`, `sys/` and `xts/` directories?

Thanks!

**Comment by omega8cc** [comment]
It is a good idea to maintain them in your own subdirectory in `.drush`. BOA will never touch them. Note that it is easy only for Aegir system/backend user (`o1`). The limited shell users (`o1.ftp`) have their `.drush` directories locked with chattr, and selected extensions symlinked there.

**Comment by omega8cc** [comment]
By the way, for extensions which have also the frontend component/module _the right way_ to add them is to include them from the hostmaster space, since Aegir no longer recommends putting them in the backend directly. Provision will then include them via `/data/disk/o1/.drush/drushrc.php`

**Comment by dsnopek** [comment]
Oh, interesting! So, the provision extensions should be part of a module enabled on the hostmaster site? That's actually easer to maintain than putting them in the .drush. :-)

**Comment by omega8cc** [comment]
Correct, that is how entire contrib in Aegir 3.x works. We no longer maintain module+extension pairs, and all contrib backend extensions have been merged into corresponding frontend modules, with their Drush related code included then via single drushrc.php generated automatically. This follows common practice in Drupal contrib space, where Drush related stuff usually comes in a bundle.

**Comment by omega8cc** [comment]
Of course adding something in the `.drush` directly still makes sense when you have some backend-only extension to use.

**Comment by dsnopek** [comment]
Cool, thanks! I haven't dug too much into Aegir 3.x yet.

What I wanted to do was basically backend only - I just want to add something special to all the settings.php files in a particular Octopus. But I might put it in a module on the frontend anyway...

**Comment by omega8cc** [comment]
@dsnopek You could perhaps add it in `/data/conf/settings.global.inc` or `/data/conf/override.global.inc` with some path check to make it Octopus instance or site specific, so you don't need to modify settings.php via Provision (which would require running Verify per site etc). See:

https://github.com/omega8cc/boa/blob/master/aegir/conf/global.inc#L364
https://github.com/omega8cc/boa/blob/master/aegir/conf/global.inc#L872

**Comment by dsnopek** [comment]
Cool, thanks! I think I might be able to make it generic enough to work in all site's settings.php without changes to the code..
