### ISSUE TITLE
Is there a way to switch to key based login in octopus instance instead of password?

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#911]
I've added authorized keys, but still get prompted for password when logging in.

**Comment by omega8cc** [comment]
You have not set correct permissions probably, Please check: https://omega8.cc/ftp-and-sftp-password-not-accepted-120

**Comment by BrianGilbert** [comment]
This does not stop the requirement to enter the password on login.

**Comment by omega8cc** [comment]
It does, if you really follow the how-to and the key added is not broken (like split into more than single line etc) There is nothing BOA specific here, it is how SSH keys work.
