### ISSUE TITLE
systemd is not removed on AWS after install, reboot and barracuda up-stable

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#912]
systemd is not removed on AWS after install, reboot and barracuda up-stable.

I am running an EC2 m3.medium instance in us-west-2b zone, using the Amazon Marketplace AMI for Debian Jessie (NOT the PVM for previous generation) from the Debian foundation. Immediately after launching the instance, I downloaded the BOA installers and installed via boa in-stable public. This failed because of DNS check failure - the installer was picking up the private IP address instead of the public one - but I changed _MY_OWNIP in .barracuda.cnf and re-ran boa in-stable public and this time it worked.

Per the instructions, I then rebooted the instance and ran boa up-stable. The output said that systemd was being removed and then completed normally.

However, restarting nginx failed, and based on that failure I found https://github.com/omega8cc/boa/issues/840, so I tried the referenced commands myself: sysvinit core and utils were already installed, but removing systemd with apt-get failed.

https://gist.github.com/anonymous/ed8e0a5db1141b55787373ce0640713e

**Comment by dnotes** [comment]
I am not sure if it is related to this, but the default /etc/fstab does not contain either cloudimg or cloudconfig, just a single UUID= disk. I believe that is how you test for an AWS system, so perhaps that test is failing. I can open a new issue for that if you'd like.

**Comment by omega8cc** [comment]
Please try this procedure again, but in the way which will not result with re-running the installer on initial install. To make it work, you need to complete uninterrupted install, reboot, and then run the upgrade. At least it worked in all our tests at Linode, DigitalOcean and our own VM instances. Not sure why it could be any different on AWS. Also, even if the detection no longer works as it worked before (that is probably why you were forced to change _MY_OWNIP etc), it shouldn't affect the way the systemd removal is expected to work.

**Comment by dnotes** [comment]
I'm happy to try again, but how would I get the install script to use the public IP? Every time it uses the AWS private IP, and then the DNS fails and it won't install. I have tried with nodns and without. Can I create empty .barracuda.cnf and .o1.octopus.cnf files and just put _MY_OWNIP variables inside of them?

**Comment by dnotes** [comment]
By the way I have also tried the install on a local VM and on digitalocean with no problems, so it does seem to work in general, just not on Amazon.

**Comment by dnotes** [comment]
I finally got a chance to try this today and I can confirm the behavior reported above, even if the boa installation completes the first time with no problems (we added the line "# cloudimg" to /etc/fstab to make it run correctly). It seems something on Amazon breaks this workflow for uninstalling systemd.

**Comment by dnotes** [comment]
I am still having this same problem with version 3.1.0.

**Comment by omega8cc** [comment]
We have not worked on this yet. I hope we will find reliable fix to be included in a bug fix release.

**Comment by DominicBoettger** [comment]
After the installation everhting worked quite well as i already reported. After doing barracuda up-stable system nginx is not starting anymore.... :-(
Happy that i did not have the time to migrate all my stuff yet......

**Comment by dnotes** [comment]
This may be relevant, from [a talk page on without-systemd.org](http://without-systemd.org/wiki/index.php/Talk:How_to_remove_systemd_from_a_Debian_jessie/sid_installation). This hasn't come up in Google searches before today.

This method doesn't work OOtB for an Amazon EC2 instance, instead, this small script (which does the same thing) can be called through the Userdata helper:

```
apt-get -y install sysvinit-core sysvinit sysvinit-utils
apt-get remove --purge --auto-remove systemd
cat >/etc/apt/preferences.d/systemd<<EOF
Package: systemd
Pin: origin ""
Pin-Priority: -1

Package: *systemd*
Pin: origin ""
Pin-Priority: -1
EOF
```

**Comment by omega8cc** [comment]
Well, not sure how it is expected to work:

>> Important
>> User data scripts and cloud-init directives only run during the first boot cycle when an instance is launched.

-- from: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html

We can't really uninstall systemd before the reboot after the initial install.

Ah:

>> Follow the procedure for launching an instance at Launching Your Instance from an AMI, but when you get to Step 6, paste the user data script text into the User data field and then complete the launch procedure.

So EC2 needs to have systemd removed outside of BOA, on initial instance launch. What an ugly workaround.

**Comment by omega8cc** [comment]
By the way, even the Userdata helper will not work, unless the first line will be:

`apt-get update`

**Comment by omega8cc** [comment]
Debugging this on EC2 now..

**Comment by DominicBoettger** [comment]
I tried the commands from @dnotes comment, but it was not possible to uninstall systemd

```
hosting:~# apt-get remove --purge --auto-remove systemd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  systemd*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 14.2 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 63794 files and directories currently installed.)
Removing systemd (215-17+deb8u4) ...
systemd is the active init system, please switch to another before removing systemd.
dpkg: error processing package systemd (--purge):
 subprocess installed pre-removal script returned error exit status 1
Failed to stop lib-init-rw.mount: Unit lib-init-rw.mount not loaded.
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by omega8cc** [comment]
Found it. Debian Jessie 8.3+ needs also grub fix/update: http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_a_Debian_jessie/sid_installation

**Comment by bserem** [comment]
I wonder how easy/difficult would be to do this on my very own desktop 
and get rid of systemd.
Now that I now Om8 supports it I feel more confident (and sadly going 
BSD or Gentoo is not an option atm).

**Comment by omega8cc** [comment]
If you are running Jessie and you still see systemd present if you run `which systemd`, follow the steps:

```
apt-get update
apt-get install -y sysvinit-core
apt-get install -y sysvinit-utils
cp -af /usr/share/sysvinit/inittab /etc/inittab
ls -la /lib/sysvinit/init
grep systemd /etc/default/grub
sed -i "s/init=\/bin\/systemd/init=\/lib\/sysvinit\/init/g" /etc/default/grub
grep init= /etc/default/grub
update-grub
echo -e 'Package: systemd\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
echo -e '\n\nPackage: *systemd*\nPin: origin ""\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
cat /etc/apt/preferences.d/systemd
```

Make sure that `grep init= /etc/default/grub` shows `init=/lib/sysvinit/init` in the line.

Now run `reboot`

Once the system is up again, run:

```
apt-get remove systemd -y --force-yes -qq --purge --auto-remove
```

**Comment by DominicBoettger** [comment]
@omega8cc Thank you very much!
My system is up and running again.

**Comment by omega8cc** [comment]
@DominicBoettger Great! Thank you.

**Comment by omega8cc** [comment]
@bserem You could use the manual procedure from https://github.com/omega8cc/boa/issues/912#issuecomment-231089396 and make sure that all running services are added to `/etc/init.d/` -- and then `update-rc.d service-name defaults`

**Comment by bserem** [comment]
I am going through that, but my grub config says `GRUB_CMDLINE_LINUX_DEFAULT="quiet"`
and there is nothing under `ls -la /lib/sysvinit/init`. As a matter of fact there is no `/lib/sysvinit` folder.

I'll check this again on the weekend after reading without-systemd.org :)

**Comment by omega8cc** [comment]
@bserem `/lib/sysvinit/init` should appear once you will have `sysvinit-core` and `sysvinit-utils` installed.

**Comment by bserem** [comment]
sysvinit-core and sysvinit-utils are installed, but nothing is there. I started with Debian8.4 and I am now following the testing branch.

Anyway, since this is about a personal machine and not a BOA server maybe I shouldn't be polluting the issue queue. I'll make sure to update it if I manage to fix this :)
Thanks for making me aware about this option, I thought the fight against systemd was lost for good, but I guess I was wrong.

**Comment by omega8cc** [comment]
The systemd is a M$-like control ghost on Linux and we hate it with passion ;)

Let us know how it works for you!

**Comment by bserem** [comment]
It turns out you need
`apt-get install -y sysvinit` to get /lib/sysvinit, not just sysvinit-tools and sysvinit-core.

I post this message before I reboot, in case you don't hear from me for a while don't try it!

**Comment by bserem** [comment]
No luck, more when I find the time.
