### ISSUE TITLE
How to bulk create / clone sites in Aegir using a list of sitenames

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#914]
I a plan to use Aegir (part of a BOA server) to host many sales sites, one site for one product.

I would like to know how to bulk-create 1000 sites using an existing platform in Aegir.

This apparently is not included in the Aegir handbook

If it may be more efficient, the other approach would be to clone 1000 sites from one existing site in Aegir.

I suppose that this can be accomplished either way using Drush, but how?

**Comment by omega8cc** [comment]
You may want to explore first if you really need separate sites. Maybe https://www.drupal.org/project/domain would work for you?

If you need to create sites in bulk, it is not supported, you would need to script this, but it should be fairly easy.

A good (old, but still useful) starting point: https://mig5.net/content/manage-your-aegir-system-command-line

**Comment by Corvalan** [comment]
Thank you I'll give the drush scripting a try.
Project Domain is not useful for more than 10 domains.
