### ISSUE TITLE
How to remove the under construction page

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#915]
A site of which the domain doesn't resolve shows 'under construction'. Can this under construction page be removed and instead just return a 404 page not found?
This is because I am using a script to check websites that are down or broken links for a large number of Aegir sites.

**Comment by omega8cc** [comment]
Edit `/var/aegir/config/server_master/nginx.conf`

Replace
```
server {
  listen        *:80;
  server_name  _;
  location / {
    expires 99s;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    add_header Access-Control-Allow-Origin *;
    root   /var/www/nginx-default;
    index  index.html index.htm;
  }
}
```

with

```
server {
  listen        *:80;
  server_name  _;
  location / {
    return 404;
  }
}
```

Note that any matter instance upgrade will overwrite this change.
