### ISSUE TITLE
Aegir does not support special characters for IDN domain names

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#916]
Using Internationalized Domain Names (using special characters) returns 'You have not specified a valid url for this site'
https://www.icann.org/resources/pages/idn-2012-02-25-en

**Comment by omega8cc** [comment]
This is not a BOA specific issue. You may want to search for related tickets in Aegir issue queues on drupal.org

**Comment by omega8cc** [comment]
Note also that we have had the extra JS code to support this in BOA-2.x but it no longer works after upgrade to D7 based Aegir 3.x -- https://github.com/omega8cc/hosting/blob/feature/3.0.x-hosting/site/hosting_site.form.js#L187

**Comment by omega8cc** [comment]
While this is still Aegir problem, the trivial fix should be somehow ported to 3.x fork we are using

**Comment by radimklaska** [comment]
I believe you can use encoded domain name. For example: test-ěščřžýáíé.cz becomes xn--test--1qa0d5a6lpg7fz4agd4s.cz and Aegir should recognize it just fine.

This is one of the first tools i found to encode/decode the domain: http://idn-encoding.online-domain-tools.com/

**Comment by omega8cc** [comment]
@radimklaska yes, but it worked directly in the add site form in BOA 2.4

**Comment by omega8cc** [comment]
We will try to debug this in head: https://github.com/omega8cc/hosting/commit/b0ed00fcbe4218112d639ac4875fa0ea76d8e28e

**Comment by omega8cc** [comment]
Fixed!
![idna_convert](https://cloud.githubusercontent.com/assets/128547/14762944/5e756314-0987-11e6-94fc-a7b001ca237a.jpg)

**Comment by Corvalan** [comment]
Amazing! Thank you
