### ISSUE TITLE
Call to undefined function conf_path() when installing a D8 website

### ISSUE THREAD

**Issue by steeff** [omega8cc/boa#917]
Hi,
is BOA-3.0.1 ready to support D8 websites?
I have created a new platform based on D8.1 in ~/static folder (that looks good...) and when I try to create a website based on that it fails.
I do not find any documentation about creating specific D8 websites but point me into the right direction if it exists... 
thanks

**Comment by omega8cc** [comment]
If you see this error, it simply means that you have not completed successful upgrade for both barracuda and octopus, because this error is possible only when you still have Drush 7 used by default. BOA supports Drupal 8 since 3.0.0 release.

**Comment by steeff** [comment]
drush --version
 Drush Version   :  8.1-dev 
but there are maybe several concurrent versions of drush running?

**Comment by steeff** [comment]
yes indeed my octopus instance was not up-to-date. I was confused by the message about the upgrade to previous stable BOA-2.4.9 before v3
thanks

**Comment by omega8cc** [comment]
Every Aegir instance in BOA (master and all octopus instances) has its own, local Drush. This makes it possible to run 3.x and 2.x instances on the same system. When you invoke drush on command line, you are using yet another copy, which defaults to drush8 on all systems with barracuda 3.x or newer.
