### ISSUE TITLE
Warning messages in tasks queue: Nginx could not be restarted

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#920]
I see that in the tasks queue the 'verify' task for all built-in drupal distro's have a warning:
ngingx on my.server.xyz could not be restarted. 
http://i.imgur.com/6pYzDng.png

**Comment by omega8cc** [comment]
You need to check nginx error log and try this as root on command line, since from the error displayed it is not clear why it can't proceed with reload.
