### ISSUE TITLE
Cron not running on cloned site to new site - can't save a site edit in the Octopus instance GUI either

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#922]
I cloned a site to a new domain name. I want both sites to exist - with same content but in different languages. On the cloned site, which I gave a new domain name, cron is not running, and in the Octopus instance, I cannot edit the site and get a different cron period to save - it always reverts back to default 24 hours (even though it doesn't actually run cron on this new site). Changes to other settings, like backup period - do save, although backup isn't working - probably because cron isn't being run.

I know you have advised not to create a new site by cloning an existing one, although I can't remember exactly why - is this a problem (not running cron) that can't easily be fixed, or fixed at all?
I am running BOA 3.0.1 stable on PHP 5.6 (both) with no real other problems.

Best regards,

Ed

**Comment by omega8cc** [comment]
Thanks for the report. It is a bug -- regression introduced probably after we have merged in the advanced cron module code, after converting it to Drupal 7 API. Cloned site has no record in the `hosting_cron` table, so it is not possible to save custom values and cron doesn't work for cloned sites at all. Note that this affects only sites cloned using BOA-3.0.0 or newer. The manual fix is to add the entry in that table in the hostmaster site, but we obviously needs to re-introduce the fix we have added in Aegir 2.x before.

**Comment by omega8cc** [comment]
This has been fixed in head via this commit: https://github.com/omega8cc/hosting/commit/998a725f0e3e148f74733096524677f32760a76c

**Comment by omega8cc** [comment]
Well, for now it is fixed for newly cloned sites. We still need to add a fix for existing sites.

**Comment by omega8cc** [comment]
Now fixed also for existing sites: https://github.com/omega8cc/hosting/commit/63e8838bad8cefdfe06561193b4dd3705ee408a1
