### ISSUE TITLE
install_update_composer() install error

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#923]
When installing a new BOA system with boa in-head (3.1.0-dev) I get the following:
```
BOA [06:13:59] ==> INFO: Installing YAML for PHP 7.0.5...
curl: (23) Failed writing body (0 != 16133)
mv: cannot stat ‘composer.phar’: No such file or directory
BOA [06:14:13] ==> INFO: Installing Limited Shell 0.9.18.3...
BOA [06:14:26] ==> INFO: Installing Redis update for Debian/jessie...
```

Installation started like this:
boa in-head public DOMAIN EMAIL OCTOPUS none php-7.0

Could be nothing, but I'm mentioning it anyway.

**Comment by bserem** [comment]
Update:
I get the same error on stable install too, with no platforms and php-7.0

**Comment by omega8cc** [comment]
Could be just YAML compatibility issue.

**Comment by omega8cc** [comment]
It was failed composer install, probably due to temporary connectivity problems, because I can't reproduce this. Here is the relevant code:

```
install_update_composer() {
  if [ -x "/usr/local/bin/composer" ]; then
    /usr/local/bin/composer self-update &> /dev/null
  fi
  if [ ! -x "/usr/local/bin/composer" ] || [ ! -L "/usr/bin/composer" ]; then
    rm -f /usr/local/bin/composer
    rm -f /usr/bin/composer
    rm -rf /root/.composer
    mkdir -p /var/opt
    cd /var/opt
    curl -sS https://getcomposer.org/installer | php &> /dev/null
    mv composer.phar /usr/local/bin/composer
    ln -sf /usr/local/bin/composer /usr/bin/composer
  fi
}
```

**Comment by omega8cc** [comment]
Try this manually on the server for testing:

`$ cd /var/opt`
`$ curl -sS https://getcomposer.org/installer | php`

**Comment by omega8cc** [comment]
Ah, it was yet another side effect of using `php-7.0`
