### ISSUE TITLE
robots.txt recreated in html format!

### ISSUE THREAD

**Issue by nitinsareen** [omega8cc/boa#925]
Hi, earlier in issue #906, with your help the box upgraded from 2.4.6 to 3.0.1. Since that update, twice it has been observed that robots.txt is been overwritten in html format. Since this is a live site with heavy SEO invested, such a format could lead to bad ranking. One of the main reasons I had to recover the backup immediately.
It is happening to all my sites after upgrade. Currently one of my sample sites have this issue for your reference - http://starterv1.o1.samedaypros.com/robots.txt

Is this by design or some upgrade issue? Please let me know if there is anything else I need to provide as info?

As usual your help is truly appreciated, thanks!

**Comment by nitinsareen** [comment]
To add to this the file robots.txt is created as a root user instead of o1.ftp or o1. Is this too by design?

**Comment by nitinsareen** [comment]
Interestingly in one of my custom drupal 8 sites the error seems to be quiet visible - 

cat robots.txt

<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "http://sdp8.samedaypros.com/robots.txt?nocache=1&amp;noredis=1&amp;q=robots.txt" was not found on this server.</p></body></html>

The script daily.sh that runs fix_robots_txt(), call this via curl.

**Comment by omega8cc** [comment]
We should run this procedure only for D6/D7 sites, because it depends on the `robots txt ` module, and we don't add any o_contrib for Drupal 8, for now.

But it shouldn't cause problems for D6/D7 sites.

Please provide the output of `boa info` command.

**Comment by nitinsareen** [comment]
Aegir on Debian/wheezy x86_64
  VPS XEN
  CPU 4
  RAM 7748
  XTR _XTRAS_LIST="CSF CHV FTP CSS SR4"
  MFX _MODULES_FIX=NO
  PFX _PERMISSIONS_FIX=NO
  DBS _DB_SERIES=5.5
  DNS _DNS_SETUP_TEST=YES
  PKG _EXTRA_PACKAGES=
  NGX nginx/1.9.14
  SSL 1.0.1e
  CRL 7.45.0
  SSH 7.2p2


Please link this information in your submission,
but only in a form of Gist snippet and not inline,
along with your hosting provider name
in the BOA issue queue on GitHub.

root@boaaegir:~#

**Comment by omega8cc** [comment]
Please modify these lines in your `/root/.barracuda.cnf` file:

_MODULES_FIX=YES
_PERMISSIONS_FIX=YES

Then run these commands:

`$ screen`
`$ bash /var/xdrago/clear.sh`
`$ bash /var/xdrago/daily.sh`

Note that the `daily.sh` command will take a long time to complete.

**Comment by nitinsareen** [comment]
Thanks a lot, have run the said commands. Will revert in case the issue reoccurs.
