### ISSUE TITLE
API call to lists/list failed: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#927]
D8 Site using the mailchimp modue was reporting this..

Solution at:
https://www.drupal.org/node/2477693#comment-10785922

**Comment by BrianGilbert** [comment]
This doesn't appear to be a complete solution..

**Comment by omega8cc** [comment]
How is this related to BOA? It's a mailchimp problem if it still depends on some outdated cert. We are not going to downgrade security by adding old certs to satisfy third party software, but you can try this on your system, I think.

**Comment by omega8cc** [comment]
Anyway, if you will find anything which should/can be fixed in BOA in this context, feel free to reopen this issue.
