### ISSUE TITLE
Detection of Amazon AWS / EC2 instance fails in install scripts

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#930]
I am running an EC2 m3.medium instance in us-west-2b zone, using the Amazon Marketplace AMI for Debian Jessie from the Debian foundation. Immediately after launching the instance, I downloaded the BOA installers and installed via boa in-stable public. This failed because of DNS, as the installer was picking up the private IP address instead of the public one. It turns out that this is a symptom of a wider failure: the install scrips attempt to recognize Amazon instances by checking the /etc/fstab file for the words "cloudimg" or "cloudconfig", but the /etc/fstab file on this instance does not have either of those words.

As a workaround, we added the line "# cloudimg" to the /etc/fstab file, and then the installation went fine.

https://gist.github.com/dnotes/27dfd944c1c072a4d88306c410f05e0b

**Comment by omega8cc** [comment]
Right, we need to figure out how to detect AWS instance reliably after they no longer have these entries in /etc/fstab

**Comment by omega8cc** [comment]
Other also struggle to find reliable method, but at least there are some tricks to try: http://serverfault.com/questions/462903/how-to-know-if-a-machine-is-an-ec2-instance

**Comment by omega8cc** [comment]
Should be fixed now.
