### ISSUE TITLE
Cron runs every three minutes for sites, even if cronjobs are disabled

### ISSUE THREAD

**Issue by Nebel54** [omega8cc/boa#931]
I've got a strange issue on two different BOA-Servers. Site cronjobs are executed on nearly all sites every three minutes. It does not matter if cronjobs are disabled for a site or the interval is set to 1/3/6 hours.

Can anyone confirm my observations?

Output of boa info:
https://gist.github.com/Nebel54/9972737ffc6e6eebf5be07e2d731fd9d

**Comment by omega8cc** [comment]
I have seen this on one instance after failed octopus upgrade from BOA-2.4.9, which resulted with BOA specific feature left disabled.

Please upgrade to BOA-3.0.2 (both barracuda and octopus).

As a quick workaround, run these commands (if the instance is still on BOA-2.x)

`$ syncpass fix o1`
`$ su -s /bin/bash - o1`
`$ drush @hostmaster en aegir_custom_settings -y`
`$ drush @hostmaster fr aegir_custom_settings -y`
`$ drush @hostmaster cc all`

If it i already on BOA-3.x, run these commands instead:

`$ syncpass fix o1`
`$ su -s /bin/bash - o1`
`$ drush @hostmaster en hosting_custom_settings -y`
`$ drush @hostmaster fr hosting_custom_settings -y`
`$ drush @hostmaster cc all`

Then watch the nginx access log (as root) to make sure that the UA reported is not `Drupal` but `iCabProXy`:

$ tail -f /var/log/nginx/access.log | grep cron.php

**Comment by Nebel54** [comment]
Thanks omega8cc for the quick reply, sorry for my late response. I just tried enabling hosting_custom_settings and it failed (in BOA 3.0.2), because the module hosting_custom_settings does not exist:

drush @hostmaster en hosting_custom_settings
hosting_custom_settings was not found.

In my .barracuda.cnf automatic updates are enabled, but is set to:
_AEGIR_UPGRADE_ONLY=NO
_SYSTEM_UPGRADE_ONLY=YES

Is it possible that i need to run a full upgrade manually to get the custom settings feature?

**Comment by omega8cc** [comment]
Maybe you just need to run full upgrade for both barracuda and octopus and not just system upgrade?

It is explained at the top of https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt

**Comment by omega8cc** [comment]
>> automatic updates are enabled

No, automatic updates can be enabled only for system-only upgrade, while full upgrade has to be scheduled or run manually.

>> _AEGIR_UPGRADE_ONLY=NO
>> _SYSTEM_UPGRADE_ONLY=YES

These two variables have nothing to do with automatic upgrades

**Comment by omega8cc** [comment]
It is explained in the docs: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L108

**Comment by Nebel54** [comment]
Thanks again for the feedback! The automatic upgrades where enabled. I just managed to overlook, that i still need to perform octopus upgrades manually. After upgrading the octopus instances (which where still on a version pre 2.4.9) the error was gone.
