### ISSUE TITLE
Support Request: Anyone tried switching a BOA installation from XEN to KVM on linode?

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#932]
Linode is using KVM for all new VMs, but older ones still use XEN and they have an option to switch to KVM (with a downtime of some minutes, depending on the VM size).

I believe this is irreversible. I currently don't have any dev BOA servers with XEN. Only a production server has been left with XEN, and I am hesitant to do the switch.

Has anyone tried it? Did you run into any issues?

**Comment by omega8cc** [comment]
We have switched many BOA instances from XEN to KVM on Linode, with zero issues.

**Comment by bserem** [comment]
Thanks, I did the switch and I can also verify that it went without issues. Total downtime was ~5m for 50gb.
