### ISSUE TITLE
sites all down - mariadb stopped after 3.0.2 upgrade

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#933]
Maria DB is stopped and all sites are down after upgrade to mariaDB - php5.6 for both.

A mariadb restart failed with error: no valid socket file " " found!

boa info command is here:  https://gist.github.com/EdNett/47376c43f082248703ec74df3b9a1368

**Comment by omega8cc** [comment]
I have never seen anything like that. You may need to investigate the verbose upgrade log you can find in /var/backups/ to determine what exactly happened.

**Comment by EdNett** [comment]
barracuda upgrade log is here - looks like pdnsd error:

https://gist.github.com/EdNett/82b6c57d12b9a1dac81cbea1deeea1f0

**Comment by EdNett** [comment]
I can't get barracuda master or octopus gui to resolve, currently.

**Comment by EdNett** [comment]
nginx is running, pdnsd is running ... php56-fpm is running - they all restart fine - it's only mysql (mariadb) that doesn't start - am investigating it further.

**Comment by EdNett** [comment]
mysql can't find the socket - do I need to upgrade to head? (This is a production server - this didn't happen on my test vps that I upgraded to boa 3.0.2 24 hours before this one)!

server1:~# /etc/init.d/mysql force-reload
[....] Reloading MariaDB database server: mysqld/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
server1:~#

**Comment by EdNett** [comment]
There is no file in /run/mysqld/

**Comment by EdNett** [comment]
re-running barracuda up-stable does not fix the problem. WOuld you suggest starting mysql in safe mode - or reinstalling mariadb? Galera Cluster wasn't installed by mistake, was it? - for 10.0.25?

**Comment by omega8cc** [comment]
There is no sign of any problem in this log.

Maybe your disk is full?

**Comment by omega8cc** [comment]
Please run this command for some hints:

`grep mysql /var/log/syslog`

**Comment by EdNett** [comment]
Thanks for that hint:

It looks like the problem was in a innodb cache table file. I have forced a repair by adding innodb_force_repair = 1 to the my.cnf file, and now mysql has started and the .sock file is present. Here is the error:

https://gist.github.com/EdNett/fee1c75eb7ff8cb8a4776d9668e57b90

**Comment by EdNett** [comment]
The problem is resolved for me - thanks for your help. I wonder what caused it?

**Comment by omega8cc** [comment]
It could be a disk error, OOM which caused the parent system to kill mysql, etc. Please note that after the server was able to recover, you need to remove `innodb_force_repair` or set it to `0` -- it is explained i this article: https://mariadb.com/kb/en/mariadb/xtradbinnodb-recovery-modes/

**Comment by omega8cc** [comment]
This commit should help to avoid crashing mariadb, unless it was not XtraDB default behavior which crashed it: https://github.com/omega8cc/boa/commit/d5125893e6b41ae0e48716a3e793272319df3316
