### ISSUE TITLE
Clean 2.4 install "Errors were encountered while processing: auditd"

### ISSUE THREAD

**Issue by radimklaska** [omega8cc/boa#934]
Hi, I have clean install on new dedicated Debian Jessie server.

After running:
`cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`
`boa in-2.4 public boa.example.com boa@example.com o1 none`

I noticed few errors (logs below). Install finised. Managing and serving sites seems to be working.

Then I run `apt-get install nload` and got this:
`Setting up auditd (1:2.4-1+b1) ...`
`update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults`
`[FAIL] Starting audit daemon: auditd failed!`
(skipping expected output, nload installed correctly)

From syslog:
`May  9 12:28:50 boa auditd[22252]: Error - audit support not in kernel`
`May  9 12:28:50 boa auditd[22252]: Cannot open netlink audit socket`
`May  9 12:28:50 boa auditd[22252]: The audit daemon is exiting.`
`May  9 12:28:50 boa auditd: Cannot daemonize (Success)`
`May  9 12:28:50 boa auditd: The audit daemon is exiting.`

boa info more:
https://gist.github.com/anonymous/3e158d1a5363029fd91fd40169e90bb1#file-jessie-boa-info-more

barracuda-install-160509-1035.log
https://gist.github.com/anonymous/3e158d1a5363029fd91fd40169e90bb1#file-jessie-barracuda-install-160509-1035-log (check line 2668, for more occurrences of this error search for "Errors were encountered while processing")

Any help would be much appreciated.

**Comment by omega8cc** [comment]
It is normal on initial install on Jessie, because `sysvinit` is not active yet. The problem should be gone after you reboot and run barracuda upgrade to remove `systems` cleanly.

Note that `boa-2.4` is no longer supported, even if it can be installed, so no bug fixes are possible/expected.

**Comment by radimklaska** [comment]
Cool, thanks for the prompt info! I used 2.4 just to xboa another instance over and do all the updates safely.
