### ISSUE TITLE
mysql connections aborted too high and error in barracuda upgrade

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#937]
I see that we have a mysql report connections aborted rate of 46% since the upgrade to 3.0.2 stable, so I re-ran the up-stable, this time with _CUSTOM_CONFIG_SQL=NO, and saw this error:

Calling hook drush_db_provision_migrate_validate [7.48 sec, 9.39 MB]             [debug]
SQLSTATE[28000] [1045] Access denied for user 'aegir_root'@'localhost' (using[error]
password: YES) [7.48 sec, 10.03 MB]
Returned from hook drush_db_provision_migrate_validate [7.48 sec, 9.4 MB]        [debug]
Command dispatch complete [7.48 sec, 9.37 MB]   

Could this error be causing the high connections aborted ?

BOA info is here:
https://gist.github.com/EdNett/0c6e4a9272cc4058f7dcbfcc7117c61d

After this up-stable connections aborted is 36% after 10 min of mysql running. DO I need to sync password? or, what do you suggest?

Here's the mysql report after 2 min of uptime:
https://gist.github.com/EdNett/dc4286134f0edd31e3672cbccccd47c3

Thank you.

**Comment by omega8cc** [comment]
Please try this (twice):

`$ syncpass fix aegir`
`$ syncpass fix aegir`

Then run `barracuda up-stable` again (to run hostmaster upgrade again)

Then make sure to upgrade all octopus instances with:

`$ octopus up-stable all both`

**Comment by EdNett** [comment]
Thanks for that advice. FYI: this was the screen return to the syncpass commands (not exactly what I would expect):
https://gist.github.com/EdNett/d1baf239ba29e617727605ba6d09f8c2

I am running the up-stables and will confirm result when finished.

**Comment by EdNett** [comment]
I already see the same error in the barracuda upgrade:
https://gist.github.com/EdNett/435dd31e049fe24359a557c96989a419

**Comment by EdNett** [comment]
In fact this file does exist - could the permissions be wrong?:
INFO: Expected file /var/aegir/backups/system/.aegir_root.pass.txt does not exist
Here are file/folder ownerships and permissions:

file /var/aegir/backups/system/.aegir_root.pass.txt :  Owner 110 Group 119,  644

Folder /var/aegir/backups/system/ = 110,119, 700

folder /var/aegir/backups = 110,119,  750

folder /var/aegir  =  110,119 755

**Comment by EdNett** [comment]
I found this mysql error connecting error at the very beginning of last barracuda-up stable:
https://gist.github.com/EdNett/96bdbdf014485afcf8bf314b623c5dd5

**Comment by EdNett** [comment]
I am going to try the whole thing again (your fix advice in your first comment, above) starting with the syncpass aegir command again - this time with the  .mysql.yes.new.password.cnf file present in the root.

**Comment by EdNett** [comment]
In fact we are getting both mysql connection errors - at the very start of the upgrade:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

and later in the upgrade process:
SQLSTATE[28000] [1045] Access denied for user 'aegir_root'@'localhost' (using[error]
password: YES) [7.45 sec, 10.03 MB]

gist is here:
https://gist.github.com/EdNett/56326a6c53e3c88c7d8739b0b5718771

Is there another more comprehensive syncpass command or sequence of commands to ru? I am going to stop trying to fix this now using your previous instructions, as it isn't working. Thanks for your advice and help.

**Comment by EdNett** [comment]
I think there is a problem with mariadb 10.0.25 - it must have changed the way one can connect to the db - since all of my mysql connect problems happened with the mariadb upgrade to 10.0.25.  The only non-boa thing I do on this dedicated server is occasionally run the mysqltuner.pl script in order to fine-tune the mysql configuration file for speed.  When I run that script (it is only run manually from the terminal command, and I know it is an old script) it is giving many connection errors, and it also reports that I am not running the script as the root user, even though I am:

https://gist.github.com/EdNett/d92ad81bd599a89c1f9f94582ed809f5

**Comment by EdNett** [comment]
When trying to connect to mysql via the command line I get some interesting errors including a bash return echoing the part of the password that begins and ends with exclamation points - stating event not found!:
https://gist.github.com/EdNett/5b1eebfc99f5279ba09c498f5faf245a

**Comment by omega8cc** [comment]
>> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

The `syncpass` command will do nothing if the mysql `root` password doesn't match the password stored in `/root/.my.cnf`

You have managed to somehow break mysql root password, and it is not updated on upgrade, so it should just for, if it worked before.

This will cause all internal tasks and upgrade attempts to fail.

You need to first sync the mysql root password with `/root/.my.cnf`

**Comment by EdNett** [comment]
I have researched this and I believe the problem occurred when mysql crashed because of a crashed cache table in one site - this issue:
https://github.com/omega8cc/boa/issues/933

I see that the last backup aegir took was the site before the site that had a cache table marked as crashed on that day - and no backups have been made since. - neither site backups nor the sql backups in /arch: which are empty.

So, how do you suggest that I sync the mysql root password with /root/.my.cnf? By just updating it to whatever is found at present in the /root/.my.cnf file?

Thank you for your advice

Ed

**Comment by omega8cc** [comment]
This has nothing to do with mysql crash. Yes, you just need to set the mysql root password to match the password listed in both `/root/.my.cnf` and `/root/.my.pass.txt`

**Comment by EdNett** [comment]
Well I did that (although I didn't verify the .my.pass.txt - but I changed the mysql root password to be the same as that found in /root/.my.cnf  and had lots of errors when running the upgrade - 
https://gist.github.com/EdNett/3145ae56c6ffae076199954c3dd595b9

**Comment by omega8cc** [comment]
After you have synced mysql root password, you have to sync Aegir Master Instance mysql password with:

`syncpass fix aegir`

Run this twice and *then* try the upgrade again.

**Comment by EdNett** [comment]
Hello,

This is not working - and it is the same problem as before - mysql connect errors - having something to do with connecting via socket, I believe.  I also believe I saw a reference to php5-fpm in your code somewhere (and this sounds like an error - shouldn't it be php56-fpm?).

For example (I have tried this 3 times each time fails the same way) - at the beginning of the barracuda upgrade the mysqltuner test fails - here is failure report:
https://gist.github.com/EdNett/167dddbe9558ca921c28367e3718bc7a

Notice it says InnoDB is disabled and INNOdb is not being used, and repeatedly 👍 ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")

**Comment by EdNett** [comment]
Hello,

happy to say that after forcing the octopus update, that a full barracuda up-stable and octopus up-stable force (octopus won't update if there is nothing to update, and screen returns a strange message: Failed Update - maybe change this so it doesn't read failure?

The high mysql aborted connections is gone do I'm going to close this, and thank you for your help getting the passwords back into sync. I was alarmed by the messages in the mysqltuner.pl script and by another tuning-primer.sh script (by Matthew Montgomery) that report INNOdb as disabled, etc, and then I don't understand the references to php5-fpm related to sockets, when I never use php5-fpm, but only php56-fpm or php55-fpm, etc.

Thank you - it appears to be working fine now that the passwords are all synced.
