### ISSUE TITLE
Add auto-renewal procedure for Let's encrypt certs

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#942]
We have added Let's encrypt support in #500, but there is no auto-renewal in the `daily.sh` script implemented yet. It should be simple, because all we need to do it is to call `letsencrypt.sh -c` per Octopus instance, if the script exists there.

**Comment by almereyda** [comment]
Pasting a piece from @ecobytes' internal documentation, that featureas a simple approach for the `acme-challange` validation. Useful if no webserver is yet present on a system.

```
### create TLS certificate

with [letsencrypt.sh](https://github.com/lukas2511/letsencrypt.sh) + `python -m SimpleHTTPServer`

* `/root/letsencrypt.sh`
  * `domains.txt`

    ```
    email.ecobytes.net
    ```
  * `config.sh`

    ```
    WELLKNOWN="/root/.webroot/.well-known/acme-challenge"
    CONTACT_EMAIL="hostmaster@ecobytes.net"
    ```
* `mkdir -p /root/.webroot/.well-known/acme-challenge`
  * `cd /root/webroot`
  * `python -m SimpleHTTPServer 80`, but kill it when done
```

**Comment by omega8cc** [comment]
This has been partially fixed by this commit: https://github.com/omega8cc/hosting_le/commit/5c8909d1fcce34901830c0de26fc55b860eb973e

We still need to fully automate this, though.
