### ISSUE TITLE
The makefile based platform creation fails with permissions error

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#943]
The error reported is:

>> Destination directory /data/disk/o1/.tmp/cache/download is not writable."

This is probably only a symptom and not the real issue, because the Aegir backend user has full write access there all the time.

**Comment by radimklaska** [comment]
I can see the same issue. drush @platform_test1 provision-verify fails at random projects. Seem like some race condition / network issue. Any way I can help with this? / Provide more info?

boa info more: https://gist.github.com/anonymous/a5cff3344cba13f8dedc5579b758e694

**Comment by omega8cc** [comment]
Well, something really trivial... 

Check what you will see in your `/data/disk/o1/aegir.sh` -- on line  number 6.

We have added this before during debugging some failed upgrades, but later the proper fix has been added elsewhere.

Ouch!
