### ISSUE TITLE
allowing URLS generated by AMP modules

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#944]
Hello 
I have installed AMP module for my news website. The problem is that the server generates a redirection for google bot. To be able to access the AMP version i need to add "?amp" at the end of my website URLS.   
Is there a custom setting that i need to make on the server to be able to allow googleBot to access this URL without generating a 301 redirection. 
Thanks for any suggestion.

**Comment by omega8cc** [comment]
Unfortunately this protection is hardcoded and is not configurable: https://github.com/omega8cc/provision/blob/3.x.x-dev/http/Provision/Config/Nginx/Inc/vhost_include.tpl.php#L1170

```
###
### Send all not cached requests to drupal with clean URLs support.
###
location @drupal {
  error_page 418 = @nobots;
  if ($args) {
    return 418;
  }
  rewrite ^/(.*)$  /index.php?q=$1 last;
}
```

```
###
### Send all known bots to $args free URLs.
###
location @nobots {
  if ($is_bot) {
    return 301 $scheme://$host$request_uri;
  }
  ###
  ### Return 404 on special PHP URLs to avoid revealing version used,
  ### even indirectly. See also: https://drupal.org/node/2116387
  ###
  if ( $args ~* "=PHP[A-Z0-9]{8}-" ) {
    return 404;
  }
  rewrite ^/(.*)$  /index.php?q=$1 last;
}
```

https://github.com/omega8cc/provision/blob/3.x.x-dev/http/Provision/Config/Nginx/server.tpl.php#L248

```
###
### Deny all known bots/spiders on some URIs.
###
map $http_user_agent $is_bot {
  default  '';
  ~*crawl|bot|spider|tracker|click|parser|google|yahoo|yandex|baidu|bing  is_bot;
}
```

**Comment by omega8cc** [comment]
Correction: you *can* override named location, see example: https://github.com/omega8cc/boa/issues/948#issuecomment-224548976
