### ISSUE TITLE
Cosmetic error when selecting Octopus to not install platforms

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#945]
I just upgraded BOA 3.0.1 -> 3.0.2 and I got this cosmetic error:
`touch: cannot touch /data/all/008/javascript_aggregator.out.txt: No such file or directory`

This is quite old cosmetic bug (I remember it happened to me before during upgrades), but just haven't reported about it, should be easy fix I think.

Cheers for BOA, you guys rule!

BOA info: https://gist.github.com/Pls/d989d8e72b29f7c6f0a9d53efb43445f
Octopus upgrade log: https://gist.github.com/Pls/acb90578686e75d245bba5bdcd7aa17e

**Comment by omega8cc** [comment]
Fixed!

**Comment by Pls** [comment]
You guys are the best!
