### ISSUE TITLE
FATAL ERROR: Drush is broken (/opt/php56/bin/php /data/disk/o1/tools/drush/drush.php help failed)

### ISSUE THREAD

**Issue by sTb1337** [omega8cc/boa#946]
Hi there, 

ill tryed to install the latest stable version but the installation failed after the Shared platforms and users were created. (see gist links)

Is this system still functional intact because we dont need the shared platforms and the setup stated "BOA in-stable completed" at the end.

boa info: https://gist.github.com/SteffenBxyz/bb4c60f2679a103f746cb830246bc99f
boa installation log:  https://gist.github.com/SteffenBxyz/b3143fa78ccc640c0186566b4b1cbf58
.barracuda.cnf file: https://gist.github.com/SteffenBxyz/9776a52f9403359f77703ac9029183f7

**Comment by omega8cc** [comment]
It failed early for some reason -- maybe tmp connection issue. You could install just Octopus now with `boa in-octopus etc` command, but choose different name or remove leftovers first:

`deluser o1`
`rm -rf /data/disk/o1`

**Comment by omega8cc** [comment]
Note: it installed only master instance you shouldn't use, but it failed to install the satellite instance, so you need to install one. There is no need to re-install the system, though.

**Comment by memtkmcc** [comment]
Not sure why this happens now (we have never seen this before with BOA-3.0.2), but I have just reproduced this with BOA head:

```
BOA [16:50:52] ==> INIT A: Shared platforms code v.001 (new) will be created
BOA [16:50:52] ==> INIT A: Adding user...
BOA [16:50:57] ==> INIT B: Downloading drush micro-8-24-04-2016...
BOA [16:51:02] ==> INIT B: Installing Aegir Provision backend...
BOA [16:51:02] ==> INIT B: Downloading Drush and Provision extensions...
BOA [16:51:08] ==> INIT B: FATAL ERROR: Drush is broken (/opt/php56/bin/php /data/disk/o1/tools/drush/drush.php help failed)
BOA [16:51:08] ==> INIT B: FATAL ERROR: Aborting AegirSetupB installer NOW!
BOA [16:51:08] ==> INIT A: FATAL ERROR: AegirSetupB installer failed
BOA [16:51:08] ==> INIT A: FATAL ERROR: Aborting AegirSetupA installer NOW!
BOA [16:51:08] ==> FATAL ERROR: AegirSetupA installer failed
BOA [16:51:08] ==> FATAL ERROR: Aborting Octopus installer NOW!
```

Now testing if this commit could fix this: https://github.com/omega8cc/boa/commit/50817c8401c310db1ed03f788e811d4fa62c6b2a

**Comment by memtkmcc** [comment]
Looks fixed after that commit, but it was weird anyway.
