### ISSUE TITLE
Drupal 8 database update (update.php)

### ISSUE THREAD

**Issue by leevh** [omega8cc/boa#947]
Hello, I cannot seem to manually run the database update script on drupal 8 sites.  

boa info: https://gist.github.com/leevh/9a76b8ec5d49623e4078de2ebc680006

Steps to reproduce for me:

-drush dl drupal-8 in static directory
-set permissions as https://omega8.cc/how-to-add-custom-platform-properly-140 and added platform
-created new site on platform and visit update.php
-click continue --> "Page not found"
-run "Run db updates" from Aegir UI
-visit site and it only shows "The website encountered an unexpected error. Please try again later."

These steps all work as expected on drupal 6 & 7 sites on this Octopus instance

Any thoughts?  Any info I could provide?  thank you!

**Comment by omega8cc** [comment]
We didn't implement this yet, because you are not expected to run updates like this. If you really want to skip migrate procedures, you can still run db updates with drush. But since it worked for Drupal 6 and 7, we should fix this for Drupal 8, too.

**Comment by leevh** [comment]
Totally understood and thank you.  Just as a followup to that, I have tried using drush as o1.ftp user and `drush updatedb` says the command is not available directly and to use `drush dbup` .  Trying that yields `The drush command 'dbup' could not be found.`

**Comment by omega8cc** [comment]
@leevh -- You should be able to run it via drush alias:

`drush @sitename updb`
