### ISSUE TITLE
Adding AMP support

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#948]
Our site is hosted on BOA and we appreciate speed and security feature. Being able to generate AMP pages is critical for us. We have a news site and we struggle to appear on results on googlenews. 
We would love to see a fix on future release of BOA to allow us to stay visible.

**Comment by attiks** [comment]
FYI: https://www.drupal.org/node/2744331

**Comment by angel0d** [comment]
@yazzou I think you can override the default behaviour and allow urls with ?amp to reach drupal for everybody by adding a nginx config under 

/data/disk/o1/config/server_master/nginx/post.d/nginx_vhost_include_custom.conf

with an override for the nobots location

```
location @nobots {
  ###
  ### Return 404 on special PHP URLs to avoid revealing version used,
  ### even indirectly. See also: https://drupal.org/node/2116387
  ###
  if ( $args ~* "=PHP[A-Z0-9]{8}-" ) {
    return 404;
  }
  rewrite ^/(.*)$  /index.php?q=$1 last;
}
```

**Comment by omega8cc** [comment]
That is correct, you can easily override any named location like this. Nginx will not allow to duplicate any other regex/literal etc location, though.

**Comment by attiks** [comment]
In case anybody wants a copy-paste:

Create a file /data/disk/o1/config/server_master/nginx/post.d/nginx_force_include_amp.conf

```
location @nobots {
  if ( $query_string ~ "^amp$" ) {
    rewrite ^/(.*)$  /index.php?q=$1 last;
  }

  if ($is_bot) {
    return 301 $scheme://$host$request_uri;
  }
  ###
  ### Return 404 on special PHP URLs to avoid revealing version used,
  ### even indirectly. See also: https://drupal.org/node/2116387
  ###
  if ( $args ~* "=PHP[A-Z0-9]{8}-" ) {
    return 404;
  }
  rewrite ^/(.*)$  /index.php?q=$1 last;
}
```

Test using ``` curl -A "'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)')" https://example.com/node/1?amp ```

**Comment by omega8cc** [comment]
This has been fixed in https://github.com/omega8cc/provision/commit/0cc5929d9aff69edbc73be33dd74b2faa760f76d

See also: https://www.drupal.org/node/2820747
