### ISSUE TITLE
502 Errors on All Octopus sites after Octopus Upgrade to 3.0.2

### ISSUE THREAD

**Issue by kepford** [omega8cc/boa#949]
A look at the NGinx log /var/log/nginx/error.log shows that it is full of errors like this.

```2016/05/22 16:39:05 [crit] 14103#0: *479 connect() to unix:/var/run/o1.fpm.socket failed (2: No such file or directory) while connecting to upstream, client: 192.241.231.192, server: example.com, request: "GET /jobs.json HTTP/1.0", upstream: "fastcgi://unix:/var/run/o1.fpm.socket:", host: "example.com"```

This affects D6 and D7 sites

Any ideas or direction is appreciated.

[boa info](https://gist.githubusercontent.com/kepford/5530a8e1421259ea648ff0b67c1811fe/raw/60c331aa5b30ad4dc1b8ef845a64960ddf1d4bb7/boa%2520info)
Host: Digital Ocean

**Comment by memtkmcc** [comment]
Please run update with:

`cd;rm -f BOA.sh*;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`

Then switch PHP-FPM version in `/data/disk/o1/static/control/fpm.info` to some other installed version (or to `5.2` if you have only single version installed) to force socket update.

This should help, I think, no matter what caused the problem.

**Comment by kepford** [comment]
Update, looked at the `.o1.octopus.cnf` file and noticed that php-fpm was set to PHP 5.5 and I changed it to 5.6. Then did a force upgrade on o1 and the 502s are gone. 

Thanks @memtkmcc. I think your suggestion was basically getting to the same result?

**Comment by kepford** [comment]
Closing, but I'm still curious about how this happened. A PHP upgrade went bad?

**Comment by memtkmcc** [comment]
It could be a regression we have introduced in head for multi-fpm mode, which could affect instances which for some reason didn't update all wrappers via `BOA.sh.txt`, but I have just added forced mode for this update, so it should work for everybody, unless someone disabled these auto-updates with `_SKYNET_MODE=OFF`

**Comment by memtkmcc** [comment]
We should still try to reproduce this, I think, and close only if it is really either fixed or if we can't reproduce.

**Comment by omega8cc** [comment]
I couldn't reproduce this with `BOA-3.0.2`, but I could reproduce something else: #946 

We should release `BOA-3.1.0` this week, and it will fix those random issues.
