### ISSUE TITLE
Skynet upgrades for limited shell configuration

### ISSUE THREAD

**Issue by nitinsareen** [omega8cc/boa#950]
Skynet updates are switched on my server. Everytime they run or even if I trigger a manual major upgrade all (almost) scripts and configuration files under /var/xdrago are upgraded. Some of them like lshell.conf contains changes that are required by my team gets overwritten and I have to re-do them again.
Any kind suggestions to preserve such changes for configuration files atleast?

Thanks

**Comment by omega8cc** [comment]
There is an option to do what you want: `_CUSTOM_CONFIG_LSHELL=YES` -- see:  https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L80

**Comment by nitinsareen** [comment]
Thanks for your response, this apparently was known from your docs. And it was set to YES already. Looks like something that is supposed to check this value is skipping it. Attaching my .barracuda.cnf for your reference.

[https://gist.github.com/nitinsareen/52fbd1930cdd0f3087fdf299da6cbc1c](url)

Thanks again

**Comment by omega8cc** [comment]
Ah, so it sounds like a bug then.
