### ISSUE TITLE
Something is stuck after BOA upgrade to 3.0.2

### ISSUE THREAD

**Issue by Naurisr** [omega8cc/boa#951]
It looks that after upgrade some services are not running:
1. I have FTP in _XTRAS_LIST, but after server restart FTP is not accessible. I need to run `/usr/local/sbin/pure-ftpd -A -b -c50 -B -C8 -d -E -fftp -H -I15 -lunix -L10000:8 -m4 -p30000:50000 -s -U113:002 -u100 -w -i -Ostats:/var/log/pureftpd.log -k99 -Z -0 -Y2` from commandline 
2. Emails are not sent, trying to send them from commandline (`mail -s "Hello World" mymail@example.com`). Command hangs and after Ctrl+C, it says "(Interrupt -- one more to kill letter)"
3. Aegir's task queue stopped running and it looks that cron is not running too.

All the sites hosted on the server are up and running.
I've tested upgrade path on server clone before, and there where no such problems.
BOA is upgraded from 2.3.8 though 2.4.9. In 2.4.9. I haven't noticed these problems.
Hosted on linode.
Any ideas?

[boa info](https://gist.githubusercontent.com/Naurisr/c5671feb76ce2a661c53b550a07e1052/raw/19a0fb65d071b9a83b6dc2dbfaf53fb6a4df8d18/gistfile1.txt)

Thanks

**Comment by EdNett** [comment]
I have the same problems after upgrading to 3.1.0-dev as of 12 PM UTC Monday May 23rd.
I ran the daily cron as suggested after, rebooted the server, etc. I am going to run the full barracuda up-head and octopus up-head force again to see what effect this has.
Octopus tasks not running, no service pure-ftpd found. This is php 5.6 on wheezy.

How can I help troubleshoot this?

**Comment by EdNett** [comment]
My boa info more is here:
https://gist.github.com/EdNett/652a06918d9ae9275c4a84ad92c7a953

**Comment by omega8cc** [comment]
Hmmm.. we are running BOA-3.1.0-dec (barracuda) plus BOA-3.0.2 (octopus) in production, and we don't experience any such issues. We couldn't reproduce this, either.

Please check if system cron runs?

**Comment by Naurisr** [comment]
Running `/etc/init.d/cron status` from commandline says:
[ ok ] cron is running.

How to check if it is really running?

**Comment by omega8cc** [comment]
Please try:

`$ service clean-boa-env start`

This should remove pid files which could pause tasks queue, etc.

**Comment by Naurisr** [comment]
`service clean-boa-env start`
Starting clean-boa-env: clean-boa-env 1 nothing to do.
clean-boa-env 2 nothing to do.
clean-boa-env 3 nothing to do.
clean-boa-env 4 nothing to do.

**Comment by Naurisr** [comment]
3rd issue (Aegir's task queue stopped running) is now fixed by manually removing from crontab two lines that was added from /var/xdrago/cron/custom.txt as suggested [here](https://github.com/omega8cc/boa/blob/a63d7610e5e1a977fb8808d52afa2be9585db52b/CHANGELOG.txt#L5871) 
I'll check later what is wrong now with these lines. In BOA 2.3.8 these lines where in crontab.

But I'm still not able to send mails and most likely FTP access problem is not fixed too (I have not restarted the server yet to confirm)

**Comment by Naurisr** [comment]
2nd issue also is fixed. Now I can use different command to send emails via commandline
`$ echo "something" | mailx -s "subject" recipient@somewhere.com`
Emails from sites are working too

**Comment by EdNett** [comment]
Doing a complete barracuda and octopus up-head did not resolve the problem of no tasks running.  I see a BAAZAR installation error, and I am looking into that, and will report it separately if there is a real issue - I don't think it could cause the tasks to stop running.  I don't have any custom CRON; I found one possible reason for this in a log file called /var/last-fpmcheck-y-problem that has this verify task - which appears to be the first one after the static platform on the octopus verified. (Can we uninstall just the overlay module? in the aegir frontend?)
https://o1.server1.example.com/hosting/task/2825renderoverlay

**Comment by EdNett** [comment]
Is it correct that in the hostmaster GUI frontend that no-one (neither the root , nor the admin, nor any of the aegir roles) has the permissions to create, edit or delete any tasks? These are the settings I see - do they need to be modified?

Thank you.

**Comment by Naurisr** [comment]
@EdNett it looks you have posted the content of /var/xdrago/cron/crontabs/root .
Try to run from commandline `crontab -e`.
I have added those previously removed lines back to `crontab -e` without change and cron are still running so I just had to resave crontab so that gets reloaded.

**Comment by EdNett** [comment]
I keep on doing the barracuda up-head followed by the octopus up-head, and now I see a pattern: after the octopus upgrade one (1) task - a verify hostmaster platform task - is done - one and only one task.  These tasks are from my initial barracuda up-stable and octopus up-stable 10 hours ago. Does this help to troubleshoot this issue, OR do you recommend a FULL REINSTALL?

**Comment by omega8cc** [comment]
Can you check if you have `/data/disk/o1/.tmp/cache/download` directory by any chance?

**Comment by EdNett** [comment]
Yes, that directory is there - it is empty

**Comment by omega8cc** [comment]
OK, so we have introduced too strict check in head: https://github.com/omega8cc/boa/commit/11e18b7188034157394e7e17f6f17ff873786818

Please delete this empty directory to unlock the tasks queue.

**Comment by omega8cc** [comment]
Amazing, so `.tmp/cache/download` gets recreated by Drush on every task run, so we can't use it as an indicator of running makefile build via frontend to fix #943

**Comment by omega8cc** [comment]
That said, the problem affected only octopus instances running `BOA-3.1.0-dev`

Thanks all for your feedback!

**Comment by omega8cc** [comment]
As for the initial report related to `BOA-3.0.2`  -- we couldn't reproduce any of the reported issues, so not sure if there is anything we should follow up here.

**Comment by EdNett** [comment]
deleting that empty folder repeatedly is working for me - I'll up-head again if it's fixed.
Thanks

**Comment by Naurisr** [comment]
It looks that pure-ftpd is started with a little delay. So all issues are sloved for me too.
Thanks!!!

**Comment by omega8cc** [comment]
Thank you.
