### ISSUE TITLE
sed: cannot rename

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#957]
I'm upgrading my Octopus instances with `octopus up-stable all both log` (after doing `octopus up-2.4 all both log` first), and in the octopus-up logs I see the following:

> BOA [17:55:13] ==> UPGRADE A: Aegir Satellite Instance upgrade completed
> BOA [17:55:23] ==> UPGRADE C: Shared platforms code v.006 (new) will be created
> BOA [17:55:25] ==> DISTRO: Drupal 6.38.2 D.006 installed
> BOA [17:55:25] ==> DISTRO: Drupal 6.38.2 S.006 installed
> BOA [17:55:25] ==> DISTRO: Drupal 6.38.2 P.006 installed
> BOA [17:55:25] ==> DISTRO: Drupal 7.43.2 D.006 installed
> BOA [17:55:25] ==> DISTRO: Drupal 7.43.2 S.006 installed
> BOA [17:55:25] ==> DISTRO: Drupal 7.43.2 P.006 installed
> BOA [17:55:25] ==> UPGRADE C: Running Platforms Verify tasks, please wait...
> BOA [17:55:29] ==> UPGRADE A: Platforms installed
> BOA [17:55:29] ==> UPGRADE A: Cleaning up various dot files, please wait...
> BOA [17:55:29] ==> Final post-upgrade cleaning, one moment...
> BOA [17:55:55] ==> BYE!
> cp: cannot remove `/home/arjan.web/.drush/php.ini': Operation not permitted
> sed: cannot rename /home/arjan.web/.drush/sed1LgBh2: Operation not permitted
> sed: cannot rename /home/arjan.web/.drush/sedt2RC45: Operation not permitted
> sed: cannot rename /home/arjan.web/.drush/sedSfc363: Operation not permitted
> sed: cannot rename /home/arjan.web/.drush/seda1iIS7: Operation not permitted
> sed: cannot rename /home/arjan.web/.drush/sedeWC3q8: Operation not permitted
> chown: changing ownership of `/home/arjan.web/.drush/php.ini': Operation not permitted
> chmod: changing permissions of `/home/arjan.web/.drush/php.ini': Operation not permitted

Afterwards the platforms contain only the `all` and `default` folders, none of the core symlinks. I thought I'd seen such an issue fixed already before? (Posting system info next)

**Comment by ar-jan** [comment]
Hm, I'd been using _AUTO_UP_WEEKLY for a long time (without manual full upgrades). Could it be that I'd needed to do `octopus up-stable` some time ago, would that explain it?

**Comment by omega8cc** [comment]
`_AUTO_UP_WEEKLY` does only system upgrades and should be used only to automate upgrades *between releases*. Once there is new release, you should always run complete upgrade, as explained in the `docs/UPGRADE.txt`

**Comment by omega8cc** [comment]
For reference:

https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L107
https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt

**Comment by ar-jan** [comment]
Yeah I figured that, but the octopus instances have now been updated as well so everything's at the latest version. Maybe it will work again when there's new platform code to install? In the mean time, I generally use custom platforms anyway.

**Comment by omega8cc** [comment]
The errors are rather weird, so something went wrong in the process. I would suggest to run:

`$ bash /var/xdrago/daily.sh`

and then again:

`$ octopus up-stable all force`
