### ISSUE TITLE
hosting_git breaks Hostmaster upgrade, if enabled

### ISSUE THREAD

**Issue by thebennos** [omega8cc/boa#961]
Drush command terminated abnormally due to an unrecoverable error.                                                                                                  [error]
Error: Cannot redeclare drush_provision_pre_provision_git_pull() (previously declared in
/data/disk/o1/aegir/distro/001/profiles/hostmaster/modules/aegir/hosting_git/drush/provision_git.drush.inc:131) in
/data/disk/o1/aegir/distro/002/profiles/hostmaster/modules/aegir/hosting_git/pull/drush/provision_git_pull.drush.inc, line 27 [148.84 sec, 11.06 MB]
The external command could not be executed due to an application error. [148.85 sec, 11.06 MB]                                                                      [error]
Checking DB credentials yielded error: Unable to find a matching SQL Class. Drush cannot find your database connection details. [148.86 sec, 11.69 MB]                  [debug]
could not bootstrap drupal after updatedb [148.86 sec, 11.68 MB]                                                                                                       [notice]
Returned from hook drush_provision_drupal_post_provision_deploy [148.86 sec, 11.68 MB]        

Upgraded barracuda to 3.1 without problems. 
Update from octopus o1 failed with error above.

**Comment by thebennos** [comment]
Looks like this is related to it. 
https://www.drupal.org/node/2729891

I disable the git features and try again an upgrade of octopus instance.

**Comment by omega8cc** [comment]
Yes, it is a known issue with `hosting_git` contrib module.

**Comment by thebennos** [comment]
Upgrade works if hosting_git is disabled before octopus upgrade. 

We should document it, for other users of hosting_git.

**Comment by omega8cc** [comment]
It is still experimental module, and even hotfix introduced in Aegir broke something else (upgrade path from Aegir 2.x, and it is already "documented" in the issue you have linked.

**Comment by omega8cc** [comment]
Note that we automatically document all known issues by adding them to special milestone linked in the release notes: https://github.com/omega8cc/boa/blob/3.x.x-dev/CHANGELOG.txt#L388

**Comment by omega8cc** [comment]
That's an old issue, fixed a long time ago, so closing.
