### ISSUE TITLE
Error in browser after enabling le for o1.myservername

### ISSUE THREAD

**Issue by mabo1972** [omega8cc/boa#962]
After i enabled LE for o1.myservername i get "ERR_TOO_MANY_REDIRECTS" in all browsers for the o1.myservername site. I've cleared the browser cache and cookies with no effect.

In the edit tab of the o1.myservername site i selected "required" under encryption.
I use LE in live mode.

How can i get  access to my control panel?

System BOA 3.1.0 Debian Jessie

BOA info

hostmaster:~# boa info

Aegir on Debian/jessie x86_64
  VPS XEN
  CPU 4
  RAM 12043
  XTR _XTRAS_LIST="CSF CHV FTP FMG SR4 IMG "
  MFX _MODULES_FIX=NO
  PFX _PERMISSIONS_FIX=NO
  DBS _DB_SERIES=5.5
  DNS _DNS_SETUP_TEST=YES
  PKG _EXTRA_PACKAGES=
  NGX nginx/1.11.0
  SSL 1.0.1t
  CRL 7.49.0
  SSH 7.2p2

**Comment by omega8cc** [comment]
Please don't enable SSL for hostmaster like this, it is not intended to be enabled within hostmaster, exactly to avoid this type of problems. Now you need to revert this directly in the hostmaster database, drush alias and its vhost to remove SSL from there. We should add a big red warning in the release notes, perhaps?

**Comment by omega8cc** [comment]
Additional warning added to inline messages, SSL how-to, and in the changelog.

**Comment by omega8cc** [comment]
Now the shortest possible route is:

1. Edit hostmaster vhost to remove forced redirect and SSL stuff
2. Edit hostmaster node in Aegir and disable SSL there.
