### ISSUE TITLE
Update docs/SOLR.txt to match currently supported procedures

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#963]
When I manually add  a core in `/opt/solr4` and in the configuration file `/opt/solr4/solr.xml` the core directory and the entry in the solr.xml is deleted at the next day.

Why? Is there a cron task which removes entities in solr.xml?

Here is my [config](https://gist.github.com/luxio/37edf7d45ccdfb142232ea95b2b8b153)

**Comment by omega8cc** [comment]
You should never add anything manually there. Instead follow the docs: https://omega8.cc/how-to-add-update-or-delete-solr-4-cores-336

**Comment by luxio** [comment]
Thanks for the reply. 

I have followed instead these [docs](https://github.com/omega8cc/boa/blob/master/docs/SOLR.txt).

~~~
To add more cores, you need to:

1. Create a copy of example core directory:
   cp -ar /opt/solr3/core0 /opt/solr3/core11

2. Add this new core in the solr.xml file:
   /opt/solr1/solr.xml (for Solr 1.x with Jetty 7)
   /opt/solr3/solr.xml (for Solr 3.x with Jetty 8)
   /opt/solr4/solr.xml (for Solr 4.x with Jetty 8 or 9 on Precise/Wheezy)
~~~

Is `solr.xml` being updated although  `MODULES_FIX` ist set to `NO`?

**Comment by omega8cc** [comment]
We should replace this outdated docs entry with https://omega8.cc/how-to-add-update-or-delete-solr-4-cores-336, to avoid confusion, I guess.

**Comment by omega8cc** [comment]
It is not expected to work (the old how-to) since we have automated Solr cores management.
