### ISSUE TITLE
\Drupal::moduleHandler()->moduleExists() don't return correct value

### ISSUE THREAD

**Issue by jfayad** [omega8cc/boa#966]
When I try to install a custom installation profile which contains a module that requires libraries and check for them in a hook_requirements I can't get the installation to succeed.

What happens is that in hook_requirements() the following if is being called to assess in which folder to look for the libraries: if (\Drupal::moduleHandler()->moduleExists('libraries')) {

Unfortunately, this if returns false and thus the libraries are being fetched from the root libraries folder...

I initially though it was a module installation order issue, but even after I added the libraries module to the module's dependencies list (just to test) I still face the same issue.

To reproduce it's very easy, create a profile that depends on the file_browser module, let drush download the libraries into the libraries folder of your profile and try to install...

For info a drush_log("libraries exist " . \Drupal::moduleHandler()->moduleExists('libraries')); will return 
"libraries exist " with no return for the concatenated \Drupal::moduleHandler()->moduleExists('libraries') call

I'm not really sure if this is directly related to boa but since I can only test from a boa instance I need at least some info on how can I get more information to debug what's going on. (Or maybe someone here knows this as a common issue ?)

Thanks,

**Comment by omega8cc** [comment]
It doesn't seem BOA related.
