### ISSUE TITLE
backboa can't find python2 on Squeeze

### ISSUE THREAD

**Issue by kepford** [omega8cc/boa#967]
I noticed that the data included in my daily backup email changed recently. Not sure if this was after an update but the issue appears to be that either Python2 is not properly installed or it's just not in the path for the backup script. When I run different backboa commands I get output like this 

```
root@server1:~# backboa list
9231: old priority 10, new priority 19
/usr/bin/env: python2: No such file or directory
```

* If I type `python2` in the shell I get `-bash: python2: command not found`. 
* `which python2` returns nothing
* `whereis python2` returns
```
python2: /usr/bin/python2.6-config /usr/bin/python2.6 /etc/python2.6 /usr/lib/python2.5 /usr/lib/python2.6 /usr/lib/python2.4 /usr/lib64/python2.5 /usr/lib64/python2.6 /usr/lib64/python2.4 /usr/local/lib/python2.6 /usr/include/python2.6
```

This seems to be a failed upgrade to python 2.7. If that is the case I'm not sure what to do to resolve this. Should I manually reinstall Python. Typically doing such things is a bad idea with BOA servers in my experience. 

Host: Digital Ocean
[BOA info](https://gist.githubusercontent.com/kepford/4d00075ef7af457a31fee21569f248a5/raw/f6faefe54da4a0275f876592b9747700b03693ee/gistfile1.txt)

**Comment by omega8cc** [comment]
Ah, it is because you are still using Squeeze, which is no longer supported: https://github.com/omega8cc/boa/blob/BOA-3.1.0/README.txt#L86

>> * Debian 6 Squeeze (limited to upgrade to Wheezy with _SQUEEZE_TO_WHEEZY=YES)

Please use this procedure (just with `_SQUEEZE_TO_WHEEZY=YES`, of course): https://github.com/omega8cc/boa/blob/BOA-3.1.0/CHANGELOG.txt#L292

**Comment by kepford** [comment]
Thanks. 

btw this isn't funny <img src="https://dl.dropboxusercontent.com/s/xlqcelpwv2tao19/2016-06-01%20at%206.11%20PM.png" alt="" width="" height="" border="0" />

**Comment by kepford** [comment]
I followed the instructions 
https://github.com/omega8cc/boa/blob/BOA-3.1.0/CHANGELOG.txt#L292
and for some reason I'm still on Squeeze. Going to give it another try.

**Comment by kepford** [comment]
Maybe this is why it didn't work. I added ` _WHEEZY_TO_JESSIE=YES` first before running any upgrade commands. The instructions actually call for this after upgrading boa and octopus. I just assumed I didn't need to upgrade either of those since I had recently ran the upgrades.

**Comment by kepford** [comment]
The upgrade appears to be hanging.

```
BOA [03:10:37] ==> Aegir on server1.example.com Debian/squeeze x86_64 PHP 5.6

BOA [03:10:45] ==> WARN: Squeeze to Wheezy upgrade will start in 60 seconds...
BOA [03:10:45] ==> WARN: Now pray it will work... or hit ctrl-c to stop now!
BOA [03:11:46] ==> WARN: Too late! Squeeze to Wheezy upgrade in progress...
BOA [03:11:46] ==> HINT: Run tail -f /var/backups/barracuda-upgrade-160602-0310.log
BOA [03:11:46] ==> HINT: in another terminal window to watch details
|BOA [03:14:15] ==> INFO: Upgrading Nginx...
curl: /usr/lib/libcurl.so.4: no version information available (required by curl)
/curl: /usr/lib/libcurl.so.4: no version information available (required by curl)
```

**Comment by omega8cc** [comment]
Yeah, as you can see, there is a reason why we have added that frightening warning.

But wait, you have added `_WHEEZY_TO_JESSIE=YES` ???

You are on Squeeze... so you should add `_SQUEEZE_TO_WHEEZY=YES` instead.

The problem is that once you wait too long (after Squeeze LTS is no longer maintained) it can be even not possible to upgrade at all. We can do literally nothing if Debian shuts down the archives for no longer maintained LTS version.

Your only safe option is then install new system from scratch and migrate everything with `xboa`.

But before trying that, try to determine what exactly happens, look what the verbose log tells you. Maybe it could be possible to install/fix some broken package manually etc.

Have you run the suggested `tail -f /var/backups/barracuda-upgrade-160602-0310.log` in another terminal window?

**Comment by kepford** [comment]
>Your only safe option is then install new system from scratch and migrate everything with xboa

This is what I'm doing tonight. Already have the new system set up.

Long version, I added `_SQUEEZE_TO_WHEEZY=YES` but watching the verbose log showed me that many packages were returning 404s. Thanks for the tips.

**Comment by omega8cc** [comment]
I hope it worked!

**Comment by kepford** [comment]
Sorry, forgot to close the look. It worked perfectly. The migration system is very useful. Had zero issues with it.

**Comment by omega8cc** [comment]
Great! Thanks for the update.
