### ISSUE TITLE
can't add new users to octopus

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#971]
boa 3-1-0 stable, php 5.6, and I'm unable to add any type of new user to Octopus gui. I have enabled LE (the right way - by removing the control file) for the o1 instance. the error on-screen reads:
The website encountered an unexpected error. Please try again later.
Boa info more: 
https://gist.github.com/EdNett/7e4e11ceeee7e1346ca8eb8a4f374969

In fact this doesn' work (adding new users) on any of our octopus instances (all 3.1.0), including those without LE encryption enabled, on the octopus hostmaster site.

**Comment by omega8cc** [comment]
It's a known problem: #926
