### ISSUE TITLE
Drush is broken (/opt/php53/bin/php /var/aegir/drush/drush.php help failed) error during barracuda up-stable

### ISSUE THREAD

**Issue by breuter-zq** [omega8cc/boa#973]
When the script is trying to upgrade the Aegir Master instance it is throwing the error.  Below is the log from the script up to that point:
BOA [06:45:43] ==> INFO: Running Aegir Master Instance upgrade
BOA [06:45:44] ==> INFO: Syncing provision backend db_passwd...
BOA [06:45:48] ==> INFO: Running hosting-dispatch (1/3)...
BOA [06:45:55] ==> INFO: Running hosting-dispatch (2/3)...
BOA [06:46:02] ==> INFO: Running hosting-dispatch (3/3)...
BOA [06:46:03] ==> INFO: Syncing hostmaster frontend db_passwd...
BOA [06:46:03] ==> INFO: Downloading hostmaster modules...
BOA [06:46:17] ==> INFO: Testing previous install...
BOA [06:46:17] ==> INFO: Testing previous install...
BOA [06:46:17] ==> INFO: OPS, zombie found, moving it to backups...
BOA [06:46:18] ==> INFO: Testing previous install again after removing zombie...
BOA [06:46:19] ==> INFO: Testing previous install again...
BOA [06:46:19] ==> INFO: OPS, another zombie found, moving it to backups...
BOA [06:46:20] ==> INFO: Testing previous install again after removing second zombie...
BOA [06:46:21] ==> INFO: Test OK, we can proceed with Hostmaster upgrade
BOA [06:46:21] ==> INFO: Moving old directories
BOA [06:46:21] ==> INFO: Downloading drush micro-8-24-04-2016...
BOA [06:46:25] ==> INFO: Installing Aegir Provision backend...
BOA [06:46:25] ==> INFO: Downloading Drush and Provision extensions...
BOA [06:46:27] ==> FATAL ERROR: Drush is broken (/opt/php53/bin/php /var/aegir/drush/drush.php help failed)

**Comment by omega8cc** [comment]
Please link the output of `boa info more` command.

Also, can you find the hostmaster site in any of existing platforms: `/var/aegir/host_master/*/sites/` ?

If yes, please run this command twice: `syncpass fix aegir`

Then please enable debug mode: set `_DEBUG_MODE=YES` in `/root/.barracuda.cnf` and then try the upgrade again.

**Comment by breuter-zq** [comment]
Attached are the log files, please advise still seeing same issue after running the 'syncpass fix aegir
'
[barracuda up-stable with debug.txt](https://github.com/omega8cc/boa/files/303023/barracuda.up-stable.with.debug.txt)
[boa info more.txt](https://github.com/omega8cc/boa/files/302996/boa.info.more.txt)

**Comment by omega8cc** [comment]
Drush 8 in BOA stable requires newer PHP version. 5.3 will not work.

Please switch both cli and fpm to 5.6 before trying again.

In `/root/.barracuda.cnf`you should have (at minimum)

```
_PHP_CLI_VERSION=5.6
_PHP_FPM_VERSION=5.6
_PHP_SINGLE_INSTALL=
_PHP_MULTI_INSTALL="5.6 5.3"
```
