### ISSUE TITLE
How to permanently disable CSF

### ISSUE THREAD

**Issue by sTb1337** [omega8cc/boa#975]
Hello everyone,

how can i disable csf permanetly?

I changed the /etc/csf/csf.conf but the deamon and csf were restarted.

**Comment by omega8cc** [comment]
Three steps:

1. Set `TESTING = "1"` in `/etc/csf/csf.conf`
2. Set `_CUSTOM_CONFIG_CSF=YES` in `/root/.barracuda.cnf`
3. Run `csf -q`

**Comment by sTb1337** [comment]
Thanks a lot.

**Comment by DominicBoettger** [comment]
After doing this csf is still consuming a lot of cpu. Is it possible to completely disable the service?

**Comment by omega8cc** [comment]
It is a very, very bad idea to disable the firewall! Don't do that, ever. You should rather determine what really causes problems. It is not CSF, it is most probably either your virtualization system or hardware issue.
