### ISSUE TITLE
[xdrago] improve scan_nginx docs

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#977]
Hi omega8cc team. I've been having a few issues with scan_nginx blocking regular traffic for high activity IP addresses recently. On one site a user is developing, there are around 100 images on the home page. So if they load the page more than twice in succession, they are likely to get blocked (especially on a lower traffic server). My perl reading skills are sub-par and I'm having a hard time understanding ways around it.

- Does `_NGINX_DOS_LIMIT` define the maximum number of requests per 300 lines of nginx access.log before someone gets blocked?
- If so, does any value for `_NGINX_DOS_LIMIT` greater than 300 effectively disable scan_nginx?
- Do the comments `### don't block logged in users` refer to IPs connected via SSH?
- Apart from `/root/.local.IP.list` how can a specific IP address be ignored by scan_nginx?

Thanks!

**Comment by omega8cc** [comment]
It is designed for production level systems, when there is enough IP-noise in the access log.

Normally only dynamic requests are logged, but when you happen to visit a single page with 150 images derivatives which don't exist yet, so all those requests go to Drupal at the same time, these requests will be logged and counted.

If you will set `_NGINX_DOS_LIMIT` to anything higher than `300`, you will effectively disable this protection.

To whitelist any IP permanently, add this line in `/etc/csf/csf.allow` and then restart firewall with `csf -q`

`tcp|in|d=80|s=11.11.11.11`

Anyone can whitelist his/her IP address on the fly, if they have active SSH session with the BOA server.

It is also explained at: https://omega8.cc/how-firewall-works-is-my-ip-blocked-121

**Comment by pricejn2** [comment]
Great, thank you for clarifying.
