### ISSUE TITLE
SOLR core ist not beeing added to solr.xml

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#978]
I have enabled the Solr integration (search_api_solr). The Solr core and `solr.php` has been created, but the core was not added to `/opt/solr4/solr.xml`. 

Any ideas why it was not added?

Here is my [config](https://gist.github.com/luxio/a1c861ca362556c4e152d374d84fa62b)

**Comment by omega8cc** [comment]
We can't reproduce this. Please check details in relevant logs in `/var/xdrago/log/daily/`
