### ISSUE TITLE
New Relic: Servers Processes only displaying nrsysmond and nothing else

### ISSUE THREAD

**Issue by radimklaska** [omega8cc/boa#979]
As title says, In New Relic monitoring I see only nrsysmond process running on the server and no other processes.

* boa info: https://gist.github.com/anonymous/b3ad47bc2b7f8746f503fcf384caa812
* _NEWRELIC_KEY="xxx" is set in .barracuda.cnf
* /root/.enable.newrelic.sysmond.cnf exists
* /data/disk/o1/static/control/newrelic.info exists and contains same newrelic key

Reading this
> "...monitoring with per Octopus instance... ...feature will disable global New Relic monitoring by deactivating server-level license key, so it can safely auto-enable or auto-disable it every 5 minutes, but per Octopus instanc..."

makes me think I have to choose between reporting on server level and application level. (and it seems I'm not only one: https://github.com/omega8cc/boa/issues/428#issuecomment-57093009 )

Removing /data/disk/*/static/control/newrelic.info resulted in no application data reported + still no info on running processes.

From New Relic forum ( https://discuss.newrelic.com/t/servers-processes-only-displaying-nrsysmond-and-nothing-else/8256/1 ): 
> generally this issue manifests when running in an enhanced security mode, possibly using tools such as grsecurity, SELinux "strict" or AppArmor. Because the New Relic system monitor runs as an unprivileged process, it is unable to access information about other processes when the/proc/‹pid›/ directory is inaccessible.

In a perfect scenario I (as a server admin) should be able to see server level data + application data in my New Relic account (my key in .barracuda.cnf and /data/disk/o1/static/control/newrelic.info) and other clients should see only their application data in their New Relic accounts ( client specific key in /data/disk/*/static/control/newrelic.info )

Is that possible?

**Comment by omega8cc** [comment]
It is not possible to restrict this, so octopus level user/licence will see only its app monitoring. If you enable nrsysmond, they will see system level reporting provided by nrsysmond, too, which is not desirable, because octopus instance should live in its virtual chroot and know almost nothing about the system it is running on.

At least, this is how it worked before. We have no tested nrsysmond for a long time, I think.

**Comment by radimklaska** [comment]
Can we introduce some switch to allow server level data (everyone / no one)?

**Comment by omega8cc** [comment]
Can you run this command and let us know if this fixes the problem?

`$ usermod -aG users newrelic`

**Comment by radimklaska** [comment]
Nothing changed after running the command.

**Comment by omega8cc** [comment]
Have you tried to restart `nrsysmond` after adding its user to the `users` group? It should work, because it allows this user to escape `_STRICT_BIN_PERMISSIONS=YES`

**Comment by radimklaska** [comment]
Yes, I restarted both `newrelic-daemon` and `newrelic-sysmond`. 

Seems like New Relic renamed their service and BOA is using old name? `newrelic-sysmond` -> `nrsysmond`

**Comment by memtkmcc** [comment]
I have tried to reproduce this with BOA head, and I can't. It just works, without any extra tricks.

<img width="2048" alt="screenshot 2016-06-15 23 54 45" src="https://cloud.githubusercontent.com/assets/10896523/16098794/1b6a594c-3355-11e6-9d3c-4dfc5a8744dc.png">

<img width="2048" alt="screenshot 2016-06-15 23 55 13" src="https://cloud.githubusercontent.com/assets/10896523/16098801/3213566c-3355-11e6-8619-a82287537c94.png">

<img width="2048" alt="screenshot 2016-06-15 23 55 42" src="https://cloud.githubusercontent.com/assets/10896523/16098810/424bdb80-3355-11e6-8412-8ac3d5048f78.png">

**Comment by memtkmcc** [comment]
BTW: `newrelic-sysmond` is a service name, while `nrsysmond` is the name of the daemon running. There were no changes for years, and it works.

**Comment by memtkmcc** [comment]
It works like it always worked: https://github.com/omega8cc/boa/issues/428#issuecomment-57101757
