### ISSUE TITLE
Update Mongo PHP extension to 1.6.14

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#981]
Currently BOA generates 1.6.13 mongo PHP driver. Just wanted to update that latest mongo PHP driver version is 1.6.14 (compatible up to PHP 5.6), all versions listed here - https://pecl.php.net/package/mongo.

Too bad that http://drupal.org/project/mongodb doesn't support newest mongodb PHP extension, which supports PHP 7. Related issue comment: https://www.drupal.org/node/2669050#comment-11240823. Would love to test PHP7 with mongodb in excellent multi-FPM mode :)

If monogdb drupal module will support latest PHP extension, then we should add mongodb PHP driver for PHP 7. Would love to hear your thoughts about that. Cheers.

**Comment by MetaBureau** [comment]
Mongo for PHP 5.6 would be a great enhancement. Clearly at this stage the mongodb module is not going to offer support for PHP 6 or 7 any time soon.

Question: Does the current implementation of Mongo in Barracuda support PHP 5.5? /boa/blob/master/docs/cnf/barracuda.cnf Says Installs MONGODB for PHP **5.3-only** when YES

**Comment by omega8cc** [comment]
https://pecl.php.net/package/mongo is deprecated, and we should use https://pecl.php.net/package/mongodb instead, which supports PHP 7, but drops support for PHP 5.3

**Comment by omega8cc** [comment]
Hmm.. OK, so we can't do this until the Drupal module is ready.

**Comment by omega8cc** [comment]
Which is not going to happen, if I read these comments correctly.

**Comment by MetaBureau** [comment]
https://www.drupal.org/project/mongodb 7.x-1.x-dev requires PHP 5.3 or higher so theoretically should be okay with 5.5 or 5.6. 
I'll raise a issue with them and report back.

**Comment by omega8cc** [comment]
Yeah, but [this comment](https://www.drupal.org/node/2669050#comment-11240823) suggests, that supporting new MongoDB driver is not going to happen (at least not for D7 and D6), so everything we can do is to update the legacy driver to 1.6.14, so at least it will work for up to PHP 5.6

**Comment by omega8cc** [comment]
@MetaBureau BOA already supported Mongo driver for all versions < 7.0 since BOA-3.0.0, only the docs still listed the old 5.3-only mode.
