### ISSUE TITLE
Create new site task fails on static 8.1.2 platform

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#982]
On BOA-3.1.0 I can add a static D8 platform successfully. However, when I create sites on that platform, the task fails with the following error:
```
Find command files for phase 3 (max=)	
- Drush command terminated abnormally due to an unrecoverable error.
Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/disk/o1/static/8.1.2/core/includes/common.inc, line 1273
- The external command could not be executed due to an application error.	
- Checking DB credentials yielded error: Unable to find a matching SQL Class. Drush cannot find your database connection details.
```
I have verified that the octopus instance is running Drush 8

I probably missed some important step in the Docs or the issue queue. Please enlighten me!

**Comment by LunkRat** [comment]
Thank you @omega8cc, you reminded me that I had downgraded my PHP versions to 5.4 during a troubleshooting process. I upgraded them back to 5.6 and I can now create sites in my 8.1.2 platform. 

Thank you for the help, as always. 

```
Mon Jun 6 13:02:44 CDT 2016 / Debian.wheezy x86_64 / Aegir BOA-3.1.0 / Octopus BOA-3.1.0 / FPM 5.4 / CLI 5.4
Wed Jun 15 14:45:16 CDT 2016 / Debian.wheezy x86_64 / Aegir BOA-3.1.0 / Octopus BOA-3.1.0 / FPM 5.6 / CLI 5.6
```

**Comment by omega8cc** [comment]
OK, thanks for the update.
