### ISSUE TITLE
Alternatives to Chive?

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#983]
The Chive project is no longer actively developed / maintained since July 2014, plus some UI sections are starting to be obsolete in new browser versions. 
SQL query window is a "_PITA_" to work with, the textarea autoscale doesn't work properly for large queries

So maybe is a good time to search for a better alternative to replace it.

I haven't tested much, but [Adminer](https://www.adminer.org/) looks like a good candidate. FLOSS,  only 1 php file, multilingual, and actively maintained project

Any thoughts?

**Comment by Pls** [comment]
I agree that we should replace Chive, also had problems with SQL queries.

[SQL Buddy](http://sqlbuddy.com/) looks promising too, my vote is on this one. 

Maby someone knows better alternatives?

**Comment by omega8cc** [comment]
We should remove both Chive and SQL Buddy and use Adminer instead. Thanks for the hints!

**Comment by omega8cc** [comment]
This integration also looks interesting: https://www.drupal.org/project/adminer

**Comment by ixiam** [comment]
Yes, definitely interesting. 
Adminer could be based on an ad-hoc Drupal platform like hostmaster, and maybe the implementation would be even easier than Chive is.

**Comment by omega8cc** [comment]
Should we use some alt design, perhaps? http://www.adminer.org/#extras

**Comment by bserem** [comment]
Nette (the second one) looks pretty easy on the eyes.
