### ISSUE TITLE
Remote drush aliases failing with: sed: -e expression #1, char 0: no previous regular expression

### ISSUE THREAD

**Issue by dsnopek** [omega8cc/boa#984]
When I setup a remote alias to a site in BOA, I always get this error:

```
sed: -e expression #1, char 0: no previous regular expression
```

Running drush with `-vvv` I can see the command it's running is:

```
env COLUMNS=160 drush  --verbose --uri=site.o1.example.com --root=/data/disk/o1/static/platform  core-status
```

If I run that just by SSH'ing in as the `o1.ftp` user, I get the same error. If I remove the `env COLUMNS=160` part, the command runs correctly!

This is on an account on omega8.cc - if this would be better as a support request there, I can do that. Thanks!

**Comment by omega8cc** [comment]
Is that account running latest BOA-3.1.0 ?

I think we have seen this before fixing some known issues in the lshell, so prefixes like `COLUMNS=160` are stripped properly, so they don't break drush commands executed remotely:

https://github.com/omega8cc/boa/blob/master/aegir/helpers/websh.sh.txt#L7

By the way, it doesn't make any sense to force anything via `env` because it will be ignored anyway, since in lshell we map `env` to `true` to silence possible warnings etc.

**Comment by dsnopek** [comment]
Thanks for the speedy response!

> Is that account running latest BOA-3.1.0 ?

Since it's running on omega8.cc (as opposed to a local server), I don't know. How do I check?

> By the way, it doesn't make any sense to force anything via env because it will be ignored anyway, since in lshell we map env to true to silence possible warnings etc.

Hm, yeah, if I knew how to prevent drush from putting that in the command, I would! :-)

**Comment by omega8cc** [comment]
We host some instances which still run on BOA-2.4.9 because they still depend on PHP 5.3

If you know the instance Aegir URL, it is easy to determine, because BOA-3.x has D7 based Hostmaster, while 2.4.x has D6 based.

Yeah, Drush does this weird thing, and we can't prevent it, obviously, when Drush is run remotely, so we are trying to strip this prefix on the fly. It worked in our tests for a long time.

What is the Drush version you are running remotely?

**Comment by omega8cc** [comment]
Ah, I just reproduced this in the debug mode, so I know why this happens. Fix is coming soon!

**Comment by dsnopek** [comment]
Ah, it's BOA 2.4.9 then.

Locally, I'm running Drush 7 - I'm not sure remotely, because all of a sudden I can't SSH in. Hopefully, I wasn't trying too frequently and got blocked. :-/

Thanks for looking into this!

**Comment by omega8cc** [comment]
If you need to whitelist your trusted remote IP, please open a ticket at https://omega8.cc/support

**Comment by omega8cc** [comment]
It works again:

```
o1.ftp:~$ env COLUMNS=85 drush --version
 Drush Version   :  8.1.0
```

The hot-fix will be applied on all instances within the next 45 minutes.

If it will not work for you on some instance, please let us know the instance Aegir URL via https://omega8.cc/support

Thanks for the report!

**Comment by dsnopek** [comment]
Hm. This appears to be partially working.

When I SSH into the server, and run it locally, it works. However, if I run exactly the command that Drush is running (which executes the command as an argument to `ssh`) then I still get the same sed error.

Here's the command drush is running (got it by using the `-vvv` option):

```
ssh -o PasswordAuthentication=no o1.ftp@o1.example.com 'env COLUMNS=160 drush  --verbose --uri=site.o1.example.com --root=/data/disk/o1/static/platform  core-status 2>&1' 2>&1
```

If I remove the `env COLUMNS=160` then it works.

I'm not sure why SSH'ing in and running the command would be different than putting the command as an argument to `ssh`?

Thanks again for your help!

**Comment by omega8cc** [comment]
Have you tried to follow this how-to? https://omega8.cc/how-to-use-drush-aliases-321

It works in my test, and allows to avoid all those issues with running drush remotely.
```
$ ssh o1.ftp@o1.quad.tt.o8.io 'drush @d7.o1.quad.tt.o8.io status'
 Drupal version                :  7.42
 Site URI                      :  d7.o1.quad.tt.o8.io
 Database driver               :  mysql
 Database hostname             :  localhost
 Database port                 :  3306
 Database username             :  d7o1quadtto8io
 Database name                 :  d7o1quadtto8io
 Drupal bootstrap              :  Successful
 Drupal user                   :
 Default theme                 :  bartik
 Administration theme          :  seven
 PHP executable                :  /opt/php55/bin/php
 PHP configuration             :  /home/o1.ftp/.drush/php.ini
 PHP OS                        :  Linux
 Drush script                  :  /opt/tools/drush/8/drush/drush.php
 Drush version                 :  8.1.0
 Drush temp directory          :  /home/o1.ftp/.tmp
 Drush configuration           :  /data/disk/o1/distro/003/drupal-7.42.1-prod/s
                                  ites/d7.o1.quad.tt.o8.io/drushrc.php
 Drush alias files             :  /home/o1.ftp/.drush/d7.o1.quad.tt.o8.io.alias
                                  .drushrc.php
 Install profile               :  standard
 Drupal root                   :  /data/disk/o1/distro/003/drupal-7.42.1-prod
 Drupal Settings File          :  sites/d7.o1.quad.tt.o8.io/settings.php
 Site path                     :  sites/d7.o1.quad.tt.o8.io
 File directory path           :  sites/d7.o1.quad.tt.o8.io/files
 Private file directory path   :  sites/d7.o1.quad.tt.o8.io/private/files
 Temporary file directory      :  sites/d7.o1.quad.tt.o8.io/private/temp
 path
```

Can you show us the exact command you are running remotely, so we could try to reproduce this?

**Comment by omega8cc** [comment]
But, indeed, it still doesn't work as expected over SSH:

```
$ ssh o1.ftp@o1.quad.tt.o8.io 'env COLUMNS=85 drush --version'
sed: -e expression #1, char 0: no previous regular expression
```

**Comment by dsnopek** [comment]
Yeah, that's exactly what I'm seeing. It works if I SSH in and run it, but not passing the same command as an argument to `ssh`

**Comment by omega8cc** [comment]
One sec.

**Comment by omega8cc** [comment]
OK, now really fixed (on the hosted BOA you are connecting to it will be fixed in the next 5 minutes):

```
$ ssh o1.ftp@o1.quad.tt.o8.io 'env COLUMNS=85 drush --version'
_R_M is -c true COLUMNS=85 drush
_ARR is --version
HOME is /home/o1.ftp
TEMP is /home/o1.ftp/.tmp
USER is o1.ftp
_ALL is -c true COLUMNS=85 drush --version
_ARGS is drush --version
_LTD_GID is users www-data lshellg
_LTD_QQQ is
_LTD_UID is o1.ftp
_Y_USR is o1
0 is /bin/sh
1 is -c
2 is true COLUMNS=85 drush --version
3 is
4 is
5 is
6 is
7 is
8 is
9 is
HOME is /home/o1.ftp
TEMP is /home/o1.ftp/.tmp
USER is o1.ftp
_ALL is /opt/tools/drush/8/drush/drush.launcher --version
_ARGS is /opt/tools/drush/8/drush/drush.launcher
_LTD_GID is users www-data lshellg
_LTD_QQQ is
_LTD_UID is o1.ftp
_Y_USR is o1
0 is /bin/sh
1 is /opt/tools/drush/8/drush/drush.launcher
2 is --version
3 is
4 is
5 is
6 is
7 is
8 is
9 is
 Drush Version   :  8.1.0
```

**Comment by dsnopek** [comment]
It's working great now, thanks! :-)

@omega8cc++

**Comment by omega8cc** [comment]
Thanks! :)
