### ISSUE TITLE
_WHEEZY_TO_JESSIE aborted due to "dpkg --audit"

### ISSUE THREAD

**Issue by Naurisr** [omega8cc/boa#986]
Tried to upgrade with _WHEEZY_TO_JESSIE , but did not succeed. Got a message

> BOA [16:49:44] ==> ALRT! I can not continue until dpkg --audit is clean
> BOA [16:49:44] ==> ALRT! The following packages are missing the md5sums control file in the
database, they need to be reinstalled:
>  default-jre          Standard Java or Java compatible Runtime
> BOA [16:49:44] ==> ALRT! Aborting installer NOW!

Any idea how to fix this?
[boa info](https://gist.githubusercontent.com/Naurisr/c5070e34686a83b5e46cc1f694777b2d/raw/28c210b2208597a306b3705686369673afa9d306/gistfile1.txt)

**Comment by Naurisr** [comment]
I ran `apt-get install --reinstall default-jre` and now `dpkg --audit` is empty (as expected). I hope this will not break something.
Will try _WHEEZY_TO_JESSIE some other day

**Comment by omega8cc** [comment]
We should probably reinstall this on the fly, if needed.
