### ISSUE TITLE
Cannot redeclare _ds_extras_menu_alter()

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#987]
BOA 3.1.0
OS: Debian Wheezy

Likely an upstream issue, or just a support request for a detail I'm missing.

When trying to clone a site that has a site-specific version of the display suite ds_extras module enabled, I am getting the following error:

```
Drush command terminated abnormally due to an unrecoverable error.
Error: Cannot redeclare _ds_extras_menu_alter() (previously declared in /data/disk/o2/distro/004/commerce-1.37-7.38.1/sites/example.com/modules/ds/modules/ds_extras/includes/ds_extras.registry.inc:11) in /data/disk/o2/distro/004/commerce-1.37-7.38.1/sites/bkup-0620.example.com/modules/ds/modules/ds_extras/includes/ds_extras.registry.inc, line 32
```

Thank you!

**Comment by omega8cc** [comment]
Please check recipe  number 4 at https://omega8.cc/the-best-recipes-for-disaster-139

**Comment by pricejn2** [comment]
Very well. Thanks for the quick response.
