### ISSUE TITLE
/var/backups/BARRACUDA.sh.txt: line 1: 404:: command not found

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#990]
I'm trying to upgrade a server from BOA 3.1.0 to the new 3.1.1, but I get this:

    root@boa:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
    STATUS: Skynet Agent is Active, OK!
    STATUS: You can add the _SKYNET_MODE=OFF line in
    STATUS: /root/.barracuda.cnf to disable me, if needed.
    BOA Meta Installer setup completed
    Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
    Bye
    root@boa:~# barracuda up-stable
    /var/backups/BARRACUDA.sh.txt: line 1: 404:: command not found
    BARRACUDA upgrade completed
    Bye

There's maybe a small chance this is related to not having done full BOA updates for some time previously (see #957). But currently the barracuda and all octopus instances are 3.1.0 and otherwise everything works.

boa info [here](https://gist.github.com/ar-jan/01389cbc8ebca551e43ba2e06d4b8188). Any ideas?

**Comment by ar-jan** [comment]
And, not sure if `/var/backups/BARRACUDA.sh.txt` is the expected location, but that file does not exist on my system.

**Comment by omega8cc** [comment]
Please wait 5 minutes, apparently not all our mirrors synced everything after release.

**Comment by omega8cc** [comment]
It should work now:

```
root@quad:~# barracuda up-stable

BOA [22:23:33] ==> Skynet Agent v.BOA-3.1.1 welcomes you aboard!

BOA [22:23:36] ==> INFO: UPGRADE

BOA [22:23:41] ==> VIRT: This system is supported: Linux VServer guest

BOA [22:23:41] ==> Aegir on quad.tt.o8.io Debian/wheezy x86_64 PHP 5.6

BOA [22:23:45] ==> INFO: Installing extra Drush versions...
BOA [22:23:50] ==> INFO: Running system packages update...
BOA [22:24:24] ==> INFO: Upgrading required libraries and tools...
BOA [22:24:50] ==> INFO: Running aptitude full-upgrade...
BOA [22:25:11] ==> INFO: Installing MySecureShell master-20-03-2015...
```

**Comment by ar-jan** [comment]
Guess I was too fast then, the upgrade is running now ;)
