### ISSUE TITLE
LE ssl not working on one server

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#992]
Hi,

I installed a fresh vanilla Debian Jessie VPS (Digital Ocean) and installed BOA 3.10.
Although LE ssl is working ok on all of our other servers, on this paricular one it doesn't.

Not only for the sites, but also for hostmaster, it says when inspecting the ceriticate for hostmaster:
There are issues with the site's certificate chain (net::ERR_CERT_AUTHORITY_INVALID).

After enabling encryption for a site, the task verify log says:
[hosting_le] The LE Certificate attempted creation failed in /data/disk/o1/tools/le/certs/schleifenbauer.eu	
[hosting_le] Make sure that all aliases have valid DNS names pointing to your instance IP address.	
[hosting_le] The alternative is to disable SAN mode for this site with empty ctrl file: /data/disk/o1/static/control/ssl-no-san-schleifenbauer.eu.info

There are no differences in DNS settings, no aliasses other than www active.

One strange this that could be related: Ever since installing BOA I get a notification about system integrity check:
Time:     Thu Jun 23 10:08:55 2016 +0200

The following list of files have FAILED the md5sum comparison test. This means that the file has been changed in some way. This could be a result of an OS update or application upgrade. If the change is unexpected it should be investigated:

/usr/bin/MySecureShell: FAILED
/usr/bin/git-old: FAILED
/usr/bin/mysecureshell: FAILED
/usr/bin/nginx: FAILED
/usr/bin/php: FAILED
/usr/bin/php-cli: FAILED
/usr/bin/php-old: FAILED
/usr/bin/redis-benchmark: FAILED
/usr/bin/redis-check-aof: FAILED
/usr/bin/redis-check-rdb: FAILED
/usr/bin/redis-cli: FAILED
/usr/bin/redis-sentinel: FAILED
/usr/bin/redis-server: FAILED
/usr/sbin/nginx: FAILED
/usr/sbin/nginx.old: FAILED
/usr/sbin/sshd: FAILED
/bin/sh: FAILED
/usr/local/sbin/pure-ftpd: FAILED

**Comment by omega8cc** [comment]
Have you run barracuda upgrade after system reboot on this VPS?

**Comment by omega8cc** [comment]
You should not receive these LFD notices, unless you have run system (barracuda) upgrade. That said, you should only receive such email once after the upgrade. If it works differently, the VPS looks seriously broken...

**Comment by florisvanwoudenberg** [comment]
I now see that the errors and the not working LE is due to not following the installation instructions. I did the installation the way I always did, before BOA 3.0. But I see that the reboot and barracuda up-stable system after the initial installation is absolutely necessary otherwise the system will be broken.
On the new installation everything works fine, thank you very very much for the LE integration, supercool!!
Maybe a tip: Let users now that the reboot and barracuda up-stable has to be done at the end for the installation script, so they see it in the terminal.

**Comment by omega8cc** [comment]
It is required on Jessie, and it is displayed prominently at the top in your terminal. (It can't be displayed in the end of installation, because the procedure applies to barracuda and not octopus). Example:

```
BOA [06:42:18] ==> Skynet Agent v.BOA-3.0.0-dev welcomes you aboard!

BOA [06:42:21] ==> INFO: NORMAL INIT
BOA [06:42:21] ==> INFO: Public Setup Mode Active
BOA [06:42:21] ==> INFO: Creating your /root/.barracuda.cnf config file

BOA [06:42:30] ==> Aegir on server.ocean.o8.io Debian/jessie x86_64 PHP 5.6

BOA [06:42:30] ==> INFO: Installing some basic tools now, please wait...
BOA [06:42:51] ==> INFO: Installing sysvinit on Debian jessie...

BOA [06:42:55] ==> NOTE: Please reboot and run barracuda upgrade
BOA [06:42:55] ==> NOTE: when boa will complete initial installation
BOA [06:42:55] ==> NOTE: to cleanly remove not used systemd packages!

BOA [06:43:12] ==> INFO: Installing more basic tools now, please wait...
BOA [06:43:35] ==> INFO: DNS test: OK
```
