### ISSUE TITLE
entitycache related PDOException due to missing variable after daily cleanup / cc

### ISSUE THREAD

**Issue by gandhiano** [omega8cc/boa#994]
Since a few weeks, I'm having problems with the BOA (3.0.2) provided entitycache and an Open Atrium installation. Nearly every morning (maybe after the cleanup), the site becomes unavailable (throws uknown error), and following error is visible on dblog:

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS , revision.uid AS revision_uid FROM node base INNER JOIN node_revision revis' at line 1: SELECT base.*, revision.*, revision.timestamp AS revision_timestamp, base. AS , revision.uid AS revision_uid FROM {node} base INNER JOIN {node_revision} revision ON revision.vid = base.vid WHERE (base.nid IN (:db_condition_placeholder_0)) ; Array ( [:db_condition_placeholder_0] => 0 ) in EntityCacheControllerHelper::entityCacheLoad() (line 142 of /data/all/008/o_contrib_seven/entitycache/includes/entitycache.entitycachecontrollerhelper.inc).
```

The problem is obviously on the entry base. AS, which is missing one or two properly set variables.

running drush rr usually fixes the issue; running drush cc all afterwards often (but not always) brings the issue again.

I found that the errors start when the daily cleanup routine runs - and on dblog a Redis connection error is also the first one to appear:

```
RedisException: read error on connection in Redis->hGetAll() (line 48 of /data/all/000/modules/redis_edge/lib/Redis/Cache/PhpRedis.php).
```

**Comment by omega8cc** [comment]
Can you please upgrade to latest stable (both barracuda and octopus) and migrate the site to the latest OA version? We don't support/debug old stable.
