### ISSUE TITLE
Tasks not running after up-stable 3.1.1 of both barracuda and octopus

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#995]
Tasks are not running after up-stable 3.1.1 of both barracuda and octopus. I restarted the server, ran the o1 instance cron manually  and cleared its cache manually and tasks are not being processed. It has been over 90 min since the upgrade.  We use "fast1" as the name of the octopus instance.

Boa info more (plus a few terminal errors that were returned immediately after the successful octopus upgrade - at the very top of the gist) is here:
https://gist.github.com/EdNett/22e2a7358f5d3ea240cfc7677bf70211

**Comment by EdNett** [comment]
I may have solved this problem - this vps boa reports to be 91% disk space full, so I cannot run the 
bash /var/xdrago/manage_ltd_users.sh  and daily cron. I am removing backups so that I can do this, and will close this issue if that is the problem

**Comment by omega8cc** [comment]
Definitely, with disk usage > 90% many scheduled cron tasks (and any further barracuda / octopus upgrades) will stop working. It is by design.
