### ISSUE TITLE
wheezy to jessie upgrade fails

### ISSUE THREAD

**Issue by cwaone** [omega8cc/boa#996]
i try to make the wheezy to jessie upgrade, on our testserver it works fine, on our production environment (same server ESXI configuration) the upgrade start taking a long time at the step |BOA [23:23:38] ==> INFO: Upgrading Nginx... The logfile in the other shell window shows: Get:415 http://httpredir.debian.org/debian/ jessie/main postfix-pcre amd64 2.11.3-1 [278 kB]
Get:416 http://httpredir.debian.org/debian/ jessie/main postfix amd64 2.11.3-1 [1371 kB]
Fetched 216 MB in 11s (19.0 MB/s)
how long should this step usually take? No error is reported till now and we follow this manual: https://omega8.cc/boa-310-full-edition-380

i checked the nginx error log which shows up: 2016/06/23 23:59:10 [error] 24570#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) whiile request ....

**Comment by omega8cc** [comment]
Please follow guidelines: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by cwaone** [comment]
i am sorry, first time issuer ... here is the boa info output: https://gist.github.com/cwaone/c345efb380a53ba6a6b29ba4e18c30a2  and the boa info more: https://gist.github.com/cwaone/4f895005eef93338735583df74e72f9e

**Comment by omega8cc** [comment]
OK, so again, tt looks like you have dns/firewall/connectivity issues on your system. What is the result of the commands list below?

`dig drupal.org`
`ping 8.8.8.8`
`cat /etc/resolv.conf`
`ls -la /etc/resolv.conf`

**Comment by cwaone** [comment]
her is the output of dig drupal.org: https://gist.github.com/cwaone/4f1885eafcfba8888e32a85855d9f6ae

ping 8.8.8.8: https://gist.github.com/cwaone/be9768a45e867a064b221ab839fa3454

cat /etc/resolv.conf: https://gist.github.com/cwaone/a2e08eaf637d41d17c219c4c6133f6ed

ls -la /etc/resolv.conf: https://gist.github.com/cwaone/c65bd7f18130d9952222f70b449c5ace

**Comment by omega8cc** [comment]
Thanks. Can you try to remove the `search ischwenk.com` line from `/etc/resolvconf/run/resolv.conf` and then try to run manually:

`$ aptitude update`
`$ aptitude full-upgrade`

...and see what happens?

Not sure why that line is there, or if it's the source of the problem, but it shouldn't be there.

**Comment by cwaone** [comment]
Thank you very much for your info, i did the changes as you recommended, but the update stopped again at the same line as before. 

I also went back  to a earlier snapshot on our test system (which includes the same line (search i-schwenk.com in this case) and the jessie upgrade went well without errors, both,  with or without the line in the resolv.conf. 

Unfotunately, it seems that this is not the problem.

**Comment by omega8cc** [comment]
Sounds really weird then. Please set `_LOCAL_DEBIAN_MIRROR="ftp.debian.org"` and then try to run normal upgrade first (remove the `_WHEEZY_TO_JESSIE` line, if exists). If that works, try with `_WHEEZY_TO_JESSIE=YES` again, but keep `_LOCAL_DEBIAN_MIRROR="ftp.debian.org"`
