### ISSUE TITLE
Problems with cron and Aegir's task queue after every upgrade

### ISSUE THREAD

**Issue by Naurisr** [omega8cc/boa#998]
Every time I upgrade Barracuda I have problems with cron and Aegir's task queue. They do not run. Finally I somehow make it work, by running following commands in random order repeatedly
`rm -r /data/disk/o1/.tmp/cache/download`
`crontab -e` and save
`service clean-boa-env start`
`bash /var/xdrago/manage_ltd_users.sh`
`bash /var/xdrago/daily.sh`
`reboot`
Actually I'm not sure if these commands or something else makes it work
`/etc/init.d/cron status` says "cron is running"
`df` says disk usage is 86%
Usually Aegir's task queue starts running first and later (may take even >24h) also cron for sites starts, but it does not starts automatically.
Maybe that is not related, but I think I have changed servers time on this server after I installed Barracuda a long ago.

[boa info](https://gist.githubusercontent.com/Naurisr/bab325d913a9e634fda703891f6cf221/raw/8b2013b4bdf177caaf1feac29eabd2e45fc9fb46/gistfile1.txt)

**Comment by Naurisr** [comment]
Actually cron is not running on one of three octopus instaces.

**Comment by Naurisr** [comment]
runing `drush @hostmaster hosting-cron` gives error in this octopus instance
> $ drush @hostmaster hosting-cron
drush: Cannot acquire lock on cron queue.
Drush command terminated abnormally due to an unrecoverable error.

**Comment by omega8cc** [comment]
Have you run reboot after upgrade to Jessie?

**Comment by Naurisr** [comment]
Yes. I'm sure i rebooted the server.
I ran `barracuda up-stable` then `reboot` and then `barracuda up-stable system`

**Comment by omega8cc** [comment]
Then no idea. The 'Cannot acquire lock on cron queue' error seems to suggest that hostmaster backend doesn't work as expected, and you may need to unlock the queue (delete the semaphore) directly in the hostmaster database:

`$ su -s /bin/bash - o1`
`$ drush @hm vdel hosting_queue_cron_running -y`

Then try:
`$ drush @hm hosting-dispatch -d`

**Comment by me336408** [comment]
i having issues as well none of the verify tasks have completed since i upgraded to the last stable version 3.0.1 to 3.1.1

**Comment by Naurisr** [comment]
Now about 24h after upgrade I see that cron tasks are running. When looking in watchdog log it seams it started in about 22-23h after upgrade and I didn't do anything on the server for last 10hours. So it heals himself somehow.

**Comment by Naurisr** [comment]
Just ran `up-stable` again after adding PHP 5.6 to barracuda.cnf as suggested in #999 [here](https://github.com/omega8cc/boa/issues/999#issuecomment-228535122) and both task queues and crons stopped working. Right now they do not work in all three octopus instances.

**Comment by Naurisr** [comment]
Now task queues are running on all octopus instances and cron is running in two of three instances.
What I did I again tried to run all the commands (including) mentioned in my first comment.
I'm afraid I will have to wait 24h for crons to start running on this last octopus instance.
Maybe I will try to install new octopus instance and migrate everything from 'broken' octopus to it

**Comment by me336408** [comment]
i want to migrate as well but first i need backups created for all sites. but since the tasks are nor running i don't have backup either
can i force the backup tasks to run?

**Comment by Naurisr** [comment]
I took a look again at sites and see that now cron runs. There was a ~1 hour gap after up-stable when cron did not run
![image](https://cloud.githubusercontent.com/assets/279771/16359985/5c631448-3b52-11e6-838e-704031030b20.png)

Maybe this is something related to timezones and daylight savings time

**Comment by omega8cc** [comment]
@Naurisr -- We couldn't reproduce the problem anywhere. Please touch this ctrl file and let us know if this helped:

`/data/disk/o1/static/control/clear-drush-cache.info`

**Comment by omega8cc** [comment]
@Naurisr -- Also, consider enabling Skynet updates for testing and set `_SKYNET_MODE=ON`

**Comment by omega8cc** [comment]
By the way, why `_DNS_SETUP_TEST=NO` ?

**Comment by me336408** [comment]
moved a site to a new boa installation. but i see that cron is not running again on the new boa either
i installed the latest boa stable 3.1.1

**Comment by bserem** [comment]
What BOA version did you have before?

**Comment by me336408** [comment]
this is a fresh installation of boa 3.1.1

**Comment by bserem** [comment]
yeah, what did you have before that? When you had no problems, v3.x, v2.4 ?

**Comment by me336408** [comment]
3.0.1 was working just fine prior to updating

**Comment by omega8cc** [comment]
@me336408 Please open separate issue and provide required report, as explained in the guidelines.

**Comment by omega8cc** [comment]
@Naurisr -- If the problem is that no tasks are run (not just site's cron), then it is probably a side effect of the protection we have introduced in BOA-3.1.0

It was explained in the BOA-3.1.0 release notes: https://omega8.cc/boa-310-full-edition-380

Also available in the ~/static/control/README.txt in every instance main account.

It is also posted here: https://github.com/omega8cc/boa/blob/master/aegir/tools/system/conf/control-readme.txt#L74

```
###
### Support for forced Drush cache clear in the Aegir backend
###
### ~/static/control/clear-drush-cache.info
###
### Octopus instance will pause all scheduled tasks in its queue, if it will
### detect a platform build from the makefile in progress, to make sure
### that no other running task could break the build.
###
### This is great, until there will be a broken build, and Drush will fail
### to clean up all leftovers from its .tmp/cache directory, which in turn
### will pause all tasks in the queue for up to 24-48 hours, until the cache
### directory will be automatically purged by running daily cleanup tasks,
### designed to not touch anything not old enough (24 hours at minimum)
### to not break any running builds.
###
### If you need to unlock the tasks queue by forcefully removing everything
### from the Aegir backend Drush cache, you can create an empty control file:
### ~/static/control/clear-drush-cache.info
###
### You have to delete this file once the tasks queue is unlocked again,
### or it will forcefully clear Drupal cache on every run, which in turn will
### break all future attempts to build the platform from makefile via Aegir
### control panel interface.
###
```

**Comment by Naurisr** [comment]
@omega8cc I can't test it as currently everything works. I will try to up-stable again in the weekend just to test if you are right and then I'll report about results.

**Comment by omega8cc** [comment]
Also, the cleanup is not aggressive enough, apparently, and we have fixed this in head: https://github.com/omega8cc/boa/commit/5724e897d0b7195b1e0eafbd876126021b4ff20b

**Comment by omega8cc** [comment]
Feel free to reopen if the issue will persist after applying the patch to your `/var/xdrago/run-o1`
